/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/dram\a53_io_controller_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029b90
 * symbol: isVaSramIoController_BootConfigurationValid
 * prototype: bool isVaSramIoController_BootConfigurationValid(uint64_t vaSramIoController_BootConfiguration)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::IOC::IoController::isVaSramIoController_BootConfigurationValid
               (uint64_t vaSramIoController_BootConfiguration)

{
  return (IoController_BootConfiguration *)vaSramIoController_BootConfiguration ==
         &core0_boot_config;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029ba4
 * symbol: isIoController_BootConfigurationValid
 * prototype: bool isIoController_BootConfigurationValid(uint64_t vaSramIoController_BootConfiguration)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::IOC::IoController::isIoController_BootConfigurationValid
               (uint64_t vaSramIoController_BootConfiguration)

{
  return (IoController_BootConfiguration *)vaSramIoController_BootConfiguration ==
         &core0_boot_config;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029bb8
 * symbol: setVaSramIoController_BootConfiguration
 * prototype: bool setVaSramIoController_BootConfiguration(IoController * this, uint64_t vaSramIoController_BootConfiguration)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool setVaSramIoController_BootConfiguration(IoController * this,
   uint64_t vaSramIoController_BootConfiguration) */

bool __thiscall
A53::IOC::IoController::setVaSramIoController_BootConfiguration
          (IoController *this,uint64_t vaSramIoController_BootConfiguration)

{
  if ((IoController_BootConfiguration *)vaSramIoController_BootConfiguration == &core0_boot_config)
  {
    (this->m_runtime_config).field_0.field_0.m_vaSramA53Controller_BootConfiguration = 0x4e0c000;
  }
  return (IoController_BootConfiguration *)vaSramIoController_BootConfiguration ==
         &core0_boot_config;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602ac7c
 * symbol: ioControllerHaltAndError
 * prototype: void ioControllerHaltAndError(IoController * this, IoControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void ioControllerHaltAndError(IoController * this,
   IoControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError) */

void __thiscall
A53::IOC::IoController::ioControllerHaltAndError
          (IoController *this,IoControllerSysErrorCode eErrorCode,uint64_t addressError,
          uint16_t pasidError)

{
  ControllerRings local_78;
  
  local_78.m_pRingsState = &this->m_rings_state;
  local_78.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_78.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_78.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_78.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_78.m_paInputRingHead = this->m_aInputRingHead;
  local_78.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_78.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_78.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_78.m_paOutputRing = this->m_aOutputRing;
  local_78.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_78.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_78.m_paInputRing = this->m_aInputRing;
  local_78.m_pContext_HandleControllerRingsEvent = this;
  controllerHaltAndError(&local_78,eErrorCode,addressError,pasidError);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602c5f8
 * symbol: canPushInterrupt
 * prototype: bool canPushInterrupt(IoController * this)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool canPushInterrupt(IoController * this) */

bool __thiscall A53::IOC::IoController::canPushInterrupt(IoController *this)

{
  if (((this->m_rings_state).field_0.asU64[3] >> 0x34 & 1) == 0) {
    return false;
  }
  return 1 << (ulong)(this->m_aOutputRing[0].field_0.field_0.m_numCacheElemsLog2 & 0x1f) !=
         (uint)this->m_aOutputRing[0].field_0.field_0.m_countDmaNotComplete;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602c624
 * symbol: pushInterruptCommandError
 * prototype: bool pushInterruptCommandError(IoController * this, IoControllerCommandRing eRing, uint16_t ringLocationError, uint16_t ibCommandIdError, uint32_t pid, uint32_t opCode, ErrorCodeType eErrorCodeType, uint8_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 208
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool pushInterruptCommandError(IoController * this,
   IoControllerCommandRing eRing, uint16_t ringLocationError, uint16_t ibCommandIdError, uint32_t
   pid, uint32_t opCode, ErrorCodeType eErrorCodeType, uint8_t eErrorCode, uint64_t addressError,
   uint16_t pasidError) */

bool __thiscall
A53::IOC::IoController::pushInterruptCommandError
          (IoController *this,IoControllerCommandRing eRing,uint16_t ringLocationError,
          uint16_t ibCommandIdError,uint32_t pid,uint32_t opCode,ErrorCodeType eErrorCodeType,
          uint8_t eErrorCode,uint64_t addressError,uint16_t pasidError)

{
  bool bVar1;
  ulong uVar2;
  ulong uVar3;
  uint64_t in_stack_00000000;
  uint16_t in_stack_00000008;
  
  bVar1 = canPushInterrupt(this);
  if (bVar1) {
    interruptContextRing_pushCommandError
              (this->m_aOutputRing,eRing,ringLocationError,ibCommandIdError,pid,opCode,
               eErrorCodeType,(uint)eErrorCode,in_stack_00000000,in_stack_00000008);
    uVar2 = (this->m_InterruptContextRingTail).field_0.asU64[0];
    if (((uint)uVar2 >> 0x1e & 1) == 0) {
      bVar1 = true;
    }
    else {
      uVar3 = (this->m_rings_state).field_0.asU64[3];
      bVar1 = true;
      (this->m_InterruptContextRingTail).field_0.asU64[0] = uVar2 & 0xffffffffbfffffff;
      (this->m_rings_state).field_0.asU64[3] =
           uVar3 & 0xffff000000000000 |
           uVar3 & 0xfffffffffff | (ulong)((uint)(uVar3 >> 0x2c) & 0xe | 1) << 0x2c;
    }
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602ced4
 * symbol: discardHeadCommand
 * prototype: bool discardHeadCommand(ZcnVqState * this, uint32_t * out_discard_start_lo, uint32_t * out_discard_end_lo)
 * body addresses: 168
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool discardHeadCommand(ZcnVqState * this, uint32_t *
   out_discard_start_lo, uint32_t * out_discard_end_lo) */

bool __thiscall
A53::ZcnVqState::discardHeadCommand
          (ZcnVqState *this,uint32_t *out_discard_start_lo,uint32_t *out_discard_end_lo)

{
  uint uVar1;
  byte bVar2;
  bool bVar3;
  uint uVar4;
  ulong uVar5;
  long lVar6;
  
  uVar5 = (ulong)(this->m_submit).m_iVq;
  if ((*(uint *)(&DAT_022e1000 + uVar5 * 0x1000) >> 1 & 1) == 0) {
    bVar3 = false;
  }
  else {
    lVar6 = uVar5 * 0x1000;
    this->m_tail_lo = *(uint32_t *)(&DAT_022e1004 + lVar6);
    uVar4 = *(uint *)(&DAT_022e1008 + lVar6);
    this->m_head_lo = uVar4 & 0x7fffffff;
    *out_discard_start_lo = uVar4 & 0x7fffffff;
    uVar4 = this->m_head_lo;
    if (uVar4 != this->m_tail_lo) {
      uVar1 = (this->m_submit).m_maskVqdPointer;
      bVar2 = (this->m_submit).m_iVq;
      uVar4 = uVar1 & uVar4 + 0x20 | uVar4 & (uVar1 ^ 0xffffffff);
      this->m_head_lo = uVar4;
      *(uint *)(&DAT_022e1008 + (ulong)bVar2 * 0x1000) = uVar4 & 0x7fffffff;
      uVar4 = this->m_head_lo;
    }
    *out_discard_end_lo = uVar4;
    bVar3 = true;
    (this->m_submit).m_numCommandsAvailable =
         (uint16_t)
         (((this->m_head_lo - (this->m_submit).m_offsetPut) + 0x1fffe0 &
          (this->m_submit).m_maskVqdPointer) >> 5);
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602cfb4
 * symbol: getZcnCommandSource
 * prototype: bool getZcnCommandSource(IoController * this, ZcnQueue eZcnQueue, uint32_t iZcnCmd, DeviceOpSource * out_deviceOpSource)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool getZcnCommandSource(IoController * this, ZcnQueue eZcnQueue,
   uint32_t iZcnCmd, DeviceOpSource * out_deviceOpSource) */

bool __thiscall
A53::IOC::IoController::getZcnCommandSource
          (IoController *this,ZcnQueue eZcnQueue,uint32_t iZcnCmd,DeviceOpSource *out_deviceOpSource
          )

{
  bool bVar1;
  
  bVar1 = zcnDriverGetCommandInfo
                    (&this->m_zcn,(ulong)this->m_vaSramCacheBase,eZcnQueue,iZcnCmd,
                     (ZcnCommandInfo *)out_deviceOpSource);
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602cfe0
 * symbol: clearZcnCommandSource
 * prototype: bool clearZcnCommandSource(IoController * this, ZcnQueue eZcnQueue, uint32_t iZcnCmdStart, uint32_t numZcnCmds)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool clearZcnCommandSource(IoController * this, ZcnQueue eZcnQueue,
   uint32_t iZcnCmdStart, uint32_t numZcnCmds) */

bool __thiscall
A53::IOC::IoController::clearZcnCommandSource
          (IoController *this,ZcnQueue eZcnQueue,uint32_t iZcnCmdStart,uint32_t numZcnCmds)

{
  bool bVar1;
  
  bVar1 = zcnDriverSetCommandInfo
                    (&this->m_zcn,(ulong)this->m_vaSramCacheBase,eZcnQueue,iZcnCmdStart,numZcnCmds,0
                     ,0);
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602eb98
 * symbol: getRingLocationBackwardFromTail
 * prototype: uint16_t getRingLocationBackwardFromTail(ConstSramRingView * this, uint16_t indexBeforeTail)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getRingLocationBackwardFromTail(ConstSramRingView * this,
   uint16_t indexBeforeTail) */

uint16_t __thiscall
A53::ConstSramRingView::getRingLocationBackwardFromTail
          (ConstSramRingView *this,uint16_t indexBeforeTail)

{
  uint16_t uVar1;
  ulong uVar2;
  
  uVar2 = *(ulong *)((long)&this->field_0 + 4);
  if ((uVar2 >> 0x33 & 0x1f) != 0) {
    return ((short)(uVar2 >> 0x20) - indexBeforeTail) + (short)(uVar2 >> 0x10) &
           (short)(1 << (ulong)((uint)(uVar2 >> 0x33) & 0x1f)) - 1U;
  }
  uVar1 = getElementIndexBackwardFromTail(this,indexBeforeTail);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602ebdc
 * symbol: getRingLocationFromHead
 * prototype: uint16_t getRingLocationFromHead(ConstSramRingView * this, uint16_t indexFromHead)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getRingLocationFromHead(ConstSramRingView * this, uint16_t
   indexFromHead) */

uint16_t __thiscall
A53::ConstSramRingView::getRingLocationFromHead(ConstSramRingView *this,uint16_t indexFromHead)

{
  uint16_t uVar1;
  ulong uVar2;
  
  uVar2 = *(ulong *)((long)&this->field_0 + 4);
  if ((uVar2 >> 0x33 & 0x1f) != 0) {
    return (short)(1 << (ulong)((uint)(uVar2 >> 0x33) & 0x1f)) - 1U &
           (short)(uVar2 >> 0x10) + indexFromHead;
  }
  uVar1 = getElementIndexFromHead(this,indexFromHead);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602ec20
 * symbol: readElementFromHead<unsigned_int>
 * prototype: uint32_t readElementFromHead<unsigned_int>(ConstSramRingView * this, uint * elem, uint32_t indexFromHead)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElementFromHead<unsigned int>
   DWARF original prototype: uint32_t readElementFromHead<unsigned_int>(ConstSramRingView * this,
   uint * elem, uint32_t indexFromHead) */

uint32_t __thiscall
A53::ConstSramRingView::readElementFromHead<unsigned_int>
          (ConstSramRingView *this,uint *elem,uint32_t indexFromHead)

{
  uint16_t uVar1;
  uint32_t uVar2;
  
  uVar1 = getElementIndexFromHead(this,(uint16_t)indexFromHead);
  uVar2 = readElement<unsigned_int>(this,(uint)uVar1,elem);
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602ec54
 * symbol: getConstSramRingView_PipelineCommandData_DramPipeline_OpIssue
 * prototype: ConstSramRingView getConstSramRingView_PipelineCommandData_DramPipeline_OpIssue(IoController * this, IoDramPipeline eIoDramPipeline)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: ConstSramRingView
   getConstSramRingView_PipelineCommandData_DramPipeline_OpIssue(IoController * this, IoDramPipeline
   eIoDramPipeline) */

ConstSramRingView __thiscall
A53::IOC::IoController::getConstSramRingView_PipelineCommandData_DramPipeline_OpIssue
          (IoController *this,IoDramPipeline eIoDramPipeline)

{
  anon_union_12_2_653be89a_for_ConstSramRingView_0 aVar1;
  
  aVar1.field_0._0_12_ =
       (anon_struct_12_6_365e0882_for_anon_union_12_2_653be89a_for_ConstSramRingView_0_0)
       OutputRing::getSramRingViewOfCache<14>
                 (this->m_aOutputRing_PipelineCommandData_OpIssue + eIoDramPipeline,
                  *(uint16_t *)
                   (&DAT_000012e4 +
                   (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 2));
  return (anon_union_12_2_653be89a_for_ConstSramRingView_0)
         (anon_union_12_2_653be89a_for_ConstSramRingView_0)aVar1.field_0._0_12_;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602ec6c
 * symbol: getRingLocationTail
 * prototype: uint16_t getRingLocationTail(ConstSramRingView * this)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getRingLocationTail(ConstSramRingView * this) */

uint16_t __thiscall A53::ConstSramRingView::getRingLocationTail(ConstSramRingView *this)

{
  uint16_t uVar1;
  ulong uVar2;
  
  uVar2 = *(ulong *)((long)&this->field_0 + 4);
  if ((uVar2 >> 0x33 & 0x1f) != 0) {
    return (short)(1 << (ulong)((uint)(uVar2 >> 0x33) & 0x1f)) - 1U &
           (short)(uVar2 >> 0x20) + (short)(uVar2 >> 0x10);
  }
  uVar1 = getElementIndexTail(this);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f354
 * symbol: readElementFromHead<unsigned_short>
 * prototype: uint32_t readElementFromHead<unsigned_short>(ConstSramRingView * this, unsigned short * elem, uint32_t indexFromHead)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElementFromHead<unsigned short>
   DWARF original prototype: uint32_t readElementFromHead<unsigned_short>(ConstSramRingView * this,
   unsigned short * elem, uint32_t indexFromHead) */

uint32_t __thiscall
A53::ConstSramRingView::readElementFromHead<unsigned_short>
          (ConstSramRingView *this,unsigned_short *elem,uint32_t indexFromHead)

{
  uint16_t uVar1;
  uint32_t uVar2;
  
  uVar1 = getElementIndexFromHead(this,(uint16_t)indexFromHead);
  uVar2 = readElement<unsigned_short>(this,(uint)uVar1,elem);
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f420
 * symbol: getElementIndexBackwardFromTail
 * prototype: uint16_t getElementIndexBackwardFromTail(ConstSramRingView * this, uint16_t indexBeforeTail)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexBackwardFromTail(ConstSramRingView * this,
   uint16_t indexBeforeTail) */

uint16_t __thiscall
A53::ConstSramRingView::getElementIndexBackwardFromTail
          (ConstSramRingView *this,uint16_t indexBeforeTail)

{
  uint uVar1;
  short sVar2;
  int iVar3;
  uint uVar4;
  
  uVar4 = (this->field_0).asU32[1];
  uVar1 = ((this->field_0).asU32[2] & 0x1ffff) + (uVar4 >> 0x10);
  iVar3 = 0;
  if ((uVar4 & 0xffff) < uVar1) {
    iVar3 = (uVar4 & 0xffff) + 1;
  }
  uVar1 = uVar1 - iVar3;
  sVar2 = 0;
  if (uVar1 < indexBeforeTail) {
    sVar2 = (short)uVar4 + 1;
  }
  return ((short)uVar1 - indexBeforeTail) + sVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f44c
 * symbol: getElementIndexFromHead
 * prototype: uint16_t getElementIndexFromHead(ConstSramRingView * this, uint16_t indexFromHead)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexFromHead(ConstSramRingView * this, uint16_t
   indexFromHead) */

uint16_t __thiscall
A53::ConstSramRingView::getElementIndexFromHead(ConstSramRingView *this,uint16_t indexFromHead)

{
  uint uVar1;
  short sVar2;
  uint uVar3;
  
  uVar3 = (this->field_0).asU32[1];
  uVar1 = (uVar3 >> 0x10) + (uint)indexFromHead;
  sVar2 = 0;
  if ((uVar3 & 0xffff) < uVar1) {
    sVar2 = (short)uVar3 + 1;
  }
  return (short)uVar1 - sVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f468
 * symbol: getSramRingViewOfCache<14>
 * prototype: ConstSramRingView getSramRingViewOfCache<14>(InputRing * this)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: ConstSramRingView getSramRingViewOfCache<14>(InputRing * this) */

ConstSramRingView __thiscall A53::InputRing::getSramRingViewOfCache<14>(InputRing *this)

{
  byte bVar1;
  byte bVar2;
  ushort uVar3;
  ushort uVar4;
  undefined4 in_w1;
  undefined4 *in_x8;
  ConstSramRingView CVar5;
  
  bVar1 = (this->field_0).field_0.m_numCacheElemsLog2;
  bVar2 = (this->field_0).field_0.m_sizeofElemLog2;
  uVar3 = (this->field_0).field_0.m_head;
  uVar4 = (this->field_0).field_0.m_countDmaComplete;
  *in_x8 = (int)(this->field_0).field_0.m_vaSramCache;
  *(ulong *)(in_x8 + 1) =
       (ulong)(bVar2 & 0xf) << 0x38 |
       (ulong)((1 << (ulong)(bVar1 & 0x1f)) + 0xffffU & 0xffff) | ((ulong)uVar3 & 0x3fff) << 0x10 |
       (ulong)uVar4 << 0x20 | 0x70000000000000;
  CVar5.field_0.asU32[2] = in_w1;
  CVar5.field_0._0_8_ = this;
  return (ConstSramRingView)CVar5.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f4b4
 * symbol: getSramRingViewOfCache<14>
 * prototype: ConstSramRingView getSramRingViewOfCache<14>(OutputRing * this, uint16_t ringLocationHead)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: ConstSramRingView getSramRingViewOfCache<14>(OutputRing * this,
   uint16_t ringLocationHead) */

ConstSramRingView __thiscall
A53::OutputRing::getSramRingViewOfCache<14>(OutputRing *this,uint16_t ringLocationHead)

{
  uint uVar1;
  uint uVar2;
  uint32_t uVar3;
  byte bVar4;
  byte bVar5;
  ushort uVar6;
  undefined4 *in_x8;
  ConstSramRingView CVar7;
  
  bVar4 = (this->field_0).field_0.m_numCacheElemsLog2;
  uVar3 = (this->field_0).field_0.m_tail;
  bVar5 = (this->field_0).field_0.m_sizeofElemLog2;
  uVar6 = (this->field_0).field_0.m_countDmaNotComplete;
  uVar1 = uVar3 - ringLocationHead & 0x3fff;
  uVar2 = (uint)uVar6;
  if (uVar1 <= uVar6) {
    uVar2 = uVar1;
  }
  *in_x8 = (int)(this->field_0).field_0.m_vaSramCache;
  *(ulong *)(in_x8 + 1) =
       (ulong)(bVar5 & 0xf) << 0x38 |
       (ulong)(CONCAT24(uVar6,(1 << (ulong)(bVar4 & 0x1f)) + 0xffff) & 0xffff0000ffff) |
       (ulong)((uVar3 - uVar2 & 0x3fff) << 0x10) | 0x70000000000000;
  CVar7.field_0.asU32[2]._0_2_ = ringLocationHead;
  CVar7.field_0._0_8_ = this;
  CVar7.field_0.asU32[2]._2_2_ = 0;
  return (ConstSramRingView)CVar7.field_0;
}


