/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/dram\a53_io_controller_command_exec_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06013728
 * symbol: issuePtdmaRead
 * prototype: IssuePtdmaReadResult issuePtdmaRead(IoController * this, uint32_t len, uint64_t sysvaSrc, uint16_t pasid, DeviceOpSource source, uint32_t * out_ptdmaReadCacheIdx)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssuePtdmaReadResult issuePtdmaRead(IoController * this, uint32_t len,
   uint64_t sysvaSrc, uint16_t pasid, DeviceOpSource source, uint32_t * out_ptdmaReadCacheIdx) */

IssuePtdmaReadResult __thiscall
A53::IOC::IoController::issuePtdmaRead
          (IoController *this,uint32_t len,uint64_t sysvaSrc,uint16_t pasid,DeviceOpSource source,
          uint32_t *out_ptdmaReadCacheIdx)

{
  IssuePtdmaReadResult IVar1;
  
  IVar1 = A53::issuePtdmaRead((ControllerStaticConfiguration)0x54273bd0,&this->m_runtime_config,
                              this->m_aPtdmaQueue,this->m_aVaSramPtdmaCommandSource,
                              &this->m_sramRing_PtdmaReadCache,this->m_amaskPtdmaReadCacheElemsInUse
                              ,len,sysvaSrc,pasid,(A53DeviceOpSource)source.field_0,
                              out_ptdmaReadCacheIdx);
  return IVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06013788
 * symbol: readElement<unsigned_long>
 * prototype: uint32_t readElement<unsigned_long>(ConstSramRingView * this, uint32_t ringLocation, ulong * elem)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElement<unsigned long>
   DWARF original prototype: uint32_t readElement<unsigned_long>(ConstSramRingView * this, uint32_t
   ringLocation, ulong * elem) */

uint32_t __thiscall
A53::ConstSramRingView::readElement<unsigned_long>
          (ConstSramRingView *this,uint32_t ringLocation,ulong *elem)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  
  uVar5 = *(ulong *)((long)&this->field_0 + 4);
  uVar4 = (uint)uVar5;
  uVar2 = uVar4 & 0xffff;
  uVar3 = (uint)(uVar5 >> 0x20);
  if ((uVar5 >> 0x33 & 0x1f) == 0) {
    if (uVar2 < ringLocation) {
      return 0;
    }
    iVar1 = uVar2 + 1;
    if (((uint)(uVar5 >> 0x10) & 0xffff) <= ringLocation) {
      iVar1 = 0;
    }
    uVar4 = (ringLocation - (uVar4 >> 0x10)) + iVar1;
  }
  else {
    uVar4 = ringLocation - (uVar4 >> 0x10);
    ringLocation = uVar2 & ringLocation;
    uVar4 = (1 << (ulong)(uVar3 >> 0x13 & 0x1f)) - 1U & uVar4;
  }
  if ((uVar3 & 0x1ffff) <= uVar4) {
    return 0;
  }
  *elem = *(ulong *)((ulong)(this->field_0).field_0.m_vaSramRing +
                    (ulong)(ringLocation << (uVar5 >> 0x38 & 0xf)));
  return 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06013804
 * symbol: releasePtdmaRead
 * prototype: bool releasePtdmaRead(IoController * this, uint32_t len, uint32_t ptdmaReadCacheIdx)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool releasePtdmaRead(IoController * this, uint32_t len, uint32_t
   ptdmaReadCacheIdx) */

bool __thiscall
A53::IOC::IoController::releasePtdmaRead(IoController *this,uint32_t len,uint32_t ptdmaReadCacheIdx)

{
  bool bVar1;
  
  bVar1 = A53::releasePtdmaRead
                    (&this->m_sramRing_PtdmaReadCache,this->m_amaskPtdmaReadCacheElemsInUse,len,
                     ptdmaReadCacheIdx);
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06014114
 * symbol: getPipelineCommandData_pid
 * prototype: uint32_t getPipelineCommandData_pid(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::IOC::IoController::getPipelineCommandData_pid
                   (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId)

{
  bool bVar1;
  CommandInRingLocation CStack_18;
  
  bVar1 = getPipelineCommandDataCommandInRingLocation
                    (sramRingView_PipelineCommandData,pipelineCommandId,&CStack_18);
  if (!bVar1) {
    CStack_18.field_0.field_0.m_pid = 0xffffffff;
  }
  return CStack_18.field_0.field_0.m_pid;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06014bc8
 * symbol: issuePtdmaWrite
 * prototype: IssuePtdmaWriteResult issuePtdmaWrite(IoController * this, uint32_t len, uint64_t vaSramSrc, uint64_t sysvaDst, uint16_t pasid, DeviceOpSource source)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssuePtdmaWriteResult issuePtdmaWrite(IoController * this, uint32_t
   len, uint64_t vaSramSrc, uint64_t sysvaDst, uint16_t pasid, DeviceOpSource source) */

IssuePtdmaWriteResult __thiscall
A53::IOC::IoController::issuePtdmaWrite
          (IoController *this,uint32_t len,uint64_t vaSramSrc,uint64_t sysvaDst,uint16_t pasid,
          DeviceOpSource source)

{
  IssuePtdmaWriteResult IVar1;
  
  IVar1 = A53::issuePtdmaWrite
                    ((ControllerStaticConfiguration)0x54273bd0,&this->m_runtime_config,
                     this->m_aPtdmaQueue,this->m_aVaSramPtdmaCommandSource,
                     callback_dmaWriteCmdCompleted,this,len,vaSramSrc,sysvaDst,pasid,
                     (A53DeviceOpSource)source.field_0);
  return IVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06017714
 * symbol: markPackageUnbound
 * prototype: void markPackageUnbound(IoController * this, uint32_t packageIdx)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void markPackageUnbound(IoController * this, uint32_t packageIdx) */

void __thiscall A53::IOC::IoController::markPackageUnbound(IoController *this,uint32_t packageIdx)

{
  if (packageIdx < 0x5d) {
    this->m_amaskPackageUnbound[packageIdx >> 6] =
         this->m_amaskPackageUnbound[packageIdx >> 6] | 1L << (packageIdx & 0x3f);
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06018ee4
 * symbol: getVaSramElementWrapped
 * prototype: uint64_t getVaSramElementWrapped(ConstSramRingView * this, uint16_t ringLocationStart, uint32_t elemOffset)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint64_t getVaSramElementWrapped(ConstSramRingView * this, uint16_t
   ringLocationStart, uint32_t elemOffset) */

uint64_t __thiscall
A53::ConstSramRingView::getVaSramElementWrapped
          (ConstSramRingView *this,uint16_t ringLocationStart,uint32_t elemOffset)

{
  uint uVar1;
  int iVar2;
  ulong uVar3;
  
  uVar3 = *(ulong *)((long)&this->field_0 + 4);
  uVar1 = 0xffff;
  if ((uVar3 & 0xf8000000000000) != 0) {
    uVar1 = (uint)uVar3;
  }
  uVar1 = elemOffset + (uVar1 & ringLocationStart);
  iVar2 = 0;
  if ((ushort)uVar3 < uVar1) {
    iVar2 = ((uint)uVar3 & 0xffff) + 1;
  }
  return ((ulong)(uVar1 - iVar2) << (uVar3 >> 0x38 & 0xf)) +
         (ulong)(this->field_0).field_0.m_vaSramRing;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601a568
 * symbol: getPipelineCommandDataHeader_commandRingExecutingCommandId
 * prototype: uint16_t getPipelineCommandDataHeader_commandRingExecutingCommandId(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t A53::IOC::IoController::getPipelineCommandDataHeader_commandRingExecutingCommandId
                   (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId)

{
  bool bVar1;
  ushort uVar2;
  PipelineCommandDataHeader aPStack_18 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (sramRingView_PipelineCommandData,pipelineCommandId,aPStack_18);
  if (bVar1) {
    uVar2 = aPStack_18[0].field_0.asU32._2_2_ & 0x7ff;
  }
  else {
    uVar2 = 0xffff;
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601a740
 * symbol: getSramRingView_PipelineCommandData_DramPipeline_OpIssue
 * prototype: SramRingView getSramRingView_PipelineCommandData_DramPipeline_OpIssue(IoController * this, IoDramPipeline eIoDramPipeline)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: SramRingView
   getSramRingView_PipelineCommandData_DramPipeline_OpIssue(IoController * this, IoDramPipeline
   eIoDramPipeline) */

SramRingView __thiscall
A53::IOC::IoController::getSramRingView_PipelineCommandData_DramPipeline_OpIssue
          (IoController *this,IoDramPipeline eIoDramPipeline)

{
  ConstSramRingView CVar1;
  
  CVar1.field_0 =
       (anon_union_12_2_653be89a_for_ConstSramRingView_0)
       OutputRing::getSramRingViewOfCache<14>
                 (this->m_aOutputRing_PipelineCommandData_OpIssue + eIoDramPipeline,
                  *(uint16_t *)
                   (&DAT_000012e4 +
                   (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 2));
  return (ConstSramRingView)(ConstSramRingView)CVar1.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601ac8c
 * symbol: advanceIoDeviceOpDataOpConsumeReadNvmBufferHead
 * prototype: void advanceIoDeviceOpDataOpConsumeReadNvmBufferHead(IoController * this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void advanceIoDeviceOpDataOpConsumeReadNvmBufferHead(IoController *
   this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader) */

void __thiscall
A53::IOC::IoController::advanceIoDeviceOpDataOpConsumeReadNvmBufferHead
          (IoController *this,IoDramPipeline eIoDramPipeline,IoDeviceOpHeader *ioDeviceOpHeader)

{
  long lVar1;
  uint uVar2;
  short sVar3;
  
  lVar1 = (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 2;
  uVar2 = (uint)*(ushort *)(&DAT_000013d8 + lVar1) + ((ioDeviceOpHeader->field_0).asU32 & 0xf) + 1;
  sVar3 = 0;
  if ((*(uint *)(&DAT_000010fc + (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 0xc
                ) & 0xffff) < uVar2) {
    sVar3 = (short)*(uint *)(&DAT_000010fc +
                            (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 0xc) + 1
    ;
  }
  *(short *)(&DAT_000013d8 + lVar1) = (short)uVar2 - sVar3;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601acc4
 * symbol: advanceIoDeviceOpDataOpConsumeIssueZcnHead
 * prototype: void advanceIoDeviceOpDataOpConsumeIssueZcnHead(IoController * this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void advanceIoDeviceOpDataOpConsumeIssueZcnHead(IoController * this,
   IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader) */

void __thiscall
A53::IOC::IoController::advanceIoDeviceOpDataOpConsumeIssueZcnHead
          (IoController *this,IoDramPipeline eIoDramPipeline,IoDeviceOpHeader *ioDeviceOpHeader)

{
  long lVar1;
  uint uVar2;
  short sVar3;
  
  lVar1 = (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 2;
  uVar2 = (uint)*(ushort *)(&DAT_000013e4 + lVar1) + ((ioDeviceOpHeader->field_0).asU32 & 0xf) + 1;
  sVar3 = 0;
  if ((*(uint *)(&DAT_000010fc + (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 0xc
                ) & 0xffff) < uVar2) {
    sVar3 = (short)*(uint *)(&DAT_000010fc +
                            (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 0xc) + 1
    ;
  }
  *(short *)(&DAT_000013e4 + lVar1) = (short)uVar2 - sVar3;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601d598
 * symbol: advanceIoDeviceOpDataOpConsumeWaitForPtOdmaHead
 * prototype: void advanceIoDeviceOpDataOpConsumeWaitForPtOdmaHead(IoController * this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void advanceIoDeviceOpDataOpConsumeWaitForPtOdmaHead(IoController *
   this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader) */

void __thiscall
A53::IOC::IoController::advanceIoDeviceOpDataOpConsumeWaitForPtOdmaHead
          (IoController *this,IoDramPipeline eIoDramPipeline,IoDeviceOpHeader *ioDeviceOpHeader)

{
  long lVar1;
  uint uVar2;
  short sVar3;
  
  lVar1 = (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 2;
  uVar2 = (uint)*(ushort *)(&DAT_000013f0 + lVar1) + ((ioDeviceOpHeader->field_0).asU32 & 0xf) + 1;
  sVar3 = 0;
  if ((*(uint *)(&DAT_000010fc + (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 0xc
                ) & 0xffff) < uVar2) {
    sVar3 = (short)*(uint *)(&DAT_000010fc +
                            (long)&this->m_aInputRing[0].field_0 + (ulong)eIoDramPipeline * 0xc) + 1
    ;
  }
  *(short *)(&DAT_000013f0 + lVar1) = (short)uVar2 - sVar3;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06022aa8
 * symbol: readElementsWrapped<unsigned_long>
 * prototype: uint32_t readElementsWrapped<unsigned_long>(ConstSramRingView * this, uint32_t ringLocationStart, uint32_t numElems, ulong * aElem)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElementsWrapped<unsigned long>
   DWARF original prototype: uint32_t readElementsWrapped<unsigned_long>(ConstSramRingView * this,
   uint32_t ringLocationStart, uint32_t numElems, ulong * aElem) */

uint32_t __thiscall
A53::ConstSramRingView::readElementsWrapped<unsigned_long>
          (ConstSramRingView *this,uint32_t ringLocationStart,uint32_t numElems,ulong *aElem)

{
  uint32_t uVar1;
  
  uVar1 = readElementsWrapped<unsigned_long>(this,ringLocationStart,0,numElems,aElem);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06027d94
 * symbol: pushElement
 * prototype: bool pushElement(SramRing * this)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool pushElement(SramRing * this) */

bool __thiscall A53::SramRing::pushElement(SramRing *this)

{
  bool bVar1;
  ulong uVar2;
  
  uVar2 = *(ulong *)((long)&(this->super_SramRingView).super_ConstSramRingView.field_0 + 4);
  bVar1 = ((uint)(uVar2 >> 0x20) & 0x1ffff) <= (uint)(ushort)uVar2;
  if (bVar1) {
    *(ulong *)((long)&(this->super_SramRingView).super_ConstSramRingView.field_0 + 4) =
         uVar2 & 0xfffe000000000000 |
         uVar2 & 0xffffffff | (uVar2 + 0x100000000 >> 0x20 & 0x1ffff) << 0x20;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06028544
 * symbol: readElementsWrapped<unsigned_int>
 * prototype: uint32_t readElementsWrapped<unsigned_int>(ConstSramRingView * this, uint32_t ringLocationStart, uint32_t numElems, uint * aElem)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElementsWrapped<unsigned int>
   DWARF original prototype: uint32_t readElementsWrapped<unsigned_int>(ConstSramRingView * this,
   uint32_t ringLocationStart, uint32_t numElems, uint * aElem) */

uint32_t __thiscall
A53::ConstSramRingView::readElementsWrapped<unsigned_int>
          (ConstSramRingView *this,uint32_t ringLocationStart,uint32_t numElems,uint *aElem)

{
  uint32_t uVar1;
  
  uVar1 = readElementsWrapped<unsigned_int>(this,ringLocationStart,0,numElems,aElem);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06028594
 * symbol: writeElementsWrapped<unsigned_int>
 * prototype: uint32_t writeElementsWrapped<unsigned_int>(SramRingView * this, uint32_t ringLocationStart, uint32_t numElems, uint * aElem)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: writeElementsWrapped<unsigned int>
   DWARF original prototype: uint32_t writeElementsWrapped<unsigned_int>(SramRingView * this,
   uint32_t ringLocationStart, uint32_t numElems, uint * aElem) */

uint32_t __thiscall
A53::SramRingView::writeElementsWrapped<unsigned_int>
          (SramRingView *this,uint32_t ringLocationStart,uint32_t numElems,uint *aElem)

{
  uint32_t uVar1;
  
  uVar1 = writeElementsWrapped<unsigned_int>(this,ringLocationStart,0,numElems,aElem);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029574
 * symbol: getSysNsid2CommandRingExecutingCommand
 * prototype: bool getSysNsid2CommandRingExecutingCommand(ConstSramRingView * sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId, SysNsid2CommandRingExecutingCommand * out_commandRingExecutingCommand)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::IOC::IoController::getSysNsid2CommandRingExecutingCommand
               (ConstSramRingView *sramRingView_CommandRingExecutingCommand,
               uint16_t commandRingExecutingCommandId,
               SysNsid2CommandRingExecutingCommand *out_commandRingExecutingCommand)

{
  uint32_t uVar1;
  
  uVar1 = ConstSramRingView::readElement<unsigned_int>
                    (sramRingView_CommandRingExecutingCommand,(uint)commandRingExecutingCommandId,
                     (uint *)out_commandRingExecutingCommand);
  return uVar1 == 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060295c4
 * symbol: makeDeviceOpSource_InputCommand_SramPipeline
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_SramPipeline(IoSramPipeline eIoSramPipeline, uint16_t pipelineCommandId, DeviceOpSourceIsAppPasid eIsAppPasid, DeviceOpSourceNotify eNotify, uint32_t notifyHeaderStateBit)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


DeviceOpSource
A53::IOC::makeDeviceOpSource_InputCommand_SramPipeline
          (IoSramPipeline eIoSramPipeline,uint16_t pipelineCommandId,
          DeviceOpSourceIsAppPasid eIsAppPasid,DeviceOpSourceNotify eNotify,
          uint32_t notifyHeaderStateBit)

{
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         ((eIsAppPasid & 1) << 0x19 |
          pipelineCommandId & 0x7fff | (eIoSramPipeline & 0xf) << 0x10 |
          (eNotify & 0xf | (uint)(eIsAppPasid == 4) << 3) << 0x15 | 0xd8000000);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060296c4
 * symbol: getSramRingViewOfCache<14>
 * prototype: SramRingView getSramRingViewOfCache<14>(InputRing * this)
 * body addresses: 252
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: SramRingView getSramRingViewOfCache<14>(InputRing * this) */

SramRingView __thiscall A53::InputRing::getSramRingViewOfCache<14>(InputRing *this)

{
  byte bVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  uint64_t uVar5;
  uint count;
  ushort uVar6;
  ConstSramRingView *in_x8;
  uint uVar7;
  SramRingView SVar8;
  uint32_t vaSramRing;
  
  uVar2 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
  if ((this->field_0).field_0.m_countPtdmaCommand == 0) {
    uVar6 = (this->field_0).field_0.m_head;
    vaSramRing = *(uint32_t *)((long)&this->field_0 + 0x10);
    bVar1 = (this->field_0).field_0.m_sizeofElemLog2;
    count = (uint)(this->field_0).field_0.m_countDmaComplete;
  }
  else {
    iVar3 = 1 << (ulong)((this->field_0).field_0.m_sizeofElemLog2 & 0x1f);
    uVar5 = getVaSramCacheElemFromHead(this,(uint)(this->field_0).field_0.m_countDmaComplete);
    uVar4 = (((uint)uVar5 & 0x3f) + iVar3) - 1 >>
            (ulong)((this->field_0).field_0.m_sizeofElemLog2 & 0x1f);
    uVar5 = getVaSramCacheElemFromHead(this,(uint)(this->field_0).field_0.m_countDmaIssued);
    bVar1 = (this->field_0).field_0.m_sizeofElemLog2;
    uVar7 = (((-(int)uVar5 & 0x3fU) + iVar3) - 1 >> (ulong)(bVar1 & 0x1f)) +
            (uint)(this->field_0).field_0.m_countDmaIssued;
    iVar3 = uVar7 - uVar2;
    count = 0;
    if (uVar7 < uVar2 || iVar3 == 0) {
      iVar3 = 0;
    }
    uVar7 = (uint)(this->field_0).field_0.m_countDmaComplete;
    if (iVar3 + uVar4 < uVar7) {
      count = (uVar7 - uVar4) - iVar3 & 0xffff;
    }
    vaSramRing = *(uint32_t *)((long)&this->field_0 + 0x10);
    uVar6 = (short)iVar3 + (this->field_0).field_0.m_head;
  }
  ConstSramRingView::ConstSramRingView
            (in_x8,vaSramRing,(uint)bVar1,(short)uVar2 - 1,uVar6 & 0x3fff,count,0xe);
  SVar8.super_ConstSramRingView.field_0.asU32[2] = vaSramRing;
  SVar8.super_ConstSramRingView.field_0._0_8_ = in_x8;
  return (SramRingView)SVar8.super_ConstSramRingView.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060297c0
 * symbol: getVaSramCacheElemFromHead
 * prototype: uint64_t getVaSramCacheElemFromHead(InputRing * this, uint32_t indexFromHead)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint64_t getVaSramCacheElemFromHead(InputRing * this, uint32_t
   indexFromHead) */

uint64_t __thiscall
A53::InputRing::getVaSramCacheElemFromHead(InputRing *this,uint32_t indexFromHead)

{
  return ((ulong)((1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f)) - 1U &
                 (this->field_0).field_0.m_head + indexFromHead) <<
         ((ulong)(this->field_0).field_0.m_sizeofElemLog2 & 0x3f)) +
         (this->field_0).field_0.m_vaSramCache;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060297f0
 * symbol: ConstSramRingView
 * prototype: void ConstSramRingView(ConstSramRingView * this, uint32_t vaSramRing, uint32_t sizeofElemLog2, uint16_t numRingElemsMinus1, uint16_t head, uint32_t count, uint32_t ringLocationSizeLog2)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void ConstSramRingView(ConstSramRingView * this, uint32_t vaSramRing,
   uint32_t sizeofElemLog2, uint16_t numRingElemsMinus1, uint16_t head, uint32_t count, uint32_t
   ringLocationSizeLog2) */

void __thiscall
A53::ConstSramRingView::ConstSramRingView
          (ConstSramRingView *this,uint32_t vaSramRing,uint32_t sizeofElemLog2,
          uint16_t numRingElemsMinus1,uint16_t head,uint32_t count,uint32_t ringLocationSizeLog2)

{
  (this->field_0).field_0.m_vaSramRing = vaSramRing;
  *(ulong *)((long)&this->field_0 + 4) =
       (ulong)(sizeofElemLog2 & 0xf) << 0x38 |
       CONCAT44(count,CONCAT22(head,numRingElemsMinus1)) & 0x1ffffffffffff |
       (ulong)(ringLocationSizeLog2 & 0x1f) << 0x33;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029820
 * symbol: getSramRingViewOfCache<14>
 * prototype: SramRingView getSramRingViewOfCache<14>(OutputRing * this, uint16_t ringLocationHead)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: SramRingView getSramRingViewOfCache<14>(OutputRing * this, uint16_t
   ringLocationHead) */

SramRingView __thiscall
A53::OutputRing::getSramRingViewOfCache<14>(OutputRing *this,uint16_t ringLocationHead)

{
  uint count;
  uint uVar1;
  uint32_t uVar2;
  ushort uVar3;
  ConstSramRingView *in_x8;
  SramRingView SVar4;
  uint32_t vaSramRing;
  
  uVar2 = (this->field_0).field_0.m_tail;
  uVar3 = (this->field_0).field_0.m_countDmaNotComplete;
  vaSramRing = *(uint32_t *)((long)&this->field_0 + 0x10);
  count = uVar2 - ringLocationHead & 0x3fff;
  uVar1 = (uint)uVar3;
  if (count <= uVar3) {
    uVar1 = count;
  }
  ConstSramRingView::ConstSramRingView
            (in_x8,vaSramRing,(uint)(this->field_0).field_0.m_sizeofElemLog2,
             (short)(1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f)) - 1,
             (short)uVar2 - (short)uVar1 & 0x3fff,count,0xe);
  SVar4.super_ConstSramRingView.field_0.asU32[2] = vaSramRing;
  SVar4.super_ConstSramRingView.field_0._0_8_ = in_x8;
  return (SramRingView)SVar4.super_ConstSramRingView.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029868
 * symbol: makeDeviceOpSource_InputCommand_DramPipeline_OpIssue
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_DramPipeline_OpIssue(IoDramPipeline eIoDramPipeline, IoControllerCommandRing eRing, uint16_t commandRingExecutingCommandId, DeviceOpSourceIsAppPasid eIsAppPasid, DeviceOpSourceNotify eNotify, uint32_t notifyHeaderStateBit)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


DeviceOpSource
A53::IOC::makeDeviceOpSource_InputCommand_DramPipeline_OpIssue
          (IoDramPipeline eIoDramPipeline,IoControllerCommandRing eRing,
          uint16_t commandRingExecutingCommandId,DeviceOpSourceIsAppPasid eIsAppPasid,
          DeviceOpSourceNotify eNotify,uint32_t notifyHeaderStateBit)

{
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         ((eIsAppPasid & 1) << 0x19 |
          (eRing & 0x1f) << 0xb | (eIoDramPipeline & 0xf) << 0x10 |
          commandRingExecutingCommandId & 0x7ff |
          (eNotify & 0xf | (uint)(eIsAppPasid == 4) << 3) << 0x15 | 0xe0000000);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029894
 * symbol: readElementsWrapped<unsigned_long>
 * prototype: uint32_t readElementsWrapped<unsigned_long>(ConstSramRingView * this, uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, ulong * aElem)
 * body addresses: 300
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElementsWrapped<unsigned long>
   DWARF original prototype: uint32_t readElementsWrapped<unsigned_long>(ConstSramRingView * this,
   uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, ulong * aElem) */

uint32_t __thiscall
A53::ConstSramRingView::readElementsWrapped<unsigned_long>
          (ConstSramRingView *this,uint32_t ringLocationBase,uint32_t elemOffsetStart,
          uint32_t numElems,ulong *aElem)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  long lVar6;
  uint uVar7;
  
  uVar5 = *(ulong *)((long)&this->field_0 + 4);
  uVar4 = (uint)uVar5;
  uVar2 = uVar4 & 0xffff;
  uVar1 = uVar2 + 1;
  uVar7 = (uint)(uVar5 >> 0x20);
  if ((uVar5 >> 0x33 & 0x1f) == 0) {
    if (uVar2 < ringLocationBase) {
      return 0;
    }
    if ((ulong)uVar1 < (ulong)numElems + (ulong)elemOffsetStart) {
      return 0;
    }
    uVar3 = uVar1;
    if (((uint)(uVar5 >> 0x10) & 0xffff) <= ringLocationBase) {
      uVar3 = 0;
    }
    uVar3 = (ringLocationBase - (uVar4 >> 0x10)) + uVar3;
  }
  else {
    uVar3 = (1 << (ulong)(uVar7 >> 0x13 & 0x1f)) - 1U & ringLocationBase - (uVar4 >> 0x10);
    if ((uVar7 & 0x1ffff) <= uVar3) {
      return 0;
    }
    ringLocationBase = uVar2 & ringLocationBase;
  }
  if (numElems == 0) {
    return 0;
  }
  if ((uVar7 & 0x1ffff) < numElems + elemOffsetStart + uVar3) {
    return 0;
  }
  uVar7 = uVar1;
  if (ringLocationBase + elemOffsetStart <= uVar2) {
    uVar7 = 0;
  }
  uVar7 = (ringLocationBase + elemOffsetStart) - uVar7;
  uVar2 = uVar7 + numElems;
  if (uVar1 < uVar2) {
    for (; uVar7 <= (ushort)uVar5; uVar7 = uVar7 + 1) {
      *aElem = *(ulong *)((ulong)(this->field_0).field_0.m_vaSramRing +
                         (ulong)(uVar7 << (uVar5 >> 0x38 & 0xf)));
      uVar5 = *(ulong *)((long)&this->field_0 + 4);
      aElem = aElem + 1;
    }
    for (lVar6 = 0; uVar2 - uVar1 != (int)lVar6; lVar6 = lVar6 + 1) {
      aElem[lVar6] = *(ulong *)((ulong)(this->field_0).field_0.m_vaSramRing +
                               (ulong)(uint)((int)lVar6 <<
                                            (ulong)(*(byte *)((long)&this->field_0 + 0xb) & 0xf)));
    }
    return numElems;
  }
  for (; uVar7 < uVar2; uVar7 = uVar7 + 1) {
    *aElem = *(ulong *)((ulong)(this->field_0).field_0.m_vaSramRing +
                       (ulong)(uVar7 << (ulong)(*(byte *)((long)&this->field_0 + 0xb) & 0xf)));
    aElem = aElem + 1;
  }
  return numElems;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060299c0
 * symbol: writeElementsWrapped<unsigned_int>
 * prototype: uint32_t writeElementsWrapped<unsigned_int>(SramRingView * this, uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, uint * aElem)
 * body addresses: 300
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: writeElementsWrapped<unsigned int>
   DWARF original prototype: uint32_t writeElementsWrapped<unsigned_int>(SramRingView * this,
   uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, uint * aElem) */

uint32_t __thiscall
A53::SramRingView::writeElementsWrapped<unsigned_int>
          (SramRingView *this,uint32_t ringLocationBase,uint32_t elemOffsetStart,uint32_t numElems,
          uint *aElem)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  long lVar6;
  uint uVar7;
  
  uVar5 = *(ulong *)((long)&(this->super_ConstSramRingView).field_0 + 4);
  uVar4 = (uint)uVar5;
  uVar2 = uVar4 & 0xffff;
  uVar1 = uVar2 + 1;
  uVar7 = (uint)(uVar5 >> 0x20);
  if ((uVar5 >> 0x33 & 0x1f) == 0) {
    if (uVar2 < ringLocationBase) {
      return 0;
    }
    if ((ulong)uVar1 < (ulong)numElems + (ulong)elemOffsetStart) {
      return 0;
    }
    uVar3 = uVar1;
    if (((uint)(uVar5 >> 0x10) & 0xffff) <= ringLocationBase) {
      uVar3 = 0;
    }
    uVar3 = (ringLocationBase - (uVar4 >> 0x10)) + uVar3;
  }
  else {
    uVar3 = (1 << (ulong)(uVar7 >> 0x13 & 0x1f)) - 1U & ringLocationBase - (uVar4 >> 0x10);
    if ((uVar7 & 0x1ffff) <= uVar3) {
      return 0;
    }
    ringLocationBase = uVar2 & ringLocationBase;
  }
  if (numElems == 0) {
    return 0;
  }
  if ((uVar7 & 0x1ffff) < numElems + elemOffsetStart + uVar3) {
    return 0;
  }
  uVar7 = uVar1;
  if (ringLocationBase + elemOffsetStart <= uVar2) {
    uVar7 = 0;
  }
  uVar7 = (ringLocationBase + elemOffsetStart) - uVar7;
  uVar2 = uVar7 + numElems;
  if (uVar1 < uVar2) {
    for (; uVar7 <= (ushort)uVar5; uVar7 = uVar7 + 1) {
      *(uint *)((ulong)(this->super_ConstSramRingView).field_0.field_0.m_vaSramRing +
               (ulong)(uVar7 << (uVar5 >> 0x38 & 0xf))) = *aElem;
      uVar5 = *(ulong *)((long)&(this->super_ConstSramRingView).field_0 + 4);
      aElem = aElem + 1;
    }
    for (lVar6 = 0; uVar2 - uVar1 != (int)lVar6; lVar6 = lVar6 + 1) {
      *(uint *)((ulong)(this->super_ConstSramRingView).field_0.field_0.m_vaSramRing +
               (ulong)(uint)((int)lVar6 <<
                            (ulong)(*(byte *)((long)&(this->super_ConstSramRingView).field_0 + 0xb)
                                   & 0xf))) = aElem[lVar6];
    }
    return numElems;
  }
  for (; uVar7 < uVar2; uVar7 = uVar7 + 1) {
    *(uint *)((ulong)(this->super_ConstSramRingView).field_0.field_0.m_vaSramRing +
             (ulong)(uVar7 << (ulong)(*(byte *)((long)&(this->super_ConstSramRingView).field_0 + 0xb
                                               ) & 0xf))) = *aElem;
    aElem = aElem + 1;
  }
  return numElems;
}


