/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/dram\a53_zcn_driver_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06033898
 * symbol: init
 * prototype: int init(ZcnVqState * this, EVP_PKEY_CTX * ctx)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void init(ZcnVqState * this, uint32_t iVq, uint64_t vaSramZcnQueue) */

int __thiscall A53::ZcnVqState::init(ZcnVqState *this,EVP_PKEY_CTX *ctx)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  uint8_t uVar4;
  uint uVar5;
  uint32_t in_w2;
  
  uVar3 = (int)ctx << 0xc;
  uVar1 = *(uint *)(&DAT_022e1000 + uVar3);
  (this->m_submit).m_reserved = 0;
  (this->m_submit).m_numCommandsUntilDone = 0;
  uVar1 = uVar1 >> 3 & 0xf;
  uVar4 = (char)uVar1 + '\x06';
  iVar2 = 0x40 << (ulong)uVar1;
  uVar5 = iVar2 - 0x20;
  (this->m_submit).m_sizeofQueueLog2 = uVar4;
  uVar1 = *(uint *)(&DAT_022e1008 + uVar3);
  this->m_head_lo = uVar1 & 0x7fffffff;
  uVar3 = *(uint *)(&DAT_022e1004 + uVar3);
  (this->m_submit).m_sizeofQueueLog2 = uVar4;
  (this->m_submit).m_iVq = (uint8_t)ctx;
  this->m_tail_lo = uVar3;
  (this->m_submit).m_maskVqdPointer = uVar5;
  (this->m_submit).m_offsetPut = uVar3 & uVar5;
  (this->m_submit).m_paQueue = uVar3 & 0x1fU - iVar2;
  (this->m_submit).m_vaQueue = in_w2;
  (this->m_submit).m_numCommandsAvailable =
       (uint16_t)((((uVar1 & 0x7fffffff) - uVar3) + 0x1fffe0 & uVar5) >> 5);
  return (int)this;
}


