/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/dram\a53_nvm_ttn_driver_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602fb94
 * symbol: nvmSetAdminQueueAttributes
 * prototype: bool nvmSetAdminQueueAttributes(uint32_t numSqe, uint32_t numCqe)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

bool A53::nvmSetAdminQueueAttributes(uint32_t numSqe,uint32_t numCqe)

{
  uint uVar1;
  uint uVar2;
  
  if (((numSqe != 0) && (numCqe != 0)) &&
     ((0xfffe < numSqe - 2 || 0xfffd < numCqe - 2) && (0xfffe < numSqe - 2 || numCqe - 2 != 0xfffe))
     ) {
    return false;
  }
  uVar1 = numSqe + 0xfff & 0xfff;
  if (numSqe < 2) {
    uVar1 = 0;
  }
  uVar2 = numCqe * 0x10000 + 0xfff0000 & 0xfff0000;
  if (numCqe < 2) {
    uVar2 = 0;
  }
  _DAT_03800024 = uVar2 | uVar1;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602fbf8
 * symbol: setInCreate
 * prototype: void setInCreate(NvmCompletionQueue * this, uint64_t paBase, uint32_t nvmvaBasePage, uint32_t numCqe)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setInCreate(NvmCompletionQueue * this, uint64_t paBase, uint32_t
   nvmvaBasePage, uint32_t numCqe) */

void __thiscall
A53::IOC::NvmCompletionQueue::setInCreate
          (NvmCompletionQueue *this,uint64_t paBase,uint32_t nvmvaBasePage,uint32_t numCqe)

{
  ushort uVar1;
  uint16_t uVar2;
  
  uVar2 = 0xffff;
  if ((*(byte *)((long)&this->field_0 + 0xe) >> 3 & 1) != 0) {
    uVar2 = (this->field_0).field_0.m_ptdmaCmdFetch;
  }
  reset(this);
  (this->field_0).field_0.m_paBase = paBase;
  (this->field_0).field_0.m_nvmvaBasePage = nvmvaBasePage;
  (this->field_0).field_0.m_sizeMinus1 = (short)numCqe - 1;
  uVar1 = *(ushort *)((long)&this->field_0 + 0xe) & 0xfffc;
  *(ushort *)((long)&this->field_0 + 0xe) = uVar1 | 2;
  if (uVar2 != 0xffff) {
    (this->field_0).field_0.m_ptdmaCmdFetch = uVar2;
    *(ushort *)((long)&this->field_0 + 0xe) = uVar1 | 10;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602fc84
 * symbol: setInCreate
 * prototype: void setInCreate(NvmSubmissionQueue * this, uint64_t paBase, uint32_t nvmvaBasePage, uint32_t numSqe, uint32_t cqid, NvmQueuePriority ePriority)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setInCreate(NvmSubmissionQueue * this, uint64_t paBase, uint32_t
   nvmvaBasePage, uint32_t numSqe, uint32_t cqid, NvmQueuePriority ePriority) */

void __thiscall
A53::IOC::NvmSubmissionQueue::setInCreate
          (NvmSubmissionQueue *this,uint64_t paBase,uint32_t nvmvaBasePage,uint32_t numSqe,
          uint32_t cqid,NvmQueuePriority ePriority)

{
  reset(this);
  (this->field_0).field_0.m_paBase = paBase;
  (this->field_0).field_0.m_nvmvaBasePage = nvmvaBasePage;
  (this->field_0).field_0.m_sizeMinus1 = (short)numSqe - 1;
  *(ushort *)((long)&this->field_0 + 0xe) =
       (ushort)((ePriority & 3) << 8) | (ushort)((cqid & 7) << 0xc) |
       *(ushort *)((long)&this->field_0 + 0xe) & 0x8cfc | 2;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06030690
 * symbol: reset
 * prototype: void reset(NvmTtnNotificationBuffer * this)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void reset(NvmTtnNotificationBuffer * this) */

void __thiscall A53::IOC::NvmTtnNotificationBuffer::reset(NvmTtnNotificationBuffer *this)

{
  uint16_t uVar1;
  
  uVar1 = (this->field_0).field_0.m_offsetSramCache;
  (this->field_0).field_0.m_paBase = 0;
  (this->field_0).asU64[1] = 0;
  (this->field_0).asU64[2] = 0xffff;
  (this->field_0).asU64[3] = 0xffff00000000;
  (this->field_0).field_0.m_offsetSramCache = uVar1;
  (this->field_0).field_0.m_numNbeSramCacheLog2 = (this->field_0).field_0.m_numNbeSramCacheLog2;
  (this->field_0).field_0.m_numConfigCommands = (this->field_0).field_0.m_numConfigCommands;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0603075c
 * symbol: isCreated
 * prototype: bool isCreated(NvmSubmissionQueue * this)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isCreated(NvmSubmissionQueue * this) */

bool __thiscall A53::IOC::NvmSubmissionQueue::isCreated(NvmSubmissionQueue *this)

{
  ushort uVar1;
  
  if (((this->field_0).field_0.m_sizeMinus1 != 0) &&
     (uVar1 = *(ushort *)((long)&this->field_0 + 0xe), (uVar1 & 3) == 0)) {
    return (uVar1 & 4) == 0;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06030784
 * symbol: isCreated
 * prototype: bool isCreated(NvmCompletionQueue * this)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isCreated(NvmCompletionQueue * this) */

bool __thiscall A53::IOC::NvmCompletionQueue::isCreated(NvmCompletionQueue *this)

{
  ushort uVar1;
  
  if (((this->field_0).field_0.m_sizeMinus1 != 0) &&
     (uVar1 = *(ushort *)((long)&this->field_0 + 0xe), (uVar1 & 3) == 0)) {
    return (uVar1 & 4) == 0;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06030f24
 * symbol: isDeleted
 * prototype: bool isDeleted(NvmCompletionQueue * this)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isDeleted(NvmCompletionQueue * this) */

bool __thiscall A53::IOC::NvmCompletionQueue::isDeleted(NvmCompletionQueue *this)

{
  ushort uVar1;
  
  uVar1 = *(ushort *)((long)&this->field_0 + 0xe);
  if ((ushort)(uVar1 & 1 | (ushort)((this->field_0).field_0.m_sizeMinus1 == 0)) != 1 ||
      (uVar1 & 4) != 0) {
    return false;
  }
  return (uVar1 & 2) == 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0603119c
 * symbol: isDeleted
 * prototype: bool isDeleted(NvmSubmissionQueue * this)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isDeleted(NvmSubmissionQueue * this) */

bool __thiscall A53::IOC::NvmSubmissionQueue::isDeleted(NvmSubmissionQueue *this)

{
  ushort uVar1;
  
  uVar1 = *(ushort *)((long)&this->field_0 + 0xe);
  if ((ushort)(uVar1 & 1 | (ushort)((this->field_0).field_0.m_sizeMinus1 == 0)) != 1 ||
      (uVar1 & 4) != 0) {
    return false;
  }
  return (uVar1 & 2) == 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060320fc
 * symbol: isDeleted
 * prototype: bool isDeleted(NvmTtnNotificationBuffer * this)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isDeleted(NvmTtnNotificationBuffer * this) */

bool __thiscall A53::IOC::NvmTtnNotificationBuffer::isDeleted(NvmTtnNotificationBuffer *this)

{
  byte bVar1;
  
  bVar1 = *(byte *)((long)&this->field_0 + 0xe);
  if ((bVar1 & 1 | (this->field_0).field_0.m_sizeMinus1 == 0) != 1 || (bVar1 & 4) != 0) {
    return false;
  }
  return (bVar1 & 2) == 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06032138
 * symbol: isCreated
 * prototype: bool isCreated(NvmTtnNotificationBuffer * this)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isCreated(NvmTtnNotificationBuffer * this) */

bool __thiscall A53::IOC::NvmTtnNotificationBuffer::isCreated(NvmTtnNotificationBuffer *this)

{
  byte bVar1;
  
  if (((this->field_0).field_0.m_sizeMinus1 != 0) &&
     (bVar1 = *(byte *)((long)&this->field_0 + 0xe), (bVar1 & 3) == 0)) {
    return (bVar1 & 4) == 0;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06032160
 * symbol: setInCreate
 * prototype: void setInCreate(NvmTtnNotificationBuffer * this, uint64_t paBase, uint32_t nvmvaBasePage, uint32_t numEntries)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setInCreate(NvmTtnNotificationBuffer * this, uint64_t paBase,
   uint32_t nvmvaBasePage, uint32_t numEntries) */

void __thiscall
A53::IOC::NvmTtnNotificationBuffer::setInCreate
          (NvmTtnNotificationBuffer *this,uint64_t paBase,uint32_t nvmvaBasePage,uint32_t numEntries
          )

{
  byte bVar1;
  uint16_t uVar2;
  
  uVar2 = 0xffff;
  if ((*(byte *)((long)&this->field_0 + 0xe) >> 3 & 1) != 0) {
    uVar2 = (this->field_0).field_0.m_ptdmaCmdFetch;
  }
  reset(this);
  (this->field_0).field_0.m_paBase = paBase;
  (this->field_0).field_0.m_nvmvaBasePage = nvmvaBasePage;
  (this->field_0).field_0.m_sizeMinus1 = (short)numEntries - 1;
  bVar1 = *(byte *)((long)&this->field_0 + 0xe) & 0xfc;
  *(byte *)((long)&this->field_0 + 0xe) = bVar1 | 2;
  if (uVar2 != 0xffff) {
    (this->field_0).field_0.m_ptdmaCmdFetch = uVar2;
    *(byte *)((long)&this->field_0 + 0xe) = bVar1 | 10;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060330b4
 * symbol: reset
 * prototype: void reset(NvmCompletionQueue * this)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void reset(NvmCompletionQueue * this) */

void __thiscall A53::IOC::NvmCompletionQueue::reset(NvmCompletionQueue *this)

{
  uint16_t uVar1;
  
  uVar1 = (this->field_0).field_0.m_offsetSramCache;
  (this->field_0).field_0.m_paBase = 0;
  (this->field_0).asU64[1] = 0;
  (this->field_0).asU64[2] = 0;
  (this->field_0).asU64[3] = 0xffffffff00000000;
  (this->field_0).field_0.m_offsetSramCache = uVar1;
  (this->field_0).field_0.m_numCqeSramCacheLog2 = (this->field_0).field_0.m_numCqeSramCacheLog2;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060330d4
 * symbol: reset
 * prototype: void reset(NvmSubmissionQueue * this)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void reset(NvmSubmissionQueue * this) */

void __thiscall A53::IOC::NvmSubmissionQueue::reset(NvmSubmissionQueue *this)

{
  uint16_t uVar1;
  
  uVar1 = (this->field_0).field_0.m_offsetSramCache;
  (this->field_0).field_0.m_paBase = 0;
  (this->field_0).asU64[1] = 0;
  (this->field_0).asU64[2] = 0;
  (this->field_0).asU64[3] = 0xffffffff00000000;
  (this->field_0).field_0.m_offsetSramCache = uVar1;
  (this->field_0).field_0.m_numSqeSramCacheLog2 = (this->field_0).field_0.m_numSqeSramCacheLog2;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060330f4
 * symbol: nvmZeroSqe
 * prototype: void nvmZeroSqe(NvmSqe * out_cmd)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::nvmZeroSqe(NvmSqe *out_cmd)

{
  (out_cmd->field_0).asU64[6] = 0;
  (out_cmd->field_0).asU64[7] = 0;
  (out_cmd->field_0).asU64[4] = 0;
  (out_cmd->field_0).asU64[5] = 0;
  (out_cmd->field_0).field_0.MPTR = 0;
  (out_cmd->field_0).asU64[3] = 0;
  (out_cmd->field_0).asU64[0] = 0;
  (out_cmd->field_0).field_0.rsv1 = 0;
  return;
}


