/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/dram\io_controller_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06033adc
 * symbol: IoController_BootConfiguration_print
 * prototype: void IoController_BootConfiguration_print(IoController_BootConfiguration * bc)
 * body addresses: 408
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void IoController_BootConfiguration_print(IoController_BootConfiguration *bc)

{
  printf("m_kernelShared\n");
  A53Controller_BootConfiguration_KernelShared_show
            ((A53Controller_BootConfiguration_KernelShared *)bc);
  printf("m_private\n");
  A53Controller_BootConfiguration_PrivateDram_print(&(bc->field_0).field_0.m_private);
  printf("m_aslr\n");
  A53Controller_BootConfiguration_ASLR_print(&(bc->field_0).field_0.m_aslr);
  printf("m_titania\n");
  printf("m_ttnvaTitania64K             = 0x%08llx\n",(ulong)(bc->field_0).asU32[0x14]);
  printf("m_offsetSyshubIf64K           = 0x%04llx\n",(ulong)*(ushort *)((long)&bc->field_0 + 0x54))
  ;
  printf("m_sizeTitania64K              = 0x%04llx\n",(ulong)*(ushort *)((long)&bc->field_0 + 0x56))
  ;
  printf("m_sizeTitaniaRingNSID1        = 0x%03llx\n",(ulong)((bc->field_0).asU32[0x16] & 0x1ff));
  printf("m_sizeTitaniaRingNSID2W       = 0x%03llx\n",
         (ulong)((bc->field_0).asU32[0x16] >> 9 & 0x1ff));
  printf("m_sizeTitaniaRingNSID2N       = 0x%03llx\n",
         (ulong)((bc->field_0).asU32[0x16] >> 0x12 & 0x1ff));
  printf("m_sizeTitaniaRingNSID2H       = 0x%03llx\n",(bc->field_0).asU64[0xb] >> 0x1b & 0x1ff);
  printf("m_sizeTitaniaRingNSID2U       = 0x%03llx\n",(bc->field_0).asU64[0xb] >> 0x24 & 0x1ff);
  printf("m_sizeTitaniaRingNSID3        = 0x%03llx\n",(bc->field_0).asU64[0xb] >> 0x2d & 0x1ff);
  printf("RESERVED BITS[118:127]        = 0x%03llx\n",(bc->field_0).asU64[0xb] >> 0x35 & 0x3ff);
  printf("m_zcnvaTitania64K             = 0x%08llx\n",(ulong)(bc->field_0).asU32[0x18]);
  printf("m_ttnvaTitaniaDirectWrite64K  = 0x%08llx\n",(ulong)(bc->field_0).asU32[0x19]);
  printf("m_sizeTitaniaDirectWrite64K   = 0x%04llx\n",(ulong)((bc->field_0).asU32[0x1a] & 0x3fff));
  printf("m_offsetSyshubIfSystemMmio4K  = 0x%05llx\n",(bc->field_0).asU64[0xd] >> 0xe & 0xfffff);
  printf("RESERVED BITS[226:255]        = 0x%08llx\n",(bc->field_0).asU64[0xd] >> 0x22);
  printf("RESERVED BITS[896:959]        = 0x%016llx\n",(bc->field_0).asU64[0xe]);
  printf("RESERVED BITS[960:1023]       = 0x%016llx\n",(bc->field_0).asU64[0xf]);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06033c74
 * symbol: show
 * prototype: int show(void)
 * body addresses: 304
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int show(void)

{
  undefined8 uVar1;
  undefined8 *puVar2;
  
  printf("%s()\n",&DAT_0011d295);
  printf("SP: 0x%08llx in stack [0x%08lx:0x%08lx]\n",&stack0xffffffffffffffd0,0x4a24000,0x4a26000);
  uVar1 = dczid_el0;
  printf("DCZID_EL0: 0x%08llx\n",uVar1);
  printf("bc=%p\n",&core0_boot_config);
  IoController_BootConfiguration_print(&core0_boot_config);
  for (puVar2 = (undefined8 *)&DAT_40000000; (ulong)puVar2 >> 0x15 < 0x215;
      puVar2 = puVar2 + 0x40000) {
    printf("%s: check Titania Buffer: %p = %#x\n",&DAT_0011d295,puVar2,*puVar2);
  }
  printf("%s: check Titania MMIO: %p = %#x\n",&DAT_0011d295,0x3800000,_DAT_03800000);
  printf("%s: check Titania MMIO: %p = %#x\n",&DAT_0011d295,&DAT_03800008,(ulong)_DAT_03800008);
  for (puVar2 = (undefined8 *)&DAT_30000000; (ulong)puVar2 >> 0x15 < 0x181;
      puVar2 = puVar2 + 0x40000) {
    printf("%s: check IO DRAM DATA: %p = %#x\n",&DAT_0011d295,puVar2,*puVar2);
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06033da4
 * symbol: io_controller_dram_entry
 * prototype: int io_controller_dram_entry(uint32_t cp_param2)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int io_controller_dram_entry(uint32_t cp_param2)

{
  int iVar1;
  
  dev_context_init(&g_dev_context_io,&g_sttyp_putchar_context_io,1,cp_param2,buf,0x200,
                   (mp4_debug_status_t *)0x3c00000);
  printf("%s()\n","io_controller_dram_entry");
  io_controller_dram();
  printf("%s: Loader Version 0x%08x: 0x%08x\n","io_controller_dram",0x401,10);
  show();
  printf("%s:test MSI: 0x%016lx - 0x%08x\n","io_controller_dram",0x3000000,
         (ulong)(byte)core0_boot_config.field_0.asU64[4]._4_1_);
  for (iVar1 = 10; iVar1 != 0; iVar1 = iVar1 + -1) {
    _DAT_03000000 = (uint)(byte)core0_boot_config.field_0.asU64[4]._4_1_;
  }
  controller_dram();
  io_controller_dev();
  controller_dev();
  io_controller_sram();
  printf("%s:STOP HERE\n","io_controller_dram");
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06033df4
 * symbol: io_controller_dram
 * prototype: int io_controller_dram(void)
 * body addresses: 152
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int io_controller_dram(void)

{
  int iVar1;
  
  printf("%s: Loader Version 0x%08x: 0x%08x\n","io_controller_dram",0x401,10);
  show();
  printf("%s:test MSI: 0x%016lx - 0x%08x\n","io_controller_dram",0x3000000,
         (ulong)(byte)core0_boot_config.field_0.asU64[4]._4_1_);
  for (iVar1 = 10; iVar1 != 0; iVar1 = iVar1 + -1) {
    _DAT_03000000 = (uint)(byte)core0_boot_config.field_0.asU64[4]._4_1_;
  }
  controller_dram();
  io_controller_dev();
  controller_dev();
  io_controller_sram();
  printf("%s:STOP HERE\n","io_controller_dram");
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


