/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/../../controller/io_controller/a53_zcn_driver.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601ac44
 * symbol: zcnDriverAddCommandsCopyBuffer
 * prototype: uint32_t zcnDriverAddCommandsCopyBuffer(ZcnDriver * zcnDriver, uint64_t vaSramCacheBase, ZcnCommandInfo deviceOpSource_notify, uint64_t mp4paSrc, uint64_t mp4paDst, uint16_t pasidSrcDst, uint64_t cycleSrcBufferAvailable, IoTraceCommandSource io_trace_source)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::IOC::zcnDriverAddCommandsCopyBuffer
                   (ZcnDriver *zcnDriver,uint64_t vaSramCacheBase,
                   ZcnCommandInfo deviceOpSource_notify,uint64_t mp4paSrc,uint64_t mp4paDst,
                   uint16_t pasidSrcDst,uint64_t cycleSrcBufferAvailable,
                   IoTraceCommandSource io_trace_source)

{
  uint32_t uVar1;
  
  uVar1 = zcnDriverAddCommandsCopyBufferPartial
                    (zcnDriver,vaSramCacheBase,deviceOpSource_notify,deviceOpSource_notify,mp4paSrc,
                     mp4paDst,0x10000,pasidSrcDst,cycleSrcBufferAvailable,io_trace_source);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601bf40
 * symbol: zcnDriverAllocateZcnOutputBuffer
 * prototype: ZcnAllocateResult zcnDriverAllocateZcnOutputBuffer(ZcnDriver * zcnDriver, uint64_t vaSramCacheBase, ZcnCommandInfo commandInfo_lock)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ZcnAllocateResult
A53::IOC::zcnDriverAllocateZcnOutputBuffer
          (ZcnDriver *zcnDriver,uint64_t vaSramCacheBase,ZcnCommandInfo commandInfo_lock)

{
  ZcnAllocateResult ZVar1;
  InnerBlockCacheId unaff_w21;
  bool local_14 [4];
  
  local_14[0] = false;
  ZVar1 = zcnDriverAllocateZcnOutputBuffer
                    (zcnDriver,vaSramCacheBase,commandInfo_lock,unaff_w21,local_14);
  return ZVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601f46c
 * symbol: zcnDriverAddMissToZcnOuterBlockCache
 * prototype: void zcnDriverAddMissToZcnOuterBlockCache(ZcnDriver * zcnDriver, ZcnOuterBlockCachePipeline ePipeline)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IOC::zcnDriverAddMissToZcnOuterBlockCache
               (ZcnDriver *zcnDriver,ZcnOuterBlockCachePipeline ePipeline)

{
  uint32_t uStack_14;
  
  zcnDriverCheckZcnOuterBlockCache
            (zcnDriver,ePipeline,(OuterBlockCacheId)0xffffffffffffffff,
             kZcnDriverCheckZcnOuterBlockCacheMissForcedAdvanceCache,&uStack_14);
  return;
}


