/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/../../controller/io_controller/a53_nvm_ttn.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06031b78
 * symbol: ttnBuildAdminCommandMediaScan
 * prototype: void ttnBuildAdminCommandMediaScan(NvmSqe * out_cmd, uint16_t cid, uint32_t nsid, NvmTtnMediaScanControl eControl, uint64_t startLbaOrSuperblock, uint32_t count)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::ttnBuildAdminCommandMediaScan
               (NvmSqe *out_cmd,uint16_t cid,uint32_t nsid,NvmTtnMediaScanControl eControl,
               uint64_t startLbaOrSuperblock,uint32_t count)

{
  uint uVar1;
  uint uVar2;
  
  nvmZeroSqe(out_cmd);
  uVar1 = (out_cmd->field_0).asU32[0];
  *(undefined *)((long)&out_cmd->field_0 + 0x30) = 0x1b;
  (out_cmd->field_0).asU32[0] = uVar1 & 0xff00 | (uint)cid << 0x10 | 0xc0;
  (out_cmd->field_0).field_0.NSID = nsid;
  if (eControl == kNvmTtnMediaScanControlStart) {
    uVar1 = count & 0xffffff;
    uVar2 = 0;
    if (nsid != 1) {
      count = (uint32_t)(startLbaOrSuperblock >> 0x20);
      uVar2 = uVar1;
    }
    (out_cmd->field_0).asU32[0xd] = uVar2;
    (out_cmd->field_0).asU32[0xe] = (uint32_t)startLbaOrSuperblock;
    (out_cmd->field_0).asU32[0xf] = count;
  }
  else {
    (out_cmd->field_0).asU32[0xd] = eControl << 0x1f;
  }
  return;
}


