/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/../../controller/io_controller/a53_ioc_bootconfiguration.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060133c8
 * symbol: IoController_BootConfiguration_getTitaniaMemory
 * prototype: void IoController_BootConfiguration_getTitaniaMemory(uint64_t vaSramBootConfiguration, uint64_t * out_ttnvaTitania, uint64_t * out_sizeTitania, uint64_t * out_paSyshubTitania)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_getTitaniaMemory
               (uint64_t vaSramBootConfiguration,uint64_t *out_ttnvaTitania,
               uint64_t *out_sizeTitania,uint64_t *out_paSyshubTitania)

{
  IoController_BootConfiguration_Titania_getTitaniaMemory
            (vaSramBootConfiguration + 0x50,out_ttnvaTitania,out_sizeTitania,out_paSyshubTitania);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029594
 * symbol: IoController_BootConfiguration_Titania_getTitaniaMemory
 * prototype: void IoController_BootConfiguration_Titania_getTitaniaMemory(uint64_t vaSramBootConfiguration_Titania, uint64_t * out_ttnvaTitania, uint64_t * out_sizeTitania, uint64_t * out_paSyshubTitania)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_Titania_getTitaniaMemory
               (uint64_t vaSramBootConfiguration_Titania,uint64_t *out_ttnvaTitania,
               uint64_t *out_sizeTitania,uint64_t *out_paSyshubTitania)

{
  ulong uVar1;
  
  uVar1 = *(ulong *)vaSramBootConfiguration_Titania;
  *out_ttnvaTitania = (uVar1 & 0xffffffff) << 0x10;
  *out_sizeTitania = uVar1 >> 0x20 & 0xffff0000;
  *out_paSyshubTitania = (uVar1 >> 0x10 & 0xffff0000) + 0x4000000;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06029c44
 * symbol: IoController_BootConfiguration_getZcnVaTitaniaAndSyshubMmio
 * prototype: void IoController_BootConfiguration_getZcnVaTitaniaAndSyshubMmio(uint64_t vaSramBootConfiguration, uint64_t * out_zcnvaTitania, uint64_t * out_paSyshubMmioTitania)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_getZcnVaTitaniaAndSyshubMmio
               (uint64_t vaSramBootConfiguration,uint64_t *out_zcnvaTitania,
               uint64_t *out_paSyshubMmioTitania)

{
  IoController_BootConfiguration_Titania_getZcnVaTitaniaAndSyshubMmio
            (vaSramBootConfiguration + 0x50,out_zcnvaTitania,out_paSyshubMmioTitania);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602a434
 * symbol: IoController_BootConfiguration_getTitaniaRingSizes
 * prototype: void IoController_BootConfiguration_getTitaniaRingSizes(uint64_t vaSramBootConfiguration, uint16_t * out_aTitaniaRingSize)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_getTitaniaRingSizes
               (uint64_t vaSramBootConfiguration,uint16_t *out_aTitaniaRingSize)

{
  IoController_BootConfiguration_Titania_getTitaniaRingSizes
            (vaSramBootConfiguration + 0x50,out_aTitaniaRingSize);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602a728
 * symbol: IoController_BootConfiguration_getRingSizes
 * prototype: void IoController_BootConfiguration_getRingSizes(uint64_t vaSramBootConfiguration, uint8_t * out_numElementsLog2InterruptContextRing, uint8_t * out_aNumElementsLog2CommandRing)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_getRingSizes
               (uint64_t vaSramBootConfiguration,uint8_t *out_numElementsLog2InterruptContextRing,
               uint8_t *out_aNumElementsLog2CommandRing)

{
  A53Controller_BootConfiguration_KernelShared_getRingSizes
            (vaSramBootConfiguration,out_numElementsLog2InterruptContextRing,0x16,
             out_aNumElementsLog2CommandRing);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602a738
 * symbol: IoController_BootConfiguration_getPaDebugRingSizes
 * prototype: void IoController_BootConfiguration_getPaDebugRingSizes(uint64_t vaSramBootConfiguration, uint8_t * out_aNumElementsLog2PaDebugOutputRing)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_getPaDebugRingSizes
               (uint64_t vaSramBootConfiguration,uint8_t *out_aNumElementsLog2PaDebugOutputRing)

{
  A53Controller_BootConfiguration_KernelShared_getPaDebugRingSizes
            (vaSramBootConfiguration,2,out_aNumElementsLog2PaDebugOutputRing);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f388
 * symbol: IoController_BootConfiguration_Titania_getZcnVaTitaniaAndSyshubMmio
 * prototype: void IoController_BootConfiguration_Titania_getZcnVaTitaniaAndSyshubMmio(uint64_t vaSramBootConfiguration_Titania, uint64_t * out_zcnvaTitania, uint64_t * out_paSyshubMmioTitania)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_Titania_getZcnVaTitaniaAndSyshubMmio
               (uint64_t vaSramBootConfiguration_Titania,uint64_t *out_zcnvaTitania,
               uint64_t *out_paSyshubMmioTitania)

{
  ulong uVar1;
  
  uVar1 = *(ulong *)(vaSramBootConfiguration_Titania + 0x10);
  *out_paSyshubMmioTitania =
       (*(ulong *)(vaSramBootConfiguration_Titania + 0x18) >> 2 & 0xfffff000) + 0x4000000;
  *out_zcnvaTitania = (uVar1 & 0xffffffff) << 0x10;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602f3ac
 * symbol: IoController_BootConfiguration_Titania_getTitaniaRingSizes
 * prototype: void IoController_BootConfiguration_Titania_getTitaniaRingSizes(uint64_t vaSramBootConfiguration_Titania, uint16_t * out_aTitaniaRingSize)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::IoController_BootConfiguration_Titania_getTitaniaRingSizes
               (uint64_t vaSramBootConfiguration_Titania,uint16_t *out_aTitaniaRingSize)

{
  ulong uVar1;
  
  uVar1 = *(ulong *)(vaSramBootConfiguration_Titania + 8);
  out_aTitaniaRingSize[1] = (ushort)((uint)uVar1 >> 9) & 0x1ff;
  out_aTitaniaRingSize[2] = (ushort)(uVar1 >> 0x10) >> 2 & 0x1ff;
  out_aTitaniaRingSize[3] = (ushort)(uVar1 >> 0x1b) & 0x1ff;
  out_aTitaniaRingSize[4] = (ushort)(uVar1 >> 0x24) & 0x1ff;
  *out_aTitaniaRingSize = (ushort)uVar1 & 0x1ff;
  out_aTitaniaRingSize[5] = (ushort)(uVar1 >> 0x2d) & 0x1ff;
  return;
}


