/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller\a53_io_controller_io_trace.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604cba4
 * symbol: io_trace_getIoTraceCommandSource
 * prototype: IoTraceCommandSource io_trace_getIoTraceCommandSource(IoController * this, DeviceOpSource source)
 * body addresses: 816
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Type propagation algorithm not settling */
/* DWARF original prototype: IoTraceCommandSource io_trace_getIoTraceCommandSource(IoController *
   this, DeviceOpSource source) */

IoTraceCommandSource __thiscall
A53::IOC::IoController::io_trace_getIoTraceCommandSource(IoController *this,DeviceOpSource source)

{
  IoPipeline eIoPipeline;
  uint uVar1;
  IoDramPipeline eIoDramPipeline;
  bool bVar2;
  uint32_t uVar3;
  anon_union_8_3_e9e78e08_for_IoTraceCommandSource_0 aVar4;
  ushort uVar5;
  ulong in_x1;
  uint uVar6;
  undefined4 uVar7;
  long lVar8;
  IoPipeline IVar9;
  uint16_t pipelineCommandId;
  uint uVar10;
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_60;
  undefined4 uStack_5c;
  uint32_t local_58;
  ConstSramRingView local_50;
  anon_union_4_6_678d1698_for_IoDeviceOpHeader_0 local_38 [2];
  
  uVar10 = (uint)in_x1;
  if ((uVar10 >> 0x1e & 1) == 0) {
    return (IoTraceCommandSource)0xf800;
  }
  uVar6 = uVar10 >> 0x1b & 7;
  if (uVar6 - 5 < 2) {
    bVar2 = (uVar10 & 0x38000000) != 0x28000000;
    uVar6 = 0x10;
    if (bVar2) {
      uVar6 = 0x17;
    }
    IVar9 = kIoPipelineAdmin|kIoPipelineExtFs;
    if (bVar2) {
      IVar9 = kIoPipelineAdmin;
    }
    IVar9 = uVar10 >> (ulong)uVar6 & IVar9;
    uVar5 = 0x7fff;
    if (bVar2) {
      uVar5 = 0x3fff;
    }
    eIoPipeline = IVar9;
    if (kIoPipelineNSID3 < IVar9) {
      eIoPipeline = kIoPipelineAdmin|kIoPipelineExtFs;
    }
    bVar2 = getIoDeviceOpHeader(this,eIoPipeline,uVar5 & (ushort)in_x1,
                                (IoDeviceOpHeader *)&local_38[0].field_0);
    if (!bVar2) {
      return (IoTraceCommandSource)0xf800;
    }
    if ((local_38[0].asU32 >> 0xf & 1) == 0) {
      return (IoTraceCommandSource)0xf800;
    }
    if ((int)local_38[0] < 0) {
      uVar6 = local_38[0].asU32 >> 0x1b & 0xf;
      bVar2 = 2 < eIoPipeline + ~kIoPipelineNSID2W;
      if ((bVar2 || 8 < uVar6) && (bVar2 || uVar6 != 9)) {
        return (IoTraceCommandSource)0xf800;
      }
      uVar10 = uVar6 + 0xc;
      uVar5 = (ushort)((uint)local_38[0] >> 0x10);
      if (uVar10 < 0xf) {
        bVar2 = getSysNsid2CommandRingExecutingCommand
                          ((ConstSramRingView *)
                           (&DAT_00001140 +
                           (long)&this->m_aInputRing[0].field_0 + (ulong)uVar10 * 0xc),uVar5 & 0x7ff
                           ,(SysNsid2CommandRingExecutingCommand *)&local_50);
        if (!bVar2) {
          return (IoTraceCommandSource)0xf800;
        }
        uVar10 = local_50.field_0.field_0.m_vaSramRing >> 0xf & 0x7fff;
        if ((local_50.field_0.field_0.m_vaSramRing >> 0x1e != IVar9 + ~kIoPipelineNSID1 ||
            (local_50.field_0.field_0.m_vaSramRing & 0x7fff) != 0x7fff) || uVar10 == 0x7fff) {
          return (IoTraceCommandSource)0xf800;
        }
      }
      else {
        bVar2 = getCommandRingExecutingCommand
                          ((ConstSramRingView *)
                           (&DAT_00001140 +
                           (long)&this->m_aInputRing[0].field_0 + (ulong)uVar10 * 0xc),uVar5 & 0x7ff
                           ,(CommandRingExecutingCommand *)&local_50);
        if (!bVar2) {
          return (IoTraceCommandSource)0xf800;
        }
        if (-1 < (short)local_50.field_0.field_0.m_vaSramRing._0_2_) {
          return (IoTraceCommandSource)0xf800;
        }
        uVar10 = (int)(short)local_50.field_0.field_0.m_vaSramRing._0_2_ & 0x7fff;
        if (uVar10 == 0x7fff) {
          return (IoTraceCommandSource)0xf800;
        }
      }
      if (uVar10 >> 0xe != 0) {
        lVar8 = (long)&this->m_aInputRing[0].field_0 + (ulong)uVar6 * 0xc;
        uVar10 = uVar10 & 0x3fff;
        local_50.field_0.asU32[2] = *(undefined4 *)(&DAT_00001250 + lVar8);
        local_50.field_0._0_8_ = *(undefined8 *)(&DAT_00001248 + lVar8);
        goto LAB_0604ccb0;
      }
    }
    else {
      uVar10 = local_38[0].asU32 >> 0x10 & 0x7fff;
    }
    InputRing::getSramRingViewOfCache<14>(this->m_aInputRing_PipelineCommandData_OpConsume + IVar9);
    local_50.field_0._0_8_ = CONCAT44(uStack_5c,local_60.asU32);
    local_50.field_0.asU32[2] = local_58;
  }
  else {
    if (uVar6 == 4) {
      uVar5 = (ushort)in_x1 & 0x7ff;
      uVar6 = uVar10 >> 0xb & 0x1f;
      eIoDramPipeline = uVar10 >> 0x10 & 0xf;
      if (uVar6 - 0xb < 4) {
        bVar2 = getSysNsid2CommandRingExecutingCommand
                          ((ConstSramRingView *)
                           (&DAT_00001140 +
                           (long)&this->m_aInputRing[0].field_0 + (ulong)uVar6 * 0xc),uVar5,
                           (SysNsid2CommandRingExecutingCommand *)&local_50);
        if (!bVar2) {
          return (IoTraceCommandSource)0xf800;
        }
        uVar1 = eIoDramPipeline + ~kIoDramPipelineNSID1;
        if (uVar1 == 0) {
          uVar1 = 1;
        }
        if (local_50.field_0.field_0.m_vaSramRing >> 0x1e != uVar1) {
          return (IoTraceCommandSource)0xf800;
        }
        uVar7 = local_50.field_0.field_0.m_vaSramRing;
        if (eIoDramPipeline != kIoDramPipelineNSID2W) {
          uVar7 = local_50.field_0.field_0.m_vaSramRing >> 0xf;
        }
      }
      else {
        bVar2 = getCommandRingExecutingCommand
                          ((ConstSramRingView *)
                           (&DAT_00001140 +
                           (long)&this->m_aInputRing[0].field_0 + (ulong)uVar6 * 0xc),uVar5,
                           (CommandRingExecutingCommand *)&local_50);
        if (!bVar2) {
          return (IoTraceCommandSource)0xf800;
        }
        uVar7 = (int)(short)local_50.field_0.field_0.m_vaSramRing._0_2_;
        if (-1 < (short)local_50.field_0.field_0.m_vaSramRing._0_2_) {
          return (IoTraceCommandSource)0xf800;
        }
      }
      uVar1 = uVar7 & 0x7fff;
      pipelineCommandId = (uint16_t)uVar1;
      if (uVar1 == 0x7fff) {
        return (IoTraceCommandSource)0xf800;
      }
      if ((uVar6 < 0xc) || (((uVar10 & 0x1e00000) != 0x1c00000 && (uVar1 >> 0xe == 0)))) {
        if ((uVar10 >> 0x14 & 1) == 0) {
          getConstSramRingView_PipelineCommandData_DramPipeline_OpIssue(this,eIoDramPipeline);
        }
        else {
          InputRing::getSramRingViewOfCache<14>
                    (this->m_aInputRing_PipelineCommandData_OpConsume + eIoDramPipeline);
        }
        local_50.field_0.asU32[2] = local_58;
        local_50.field_0._0_8_ = CONCAT44(uStack_5c,local_60.asU32);
      }
      else {
        lVar8 = (long)&this->m_aInputRing[0].field_0 + (long)(int)uVar6 * 0xc;
        pipelineCommandId = (ushort)uVar7 & 0x3fff;
        local_50.field_0.asU32[2] = *(undefined4 *)(&DAT_000011c0 + lVar8);
        local_50.field_0._0_8_ = *(undefined8 *)(&DAT_000011b8 + lVar8);
      }
      goto LAB_0604ccbc;
    }
    if (uVar6 != 3) {
      return (IoTraceCommandSource)0xf800;
    }
    lVar8 = (long)&this->m_aInputRing[0].field_0 + (in_x1 >> 0x10 & 0xf) * 0xc;
    uVar10 = uVar10 & 0x7fff;
    local_50.field_0.asU32[2] = *(undefined4 *)(&DAT_000012c8 + lVar8);
    local_50.field_0._0_8_ = *(undefined8 *)(&DAT_000012c0 + lVar8);
  }
LAB_0604ccb0:
  pipelineCommandId = (uint16_t)uVar10;
  if (uVar10 == 0x7fff) {
    return (IoTraceCommandSource)0xf800;
  }
LAB_0604ccbc:
  bVar2 = getPipelineCommandDataHeader
                    (&local_50,pipelineCommandId,(PipelineCommandDataHeader *)&local_60.field_0);
  if ((bVar2) && ((local_60.asU32 >> 6 & 1) == 0)) {
    if ((local_60.asU32 >> 5 & 1) == 0) {
      uVar3 = getPipelineCommandData_pid(&local_50,pipelineCommandId);
    }
    else {
      uVar3 = (this->m_runtime_config).field_0.field_0.m_pidApp;
    }
    aVar4.field_0.m_pid = uVar3;
    aVar4.asU32[0] = local_60.asU32 >> 0x10 & 0xf800 | local_60.asU32 & 0x7ff0000;
    return (IoTraceCommandSource)aVar4;
  }
  return (IoTraceCommandSource)(anon_union_8_3_e9e78e08_for_IoTraceCommandSource_0)0xf800;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604ced4
 * symbol: io_trace_write_event_InputRingStatus
 * prototype: void io_trace_write_event_InputRingStatus(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, uint32_t maskCommandRingsHalting, uint32_t maskCommandRingsIdle)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_InputRingStatus(IoController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, uint32_t maskCommandRingsHalting, uint32_t
   maskCommandRingsIdle) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_InputRingStatus
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          uint32_t maskCommandRingsHalting,uint32_t maskCommandRingsIdle)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_20;
  uint local_18;
  uint uStack_14;
  
  local_18 = maskCommandRingsHalting & 0x3fffff;
  local_20 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | 0x81);
  uStack_14 = maskCommandRingsIdle & 0x3fffff;
  io_trace_write_event(this,rings,(IoTraceEventHeader *)&local_20.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604cf0c
 * symbol: io_trace_write_event
 * prototype: void io_trace_write_event(IoController * this, ControllerRings * rings, IoTraceEventHeader * pHeaderAndData)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event(IoController * this, ControllerRings * rings,
   IoTraceEventHeader * pHeaderAndData) */

void __thiscall
A53::IOC::IoController::io_trace_write_event
          (IoController *this,ControllerRings *rings,IoTraceEventHeader *pHeaderAndData)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,pHeaderAndData);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604cf60
 * symbol: io_trace_write_event_CommandExecuteResume
 * prototype: void io_trace_write_event_CommandExecuteResume(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, IoControllerExecutionPipeline ePipeline)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_CommandExecuteResume(IoController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t
   commandRingExecutingCommandId, IoControllerExecutionPipeline ePipeline) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_CommandExecuteResume
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId,
          IoControllerExecutionPipeline ePipeline)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_20;
  uint local_18;
  
  local_20 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)commandRingExecutingCommandId << 0x10 |
             (ulong)((eSource & 0x1f) << 0xb | 0x4e));
  local_18 = ePipeline & 0xf;
  io_trace_write_event(this,rings,(IoTraceEventHeader *)&local_20.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604cfa4
 * symbol: io_trace_write_event_CommandExecuteSuspend
 * prototype: void io_trace_write_event_CommandExecuteSuspend(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, IoControllerExecutionPipeline ePipeline, IoControllerCommandRing eSourcePreempting, uint16_t commandRingExecutingCommandIdPreempting)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_CommandExecuteSuspend(IoController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t
   commandRingExecutingCommandId, IoControllerExecutionPipeline ePipeline, IoControllerCommandRing
   eSourcePreempting, uint16_t commandRingExecutingCommandIdPreempting) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_CommandExecuteSuspend
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId,
          IoControllerExecutionPipeline ePipeline,IoControllerCommandRing eSourcePreempting,
          uint16_t commandRingExecutingCommandIdPreempting)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_20;
  uint local_18;
  
  local_20 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)commandRingExecutingCommandId << 0x10 |
             (ulong)((eSource & 0x1f) << 0xb | 0x4f));
  local_18 = (uint)commandRingExecutingCommandIdPreempting | (ePipeline & 0xf) << 0x10 |
             (eSourcePreempting & 0x1f) << 0x14;
  io_trace_write_event(this,rings,(IoTraceEventHeader *)&local_20.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604cff0
 * symbol: io_trace_write_event_OnCommandCompletion_SramPipeline
 * prototype: void io_trace_write_event_OnCommandCompletion_SramPipeline(IoController * this, ControllerRings * rings, IoControllerExecutionPipeline ePipeline, ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader pipelineCmdDataHeader)
 * body addresses: 212
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_OnCommandCompletion_SramPipeline(IoController
   * this, ControllerRings * rings, IoControllerExecutionPipeline ePipeline, ConstSramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader
   pipelineCmdDataHeader) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_OnCommandCompletion_SramPipeline
          (IoController *this,ControllerRings *rings,IoControllerExecutionPipeline ePipeline,
          ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
          PipelineCommandDataHeader pipelineCmdDataHeader)

{
  uint32_t uVar1;
  ushort commandRingExecutingCommandId;
  uint64_t uVar2;
  uint in_w5;
  undefined4 uStack_50;
  uint32_t local_4c;
  ulong local_48;
  
  getPipelineCommandDataElements(sramRingView_PipelineCommandData,pipelineCommandId,0,4,&uStack_50);
  uVar1 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
  if (uVar1 == 0xffffffff || uVar1 == local_4c) {
    uVar2 = readSystemClock(this);
    commandRingExecutingCommandId = (ushort)(in_w5 >> 0x10) & 0x7ff;
    if ((in_w5 & 0x300) == 0) {
      io_trace_write_event_CommandExecuteEnd
                (this,rings,(uint32_t)uVar2,in_w5 >> 0x1b,commandRingExecutingCommandId,local_4c,
                 (uint32_t)(local_48 >> 0x20));
    }
    else {
      io_trace_write_event_CommandExecuteEndError
                (this,rings,(uint32_t)uVar2,in_w5 >> 0x1b,commandRingExecutingCommandId,local_4c,
                 ((uint)local_48 >> 7 ^ 0xffffffff) & 1,(byte)(local_48 >> 8) & 0x7f,
                 local_48 >> 0x10,uStack_50._2_2_);
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d0c4
 * symbol: io_trace_write_event_CommandExecuteEnd
 * prototype: void io_trace_write_event_CommandExecuteEnd(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, uint32_t pid, uint32_t returnValue)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_CommandExecuteEnd(IoController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t
   commandRingExecutingCommandId, uint32_t pid, uint32_t returnValue) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_CommandExecuteEnd
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId,uint32_t pid,
          uint32_t returnValue)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_CommandExecuteEnd
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,
             commandRingExecutingCommandId,pid,returnValue);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d150
 * symbol: io_trace_write_event_CommandExecuteEndError
 * prototype: void io_trace_write_event_CommandExecuteEndError(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, uint32_t pid, IoTraceIsAppErrorCode eIsAppErrorCode, uint8_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 164
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_CommandExecuteEndError(IoController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t
   commandRingExecutingCommandId, uint32_t pid, IoTraceIsAppErrorCode eIsAppErrorCode, uint8_t
   eErrorCode, uint64_t addressError, uint16_t pasidError) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_CommandExecuteEndError
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId,uint32_t pid,
          IoTraceIsAppErrorCode eIsAppErrorCode,uint8_t eErrorCode,uint64_t addressError,
          uint16_t pasidError)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_CommandExecuteEndError
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,
             commandRingExecutingCommandId,pid,eIsAppErrorCode,eErrorCode,addressError,pasidError);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d1f4
 * symbol: io_trace_write_event_OnCommandCompletion_DramPipeline
 * prototype: void io_trace_write_event_OnCommandCompletion_DramPipeline(IoController * this, ControllerRings * rings, IoControllerExecutionPipeline ePipeline, ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader pipelineCmdDataHeader)
 * body addresses: 340
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_OnCommandCompletion_DramPipeline(IoController
   * this, ControllerRings * rings, IoControllerExecutionPipeline ePipeline, ConstSramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader
   pipelineCmdDataHeader) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_OnCommandCompletion_DramPipeline
          (IoController *this,ControllerRings *rings,IoControllerExecutionPipeline ePipeline,
          ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
          PipelineCommandDataHeader pipelineCmdDataHeader)

{
  ushort uVar1;
  byte bVar2;
  uint32_t uVar3;
  uint in_w5;
  uint uVar5;
  uint32_t pid;
  undefined4 uStack_58;
  uint32_t local_54;
  ulong local_50;
  ulong local_48;
  uint64_t uVar4;
  
  uVar1 = (ushort)(in_w5 >> 0x10);
  if ((in_w5 >> 5 & 1) == 0) {
    getPipelineCommandDataElements
              (sramRingView_PipelineCommandData,pipelineCommandId,0,4,&uStack_58);
    uVar3 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
    if (uVar3 != 0xffffffff && uVar3 != local_54) {
      return;
    }
    uVar4 = readSystemClock(this);
    uVar3 = (uint32_t)uVar4;
    local_48 = local_50;
    if ((in_w5 & 0x300) == 0) {
LAB_0604d300:
      io_trace_write_event_CommandExecuteEnd
                (this,rings,uVar3,in_w5 >> 0x1b,uVar1 & 0x7ff,local_54,(uint32_t)(local_48 >> 0x20))
      ;
      return;
    }
    uVar5 = (uint)local_50;
    bVar2 = (byte)(local_50 >> 8);
    pid = local_54;
  }
  else {
    uVar3 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
    pid = (this->m_runtime_config).field_0.field_0.m_pidApp;
    if (uVar3 != 0xffffffff && pid != uVar3) {
      return;
    }
    getPipelineCommandDataElements
              (sramRingView_PipelineCommandData,pipelineCommandId,0,6,&uStack_58);
    uVar4 = readSystemClock(this);
    uVar3 = (uint32_t)uVar4;
    local_54 = pid;
    if ((in_w5 & 0x300) == 0) goto LAB_0604d300;
    uVar5 = (uint)local_48;
    bVar2 = (byte)(local_48 >> 8);
    local_50 = local_48;
    if ((uVar5 >> 0xf & 1) == 0) {
      uStack_58._2_2_ = 0;
    }
    else {
      uStack_58._2_2_ = (this->m_runtime_config).field_0.field_0.m_pasidIndirect;
    }
  }
  io_trace_write_event_CommandExecuteEndError
            (this,rings,uVar3,in_w5 >> 0x1b,uVar1 & 0x7ff,pid,(uVar5 >> 7 ^ 0xffffffff) & 1,
             bVar2 & 0x7f,local_50 >> 0x10,uStack_58._2_2_);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d348
 * symbol: io_trace_write_event_executeSopCommandsAndPreParseNextCommand
 * prototype: void io_trace_write_event_executeSopCommandsAndPreParseNextCommand(IoController * this, ControllerRings * rings, ControllerPipelineCommon * pipeline, uint32_t iCommandRing, A53ControllerTraceEventType eEventType, A53ControllerCommandHeader cmdHeader, A53ControllerCommandHasPid eHasPid, uint32_t errorCode_or_returnValue)
 * body addresses: 780
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void
   io_trace_write_event_executeSopCommandsAndPreParseNextCommand(IoController * this,
   ControllerRings * rings, ControllerPipelineCommon * pipeline, uint32_t iCommandRing,
   A53ControllerTraceEventType eEventType, A53ControllerCommandHeader cmdHeader,
   A53ControllerCommandHasPid eHasPid, uint32_t errorCode_or_returnValue) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_executeSopCommandsAndPreParseNextCommand
          (IoController *this,ControllerRings *rings,ControllerPipelineCommon *pipeline,
          uint32_t iCommandRing,A53ControllerTraceEventType eEventType,
          A53ControllerCommandHeader cmdHeader,A53ControllerCommandHasPid eHasPid,
          uint32_t errorCode_or_returnValue)

{
  uint32_t uVar1;
  uint uVar2;
  uint32_t timestamp100MHz;
  uint64_t uVar3;
  uint32_t uVar4;
  IoController_InputRingWithIndirectBufferHead *pIVar5;
  ushort ibCommandId;
  uint32_t aCmdData [15];
  uint32_t local_a4 [15];
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_68 [2];
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_58 [2];
  
  local_58[0] = cmdHeader.field_0;
  uVar3 = readSystemClock(this);
  uVar2 = iCommandRing - 0xf;
  if (uVar2 < 7) {
    pIVar5 = this->m_aInputRingHeadIb + uVar2;
    ibCommandId = *(ushort *)((long)&this->m_aInputRingHeadIb[uVar2].field_0 + 2) & 0x1fff;
  }
  else {
    ibCommandId = this->m_aInputRing[iCommandRing].field_0.field_0.m_head;
    pIVar5 = (IoController_InputRingWithIndirectBufferHead *)0x0;
  }
  timestamp100MHz = (uint32_t)uVar3;
  switch(eEventType) {
  case kA53ControllerTraceEventTypeMarker:
  case kA53ControllerTraceEventTypeCommandExecuteBegin:
    uVar2 = (uint)cmdHeader.field_0 >> 8 & 0xf;
    if (uVar2 != 0) {
      peekCommandDataElements(rings,iCommandRing,0,uVar2,local_a4);
    }
    if (eEventType == kA53ControllerTraceEventTypeMarker) {
      io_trace_write_event_Marker
                (this,rings,timestamp100MHz,iCommandRing,ibCommandId,
                 (A53ControllerCommandHeader *)&local_58[0].field_0,local_a4);
    }
    else {
      local_68[0].field_0 = local_58[0].field_0;
      if (eHasPid == kA53ControllerCommandDefaultPid) {
        uVar4 = 0;
      }
      else {
        uVar4 = local_a4[(local_58[0].asU32 >> 8 & 0xf) - 1];
        local_68[0].asU32 =
             local_58[0].asU32 & 0xfffff000 |
             local_58[0].asU32 & 0xff | (local_58[0].asU32 + 0xf00 >> 8 & 0xf) << 8;
      }
      uVar1 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
      if ((uVar1 == 0) || (uVar4 == uVar1)) {
        io_trace_write_event_CommandExecuteBegin
                  (this,rings,timestamp100MHz,iCommandRing,ibCommandId,0xffff,0xf,uVar4,
                   (A53ControllerCommandHeader *)&local_68[0].field_0,local_a4);
      }
    }
    break;
  case kA53ControllerTraceEventTypeIbResume:
    uVar3 = (pIVar5->field_0).asU64[0];
    io_trace_write_event_IbResume
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId - 4,
               (pIVar5->field_0).asU64[1] >> 0x10,
               (uint)(byte)(uVar3 >> 0x38) | ((uint)(pIVar5->field_0).asU64[1] & 0xffff) << 8,
               (uint16_t)uVar3,(uint)(uVar3 >> 0x20) & 0xffffff);
    break;
  case kA53ControllerTraceEventTypeIbCall:
    io_trace_write_event_IbCall
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId - 3,
               (pIVar5->field_0).asU64[1] >> 0x10,
               (uint)(byte)((pIVar5->field_0).asU64[0] >> 0x38) |
               ((uint)(pIVar5->field_0).asU64[1] & 0xffff) << 8,(uint16_t)(pIVar5->field_0).asU64[0]
              );
    return;
  case kA53ControllerTraceEventTypeIbChain:
    io_trace_write_event_IbChain
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId - 3,
               (pIVar5->field_0).asU64[1] >> 0x10,
               (uint)*(byte *)((long)&pIVar5->field_0 + 7) |
               ((uint)(pIVar5->field_0).asU64[1] & 0xffff) << 8);
    return;
  case kA53ControllerTraceEventTypeIbReturn:
    io_trace_write_event_IbReturn
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId,*(uint16_t *)&pIVar5->field_0);
    return;
  case kA53ControllerTraceEventTypeCommandExecuteEnd:
  case kA53ControllerTraceEventTypeCommandExecuteEndError:
    local_a4[0] = 0;
    if (eHasPid != kA53ControllerCommandDefaultPid) {
      peekCommandDataElements
                (rings,iCommandRing,((uint)cmdHeader.field_0 >> 8 & 0xf) - 1,1,local_a4);
    }
    uVar4 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
    if ((uVar4 == 0) || (local_a4[0] == uVar4)) {
      if (eEventType == kA53ControllerTraceEventTypeCommandExecuteEnd) {
        io_trace_write_event_CommandExecuteEnd
                  (this,rings,timestamp100MHz,iCommandRing,0xffff,local_a4[0],
                   errorCode_or_returnValue);
      }
      else {
        io_trace_write_event_CommandExecuteEndError
                  (this,rings,timestamp100MHz,iCommandRing,0xffff,local_a4[0],
                   errorCode_or_returnValue >> 7 & 1,(byte)errorCode_or_returnValue & 0x7f,0,0);
      }
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d654
 * symbol: io_trace_write_event_Marker
 * prototype: void io_trace_write_event_Marker(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t commandId, A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_Marker(IoController * this, ControllerRings *
   rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t commandId,
   A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_Marker
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t commandId,A53ControllerCommandHeader *cmdHeader,
          uint32_t *aCmdData)

{
  ulong uVar1;
  uint uVar2;
  A53ControllerCommandHeader *unaff_x29;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_Marker
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,commandId,unaff_x29,aCmdData
            );
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d6dc
 * symbol: io_trace_write_event_IbResume
 * prototype: void io_trace_write_event_IbResume(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation, uint32_t ibLocationStart)
 * body addresses: 156
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_IbResume(IoController * this, ControllerRings
   * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId,
   uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation, uint32_t
   ibLocationStart) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_IbResume
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t ibCommandId,uint64_t vaIndirectBufferBase,
          uint32_t numBufferElemsMinus1,uint16_t ringLocation,uint32_t ibLocationStart)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbResume
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,
             vaIndirectBufferBase,numBufferElemsMinus1,ringLocation,ibLocationStart);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d778
 * symbol: io_trace_write_event_IbCall
 * prototype: void io_trace_write_event_IbCall(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_IbCall(IoController * this, ControllerRings *
   rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId, uint64_t
   vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_IbCall
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t ibCommandId,uint64_t vaIndirectBufferBase,
          uint32_t numBufferElemsMinus1,uint16_t ringLocation)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbCall
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,
             vaIndirectBufferBase,numBufferElemsMinus1,ringLocation);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d80c
 * symbol: io_trace_write_event_IbChain
 * prototype: void io_trace_write_event_IbChain(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_IbChain(IoController * this, ControllerRings
   * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId,
   uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_IbChain
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t ibCommandId,uint64_t vaIndirectBufferBase,
          uint32_t numBufferElemsMinus1)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbChain
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,
             vaIndirectBufferBase,numBufferElemsMinus1);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d898
 * symbol: io_trace_write_event_IbReturn
 * prototype: void io_trace_write_event_IbReturn(IoController * this, ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId, uint16_t ringLocation)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_IbReturn(IoController * this, ControllerRings
   * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t ibCommandId,
   uint16_t ringLocation) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_IbReturn
          (IoController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          IoControllerCommandRing eSource,uint16_t ibCommandId,uint16_t ringLocation)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbReturn
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,ringLocation);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604d91c
 * symbol: io_trace_write_event_FlashIoCommand
 * prototype: void io_trace_write_event_FlashIoCommand(IoController * this, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, TtnSubmissionQueue eSq, uint16_t cid, uint32_t nvm_opc, uint64_t flashAddress, uint32_t outerBlockIdxInCommand)
 * body addresses: 292
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_FlashIoCommand(IoController * this,
   IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, TtnSubmissionQueue eSq,
   uint16_t cid, uint32_t nvm_opc, uint64_t flashAddress, uint32_t outerBlockIdxInCommand) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_FlashIoCommand
          (IoController *this,IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId
          ,TtnSubmissionQueue eSq,uint16_t cid,uint32_t nvm_opc,uint64_t flashAddress,
          uint32_t outerBlockIdxInCommand)

{
  uint32_t uVar1;
  uint64_t uVar2;
  ControllerRings local_e0;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_78;
  uint local_70;
  undefined4 uStack_6c;
  uint local_68;
  
  uVar2 = readSystemClock(this);
  uVar1 = NvmSubmissionQueue::getPosPutPrev((this->m_nvm).m_aSq + eSq);
  local_78 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)((eSource & 0x1f) << 0xb | 0xe0) | (ulong)commandRingExecutingCommandId << 0x10
             | uVar2 << 0x20);
  local_70 = (uint)cid << 0x10 |
             nvm_opc & 0x80 | eSq & 7 | (nvm_opc & 0xf) << 3 | (uVar1 & 0xff) << 8;
  local_68 = (uint)(flashAddress >> 0x20) & 0xff | outerBlockIdxInCommand << 8;
  uStack_6c = (undefined4)flashAddress;
  local_e0.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_e0.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_e0.m_pRingsState = &this->m_rings_state;
  local_e0.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_e0.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_e0.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_e0.m_paInputRingHead = this->m_aInputRingHead;
  local_e0.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_e0.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_e0.m_paOutputRing = this->m_aOutputRing;
  local_e0.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_e0.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_e0.m_paInputRing = this->m_aInputRing;
  local_e0.m_pContext_HandleControllerRingsEvent = this;
  io_trace_write_event(this,&local_e0,(IoTraceEventHeader *)&local_78.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604da40
 * symbol: getPosPutPrev
 * prototype: uint32_t getPosPutPrev(NvmSubmissionQueue * this)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getPosPutPrev(NvmSubmissionQueue * this) */

uint32_t __thiscall A53::IOC::NvmSubmissionQueue::getPosPutPrev(NvmSubmissionQueue *this)

{
  int iVar1;
  ushort uVar2;
  uint uVar3;
  
  uVar2 = (this->field_0).field_0.m_sizeMinus1;
  uVar3 = ((uint)(this->field_0).field_0.m_tail + (uint)(this->field_0).field_0.m_numSqePut) - 1;
  iVar1 = 0;
  if (uVar2 < uVar3) {
    iVar1 = uVar2 + 1;
  }
  return uVar3 - iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604da64
 * symbol: io_trace_write_event_FlashAdminCommand
 * prototype: void io_trace_write_event_FlashAdminCommand(IoController * this, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, NvmSqe * sqe, uint32_t maskSqeCdw)
 * body addresses: 452
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_FlashAdminCommand(IoController * this,
   IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, NvmSqe * sqe, uint32_t
   maskSqeCdw) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_FlashAdminCommand
          (IoController *this,IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId
          ,NvmSqe *sqe,uint32_t maskSqeCdw)

{
  uint uVar1;
  long lVar2;
  uint uVar3;
  uint32_t uVar4;
  uint64_t uVar5;
  uint32_t *puVar6;
  uint32_t *puVar7;
  ulong uVar8;
  uint uVar9;
  ControllerRings local_e0;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_78;
  uint local_70;
  uint32_t local_6c [11];
  
  uVar5 = readSystemClock(this);
  uVar4 = NvmSubmissionQueue::getPosPutPrev((this->m_nvm).m_aSq);
  uVar3 = (sqe->field_0).asU32[0];
  uVar1 = uVar3 >> 2 | 0xc;
  if ((uVar3 & 0xff) < 0xc0) {
    uVar1 = uVar3;
  }
  uVar9 = (uint)((maskSqeCdw & 0xc00) != 0);
  local_70 = (uint)((maskSqeCdw & 0xc0) != 0) << 6 | (uint)((maskSqeCdw & 0x300) != 0) << 7 |
             uVar9 << 8 | (uVar4 & 0x7f) << 9 | uVar3 & 0xffff0000 |
             ((sqe->field_0).field_0.NSID & 3) << 4 | uVar1 & 0xf;
  if ((maskSqeCdw & 0xc0) == 0) {
    puVar7 = local_6c;
  }
  else {
    local_6c[0] = (sqe->field_0).asU32[6];
    local_6c[1] = (sqe->field_0).asU32[7];
    puVar7 = local_6c + 2;
  }
  puVar6 = puVar7;
  if ((maskSqeCdw & 0x300) != 0) {
    uVar4 = (sqe->field_0).asU32[9];
    puVar6 = puVar7 + 2;
    *puVar7 = (sqe->field_0).asU32[8];
    puVar7[1] = uVar4;
  }
  if (uVar9 != 0) {
    lVar2 = 4;
    if ((maskSqeCdw & 0xf800) != 0) {
      lVar2 = 8;
    }
    *puVar6 = (sqe->field_0).asU32[10];
    puVar6[1] = (sqe->field_0).asU32[0xb];
    puVar6 = (uint32_t *)((long)puVar6 + lVar2);
  }
  puVar7 = (sqe->field_0).asU32 + 0xc;
  for (uVar8 = (ulong)(maskSqeCdw >> 0xc); (int)uVar8 != 0; uVar8 = uVar8 >> 1) {
    *puVar6 = *puVar7;
    puVar6 = puVar6 + 1;
    puVar7 = puVar7 + 1;
  }
  local_e0.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_e0.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_78 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)commandRingExecutingCommandId << 0x10 | uVar5 << 0x20 |
             (ulong)(((int)puVar6 - ((int)&local_78 + 8)) * 0x10 & 0x7c0U | (eSource & 0x1f) << 0xb
                    | 0x24));
  local_e0.m_pRingsState = &this->m_rings_state;
  local_e0.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_e0.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_e0.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_e0.m_paInputRingHead = this->m_aInputRingHead;
  local_e0.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_e0.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_e0.m_paOutputRing = this->m_aOutputRing;
  local_e0.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_e0.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_e0.m_paInputRing = this->m_aInputRing;
  local_e0.m_pContext_HandleControllerRingsEvent = this;
  io_trace_write_event(this,&local_e0,(IoTraceEventHeader *)&local_78.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604dc28
 * symbol: io_trace_write_event_FlashCommandsSubmitted
 * prototype: void io_trace_write_event_FlashCommandsSubmitted(IoController * this, TtnSubmissionQueue eSq, uint32_t numSqe)
 * body addresses: 240
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_FlashCommandsSubmitted(IoController * this,
   TtnSubmissionQueue eSq, uint32_t numSqe) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_FlashCommandsSubmitted
          (IoController *this,TtnSubmissionQueue eSq,uint32_t numSqe)

{
  ulong uVar1;
  uint32_t uVar2;
  uint64_t uVar3;
  ControllerRings local_a8;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_40;
  uint local_38;
  
  uVar3 = readSystemClock(this);
  uVar2 = NvmSubmissionQueue::getPosBackFromSubmit((this->m_nvm).m_aSq + eSq,numSqe);
  local_a8.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  uVar1 = 0xf867;
  if (eSq != kTtnSubmissionQueueAdmin) {
    uVar1 = 0xf863;
  }
  local_40 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)(uVar1 | uVar3 << 0x20);
  local_a8.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_a8.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_a8.m_pRingsState = &this->m_rings_state;
  local_a8.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_a8.m_paInputRingHead = this->m_aInputRingHead;
  local_38 = numSqe * 0x10000 + 0xff0000 & 0xff0000 | eSq & 7 | (uVar2 & 0xff) << 8;
  local_a8.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_a8.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_a8.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_a8.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_a8.m_paOutputRing = this->m_aOutputRing;
  local_a8.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_a8.m_paInputRing = this->m_aInputRing;
  local_a8.m_pContext_HandleControllerRingsEvent = this;
  io_trace_write_event(this,&local_a8,(IoTraceEventHeader *)&local_40.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604dd18
 * symbol: getPosBackFromSubmit
 * prototype: uint32_t getPosBackFromSubmit(NvmSubmissionQueue * this, uint32_t numSqe)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getPosBackFromSubmit(NvmSubmissionQueue * this, uint32_t
   numSqe) */

uint32_t __thiscall
A53::IOC::NvmSubmissionQueue::getPosBackFromSubmit(NvmSubmissionQueue *this,uint32_t numSqe)

{
  uint uVar1;
  int iVar2;
  ushort uVar3;
  
  uVar3 = (this->field_0).field_0.m_sizeMinus1;
  uVar1 = ((this->field_0).field_0.m_tail - numSqe) + (uint)(this->field_0).field_0.m_numSqeSubmit;
  iVar2 = 0;
  if (uVar3 < uVar1) {
    iVar2 = uVar3 + 1;
  }
  return uVar1 - iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604dd3c
 * symbol: io_trace_write_event_FlashCommandCompleted
 * prototype: void io_trace_write_event_FlashCommandCompleted(IoController * this, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, TtnSubmissionQueue eSq, uint16_t cid, NvmStatusCodeType SCT, uint32_t SC)
 * body addresses: 292
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_FlashCommandCompleted(IoController * this,
   IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, TtnSubmissionQueue eSq,
   uint16_t cid, NvmStatusCodeType SCT, uint32_t SC) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_FlashCommandCompleted
          (IoController *this,IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId
          ,TtnSubmissionQueue eSq,uint16_t cid,NvmStatusCodeType SCT,uint32_t SC)

{
  uint64_t uVar1;
  uint uVar2;
  int iVar3;
  ControllerRings local_c8;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_60;
  uint local_58;
  
  uVar1 = readSystemClock(this);
  uVar2 = SC | SCT;
  if (uVar2 != 0) {
    uVar2 = (uint)(SCT != SCT_VENDOR_SPECIFIC || SC != 0xc0);
  }
  iVar3 = 0x25;
  if (eSq != kTtnSubmissionQueueAdmin) {
    iVar3 = 0x21;
  }
  local_60 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)commandRingExecutingCommandId << 0x10 | uVar1 << 0x20 |
             (ulong)(uVar2 + iVar3 & 0xffff0000 | uVar2 + iVar3 & 0x7ff | (eSource & 0x1f) << 0xb |
                    0x40));
  local_c8.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_c8.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_58 = (uint)cid << 0x10 | eSq & 7 | (SCT & 7) << 4 | (SC & 0xff) << 8;
  local_c8.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_c8.m_pRingsState = &this->m_rings_state;
  local_c8.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_c8.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_c8.m_paInputRingHead = this->m_aInputRingHead;
  local_c8.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_c8.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_c8.m_paOutputRing = this->m_aOutputRing;
  local_c8.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_c8.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_c8.m_paInputRing = this->m_aInputRing;
  local_c8.m_pContext_HandleControllerRingsEvent = this;
  io_trace_write_event(this,&local_c8,(IoTraceEventHeader *)&local_60.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604de60
 * symbol: io_trace_write_event_ZcnCommand
 * prototype: void io_trace_write_event_ZcnCommand(IoController * this, ControllerRings * rings, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, uint32_t timestamp100MHz, ZcnVq eVq, uint32_t offsetCmd, uint16_t zcnCommandId, ZcnCommand * cmd)
 * body addresses: 304
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_ZcnCommand(IoController * this,
   ControllerRings * rings, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId,
   uint32_t timestamp100MHz, ZcnVq eVq, uint32_t offsetCmd, uint16_t zcnCommandId, ZcnCommand * cmd)
    */

void __thiscall
A53::IOC::IoController::io_trace_write_event_ZcnCommand
          (IoController *this,ControllerRings *rings,IoControllerCommandRing eSource,
          uint16_t commandRingExecutingCommandId,uint32_t timestamp100MHz,ZcnVq eVq,
          uint32_t offsetCmd,uint16_t zcnCommandId,ZcnCommand *cmd)

{
  short *psVar1;
  uint uVar2;
  undefined2 *puVar3;
  uint uVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  int iVar7;
  long lVar8;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_40;
  uint local_38;
  anon_struct_4_3_0a0f41ca_for_anon_union_32_10_f145cf84_for_ZcnCommand_0_6 local_34;
  undefined4 local_30;
  
  local_38 = eVq & 0x1f | (offsetCmd >> 5 & 0xff) << 8 | (uint)zcnCommandId << 0x10;
  lVar8 = 0;
  puVar3 = (undefined2 *)((long)&cmd->field_0 + 4);
  local_34 = (cmd->field_0).field_3;
  uVar4 = 0;
  while (iVar7 = (int)lVar8, iVar7 != 0xe) {
    psVar1 = puVar3 + lVar8;
    lVar8 = lVar8 + 1;
    uVar2 = 0;
    if (*psVar1 != 0) {
      uVar2 = 1 << (ulong)(iVar7 + 2U & 0x1f);
    }
    uVar4 = uVar2 | uVar4;
  }
  if (uVar4 == 0xfffc) {
    uVar4 = 0x274;
    for (lVar8 = 0; lVar8 != 0x1c; lVar8 = lVar8 + 4) {
      *(undefined4 *)((long)&local_38 + lVar8) = *(undefined4 *)((long)&cmd->field_0 + lVar8 + 4);
    }
  }
  else {
    local_38 = local_38 | 0x20;
    local_30 = uVar4 >> 2 & 0x3fff;
    puVar6 = (undefined2 *)((long)&local_30 + 2);
    for (uVar4 = uVar4 >> 2; uVar4 != 0; uVar4 = uVar4 >> 1) {
      puVar5 = puVar6;
      if ((uVar4 & 1) != 0) {
        puVar5 = puVar6 + 1;
        *puVar6 = *puVar3;
      }
      puVar3 = puVar3 + 1;
      puVar6 = puVar5;
    }
    puVar3 = puVar6;
    if (((uint)puVar6 >> 1 & 1) != 0) {
      puVar3 = puVar6 + 1;
      *puVar6 = 0;
    }
    uVar4 = ((uint)((int)puVar3 - (int)&local_38) >> 2 & 0x1f) << 6 | 0x34;
  }
  local_40 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)commandRingExecutingCommandId << 0x10 | (ulong)timestamp100MHz << 0x20 |
             (ulong)(uVar4 | (eSource & 0x1f) << 0xb));
  io_trace_write_event(this,rings,(IoTraceEventHeader *)&local_40.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604df90
 * symbol: io_trace_write_events_ZcnCommand
 * prototype: void io_trace_write_events_ZcnCommand(IoController * this, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, ZcnQueue eZcnQueue, uint32_t offsetCmdStart, uint16_t zcnCommandIdStart, uint32_t numCmds)
 * body addresses: 356
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_events_ZcnCommand(IoController * this,
   IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, ZcnQueue eZcnQueue,
   uint32_t offsetCmdStart, uint16_t zcnCommandIdStart, uint32_t numCmds) */

void __thiscall
A53::IOC::IoController::io_trace_write_events_ZcnCommand
          (IoController *this,IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId
          ,ZcnQueue eZcnQueue,uint32_t offsetCmdStart,uint16_t zcnCommandIdStart,uint32_t numCmds)

{
  uint64_t *puVar1;
  long lVar2;
  uint64_t uVar3;
  ZcnCommand local_f0;
  ControllerRings local_c8;
  
  uVar3 = readSystemClock(this);
  local_c8.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_c8.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_c8.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_c8.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_c8.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_c8.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_c8.m_paOutputRing = this->m_aOutputRing;
  lVar2 = (long)&this->m_aInputRing[0].field_0 + (ulong)eZcnQueue * 0x20;
  local_c8.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_c8.m_paInputRingHead = this->m_aInputRingHead;
  local_c8.m_pRingsState = &this->m_rings_state;
  local_c8.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_c8.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_c8.m_paInputRing = this->m_aInputRing;
  local_c8.m_pContext_HandleControllerRingsEvent = this;
  for (; numCmds != 0; numCmds = numCmds - 1) {
    if ((offsetCmdStart & (*(uint *)(&DAT_00001470 + lVar2) ^ 0xffffffff)) == 0) {
      puVar1 = (uint64_t *)((ulong)*(uint *)(&DAT_0000147c + lVar2) + (ulong)offsetCmdStart);
      local_f0.field_0.asU64[0] = *puVar1;
      local_f0.field_0.asU64[1] = puVar1[1];
      local_f0.field_0.asU64[2] = puVar1[2];
      local_f0.field_0.asU64[3] = puVar1[3];
    }
    io_trace_write_event_ZcnCommand
              (this,&local_c8,eSource,commandRingExecutingCommandId,(uint32_t)uVar3,
               (uint)(byte)(&DAT_00001469)[lVar2],offsetCmdStart,zcnCommandIdStart,&local_f0);
    zcnCommandIdStart = zcnCommandIdStart + 1;
    offsetCmdStart = *(uint *)(&DAT_00001470 + lVar2) & offsetCmdStart + 0x20;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e0f4
 * symbol: io_trace_write_event_ZcnCommands_internal
 * prototype: void io_trace_write_event_ZcnCommands_internal(IoController * this, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, IoTraceEventType eEventType, ZcnQueue eZcnQueue, uint32_t offsetCmdStart, uint32_t numCmds)
 * body addresses: 340
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_ZcnCommands_internal(IoController * this,
   IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, IoTraceEventType
   eEventType, ZcnQueue eZcnQueue, uint32_t offsetCmdStart, uint32_t numCmds) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_ZcnCommands_internal
          (IoController *this,IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId
          ,IoTraceEventType eEventType,ZcnQueue eZcnQueue,uint32_t offsetCmdStart,uint32_t numCmds)

{
  uint uVar1;
  long lVar2;
  uint64_t uVar3;
  uint uVar4;
  ControllerRings local_c8;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_60;
  uint local_58;
  
  uVar3 = readSystemClock(this);
  local_c8.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_c8.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  lVar2 = (long)&this->m_aInputRing[0].field_0 + (ulong)eZcnQueue * 0x20;
  local_c8.m_pRingsState = &this->m_rings_state;
  local_c8.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_60 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)(eEventType & 0x3f | (eSource & 0x1f) << 0xb | 0x40) |
              (ulong)commandRingExecutingCommandId << 0x10 | uVar3 << 0x20);
  local_c8.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_c8.m_paInputRingHead = this->m_aInputRingHead;
  local_c8.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  uVar1 = numCmds + (offsetCmdStart >> 5);
  local_c8.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_c8.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_58 = (byte)(&DAT_00001469)[lVar2] & 0x1f | (offsetCmdStart >> 5 & 0xff) << 8;
  local_c8.m_paOutputRing = this->m_aOutputRing;
  local_c8.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_c8.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_c8.m_paInputRing = this->m_aInputRing;
  local_c8.m_pContext_HandleControllerRingsEvent = this;
  if (uVar1 < *(uint *)(&DAT_00001470 + lVar2) >> 5) {
    uVar4 = numCmds - 1;
  }
  else {
    uVar4 = *(uint *)(&DAT_00001470 + lVar2) >> 5;
    local_58 = local_58 | (uVar4 - (offsetCmdStart >> 5) & 0xff) << 0x10;
    io_trace_write_event(this,&local_c8,(IoTraceEventHeader *)&local_60.field_0);
    uVar4 = (uVar1 - 2) - uVar4;
    local_58 = local_58 & 0xffff00ff;
  }
  local_58 = local_58 & 0xff000000 | local_58 & 0xffff | (uVar4 & 0xff) << 0x10;
  io_trace_write_event(this,&local_c8,(IoTraceEventHeader *)&local_60.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e248
 * symbol: io_trace_write_event_ZcnCommandError
 * prototype: void io_trace_write_event_ZcnCommandError(IoController * this, IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, ZcnQueue eZcnQueue, uint32_t offsetCmd, ZcnErrorCode eZcnErrorCode, ZcnErrorSource eZcnErrorSource)
 * body addresses: 260
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void io_trace_write_event_ZcnCommandError(IoController * this,
   IoControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, ZcnQueue eZcnQueue,
   uint32_t offsetCmd, ZcnErrorCode eZcnErrorCode, ZcnErrorSource eZcnErrorSource) */

void __thiscall
A53::IOC::IoController::io_trace_write_event_ZcnCommandError
          (IoController *this,IoControllerCommandRing eSource,uint16_t commandRingExecutingCommandId
          ,ZcnQueue eZcnQueue,uint32_t offsetCmd,ZcnErrorCode eZcnErrorCode,
          ZcnErrorSource eZcnErrorSource)

{
  uint64_t uVar1;
  ControllerRings local_c8;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_60;
  uint local_58;
  
  uVar1 = readSystemClock(this);
  local_c8.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_c8.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_c8.m_pRingsState = &this->m_rings_state;
  local_58 = (offsetCmd & 0x1fe0) << 3 | (eZcnErrorCode & 0x3f) << 0x10 |
             (eZcnErrorSource & (kZcnErrorSourceKeyDataRead|kZcnErrorSourceWfqTimeout)) << 0x16 |
             (byte)(&DAT_00001469)[(long)&this->m_aInputRing[0].field_0 + (ulong)eZcnQueue * 0x20] &
             0x1f;
  local_c8.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_c8.m_paInputRingHead = this->m_aInputRingHead;
  local_c8.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_c8.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_c8.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_c8.m_paOutputRing = this->m_aOutputRing;
  local_60 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)((eSource & 0x1f) << 0xb | 0x76) | (ulong)commandRingExecutingCommandId << 0x10
             | uVar1 << 0x20);
  local_c8.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_c8.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x54273bd0;
  local_c8.m_pfnHandleControllerRingsEvent = IoController_handleControllerRingsEvent;
  local_c8.m_paInputRing = this->m_aInputRing;
  local_c8.m_pContext_HandleControllerRingsEvent = this;
  io_trace_write_event(this,&local_c8,(IoTraceEventHeader *)&local_60.field_0);
  return;
}


