/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/a53_zcn.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602cf7c
 * symbol: zcnSetVqd_Control
 * prototype: void zcnSetVqd_Control(uint32_t iVq, uint32_t paCommandQueueHi, uint32_t numCommandsLog2, uint32_t run)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::zcnSetVqd_Control
               (uint32_t iVq,uint32_t paCommandQueueHi,uint32_t numCommandsLog2,uint32_t run)

{
  *(uint32_t *)(&DAT_022e1000 + (iVq << 0xc)) =
       (paCommandQueueHi >> 0xe & 4 | paCommandQueueHi << 0x10 | numCommandsLog2 * 8 + 0x78 & 0x78)
       ^ 5;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0602d010
 * symbol: zcnGetCommandPasid
 * prototype: bool zcnGetCommandPasid(uint64_t vaQueue, uint32_t iZcnCmd, uint16_t * out_pasid)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::zcnGetCommandPasid(uint64_t vaQueue,uint32_t iZcnCmd,uint16_t *out_pasid)

{
  ulong *puVar1;
  ushort uVar2;
  
  puVar1 = (ulong *)(vaQueue + (ulong)iZcnCmd * 0x20);
  if (((uint)*puVar1 >> 0x1a & 1) == 0) {
    if ((*puVar1 & 0x1f00000) == 0x300000) {
      uVar2 = (ushort)puVar1[3];
    }
    else {
      uVar2 = (ushort)(puVar1[2] >> 0x32) & 0xfff | (ushort)(uint)(puVar1[3] >> 0x2f) & 0xf000;
    }
  }
  else {
    uVar2 = 0;
  }
  *out_pasid = uVar2;
  return SUB81(vaQueue,0);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060545cc
 * symbol: zcnPutCommandWait
 * prototype: uint32_t zcnPutCommandWait(ZcnVqSubmitState * submit, uint32_t numQueues, uint8_t * aiQueueId, uint16_t * aiCommandId, uint64_t timeout)
 * body addresses: 608
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::zcnPutCommandWait
                   (ZcnVqSubmitState *submit,uint32_t numQueues,uint8_t *aiQueueId,
                   uint16_t *aiCommandId,uint64_t timeout)

{
  ulong uVar1;
  uint32_t uVar2;
  ulong uVar3;
  ulong uVar4;
  ulong uVar5;
  ulong uVar6;
  ulong uVar7;
  ulong uVar8;
  ulong uVar9;
  ulong uVar10;
  ulong uVar11;
  ZcnCommand local_30;
  
  local_30.field_0.asU64[2] = 0;
  local_30.field_0.asU64[3] = 0;
  local_30.field_0.asU64[0] = (uint64_t)(numQueues * 0x20 + 0xe0 & 0xe0 | 0x4000000);
  local_30.field_0.asU64[1] = 0;
  uVar7 = 0;
  uVar9 = 0;
  uVar4 = 0;
  uVar8 = 0;
  uVar10 = 0;
  uVar11 = 0;
  uVar3 = 0;
  uVar5 = 0;
  uVar6 = 0;
  uVar1 = 0;
  switch(numQueues) {
  case 8:
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] | (ulong)aiQueueId[7] << 0x3c |
         (ulong)((aiQueueId[7] & 0x10) << 0x13);
    uVar7 = (ulong)aiCommandId[7] << 0x30;
  case 7:
    uVar9 = uVar7 | (ulong)aiCommandId[6] << 0x20;
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xf000000000000000 |
         local_30.field_0.asU64[0] & 0xffffffffbfffff | (ulong)(aiQueueId[6] & 0xf) << 0x38 |
         (ulong)((aiQueueId[6] & 0x10) << 0x12);
  case 6:
    uVar4 = uVar9 | (ulong)aiCommandId[5] << 0x10;
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xff00000000000000 |
         local_30.field_0.asU64[0] & 0xfffffffdfffff | (ulong)(aiQueueId[5] & 0xf) << 0x34 |
         (ulong)((aiQueueId[5] & 0x10) << 0x11);
  case 5:
    uVar8 = uVar4 | aiCommandId[4];
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xfff0000000000000 |
         local_30.field_0.asU64[0] & 0xffffffefffff | (ulong)(aiQueueId[4] & 0xf) << 0x30 |
         (ulong)((aiQueueId[4] & 0x10) << 0x10);
  case 4:
    uVar10 = (ulong)aiCommandId[3] << 0x30;
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xffff000000000000 |
         local_30.field_0.asU64[0] & 0xfffffffffff | (ulong)(aiQueueId[3] & 0xf) << 0x2c |
         (ulong)((aiQueueId[3] & 0x10) << 0xf);
    uVar1 = uVar8;
  case 3:
    uVar3 = uVar1;
    uVar11 = uVar10 | (ulong)aiCommandId[2] << 0x20;
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xfffff00000000000 |
         local_30.field_0.asU64[0] & 0xfffffbffff | (ulong)(aiQueueId[2] & 0xf) << 0x28 |
         (ulong)((aiQueueId[2] & 0x10) << 0xe);
  case 2:
    uVar5 = uVar11 | (ulong)aiCommandId[1] << 0x10;
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xffffff0000000000 |
         local_30.field_0.asU64[0] & 0xffffdffff | (ulong)(aiQueueId[1] & 0xf) << 0x24 |
         (ulong)((aiQueueId[1] & 0x10) << 0xd);
    uVar6 = uVar3;
  case 1:
    local_30.field_0.asU64[1] = uVar5 | *aiCommandId;
    local_30.field_0.asU64[0] =
         local_30.field_0.asU64[0] & 0xfffffff000000000 |
         local_30.field_0.asU64[0] & 0xfffeffff | (ulong)(*aiQueueId & 0xf) << 0x20 |
         (ulong)((*aiQueueId & 0x10) << 0xc);
    local_30.field_0.asU64[2] = uVar6;
  default:
    uVar2 = zcnPutCommand(submit,&local_30);
    return uVar2;
  }
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06054b70
 * symbol: zcnPutCommandIdmaToLsb
 * prototype: uint32_t zcnPutCommandIdmaToLsb(ZcnVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint16_t PASID, uint8_t lsbDstID, uint32_t lsbDstID_byteOffset, ZcnPtByteSwap eByteSwap, ZcnEngine ePtEngine)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::zcnPutCommandIdmaToLsb
                   (ZcnVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint16_t PASID,
                   uint8_t lsbDstID,uint32_t lsbDstID_byteOffset,ZcnPtByteSwap eByteSwap,
                   ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  int local_30;
  uint32_t uStack_2c;
  undefined8 uStack_28;
  undefined8 local_20;
  undefined8 uStack_18;
  
  uStack_28 = paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20 |
              (ulong)((~(uint)(paSrc >> 0x2f) & 2) >> 1) << 0x31;
  uStack_2c = len;
  local_30 = (eByteSwap & 0x1f) << 0x14;
  local_20 = (ulong)(lsbDstID_byteOffset + (uint)lsbDstID * 0x20) | (ulong)(PASID & 0xfff) << 0x32 |
             0x1000000000000;
  uStack_18 = (ulong)(PASID >> 0xc) << 0x3b;
  uVar1 = zcnPutCommand(submit,(ZcnCommand *)&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06054be4
 * symbol: zcnPutCommandAesXts
 * prototype: uint32_t zcnPutCommandAesXts(ZcnVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t PASID, ZcnAesXtsMode eAesXtsMode, ZcnAesType eAesType, ZcnAesXtsSize eAesXtsSize, uint8_t kmbKeyID, uint8_t lsbContextID, ZcnCommandOrder eOrder)
 * body addresses: 252
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::zcnPutCommandAesXts
                   (ZcnVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t PASID,ZcnAesXtsMode eAesXtsMode,ZcnAesType eAesType,
                   ZcnAesXtsSize eAesXtsSize,uint8_t kmbKeyID,uint8_t lsbContextID,
                   ZcnCommandOrder eOrder)

{
  uint32_t uVar1;
  ulong uVar2;
  ZcnCommand local_30;
  
  if ((long)paSrc < 0) {
    uVar2 = 0x3000000000000;
  }
  else {
    uVar2 = (ulong)(~(uint)(paSrc >> 0x2f) & 2) << 0x30;
  }
  local_30.field_0.asU64[1] = paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20 | uVar2;
  if ((long)paDst < 0) {
    uVar2 = 0x3000000000000;
  }
  else {
    uVar2 = (ulong)(~(uint)(paDst >> 0x2f) & 2) << 0x30;
  }
  local_30.field_0.asU64[3] =
       (ulong)((eAesXtsSize & 0xff) << 5 | 0x2000) | 0x1000000000000 | (ulong)(PASID >> 0xc) << 0x3b
  ;
  local_30.field_0.asU64[2] =
       paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20 | uVar2 |
       (ulong)(PASID & 0xfff) << 0x32;
  local_30.field_0.asU64[0] =
       CONCAT44(len,(eAesXtsMode & 0x3f) << 0xc | (eAesType & 0x7f) << 5) | 0x100018;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060551f0
 * symbol: zcnPutCommandIdmaPt
 * prototype: uint32_t zcnPutCommandIdmaPt(ZcnVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint32_t sramDst, uint16_t PASID, ZcnEngine ePtEngine)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommandIdmaPt
                   (ZcnVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint32_t sramDst,
                   uint16_t PASID,ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  ZcnCommand local_30;
  
  local_30.field_0.asU64[0] = CONCAT44(len,(ePtEngine & 0x1f) << 0x14);
  local_30.field_0.asU64[2] = (ulong)sramDst | (ulong)(PASID & 0xfff) << 0x32 | 0x3000000000000;
  local_30.field_0.asU64[3] = (ulong)(PASID >> 0xc) << 0x3b;
  local_30.field_0.asU64[1] =
       paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20 |
       (ulong)((~(uint)(paSrc >> 0x2f) & 2) >> 1) << 0x31;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060557e8
 * symbol: zcnPutCommandCopySramToSram
 * prototype: uint32_t zcnPutCommandCopySramToSram(ZcnVqSubmitState * submit, uint32_t len, uint32_t sramSrc, uint32_t sramDst, ZcnEngine ePtEngine)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommandCopySramToSram
                   (ZcnVqSubmitState *submit,uint32_t len,uint32_t sramSrc,uint32_t sramDst,
                   ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  ZcnCommand local_30;
  
  local_30.field_0.asU64[0] = CONCAT44(len,(ePtEngine & 0x1f) << 0x14);
  local_30.field_0.asU64[2] = (ulong)sramDst | 0x3fff000000000000;
  local_30.field_0.asU64[1] = (ulong)sramSrc | 0x3000000000000;
  local_30.field_0.asU64[3] = 0x7800000000000000;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605592c
 * symbol: zcnPutCommandWait
 * prototype: uint32_t zcnPutCommandWait(A53 * this, ZcnVqSubmitState * submit, uint8_t iQueueId0, uint16_t iCommandId0, uint64_t timeout)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t __thiscall
A53::zcnPutCommandWait
          (A53 *this,ZcnVqSubmitState *submit,uint8_t iQueueId0,uint16_t iCommandId0,
          uint64_t timeout)

{
  uint32_t uVar1;
  uint16_t local_18 [2];
  uint8_t local_14 [4];
  
  local_18[0] = (uint16_t)submit;
  local_14[0] = '\0';
  uVar1 = zcnPutCommandWait((ZcnVqSubmitState *)this,1,local_14,local_18,timeout);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06055c3c
 * symbol: zcnPutCommandSha3
 * prototype: uint32_t zcnPutCommandSha3(ZcnVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint16_t PASID, ZcnShaType eSha3Type, uint64_t paInputContext, uint8_t lsbOutputMAC, ZcnCommandOrder eOrder)
 * body addresses: 260
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Removing unreachable block (ram,0x06055cc4) */

uint32_t A53::zcnPutCommandSha3
                   (ZcnVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint16_t PASID,
                   ZcnShaType eSha3Type,uint64_t paInputContext,uint8_t lsbOutputMAC,
                   ZcnCommandOrder eOrder)

{
  uint32_t uVar1;
  ulong uVar2;
  undefined4 local_30;
  uint32_t uStack_2c;
  undefined8 uStack_28;
  undefined8 local_20;
  undefined8 uStack_18;
  
  if ((long)paSrc < 0) {
    uVar2 = 0x3000000000000;
  }
  else {
    uVar2 = (ulong)(~(uint)(paSrc >> 0x2f) & 2) << 0x30;
  }
  uStack_28 = paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20 | uVar2;
  uStack_2c = len;
  local_30 = 0x348018;
  uStack_18 = (ulong)(PASID >> 0xc) << 0x3b | (ulong)eSha3Type | 0x2000000000000;
  local_20 = (ulong)((uint)paInputContext & 0xff) << 5 | (ulong)(PASID & 0xfff) << 0x32 |
             0x1000000000000;
  uVar1 = zcnPutCommand(submit,(ZcnCommand *)&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06055d40
 * symbol: zcnPutCommandCopyLsbToLsb
 * prototype: uint32_t zcnPutCommandCopyLsbToLsb(ZcnVqSubmitState * submit, uint32_t len, uint8_t lsbSrcID, uint32_t lsbSrcID_byteOffset, uint8_t lsbDstID, uint32_t lsbDstID_byteOffset, ZcnPtByteSwap eByteSwap, ZcnEngine ePtEngine)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::zcnPutCommandCopyLsbToLsb
                   (ZcnVqSubmitState *submit,uint32_t len,uint8_t lsbSrcID,
                   uint32_t lsbSrcID_byteOffset,uint8_t lsbDstID,uint32_t lsbDstID_byteOffset,
                   ZcnPtByteSwap eByteSwap,ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  ZcnCommand local_30;
  
  local_30.field_0.asU64[2] = (ulong)lsbSrcID << 5 | 0x3ffd000000000000;
  local_30.field_0.asU64[0] = (ulong)((lsbSrcID_byteOffset & 0x1f) << 0x14) | 0x2000000000;
  local_30.field_0.asU64[1] = (ulong)(len << 5) & 0x1fe0 | 0x1000000000000;
  local_30.field_0.asU64[3] = 0x7800000000000000;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06056094
 * symbol: zcnPutCommandPtOdmaFromLsb
 * prototype: uint32_t zcnPutCommandPtOdmaFromLsb(ZcnVqSubmitState * submit, uint32_t len, uint8_t lsbSrcID, uint32_t lsbSrcID_byteOffset, uint64_t paDst, uint16_t PASID, ZcnPtByteSwap eByteSwap, ZcnEngine ePtEngine)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommandPtOdmaFromLsb
                   (ZcnVqSubmitState *submit,uint32_t len,uint8_t lsbSrcID,
                   uint32_t lsbSrcID_byteOffset,uint64_t paDst,uint16_t PASID,
                   ZcnPtByteSwap eByteSwap,ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  uint local_30;
  uint32_t uStack_2c;
  undefined8 uStack_28;
  undefined8 local_20;
  undefined8 uStack_18;
  
  uStack_28 = (ulong)(lsbSrcID_byteOffset + (uint)lsbSrcID * 0x20) | 0x1000000000000;
  uStack_18 = (ulong)(PASID >> 0xc) << 0x3b;
  local_20 = paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20 |
             ((ulong)~(uint)(paDst >> 0x2f) & 2) << 0x30 | (ulong)(PASID & 0xfff) << 0x32;
  uStack_2c = len;
  local_30 = (eByteSwap & (kZcnPtByteSwap4Byte|kZcnPtByteSwap32Byte)) << 5 |
             (ePtEngine & 0x1f) << 0x14;
  uVar1 = zcnPutCommand(submit,(ZcnCommand *)&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06056854
 * symbol: zcnPutCommandZde
 * prototype: uint32_t zcnPutCommandZde(ZcnVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t PASID, ZcnEngine eZdeEngine, ZcnCommandOrder eOrder)
 * body addresses: 224
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommandZde
                   (ZcnVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t PASID,ZcnEngine eZdeEngine,ZcnCommandOrder eOrder)

{
  uint32_t uVar1;
  ulong uVar2;
  ZcnCommand local_30;
  
  if ((long)paSrc < 0) {
    uVar2 = 0x3000000000000;
  }
  else {
    uVar2 = (ulong)(~(uint)(paSrc >> 0x2f) & 2) << 0x30;
  }
  local_30.field_0.asU64[1] = paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20 | uVar2;
  if ((long)paDst < 0) {
    uVar2 = 0x3000000000000;
  }
  else {
    uVar2 = (ulong)(~(uint)(paDst >> 0x2f) & 2) << 0x30;
  }
  local_30.field_0.asU64[0] =
       (ulong)((eZdeEngine & 0x1f) << 0x14) |
       CONCAT44(len,eOrder << 3) & 0xffffffff00000008 | (ulong)(eOrder << 3 & 0x10);
  local_30.field_0.asU64[3] = (ulong)(PASID >> 0xc) << 0x3b;
  local_30.field_0.asU64[2] =
       paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20 | (ulong)(PASID & 0xfff) << 0x32 |
       uVar2;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06056e58
 * symbol: zcnPutCommandPtOdma
 * prototype: uint32_t zcnPutCommandPtOdma(ZcnVqSubmitState * submit, uint32_t len, uint32_t sramSrc, uint64_t paDst, uint16_t PASID, ZcnEngine ePtEngine)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommandPtOdma
                   (ZcnVqSubmitState *submit,uint32_t len,uint32_t sramSrc,uint64_t paDst,
                   uint16_t PASID,ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  ZcnCommand local_30;
  
  local_30.field_0.asU64[0] = CONCAT44(len,(ePtEngine & 0x1f) << 0x14);
  local_30.field_0.asU64[1] = (ulong)sramSrc | 0x3000000000000;
  local_30.field_0.asU64[3] = (ulong)(PASID >> 0xc) << 0x3b;
  local_30.field_0.asU64[2] =
       (ulong)(PASID & 0xfff) << 0x32 |
       paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20 |
       (ulong)((~(uint)(paDst >> 0x2f) & 2) >> 1) << 0x31;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605850c
 * symbol: zcnPutCommandIdmaPtOdma
 * prototype: uint32_t zcnPutCommandIdmaPtOdma(ZcnVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t PASID, ZcnEngine ePtEngine)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommandIdmaPtOdma
                   (ZcnVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t PASID,ZcnEngine ePtEngine)

{
  uint32_t uVar1;
  ZcnCommand local_30;
  
  local_30.field_0.asU64[0] = CONCAT44(len,(ePtEngine & 0x1f) << 0x14);
  local_30.field_0.asU64[3] = (ulong)(PASID >> 0xc) << 0x3b;
  local_30.field_0.asU64[2] =
       (ulong)(PASID & 0xfff) << 0x32 |
       paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20 |
       (ulong)((~(uint)(paDst >> 0x2f) & 2) >> 1) << 0x31;
  local_30.field_0.asU64[1] =
       paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20 |
       (ulong)((~(uint)(paSrc >> 0x2f) & 2) >> 1) << 0x31;
  uVar1 = zcnPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06059ce4
 * symbol: zcnPutCommand
 * prototype: uint32_t zcnPutCommand(ZcnVqSubmitState * submit, ZcnCommand * cmd)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::zcnPutCommand(ZcnVqSubmitState *submit,ZcnCommand *cmd)

{
  uint64_t *puVar1;
  uint uVar2;
  uint32_t uVar3;
  uint64_t uVar4;
  
  uVar4 = (cmd->field_0).asU64[1];
  puVar1 = (uint64_t *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = (cmd->field_0).asU64[0];
  puVar1[1] = uVar4;
  uVar4 = (cmd->field_0).asU64[3];
  puVar1[2] = (cmd->field_0).asU64[2];
  puVar1[3] = uVar4;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}


