/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/a53_nvm_ttn_driver.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601a524
 * symbol: nvmDriverIsSqSpaceAvailable
 * prototype: uint32_t nvmDriverIsSqSpaceAvailable(NvmDriver * nvmDriver, uint32_t iSq)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::IOC::nvmDriverIsSqSpaceAvailable(NvmDriver *nvmDriver,uint32_t iSq)

{
  NvmSubmissionQueue *this;
  bool bVar1;
  
  this = nvmDriver->m_aSq + iSq;
  if (1 << (ulong)((this->field_0).field_0.m_numSqeSramCacheLog2 & 0x1f) ==
      (uint)(this->field_0).field_0.m_numSqePut) {
    return 0;
  }
  bVar1 = NvmSubmissionQueue::isFull(this);
  return ~(uint)bVar1 & 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0601c628
 * symbol: nvmDriverIsSqSpaceAvailable
 * prototype: uint32_t nvmDriverIsSqSpaceAvailable(NvmDriver * nvmDriver, uint32_t iSq, uint32_t numSqe)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::IOC::nvmDriverIsSqSpaceAvailable(NvmDriver *nvmDriver,uint32_t iSq,uint32_t numSqe)

{
  NvmSubmissionQueue *this;
  uint32_t uVar1;
  uint uVar2;
  
  this = nvmDriver->m_aSq + iSq;
  if ((1 << (ulong)((this->field_0).field_0.m_numSqeSramCacheLog2 & 0x1f)) -
      (uint)(this->field_0).field_0.m_numSqePut < numSqe) {
    uVar2 = 0;
  }
  else {
    uVar1 = NvmSubmissionQueue::getNumSqeAvailable(this);
    uVar2 = (uint)(numSqe <= uVar1);
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06042d1c
 * symbol: nvmDriverIsSpaceToPutAdminCommands
 * prototype: bool nvmDriverIsSpaceToPutAdminCommands(NvmDriver * nvmDriver, uint32_t numCommands)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::IOC::nvmDriverIsSpaceToPutAdminCommands(NvmDriver *nvmDriver,uint32_t numCommands)

{
  if (*(ushort *)&nvmDriver->field_0x172 + 1 < *(ushort *)&nvmDriver->field_0x176 + numCommands) {
    return false;
  }
  return nvmDriver->m_aSq[0].field_0.field_0.m_numSqePut + numCommands <=
         (uint)(1 << (ulong)(nvmDriver->m_aSq[0].field_0.field_0.m_numSqeSramCacheLog2 & 0x1f));
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06044440
 * symbol: nvmDriverIsSqSpaceAvailable
 * prototype: uint32_t nvmDriverIsSqSpaceAvailable(NvmDriver * nvmDriver, uint32_t iSq)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::IOC::nvmDriverIsSqSpaceAvailable(NvmDriver *nvmDriver,uint32_t iSq)

{
  NvmSubmissionQueue *this;
  bool bVar1;
  
  this = nvmDriver->m_aSq + iSq;
  if (1 << (ulong)((this->field_0).field_0.m_numSqeSramCacheLog2 & 0x1f) ==
      (uint)(this->field_0).field_0.m_numSqePut) {
    return 0;
  }
  bVar1 = NvmSubmissionQueue::isFull(this);
  return ~(uint)bVar1 & 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06050d5c
 * symbol: nvmDriverIsSqSpaceAvailable
 * prototype: uint32_t nvmDriverIsSqSpaceAvailable(NvmDriver * nvmDriver, uint32_t iSq, uint32_t numSqe)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::IOC::nvmDriverIsSqSpaceAvailable(NvmDriver *nvmDriver,uint32_t iSq,uint32_t numSqe)

{
  uint32_t uVar1;
  
  if (1 < (1 << (ulong)(nvmDriver->m_aSq[2].field_0.field_0.m_numSqeSramCacheLog2 & 0x1f)) -
          (uint)nvmDriver->m_aSq[2].field_0.field_0.m_numSqePut) {
    uVar1 = NvmSubmissionQueue::getNumSqeAvailable(nvmDriver->m_aSq + 2);
    return (uint32_t)(1 < uVar1);
  }
  return 0;
}


