/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/../../controller/io_controller/a53_nvm.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060307ac
 * symbol: nvmSetControllerConfig
 * prototype: bool nvmSetControllerConfig(NvmControllerControlEnable eEnabled, NvmCommandSet eCommandSet, uint32_t memPageSizeLog2, NvmArbitrationMechanism eArbitration, NvmShutdownNotification eShutdown, uint32_t sizeofSqeLog2, uint32_t sizeofCqeLog2)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

bool A53::nvmSetControllerConfig
               (NvmControllerControlEnable eEnabled,NvmCommandSet eCommandSet,
               uint32_t memPageSizeLog2,NvmArbitrationMechanism eArbitration,
               NvmShutdownNotification eShutdown,uint32_t sizeofSqeLog2,uint32_t sizeofCqeLog2)

{
  if (eCommandSet + 0xfffffff4 < 0x10) {
    _DAT_03800014 =
         eCommandSet * 0x80 + 0x200 & 0x780 | eEnabled & 1 | (memPageSizeLog2 & 7) << 0xb |
         (eArbitration & 3) << 0xe | 0x460000;
    return true;
  }
  return false;
}


