/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller\a53_nvm_ttn_notification_buffer.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052934
 * symbol: popEntry
 * prototype: bool popEntry(NvmTtnNotificationBuffer * this, uint64_t vaSramCacheBase, uint64_t * out_entry)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool popEntry(NvmTtnNotificationBuffer * this, uint64_t
   vaSramCacheBase, uint64_t * out_entry) */

bool __thiscall
A53::IOC::NvmTtnNotificationBuffer::popEntry
          (NvmTtnNotificationBuffer *this,uint64_t vaSramCacheBase,uint64_t *out_entry)

{
  uint uVar1;
  
  uVar1 = (uint)(this->field_0).field_0.m_numNbeToGet;
  if (uVar1 != 0) {
    *out_entry = *(uint64_t *)
                  ((this->field_0).field_0.m_offsetSramCache + vaSramCacheBase +
                  (ulong)((this->field_0).field_0.m_head - uVar1 &
                         (1 << (ulong)((this->field_0).field_0.m_numNbeSramCacheLog2 & 0x1f)) - 1U)
                  * 8);
    (this->field_0).field_0.m_numNbeToGet = (this->field_0).field_0.m_numNbeToGet + 0xff;
  }
  return uVar1 != 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052984
 * symbol: peekEntry
 * prototype: bool peekEntry(NvmTtnNotificationBuffer * this, uint64_t vaSramCacheBase, uint64_t * out_entry, uint32_t indexFromHead)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool peekEntry(NvmTtnNotificationBuffer * this, uint64_t
   vaSramCacheBase, uint64_t * out_entry, uint32_t indexFromHead) */

bool __thiscall
A53::IOC::NvmTtnNotificationBuffer::peekEntry
          (NvmTtnNotificationBuffer *this,uint64_t vaSramCacheBase,uint64_t *out_entry,
          uint32_t indexFromHead)

{
  byte bVar1;
  
  bVar1 = (this->field_0).field_0.m_numNbeToGet;
  if (indexFromHead < bVar1) {
    *out_entry = *(uint64_t *)
                  ((this->field_0).field_0.m_offsetSramCache + vaSramCacheBase +
                  (ulong)((indexFromHead - bVar1) + (uint)(this->field_0).field_0.m_head &
                         (1 << (ulong)((this->field_0).field_0.m_numNbeSramCacheLog2 & 0x1f)) - 1U)
                  * 8);
  }
  return indexFromHead < bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060529d0
 * symbol: issueFetch
 * prototype: IssueFetchReturn issueFetch(NvmTtnNotificationBuffer * this, A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PtdmaVqSubmitState * submit_read, uint16_t pasid)
 * body addresses: 248
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueFetchReturn issueFetch(NvmTtnNotificationBuffer * this,
   A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PtdmaVqSubmitState *
   submit_read, uint16_t pasid) */

IssueFetchReturn __thiscall
A53::IOC::NvmTtnNotificationBuffer::issueFetch
          (NvmTtnNotificationBuffer *this,A53_AddressTranslator *addressTranslator,
          uint64_t vaSramCacheBase,PtdmaVqSubmitState *submit_read,uint16_t pasid)

{
  uint uVar1;
  ushort uVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  uint32_t uVar6;
  ulong uVar7;
  ulong uVar8;
  DmaCommand local_40;
  
  local_40.field_0.asU64[3] = (uint64_t)pasid;
  if ((((this->field_0).field_0.m_numNbeFetch == '\0') &&
      ((*(byte *)((long)&this->field_0 + 0xe) >> 3 & 1) == 0)) &&
     (submit_read->m_numCommandsAvailable != 0)) {
    iVar3 = 1 << (ulong)((this->field_0).field_0.m_numNbeSramCacheLog2 & 0x1f);
    uVar5 = iVar3 - (uint)(this->field_0).field_0.m_numNbeToGet;
    if (uVar5 != 0) {
      uVar2 = (this->field_0).field_0.m_head;
      uVar1 = iVar3 + 0xffffU & (uint)uVar2;
      uVar4 = iVar3 - uVar1;
      if (uVar5 <= uVar4) {
        uVar4 = uVar5;
      }
      uVar7 = (this->field_0).field_0.m_paBase + (ulong)uVar2 * 8;
      uVar5 = uVar4 & 0xffffffe0;
      if (uVar4 < 0x21) {
        uVar5 = uVar4;
      }
      uVar8 = (ulong)uVar5;
      local_40.field_0.asU64[2] =
           (ulong)((uint)(this->field_0).field_0.m_offsetSramCache + (int)vaSramCacheBase +
                  uVar1 * 8) & 0xfffff;
      local_40.field_0.asU64[1] =
           -(uVar7 >> 0x30 & 1) & 0x3000000000000 |
           uVar7 & 0xffffffff | (uVar7 >> 0x20 & 0xffff) << 0x20;
      local_40.field_0.asU64[0] = (ulong)(uVar5 < 0x21) << 5 | uVar8 << 0x23;
      uVar6 = ptdmaPutCommand(submit_read,&local_40);
      (this->field_0).field_0.m_numNbeFetch = (uint8_t)uVar5;
      (this->field_0).field_0.m_ptdmaCmdFetch = (uint16_t)(uVar6 >> 5);
      uVar7 = (ulong)(uVar6 >> 5 & 0xffff | 0x10000) << 0x20;
      goto LAB_06052a1c;
    }
  }
  uVar8 = 0;
  uVar7 = 0;
LAB_06052a1c:
  return (IssueFetchReturn)(uVar7 | uVar8);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052ac8
 * symbol: issueClear
 * prototype: IssueClearReturn issueClear(NvmTtnNotificationBuffer * this, PtdmaVqSubmitState * submit_write, uint16_t pasid)
 * body addresses: 200
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueClearReturn issueClear(NvmTtnNotificationBuffer * this,
   PtdmaVqSubmitState * submit_write, uint16_t pasid) */

IssueClearReturn __thiscall
A53::IOC::NvmTtnNotificationBuffer::issueClear
          (NvmTtnNotificationBuffer *this,PtdmaVqSubmitState *submit_write,uint16_t pasid)

{
  uint uVar1;
  ushort uVar2;
  ushort uVar3;
  uint32_t uVar4;
  DmaFunction in_w4;
  DmaWaitOnCompletion in_w5;
  ulong uVar5;
  uint uVar6;
  ulong uVar7;
  uint uVar8;
  uint uVar9;
  
  if ((*(byte *)((long)&this->field_0 + 0xe) >> 4 & 1) == 0) {
    uVar2 = (this->field_0).field_0.m_headClear;
    uVar3 = (this->field_0).field_0.m_head;
    if (((uint)uVar2 != (uint)uVar3) && (submit_write->m_numCommandsAvailable != 0)) {
      uVar9 = 0xfffffff8;
      uVar8 = (uint)(this->field_0).field_0.m_sizeMinus1;
      uVar1 = uVar8 + 1;
      if (uVar8 < 0x20) {
        uVar9 = -(uVar1 >> 2);
      }
      uVar8 = uVar9 & uVar3;
      uVar6 = (uint)uVar2;
      if (uVar3 <= uVar6 || (uVar9 & uVar2) != uVar8) {
        uVar9 = uVar8;
        if (uVar8 <= uVar6) {
          uVar9 = uVar1;
        }
        if (uVar8 <= uVar6) {
          uVar8 = 0;
        }
        uVar4 = ptdmaPutCommandZero(submit_write,(uVar9 - uVar6) * 8,
                                    (this->field_0).field_0.m_paBase + (ulong)uVar2 * 8,pasid,in_w4,
                                    in_w5);
        (this->field_0).field_0.m_headClear = (uint16_t)uVar8;
        (this->field_0).field_0.m_ptdmaCmdClear = (uint16_t)(uVar4 >> 5);
        uVar7 = (ulong)(uVar4 >> 5) << 0x20;
        uVar5 = 1;
        *(byte *)((long)&this->field_0 + 0xe) = *(byte *)((long)&this->field_0 + 0xe) | 0x10;
        goto LAB_06052b80;
      }
    }
  }
  uVar5 = 0;
  uVar7 = 0;
LAB_06052b80:
  return (IssueClearReturn)(uVar7 | uVar5);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052bd8
 * symbol: issueInitDram
 * prototype: IssueClearReturn issueInitDram(NvmTtnNotificationBuffer * this, PtdmaVqSubmitState * submit_write, uint16_t pasid)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueClearReturn issueInitDram(NvmTtnNotificationBuffer * this,
   PtdmaVqSubmitState * submit_write, uint16_t pasid) */

IssueClearReturn __thiscall
A53::IOC::NvmTtnNotificationBuffer::issueInitDram
          (NvmTtnNotificationBuffer *this,PtdmaVqSubmitState *submit_write,uint16_t pasid)

{
  uint32_t uVar1;
  DmaFunction in_w4;
  DmaWaitOnCompletion in_w5;
  ulong uVar2;
  ulong uVar3;
  
  if ((((this->field_0).field_0.m_numNbeFetch == '\0') &&
      ((*(byte *)((long)&this->field_0 + 0xe) >> 3 & 1) == 0)) &&
     (submit_write->m_numCommandsAvailable != 0)) {
    uVar1 = ptdmaPutCommandZero(submit_write,(uint)(this->field_0).field_0.m_sizeMinus1 * 8 + 8,
                                (this->field_0).field_0.m_paBase,pasid,in_w4,in_w5);
    (this->field_0).field_0.m_ptdmaCmdFetch = (uint16_t)(uVar1 >> 5);
    uVar3 = (ulong)(uVar1 >> 5) << 0x20;
    uVar2 = 1;
    *(byte *)((long)&this->field_0 + 0xe) = *(byte *)((long)&this->field_0 + 0xe) | 8;
  }
  else {
    uVar2 = 0;
    uVar3 = 0;
  }
  return (IssueClearReturn)(uVar3 | uVar2);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052c5c
 * symbol: updateForFetchPtdmaCompletion
 * prototype: uint32_t updateForFetchPtdmaCompletion(NvmTtnNotificationBuffer * this, uint64_t vaSramCacheBase, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 204
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t updateForFetchPtdmaCompletion(NvmTtnNotificationBuffer * this,
   uint64_t vaSramCacheBase, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
    */

uint32_t __thiscall
A53::IOC::NvmTtnNotificationBuffer::updateForFetchPtdmaCompletion
          (NvmTtnNotificationBuffer *this,uint64_t vaSramCacheBase,uint32_t ptdmaSizeofQueue,
          uint32_t ptdmaHeadLo,uint32_t ptdmaTailLo)

{
  ulong uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint32_t uVar5;
  ulong uVar6;
  uint uVar7;
  
  if (((uint)(this->field_0).field_0.m_ptdmaCmdFetch * 0x20 - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)
      < (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)) {
    uVar5 = 0;
  }
  else {
    uVar5 = (uint32_t)(this->field_0).field_0.m_numNbeFetch;
    uVar3 = 1 << (ulong)((this->field_0).field_0.m_numNbeSramCacheLog2 & 0x1f);
    uVar4 = uVar3 - 1;
    uVar7 = (uint)(this->field_0).field_0.m_head;
    uVar1 = (this->field_0).field_0.m_offsetSramCache + vaSramCacheBase;
    uVar2 = uVar4 & uVar7;
    uVar4 = uVar7 + uVar5 & uVar4;
    uVar6 = uVar1 + (uVar2 << 3) & 0xffffffffffffffc0;
    if (uVar4 <= uVar2) {
      for (; uVar6 < (uVar1 + (ulong)uVar3 * 8 + 0x3f & 0xffffffffffffffc0); uVar6 = uVar6 + 0x40) {
        DC_CIVAC(uVar6);
      }
      uVar6 = uVar1 & 0xffffffffffffffc0;
    }
    for (; uVar6 < (uVar1 + (uVar4 << 3) + 0x3f & 0xffffffffffffffc0); uVar6 = uVar6 + 0x40) {
      DC_CIVAC(uVar6);
    }
    UnkSytemRegWrite(0,3,3,0xd,4,0);
    (this->field_0).field_0.m_numNbeFetch = '\0';
    (this->field_0).field_0.m_ptdmaCmdFetch = 0xffff;
  }
  return uVar5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052d28
 * symbol: updateForClearPtdmaCompletion
 * prototype: bool updateForClearPtdmaCompletion(NvmTtnNotificationBuffer * this, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForClearPtdmaCompletion(NvmTtnNotificationBuffer * this,
   uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo) */

bool __thiscall
A53::IOC::NvmTtnNotificationBuffer::updateForClearPtdmaCompletion
          (NvmTtnNotificationBuffer *this,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo)

{
  byte bVar1;
  bool bVar2;
  
  bVar1 = *(byte *)((long)&this->field_0 + 0xe);
  if (((bVar1 >> 4 & 1) == 0) ||
     (((uint)(this->field_0).field_0.m_ptdmaCmdClear * 0x20 - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)
      < (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20))) {
    bVar2 = false;
  }
  else {
    bVar2 = true;
    *(byte *)((long)&this->field_0 + 0xe) = bVar1 & 0xef;
    (this->field_0).field_0.m_ptdmaCmdClear = 0xffff;
  }
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052d78
 * symbol: updateForInitDramPtdmaCompletion
 * prototype: bool updateForInitDramPtdmaCompletion(NvmTtnNotificationBuffer * this, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForInitDramPtdmaCompletion(NvmTtnNotificationBuffer * this,
   uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo) */

bool __thiscall
A53::IOC::NvmTtnNotificationBuffer::updateForInitDramPtdmaCompletion
          (NvmTtnNotificationBuffer *this,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo)

{
  byte bVar1;
  bool bVar2;
  
  bVar1 = *(byte *)((long)&this->field_0 + 0xe);
  if (((bVar1 >> 3 & 1) == 0) ||
     (((uint)(this->field_0).field_0.m_ptdmaCmdFetch * 0x20 - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)
      < (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20))) {
    bVar2 = false;
  }
  else {
    bVar2 = true;
    *(byte *)((long)&this->field_0 + 0xe) = bVar1 & 0xf7;
    (this->field_0).field_0.m_ptdmaCmdFetch = 0xffff;
  }
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052dc8
 * symbol: scanToHead
 * prototype: uint32_t scanToHead(NvmTtnNotificationBuffer * this, uint64_t vaSramCacheBase, uint32_t numEntriesFetched)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t scanToHead(NvmTtnNotificationBuffer * this, uint64_t
   vaSramCacheBase, uint32_t numEntriesFetched) */

uint32_t __thiscall
A53::IOC::NvmTtnNotificationBuffer::scanToHead
          (NvmTtnNotificationBuffer *this,uint64_t vaSramCacheBase,uint32_t numEntriesFetched)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  
  uVar2 = 0;
  uVar3 = (uint)(this->field_0).field_0.m_head;
  while ((uVar2 < numEntriesFetched &&
         (*(int *)((this->field_0).field_0.m_offsetSramCache + vaSramCacheBase +
                   (ulong)(uVar3 & (1 << (ulong)((this->field_0).field_0.m_numNbeSramCacheLog2 &
                                                0x1f)) - 1U) * 8 + 4) != 0))) {
    uVar1 = 0;
    if (uVar3 != (this->field_0).field_0.m_sizeMinus1) {
      uVar1 = uVar3 + 1;
    }
    uVar2 = uVar2 + 1;
    uVar3 = uVar1;
  }
  if (uVar2 != 0) {
    (this->field_0).field_0.m_head = (uint16_t)uVar3;
    (this->field_0).field_0.m_numNbeToGet = (this->field_0).field_0.m_numNbeToGet + (char)uVar2;
  }
  return uVar2;
}


