/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller\a53_nvm_cq.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e34c
 * symbol: popCqe
 * prototype: bool popCqe(NvmCompletionQueue * this, uint64_t vaSramCacheBase, NvmCqe * out_cqe)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool popCqe(NvmCompletionQueue * this, uint64_t vaSramCacheBase, NvmCqe
   * out_cqe) */

bool __thiscall
A53::IOC::NvmCompletionQueue::popCqe
          (NvmCompletionQueue *this,uint64_t vaSramCacheBase,NvmCqe *out_cqe)

{
  uint64_t *puVar1;
  uint uVar2;
  
  uVar2 = (uint)(this->field_0).field_0.m_numCqeToGet;
  if (uVar2 != 0) {
    puVar1 = (uint64_t *)
             ((this->field_0).field_0.m_offsetSramCache + vaSramCacheBase +
             (ulong)((this->field_0).field_0.m_head - uVar2 &
                    (1 << (ulong)((this->field_0).field_0.m_numCqeSramCacheLog2 & 0x1f)) - 1U) *
             0x10);
    (out_cqe->field_0).asU64[0] = *puVar1;
    (out_cqe->field_0).asU64[1] = puVar1[1];
    (this->field_0).field_0.m_numCqeToGet = (this->field_0).field_0.m_numCqeToGet + 0xff;
  }
  return uVar2 != 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e3a8
 * symbol: popCqe
 * prototype: bool popCqe(NvmCompletionQueue * this, uint64_t vaSramCacheBase)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool popCqe(NvmCompletionQueue * this, uint64_t vaSramCacheBase) */

bool __thiscall
A53::IOC::NvmCompletionQueue::popCqe(NvmCompletionQueue *this,uint64_t vaSramCacheBase)

{
  uint8_t uVar1;
  
  uVar1 = (this->field_0).field_0.m_numCqeToGet;
  if (uVar1 != '\0') {
    (this->field_0).field_0.m_numCqeToGet = uVar1 + 0xff;
    return true;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e3cc
 * symbol: peekCqe
 * prototype: bool peekCqe(NvmCompletionQueue * this, uint64_t vaSramCacheBase, NvmCqe * out_cqe, uint32_t indexFromHead)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool peekCqe(NvmCompletionQueue * this, uint64_t vaSramCacheBase,
   NvmCqe * out_cqe, uint32_t indexFromHead) */

bool __thiscall
A53::IOC::NvmCompletionQueue::peekCqe
          (NvmCompletionQueue *this,uint64_t vaSramCacheBase,NvmCqe *out_cqe,uint32_t indexFromHead)

{
  uint64_t *puVar1;
  byte bVar2;
  
  bVar2 = (this->field_0).field_0.m_numCqeToGet;
  if (indexFromHead < bVar2) {
    puVar1 = (uint64_t *)
             ((this->field_0).field_0.m_offsetSramCache + vaSramCacheBase +
             (ulong)((indexFromHead - bVar2) + (uint)(this->field_0).field_0.m_head &
                    (1 << (ulong)((this->field_0).field_0.m_numCqeSramCacheLog2 & 0x1f)) - 1U) *
             0x10);
    (out_cqe->field_0).asU64[0] = *puVar1;
    (out_cqe->field_0).asU64[1] = puVar1[1];
    return true;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e424
 * symbol: issueFetch
 * prototype: IssueFetchReturn issueFetch(NvmCompletionQueue * this, A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PtdmaVqSubmitState * submit_read, uint16_t pasid)
 * body addresses: 204
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueFetchReturn issueFetch(NvmCompletionQueue * this,
   A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PtdmaVqSubmitState *
   submit_read, uint16_t pasid) */

IssueFetchReturn __thiscall
A53::IOC::NvmCompletionQueue::issueFetch
          (NvmCompletionQueue *this,A53_AddressTranslator *addressTranslator,
          uint64_t vaSramCacheBase,PtdmaVqSubmitState *submit_read,uint16_t pasid)

{
  uint uVar1;
  ushort uVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  uint32_t uVar6;
  DmaWaitOnCompletion in_w6;
  ulong uVar7;
  ulong uVar8;
  
  if ((((this->field_0).field_0.m_numCqeFetch == '\0') &&
      ((*(byte *)((long)&this->field_0 + 0xe) >> 3 & 1) == 0)) &&
     (submit_read->m_numCommandsAvailable != 0)) {
    iVar3 = 1 << (ulong)((this->field_0).field_0.m_numCqeSramCacheLog2 & 0x1f);
    uVar5 = iVar3 - (uint)(this->field_0).field_0.m_numCqeToGet;
    if (uVar5 != 0) {
      uVar2 = (this->field_0).field_0.m_head;
      uVar1 = iVar3 + 0xffffU & (uint)uVar2;
      uVar4 = iVar3 - uVar1;
      if (uVar5 <= uVar4) {
        uVar4 = uVar5;
      }
      uVar5 = uVar4 & 0xfffffff0;
      if (uVar4 < 0x11) {
        uVar5 = uVar4;
      }
      uVar8 = (ulong)uVar5;
      uVar6 = ptdmaPutCommandCopy(submit_read,uVar5 << 4,
                                  (this->field_0).field_0.m_paBase + (ulong)uVar2 * 0x10,
                                  (ulong)((uint)(this->field_0).field_0.m_offsetSramCache +
                                          (int)vaSramCacheBase + uVar1 * 0x10) & 0xfffff,pasid,
                                  (uint)(uVar5 < 0x11),in_w6);
      (this->field_0).field_0.m_numCqeFetch = (uint8_t)uVar5;
      (this->field_0).field_0.m_ptdmaCmdFetch = (uint16_t)(uVar6 >> 5);
      uVar7 = (ulong)(uVar6 >> 5 & 0xffff | 0x10000) << 0x20;
      goto LAB_0604e46c;
    }
  }
  uVar8 = 0;
  uVar7 = 0;
LAB_0604e46c:
  return (IssueFetchReturn)(uVar7 | uVar8);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e54c
 * symbol: issueHeadUpdate
 * prototype: IssueHeadUpdateReturn issueHeadUpdate(NvmCompletionQueue * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint64_t vaDriverSramCqhdbl, uint64_t paCqhdbl)
 * body addresses: 112
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueHeadUpdateReturn issueHeadUpdate(NvmCompletionQueue * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid,
   uint64_t vaDriverSramCqhdbl, uint64_t paCqhdbl) */

IssueHeadUpdateReturn __thiscall
A53::IOC::NvmCompletionQueue::issueHeadUpdate
          (NvmCompletionQueue *this,A53_AddressTranslator *addressTranslator,
          PtdmaVqSubmitState *submit_write,uint16_t pasid,uint64_t vaDriverSramCqhdbl,
          uint64_t paCqhdbl)

{
  bool bVar1;
  uint32_t uVar2;
  DmaWaitOnCompletion in_w6;
  ulong uVar3;
  
  bVar1 = submit_write->m_numCommandsAvailable == 0;
  if (bVar1) {
    uVar3 = 0;
  }
  else {
    *(uint *)vaDriverSramCqhdbl = (uint)(this->field_0).field_0.m_head;
    uVar2 = ptdmaPutCommandCopy(submit_write,4,vaDriverSramCqhdbl & 0xfffff,paCqhdbl,pasid,
                                kDmaFunctionDisablePrefetch,in_w6);
    uVar3 = (ulong)(uVar2 >> 5) << 0x20;
    (this->field_0).field_0.m_ptdmaCmdUpdateHead = (uint16_t)(uVar2 >> 5);
  }
  return (IssueHeadUpdateReturn)(uVar3 | !bVar1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e5bc
 * symbol: issueInitDram
 * prototype: IssueInitDramReturn issueInitDram(NvmCompletionQueue * this, PtdmaVqSubmitState * submit_write, uint16_t pasid)
 * body addresses: 176
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueInitDramReturn issueInitDram(NvmCompletionQueue * this,
   PtdmaVqSubmitState * submit_write, uint16_t pasid) */

IssueInitDramReturn __thiscall
A53::IOC::NvmCompletionQueue::issueInitDram
          (NvmCompletionQueue *this,PtdmaVqSubmitState *submit_write,uint16_t pasid)

{
  uint32_t uVar1;
  ulong uVar2;
  ulong uVar3;
  DmaCommand local_40;
  
  local_40.field_0.asU64[3] = (uint64_t)pasid;
  if ((((this->field_0).field_0.m_numCqeFetch == '\0') &&
      ((*(byte *)((long)&this->field_0 + 0xe) >> 3 & 1) == 0)) &&
     (submit_write->m_numCommandsAvailable != 0)) {
    uVar3 = (this->field_0).field_0.m_paBase;
    local_40.field_0.asU64[2] =
         -(uVar3 >> 0x30 & 1) & 0x3000000000000 |
         uVar3 & 0xffffffff | (uVar3 >> 0x20 & 0xffff) << 0x20;
    local_40.field_0.asU64[0] =
         (ulong)((uint)(this->field_0).field_0.m_sizeMinus1 * 0x10 + 0x10) << 0x20;
    local_40.field_0.asU64[1] = 0x1000000000000;
    uVar1 = ptdmaPutCommand(submit_write,&local_40);
    (this->field_0).field_0.m_ptdmaCmdFetch = (uint16_t)(uVar1 >> 5);
    uVar2 = (ulong)(uVar1 >> 5) << 0x20;
    uVar3 = 1;
    *(ushort *)((long)&this->field_0 + 0xe) = *(ushort *)((long)&this->field_0 + 0xe) | 8;
  }
  else {
    uVar3 = 0;
    uVar2 = 0;
  }
  return (IssueInitDramReturn)(uVar2 | uVar3);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e66c
 * symbol: updateForFetchPtdmaCompletion
 * prototype: uint32_t updateForFetchPtdmaCompletion(NvmCompletionQueue * this, uint64_t vaSramCacheBase, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 204
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t updateForFetchPtdmaCompletion(NvmCompletionQueue * this,
   uint64_t vaSramCacheBase, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
    */

uint32_t __thiscall
A53::IOC::NvmCompletionQueue::updateForFetchPtdmaCompletion
          (NvmCompletionQueue *this,uint64_t vaSramCacheBase,uint32_t ptdmaSizeofQueue,
          uint32_t ptdmaHeadLo,uint32_t ptdmaTailLo)

{
  ulong uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint32_t uVar5;
  ulong uVar6;
  uint uVar7;
  
  if (((uint)(this->field_0).field_0.m_ptdmaCmdFetch * 0x20 - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)
      < (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)) {
    uVar5 = 0;
  }
  else {
    uVar5 = (uint32_t)(this->field_0).field_0.m_numCqeFetch;
    uVar3 = 1 << (ulong)((this->field_0).field_0.m_numCqeSramCacheLog2 & 0x1f);
    uVar4 = uVar3 - 1;
    uVar7 = (uint)(this->field_0).field_0.m_head;
    uVar1 = (this->field_0).field_0.m_offsetSramCache + vaSramCacheBase;
    uVar2 = uVar4 & uVar7;
    uVar4 = uVar7 + uVar5 & uVar4;
    uVar6 = uVar1 + (uVar2 << 4) & 0xffffffffffffffc0;
    if (uVar4 <= uVar2) {
      for (; uVar6 < (uVar1 + (ulong)uVar3 * 0x10 + 0x3f & 0xffffffffffffffc0); uVar6 = uVar6 + 0x40
          ) {
        DC_CIVAC(uVar6);
      }
      uVar6 = uVar1 & 0xffffffffffffffc0;
    }
    for (; uVar6 < (uVar1 + (uVar4 << 4) + 0x3f & 0xffffffffffffffc0); uVar6 = uVar6 + 0x40) {
      DC_CIVAC(uVar6);
    }
    UnkSytemRegWrite(0,3,3,0xd,4,0);
    (this->field_0).field_0.m_numCqeFetch = '\0';
    (this->field_0).field_0.m_ptdmaCmdFetch = 0xffff;
  }
  return uVar5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e738
 * symbol: updateForHeadUpdatePtdmaCompletion
 * prototype: bool updateForHeadUpdatePtdmaCompletion(NvmCompletionQueue * this, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForHeadUpdatePtdmaCompletion(NvmCompletionQueue * this,
   uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo) */

bool __thiscall
A53::IOC::NvmCompletionQueue::updateForHeadUpdatePtdmaCompletion
          (NvmCompletionQueue *this,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo)

{
  bool bVar1;
  
  bVar1 = (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20) <=
          ((uint)(this->field_0).field_0.m_ptdmaCmdUpdateHead * 0x20 - ptdmaHeadLo &
          ptdmaSizeofQueue - 0x20);
  if (bVar1) {
    (this->field_0).field_0.m_ptdmaCmdUpdateHead = 0xffff;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e778
 * symbol: updateForInitDramPtdmaCompletion
 * prototype: bool updateForInitDramPtdmaCompletion(NvmCompletionQueue * this, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForInitDramPtdmaCompletion(NvmCompletionQueue * this,
   uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo) */

bool __thiscall
A53::IOC::NvmCompletionQueue::updateForInitDramPtdmaCompletion
          (NvmCompletionQueue *this,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo)

{
  bool bVar1;
  
  bVar1 = (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20) <=
          ((uint)(this->field_0).field_0.m_ptdmaCmdFetch * 0x20 - ptdmaHeadLo &
          ptdmaSizeofQueue - 0x20);
  if (bVar1) {
    (this->field_0).field_0.m_ptdmaCmdFetch = 0xffff;
    *(ushort *)((long)&this->field_0 + 0xe) = *(ushort *)((long)&this->field_0 + 0xe) & 0xfff7;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e7c4
 * symbol: scanToHead
 * prototype: uint32_t scanToHead(NvmCompletionQueue * this, uint64_t vaSramCacheBase, uint32_t numCqeFetched, PfnHandleCqe pfnHandleCqe, void * pContextHandleCqe)
 * body addresses: 244
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t scanToHead(NvmCompletionQueue * this, uint64_t
   vaSramCacheBase, uint32_t numCqeFetched, PfnHandleCqe pfnHandleCqe, void * pContextHandleCqe) */

uint32_t __thiscall
A53::IOC::NvmCompletionQueue::scanToHead
          (NvmCompletionQueue *this,uint64_t vaSramCacheBase,uint32_t numCqeFetched,
          PfnHandleCqe pfnHandleCqe,void *pContextHandleCqe)

{
  uint64_t *puVar1;
  uint uVar2;
  byte bVar3;
  ushort uVar4;
  ushort uVar5;
  bool bVar6;
  uint uVar7;
  uint uVar8;
  uint uVar9;
  NvmCqe local_70;
  
  bVar3 = (this->field_0).field_0.m_numCqeSramCacheLog2;
  uVar4 = (this->field_0).field_0.m_offsetSramCache;
  uVar5 = (this->field_0).field_0.m_sizeMinus1;
  uVar9 = *(byte *)((long)&this->field_0 + 0xf) & 1;
  uVar8 = (uint)(this->field_0).field_0.m_head;
  for (uVar7 = 0; uVar7 < numCqeFetched; uVar7 = uVar7 + 1) {
    puVar1 = (uint64_t *)
             (uVar4 + vaSramCacheBase + (ulong)(uVar8 & (1 << (ulong)(bVar3 & 0x1f)) - 1U) * 0x10);
    local_70.field_0.asU64[0] = *puVar1;
    local_70.field_0.asU64[1] = puVar1[1];
    if ((((ushort)(local_70.field_0.asU64[1] >> 0x30) & 1) == uVar9) ||
       (bVar6 = (*pfnHandleCqe)(&local_70,pContextHandleCqe), !bVar6)) break;
    bVar6 = uVar8 == uVar5;
    uVar2 = 0;
    if (!bVar6) {
      uVar2 = uVar8 + 1;
    }
    uVar9 = uVar9 ^ bVar6;
    uVar8 = uVar2;
  }
  if (uVar7 != 0) {
    (this->field_0).field_0.m_head = (uint16_t)uVar8;
    (this->field_0).field_0.m_numCqeToGet = (this->field_0).field_0.m_numCqeToGet + (char)uVar7;
    *(ushort *)((long)&this->field_0 + 0xe) =
         *(ushort *)((long)&this->field_0 + 0xe) & 0xfeff | (ushort)(uVar9 << 8);
  }
  return uVar7;
}


