/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller\a53_nvm_sq.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e90c
 * symbol: isFull
 * prototype: bool isFull(NvmSubmissionQueue * this)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isFull(NvmSubmissionQueue * this) */

bool __thiscall A53::IOC::NvmSubmissionQueue::isFull(NvmSubmissionQueue *this)

{
  uint uVar1;
  uint uVar2;
  ushort uVar3;
  uint uVar4;
  
  uVar3 = (this->field_0).field_0.m_sizeMinus1;
  uVar1 = (uint)(this->field_0).field_0.m_numSqePut + (uint)(this->field_0).field_0.m_tail;
  uVar2 = 0;
  if (uVar3 < uVar1) {
    uVar2 = ~(uint)uVar3;
  }
  uVar4 = (uint)(this->field_0).field_0.m_head;
  if (uVar4 == 0) {
    uVar4 = uVar3 + 1;
  }
  return uVar1 + uVar2 + 1 == uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e944
 * symbol: getNumSqeAvailable
 * prototype: uint32_t getNumSqeAvailable(NvmSubmissionQueue * this)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumSqeAvailable(NvmSubmissionQueue * this) */

uint32_t __thiscall A53::IOC::NvmSubmissionQueue::getNumSqeAvailable(NvmSubmissionQueue *this)

{
  uint uVar1;
  int iVar2;
  ushort uVar3;
  ushort uVar4;
  
  uVar3 = (this->field_0).field_0.m_sizeMinus1;
  uVar1 = (uint)(this->field_0).field_0.m_numSqePut + (uint)(this->field_0).field_0.m_tail;
  uVar4 = (this->field_0).field_0.m_head;
  iVar2 = 0;
  if (uVar3 < uVar1) {
    iVar2 = uVar3 + 1;
  }
  uVar1 = uVar1 - iVar2;
  iVar2 = 0;
  if ((uint)uVar4 < uVar1 + 1) {
    iVar2 = uVar3 + 1;
  }
  return ~uVar1 + (uint)uVar4 + iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e980
 * symbol: putSqe
 * prototype: bool putSqe(NvmSubmissionQueue * this, uint64_t vaSramCacheBase, NvmSqe * sqe)
 * body addresses: 164
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool putSqe(NvmSubmissionQueue * this, uint64_t vaSramCacheBase, NvmSqe
   * sqe) */

bool __thiscall
A53::IOC::NvmSubmissionQueue::putSqe(NvmSubmissionQueue *this,uint64_t vaSramCacheBase,NvmSqe *sqe)

{
  uint64_t *puVar1;
  int iVar2;
  uint64_t uVar3;
  ushort uVar4;
  uint uVar5;
  bool bVar6;
  uint uVar7;
  uint uVar8;
  
  uVar5 = 1 << (ulong)((this->field_0).field_0.m_numSqeSramCacheLog2 & 0x1f);
  uVar7 = (uint)(this->field_0).field_0.m_numSqePut;
  if (uVar5 == uVar7) {
    bVar6 = false;
  }
  else {
    bVar6 = false;
    uVar4 = (this->field_0).field_0.m_sizeMinus1;
    uVar7 = (this->field_0).field_0.m_tail + uVar7;
    iVar2 = 0;
    if (uVar4 < uVar7) {
      iVar2 = uVar4 + 1;
    }
    uVar8 = (uint)(this->field_0).field_0.m_head;
    uVar7 = uVar7 - iVar2;
    if (uVar8 == 0) {
      uVar8 = uVar4 + 1;
    }
    if (uVar7 + 1 != uVar8) {
      uVar3 = (sqe->field_0).field_0.rsv1;
      puVar1 = (uint64_t *)
               (vaSramCacheBase + (ulong)(uVar7 & uVar5 - 1) * 0x40 +
               (ulong)(this->field_0).field_0.m_offsetSramCache);
      *puVar1 = (sqe->field_0).asU64[0];
      puVar1[1] = uVar3;
      uVar3 = (sqe->field_0).asU64[3];
      puVar1[2] = (sqe->field_0).field_0.MPTR;
      puVar1[3] = uVar3;
      uVar3 = (sqe->field_0).asU64[5];
      puVar1[4] = (sqe->field_0).asU64[4];
      puVar1[5] = uVar3;
      uVar3 = (sqe->field_0).asU64[7];
      puVar1[6] = (sqe->field_0).asU64[6];
      puVar1[7] = uVar3;
      DC_CVAC(puVar1);
      bVar6 = true;
      (this->field_0).field_0.m_numSqePut = (this->field_0).field_0.m_numSqePut + '\x01';
    }
  }
  return bVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604ea24
 * symbol: debug_trace_getSqeLastPut
 * prototype: void debug_trace_getSqeLastPut(NvmSubmissionQueue * this, uint64_t vaSramCacheBase, NvmSqe * out_sqe)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void debug_trace_getSqeLastPut(NvmSubmissionQueue * this, uint64_t
   vaSramCacheBase, NvmSqe * out_sqe) */

void __thiscall
A53::IOC::NvmSubmissionQueue::debug_trace_getSqeLastPut
          (NvmSubmissionQueue *this,uint64_t vaSramCacheBase,NvmSqe *out_sqe)

{
  uint64_t *puVar1;
  
  puVar1 = (uint64_t *)
           ((this->field_0).field_0.m_offsetSramCache + vaSramCacheBase +
           (ulong)(((uint)(this->field_0).field_0.m_tail + (uint)(this->field_0).field_0.m_numSqePut
                   ) - 1 & (1 << (ulong)((this->field_0).field_0.m_numSqeSramCacheLog2 & 0x1f)) - 1U
                  ) * 0x40);
  (out_sqe->field_0).asU64[0] = *puVar1;
  (out_sqe->field_0).field_0.rsv1 = puVar1[1];
  (out_sqe->field_0).field_0.MPTR = puVar1[2];
  (out_sqe->field_0).asU64[3] = puVar1[3];
  (out_sqe->field_0).asU64[4] = puVar1[4];
  (out_sqe->field_0).asU64[5] = puVar1[5];
  (out_sqe->field_0).asU64[6] = puVar1[6];
  (out_sqe->field_0).asU64[7] = puVar1[7];
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604ea98
 * symbol: issueSubmit
 * prototype: IssueSubmitReturn issueSubmit(NvmSubmissionQueue * this, A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint32_t numSqe)
 * body addresses: 564
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueSubmitReturn issueSubmit(NvmSubmissionQueue * this,
   A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PtdmaVqSubmitState *
   submit_write, uint16_t pasid, uint32_t numSqe) */

IssueSubmitReturn __thiscall
A53::IOC::NvmSubmissionQueue::issueSubmit
          (NvmSubmissionQueue *this,A53_AddressTranslator *addressTranslator,
          uint64_t vaSramCacheBase,PtdmaVqSubmitState *submit_write,uint16_t pasid,uint32_t numSqe)

{
  uint64_t paDst;
  int iVar1;
  byte bVar2;
  ushort uVar3;
  int iVar4;
  uint uVar5;
  uint32_t uVar6;
  ulong paSrc;
  uint uVar7;
  ulong uVar8;
  uint16_t uVar9;
  uint uVar10;
  uint64_t paDst_00;
  uint uVar11;
  uint uVar12;
  
  if ((this->field_0).field_0.m_sizeMinus1 == 0) {
LAB_0604eb90:
    uVar11 = 0;
    uVar8 = 0;
    goto LAB_0604eb98;
  }
  uVar8 = 0;
  uVar11 = 0;
  if ((numSqe == 0) || ((*(ushort *)((long)&this->field_0 + 0xe) & 6) != 0)) goto LAB_0604eb98;
  uVar8 = 0;
  bVar2 = (this->field_0).field_0.m_numSqeSubmit;
  uVar11 = 0;
  if (((this->field_0).field_0.m_numSqePut <= bVar2) || (bVar2 != 0)) goto LAB_0604eb98;
  if (submit_write->m_numCommandsAvailable == 0) goto LAB_0604eb90;
  DataSynchronizationBarrier(3,3);
  uVar3 = (this->field_0).field_0.m_sizeMinus1;
  uVar10 = (uint)(this->field_0).field_0.m_numSqeSubmit;
  uVar7 = uVar10 + (this->field_0).field_0.m_tail;
  uVar8 = (this->field_0).field_0.m_offsetSramCache + vaSramCacheBase;
  iVar1 = 0;
  if (uVar3 < uVar7) {
    iVar1 = uVar3 + 1;
  }
  iVar4 = 1 << (ulong)((this->field_0).field_0.m_numSqeSramCacheLog2 & 0x1f);
  uVar10 = (this->field_0).field_0.m_numSqePut - uVar10;
  paDst_00 = (this->field_0).field_0.m_paBase;
  uVar7 = uVar7 - iVar1;
  uVar11 = uVar7 & iVar4 - 1U;
  if (numSqe <= uVar10) {
    uVar10 = numSqe;
  }
  paDst = paDst_00 + (ulong)uVar7 * 0x40;
  paSrc = (ulong)((int)uVar8 + uVar11 * 0x40) & 0xfffff;
  uVar11 = iVar4 - uVar11;
  if (uVar10 < 5) {
LAB_0604ebdc:
    uVar5 = uVar10 - uVar11;
    if (uVar10 < uVar11 || uVar5 == 0) goto LAB_0604ec74;
    uVar6 = ptdmaPutCommandCopy(submit_write,(uint32_t)((ulong)uVar11 * 0x40),paSrc,paDst,pasid,
                                (uint)(uVar11 < 5),(uint)(submit_write->m_numCommandsAvailable == 1)
                               );
    uVar12 = uVar6 >> 5;
    uVar9 = (uint16_t)uVar12;
    if (submit_write->m_numCommandsAvailable == 0) {
      uVar7 = 0x10000;
    }
    else {
      if (uVar11 + uVar7 != uVar3 + 1) {
        paDst_00 = (ulong)uVar11 * 0x40 + paDst;
      }
      uVar6 = ptdmaPutCommandCopy(submit_write,uVar5 * 0x40,uVar8 & 0xfffff,paDst_00,pasid,
                                  (uint)(uVar5 < 5),kDmaWaitOnCompletionEnable);
      uVar7 = 0x20000;
      uVar9 = (uint16_t)(uVar6 >> 5);
      uVar11 = uVar10;
    }
  }
  else {
    uVar5 = uVar10 - uVar11;
    if (uVar10 < uVar11 || uVar5 == 0) {
      uVar10 = uVar10 & 0xfffffffc;
      goto LAB_0604ebdc;
    }
    if ((uVar11 < 5) || ((uVar11 & 3) == 0)) {
      if ((uVar5 & 3) != 0 && 4 < uVar5) {
        uVar10 = (uVar5 & 0xfffffffc) + uVar11;
      }
      goto LAB_0604ebdc;
    }
    uVar10 = uVar11 & 0xfffffffc;
LAB_0604ec74:
    uVar6 = ptdmaPutCommandCopy(submit_write,uVar10 << 6,paSrc,paDst,pasid,(uint)(uVar10 < 5),
                                kDmaWaitOnCompletionEnable);
    uVar12 = uVar6 >> 5;
    uVar9 = (uint16_t)uVar12;
    uVar7 = 0x10000;
    uVar11 = uVar10;
  }
  (this->field_0).field_0.m_ptdmaCmdSubmit = uVar9;
  uVar8 = (ulong)(uVar7 | uVar12 & 0xffff) << 0x20;
  (this->field_0).field_0.m_numSqeSubmit = (char)uVar11 + (this->field_0).field_0.m_numSqeSubmit;
LAB_0604eb98:
  return (IssueSubmitReturn)(uVar8 | uVar11);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604ed54
 * symbol: issueTailUpdate
 * prototype: IssueTailUpdateReturn issueTailUpdate(NvmSubmissionQueue * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint64_t vaSramCacheSqtdbl, uint64_t paSqtdbl)
 * body addresses: 152
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueTailUpdateReturn issueTailUpdate(NvmSubmissionQueue * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid,
   uint64_t vaSramCacheSqtdbl, uint64_t paSqtdbl) */

IssueTailUpdateReturn __thiscall
A53::IOC::NvmSubmissionQueue::issueTailUpdate
          (NvmSubmissionQueue *this,A53_AddressTranslator *addressTranslator,
          PtdmaVqSubmitState *submit_write,uint16_t pasid,uint64_t vaSramCacheSqtdbl,
          uint64_t paSqtdbl)

{
  uint uVar1;
  int iVar2;
  ushort uVar3;
  uint32_t uVar4;
  ulong uVar5;
  ulong uVar6;
  
  if (submit_write->m_numCommandsAvailable == 0) {
    uVar5 = 0;
    uVar6 = 0;
  }
  else {
    uVar3 = (this->field_0).field_0.m_sizeMinus1;
    uVar1 = (uint)(this->field_0).field_0.m_numSqeSubmit + (uint)(this->field_0).field_0.m_tail;
    iVar2 = 0;
    if (uVar3 < uVar1) {
      iVar2 = uVar3 + 1;
    }
    *(uint *)vaSramCacheSqtdbl = uVar1 - iVar2;
    DC_CVAC(vaSramCacheSqtdbl & 0xffffffffffffffc0);
    DataSynchronizationBarrier(3,3);
    uVar4 = ptdmaPutCommandCopy(submit_write,4,vaSramCacheSqtdbl & 0xfffff,paSqtdbl,pasid,
                                kDmaFunctionDisablePrefetch,kDmaWaitOnCompletionDisable);
    uVar5 = 1;
    uVar6 = (ulong)(uVar4 >> 5) << 0x20;
    (this->field_0).field_0.m_ptdmaCmdUpdateTail = (uint16_t)(uVar4 >> 5);
  }
  return (IssueTailUpdateReturn)(uVar6 | uVar5);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604edec
 * symbol: updateForSubmitPtdmaCompletion
 * prototype: uint32_t updateForSubmitPtdmaCompletion(NvmSubmissionQueue * this, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t updateForSubmitPtdmaCompletion(NvmSubmissionQueue * this,
   uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo) */

uint32_t __thiscall
A53::IOC::NvmSubmissionQueue::updateForSubmitPtdmaCompletion
          (NvmSubmissionQueue *this,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo)

{
  uint uVar1;
  byte bVar2;
  ushort uVar3;
  uint16_t uVar4;
  uint32_t uVar5;
  
  if (((uint)(this->field_0).field_0.m_ptdmaCmdSubmit * 0x20 - ptdmaHeadLo & ptdmaSizeofQueue - 0x20
      ) < (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)) {
    uVar5 = 0;
  }
  else {
    bVar2 = (this->field_0).field_0.m_numSqeSubmit;
    uVar5 = (uint32_t)bVar2;
    uVar3 = (this->field_0).field_0.m_sizeMinus1;
    uVar1 = (this->field_0).field_0.m_tail + uVar5;
    (this->field_0).field_0.m_numSqePut = (this->field_0).field_0.m_numSqePut - bVar2;
    uVar4 = (uint16_t)uVar1;
    (this->field_0).field_0.m_tail = uVar4;
    if ((uint)uVar3 < (uVar1 & 0xffff)) {
      (this->field_0).field_0.m_tail = (uVar4 - 1) - uVar3;
    }
    (this->field_0).field_0.m_numSqeSubmit = '\0';
    (this->field_0).field_0.m_ptdmaCmdSubmit = 0xffff;
  }
  return uVar5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604ee68
 * symbol: updateForTailUpdatePtdmaCompletion
 * prototype: bool updateForTailUpdatePtdmaCompletion(NvmSubmissionQueue * this, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForTailUpdatePtdmaCompletion(NvmSubmissionQueue * this,
   uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo) */

bool __thiscall
A53::IOC::NvmSubmissionQueue::updateForTailUpdatePtdmaCompletion
          (NvmSubmissionQueue *this,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo)

{
  bool bVar1;
  
  bVar1 = (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20) <=
          ((uint)(this->field_0).field_0.m_ptdmaCmdUpdateTail * 0x20 - ptdmaHeadLo &
          ptdmaSizeofQueue - 0x20);
  if (bVar1) {
    (this->field_0).field_0.m_ptdmaCmdUpdateTail = 0xffff;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604eea8
 * symbol: updateHeadForCqe
 * prototype: bool updateHeadForCqe(NvmSubmissionQueue * this, uint32_t iCq, NvmCqe * cqe)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateHeadForCqe(NvmSubmissionQueue * this, uint32_t iCq, NvmCqe *
   cqe) */

bool __thiscall
A53::IOC::NvmSubmissionQueue::updateHeadForCqe(NvmSubmissionQueue *this,uint32_t iCq,NvmCqe *cqe)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  ushort uVar6;
  ushort uVar7;
  uint uVar8;
  uint uVar9;
  
  uVar6 = (this->field_0).field_0.m_sizeMinus1;
  if (((uVar6 == 0) || (uVar7 = *(ushort *)((long)&this->field_0 + 0xe), (uVar7 & 6) != 0)) ||
     ((uVar7 >> 0xc & 7) != iCq)) {
    return false;
  }
  uVar7 = (this->field_0).field_0.m_head;
  uVar2 = (uint)(cqe->field_0).asU64[1] & 0xffff;
  uVar9 = (uint)uVar7;
  if (uVar2 == uVar9) {
    return true;
  }
  uVar1 = (uint)(this->field_0).field_0.m_numSqeSubmit + (uint)(this->field_0).field_0.m_tail;
  uVar8 = (uint)uVar6;
  iVar3 = 0;
  if (uVar6 <= uVar1 && uVar1 != uVar8) {
    iVar3 = uVar8 + 1;
  }
  iVar4 = 0;
  if (uVar1 - iVar3 < uVar9) {
    iVar4 = uVar8 + 1;
  }
  iVar5 = 0;
  if (uVar2 < uVar7) {
    iVar5 = uVar8 + 1;
  }
  if (((uVar1 - iVar3) - uVar9) + iVar4 < (uVar2 - uVar7) + iVar5) {
    return false;
  }
  (this->field_0).field_0.m_head = (uint16_t)(cqe->field_0).asU64[1];
  return true;
}


