/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller/a53_io_controller.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06013704
 * symbol: makeDeviceOpSource_InputCommand_SramPipeline
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_SramPipeline(IOC * this, IoSramPipeline eIoSramPipeline, uint16_t pipelineCommandId, DeviceOpSourceIsAppPasid eIsAppPasid, uint32_t notifyHeaderStateBit)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


DeviceOpSource __thiscall
A53::IOC::makeDeviceOpSource_InputCommand_SramPipeline
          (IOC *this,IoSramPipeline eIoSramPipeline,uint16_t pipelineCommandId,
          DeviceOpSourceIsAppPasid eIsAppPasid,uint32_t notifyHeaderStateBit)

{
  anon_union_4_12_db32e35f_for_DeviceOpSource_0 aVar1;
  
  aVar1.field_0 =
       (anon_struct_4_2_f2ff4ae4_for_anon_union_4_12_db32e35f_for_DeviceOpSource_0_0)
       makeDeviceOpSource_InputCommand_SramPipeline
                 ((IoSramPipeline)this,(uint16_t)eIoSramPipeline,kDeviceOpSourceIsAppPasid,
                  (uint)pipelineCommandId,notifyHeaderStateBit);
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)aVar1.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06014504
 * symbol: pipelineCommandDataHeader_unpackCqeIoErrorCode
 * prototype: bool pipelineCommandDataHeader_unpackCqeIoErrorCode(uint32_t packedCqeErrorCode, NvmStatusCodeType * out_SCT, uint32_t * out_SC)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::IOC::pipelineCommandDataHeader_unpackCqeIoErrorCode
               (uint32_t packedCqeErrorCode,NvmStatusCodeType *out_SCT,uint32_t *out_SC)

{
  uint uVar1;
  NvmStatusCodeType NVar2;
  
  if (packedCqeErrorCode < 0x18 || packedCqeErrorCode - 0x40 < 0x18) {
    NVar2 = SCT_GENERIC;
  }
  else if (packedCqeErrorCode - 0x18 < 0x20 || packedCqeErrorCode - 0x58 < 7) {
    NVar2 = SCT_COMMAND_SPECIFIC;
  }
  else {
    if ((packedCqeErrorCode & 0xfffffff8) != 0x70) {
      return false;
    }
    NVar2 = SCT_MEDIA_AND_DATA_INTEGRITY;
  }
  *out_SCT = NVar2;
  uVar1 = packedCqeErrorCode + NVar2 * -0x18;
  *out_SC = uVar1 & 0x1f | (uVar1 >> 4 & 7) << 5;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06020010
 * symbol: makeDeviceOpSource_InputCommand_DramPipeline_OpIssue
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_DramPipeline_OpIssue(IOC * this, IoDramPipeline eIoDramPipeline, IoControllerCommandRing eRing, uint16_t commandRingExecutingCommandId, DeviceOpSourceIsAppPasid eIsAppPasid, uint32_t notifyHeaderStateBit)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


DeviceOpSource __thiscall
A53::IOC::makeDeviceOpSource_InputCommand_DramPipeline_OpIssue
          (IOC *this,IoDramPipeline eIoDramPipeline,IoControllerCommandRing eRing,
          uint16_t commandRingExecutingCommandId,DeviceOpSourceIsAppPasid eIsAppPasid,
          uint32_t notifyHeaderStateBit)

{
  anon_union_4_12_db32e35f_for_DeviceOpSource_0 aVar1;
  
  aVar1.field_0 =
       (anon_struct_4_2_f2ff4ae4_for_anon_union_4_12_db32e35f_for_DeviceOpSource_0_0)
       makeDeviceOpSource_InputCommand_DramPipeline_OpIssue
                 ((IoDramPipeline)this,eIoDramPipeline,(uint16_t)eRing,kDeviceOpSourceIsAppPasid,
                  (uint)commandRingExecutingCommandId,notifyHeaderStateBit);
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)aVar1.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06043980
 * symbol: makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp(IoDramPipeline eIoDramPipeline, uint16_t ioDeviceOpId, DeviceOpSourceIsAppPasid eIsAppPasid, uint32_t notifyHeaderStateBit)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

DeviceOpSource
A53::IOC::makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
          (IoDramPipeline eIoDramPipeline,uint16_t ioDeviceOpId,DeviceOpSourceIsAppPasid eIsAppPasid
          ,uint32_t notifyHeaderStateBit)

{
  anon_union_4_12_db32e35f_for_DeviceOpSource_0 aVar1;
  
  aVar1.field_0 =
       (anon_struct_4_2_f2ff4ae4_for_anon_union_4_12_db32e35f_for_DeviceOpSource_0_0)
       makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
                 (eIoDramPipeline,ioDeviceOpId,eIsAppPasid,kDeviceOpSourceNotifyCommand,
                  notifyHeaderStateBit);
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)aVar1.field_0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06048494
 * symbol: makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp(IoDramPipeline eIoDramPipeline, uint16_t ioDeviceOpId, DeviceOpSourceIsAppPasid eIsAppPasid, DeviceOpSourceNotify eNotify, uint32_t notifyHeaderStateBit)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

DeviceOpSource
A53::IOC::makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
          (IoDramPipeline eIoDramPipeline,uint16_t ioDeviceOpId,DeviceOpSourceIsAppPasid eIsAppPasid
          ,DeviceOpSourceNotify eNotify,uint32_t notifyHeaderStateBit)

{
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         ((eIsAppPasid & 1) << 0x1a | (eNotify & 1) << 0x19 |
          (eIoDramPipeline & 0xf) << 0x10 |
          ioDeviceOpId & 0x7fff |
          (uint)(eNotify == kDeviceOpSourceNotifyCommandOnCounterDecrementToZero) << 0xf |
          (notifyHeaderStateBit & 0xf |
          (uint)(eNotify == kDeviceOpSourceNotifyCommandOnGcrSyncIssueAndCompletion) << 3) << 0x15 |
         0xe8000000);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604c82c
 * symbol: makeDeviceOpSource_InputCommand_DramPipeline_OpConsume
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_DramPipeline_OpConsume(IoDramPipeline eIoDramPipeline, IoControllerCommandRing eRing, uint16_t commandRingExecutingCommandId, DeviceOpSourceIsAppPasid eIsAppPasid, DeviceOpSourceNotify eNotify, uint32_t notifyHeaderStateBit)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

DeviceOpSource
A53::IOC::makeDeviceOpSource_InputCommand_DramPipeline_OpConsume
          (IoDramPipeline eIoDramPipeline,IoControllerCommandRing eRing,
          uint16_t commandRingExecutingCommandId,DeviceOpSourceIsAppPasid eIsAppPasid,
          DeviceOpSourceNotify eNotify,uint32_t notifyHeaderStateBit)

{
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         ((eIsAppPasid & 1) << 0x1a | (eNotify & 1) << 0x19 |
          (eRing & 0x1f) << 0xb | (eIoDramPipeline & 0xf) << 0x10 |
          commandRingExecutingCommandId & 0x7ff |
          (notifyHeaderStateBit & 0xf |
          (uint)(eNotify == kDeviceOpSourceNotifyCommandOnGcrSyncIssueAndCompletion) << 3) << 0x15 |
         0xe0100000);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604c860
 * symbol: makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
 * prototype: DeviceOpSource makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp(IoDramPipeline eIoDramPipeline, uint16_t ioDeviceOpId, DeviceOpSourceIsAppPasid eIsAppPasid)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

DeviceOpSource
A53::IOC::makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
          (IoDramPipeline eIoDramPipeline,uint16_t ioDeviceOpId,DeviceOpSourceIsAppPasid eIsAppPasid
          )

{
  anon_union_4_12_db32e35f_for_DeviceOpSource_0 aVar1;
  
  aVar1.field_0 =
       (anon_struct_4_2_f2ff4ae4_for_anon_union_4_12_db32e35f_for_DeviceOpSource_0_0)
       makeDeviceOpSource_InputCommand_DramPipeline_IoDeviceOp
                 (eIoDramPipeline,ioDeviceOpId,eIsAppPasid,kDeviceOpSourceNotifyDisabled,0xf);
  return (anon_union_4_12_db32e35f_for_DeviceOpSource_0)
         (anon_union_4_12_db32e35f_for_DeviceOpSource_0)aVar1.field_0;
}


