/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller\io_controller_sram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06059de4
 * symbol: io_controller_sram
 * prototype: int io_controller_sram(void)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int io_controller_sram(void)

{
  undefined8 uVar1;
  
  printf("%s()\n","io_controller_sram");
  printf("%s:0x%08x = 0x%08x\n","io_controller_sram",&DAT_042270c0,(ulong)_DAT_042270c0);
  uVar1 = dczid_el0;
  printf("%s:_DCZID_EL0 = 0x%08x\n","io_controller_sram",uVar1);
  DC_ZVA(0x4227000);
  controller_sram();
  io_controller_run();
  return 0;
}


