/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/io_controller\io_controller_boot.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06059d38
 * symbol: io_controller_boot_setup
 * prototype: void io_controller_boot_setup(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void io_controller_boot_setup(void)

{
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06059d3c
 * symbol: io_controller_run
 * prototype: void io_controller_run(void)
 * body addresses: 168
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void io_controller_run(void)

{
  bool bVar1;
  
  printf("io_controller_run(): vaSramIoController=0x%08llx, vaSRAM_IoController_BootConfiguration=0x%08llx\n"
         ,&DAT_042270c0,&core0_boot_config);
  A53::IOC::IoController::construct((IoController *)&DAT_042270c0);
  printf("io_controller_run(): pIoController->clear()\n");
  A53::IOC::IoController::clear((IoController *)&DAT_042270c0);
  printf("io_controller_run(): pIoController->startup()\n");
  bVar1 = A53::IOC::IoController::startup((IoController *)&DAT_042270c0,0x4e0c000);
  if (bVar1) {
    printf("io_controller_run(): do { pIoController->execute() } while (true);\n");
    do {
      A53::IOC::IoController::execute((IoController *)&DAT_042270c0);
    } while( true );
  }
  printf("io_controller_run(): pIoController->startup() failed!\n");
  printf("io_controller_run(): pIoController->~IoController();\n");
  A53::IOC::IoController::~IoController((IoController *)&DAT_042270c0);
  return;
}


