/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_memory_wrapper.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060661d4
 * symbol: A53_MEMSET_ZERO
 * prototype: void A53_MEMSET_ZERO(uint64_t va, uint64_t length)
 * body addresses: 372
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::A53_MEMSET_ZERO(uint64_t va,uint64_t length)

{
  undefined8 *puVar1;
  undefined8 *puVar2;
  undefined8 *puVar3;
  ulong uVar4;
  long lVar5;
  undefined8 *puVar6;
  
  if (length == 0) {
    return;
  }
  puVar1 = (undefined8 *)(length + va);
  if ((va & 0x3f) != 0) {
    puVar2 = (undefined8 *)va;
    if ((va & 0xf) != 0) {
      if ((va & 1) != 0) {
        puVar2 = (undefined8 *)(va + 1);
        *(undefined *)va = 0;
      }
      if (puVar1 < (undefined8 *)((long)puVar2 + 2)) goto LAB_060662c8;
      if (((uint)puVar2 >> 1 & 1) != 0) {
        *(undefined2 *)puVar2 = 0;
        puVar2 = (undefined8 *)((long)puVar2 + 2);
      }
      if (puVar1 < (undefined8 *)((long)puVar2 + 4)) goto LAB_060662c8;
      if (((uint)puVar2 >> 2 & 1) != 0) {
        *(undefined4 *)puVar2 = 0;
        puVar2 = (undefined8 *)((long)puVar2 + 4);
      }
      if (puVar1 < puVar2 + 1) goto LAB_060662c8;
      if (((uint)puVar2 >> 3 & 1) != 0) {
        *puVar2 = 0;
        puVar2 = puVar2 + 1;
      }
    }
    uVar4 = va + 0x3f & 0xffffffffffffffc0;
    if (((ulong)puVar1 & 0xfffffffffffffff0) <= uVar4) {
      uVar4 = (ulong)puVar1 & 0xfffffffffffffff0;
    }
    lVar5 = uVar4 - (long)puVar2;
    if (lVar5 == 0x10) {
LAB_06066280:
      va = (uint64_t)(puVar2 + 2);
      *puVar2 = 0;
      puVar2[1] = 0;
    }
    else {
      puVar3 = puVar2;
      if (lVar5 == 0x20) {
LAB_0606627c:
        puVar2 = puVar3 + 2;
        *puVar3 = 0;
        puVar3[1] = 0;
        goto LAB_06066280;
      }
      va = (uint64_t)puVar2;
      if (lVar5 == 0x30) {
        puVar3 = puVar2 + 2;
        *puVar2 = 0;
        puVar2[1] = 0;
        goto LAB_0606627c;
      }
    }
    puVar2 = (undefined8 *)va;
    if (puVar1 < (undefined8 *)(va + 0x40)) goto LAB_060662c8;
  }
  puVar3 = (undefined8 *)((ulong)puVar1 & 0xffffffffffffffc0);
  puVar2 = (undefined8 *)va;
  if (va <= puVar3) {
    puVar2 = puVar3;
  }
  for (puVar6 = (undefined8 *)va; puVar6 < puVar3; puVar6 = puVar6 + 8) {
    DC_ZVA(puVar6);
  }
  puVar2 = (undefined8 *)(va + ((ulong)((long)puVar2 + (0x3f - va)) & 0xffffffffffffffc0));
LAB_060662c8:
  if (puVar2 != puVar1) {
    while (puVar2 + 2 <= puVar1) {
      *puVar2 = 0;
      puVar2[1] = 0;
      puVar2 = puVar2 + 2;
    }
    if (puVar1 != puVar2) {
      if (puVar2 + 1 <= puVar1) {
        *puVar2 = 0;
        puVar2 = puVar2 + 1;
      }
      if (puVar2 != puVar1) {
        if ((undefined8 *)((long)puVar2 + 4) <= puVar1) {
          *(undefined4 *)puVar2 = 0;
          puVar2 = (undefined8 *)((long)puVar2 + 4);
        }
        if ((undefined8 *)((long)puVar2 + 2) <= puVar1) {
          *(undefined2 *)puVar2 = 0;
          puVar2 = (undefined8 *)((long)puVar2 + 2);
        }
        if ((undefined8 *)((long)puVar2 + 1) <= puVar1) {
          *(undefined *)puVar2 = 0;
        }
      }
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066348
 * symbol: A53_MEMCMP_U8
 * prototype: bool A53_MEMCMP_U8(uint64_t va, uint64_t length, uint8_t val)
 * body addresses: 200
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::A53_MEMCMP_U8(uint64_t va,uint64_t length,uint8_t val)

{
  long *plVar1;
  long lVar2;
  long lVar3;
  uint uVar4;
  long *plVar5;
  long *plVar6;
  
  if (length == 0) {
    return true;
  }
  uVar4 = (uint)val << 0x10 | (uint)val << 0x18 | (uint)CONCAT11(val,val);
  plVar1 = (long *)(length + va);
  lVar2 = CONCAT44(uVar4,uVar4);
  while ((long *)(va + 0x10) <= plVar1) {
    lVar3 = *(long *)va;
    plVar6 = (long *)(va + 8);
    va = (uint64_t)(long *)(va + 0x10);
    if (lVar3 != lVar2 || *plVar6 != lVar2) {
      return false;
    }
  }
  plVar6 = (long *)va;
  if (((long *)(va + 8) <= plVar1) && (plVar6 = (long *)(va + 8), *(long *)va != lVar2)) {
    return false;
  }
  plVar5 = plVar6;
  if (((long *)((long)plVar6 + 4U) <= plVar1) &&
     (plVar5 = (long *)((long)plVar6 + 4U), *(uint *)plVar6 != uVar4)) {
    return false;
  }
  plVar6 = plVar5;
  if (((long *)((long)plVar5 + 2U) <= plVar1) &&
     (plVar6 = (long *)((long)plVar5 + 2U), (uint)CONCAT11(val,val) != (uint)*(ushort *)plVar5)) {
    return false;
  }
  if (plVar1 < (long *)((long)plVar6 + 1U)) {
    return true;
  }
  if (*(uint8_t *)plVar6 != val) {
    return false;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066410
 * symbol: A53_MEMSET
 * prototype: bool A53_MEMSET(uint64_t va, uint64_t length, uint8_t val)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::A53_MEMSET(uint64_t va,uint64_t length,uint8_t val)

{
  undefined8 *puVar1;
  undefined8 uVar2;
  uint uVar3;
  
  if (length != 0) {
    uVar3 = (uint)val << 0x10 | (uint)val << 0x18 | (uint)CONCAT11(val,val);
    puVar1 = (undefined8 *)(length + va);
    uVar2 = CONCAT44(uVar3,uVar3);
    while ((undefined8 *)(va + 0x10) <= puVar1) {
      *(undefined8 *)va = uVar2;
      *(undefined8 *)(va + 8) = uVar2;
      va = (uint64_t)(undefined8 *)(va + 0x10);
    }
    if ((undefined8 *)(va + 8) <= puVar1) {
      *(undefined8 *)va = uVar2;
      va = (uint64_t)(undefined8 *)(va + 8);
    }
    if ((undefined8 *)(va + 4) <= puVar1) {
      *(uint *)va = uVar3;
      va = (uint64_t)(undefined8 *)(va + 4);
    }
    if ((undefined8 *)(va + 2) <= puVar1) {
      *(ushort *)va = CONCAT11(val,val);
      va = (uint64_t)(undefined8 *)(va + 2);
    }
    if ((undefined8 *)(va + 1) <= puVar1) {
      *(uint8_t *)va = val;
    }
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060664a4
 * symbol: A53ControllerEmitBreadcrumb
 * prototype: void A53ControllerEmitBreadcrumb(A53ControllerBreadcrumbType eType, uint32_t numElems, uint64_t data0_b0_55, uint64_t * aData)
 * body addresses: 356
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void A53::A53ControllerEmitBreadcrumb
               (A53ControllerBreadcrumbType eType,uint32_t numElems,uint64_t data0_b0_55,
               uint64_t *aData)

{
  ulong *puVar1;
  ulong uVar2;
  uint uVar3;
  ulong uVar4;
  uint uVar5;
  uint uVar6;
  ulong *puVar7;
  uint uVar8;
  ulong *puVar9;
  uint uVar10;
  uint64_t *puVar11;
  
  if (((0xf < (numElems | eType)) || (data0_b0_55 >> 0x38 != 0)) ||
     ((numElems != 0 && (aData == (uint64_t *)0x0)))) {
    return;
  }
  uVar6 = (uint)_DAT_04426400;
  if (_DAT_04426400 >> 0x20 != 0xa53bcc01) {
    uVar6 = 0x17600000;
  }
  puVar7 = (ulong *)(&DAT_04426408 + ((uVar6 & 0x1ff) << 3));
  if ((uVar6 >> 9 & 1) == 0) {
    uVar8 = (uVar6 >> 0x14 & 0x1ff) + 1;
  }
  else {
    uVar8 = uVar6 >> 10 & 0x1ff;
  }
  if (uVar8 <= (uVar6 & 0x1ff) + numElems) {
    if ((uVar6 >> 9 & 1) != 0) goto LAB_060665fc;
    uVar8 = (uVar6 >> 0x14) - uVar6;
    uVar6 = uVar6 & 0xfffffc00 | 0x200;
    *puVar7 = (ulong)(uVar8 & 0xf | 0xf0);
    puVar7 = (ulong *)&DAT_04426408;
  }
  puVar1 = aData + (numElems & 0xfffffffe);
  puVar9 = aData;
  if (aData <= puVar1) {
    puVar9 = puVar1;
  }
  uVar2 = (long)puVar9 + (0xf - (long)aData);
  *puVar7 = (ulong)((eType & 0xf) << 4) | (ulong)numElems & 0xf | data0_b0_55 << 8;
  puVar9 = puVar7 + 1;
  for (puVar11 = aData; puVar11 < puVar1; puVar11 = puVar11 + 2) {
    uVar4 = puVar11[1];
    *puVar9 = *puVar11;
    puVar9[1] = uVar4;
    puVar9 = puVar9 + 2;
  }
  if (aData + (uVar2 >> 3 & 0x1ffffffffffffffe) < aData + numElems) {
    *(uint64_t *)((long)puVar7 + (uVar2 & 0xfffffffffffffff0) + 8) =
         aData[uVar2 >> 3 & 0x1ffffffffffffffe];
  }
  uVar8 = numElems + (uVar6 & 0x1ff) + 1;
  uVar5 = uVar6 >> 0x14 & 0x1ff;
  uVar10 = 0xfffffc00;
  if (uVar8 <= uVar5) {
    uVar10 = 0xfffffe00;
  }
  uVar3 = 0x200;
  if (uVar8 <= uVar5) {
    uVar3 = uVar8 & 0x1ff;
  }
  uVar6 = uVar10 & uVar6 | uVar3;
LAB_060665fc:
  _DAT_04426400 = (ulong)uVar6 | 0xa53bcc0100000000;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066608
 * symbol: A53ControllerReadBreadcrumb
 * prototype: bool A53ControllerReadBreadcrumb(A53ControllerBreadcrumb * breadcrumb)
 * body addresses: 188
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

bool A53::A53ControllerReadBreadcrumb(A53ControllerBreadcrumb *breadcrumb)

{
  uint uVar1;
  uint64_t *puVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  uint64_t uVar6;
  uint64_t *puVar7;
  uint64_t *puVar8;
  
  if ((_DAT_04426400 >> 0x20 == 0xa53bcc01) &&
     ((uVar4 = (uint)_DAT_04426400, (uVar4 >> 9 & 1) != 0 ||
      ((uVar4 >> 10 & 0x1ff) < (uVar4 & 0x1ff))))) {
    uVar5 = _DAT_04426400 >> 7 & 0xff8;
    uVar6 = *(uint64_t *)(&DAT_04426408 + uVar5);
    (breadcrumb->field_0).asU64[0] = uVar6;
    if ((uVar6 & 0xf) != 0) {
      puVar7 = (breadcrumb->field_0).asU64 + 1;
      puVar2 = puVar7 + (uVar6 & 0xf);
      puVar8 = (uint64_t *)(&DAT_04426410 + uVar5);
      for (; puVar7 < puVar2; puVar7 = puVar7 + 1) {
        *puVar7 = *puVar8;
        puVar8 = puVar8 + 1;
      }
      uVar6 = (breadcrumb->field_0).asU64[0];
    }
    uVar1 = (uVar4 >> 10 & 0x1ff) + ((uint)uVar6 & 0xf) + 1;
    uVar3 = uVar4 & 0xfff801ff;
    if (uVar1 <= (uVar4 >> 0x14 & 0x1ff)) {
      uVar3 = uVar4 & 0xfff80000 | uVar4 & 0x3ff | (uVar1 & 0x1ff) << 10;
    }
    _DAT_04426400 = (ulong)uVar3 | 0xa53bcc0100000000;
    return true;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060666c4
 * symbol: A53ControllerPeekBreadcrumbHeader
 * prototype: bool A53ControllerPeekBreadcrumbHeader(A53ControllerBreadcrumbHeader * header, uint32_t offsetFromRpos)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

bool A53::A53ControllerPeekBreadcrumbHeader
               (A53ControllerBreadcrumbHeader *header,uint32_t offsetFromRpos)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  
  if (_DAT_04426400 >> 0x20 == 0xa53bcc01) {
    uVar2 = (uint)_DAT_04426400;
    if ((uVar2 >> 9 & 1) == 0) {
      uVar3 = uVar2 >> 10 & 0x1ff;
      if ((uVar2 & 0x1ff) <= uVar3) {
        return false;
      }
      iVar1 = 0;
    }
    else {
      iVar1 = (uVar2 >> 0x14 & 0x1ff) + 1;
      uVar3 = uVar2 >> 10 & 0x1ff;
    }
    if (offsetFromRpos < ((uVar2 & 0x1ff) - uVar3) + iVar1) {
      uVar2 = uVar2 >> 0x14 & 0x1ff;
      iVar1 = 0;
      if (uVar2 < uVar3 + offsetFromRpos) {
        iVar1 = uVar2 + 1;
      }
      header->field_0 =
           *(anon_union_8_2_653be918_for_A53ControllerBreadcrumbHeader_0 *)
            (&DAT_04426408 + (ulong)((uVar3 + offsetFromRpos) - iVar1) * 8);
      return true;
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066758
 * symbol: A53ControllerPeekBreadcrumb
 * prototype: bool A53ControllerPeekBreadcrumb(A53ControllerBreadcrumb * breadcrumb, uint32_t offsetFromRpos)
 * body addresses: 184
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

bool A53::A53ControllerPeekBreadcrumb(A53ControllerBreadcrumb *breadcrumb,uint32_t offsetFromRpos)

{
  uint64_t *puVar1;
  ulong uVar2;
  int iVar3;
  uint64_t *puVar4;
  ulong uVar5;
  uint64_t *puVar6;
  uint uVar7;
  uint uVar8;
  
  if (_DAT_04426400 >> 0x20 == 0xa53bcc01) {
    uVar7 = (uint)_DAT_04426400;
    if ((uVar7 >> 9 & 1) == 0) {
      uVar8 = uVar7 >> 10 & 0x1ff;
      if ((uVar7 & 0x1ff) <= uVar8) {
        return false;
      }
      iVar3 = 0;
    }
    else {
      iVar3 = (uVar7 >> 0x14 & 0x1ff) + 1;
      uVar8 = uVar7 >> 10 & 0x1ff;
    }
    if (offsetFromRpos < ((uVar7 & 0x1ff) - uVar8) + iVar3) {
      uVar7 = uVar7 >> 0x14 & 0x1ff;
      iVar3 = 0;
      if (uVar7 < uVar8 + offsetFromRpos) {
        iVar3 = uVar7 + 1;
      }
      uVar5 = *(ulong *)(&DAT_04426408 + (ulong)((uVar8 + offsetFromRpos) - iVar3) * 8);
      uVar2 = uVar5 & 0xf;
      (breadcrumb->field_0).asU64[0] = uVar5;
      if (uVar2 != 0) {
        puVar6 = (breadcrumb->field_0).asU64 + 1;
        puVar1 = puVar6 + uVar2;
        puVar4 = (uint64_t *)(&DAT_04426408 + (ulong)((uVar8 + offsetFromRpos) - iVar3) * 8);
        for (; puVar6 < puVar1; puVar6 = puVar6 + 1) {
          *puVar6 = *puVar4;
          puVar4 = puVar4 + 1;
        }
      }
      return true;
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066810
 * symbol: A53ControllerGetNumBreadcrumbElemsInUse
 * prototype: uint32_t A53ControllerGetNumBreadcrumbElemsInUse(void)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

uint32_t A53::A53ControllerGetNumBreadcrumbElemsInUse(void)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  
  if (_DAT_04426400 >> 0x20 != 0xa53bcc01) {
    return 0;
  }
  uVar3 = (uint)_DAT_04426400;
  if ((uVar3 >> 9 & 1) == 0) {
    iVar1 = 0;
    uVar2 = uVar3 >> 10 & 0x1ff;
    if ((uVar3 & 0x1ff) <= uVar2) {
      return 0;
    }
  }
  else {
    iVar1 = (uVar3 >> 0x14 & 0x1ff) + 1;
    uVar2 = uVar3 >> 10 & 0x1ff;
  }
  return ((uVar3 & 0x1ff) - uVar2) + iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066870
 * symbol: A53ControllerGetNumBreadcrumbElemsAvailable
 * prototype: uint32_t A53ControllerGetNumBreadcrumbElemsAvailable(void)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

uint32_t A53::A53ControllerGetNumBreadcrumbElemsAvailable(void)

{
  uint uVar1;
  uint uVar2;
  
  if (_DAT_04426400 >> 0x20 != 0xa53bcc01) {
    return 0x177;
  }
  uVar1 = (uint)_DAT_04426400;
  if ((uVar1 >> 9 & 1) == 0) {
    uVar2 = uVar1 >> 10 & 0x1ff;
    if ((uVar1 & 0x1ff) <= uVar2) {
      uVar1 = uVar1 >> 0x14 & 0x1ff;
      goto LAB_060668dc;
    }
  }
  else {
    uVar2 = uVar1 >> 10 & 0x1ff;
  }
  uVar1 = (uVar2 - (uVar1 & 0x1ff)) + (uVar1 >> 0x14 & 0x1ff) +
          ((uVar1 >> 0x14 ^ 0xffffffff | 0xfffffe00) & (int)(uVar1 << 0x16) >> 0x1f);
LAB_060668dc:
  return uVar1 + 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060668e4
 * symbol: A53ControllerGetNumBreadcrumbs
 * prototype: uint32_t A53ControllerGetNumBreadcrumbs(void)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

uint32_t A53::A53ControllerGetNumBreadcrumbs(void)

{
  ulong uVar1;
  long lVar2;
  uint uVar3;
  uint32_t uVar4;
  uint uVar5;
  ulong uVar6;
  ulong uVar7;
  
  if ((_DAT_04426400 >> 0x20 == 0xa53bcc01) &&
     ((uVar5 = (uint)_DAT_04426400, (uVar5 >> 9 & 1) != 0 ||
      ((uVar5 >> 10 & 0x1ff) < (uVar5 & 0x1ff))))) {
    uVar4 = 0;
    uVar7 = _DAT_04426400 >> 10 & 0x1ff;
    uVar6 = _DAT_04426400 >> 0x14 & 0x1ff;
    uVar5 = uVar5 >> 9 & 1;
    do {
      lVar2 = uVar7 + (*(ulong *)(&DAT_04426408 + uVar7 * 8) & 0xf);
      uVar1 = lVar2 + 1;
      if ((~(uint)*(ulong *)(&DAT_04426408 + uVar7 * 8) & 0xf0) != 0) {
        uVar4 = uVar4 + 1;
      }
      uVar3 = 0;
      if (uVar1 <= uVar6) {
        uVar3 = uVar5;
      }
      uVar7 = 0;
      if (uVar1 <= uVar6) {
        uVar7 = lVar2 + 1;
      }
      uVar5 = uVar3;
    } while ((uVar3 != 0) || (uVar7 < (_DAT_04426400 & 0x1ff)));
    return uVar4;
  }
  return 0;
}


