/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/../controller/a53_intrinsic_wrapper.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006654
 * symbol: CountBits64
 * prototype: uint64_t CountBits64(uint64_t value)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::CountBits64(uint64_t value)

{
  ulong uVar1;
  
  uVar1 = (value >> 1 & 0x5555555555555555) + (value & 0x5555555555555555);
  uVar1 = (uVar1 >> 2 & 0x3333333333333333) + (uVar1 & 0x3333333333333333);
  uVar1 = (uVar1 >> 4 & 0x707070707070707) + (uVar1 & 0x707070707070707);
  uVar1 = (uVar1 >> 8 & 0xf000f000f000f) + (uVar1 & 0xf000f000f000f);
  uVar1 = (uVar1 >> 0x10 & 0x1f0000001f) + (uVar1 & 0x1f0000001f);
  return (uVar1 & 0x3f) + (uVar1 >> 0x20);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600f840
 * symbol: CountBits64
 * prototype: uint64_t CountBits64(uint64_t value)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::CountBits64(uint64_t value)

{
  ulong uVar1;
  
  uVar1 = (value >> 1 & 0x5555555555555555) + (value & 0x5555555555555555);
  uVar1 = (uVar1 >> 2 & 0x3333333333333333) + (uVar1 & 0x3333333333333333);
  uVar1 = (uVar1 >> 4 & 0x707070707070707) + (uVar1 & 0x707070707070707);
  uVar1 = (uVar1 >> 8 & 0xf000f000f000f) + (uVar1 & 0xf000f000f000f);
  uVar1 = (uVar1 >> 0x10 & 0x1f0000001f) + (uVar1 & 0x1f0000001f);
  return (uVar1 & 0x3f) + (uVar1 >> 0x20);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06046cac
 * symbol: CountBits32
 * prototype: uint32_t CountBits32(uint32_t value)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::CountBits32(uint32_t value)

{
  uint uVar1;
  
  uVar1 = (value >> 1 & 0x55555555) + (value & 0x55555555);
  uVar1 = (uVar1 >> 2 & 0x33333333) + (uVar1 & 0x33333333);
  uVar1 = (uVar1 >> 4 & 0x7070707) + (uVar1 & 0x7070707);
  uVar1 = (uVar1 >> 8 & 0xf000f) + (uVar1 & 0xf000f);
  return (uVar1 & 0x1f) + (uVar1 >> 0x10);
}


