/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/a53_bootconfiguration.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060022c8
 * symbol: A53Controller_BootConfiguration_KernelShared_getRingSizes
 * prototype: void A53Controller_BootConfiguration_KernelShared_getRingSizes(uint64_t vaSramBootConfiguration_KernelShared, uint8_t * out_numElementsLog2InterruptContextRing, uint32_t kNumA53ControllerInputCommandRings, uint8_t * out_aNumElementsLog2CommandRing)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::A53Controller_BootConfiguration_KernelShared_getRingSizes
               (uint64_t vaSramBootConfiguration_KernelShared,
               uint8_t *out_numElementsLog2InterruptContextRing,
               uint32_t kNumA53ControllerInputCommandRings,uint8_t *out_aNumElementsLog2CommandRing)

{
  uint uVar1;
  uint8_t uVar2;
  ulong uVar3;
  ulong uVar4;
  ulong uVar5;
  ulong uVar6;
  
  uVar5 = *(ulong *)(vaSramBootConfiguration_KernelShared + 0x18);
  uVar4 = 0;
  uVar1 = kNumA53ControllerInputCommandRings;
  if (8 < kNumA53ControllerInputCommandRings) {
    uVar1 = 9;
  }
  uVar3 = (ulong)uVar1;
  uVar6 = *(ulong *)(vaSramBootConfiguration_KernelShared + 0x10) >> 0x1c;
  *out_numElementsLog2InterruptContextRing =
       ((byte)(*(ulong *)(vaSramBootConfiguration_KernelShared + 0x10) >> 0x18) & 0xf) + 1;
  for (; uVar4 < uVar3; uVar4 = uVar4 + 1) {
    uVar2 = '\0';
    if ((uVar6 & 0xf) != 0) {
      uVar2 = ((byte)uVar6 & 0xf) + 1;
    }
    uVar6 = uVar6 >> 4;
    out_aNumElementsLog2CommandRing[uVar4] = uVar2;
  }
  uVar5 = uVar5 & 0xfffffffffffff;
  for (; uVar3 < kNumA53ControllerInputCommandRings; uVar3 = uVar3 + 1) {
    uVar2 = '\0';
    if ((uVar5 & 0xf) != 0) {
      uVar2 = ((byte)uVar5 & 0xf) + 1;
    }
    uVar5 = uVar5 >> 4;
    out_aNumElementsLog2CommandRing[uVar3] = uVar2;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06002340
 * symbol: A53Controller_BootConfiguration_KernelShared_getPaDebugRingSizes
 * prototype: void A53Controller_BootConfiguration_KernelShared_getPaDebugRingSizes(uint64_t vaSramBootConfiguration_KernelShared, uint32_t kNumA53ControllerPaDebugOutputRings, uint8_t * out_aNumElementsLog2PaDebugOutputRing)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::A53Controller_BootConfiguration_KernelShared_getPaDebugRingSizes
               (uint64_t vaSramBootConfiguration_KernelShared,
               uint32_t kNumA53ControllerPaDebugOutputRings,
               uint8_t *out_aNumElementsLog2PaDebugOutputRing)

{
  uint8_t uVar1;
  ulong uVar2;
  ulong uVar3;
  
  uVar3 = *(ulong *)(vaSramBootConfiguration_KernelShared + 0x18) >> 0x36;
  for (uVar2 = (ulong)kNumA53ControllerPaDebugOutputRings; uVar2 != 0; uVar2 = uVar2 - 1) {
    uVar1 = '\0';
    if ((uVar3 & 0x1f) != 0) {
      uVar1 = ((byte)uVar3 & 0x1f) + 1;
    }
    uVar3 = uVar3 >> 5;
    *out_aNumElementsLog2PaDebugOutputRing = uVar1;
    out_aNumElementsLog2PaDebugOutputRing = out_aNumElementsLog2PaDebugOutputRing + 1;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605eb78
 * symbol: A53Controller_BootConfiguration_KernelShared_getPaSystemMmioSdma
 * prototype: void A53Controller_BootConfiguration_KernelShared_getPaSystemMmioSdma(uint64_t vaSramBootConfiguration_KernelShared, uint64_t * out_paSystemMmioSdma)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::A53Controller_BootConfiguration_KernelShared_getPaSystemMmioSdma
               (uint64_t vaSramBootConfiguration_KernelShared,uint64_t *out_paSystemMmioSdma)

{
  long lVar1;
  bool bVar2;
  long lVar3;
  ulong uVar4;
  
  lVar3 = 0xc;
  uVar4 = 0xfffff000;
  bVar2 = (*(ulong *)(vaSramBootConfiguration_KernelShared + 0x28) & 0x800000) != 0;
  if (bVar2) {
    lVar3 = 2;
    uVar4 = 0x1fffffc;
  }
  lVar1 = 0x4000000;
  if (bVar2) {
    lVar1 = 0x1000000;
  }
  *out_paSystemMmioSdma =
       (*(ulong *)(vaSramBootConfiguration_KernelShared + 0x28) << lVar3 & uVar4) + lVar1;
  return;
}


