/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/a53_controller_rings.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06001a60
 * symbol: peekCommandDataElements
 * prototype: bool peekCommandDataElements(ControllerRings * rings, uint32_t iCommandRing, uint32_t cmdDataElemIdx, uint32_t numCmdElems, uint32_t * aElem)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::peekCommandDataElements
               (ControllerRings *rings,uint32_t iCommandRing,uint32_t cmdDataElemIdx,
               uint32_t numCmdElems,uint32_t *aElem)

{
  uint uVar1;
  bool bVar2;
  
  uVar1 = (rings->m_static_config).field_0.asU32 >> 6 & 0x1f;
  if (iCommandRing < uVar1) {
    bVar2 = InputRing::peekElements<unsigned_int>
                      (rings->m_paInputRing + iCommandRing,numCmdElems,aElem,cmdDataElemIdx + 1);
    return bVar2;
  }
  bVar2 = InputIndirectBuffer::peekElements<unsigned_int>
                    (rings->m_paInputIndirectBuffer + (iCommandRing - uVar1),numCmdElems,aElem,
                     cmdDataElemIdx + 1);
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06005094
 * symbol: canPushInterrupt
 * prototype: bool canPushInterrupt(ControllerRings * rings)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::canPushInterrupt(ControllerRings *rings)

{
  if (((rings->m_pRingsState->field_0).asU64[3] >> 0x34 & 1) == 0) {
    return false;
  }
  return 1 << (ulong)((rings->m_paOutputRing->field_0).field_0.m_numCacheElemsLog2 & 0x1f) !=
         (uint)(rings->m_paOutputRing->field_0).field_0.m_countDmaNotComplete;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006108
 * symbol: peekCommand
 * prototype: PeekCommandResult peekCommand(ControllerRings * rings, uint32_t iCommandRing, A53ControllerCommandHeader * out_cmdHeader)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

PeekCommandResult
A53::peekCommand(ControllerRings *rings,uint32_t iCommandRing,
                A53ControllerCommandHeader *out_cmdHeader)

{
  PeekCommandResult PVar1;
  
  if (iCommandRing < ((rings->m_static_config).field_0.asU32 >> 6 & 0x1f)) {
    PVar1 = peekCommandInputRing(rings,iCommandRing,out_cmdHeader);
    return PVar1;
  }
  PVar1 = peekCommandInputRingWithIndirectBuffer(rings,iCommandRing,out_cmdHeader);
  return PVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060061fc
 * symbol: popCommand
 * prototype: void popCommand(ControllerRings * rings, uint32_t iCommandRing, uint32_t numCmdElems)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::popCommand(ControllerRings *rings,uint32_t iCommandRing,uint32_t numCmdElems)

{
  if (iCommandRing < ((rings->m_static_config).field_0.asU32 >> 6 & 0x1f)) {
    popCommandInputRing(rings,iCommandRing,numCmdElems);
    return;
  }
  popCommandInputRingWithIndirectBuffer(rings,iCommandRing,numCmdElems);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060066f0
 * symbol: peekCommandInputRing
 * prototype: PeekCommandResult peekCommandInputRing(ControllerRings * rings, uint32_t iCommandRing, A53ControllerCommandHeader * out_cmdHeader)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

PeekCommandResult
A53::peekCommandInputRing
          (ControllerRings *rings,uint32_t iCommandRing,A53ControllerCommandHeader *out_cmdHeader)

{
  PeekCommandResult PVar1;
  
  PVar1 = peekCommandInputRing
                    (&rings->m_static_config,rings->m_paInputRing,iCommandRing,out_cmdHeader);
  return PVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006708
 * symbol: peekCommandInputRing
 * prototype: PeekCommandResult peekCommandInputRing(ControllerStaticConfiguration * static_config, InputRing * aInputRing, uint32_t iCommandRing, A53ControllerCommandHeader * out_cmdHeader)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

PeekCommandResult
A53::peekCommandInputRing
          (ControllerStaticConfiguration *static_config,InputRing *aInputRing,uint32_t iCommandRing,
          A53ControllerCommandHeader *out_cmdHeader)

{
  bool bVar1;
  PeekCommandResult PVar2;
  
  bVar1 = InputRing::peekElement<unsigned_int>(aInputRing + iCommandRing,(uint *)out_cmdHeader,0);
  PVar2 = kPeekCommandResultNoCommand;
  if (bVar1) {
    PVar2 = (PeekCommandResult)
            (((out_cmdHeader->field_0).asU32 >> 8 & 0xf) <
            (uint)aInputRing[iCommandRing].field_0.field_0.m_countDmaComplete);
  }
  return PVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060067a8
 * symbol: popCommandInputRingWithIndirectBuffer
 * prototype: void popCommandInputRingWithIndirectBuffer(ControllerRings * rings, uint32_t iCommandRing, uint32_t numCmdElems)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::popCommandInputRingWithIndirectBuffer
               (ControllerRings *rings,uint32_t iCommandRing,uint32_t numCmdElems)

{
  popCommandInputRingWithIndirectBuffer
            (&rings->m_static_config,rings->m_paInputIndirectBuffer,rings->m_paInputRingHeadIb,
             rings->m_pRingsState,iCommandRing,numCmdElems);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060067c8
 * symbol: popCommandInputRing
 * prototype: void popCommandInputRing(ControllerRings * rings, uint32_t iCommandRing, uint32_t numCmdElems)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::popCommandInputRing(ControllerRings *rings,uint32_t iCommandRing,uint32_t numCmdElems)

{
  popCommandInputRing(&rings->m_static_config,rings->m_paInputRing,rings->m_pRingsState,iCommandRing
                      ,numCmdElems);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060067e0
 * symbol: popCommandInputRingWithIndirectBuffer
 * prototype: void popCommandInputRingWithIndirectBuffer(ControllerStaticConfiguration * static_config, InputIndirectBuffer * aInputIndirectBuffer, A53Controller_InputRingWithIndirectBufferHead * aInputRingHeadIb, ControllerRingsState * rings_state, uint32_t iCommandRing, uint32_t numCmdElems)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::popCommandInputRingWithIndirectBuffer
               (ControllerStaticConfiguration *static_config,
               InputIndirectBuffer *aInputIndirectBuffer,
               A53Controller_InputRingWithIndirectBufferHead *aInputRingHeadIb,
               ControllerRingsState *rings_state,uint32_t iCommandRing,uint32_t numCmdElems)

{
  uint uVar1;
  
  uVar1 = iCommandRing - ((static_config->field_0).asU32 >> 6 & 0x1f);
  ibFlatCachePopCommand
            (aInputIndirectBuffer + uVar1,aInputRingHeadIb + uVar1,numCmdElems,(uint8_t *)0x0);
  if ((*(byte *)((long)&aInputRingHeadIb
                        [iCommandRing - ((static_config->field_0).asU32 >> 6 & 0x1f)].field_0 + 3)
       >> 5 & 1) == 0) {
    (rings_state->field_0).asU64[3] =
         (rings_state->field_0).asU64[3] & 0xffffffffffc00000 |
         (ulong)((uint)(1L << ((ulong)iCommandRing & 0x3f)) | (uint)(rings_state->field_0).asU64[3])
         & 0x3fffff;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06041c60
 * symbol: inputRingHaltByError
 * prototype: void inputRingHaltByError(ControllerRings * rings, uint32_t iCommandRing)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::inputRingHaltByError(ControllerRings *rings,uint32_t iCommandRing)

{
  uint uVar1;
  uint uVar2;
  
  inputRingHalt(rings,iCommandRing);
  uVar1 = (rings->m_static_config).field_0.asU32 >> 6 & 0x1f;
  if (((uVar1 <= iCommandRing) &&
      (uVar2 = (uint)(rings->m_pRingsState->field_0).asU64[0], (uVar2 >> 0x1e & 1) != 0)) &&
     (uVar1 = (uVar2 & 0x3fffff) >> (ulong)uVar1, uVar1 != 0)) {
    internal_indirectBufferHaltAllRunningAppRings(rings,(long)(int)uVar1);
    return;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06042f20
 * symbol: interruptContextRingWorkWasAdded
 * prototype: void interruptContextRingWorkWasAdded(A53Controller_InterruptContextRingTail * pInterruptContextRingTail, ControllerRingsState * pRingsState)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::interruptContextRingWorkWasAdded
               (A53Controller_InterruptContextRingTail *pInterruptContextRingTail,
               ControllerRingsState *pRingsState)

{
  ulong uVar1;
  
  if (((uint)(pInterruptContextRingTail->field_0).asU64[0] >> 0x1e & 1) != 0) {
    (pInterruptContextRingTail->field_0).asU64[0] =
         (pInterruptContextRingTail->field_0).asU64[0] & 0xffffffffbfffffff;
    uVar1 = (pRingsState->field_0).asU64[3];
    (pRingsState->field_0).asU64[3] =
         uVar1 & 0xffff000000000000 |
         uVar1 & 0xfffffffffff | (ulong)((uint)(uVar1 >> 0x2c) & 0xe | 1) << 0x2c;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605b370
 * symbol: indirectBufferHaltByErrorIfRunning
 * prototype: void indirectBufferHaltByErrorIfRunning(ControllerRings * rings, uint32_t iIb)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::indirectBufferHaltByErrorIfRunning(ControllerRings *rings,uint32_t iIb)

{
  uint uVar1;
  
  uVar1 = (uint)(rings->m_pRingsState->field_0).asU64[0];
  if ((uVar1 & (uint)(1L << ((ulong)(((rings->m_static_config).field_0.asU32 >> 6 & 0x1f) + iIb) &
                            0x3f)) & 0x3fffff) != 0) {
    indirectBufferHalt(rings,iIb);
    uVar1 = (uint)(rings->m_pRingsState->field_0).asU64[0];
  }
  if (((uVar1 >> 0x1e & 1) != 0) &&
     (uVar1 = (uVar1 & 0x3fffff) >> (ulong)((rings->m_static_config).field_0.asU32 >> 6 & 0x1f),
     uVar1 != 0)) {
    internal_indirectBufferHaltAllRunningAppRings(rings,(long)(int)uVar1);
    return;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605b3f0
 * symbol: canPushInterrupt
 * prototype: bool canPushInterrupt(ControllerRings * rings)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::canPushInterrupt(ControllerRings *rings)

{
  if (((rings->m_pRingsState->field_0).asU64[3] >> 0x34 & 1) == 0) {
    return false;
  }
  return 1 << (ulong)((rings->m_paOutputRing->field_0).field_0.m_numCacheElemsLog2 & 0x1f) !=
         (uint)(rings->m_paOutputRing->field_0).field_0.m_countDmaNotComplete;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605b424
 * symbol: interruptContextRingWorkWasAdded
 * prototype: void interruptContextRingWorkWasAdded(ControllerRings * rings)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::interruptContextRingWorkWasAdded(ControllerRings *rings)

{
  ulong uVar1;
  A53Controller_InterruptContextRingTail AVar2;
  ControllerRingsState *pCVar3;
  
  AVar2.field_0 =
       (anon_union_8_3_e9e78e08_for_A53Controller_InterruptContextRingTail_0)
       (rings->m_pInterruptContextRingTail->field_0).asU64[0];
  if ((AVar2.field_0._0_4_ >> 0x1e & 1) != 0) {
    pCVar3 = rings->m_pRingsState;
    (rings->m_pInterruptContextRingTail->field_0).asU64[0] =
         (ulong)AVar2.field_0 & 0xffffffffbfffffff;
    uVar1 = (pCVar3->field_0).asU64[3];
    (pCVar3->field_0).asU64[3] =
         uVar1 & 0xffff000000000000 |
         uVar1 & 0xfffffffffff | (ulong)((uint)(uVar1 >> 0x2c) & 0xe | 1) << 0x2c;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605b720
 * symbol: pushPspError
 * prototype: bool pushPspError(ControllerRings * rings, PushPspErrorBlocking eBlocking, A53Controller_PSP_Error * error)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::pushPspError(ControllerRings *rings,PushPspErrorBlocking eBlocking,
                      A53Controller_PSP_Error *error)

{
  undefined *vaSramA53Controller_PSP_MessageRing;
  uint uVar1;
  bool bVar2;
  
  uVar1 = (rings->m_static_config).field_0.asU32;
  vaSramA53Controller_PSP_MessageRing = &DAT_04040000;
  if ((uVar1 >> 0x1a & 1) != 0) {
    vaSramA53Controller_PSP_MessageRing = &DAT_04227000;
  }
  bVar2 = pspMessageRing_pushError
                    (uVar1 >> 0x16 & 3,uVar1 >> 0x1a & 1,
                     (uint64_t)vaSramA53Controller_PSP_MessageRing,kPushPspErrorBlocking,
                     (A53Controller_PSP_Error *)(ulong)eBlocking);
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605f350
 * symbol: setExecuteSopCommandState
 * prototype: bool setExecuteSopCommandState(ControllerRings * rings, uint32_t iCommandRing, uint32_t state_b0_7)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::setExecuteSopCommandState
               (ControllerRings *rings,uint32_t iCommandRing,uint32_t state_b0_7)

{
  uint uVar1;
  ulong uVar2;
  
  uVar1 = (rings->m_static_config).field_0.asU32;
  if (iCommandRing < (uVar1 >> 6 & 0x1f) + (uVar1 >> 0xb & 0x1f)) {
    uVar2 = rings->m_paCommandRingErrorState[iCommandRing].field_0.asU64[0];
    rings->m_paCommandRingErrorState[iCommandRing].field_0.asU64[0] =
         uVar2 & 0xff00000000000000 | uVar2 & 0xffffffffffff | (ulong)(state_b0_7 & 0xff) << 0x30;
  }
  return SUB81(rings,0);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605fb10
 * symbol: canPushInterrupt
 * prototype: bool canPushInterrupt(ControllerRings * rings)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::canPushInterrupt(ControllerRings *rings)

{
  if (((rings->m_pRingsState->field_0).asU64[3] >> 0x34 & 1) == 0) {
    return false;
  }
  return 1 << (ulong)((rings->m_paOutputRing->field_0).field_0.m_numCacheElemsLog2 & 0x1f) !=
         (uint)(rings->m_paOutputRing->field_0).field_0.m_countDmaNotComplete;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605fb84
 * symbol: interruptContextRingWorkWasAdded
 * prototype: void interruptContextRingWorkWasAdded(ControllerRings * rings)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::interruptContextRingWorkWasAdded(ControllerRings *rings)

{
  ulong uVar1;
  A53Controller_InterruptContextRingTail AVar2;
  ControllerRingsState *pCVar3;
  
  AVar2.field_0 =
       (anon_union_8_3_e9e78e08_for_A53Controller_InterruptContextRingTail_0)
       (rings->m_pInterruptContextRingTail->field_0).asU64[0];
  if ((AVar2.field_0._0_4_ >> 0x1e & 1) != 0) {
    pCVar3 = rings->m_pRingsState;
    (rings->m_pInterruptContextRingTail->field_0).asU64[0] =
         (ulong)AVar2.field_0 & 0xffffffffbfffffff;
    uVar1 = (pCVar3->field_0).asU64[3];
    (pCVar3->field_0).asU64[3] =
         uVar1 & 0xffff000000000000 |
         uVar1 & 0xfffffffffff | (ulong)((uint)(uVar1 >> 0x2c) & 0xe | 1) << 0x2c;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060618e4
 * symbol: pushInterruptCommandError
 * prototype: bool pushInterruptCommandError(ControllerRings * rings, uint32_t iRing, uint16_t ringLocationError, uint64_t vaIndirectBufferBaseError, uint32_t numBufferElemsMinus1Error, uint32_t ibLocationError, uint16_t ibCommandIdError, uint32_t pid, uint32_t opCode, ErrorCodeType eErrorCodeType, uint8_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 196
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::pushInterruptCommandError
               (ControllerRings *rings,uint32_t iRing,uint16_t ringLocationError,
               uint64_t vaIndirectBufferBaseError,uint32_t numBufferElemsMinus1Error,
               uint32_t ibLocationError,uint16_t ibCommandIdError,uint32_t pid,uint32_t opCode,
               ErrorCodeType eErrorCodeType,uint8_t eErrorCode,uint64_t addressError,
               uint16_t pasidError)

{
  bool bVar1;
  
  bVar1 = canPushInterrupt(rings);
  if (bVar1) {
    interruptContextRing_pushCommandError
              (rings->m_paOutputRing,iRing,ringLocationError,vaIndirectBufferBaseError,
               numBufferElemsMinus1Error,ibLocationError,ibCommandIdError,pid,opCode,eErrorCodeType,
               (uint)eErrorCode,addressError,pasidError);
    interruptContextRingWorkWasAdded(rings);
  }
  return bVar1;
}


