/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_input_indirect_buffer.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060655fc
 * symbol: issueFetch
 * prototype: IssueFetchReturn issueFetch(InputIndirectBuffer * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_read, uint16_t pasid, uint32_t maxElemsToFetch)
 * body addresses: 356
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueFetchReturn issueFetch(InputIndirectBuffer * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_read, uint16_t pasid,
   uint32_t maxElemsToFetch) */

IssueFetchReturn __thiscall
A53::InputIndirectBuffer::issueFetch
          (InputIndirectBuffer *this,A53_AddressTranslator *addressTranslator,
          PtdmaVqSubmitState *submit_read,uint16_t pasid,uint32_t maxElemsToFetch)

{
  uint64_t paSrc;
  uint uVar1;
  int iVar2;
  uint32_t uVar3;
  byte bVar4;
  uint16_t uVar5;
  uint16_t uVar6;
  uint uVar7;
  uint uVar8;
  uint32_t uVar9;
  DmaWaitOnCompletion in_w6;
  uint uVar10;
  ulong uVar11;
  ulong uVar12;
  
  uVar7 = (this->field_0).field_0.m_numBufferElems - (this->field_0).field_0.m_head;
  if (((uVar7 == 0) || ((this->field_0).field_0.m_countPtdmaCommand == 6)) ||
     (uVar8 = getNumCacheElemsAvailableForFetch(this,kDisallowWrapInSramCache), uVar8 == 0)) {
    uVar12 = 0;
    uVar11 = 0;
  }
  else {
    if (maxElemsToFetch <= uVar7) {
      uVar7 = maxElemsToFetch;
    }
    bVar4 = (this->field_0).field_0.m_sizeofElemLog2;
    uVar10 = (uint)(this->field_0).field_0.m_numCacheElemsMinus1;
    uVar1 = (uint)(this->field_0).field_0.m_countDmaIssued +
            (uint)(this->field_0).field_0.m_headCache & uVar10;
    if (uVar7 <= uVar8) {
      uVar8 = uVar7;
    }
    uVar7 = (uVar10 + 1) - uVar1;
    if (uVar8 <= uVar7) {
      uVar7 = uVar8;
    }
    paSrc = (this->field_0).field_0.m_paBuffer +
            (ulong)((this->field_0).field_0.m_head << (ulong)(bVar4 & 0x1f));
    uVar10 = 0x100 >> (ulong)(bVar4 & 0x1f);
    uVar11 = (this->field_0).field_0.m_vaSramCache + (ulong)(uVar1 << (ulong)(bVar4 & 0x1f));
    uVar8 = 0xffffffff;
    if (uVar10 < uVar7) {
      uVar8 = -uVar10;
    }
    uVar8 = uVar8 & uVar7;
    uVar12 = (ulong)uVar8;
    uVar7 = uVar8 << (ulong)(bVar4 & 0x1f);
    uVar9 = ptdmaPutCommandCopy(submit_read,uVar7,paSrc,uVar11 & 0xfffff,pasid,
                                (uint)((((uint)paSrc | (uint)uVar11) & 7) == 0 &&
                                      (uVar7 < 0x101 && (uVar7 & 7) == 0)),in_w6);
    uVar7 = (uint)(this->field_0).field_0.m_countPtdmaCommand +
            (uint)(this->field_0).field_0.m_headPtdmaCommand;
    iVar2 = 0;
    if (5 < uVar7) {
      iVar2 = 6;
    }
    uVar7 = uVar7 - iVar2;
    uVar5 = (this->field_0).field_0.m_countDmaIssued;
    *(short *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x26) = (short)uVar8;
    uVar6 = (this->field_0).field_0.m_countPtdmaCommand;
    uVar3 = (this->field_0).field_0.m_head;
    (this->field_0).field_0.m_countDmaIssued = (short)uVar8 + uVar5;
    *(short *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x24) = (short)(uVar9 >> 5);
    uVar11 = (ulong)(uVar9 >> 5) << 0x20;
    (this->field_0).field_0.m_countPtdmaCommand = uVar6 + 1;
    (this->field_0).field_0.m_head = uVar3 + uVar8;
  }
  return (IssueFetchReturn)(uVar11 | uVar12);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065760
 * symbol: getNumCacheElemsAvailableForFetch
 * prototype: uint32_t getNumCacheElemsAvailableForFetch(InputIndirectBuffer * this, DisallowWrap eDisallowWrap)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumCacheElemsAvailableForFetch(InputIndirectBuffer * this,
   DisallowWrap eDisallowWrap) */

uint32_t __thiscall
A53::InputIndirectBuffer::getNumCacheElemsAvailableForFetch
          (InputIndirectBuffer *this,DisallowWrap eDisallowWrap)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  
  uVar4 = (uint)(this->field_0).field_0.m_numCacheElemsMinus1;
  iVar1 = uVar4 + 1;
  uVar5 = (uint)(this->field_0).field_0.m_countDmaIssued;
  uVar2 = iVar1 - uVar5;
  uVar3 = uVar2;
  if ((((eDisallowWrap & 1) != 0) && (1 < uVar2)) &&
     (uVar3 = iVar1 - ((this->field_0).field_0.m_headCache + uVar5 & uVar4), uVar2 <= uVar3)) {
    uVar3 = uVar2;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606581c
 * symbol: issueFetchFromSram
 * prototype: IssueFetchReturn issueFetchFromSram(InputIndirectBuffer * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_read, uint64_t vaSramSrc, uint32_t maxElemsToFetch)
 * body addresses: 264
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueFetchReturn issueFetchFromSram(InputIndirectBuffer * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_read, uint64_t vaSramSrc,
   uint32_t maxElemsToFetch) */

IssueFetchReturn __thiscall
A53::InputIndirectBuffer::issueFetchFromSram
          (InputIndirectBuffer *this,A53_AddressTranslator *addressTranslator,
          PtdmaVqSubmitState *submit_read,uint64_t vaSramSrc,uint32_t maxElemsToFetch)

{
  int iVar1;
  uint16_t uVar2;
  uint16_t uVar3;
  uint uVar4;
  uint32_t uVar5;
  DmaWaitOnCompletion in_w6;
  ulong uVar6;
  uint uVar7;
  uint uVar8;
  ulong uVar9;
  
  if ((this->field_0).field_0.m_countPtdmaCommand != 6) {
    uVar7 = (uint)(this->field_0).field_0.m_numCacheElemsMinus1;
    iVar1 = uVar7 + 1;
    uVar8 = (uint)(this->field_0).field_0.m_countDmaIssued;
    uVar4 = iVar1 - uVar8;
    if (uVar4 != 0) {
      if (uVar4 <= maxElemsToFetch) {
        maxElemsToFetch = uVar4;
      }
      uVar7 = (this->field_0).field_0.m_headCache + uVar8 & uVar7;
      uVar4 = iVar1 - uVar7;
      uVar8 = (uint)(this->field_0).field_0.m_sizeofElemLog2;
      uVar6 = (this->field_0).field_0.m_vaSramCache + (ulong)(uVar7 << (ulong)(uVar8 & 0x1f));
      if (maxElemsToFetch <= uVar4) {
        uVar4 = maxElemsToFetch;
      }
      uVar9 = (ulong)uVar4;
      uVar7 = uVar4 << (ulong)(uVar8 & 0x1f);
      uVar5 = ptdmaPutCommandCopy(submit_read,uVar7,vaSramSrc & 0xfffff,uVar6 & 0xfffff,0xffff,
                                  (uint)((((uint)uVar6 | (uint)vaSramSrc) & 7) == 0 &&
                                        (uVar7 < 0x101 && (uVar7 & 7) == 0)),in_w6);
      uVar7 = (uint)(this->field_0).field_0.m_countPtdmaCommand +
              (uint)(this->field_0).field_0.m_headPtdmaCommand;
      iVar1 = 0;
      if (5 < uVar7) {
        iVar1 = 6;
      }
      uVar7 = uVar7 - iVar1;
      *(short *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x26) = (short)uVar4;
      uVar2 = (this->field_0).field_0.m_countPtdmaCommand;
      uVar3 = (this->field_0).field_0.m_countDmaIssued;
      *(short *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x24) = (short)(uVar5 >> 5);
      uVar6 = (ulong)(uVar5 >> 5) << 0x20;
      (this->field_0).field_0.m_countPtdmaCommand = uVar2 + 1;
      (this->field_0).field_0.m_countDmaIssued = (short)uVar4 + uVar3;
      goto LAB_06065914;
    }
  }
  uVar9 = 0;
  uVar6 = 0;
LAB_06065914:
  return (IssueFetchReturn)(uVar6 | uVar9);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065924
 * symbol: insertIntoSramCache
 * prototype: bool insertIntoSramCache(InputIndirectBuffer * this, uint32_t numElems, uint32_t * out_cacheElemIdx)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool insertIntoSramCache(InputIndirectBuffer * this, uint32_t numElems,
   uint32_t * out_cacheElemIdx) */

bool __thiscall
A53::InputIndirectBuffer::insertIntoSramCache
          (InputIndirectBuffer *this,uint32_t numElems,uint32_t *out_cacheElemIdx)

{
  uint uVar1;
  uint uVar2;
  
  if ((this->field_0).field_0.m_countPtdmaCommand == 0) {
    uVar1 = (uint)(this->field_0).field_0.m_numCacheElemsMinus1;
    uVar2 = (uint)(this->field_0).field_0.m_countDmaIssued;
    if (numElems <= (uVar1 + 1) - uVar2) {
      *out_cacheElemIdx = (this->field_0).field_0.m_headCache + uVar2 & uVar1;
      (this->field_0).field_0.m_countDmaIssued =
           (this->field_0).field_0.m_countDmaIssued + (short)numElems;
      (this->field_0).field_0.m_countDmaComplete =
           (this->field_0).field_0.m_countDmaComplete + (short)numElems;
      return true;
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065980
 * symbol: updateForPtdmaCompletion
 * prototype: uint32_t updateForPtdmaCompletion(InputIndirectBuffer * this, uint32_t ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo)
 * body addresses: 364
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t updateForPtdmaCompletion(InputIndirectBuffer * this, uint32_t
   ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo) */

uint32_t __thiscall
A53::InputIndirectBuffer::updateForPtdmaCompletion
          (InputIndirectBuffer *this,uint32_t ptdmaQueueSize,uint32_t ptdmaHead_Lo,
          uint32_t ptdmaTail_Lo)

{
  uint16_t uVar1;
  uint uVar2;
  uint16_t uVar3;
  byte bVar4;
  ushort uVar5;
  uint uVar6;
  uint32_t uVar7;
  uint uVar8;
  uint uVar9;
  ulong uVar10;
  uint64_t uVar11;
  uint uVar12;
  uint uVar13;
  
  uVar9 = (uint)(this->field_0).field_0.m_countDmaComplete;
  if ((this->field_0).field_0.m_countDmaIssued == uVar9) {
LAB_060659d0:
    uVar7 = 0;
  }
  else {
    uVar10 = (ulong)(this->field_0).field_0.m_headPtdmaCommand;
    uVar6 = (ptdmaQueueSize >> 5) - 1;
    uVar8 = uVar6 & ptdmaHead_Lo >> 5;
    uVar2 = uVar6 & ptdmaTail_Lo >> 5;
    uVar12 = (uint)*(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x24);
    if (uVar12 == 0xffff) {
      uVar13 = uVar2 - uVar8 & uVar6;
    }
    else {
      uVar13 = uVar2 - uVar8 & uVar6;
      if ((uVar12 - uVar8 & uVar6) < uVar13) goto LAB_060659d0;
    }
    uVar7 = (uint32_t)*(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x26);
    for (uVar8 = 1; uVar8 < (this->field_0).field_0.m_countPtdmaCommand; uVar8 = uVar8 + 1) {
      uVar12 = 0;
      if ((int)uVar10 != 5) {
        uVar12 = (int)uVar10 + 1;
      }
      uVar10 = (ulong)uVar12;
      if ((uVar2 - *(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x24) & uVar6) <= uVar13) break;
      uVar7 = uVar7 + *(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x26);
    }
    uVar5 = (this->field_0).field_0.m_numCacheElemsMinus1;
    bVar4 = (this->field_0).field_0.m_sizeofElemLog2;
    uVar9 = (this->field_0).field_0.m_headCache + uVar9;
    uVar11 = (this->field_0).field_0.m_vaSramCache;
    uVar2 = uVar9 & uVar5;
    uVar9 = uVar7 + uVar9 + 0xffff & (uint)uVar5;
    uVar10 = uVar11 + (uVar2 << (ulong)(bVar4 & 0x1f)) & 0xffffffffffffffc0;
    if (uVar9 <= uVar2) {
      for (; uVar10 < ((ulong)uVar5 + 1 << ((ulong)bVar4 & 0x3f)) + uVar11; uVar10 = uVar10 + 0x40)
      {
        DC_CIVAC(uVar10);
      }
      uVar10 = (this->field_0).field_0.m_vaSramCache;
    }
    for (; uVar10 <= uVar11 + (uVar9 << (ulong)(bVar4 & 0x1f)); uVar10 = uVar10 + 0x40) {
      DC_CIVAC(uVar10);
    }
    UnkSytemRegWrite(0,3,3,0xd,4,0);
    uVar9 = (this->field_0).field_0.m_headPtdmaCommand + uVar8;
    uVar1 = (uint16_t)uVar9;
    uVar3 = uVar1 - 6;
    if ((uVar9 & 0xfffe) < 6) {
      uVar3 = uVar1;
    }
    (this->field_0).field_0.m_countDmaComplete =
         (short)uVar7 + (this->field_0).field_0.m_countDmaComplete;
    (this->field_0).field_0.m_headPtdmaCommand = uVar3;
    (this->field_0).field_0.m_countPtdmaCommand =
         (this->field_0).field_0.m_countPtdmaCommand - (short)uVar8;
  }
  return uVar7;
}


