/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_input_ring.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065aec
 * symbol: issueFetch
 * prototype: IssueFetchReturn issueFetch(InputRing * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_read, uint16_t pasid, uint32_t maxElemsToFetch)
 * body addresses: 360
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueFetchReturn issueFetch(InputRing * this, A53_AddressTranslator *
   addressTranslator, PtdmaVqSubmitState * submit_read, uint16_t pasid, uint32_t maxElemsToFetch) */

IssueFetchReturn __thiscall
A53::InputRing::issueFetch
          (InputRing *this,A53_AddressTranslator *addressTranslator,PtdmaVqSubmitState *submit_read,
          uint16_t pasid,uint32_t maxElemsToFetch)

{
  uint64_t paSrc;
  uint uVar1;
  int iVar2;
  byte bVar3;
  uint16_t uVar4;
  uint16_t uVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  uint32_t uVar9;
  DmaWaitOnCompletion in_w6;
  ulong uVar10;
  ulong uVar11;
  
  uVar7 = getNumRingElemsAvailableToFetch(this,kDisallowWrapInDramRing);
  if (((uVar7 == 0) || ((this->field_0).field_0.m_countPtdmaCommand == 3)) ||
     (uVar8 = getNumCacheElemsAvailableForFetch(this,kDisallowWrapInSramCache), uVar8 == 0)) {
    uVar11 = 0;
    uVar10 = 0;
  }
  else {
    uVar1 = (uint)(this->field_0).field_0.m_countDmaIssued + (uint)(this->field_0).field_0.m_head &
            (1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f)) - 1U;
    bVar3 = (this->field_0).field_0.m_sizeofElemLog2;
    if (maxElemsToFetch <= uVar7) {
      uVar7 = maxElemsToFetch;
    }
    if (uVar7 <= uVar8) {
      uVar8 = uVar7;
    }
    paSrc = (this->field_0).field_0.m_paRing + (ulong)(uVar1 << (ulong)(bVar3 & 0x1f));
    uVar6 = 0x100 >> (ulong)(bVar3 & 0x1f);
    uVar10 = (this->field_0).field_0.m_vaSramCache +
             (ulong)((uVar1 & (1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f)) -
                              1U) << (ulong)(bVar3 & 0x1f));
    uVar7 = 0xffffffff;
    if (uVar6 < uVar8) {
      uVar7 = -uVar6;
    }
    uVar7 = uVar7 & uVar8;
    uVar11 = (ulong)uVar7;
    uVar8 = uVar7 << (ulong)(bVar3 & 0x1f);
    uVar9 = ptdmaPutCommandCopy(submit_read,uVar8,paSrc,uVar10 & 0xfffff,pasid,
                                (uint)((((uint)uVar10 | (uint)paSrc) & 7) == 0 &&
                                      (uVar8 < 0x101 && (uVar8 & 7) == 0)),in_w6);
    uVar8 = (uint)(this->field_0).field_0.m_countPtdmaCommand +
            (uint)(this->field_0).field_0.m_headPtdmaCommand;
    iVar2 = 0;
    if (2 < uVar8) {
      iVar2 = 3;
    }
    uVar8 = uVar8 - iVar2;
    *(short *)((long)&this->field_0 + (ulong)uVar8 * 4 + 0x32) = (short)uVar7;
    uVar4 = (this->field_0).field_0.m_countPtdmaCommand;
    uVar5 = (this->field_0).field_0.m_countDmaIssued;
    *(short *)((long)&this->field_0 + (ulong)uVar8 * 4 + 0x30) = (short)(uVar9 >> 5);
    uVar10 = (ulong)(uVar9 >> 5) << 0x20;
    (this->field_0).field_0.m_countPtdmaCommand = uVar4 + 1;
    (this->field_0).field_0.m_countDmaIssued = (short)uVar7 + uVar5;
  }
  return (IssueFetchReturn)(uVar10 | uVar11);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065c54
 * symbol: getNumRingElemsAvailableToFetch
 * prototype: uint32_t getNumRingElemsAvailableToFetch(InputRing * this, DisallowWrap eDisallowWrap)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumRingElemsAvailableToFetch(InputRing * this, DisallowWrap
   eDisallowWrap) */

uint32_t __thiscall
A53::InputRing::getNumRingElemsAvailableToFetch(InputRing *this,DisallowWrap eDisallowWrap)

{
  ushort uVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  
  uVar1 = (this->field_0).field_0.m_countDmaIssued;
  uVar4 = (this->field_0).field_0.m_count - (uint)uVar1;
  uVar3 = uVar4;
  if ((((eDisallowWrap & 1) != 0) && (1 < uVar4)) &&
     (iVar2 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f),
     uVar3 = iVar2 - ((uint)(this->field_0).field_0.m_head + (uint)uVar1 & iVar2 - 1U),
     uVar4 <= uVar3)) {
    uVar3 = uVar4;
  }
  uVar4 = uVar3;
  if ((((eDisallowWrap >> 1 & 1) != 0) && (1 < uVar3)) &&
     (iVar2 = 1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f),
     uVar4 = iVar2 - ((uint)(this->field_0).field_0.m_head + (uint)uVar1 & iVar2 - 1U),
     uVar3 <= uVar4)) {
    uVar4 = uVar3;
  }
  return uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065cd0
 * symbol: getNumCacheElemsAvailableForFetch
 * prototype: uint32_t getNumCacheElemsAvailableForFetch(InputRing * this, DisallowWrap eDisallowWrap)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumCacheElemsAvailableForFetch(InputRing * this,
   DisallowWrap eDisallowWrap) */

uint32_t __thiscall
A53::InputRing::getNumCacheElemsAvailableForFetch(InputRing *this,DisallowWrap eDisallowWrap)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  
  iVar1 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
  uVar4 = (uint)(this->field_0).field_0.m_countDmaIssued;
  uVar2 = iVar1 - uVar4;
  uVar3 = uVar2;
  if ((((eDisallowWrap & 1) != 0) && (1 < uVar2)) &&
     (uVar3 = iVar1 - ((this->field_0).field_0.m_head + uVar4 & iVar1 - 1U), uVar2 <= uVar3)) {
    uVar3 = uVar2;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065d94
 * symbol: updateTailFromMailbox
 * prototype: int32_t updateTailFromMailbox(InputRing * this, uint32_t tail)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: int32_t updateTailFromMailbox(InputRing * this, uint32_t tail) */

int32_t __thiscall A53::InputRing::updateTailFromMailbox(InputRing *this,uint32_t tail)

{
  uint uVar1;
  ushort uVar2;
  uint uVar3;
  
  uVar3 = 1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f);
  if (tail < uVar3) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = uVar3 - 1;
    uVar1 = (this->field_0).field_0.m_count + (uint)uVar2 & uVar3;
    if (uVar1 == tail) {
      return 0;
    }
    uVar1 = uVar1 - uVar2 & uVar3;
    uVar3 = tail - uVar2 & uVar3;
    if (uVar1 <= uVar3) {
      (this->field_0).field_0.m_count = uVar3;
      return uVar3 - uVar1;
    }
  }
  return -1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065df8
 * symbol: resetHeadFromMailbox
 * prototype: int32_t resetHeadFromMailbox(InputRing * this, uint32_t tail)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: int32_t resetHeadFromMailbox(InputRing * this, uint32_t tail) */

int32_t __thiscall A53::InputRing::resetHeadFromMailbox(InputRing *this,uint32_t tail)

{
  int32_t iVar1;
  
  if ((tail < (uint)(1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f))) &&
     ((this->field_0).field_0.m_countDmaIssued == (this->field_0).field_0.m_countDmaComplete)) {
    iVar1 = 0;
    *(undefined4 *)((long)&this->field_0 + 0x2a) = 0;
    (this->field_0).field_0.m_count = 0;
    (this->field_0).field_0.m_head = (uint16_t)tail;
  }
  else {
    iVar1 = -1;
  }
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065e3c
 * symbol: flushCacheAfterHeadIb
 * prototype: bool flushCacheAfterHeadIb(InputRing * this, uint16_t ringLocation_head)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool flushCacheAfterHeadIb(InputRing * this, uint16_t
   ringLocation_head) */

bool __thiscall A53::InputRing::flushCacheAfterHeadIb(InputRing *this,uint16_t ringLocation_head)

{
  bool bVar1;
  uint16_t uVar2;
  short sVar3;
  
  (this->field_0).field_0.m_count = 0;
  bVar1 = (this->field_0).field_0.m_countPtdmaCommand == 0;
  if (bVar1) {
    (this->field_0).field_0.m_head = ringLocation_head;
    *(undefined4 *)((long)&this->field_0 + 0x2a) = 0;
  }
  else {
    uVar2 = (this->field_0).field_0.m_head;
    (this->field_0).field_0.m_head = ringLocation_head;
    sVar3 = uVar2 - ringLocation_head;
    (this->field_0).field_0.m_countDmaIssued = sVar3 + (this->field_0).field_0.m_countDmaIssued;
    (this->field_0).field_0.m_countDmaComplete = sVar3 + (this->field_0).field_0.m_countDmaComplete;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065e88
 * symbol: updateForPtdmaCompletion
 * prototype: uint32_t updateForPtdmaCompletion(InputRing * this, uint32_t ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo)
 * body addresses: 352
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t updateForPtdmaCompletion(InputRing * this, uint32_t
   ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo) */

uint32_t __thiscall
A53::InputRing::updateForPtdmaCompletion
          (InputRing *this,uint32_t ptdmaQueueSize,uint32_t ptdmaHead_Lo,uint32_t ptdmaTail_Lo)

{
  uint16_t uVar1;
  ulong uVar2;
  uint uVar3;
  uint uVar4;
  uint16_t uVar5;
  uint uVar6;
  byte bVar7;
  uint uVar8;
  uint32_t uVar9;
  uint uVar10;
  uint uVar11;
  ulong uVar12;
  uint64_t uVar13;
  
  uVar11 = (uint)(this->field_0).field_0.m_countDmaComplete;
  if ((this->field_0).field_0.m_countDmaIssued != uVar11) {
    uVar12 = (ulong)(this->field_0).field_0.m_headPtdmaCommand;
    uVar8 = (ptdmaQueueSize >> 5) - 1;
    uVar10 = uVar8 & ptdmaHead_Lo >> 5;
    uVar3 = uVar8 & ptdmaTail_Lo >> 5;
    uVar4 = uVar3 - uVar10 & uVar8;
    if (uVar4 <= (*(ushort *)((long)&this->field_0 + uVar12 * 4 + 0x30) - uVar10 & uVar8)) {
      uVar9 = (uint32_t)*(ushort *)((long)&this->field_0 + uVar12 * 4 + 0x32);
      for (uVar10 = 1; uVar10 < (this->field_0).field_0.m_countPtdmaCommand; uVar10 = uVar10 + 1) {
        uVar6 = 0;
        if ((int)uVar12 != 2) {
          uVar6 = (int)uVar12 + 1;
        }
        uVar12 = (ulong)uVar6;
        if ((uVar3 - *(ushort *)((long)&this->field_0 + uVar12 * 4 + 0x30) & uVar8) <= uVar4) break;
        uVar9 = uVar9 + *(ushort *)((long)&this->field_0 + uVar12 * 4 + 0x32);
      }
      uVar13 = (this->field_0).field_0.m_vaSramCache;
      uVar3 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
      uVar11 = (this->field_0).field_0.m_head + uVar11;
      bVar7 = (this->field_0).field_0.m_sizeofElemLog2;
      uVar4 = uVar3 - 1;
      uVar12 = uVar13 + ((uVar4 & uVar11) << (ulong)(bVar7 & 0x1f)) & 0xffffffffffffffc0;
      uVar2 = uVar13 + ((uVar4 & (uVar9 + uVar11) - 1) + 1 << (ulong)(bVar7 & 0x1f));
      if (uVar2 <= uVar12) {
        for (; uVar12 < ((ulong)uVar3 << ((ulong)bVar7 & 0x3f)) + uVar13; uVar12 = uVar12 + 0x40) {
          DC_CIVAC(uVar12);
        }
        uVar12 = (this->field_0).field_0.m_vaSramCache;
      }
      for (; uVar12 < uVar2; uVar12 = uVar12 + 0x40) {
        DC_CIVAC(uVar12);
      }
      UnkSytemRegWrite(0,3,3,0xd,4,0);
      uVar11 = (this->field_0).field_0.m_headPtdmaCommand + uVar10;
      uVar1 = (uint16_t)uVar11;
      uVar5 = uVar1 - 3;
      if ((uVar11 & 0xffff) < 3) {
        uVar5 = uVar1;
      }
      (this->field_0).field_0.m_countDmaComplete =
           (short)uVar9 + (this->field_0).field_0.m_countDmaComplete;
      (this->field_0).field_0.m_headPtdmaCommand = uVar5;
      (this->field_0).field_0.m_countPtdmaCommand =
           (this->field_0).field_0.m_countPtdmaCommand - (short)uVar10;
      return uVar9;
    }
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065fe8
 * symbol: updateForPtdmaHeadUpdateCompletion
 * prototype: bool updateForPtdmaHeadUpdateCompletion(InputRing * this, uint32_t ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForPtdmaHeadUpdateCompletion(InputRing * this, uint32_t
   ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo) */

bool __thiscall
A53::InputRing::updateForPtdmaHeadUpdateCompletion
          (InputRing *this,uint32_t ptdmaQueueSize,uint32_t ptdmaHead_Lo,uint32_t ptdmaTail_Lo)

{
  uint uVar1;
  uint uVar2;
  bool bVar3;
  
  uVar2 = (ptdmaQueueSize >> 5) - 1;
  uVar1 = uVar2 & ptdmaHead_Lo >> 5;
  bVar3 = ((uVar2 & ptdmaTail_Lo >> 5) - uVar1 & uVar2) <=
          ((this->field_0).field_0.m_ptdmaCmdHeadUpdate - uVar1 & uVar2);
  if (bVar3) {
    (this->field_0).field_0.m_ptdmaCmdHeadUpdate = 0xffff;
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066030
 * symbol: issueHeadUpdate
 * prototype: IssueHeadUpdateReturn issueHeadUpdate(InputRing * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint64_t errorState_b16_63)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueHeadUpdateReturn issueHeadUpdate(InputRing * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid,
   uint64_t errorState_b16_63) */

IssueHeadUpdateReturn __thiscall
A53::InputRing::issueHeadUpdate
          (InputRing *this,A53_AddressTranslator *addressTranslator,PtdmaVqSubmitState *submit_write
          ,uint16_t pasid,uint64_t errorState_b16_63)

{
  uint32_t uVar1;
  DmaWaitOnCompletion in_w6;
  
  **(ulong **)((long)&this->field_0 + 0x18) =
       errorState_b16_63 & 0xffffffffffff0000 | (ulong)(this->field_0).field_0.m_head;
  DC_CVAC((this->field_0).field_0.m_vaSramHead & 0xffffffffffffffc0);
  DataSynchronizationBarrier(3,3);
  uVar1 = ptdmaPutCommandCopy(submit_write,8,(this->field_0).field_0.m_vaSramHead & 0xfffff,
                              (this->field_0).field_0.m_paHead,pasid,kDmaFunctionEnablePrefetch,
                              in_w6);
  (this->field_0).field_0.m_ptdmaCmdHeadUpdate = (uint16_t)(uVar1 >> 5);
  return (IssueHeadUpdateReturn)((ulong)(uVar1 >> 5) << 0x20 | 1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060660ac
 * symbol: issueHeadIbUpdate
 * prototype: IssueHeadUpdateReturn issueHeadIbUpdate(InputRing * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint64_t * aHeadAndStatus_b0_127)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueHeadUpdateReturn issueHeadIbUpdate(InputRing * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid,
   uint64_t * aHeadAndStatus_b0_127) */

IssueHeadUpdateReturn __thiscall
A53::InputRing::issueHeadIbUpdate
          (InputRing *this,A53_AddressTranslator *addressTranslator,PtdmaVqSubmitState *submit_write
          ,uint16_t pasid,uint64_t *aHeadAndStatus_b0_127)

{
  uint64_t uVar1;
  uint32_t uVar2;
  DmaWaitOnCompletion in_w6;
  uint64_t *puVar3;
  
  uVar1 = aHeadAndStatus_b0_127[1];
  puVar3 = (uint64_t *)(this->field_0).field_0.m_vaSramHead;
  *puVar3 = *aHeadAndStatus_b0_127;
  puVar3[1] = uVar1;
  DC_CVAC((this->field_0).field_0.m_vaSramHead & 0xffffffffffffffc0);
  DataSynchronizationBarrier(3,3);
  uVar2 = ptdmaPutCommandCopy(submit_write,0x10,(this->field_0).field_0.m_vaSramHead & 0xfffff,
                              (this->field_0).field_0.m_paHead,pasid,kDmaFunctionEnablePrefetch,
                              in_w6);
  (this->field_0).field_0.m_ptdmaCmdHeadUpdate = (uint16_t)(uVar2 >> 5);
  return (IssueHeadUpdateReturn)((ulong)(uVar2 >> 5) << 0x20 | 1);
}


