/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_hashtable.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063cdc
 * symbol: calcSize
 * prototype: uint32_t calcSize(HashTable * this, uint16_t maxElements)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t calcSize(HashTable * this, uint16_t maxElements) */

uint32_t __thiscall A53::HashTable::calcSize(HashTable *this,uint16_t maxElements)

{
  return ((uint)maxElements * 0x10 + 0x7fff8 & 0x7fff8) + (uint)maxElements * 4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063cf0
 * symbol: setup
 * prototype: void setup(HashTable * this, uint64_t vaSram, uint16_t maxElements, hashFunc * pfnHashFunc)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setup(HashTable * this, uint64_t vaSram, uint16_t maxElements,
   hashFunc * pfnHashFunc) */

void __thiscall
A53::HashTable::setup(HashTable *this,uint64_t vaSram,uint16_t maxElements,hashFunc *pfnHashFunc)

{
  uint64_t uVar1;
  uint uVar2;
  ulong uVar3;
  ushort index;
  
  uVar3 = (ulong)maxElements;
  uVar1 = vaSram + uVar3 * 8;
  this->m_maxElements = maxElements;
  this->m_vaHashTable = vaSram;
  this->m_vaHeap = uVar1;
  this->m_pfnHashFunc = pfnHashFunc;
  this->m_vaHeapList = (uVar1 + uVar3 * 8) - 8;
  A53_MEMSET(vaSram,uVar3 << 3,0xff);
  uVar2 = this->m_maxElements - 1;
  *(uint *)(this->m_vaHeapList + ((ulong)uVar2 & 0xffff) * 4) = uVar2 & 0xffff | uVar2 * 0x10000;
  for (index = 0; (int)(uint)index < (int)(this->m_maxElements - 1); index = index + 1) {
    pushToFreeList(this,index);
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063d84
 * symbol: pushToFreeList
 * prototype: void pushToFreeList(HashTable * this, uint16_t index)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushToFreeList(HashTable * this, uint16_t index) */

void __thiscall A53::HashTable::pushToFreeList(HashTable *this,uint16_t index)

{
  uint *puVar1;
  uint uVar2;
  ushort uVar3;
  
  uVar3 = this->m_maxElements - 1;
  puVar1 = (uint *)(this->m_vaHeapList + (ulong)uVar3 * 4);
  uVar2 = *puVar1;
  *(uint16_t *)((long)puVar1 + 2) = index;
  *(uint16_t *)(this->m_vaHeapList + (ulong)(uVar2 >> 0x10) * 4) = index;
  *(uint *)(this->m_vaHeapList + (ulong)index * 4) = uVar2 & 0xffff0000 | (uint)uVar3;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063dc0
 * symbol: insert
 * prototype: void insert(HashTable * this, uint32_t key, uint16_t val)
 * body addresses: 180
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void insert(HashTable * this, uint32_t key, uint16_t val) */

void __thiscall A53::HashTable::insert(HashTable *this,uint32_t key,uint16_t val)

{
  ushort uVar1;
  uint uVar2;
  uint16_t uVar3;
  ulong uVar4;
  undefined8 uVar5;
  
  uVar1 = this->m_maxElements;
  uVar3 = (*this->m_pfnHashFunc)(key);
  uVar2 = 0;
  if (uVar1 != 0) {
    uVar2 = (uint)uVar3 / (uint)uVar1;
  }
  uVar4 = (ulong)((uint)uVar3 - uVar2 * uVar1);
  uVar5 = *(undefined8 *)(this->m_vaHashTable + uVar4 * 8);
  if ((int)uVar5 == -1) {
    *(ulong *)(this->m_vaHashTable + uVar4 * 8) = (ulong)CONCAT24(val,key) | 0xffff000000000000;
  }
  else {
    uVar1 = *(ushort *)(this->m_vaHeapList + (ulong)(ushort)(this->m_maxElements - 1) * 4 + 2);
    removeFromFreeList(this,uVar1);
    *(ulong *)(this->m_vaHashTable + uVar4 * 8) = CONCAT26(uVar1,CONCAT24(val,key));
    *(undefined8 *)(this->m_vaHeap + (ulong)uVar1 * 8) = uVar5;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063e74
 * symbol: peekFreeList
 * prototype: uint16_t peekFreeList(HashTable * this)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t peekFreeList(HashTable * this) */

uint16_t __thiscall A53::HashTable::peekFreeList(HashTable *this)

{
  return *(uint16_t *)(this->m_vaHeapList + (ulong)(ushort)(this->m_maxElements - 1) * 4 + 2);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063e8c
 * symbol: removeFromFreeList
 * prototype: void removeFromFreeList(HashTable * this, uint16_t index)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void removeFromFreeList(HashTable * this, uint16_t index) */

void __thiscall A53::HashTable::removeFromFreeList(HashTable *this,uint16_t index)

{
  uint uVar1;
  
  uVar1 = *(uint *)(this->m_vaHeapList + (ulong)index * 4);
  *(short *)(this->m_vaHeapList + (ulong)((uVar1 & 0xffff) << 2) + 2) = (short)(uVar1 >> 0x10);
  *(short *)(this->m_vaHeapList + (ulong)(uVar1 >> 0x10) * 4) = (short)uVar1;
  *(uint *)(this->m_vaHeapList + (ulong)index * 4) = CONCAT22(index,index);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063ec4
 * symbol: findMostRecent
 * prototype: uint16_t findMostRecent(HashTable * this, uint32_t key)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t findMostRecent(HashTable * this, uint32_t key) */

uint16_t __thiscall A53::HashTable::findMostRecent(HashTable *this,uint32_t key)

{
  ushort uVar1;
  uint uVar2;
  bool bVar3;
  uint16_t uVar4;
  ulong uVar5;
  uint64_t *puVar6;
  ulong uVar7;
  
  uVar1 = this->m_maxElements;
  uVar4 = (*this->m_pfnHashFunc)(key);
  uVar2 = 0;
  if (uVar1 != 0) {
    uVar2 = (uint)uVar4 / (uint)uVar1;
  }
  uVar5 = (ulong)((uint)uVar4 - uVar2 * uVar1);
  puVar6 = &this->m_vaHashTable;
  do {
    uVar7 = *(ulong *)(*puVar6 + (ulong)((uint)uVar5 & 0xffff) * 8);
    uVar5 = uVar7 >> 0x30;
    bVar3 = true;
    if ((uint32_t)uVar7 != key) {
      bVar3 = (short)(uVar7 >> 0x30) == -1;
    }
    puVar6 = &this->m_vaHeap;
  } while (!bVar3);
  uVar4 = (uint16_t)(uVar7 >> 0x20);
  if ((uint32_t)uVar7 != key) {
    uVar4 = 0xffff;
  }
  return uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063f40
 * symbol: find
 * prototype: void find(HashTable * this, uint32_t key)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: Iterator find(HashTable * this, uint32_t key) */

void __thiscall A53::HashTable::find(HashTable *this,uint32_t key)

{
  ushort uVar1;
  uint uVar2;
  uint16_t uVar3;
  Iterator *in_x8;
  anon_struct_8_3_e5b2e3e7_for_anon_union_8_2_653be8f9_for_HashNode_0_0 aVar4;
  
  uVar1 = this->m_maxElements;
  uVar3 = (*this->m_pfnHashFunc)(key);
  uVar2 = 0;
  if (uVar1 != 0) {
    uVar2 = (uint)uVar3 / (uint)uVar1;
  }
  aVar4 = *(anon_struct_8_3_e5b2e3e7_for_anon_union_8_2_653be8f9_for_HashNode_0_0 *)
           (this->m_vaHashTable + (ulong)((uint)uVar3 - uVar2 * uVar1) * 8);
  in_x8->m_vaHeap = this->m_vaHeap;
  in_x8->m_key = key;
  (in_x8->m_listNode).field_0.field_0 = aVar4;
  if (aVar4.m_key == key) {
    return;
  }
  Iterator::next(in_x8);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063fb8
 * symbol: next
 * prototype: void next(Iterator * this)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void next(Iterator * this) */

void __thiscall A53::HashTable::Iterator::next(Iterator *this)

{
  uint32_t uVar1;
  ulong uVar2;
  anon_struct_8_3_e5b2e3e7_for_anon_union_8_2_653be8f9_for_HashNode_0_0 aVar3;
  
  uVar2 = (ulong)(this->m_listNode).field_0.field_0.m_next;
  do {
    if ((~(uint)uVar2 & 0xffff) == 0) {
      (this->m_listNode).field_0.field_0.m_key = 0xffff;
      return;
    }
    uVar1 = this->m_key;
    aVar3 = *(anon_struct_8_3_e5b2e3e7_for_anon_union_8_2_653be8f9_for_HashNode_0_0 *)
             (this->m_vaHeap + uVar2 * 8);
    uVar2 = (ulong)aVar3 >> 0x30;
    (this->m_listNode).field_0.field_0 = aVar3;
  } while (uVar1 != aVar3.m_key);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063ff8
 * symbol: remove
 * prototype: int remove(HashTable * this, char * __filename)
 * body addresses: 320
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void remove(HashTable * this, uint32_t key, uint16_t value) */

int __thiscall A53::HashTable::remove(HashTable *this,char *__filename)

{
  ushort uVar1;
  ushort uVar2;
  uint16_t uVar3;
  uint uVar4;
  HashTable *pHVar5;
  uint uVar6;
  ulong uVar7;
  ulong in_x2;
  uint uVar8;
  ulong uVar9;
  undefined8 uVar10;
  ulong uVar11;
  ulong uVar12;
  ulong uVar13;
  uint uVar14;
  
  uVar2 = (ushort)in_x2;
  uVar1 = this->m_maxElements;
  uVar3 = (*this->m_pfnHashFunc)((uint32_t)__filename);
  uVar4 = (uint)uVar3;
  uVar12 = 0;
  uVar14 = 0;
  if (uVar1 != 0) {
    uVar14 = uVar4 / uVar1;
  }
  uVar11 = (ulong)(uVar4 - uVar14 * uVar1);
  uVar13 = *(ulong *)(this->m_vaHashTable + uVar11 * 8);
  uVar9 = uVar13;
  uVar14 = 0xffff;
  uVar8 = 0xffff;
  while( true ) {
    uVar7 = uVar9 >> 0x30;
    uVar1 = (ushort)(uVar9 >> 0x30);
    uVar6 = (uint)uVar1;
    if ((uVar6 == 0xffff) ||
       ((uint32_t)uVar9 == (uint32_t)__filename && ((uint)(uVar9 >> 0x20) & 0xffff) == (uint)uVar2))
    break;
    uVar12 = uVar9 & 0xffffffffffff;
    uVar9 = *(ulong *)(this->m_vaHeap + uVar7 * 8);
    in_x2 = uVar7;
    uVar14 = uVar8;
    uVar8 = uVar6;
  }
  if ((~uVar8 & 0xffff) == 0) {
    if (uVar6 == 0xffff) {
      *(undefined8 *)(this->m_vaHashTable + uVar11 * 8) = 0xffffffffffffffff;
    }
    else {
      uVar10 = *(undefined8 *)(this->m_vaHeap + uVar7 * 8);
      pHVar5 = this;
      pushToFreeList(this,uVar1);
      uVar4 = (uint)pHVar5;
      *(undefined8 *)(this->m_vaHashTable + uVar11 * 8) = uVar10;
    }
  }
  else {
    pHVar5 = this;
    pushToFreeList(this,(uint16_t)in_x2);
    uVar4 = (uint)pHVar5;
    if ((~uVar14 & 0xffff) == 0) {
      *(ulong *)(this->m_vaHashTable + uVar11 * 8) =
           uVar9 & 0xffff000000000000 | uVar13 & 0xffffffffffff;
    }
    else {
      *(ulong *)(this->m_vaHeap + (ulong)uVar14 * 8) = uVar12 | uVar9 & 0xffff000000000000;
    }
  }
  return uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064138
 * symbol: isEnd
 * prototype: bool isEnd(Iterator * this)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isEnd(Iterator * this) */

bool __thiscall A53::HashTable::Iterator::isEnd(Iterator *this)

{
  return (this->m_listNode).field_0.field_0.m_key == 0xffff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606414c
 * symbol: getVal
 * prototype: uint16_t getVal(Iterator * this)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getVal(Iterator * this) */

uint16_t __thiscall A53::HashTable::Iterator::getVal(Iterator *this)

{
  return (this->m_listNode).field_0.field_0.m_value;
}


