/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_controller_pipeline_common.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06059e5c
 * symbol: handleControllerRingsEvent
 * prototype: void handleControllerRingsEvent(void * pContext, ControllerRings * rings, ControllerRingsEventType eEventType, uint32_t iRing)
 * body addresses: 416
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::handleControllerRingsEvent
               (void *pContext,ControllerRings *rings,ControllerRingsEventType eEventType,
               uint32_t iRing)

{
  A53Controller_InputRingWithIndirectBufferHead *pAVar1;
  uint uVar2;
  ControllerRingsState *pCVar3;
  InputIndirectBuffer *pIVar4;
  uint64_t uVar5;
  uint64_t uVar6;
  uint uVar7;
  uint64_t uVar8;
  undefined4 uVar9;
  uint64_t uVar10;
  uint64_t uVar11;
  uint64_t uVar12;
  ulong uVar13;
  ulong uVar14;
  ulong uVar15;
  
  uVar14 = (ulong)iRing;
  if (eEventType == kControllerRingsCommandRingResettingHead) {
    uVar2 = (rings->m_static_config).field_0.asU32 >> 6 & 0x1f;
    uVar7 = (uint)(1L << (uVar14 & 0x3f));
    if (iRing < uVar2) {
      uVar13 = 0;
      *(uint16_t *)&rings->m_paInputRingHead[uVar14].field_0 =
           rings->m_paInputRing[uVar14].field_0.field_0.m_head;
      pCVar3 = rings->m_pRingsState;
      uVar8 = (pCVar3->field_0).asU64[2];
      uVar6 = (pCVar3->field_0).asU64[4];
      uVar5 = (pCVar3->field_0).field_0.m_maskTraceEventTypeFilter;
      uVar10 = (pCVar3->field_0).asU64[0];
      uVar12 = (pCVar3->field_0).asU64[1];
      uVar9 = *(undefined4 *)((long)&pCVar3->field_0 + 0x30);
      uVar14 = (ulong)(uVar7 | (uint)(pCVar3->field_0).asU64[3]) & 0x3fffff;
      uVar11 = (pCVar3->field_0).asU64[3] & 0xffffffffffc00000;
    }
    else {
      uVar15 = (ulong)(iRing - uVar2);
      pAVar1 = rings->m_paInputRingHeadIb + uVar15;
      uVar13 = (pAVar1->field_0).asU64[0];
      uVar14 = (ulong)rings->m_paInputRing[uVar14].field_0.field_0.m_head;
      (pAVar1->field_0).asU64[0] = uVar13 & 0xffffffffe0000000 | uVar14;
      if (((uint)uVar13 >> 0x1d & 1) != 0) {
        (pAVar1->field_0).asU64[0] = uVar13 & 0xffffffffc0000000 | uVar14;
        (pAVar1->field_0).asU64[1] = 0;
        (pAVar1->field_0).asU32[1] = 0;
      }
      uVar14 = (rings->m_pRingsState->field_0).asU64[3];
      (rings->m_pRingsState->field_0).asU64[3] =
           uVar14 & 0xffffffffffc00000 | (ulong)(uVar7 | (uint)uVar14) & 0x3fffff;
      InputIndirectBuffer::discardOverFetch(rings->m_paInputIndirectBuffer + uVar15,0);
      pIVar4 = rings->m_paInputIndirectBuffer;
      uVar14 = 0;
      pIVar4[uVar15].field_0.field_0.m_paBuffer = 0;
      *(undefined8 *)((long)&pIVar4[uVar15].field_0 + 0x14) = 0;
      rings->m_paInputIndirectBuffer[uVar15].field_0.field_0.m_ibCommandId = 0;
      rings->m_paIndirectBufferNumElemsRemaining[uVar15] = 0;
      pCVar3 = rings->m_pRingsState;
      uVar11 = (pCVar3->field_0).asU64[3];
      uVar6 = (pCVar3->field_0).asU64[4];
      uVar5 = (pCVar3->field_0).field_0.m_maskTraceEventTypeFilter;
      uVar10 = (pCVar3->field_0).asU64[0];
      uVar12 = (pCVar3->field_0).asU64[1];
      uVar9 = *(undefined4 *)((long)&pCVar3->field_0 + 0x30);
      uVar8 = (pCVar3->field_0).asU64[2] & 0xffffffff003fffff;
      uVar13 = (ulong)(~(uint)(1L << (uVar15 & 0x3f)) & (uint)(pCVar3->field_0).asU64[2] >> 0x16) <<
               0x16;
    }
    (pCVar3->field_0).asU64[0] = uVar10;
    (pCVar3->field_0).asU64[1] = uVar12;
    (pCVar3->field_0).asU64[2] = uVar8 | uVar13;
    (pCVar3->field_0).asU64[3] = uVar11 | uVar14;
    (pCVar3->field_0).asU64[4] = uVar6;
    (pCVar3->field_0).field_0.m_maskTraceEventTypeFilter = uVar5;
    *(undefined4 *)((long)&pCVar3->field_0 + 0x30) = uVar9;
  }
  else if (eEventType == kControllerRingsCommandRingHalting) {
    setCommandRingCommandNotPreParsed((ControllerPipelineCommandRingPreParseState *)pContext,iRing);
    setCommandRingPreParsedCommandType
              ((ControllerPipelineCommandRingPreParseState *)pContext,iRing,
               kA53ControllerCommandTypeNone);
    return;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a034
 * symbol: scrubPtdmaCommandSource
 * prototype: uint32_t scrubPtdmaCommandSource(ControllerStaticConfiguration static_config, PtdmaVqState * aPtdmaQueue, uint32_t * aVaSramPtdmaCommandSource, A53DeviceOpSource deviceOpSource, uint32_t maskPtdmaVq, uint32_t maskDeviceOpSource)
 * body addresses: 168
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::scrubPtdmaCommandSource
                   (ControllerStaticConfiguration static_config,PtdmaVqState *aPtdmaQueue,
                   uint32_t *aVaSramPtdmaCommandSource,A53DeviceOpSource deviceOpSource,
                   uint32_t maskPtdmaVq,uint32_t maskDeviceOpSource)

{
  PtdmaVqState *pPVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  uint32_t uVar6;
  ulong uVar7;
  uint uVar8;
  ulong uVar9;
  
  uVar6 = 0;
  if (((int)deviceOpSource.field_0 < 0) && (((uint)deviceOpSource.field_0 >> 0x1e & 1) != 0)) {
    uVar6 = 0;
    for (uVar7 = 0; uVar7 != ((ulong)((uint)static_config.field_0 >> 0x1b) & 3); uVar7 = uVar7 + 1)
    {
      if ((1 << (ulong)((uint)uVar7 & 0x1f) & maskPtdmaVq) != 0) {
        pPVar1 = aPtdmaQueue + uVar7;
        uVar4 = (pPVar1->m_submit).m_maskVqdPointer;
        uVar3 = pPVar1->m_tail_lo;
        uVar2 = pPVar1->m_head_lo & uVar4;
        uVar5 = aVaSramPtdmaCommandSource[uVar7];
        for (uVar8 = uVar2 >> 3;
            uVar8 < (((uVar3 & uVar4) >> 3) - (uVar2 >> 3) & uVar4 >> 3) + (uVar2 >> 3);
            uVar8 = uVar8 + 4) {
          uVar9 = (ulong)(uVar8 & uVar4 >> 3);
          if ((maskDeviceOpSource & 0xf81fffff &
              (*(uint *)(uVar5 + uVar9) ^ (uint)deviceOpSource.field_0)) == 0) {
            uVar6 = uVar6 + 1;
            *(undefined4 *)(uVar5 + uVar9) = 0xc0000000;
          }
        }
      }
    }
  }
  return uVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a0dc
 * symbol: scrubDvmGcrCommandSource
 * prototype: uint32_t scrubDvmGcrCommandSource(ControllerPipelineDvmState * dvmGcrState, A53DeviceOpSource deviceOpSource, uint32_t maskDeviceOpSource)
 * body addresses: 152
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::scrubDvmGcrCommandSource
                   (ControllerPipelineDvmState *dvmGcrState,A53DeviceOpSource deviceOpSource,
                   uint32_t maskDeviceOpSource)

{
  long lVar1;
  uint uVar2;
  uint uVar3;
  uint32_t uVar4;
  int iVar5;
  ulong uVar6;
  
  uVar4 = 0;
  if (((int)deviceOpSource.field_0 < 0) && (((uint)deviceOpSource.field_0 >> 0x1e & 1) != 0)) {
    uVar6 = *(ulong *)dvmGcrState;
    uVar3 = (uint)uVar6 >> 0x15 & 7;
    uVar2 = (uint)uVar6 - (int)(uVar6 >> 8) & 0xff;
    if ((uint)(2 << uVar3) < uVar2) {
      return 0;
    }
    uVar4 = 0;
    lVar1 = (ulong)dvmGcrState->m_vaSramRw + 0x10;
    uVar6 = (uVar6 >> 8 & 0xff) << 2;
    for (iVar5 = -uVar2; iVar5 != 0; iVar5 = iVar5 + 1) {
      if ((maskDeviceOpSource & 0xf81fffff &
          (*(uint *)(lVar1 + (uVar6 & 0xffffffff)) ^ (uint)deviceOpSource.field_0)) == 0) {
        uVar4 = uVar4 + 1;
        *(undefined4 *)((uVar6 & 0xffffffff) + lVar1) = 0xc0000000;
      }
      uVar6 = (uVar6 & 0xffffffff) + 4 & (8L << uVar3) - 1U;
    }
  }
  return uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a174
 * symbol: dmaReadCmdDiscard_SdmaHead
 * prototype: void dmaReadCmdDiscard_SdmaHead(ControllerRings * rings, ControllerPipelineDvmState * dvmGcrState, PtdmaVqState * ptdmaQueueRead, InternalDmaOpSource source, uint32_t discard_head_lo, uint32_t discard_tail_lo, uint64_t addressError, uint16_t pasidError)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::dmaReadCmdDiscard_SdmaHead
               (ControllerRings *rings,ControllerPipelineDvmState *dvmGcrState,
               PtdmaVqState *ptdmaQueueRead,InternalDmaOpSource source,uint32_t discard_head_lo,
               uint32_t discard_tail_lo,uint64_t addressError,uint16_t pasidError)

{
  if ((((rings->m_static_config).field_0.asU32 >> 0x1a ^ (uint)source.field_0 >> 7) & 1 |
      (uint)source.field_0 & 0x7f) != 0) {
    return;
  }
  *(ulong *)dvmGcrState = *(ulong *)dvmGcrState & 0xfffffffffffeffff;
  controllerHaltAndError
            (rings,kA53ControllerSysError_PageFaultRd_Dma_SdmaMmio,addressError,pasidError);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a1b4
 * symbol: dmaWriteCmdDiscard_SdmaTail
 * prototype: void dmaWriteCmdDiscard_SdmaTail(ControllerRings * rings, ControllerPipelineDvmState * dvmGcrState, PtdmaVqState * ptdmaQueueWrite, InternalDmaOpSource source, uint32_t discard_head_lo, uint32_t discard_tail_lo, uint64_t addressError, uint16_t pasidError)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::dmaWriteCmdDiscard_SdmaTail
               (ControllerRings *rings,ControllerPipelineDvmState *dvmGcrState,
               PtdmaVqState *ptdmaQueueWrite,InternalDmaOpSource source,uint32_t discard_head_lo,
               uint32_t discard_tail_lo,uint64_t addressError,uint16_t pasidError)

{
  if (((((rings->m_static_config).field_0.asU32 >> 0x1a ^ (uint)source.field_0 >> 7) & 1) == 0) &&
     ((((uint)source.field_0 >> 1 & 0x3f) << 3 | 4) == 0xc)) {
    *(ulong *)dvmGcrState = *(ulong *)dvmGcrState & 0xfffffffffffdffff;
    controllerHaltAndError
              (rings,kA53ControllerSysError_PageFaultWr_Dma_SdmaMmio,addressError,pasidError);
    return;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a1fc
 * symbol: setPipelineCommandDataError
 * prototype: bool setPipelineCommandDataError(ControllerRuntimeConfiguration * runtime_config, SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, A53ControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 312
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataError
               (ControllerRuntimeConfiguration *runtime_config,
               SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               A53ControllerSysErrorCode eErrorCode,uint64_t addressError,uint16_t pasidError)

{
  uint32_t pipelineCmdElemIdx;
  bool bVar1;
  anon_union_8_2_653be89a_for_CommandInRingLocation_0 local_68;
  ulong local_60;
  uint local_58 [2];
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_48 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_48[0].field_0);
  if (((bVar1) && ((local_48[0].asU32 >> 6 & 1) == 0)) &&
     (bVar1 = SramRingView::canWriteElementsWrapped
                        (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                         (local_48[0].asU32 & 0x1f) + 1), bVar1)) {
    pipelineCmdElemIdx = (local_48[0].asU32 >> 4 & 2) + 2;
    getPipelineCommandDataElement
              (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
               pipelineCmdElemIdx,local_58);
    local_60 = (ulong)((eErrorCode & 0x7f) << 8 | 0x80) | (addressError & 0xffff) << 0x10 |
               (addressError >> 0x10) << 0x20 | (ulong)local_58[0] & 0x7f;
    setPipelineCommandDataElements
              (sramRingView_PipelineCommandData,pipelineCommandId,pipelineCmdElemIdx,2,
               (uint32_t *)&local_60);
    setPipelineCommandDataHeaderStateCompleted
              (sramRingView_PipelineCommandData,pipelineCommandId,
               kPipelineCommandDataHeaderCompletionTypeSysError,
               *(ushort *)((long)&runtime_config->field_0 + 10) & 1);
    if (((byte)local_48[0].asU32._0_1_ >> 5 & 1) == 0) {
      getPipelineCommandDataCommandInRingLocation
                (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                 (CommandInRingLocation *)&local_68.field_0);
      local_68 = (anon_union_8_2_653be89a_for_CommandInRingLocation_0)
                 ((ulong)local_68 & 0xffffffff00000000 |
                 (ulong)local_68 & 0xffff | (ulong)pasidError << 0x10);
      setPipelineCommandDataCommandInRingLocation
                (sramRingView_PipelineCommandData,pipelineCommandId,(CommandInRingLocation)local_68)
      ;
    }
    bVar1 = true;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a3a8
 * symbol: setPipelineCommandDataError
 * prototype: bool setPipelineCommandDataError(ControllerRuntimeConfiguration * runtime_config, SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, A53ControllerAppErrorCode eAppErrorCode, uint64_t addressError, PipelineCommandErrorAddressErrorIsPasidIndirect eIsPasidIndirect)
 * body addresses: 332
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataError
               (ControllerRuntimeConfiguration *runtime_config,
               SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               A53ControllerAppErrorCode eAppErrorCode,uint64_t addressError,
               PipelineCommandErrorAddressErrorIsPasidIndirect eIsPasidIndirect)

{
  uint32_t pipelineCmdElemIdx;
  ulong uVar1;
  bool bVar2;
  anon_union_8_2_653be89a_for_CommandInRingLocation_0 local_68;
  ulong local_60;
  uint local_58 [2];
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_48 [2];
  
  bVar2 = getPipelineCommandDataHeader
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_48[0].field_0);
  if (((bVar2) && ((local_48[0].asU32 >> 6 & 1) == 0)) &&
     (bVar2 = SramRingView::canWriteElementsWrapped
                        (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                         (local_48[0].asU32 & 0x1f) + 1), bVar2)) {
    pipelineCmdElemIdx = (local_48[0].asU32 >> 4 & 2) + 2;
    getPipelineCommandDataElement
              (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
               pipelineCmdElemIdx,local_58);
    local_60 = (ulong)((eAppErrorCode & 0x7f) << 8) | (addressError & 0xffff) << 0x10 |
               (addressError >> 0x10) << 0x20 | (ulong)((eIsPasidIndirect & 1) << 0xf) |
               (ulong)local_58[0] & 0x7f;
    setPipelineCommandDataElements
              (sramRingView_PipelineCommandData,pipelineCommandId,pipelineCmdElemIdx,2,
               (uint32_t *)&local_60);
    setPipelineCommandDataHeaderStateCompleted
              (sramRingView_PipelineCommandData,pipelineCommandId,
               kPipelineCommandDataHeaderCompletionTypeAppError,
               *(ushort *)((long)&runtime_config->field_0 + 10) & 1);
    if (((byte)local_48[0].asU32._0_1_ >> 5 & 1) == 0) {
      getPipelineCommandDataCommandInRingLocation
                (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                 (CommandInRingLocation *)&local_68.field_0);
      uVar1 = 0;
      if (eIsPasidIndirect != kPipelineCommandErrorAddressErrorIsPasidZero) {
        uVar1 = (ulong)(runtime_config->field_0).field_0.m_pasidIndirect << 0x10;
      }
      local_68 = (anon_union_8_2_653be89a_for_CommandInRingLocation_0)
                 (uVar1 | (ulong)local_68 & 0xffffffff0000ffff);
      setPipelineCommandDataCommandInRingLocation
                (sramRingView_PipelineCommandData,pipelineCommandId,(CommandInRingLocation)local_68)
      ;
    }
    bVar2 = true;
  }
  else {
    bVar2 = false;
  }
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a4f4
 * symbol: pushPspError
 * prototype: bool pushPspError(ControllerRings * rings, PushPspErrorBlocking eBlocking, uint32_t iCommandRing, CommandInRingLocation * cmdLoc, uint32_t opCode, A53ControllerSysErrorCode eErrorCode, uint64_t addressError)
 * body addresses: 228
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pushPspError(ControllerRings *rings,PushPspErrorBlocking eBlocking,uint32_t iCommandRing,
                      CommandInRingLocation *cmdLoc,uint32_t opCode,
                      A53ControllerSysErrorCode eErrorCode,uint64_t addressError)

{
  undefined *vaSramA53Controller_PSP_MessageRing;
  uint uVar1;
  bool bVar2;
  anon_struct_8_3_e1c847e3_for_anon_union_8_2_653be89a_for_CommandInRingLocation_0_0 aVar3;
  A53Controller_PSP_Error local_70;
  uint32_t local_44;
  
  uVar1 = (rings->m_static_config).field_0.asU32;
  vaSramA53Controller_PSP_MessageRing = &DAT_04040000;
  if ((uVar1 & 0x4000000) != 0) {
    vaSramA53Controller_PSP_MessageRing = &DAT_04227000;
  }
  bVar2 = pspMessageRing_allocateEntry
                    (uVar1 >> 0x16 & 3,uVar1 >> 0x1a & 1,
                     (uint64_t)vaSramA53Controller_PSP_MessageRing,eBlocking,&local_44);
  if (bVar2) {
    aVar3 = (cmdLoc->field_0).field_0;
    uVar1 = (rings->m_static_config).field_0.asU32;
    local_70.field_0.asU64[1] =
         local_70.field_0.asU64[1] & 0xffffffffffffff80 | (ulong)(opCode & 0x7f);
    local_70.field_0.asU32[0] = iCommandRing & 0x1f | (eErrorCode & 0x7f) << 8 | aVar3._0_4_ << 0x10
    ;
    local_70.field_0.asU64[3] = addressError & 0xffffffffffff | ((ulong)aVar3 >> 0x10) << 0x30;
    local_70.field_0.field_0.m_pid = aVar3.m_pid;
    pspMessageRing_writeErrorAndInitiatePspInterrupt
              (uVar1 >> 0x16 & 3,uVar1 >> 0x1a & 1,(uint64_t)vaSramA53Controller_PSP_MessageRing,
               local_44,&local_70);
  }
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a5d8
 * symbol: pushPspError
 * prototype: bool pushPspError(ControllerRings * rings, PushPspErrorBlocking eBlocking, uint32_t iCommandRing, CommandInIndirectBufferLocation * cmdLoc, uint32_t pid, uint32_t opCode, A53ControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 268
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::pushPspError(ControllerRings *rings,PushPspErrorBlocking eBlocking,uint32_t iCommandRing,
                      CommandInIndirectBufferLocation *cmdLoc,uint32_t pid,uint32_t opCode,
                      A53ControllerSysErrorCode eErrorCode,uint64_t addressError,uint16_t pasidError
                      )

{
  undefined *vaSramA53Controller_PSP_MessageRing;
  ulong uVar1;
  uint uVar2;
  bool bVar3;
  ulong uVar4;
  A53Controller_PSP_Error local_78;
  uint32_t local_54;
  
  uVar2 = (rings->m_static_config).field_0.asU32;
  vaSramA53Controller_PSP_MessageRing = &DAT_04040000;
  if ((uVar2 & 0x4000000) != 0) {
    vaSramA53Controller_PSP_MessageRing = &DAT_04227000;
  }
  bVar3 = pspMessageRing_allocateEntry
                    (uVar2 >> 0x16 & 3,uVar2 >> 0x1a & 1,
                     (uint64_t)vaSramA53Controller_PSP_MessageRing,eBlocking,&local_54);
  if (bVar3) {
    uVar1 = *(ulong *)((long)&cmdLoc->field_0 + 8);
    local_78.field_0.asU32[0] =
         iCommandRing & 0x1f | (eErrorCode & 0x7f) << 8 | (int)*(ulong *)&cmdLoc->field_0 << 0x10;
    uVar4 = *(ulong *)&cmdLoc->field_0 >> 8;
    local_78.field_0.asU64[3] = addressError & 0xffffffffffff | (ulong)pasidError << 0x30;
    uVar2 = (rings->m_static_config).field_0.asU32;
    local_78.field_0.asU64[1] =
         uVar4 & 0xffffff00 |
         local_78.field_0.asU64[1] & 0xff00000000000000 | (ulong)(opCode & 0x7f) |
         uVar4 & 0xffffff00000000 | 0x80;
    local_78.field_0.asU64[2] =
         uVar1 & 0x1fff000000000000 | local_78.field_0.asU64[2] & 0xe000000000000000 |
         uVar1 & 0xffffffffffff;
    local_78.field_0.field_0.m_pid = pid;
    pspMessageRing_writeErrorAndInitiatePspInterrupt
              (uVar2 >> 0x16 & 3,uVar2 >> 0x1a & 1,(uint64_t)vaSramA53Controller_PSP_MessageRing,
               local_54,&local_78);
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605cddc
 * symbol: setPtdmaCommandSource
 * prototype: bool setPtdmaCommandSource(ControllerStaticConfiguration static_config, PtdmaVqState * aPtdmaQueue, uint32_t * aVaSramPtdmaCommandSource, uint32_t iPtdmaQueue, uint32_t iPtdmaCmdStart, uint32_t numPtdmaCmds, A53DeviceOpSource deviceOpSource)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::setPtdmaCommandSource
               (ControllerStaticConfiguration static_config,PtdmaVqState *aPtdmaQueue,
               uint32_t *aVaSramPtdmaCommandSource,uint32_t iPtdmaQueue,uint32_t iPtdmaCmdStart,
               uint32_t numPtdmaCmds,A53DeviceOpSource deviceOpSource)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  int iVar5;
  
  uVar2 = aVaSramPtdmaCommandSource[iPtdmaQueue];
  uVar3 = iPtdmaCmdStart << 2;
  if (1 < numPtdmaCmds) {
    uVar4 = 0xdfffffff;
    uVar1 = aPtdmaQueue[iPtdmaQueue].m_submit.m_maskVqdPointer;
    if (((uint)deviceOpSource.field_0 & 0x40000000) != 0) {
      uVar4 = 0xfdffffff;
    }
    iVar5 = -numPtdmaCmds;
    while (iVar5 = iVar5 + 1, iVar5 != 0) {
      *(uint *)((ulong)uVar2 + (ulong)uVar3) = uVar4 & (uint)deviceOpSource.field_0;
      uVar3 = uVar3 + 4 & uVar1 >> 3 & 0x1ffffffc;
    }
  }
  ((anon_union_4_6_0514bd10_for_A53DeviceOpSource_0 *)((ulong)uVar2 + (ulong)uVar3))->field_0 =
       (anon_struct_4_2_f2ff4ae4_for_anon_union_4_6_0514bd10_for_A53DeviceOpSource_0_0)
       deviceOpSource.field_0;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605ce40
 * symbol: clearPtdmaCommandSource
 * prototype: bool clearPtdmaCommandSource(ControllerStaticConfiguration static_config, PtdmaVqState * aPtdmaQueue, uint32_t * aVaSramPtdmaCommandSource, uint32_t iPtdmaQueue, uint32_t iPtdmaCmdStart, uint32_t numPtdmaCmds)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::clearPtdmaCommandSource
               (ControllerStaticConfiguration static_config,PtdmaVqState *aPtdmaQueue,
               uint32_t *aVaSramPtdmaCommandSource,uint32_t iPtdmaQueue,uint32_t iPtdmaCmdStart,
               uint32_t numPtdmaCmds)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  
  uVar2 = aVaSramPtdmaCommandSource[iPtdmaQueue];
  uVar3 = iPtdmaCmdStart << 2;
  uVar1 = aPtdmaQueue[iPtdmaQueue].m_submit.m_maskVqdPointer;
  for (; numPtdmaCmds != 0; numPtdmaCmds = numPtdmaCmds - 1) {
    *(undefined4 *)((ulong)uVar2 + (ulong)uVar3) = 0;
    uVar3 = uVar3 + 4 & uVar1 >> 3 & 0x1ffffffc;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605ce7c
 * symbol: issuePtdmaWrite
 * prototype: IssuePtdmaWriteResult issuePtdmaWrite(ControllerStaticConfiguration static_config, ControllerRuntimeConfiguration * runtime_config, PtdmaVqState * aPtdmaQueue, uint32_t * aVaSramPtdmaCommandSource, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t len, uint64_t vaSramSrc, uint64_t sysvaDst, uint16_t pasid, A53DeviceOpSource source)
 * body addresses: 516
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


IssuePtdmaWriteResult
A53::issuePtdmaWrite
          (ControllerStaticConfiguration static_config,
          ControllerRuntimeConfiguration *runtime_config,PtdmaVqState *aPtdmaQueue,
          uint32_t *aVaSramPtdmaCommandSource,PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,
          void *pCallbackContext,uint32_t len,uint64_t vaSramSrc,uint64_t sysvaDst,uint16_t pasid,
          A53DeviceOpSource source)

{
  PtdmaVqSubmitState *submit;
  uint len_00;
  anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0 aVar1;
  anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0 static_config_00;
  IssuePtdmaWriteResult IVar2;
  DmaWaitOnCompletion eWoC;
  uint uVar3;
  ulong uVar4;
  uint numPtdmaCmds;
  uint uVar5;
  
  IVar2 = kIssuePtdmaWriteResultErrorInvalidArgs;
  if ((((sysvaDst & 0xffff000000000000) == 0x1000000000000) && ((int)source.field_0 < 0)) &&
     (((uint)source.field_0 >> 0x1e & 1) != 0)) {
    numPtdmaCmds = 1;
    if ((0x100 < len) && (numPtdmaCmds = 1, (len & 0xff) != 0)) {
      numPtdmaCmds = 2;
    }
    if (aPtdmaQueue[1].m_submit.m_numCommandsUntilDone < numPtdmaCmds) {
      IVar2 = kIssuePtdmaWriteResultWaitForPtdmaWriteQueueSpace;
    }
    else {
      submit = &aPtdmaQueue[1].m_submit;
      eWoC = len;
      if (((aPtdmaQueue[1].m_tail_lo + 0x20) - aPtdmaQueue[1].m_head_lo &
          aPtdmaQueue[1].m_submit.m_maskVqdPointer) == 0) {
        uVar3 = (uint)aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
        uVar4 = 0;
        if (uVar3 != 0) {
          uVar4 = (ulong)(uint)(1 << (ulong)(uVar3 - 5 & 0x1f)) << 0x20;
        }
        spinWaitForPtdmaWriteSpace
                  (aPtdmaQueue + 1,
                   (A53_PtdmaCommandSourceTracker)(uVar4 | aVaSramPtdmaCommandSource[1]),
                   pfnDmaCmdCompletedCallback,pCallbackContext);
      }
      for (uVar4 = vaSramSrc & 0xffffffffffffffc0;
          uVar4 < (vaSramSrc + len + 0x3f & 0xffffffffffffffc0); uVar4 = uVar4 + 0x40) {
        DC_CVAC(uVar4);
      }
      uVar4 = vaSramSrc & 0xfffff;
      DataSynchronizationBarrier(3,3);
      uVar3 = (uint)sysvaDst;
      uVar5 = (uint)vaSramSrc;
      if ((len < 0x101) || ((len & 0xff) == 0)) {
        static_config_00.asU32 =
             ptdmaPutCommandCopy(submit,len,uVar4,sysvaDst,pasid,
                                 (uint)(len < 0x101 && ((len | uVar5 | uVar3) & 7) == 0),eWoC);
        aVar1.asU32 = static_config_00.asU32;
      }
      else {
        len_00 = len & 0xffffff00;
        aVar1.asU32 = ptdmaPutCommandCopy(submit,len_00,uVar4,sysvaDst,pasid,
                                          (uint)(len_00 < 0x101 && ((uVar3 | uVar5) & 7) == 0),eWoC)
        ;
        static_config_00.asU32 =
             ptdmaPutCommandCopy(submit,len & 0xff,uVar4 + len_00,len_00 + sysvaDst,pasid,
                                 (uint)(((len | uVar5 | uVar3) & 7) == 0),eWoC);
      }
      setPtdmaCommandSource
                ((ControllerStaticConfiguration)static_config_00,aPtdmaQueue,
                 aVaSramPtdmaCommandSource,1,aVar1.asU32 >> 5,numPtdmaCmds,source);
      IVar2 = kIssuePtdmaWriteResultSuccess;
      aPtdmaQueue[1].m_submit.m_numCommandsUntilDone =
           aPtdmaQueue[1].m_submit.m_numCommandsUntilDone - (short)numPtdmaCmds;
    }
  }
  return IVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d100
 * symbol: markPtdmaReadCacheElemsInUse
 * prototype: bool markPtdmaReadCacheElemsInUse(uint32_t * amaskPtdmaReadCacheElemsInUse, uint32_t numPtdmaReadCacheElems, uint32_t ptdmaReadCacheIdx, uint32_t numElemsToAlloc)
 * body addresses: 200
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::markPtdmaReadCacheElemsInUse
               (uint32_t *amaskPtdmaReadCacheElemsInUse,uint32_t numPtdmaReadCacheElems,
               uint32_t ptdmaReadCacheIdx,uint32_t numElemsToAlloc)

{
  uint uVar1;
  uint uVar2;
  ulong uVar3;
  uint uVar4;
  uint uVar5;
  
  uVar2 = (ptdmaReadCacheIdx + numElemsToAlloc) - 1;
  uVar4 = uVar2 >> 5;
  uVar3 = (ulong)(ptdmaReadCacheIdx >> 5);
  uVar5 = -1 << (ulong)(ptdmaReadCacheIdx & 0x1f);
  uVar2 = -2 << (ulong)(uVar2 & 0x1f);
  if (uVar4 == ptdmaReadCacheIdx >> 5) {
    uVar4 = amaskPtdmaReadCacheElemsInUse[uVar3];
    uVar2 = uVar5 & (uVar2 ^ 0xffffffff);
    if ((uVar4 & uVar2) == 0) {
LAB_0605d1b8:
      amaskPtdmaReadCacheElemsInUse[uVar3] = uVar4 | uVar2;
      return true;
    }
  }
  else if ((amaskPtdmaReadCacheElemsInUse[uVar3] & uVar5) == 0) {
    amaskPtdmaReadCacheElemsInUse[uVar3] = amaskPtdmaReadCacheElemsInUse[uVar3] | uVar5;
    for (uVar5 = 1; uVar1 = (int)uVar3 + 1, uVar5 < uVar4 - (ptdmaReadCacheIdx >> 5);
        uVar5 = uVar5 + 1) {
      if (numPtdmaReadCacheElems >> 5 <= uVar1) {
        uVar1 = 0;
      }
      uVar3 = (ulong)uVar1;
      if (amaskPtdmaReadCacheElemsInUse[uVar3] != 0) {
        return false;
      }
      amaskPtdmaReadCacheElemsInUse[uVar3] = 0xffffffff;
    }
    uVar3 = (ulong)uVar1;
    if (numPtdmaReadCacheElems >> 5 <= uVar1) {
      uVar3 = 0;
    }
    uVar4 = amaskPtdmaReadCacheElemsInUse[uVar3];
    if ((uVar4 & (uVar2 ^ 0xffffffff)) == 0) {
      uVar2 = ~uVar2;
      goto LAB_0605d1b8;
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d1c8
 * symbol: markPtdmaReadCacheElemsFree
 * prototype: bool markPtdmaReadCacheElemsFree(uint32_t * amaskPtdmaReadCacheElemsInUse, uint32_t numPtdmaReadCacheElems, uint32_t ptdmaReadCacheIdx, uint32_t numElemsToAlloc)
 * body addresses: 208
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::markPtdmaReadCacheElemsFree
               (uint32_t *amaskPtdmaReadCacheElemsInUse,uint32_t numPtdmaReadCacheElems,
               uint32_t ptdmaReadCacheIdx,uint32_t numElemsToAlloc)

{
  uint uVar1;
  uint uVar2;
  ulong uVar3;
  uint uVar4;
  uint uVar5;
  
  uVar4 = (ptdmaReadCacheIdx + numElemsToAlloc) - 1;
  uVar2 = uVar4 >> 5;
  uVar5 = -1 << (ulong)(ptdmaReadCacheIdx & 0x1f);
  uVar3 = (ulong)(ptdmaReadCacheIdx >> 5);
  uVar4 = -2 << (ulong)(uVar4 & 0x1f);
  if (uVar2 == ptdmaReadCacheIdx >> 5) {
    uVar5 = uVar5 & (uVar4 ^ 0xffffffff);
    if ((uVar5 & (amaskPtdmaReadCacheElemsInUse[uVar3] ^ 0xffffffff)) == 0) {
      uVar4 = amaskPtdmaReadCacheElemsInUse[uVar3] & (uVar5 ^ 0xffffffff);
LAB_0605d280:
      amaskPtdmaReadCacheElemsInUse[uVar3] = uVar4;
      return true;
    }
  }
  else if ((uVar5 & (amaskPtdmaReadCacheElemsInUse[uVar3] ^ 0xffffffff)) == 0) {
    amaskPtdmaReadCacheElemsInUse[uVar3] =
         amaskPtdmaReadCacheElemsInUse[uVar3] & (uVar5 ^ 0xffffffff);
    for (uVar5 = 1; uVar1 = (int)uVar3 + 1, uVar5 < uVar2 - (ptdmaReadCacheIdx >> 5);
        uVar5 = uVar5 + 1) {
      if (numPtdmaReadCacheElems >> 5 <= uVar1) {
        uVar1 = 0;
      }
      uVar3 = (ulong)uVar1;
      if (amaskPtdmaReadCacheElemsInUse[uVar3] != 0xffffffff) {
        return false;
      }
      amaskPtdmaReadCacheElemsInUse[uVar3] = 0;
    }
    uVar3 = (ulong)uVar1;
    if (numPtdmaReadCacheElems >> 5 <= uVar1) {
      uVar3 = 0;
    }
    if ((~amaskPtdmaReadCacheElemsInUse[uVar3] & (uVar4 ^ 0xffffffff)) == 0) {
      uVar4 = amaskPtdmaReadCacheElemsInUse[uVar3] & uVar4;
      goto LAB_0605d280;
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d298
 * symbol: getNumPtdmaReadCacheElemsFreeFromHead
 * prototype: uint32_t getNumPtdmaReadCacheElemsFreeFromHead(uint32_t * amaskPtdmaReadCacheElemsInUse, uint32_t numPtdmaReadCacheElems, uint32_t ptdmaReadCacheIdx_head)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::getNumPtdmaReadCacheElemsFreeFromHead
                   (uint32_t *amaskPtdmaReadCacheElemsInUse,uint32_t numPtdmaReadCacheElems,
                   uint32_t ptdmaReadCacheIdx_head)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  ulong uVar4;
  
  uVar4 = (ulong)(ptdmaReadCacheIdx_head >> 5);
  uVar3 = amaskPtdmaReadCacheElemsInUse[uVar4] >> (ulong)(ptdmaReadCacheIdx_head & 0x1f);
  if ((uVar3 & 1) != 0) {
    return 0;
  }
  if (uVar3 != 0) {
    uVar3 = (uVar3 & 0xaaaaaaaa) >> 1 | (uVar3 & 0x55555555) << 1;
    uVar3 = (uVar3 & 0xcccccccc) >> 2 | (uVar3 & 0x33333333) << 2;
    uVar3 = (uVar3 & 0xf0f0f0f0) >> 4 | (uVar3 & 0xf0f0f0f) << 4;
    uVar3 = (uVar3 & 0xff00ff00) >> 8 | (uVar3 & 0xff00ff) << 8;
    return (uint32_t)LZCOUNT(uVar3 >> 0x10 | uVar3 << 0x10);
  }
  uVar3 = 0x20 - (ptdmaReadCacheIdx_head & 0x1f);
  while( true ) {
    uVar1 = 0;
    if ((int)uVar4 + 1U < numPtdmaReadCacheElems >> 5) {
      uVar1 = (int)uVar4 + 1;
    }
    uVar4 = (ulong)uVar1;
    uVar2 = amaskPtdmaReadCacheElemsInUse[uVar4];
    if (uVar2 != 0) break;
    uVar3 = uVar3 + 0x20;
    if (uVar1 == ptdmaReadCacheIdx_head >> 5) {
LAB_0605d304:
      if (uVar3 <= numPtdmaReadCacheElems) {
        numPtdmaReadCacheElems = uVar3;
      }
      return numPtdmaReadCacheElems;
    }
  }
  uVar1 = (uVar2 & 0xaaaaaaaa) >> 1 | (uVar2 & 0x55555555) << 1;
  uVar1 = (uVar1 & 0xcccccccc) >> 2 | (uVar1 & 0x33333333) << 2;
  uVar1 = (uVar1 & 0xf0f0f0f0) >> 4 | (uVar1 & 0xf0f0f0f) << 4;
  uVar1 = (uVar1 & 0xff00ff00) >> 8 | (uVar1 & 0xff00ff) << 8;
  uVar3 = (int)LZCOUNT(uVar1 >> 0x10 | uVar1 << 0x10) + uVar3;
  goto LAB_0605d304;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d310
 * symbol: issuePtdmaRead
 * prototype: IssuePtdmaReadResult issuePtdmaRead(ControllerStaticConfiguration static_config, ControllerRuntimeConfiguration * runtime_config, PtdmaVqState * aPtdmaQueue, uint32_t * aVaSramPtdmaCommandSource, SramRing * sramRing_PtdmaReadCache, uint32_t * amaskPtdmaReadCacheElemsInUse, uint32_t len, uint64_t sysvaSrc, uint16_t pasid, A53DeviceOpSource source, uint32_t * out_ptdmaReadCacheIdx)
 * body addresses: 764
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


IssuePtdmaReadResult
A53::issuePtdmaRead(ControllerStaticConfiguration static_config,
                   ControllerRuntimeConfiguration *runtime_config,PtdmaVqState *aPtdmaQueue,
                   uint32_t *aVaSramPtdmaCommandSource,SramRing *sramRing_PtdmaReadCache,
                   uint32_t *amaskPtdmaReadCacheElemsInUse,uint32_t len,uint64_t sysvaSrc,
                   uint16_t pasid,A53DeviceOpSource source,uint32_t *out_ptdmaReadCacheIdx)

{
  uint numPtdmaCmds;
  ulong uVar1;
  uint uVar2;
  uint len_00;
  bool bVar3;
  bool bVar4;
  uint16_t uVar5;
  uint32_t uVar6;
  int iVar7;
  anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0 aVar8;
  anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0 static_config_00;
  IssuePtdmaReadResult IVar9;
  uint len_01;
  uint64_t paSrc;
  uint uVar10;
  uint64_t paDst;
  ulong paDst_00;
  
  IVar9 = kIssuePtdmaReadResultErrorInvalidArgs;
  if (((int)source.field_0 < 0) && (((uint)source.field_0 >> 0x1e & 1) != 0)) {
    if ((sysvaSrc >> 0x30 == 1) || ((sysvaSrc >> 0x1a != 0 && (sysvaSrc + len < 0xfc000001)))) {
      uVar10 = len + 7 >> 3;
      if ((*(ushort *)
            ((long)&(sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.field_0 +
            4) + 1) -
          ((sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.field_0.asU32[2] &
          0x1ffff) < uVar10) {
        IVar9 = kIssuePtdmaReadResultWaitForPtdmaReadCacheSpace;
      }
      else {
        uVar6 = SramRing::getNumRingElemsFromTailToWrap(sramRing_PtdmaReadCache);
        bVar3 = uVar10 < uVar6;
        bVar4 = uVar10 - uVar6 == 0;
        uVar2 = uVar6;
        if (bVar3 || bVar4) {
          uVar2 = uVar10;
        }
        len_01 = (uVar10 - uVar6) * 8;
        IVar9 = kIssuePtdmaReadResultWaitForPtdmaReadQueueSpace;
        if (bVar3 || bVar4) {
          len_01 = 0;
        }
        iVar7 = 1;
        if (!bVar3 && !bVar4) {
          iVar7 = 2;
        }
        numPtdmaCmds = iVar7 + (uint)(0x20 < uVar2 && (uVar2 & 0x1f) != 0) +
                       (uint)(0x100 < len_01 && (len_01 & 0xf8) != 0);
        if (numPtdmaCmds <= (aPtdmaQueue->m_submit).m_numCommandsAvailable) {
          len_00 = uVar2 << 3;
          uVar5 = ConstSramRingView::getElementIndexTail
                            ((ConstSramRingView *)sramRing_PtdmaReadCache);
          SramRing::pushElements(sramRing_PtdmaReadCache,uVar10);
          markPtdmaReadCacheElemsInUse
                    (amaskPtdmaReadCacheElemsInUse,
                     *(ushort *)
                      ((long)&(sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.
                              field_0 + 4) + 1,(uint)uVar5,uVar10);
          uVar1 = ((ulong)uVar5 <<
                  (*(byte *)((long)&(sramRing_PtdmaReadCache->super_SramRingView).
                                    super_ConstSramRingView.field_0 + 0xb) & 0xf)) +
                  (ulong)(sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.
                         field_0.field_0.m_vaSramRing;
          paDst_00 = uVar1 & 0xfffff;
          uVar10 = (uint)uVar1;
          if ((uVar2 < 0x21) || ((len_00 & 0xf8) == 0)) {
            static_config_00.asU32 =
                 ptdmaPutCommandCopy(&aPtdmaQueue->m_submit,len_00,sysvaSrc,paDst_00,pasid,
                                     (uint)(uVar2 < 0x21 && ((uVar10 | (uint)sysvaSrc) & 7) == 0),
                                     len);
            aVar8.asU32 = static_config_00.asU32;
          }
          else {
            uVar2 = len_00 & 0xffffff00;
            bVar3 = ((uVar10 | (uint)sysvaSrc) & 7) == 0;
            aVar8.asU32 = ptdmaPutCommandCopy(&aPtdmaQueue->m_submit,uVar2,sysvaSrc,paDst_00,pasid,
                                              (uint)(uVar2 < 0x101 && bVar3),len);
            static_config_00.asU32 =
                 ptdmaPutCommandCopy(&aPtdmaQueue->m_submit,len_00 & 0xf8,uVar2 + sysvaSrc,
                                     paDst_00 + uVar2,pasid,(uint)bVar3,len);
          }
          if (len_01 != 0) {
            paSrc = sysvaSrc + len_00;
            paDst = (ulong)(sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.
                           field_0.field_0.m_vaSramRing & 0xfffff;
            if (((len_01 & 0xf8) == 0) || (len_01 < 0x101)) {
              bVar3 = len_01 < 0x101 && (((uint)paSrc | (uint)paDst) & 7) == 0;
            }
            else {
              uVar10 = len_01 & 0xffffff00;
              bVar3 = (((uint)paSrc | (uint)paDst) & 7) == 0;
              ptdmaPutCommandCopy(&aPtdmaQueue->m_submit,uVar10,paSrc,paDst,pasid,
                                  (uint)(uVar10 < 0x101 && bVar3),len);
              paSrc = paSrc + uVar10;
              paDst = paDst + uVar10;
              len_01 = len_01 & 0xf8;
            }
            static_config_00.asU32 =
                 ptdmaPutCommandCopy(&aPtdmaQueue->m_submit,len_01,paSrc,paDst,pasid,(uint)bVar3,len
                                    );
          }
          setPtdmaCommandSource
                    ((ControllerStaticConfiguration)static_config_00,aPtdmaQueue,
                     aVaSramPtdmaCommandSource,0,aVar8.asU32 >> 5,numPtdmaCmds,source);
          IVar9 = kIssuePtdmaReadResultSuccess;
          *out_ptdmaReadCacheIdx = (uint)uVar5;
        }
      }
    }
    else {
      IVar9 = kIssuePtdmaReadResultErrorInvalidArgs;
    }
  }
  return IVar9;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d60c
 * symbol: getNumRingElemsFromTailToWrap
 * prototype: uint32_t getNumRingElemsFromTailToWrap(SramRing * this)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumRingElemsFromTailToWrap(SramRing * this) */

uint32_t __thiscall A53::SramRing::getNumRingElemsFromTailToWrap(SramRing *this)

{
  ushort uVar1;
  uint16_t uVar2;
  
  uVar1 = *(ushort *)((long)&(this->super_SramRingView).super_ConstSramRingView.field_0 + 4);
  uVar2 = ConstSramRingView::getElementIndexTail((ConstSramRingView *)this);
  return (uVar1 + 1) - (uint)uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d634
 * symbol: releasePtdmaRead
 * prototype: bool releasePtdmaRead(SramRing * sramRing_PtdmaReadCache, uint32_t * amaskPtdmaReadCacheElemsInUse, uint32_t len, uint32_t ptdmaReadCacheIdx)
 * body addresses: 172
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::releasePtdmaRead
               (SramRing *sramRing_PtdmaReadCache,uint32_t *amaskPtdmaReadCacheElemsInUse,
               uint32_t len,uint32_t ptdmaReadCacheIdx)

{
  uint32_t uVar1;
  uint uVar2;
  bool bVar3;
  uint32_t uVar4;
  ulong uVar5;
  
  uVar1 = *(ushort *)
           ((long)&(sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.field_0 + 4
           ) + 1;
  bVar3 = markPtdmaReadCacheElemsFree
                    (amaskPtdmaReadCacheElemsInUse,uVar1,ptdmaReadCacheIdx,len + 7 >> 3);
  uVar5 = *(ulong *)((long)&(sramRing_PtdmaReadCache->super_SramRingView).super_ConstSramRingView.
                            field_0 + 4);
  uVar2 = 0xffff;
  if ((uVar5 & 0xf8000000000000) != 0) {
    uVar2 = (uint)uVar5;
  }
  if ((bVar3) && ((uVar2 & (uint)uVar5 >> 0x10) == ptdmaReadCacheIdx)) {
    uVar4 = getNumPtdmaReadCacheElemsFreeFromHead
                      (amaskPtdmaReadCacheElemsInUse,uVar1,ptdmaReadCacheIdx);
    uVar1 = (uint)(uVar5 >> 0x20) & 0x1ffff;
    if (uVar4 <= uVar1) {
      uVar1 = uVar4;
    }
    bVar3 = SramRing::popElements(sramRing_PtdmaReadCache,uVar1);
    return bVar3;
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d6e0
 * symbol: clearDvmGcrCommandSource
 * prototype: bool clearDvmGcrCommandSource(ControllerPipelineDvmState * dvmGcrState, uint32_t dvmGcrIdx, uint32_t numDvmGcrIdx)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::clearDvmGcrCommandSource
               (ControllerPipelineDvmState *dvmGcrState,uint32_t dvmGcrIdx,uint32_t numDvmGcrIdx)

{
  uint uVar1;
  ulong uVar2;
  uint uVar3;
  
  uVar2 = *(ulong *)dvmGcrState;
  uVar1 = dvmGcrState->m_vaSramRw;
  uVar3 = dvmGcrIdx << 2;
  for (; numDvmGcrIdx != 0; numDvmGcrIdx = numDvmGcrIdx - 1) {
    *(undefined4 *)((ulong)uVar1 + 0x10 + (ulong)uVar3) = 0;
    uVar3 = uVar3 + 4 & (int)(8L << (uVar2 >> 0x15 & 7)) - 1U;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d724
 * symbol: fakeSubmitDvmGcrForMapper
 * prototype: SubmitDvmGcrResult fakeSubmitDvmGcrForMapper(ControllerStaticConfiguration static_config, ControllerPipelineDvmState * dvmGcrState, uint64_t sysvaBase, uint64_t sysvaLimit, DvmFifoCtrlGcr control, A53DeviceOpSource deviceOpSource, uint32_t iCommandRing)
 * body addresses: 340
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

SubmitDvmGcrResult
A53::fakeSubmitDvmGcrForMapper
          (ControllerStaticConfiguration static_config,ControllerPipelineDvmState *dvmGcrState,
          uint64_t sysvaBase,uint64_t sysvaLimit,DvmFifoCtrlGcr control,
          A53DeviceOpSource deviceOpSource,uint32_t iCommandRing)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  bool bVar4;
  SubmitDvmGcrResult SVar5;
  uint uVar6;
  ulong uVar7;
  
  bVar4 = (sysvaLimit | sysvaBase) != 0;
  if ((sysvaLimit <= sysvaBase ||
       ((sysvaBase & 0xffff00000000007f) != 0x1000000000000 ||
       (sysvaLimit & 0xffff00000000007f) != 0x1000000000000)) && (bVar4 || control.field_0 != 0)) {
    return kSubmitDvmGcrResultErrorInvalidArgs;
  }
  SVar5 = kSubmitDvmGcrResultErrorInvalidArgs;
  if (((int)deviceOpSource.field_0 < 0) && (((uint)deviceOpSource.field_0 >> 0x1e & 1) != 0)) {
    SVar5 = kSubmitDvmGcrResultErrorInvalidArgs;
    if ((((uint)deviceOpSource.field_0 & 0x30000000) != 0) &&
       ((bVar4 || control.field_0 != 0) || ((uint)deviceOpSource.field_0 & 0x2000000) != 0)) {
      uVar7 = *(ulong *)dvmGcrState;
      uVar1 = (uint)deviceOpSource.field_0 & 0x3e00000;
      uVar6 = (uint)uVar7;
      iVar3 = 2 << (ulong)(uVar6 >> 0x15 & 7);
      if (((uint)deviceOpSource.field_0 >> 0x19 & 1) == 0) {
        uVar2 = (uint)(uVar7 >> 0x20) & 0xff;
        if (uVar1 != 0x1e00000) {
          uVar2 = uVar2 + 1;
        }
        bVar4 = (uint)(iVar3 * 3) >> 2 <= uVar2;
      }
      else {
        bVar4 = true;
      }
      if (uVar1 != 0x1e00000) {
        uVar2 = (uint)(uVar7 >> 8) & 0xffffff;
        if ((~uVar6 & 0xe00000) == 0) {
          uVar2 = uVar2 + 1;
        }
        if (((uVar2 + iVar3 ^ uVar6) & 0xff) == 0) {
          return kSubmitDvmGcrResultWaitForDvmGcrDeviceOpSourceSpace;
        }
      }
      if (bVar4) {
        _DAT_02060010 = _DAT_02060010 + 1;
        uVar7 = *(ulong *)dvmGcrState & 0xffffff00ffffffff;
        *(ulong *)dvmGcrState = uVar7;
      }
      if (uVar1 == 0x1e00000) {
        return kSubmitDvmGcrResultSuccess;
      }
      SVar5 = kSubmitDvmGcrResultSuccess;
      ((anon_union_4_6_0514bd10_for_A53DeviceOpSource_0 *)
      ((ulong)((iVar3 + 0xffU & (uint)uVar7 & 0xff) << 2) + (ulong)dvmGcrState->m_vaSramRw + 0x10))
      ->field_0 = (anon_struct_4_2_f2ff4ae4_for_anon_union_4_6_0514bd10_for_A53DeviceOpSource_0_0)
                  deviceOpSource.field_0;
      *(char *)dvmGcrState = (char)*(undefined4 *)dvmGcrState + '\x01';
    }
  }
  return SVar5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d878
 * symbol: submitDvmGcr
 * prototype: SubmitDvmGcrResult submitDvmGcr(ControllerStaticConfiguration static_config, ControllerPipelineDvmState * dvmGcrState, uint64_t sysvaBase, uint64_t sysvaLimit, DvmFifoCtrlGcr control, A53DeviceOpSource deviceOpSource, uint32_t iCommandRing)
 * body addresses: 672
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

SubmitDvmGcrResult
A53::submitDvmGcr(ControllerStaticConfiguration static_config,
                 ControllerPipelineDvmState *dvmGcrState,uint64_t sysvaBase,uint64_t sysvaLimit,
                 DvmFifoCtrlGcr control,A53DeviceOpSource deviceOpSource,uint32_t iCommandRing)

{
  uint uVar1;
  uint uVar2;
  uint *puVar3;
  ulong *puVar4;
  ulong *puVar5;
  int iVar6;
  uint uVar7;
  anon_union_4_2_653be89a_for_DvmFifoCtrlGcr_0 *paVar8;
  bool bVar9;
  bool bVar10;
  uint uVar11;
  uint uVar12;
  uint uVar13;
  ulong uVar14;
  uint uVar15;
  
  bVar9 = (sysvaLimit | sysvaBase) == 0;
  bVar10 = control.field_0 == 0;
  if ((sysvaLimit <= sysvaBase ||
       ((sysvaBase & 0xffff00000000007f) != 0x1000000000000 ||
       (sysvaLimit & 0xffff00000000007f) != 0x1000000000000)) && (!bVar9 || !bVar10)) {
    return kSubmitDvmGcrResultErrorInvalidArgs;
  }
  if (-1 < (int)deviceOpSource.field_0) {
    return kSubmitDvmGcrResultErrorInvalidArgs;
  }
  if (((uint)deviceOpSource.field_0 >> 0x1e & 1) == 0) {
    return kSubmitDvmGcrResultErrorInvalidArgs;
  }
  if (((uint)deviceOpSource.field_0 & 0x30000000) == 0) {
    return kSubmitDvmGcrResultErrorInvalidArgs;
  }
  if ((bVar9 && bVar10) && ((uint)deviceOpSource.field_0 & 0x2000000) == 0) {
    return kSubmitDvmGcrResultErrorInvalidArgs;
  }
  uVar14 = *(ulong *)dvmGcrState;
  uVar2 = (uint)deviceOpSource.field_0 & 0x3e00000;
  uVar13 = (uint)uVar14;
  iVar6 = 2 << (ulong)(uVar13 >> 0x15 & 7);
  if (((uint)deviceOpSource.field_0 >> 0x19 & 1) == 0) {
    uVar15 = (uint)(uVar14 >> 0x20) & 0xff;
    if (uVar2 != 0x1e00000) {
      uVar15 = uVar15 + 1;
    }
    uVar15 = (uint)((uint)(iVar6 * 3) >> 2 <= uVar15);
  }
  else {
    uVar15 = 1;
  }
  uVar1 = uVar15 + ((sysvaLimit | sysvaBase) != 0 || control.field_0 != 0);
  if (((uint)(uVar14 >> 0x18) & 0xff) < uVar1) {
    return kSubmitDvmGcrResultWaitForDvmFifoSpace;
  }
  if (uVar2 != 0x1e00000) {
    uVar12 = (uint)(uVar14 >> 8) & 0xffffff;
    if ((~uVar13 & 0xe00000) == 0) {
      uVar12 = uVar12 + 1;
    }
    if (((uVar12 + iVar6 ^ uVar13) & 0xff) == 0) {
      return kSubmitDvmGcrResultWaitForDvmGcrDeviceOpSourceSpace;
    }
  }
  puVar3 = (uint *)&DAT_022902e0;
  if (((uint)static_config.field_0 & 0x4000000) == 0) {
    puVar3 = (uint *)&DAT_022902c0;
  }
  uVar12 = *puVar3 & 0x3fffffff;
  if (0xfffffc0 < uVar12 - 0x40) {
    return kSubmitDvmGcrResultErrorInvalidSdmaConfiguration;
  }
  uVar7 = uVar12 - 1;
  if ((uVar7 & uVar12) != 0) {
    return kSubmitDvmGcrResultErrorInvalidSdmaConfiguration;
  }
  uVar12 = 0;
  if (!bVar9 || !bVar10) {
    uVar12 = 5;
  }
  uVar11 = 10;
  if (uVar15 == 0) {
    uVar11 = 0;
  }
  if (((dvmGcrState->m_sdma_head - 1) - dvmGcrState->m_sdma_allocated & uVar7) < (uVar11 | uVar12))
  {
    if ((uVar13 >> 0x10 & 1) != 0) {
      return kSubmitDvmGcrResultWaitForSdmaSpace;
    }
    *(ulong *)dvmGcrState = uVar14 | 0x40000;
    return kSubmitDvmGcrResultWaitForSdmaSpace;
  }
  if (!bVar9 || !bVar10) {
    bVar9 = ((uint)static_config.field_0 & 0x4000000) == 0;
    puVar4 = (ulong *)0x2290120;
    if (bVar9) {
      puVar4 = (ulong *)0x22900e0;
    }
    puVar5 = (ulong *)0x2290128;
    paVar8 = (anon_union_4_2_653be89a_for_DvmFifoCtrlGcr_0 *)0x2290118;
    if (bVar9) {
      puVar5 = (ulong *)0x22900e8;
      paVar8 = (anon_union_4_2_653be89a_for_DvmFifoCtrlGcr_0 *)0x22900d8;
    }
    paVar8->field_0 =
         (anon_struct_4_16_c30240e9_for_anon_union_4_2_653be89a_for_DvmFifoCtrlGcr_0_0)
         control.field_0;
    *puVar4 = sysvaBase & 0xffffffffff80;
    *puVar5 = sysvaLimit & 0xffffffffff80;
  }
  if (uVar15 == 0) {
    uVar14 = *(ulong *)dvmGcrState;
    if (uVar2 == 0x1e00000) goto LAB_0605daac;
    uVar14 = uVar14 & 0xffffff0000000000 |
             uVar14 & 0xffffffff | (uVar14 + 0x100000000 >> 0x20 & 0xff) << 0x20;
  }
  else {
    if (((uint)static_config.field_0 >> 0x1a & 1) == 0) {
      _DAT_022900f8 = 0x203000000000ffff;
    }
    else {
      _DAT_02290130 = 0x203000000000ffff;
    }
    uVar14 = *(ulong *)dvmGcrState & 0xffffff00ffffffff;
  }
  *(ulong *)dvmGcrState = uVar14;
LAB_0605daac:
  dvmGcrState->m_sdma_allocated = dvmGcrState->m_sdma_allocated + (uVar11 | uVar12) & uVar7;
  *(ulong *)dvmGcrState =
       uVar14 & 0xffffffff00ffffff | (ulong)((((uint)(uVar14 >> 0x18) & 0xff) - uVar1) * 0x1000000);
  if (uVar2 != 0x1e00000) {
    ((anon_union_4_6_0514bd10_for_A53DeviceOpSource_0 *)
    ((ulong)dvmGcrState->m_vaSramRw + (ulong)((iVar6 + 0xffU & (uint)uVar14 & 0xff) << 2) + 0x10))->
    field_0 = (anon_struct_4_2_f2ff4ae4_for_anon_union_4_6_0514bd10_for_A53DeviceOpSource_0_0)
              deviceOpSource.field_0;
    *(char *)dvmGcrState = (char)*(undefined4 *)dvmGcrState + '\x01';
  }
  return kSubmitDvmGcrResultSuccess;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605db18
 * symbol: executeDvmDma
 * prototype: void executeDvmDma(ControllerStaticConfiguration static_config, ControllerRuntimeConfiguration * runtime_config, ControllerPipelineDvmState * dvmGcrState, PtdmaVqState * ptdmaQueueRead, A53_PtdmaCommandSourceTracker * ptdmaSourceTrackerRead, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker * ptdmaSourceTrackerWrite)
 * body addresses: 864
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void A53::executeDvmDma(ControllerStaticConfiguration static_config,
                       ControllerRuntimeConfiguration *runtime_config,
                       ControllerPipelineDvmState *dvmGcrState,PtdmaVqState *ptdmaQueueRead,
                       A53_PtdmaCommandSourceTracker *ptdmaSourceTrackerRead,
                       PtdmaVqState *ptdmaQueueWrite,
                       A53_PtdmaCommandSourceTracker *ptdmaSourceTrackerWrite)

{
  ulong paDst;
  uint *puVar1;
  uint uVar2;
  uint uVar3;
  uint64_t uVar4;
  uint32_t uVar5;
  DmaWaitOnCompletion eWoC;
  uint uVar6;
  ulong uVar7;
  int iVar8;
  uint uVar9;
  ulong *puVar10;
  ulong paSrc;
  uint64_t local_68;
  
  eWoC = (DmaWaitOnCompletion)ptdmaSourceTrackerWrite;
  uVar5 = dvmGcrState->m_sdma_head;
  if ((uVar5 != dvmGcrState->m_sdma_allocated) || ((dvmGcrState->field_0x2 & 0xc) != 0)) {
    uVar2 = (uint)static_config.field_0 >> 0x1a;
    uVar6 = _DAT_022902c0;
    uVar9 = _DAT_02290000;
    if ((uVar2 & 1) != 0) {
      uVar6 = _DAT_022902e0;
      uVar9 = _DAT_02290000 >> 8;
    }
    uVar6 = uVar6 & 0x3fffffff;
    if ((uVar6 - 0x40 < 0xfffffc1) && (uVar3 = uVar6 - 1, (uVar3 & uVar6) == 0)) {
      uVar7 = *(ulong *)dvmGcrState;
      if (((uVar9 ^ (uint)uVar7 >> 0x18) & 0xff) != 0) {
        uVar7 = uVar7 & 0xffffffff00ffffff | (ulong)(uVar9 << 0x18);
        *(ulong *)dvmGcrState = uVar7;
      }
      if ((uVar7 & 0x120000) == 0) {
        uVar6 = (uint)static_config.field_0 >> 0x1a & 1;
        puVar10 = (ulong *)(ulong)dvmGcrState->m_vaSramRw;
        puVar1 = (uint *)0x22902ec;
        if (uVar6 == 0) {
          puVar1 = (uint *)0x22902cc;
        }
        iVar8 = (int)(*puVar10 >> 2);
        if ((iVar8 - uVar5 & uVar3) < ((*puVar1 & 0x3fffffff) - uVar5 & uVar3)) {
          *puVar10 = ((ulong)((*puVar1 & 0x3fffffff) - iVar8 & uVar3) + (*puVar10 >> 2)) * 4;
          uVar7 = *(ulong *)dvmGcrState | 0x80000;
          *(ulong *)dvmGcrState = uVar7;
        }
        if ((((uint)uVar7 >> 0x13 & 1) != 0) &&
           (((ptdmaQueueWrite->m_tail_lo + 0x20) - ptdmaQueueWrite->m_head_lo &
            (ptdmaQueueWrite->m_submit).m_maskVqdPointer) != 0)) {
          local_68 = 0;
          A53Controller_BootConfiguration_KernelShared_getPaSystemMmioSdma
                    ((ulong)(runtime_config->field_0).field_0.
                            m_vaSramA53Controller_BootConfiguration,&local_68);
          uVar4 = local_68;
          uVar7 = local_68 - 0x1000000 >> 0x19;
          if ((uVar7 == 0) && ((ptdmaQueueWrite->m_submit).m_numCommandsAvailable < 2)) {
            uVar7 = *(ulong *)dvmGcrState;
          }
          else {
            paSrc = (ulong)puVar10 & 0xfffff;
            DC_CVAC((ulong)puVar10 & 0xffffffc0);
            paDst = local_68 + 8;
            if (uVar7 == 0) {
              uVar5 = ptdmaPutCommandCopy(&ptdmaQueueWrite->m_submit,4,paSrc,paDst,0xffff,
                                          kDmaFunctionDisablePrefetch,eWoC);
              uVar6 = uVar6 << 7;
              uVar9 = (ptdmaQueueRead->m_submit).m_maskVqdPointer & uVar5;
              if (uVar9 >> 5 < ptdmaSourceTrackerWrite->m_numCommands) {
                *(uint *)((ulong)ptdmaSourceTrackerWrite->m_vaSramPtdmaCommandSourceBase +
                         (ulong)(uVar9 >> 5) * 4) = uVar6 | 0x80000902;
              }
              uVar5 = ptdmaPutCommandCopy(&ptdmaQueueWrite->m_submit,4,paSrc + 4,uVar4 + 0xc,0xffff,
                                          kDmaFunctionDisablePrefetch,eWoC);
              uVar9 = (ptdmaQueueRead->m_submit).m_maskVqdPointer & uVar5;
              if (uVar9 >> 5 < ptdmaSourceTrackerWrite->m_numCommands) {
                *(uint *)((ulong)ptdmaSourceTrackerWrite->m_vaSramPtdmaCommandSourceBase +
                         (ulong)(uVar9 >> 5) * 4) = uVar6 | 0xa0000903;
              }
            }
            else {
              uVar5 = ptdmaPutCommandCopy(&ptdmaQueueWrite->m_submit,8,paSrc,paDst,0xffff,
                                          (uint)((paDst & 7) == 0),eWoC);
              uVar6 = (ptdmaQueueRead->m_submit).m_maskVqdPointer & uVar5;
              if (uVar6 >> 5 < ptdmaSourceTrackerWrite->m_numCommands) {
                *(uint *)((ulong)ptdmaSourceTrackerWrite->m_vaSramPtdmaCommandSourceBase +
                         (ulong)(uVar6 >> 5) * 4) = (uVar2 & 1) << 7 | 0xa0000902;
              }
            }
            uVar7 = *(ulong *)dvmGcrState & 0xfffffffffff7ffff | 0x20000;
            *(ulong *)dvmGcrState = uVar7;
          }
        }
      }
      if (((uVar7 & 0x50000) == 0x40000) &&
         (((ptdmaQueueRead->m_tail_lo + 0x20) - ptdmaQueueRead->m_head_lo &
          (ptdmaQueueRead->m_submit).m_maskVqdPointer) != 0)) {
        local_68 = 0;
        A53Controller_BootConfiguration_KernelShared_getPaSystemMmioSdma
                  ((ulong)(runtime_config->field_0).field_0.m_vaSramA53Controller_BootConfiguration,
                   &local_68);
        DC_CIVAC((ulong)dvmGcrState->m_vaSramReadOnly & 0xffffffc0);
        DataSynchronizationBarrier(3,3);
        uVar5 = ptdmaPutCommandCopy(&ptdmaQueueRead->m_submit,8,local_68,
                                    (ulong)(dvmGcrState->m_vaSramReadOnly & 0xfffff),0xffff,
                                    (uint)((local_68 & 7) == 0),eWoC);
        uVar6 = (ptdmaQueueRead->m_submit).m_maskVqdPointer & uVar5;
        if (uVar6 >> 5 < ptdmaSourceTrackerRead->m_numCommands) {
          *(uint *)((ulong)ptdmaSourceTrackerRead->m_vaSramPtdmaCommandSourceBase +
                   (ulong)(uVar6 >> 5) * 4) = (uVar2 & 1) << 7 | 0xa0001500;
        }
        *(ulong *)dvmGcrState = *(ulong *)dvmGcrState & 0xfffffffffffaffff | 0x10000;
      }
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605de78
 * symbol: dmaReadCmdCompleted_SdmaHead
 * prototype: void dmaReadCmdCompleted_SdmaHead(ControllerRings * rings, ControllerPipelineDvmState * dvmGcrState, PtdmaVqState * ptdmaQueueRead, InternalDmaOpSource source, uint32_t head_lo, uint32_t tail_lo)
 * body addresses: 264
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::dmaReadCmdCompleted_SdmaHead
               (ControllerRings *rings,ControllerPipelineDvmState *dvmGcrState,
               PtdmaVqState *ptdmaQueueRead,InternalDmaOpSource source,uint32_t head_lo,
               uint32_t tail_lo)

{
  uint uVar1;
  uint *puVar2;
  ulong uVar3;
  uint32_t uVar4;
  ulong uVar5;
  ulong uVar6;
  
  if ((((rings->m_static_config).field_0.asU32 >> 0x1a ^ (uint)source.field_0 >> 7) & 1 |
      (uint)source.field_0 & 0x7f) == 0) {
    uVar3 = *(ulong *)dvmGcrState;
    *(ulong *)dvmGcrState = uVar3 & 0xfffffffffffeffff;
    DC_CIVAC((ulong)(ulong *)(ulong)dvmGcrState->m_vaSramReadOnly & 0xffffffc0);
    UnkSytemRegWrite(0,3,3,0xd,4,0);
    uVar6 = *(ulong *)(ulong)dvmGcrState->m_vaSramReadOnly;
    uVar5 = uVar6 >> 2;
    uVar4 = (uint32_t)uVar5;
    if ((dvmGcrState->m_sdma_head != uVar4) || (((byte)dvmGcrState->field_0x2 >> 4 & 1) != 0)) {
      puVar2 = (uint *)&DAT_022902c0;
      if (((rings->m_static_config).field_0.asU32 & 0x4000000) != 0) {
        puVar2 = (uint *)&DAT_022902e0;
      }
      uVar1 = *puVar2 & 0x3fffffff;
      if ((0xfffffc0 < uVar1 - 0x40) || ((uVar1 - 1 & uVar1) != 0)) {
LAB_0605df40:
        controllerHaltAndError
                  (rings,kA53ControllerSysError_InternalError_StateValidation,0xc00000000369,0);
        return;
      }
      if (((byte)dvmGcrState->field_0x2 >> 4 & 1) == 0) {
        uVar6 = *(ulong *)(ulong)dvmGcrState->m_vaSramRw >> 2;
        uVar5 = uVar6 - uVar5;
        if (((uVar1 <= uVar5) || ((long)uVar5 < 0)) ||
           (((int)uVar6 - dvmGcrState->m_sdma_head & uVar1 - 1) < (uint)uVar5)) goto LAB_0605df40;
      }
      else {
        *(ulong *)(ulong)dvmGcrState->m_vaSramRw = uVar6 & 0xfffffffffffffffc;
        *(ulong *)dvmGcrState = *(ulong *)dvmGcrState & 0xffffffffffe7ffff | 0x80000;
      }
      dvmGcrState->m_sdma_head = uVar4;
      if (((uint)uVar3 >> 0x14 & 1) != 0) {
        dvmGcrState->m_sdma_allocated = uVar4;
        return;
      }
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605df80
 * symbol: dmaWriteCmdCompleted_SdmaTail
 * prototype: void dmaWriteCmdCompleted_SdmaTail(ControllerRings * rings, ControllerPipelineDvmState * dvmGcrState, PtdmaVqState * ptdmaQueueWrite, InternalDmaOpSource source, uint32_t head_lo, uint32_t tail_lo)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::dmaWriteCmdCompleted_SdmaTail
               (ControllerRings *rings,ControllerPipelineDvmState *dvmGcrState,
               PtdmaVqState *ptdmaQueueWrite,InternalDmaOpSource source,uint32_t head_lo,
               uint32_t tail_lo)

{
  if (((((rings->m_static_config).field_0.asU32 >> 0x1a ^ (uint)source.field_0 >> 7) & 1) == 0) &&
     ((((uint)source.field_0 >> 1 & 0x3f) << 3 | 4) == 0xc)) {
    *(ulong *)dvmGcrState = *(ulong *)dvmGcrState & 0xfffffffffffdffff;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605dfb4
 * symbol: getPipelineCommandDataElement
 * prototype: bool getPipelineCommandDataElement(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t pipelineCmdElemIdx, uint32_t * out_value)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataElement
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t pipelineCmdElemIdx,uint32_t *out_value)

{
  bool bVar1;
  uint32_t uVar2;
  uint local_38 [2];
  
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (sramRingView_PipelineCommandData,(uint)pipelineCommandId,local_38);
  if ((uVar2 == 1) && (pipelineCmdElemIdx < (local_38[0] & 0x1f))) {
    uVar2 = ConstSramRingView::readElementsWrapped<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                       pipelineCmdElemIdx + 1,1,out_value);
    bVar1 = uVar2 == 1;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e038
 * symbol: getPipelineCommandDataElements
 * prototype: bool getPipelineCommandDataElements(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t pipelineCmdElemIdxStart, uint32_t numElems, uint32_t * out_aValue)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataElements
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t pipelineCmdElemIdxStart,uint32_t numElems,uint32_t *out_aValue)

{
  bool bVar1;
  uint32_t uVar2;
  uint local_38 [2];
  
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (sramRingView_PipelineCommandData,(uint)pipelineCommandId,local_38);
  if ((uVar2 == 1) && (numElems + pipelineCmdElemIdxStart <= (local_38[0] & 0x1f))) {
    uVar2 = ConstSramRingView::readElementsWrapped<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                       pipelineCmdElemIdxStart + 1,numElems,out_aValue);
    bVar1 = uVar2 == numElems;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e0c4
 * symbol: getPipelineCommandDataSramVaOfElement
 * prototype: bool getPipelineCommandDataSramVaOfElement(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t pipelineCmdElemIdx, uint64_t * out_vaSramElement)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataSramVaOfElement
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t pipelineCmdElemIdx,uint64_t *out_vaSramElement)

{
  bool bVar1;
  uint32_t uVar2;
  uint64_t uVar3;
  uint local_38 [2];
  
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (sramRingView_PipelineCommandData,(uint)pipelineCommandId,local_38);
  if ((uVar2 == 1) && (pipelineCmdElemIdx < (local_38[0] & 0x1f))) {
    uVar3 = ConstSramRingView::getVaSramElementWrapped
                      (sramRingView_PipelineCommandData,pipelineCommandId,pipelineCmdElemIdx + 1);
    bVar1 = true;
    *out_vaSramElement = uVar3;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e144
 * symbol: getPipelineCommandDataElementIndexOfInputCommandHeader
 * prototype: uint32_t getPipelineCommandDataElementIndexOfInputCommandHeader(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::getPipelineCommandDataElementIndexOfInputCommandHeader
                   (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId)

{
  bool bVar1;
  uint32_t uVar2;
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_18 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (sramRingView_PipelineCommandData,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_18[0].field_0);
  if ((bVar1) && ((local_18[0].asU32 >> 6 & 1) == 0)) {
    uVar2 = (local_18[0].asU32 >> 4 & 2) + 2;
  }
  else {
    uVar2 = 0xffffffff;
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e184
 * symbol: getPipelineCommandDataElementIndexRangeOfStateData
 * prototype: bool getPipelineCommandDataElementIndexRangeOfStateData(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t * out_pipelineCmdElemIdxStart, uint32_t * out_numElems)
 * body addresses: 168
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataElementIndexRangeOfStateData
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t *out_pipelineCmdElemIdxStart,uint32_t *out_numElems)

{
  uint uVar1;
  bool bVar2;
  uint local_48 [2];
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_38 [2];
  
  bVar2 = getPipelineCommandDataHeader
                    (sramRingView_PipelineCommandData,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_38[0].field_0);
  if ((bVar2) && ((local_38[0].asU32 >> 6 & 1) == 0)) {
    uVar1 = local_38[0].asU32 >> 4 & 2;
    bVar2 = getPipelineCommandDataElement
                      (sramRingView_PipelineCommandData,pipelineCommandId,uVar1 + 2,local_48);
    if (bVar2) {
      uVar1 = uVar1 + (local_48[0] >> 8 & 0xf) + 3;
      if (uVar1 <= (local_38[0].asU32 & 0x1f)) {
        *out_pipelineCmdElemIdxStart = uVar1;
        *out_numElems = (local_38[0].asU32 & 0x1f) - uVar1;
        return true;
      }
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e22c
 * symbol: getPipelineCommandDataCommandInRingLocation
 * prototype: bool getPipelineCommandDataCommandInRingLocation(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, CommandInRingLocation * out_cmdLoc)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataCommandInRingLocation
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               CommandInRingLocation *out_cmdLoc)

{
  bool bVar1;
  PipelineCommandDataHeader local_28 [2];
  
  bVar1 = getPipelineCommandDataHeader(sramRingView_PipelineCommandData,pipelineCommandId,local_28);
  if ((bVar1) && (((byte)local_28[0].field_0.asU32._0_1_ >> 5 & 1) == 0)) {
    bVar1 = getPipelineCommandDataElements
                      (sramRingView_PipelineCommandData,pipelineCommandId,0,2,(uint32_t *)out_cmdLoc
                      );
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e290
 * symbol: getPipelineCommandDataCommandInIndirectBufferLocation
 * prototype: bool getPipelineCommandDataCommandInIndirectBufferLocation(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, CommandInIndirectBufferLocation * out_cmdLoc)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataCommandInIndirectBufferLocation
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               CommandInIndirectBufferLocation *out_cmdLoc)

{
  bool bVar1;
  PipelineCommandDataHeader local_28 [2];
  
  bVar1 = getPipelineCommandDataHeader(sramRingView_PipelineCommandData,pipelineCommandId,local_28);
  if ((bVar1) && (((byte)local_28[0].field_0.asU32._0_1_ >> 5 & 1) != 0)) {
    bVar1 = getPipelineCommandDataElements
                      (sramRingView_PipelineCommandData,pipelineCommandId,0,4,(uint32_t *)out_cmdLoc
                      );
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e2f4
 * symbol: getPipelineCommandDataInputCommandHeader
 * prototype: bool getPipelineCommandDataInputCommandHeader(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, A53ControllerCommandHeader * out_cmdHeader)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataInputCommandHeader
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               A53ControllerCommandHeader *out_cmdHeader)

{
  bool bVar1;
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_28 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (sramRingView_PipelineCommandData,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_28[0].field_0);
  if ((bVar1) && ((local_28[0].asU32 >> 6 & 1) == 0)) {
    bVar1 = getPipelineCommandDataElement
                      (sramRingView_PipelineCommandData,pipelineCommandId,
                       (local_28[0].asU32 >> 4 & 2) + 2,(uint32_t *)out_cmdHeader);
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e35c
 * symbol: getPipelineCommandDataError
 * prototype: bool getPipelineCommandDataError(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandError * out_pipelineCommandError)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataError
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               PipelineCommandError *out_pipelineCommandError)

{
  bool bVar1;
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_28 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (sramRingView_PipelineCommandData,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_28[0].field_0);
  if ((bVar1) && ((local_28[0].asU32 >> 6 & 1) != 0)) {
    bVar1 = getPipelineCommandDataElements
                      (sramRingView_PipelineCommandData,pipelineCommandId,
                       (local_28[0].asU32 >> 4 & 2) + 2,2,(uint32_t *)out_pipelineCommandError);
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e3c8
 * symbol: setPipelineCommandDataHeaderState
 * prototype: bool setPipelineCommandDataHeaderState(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t state_b0_8)
 * body addresses: 112
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataHeaderState
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t state_b0_8)

{
  bool bVar1;
  uint32_t uVar2;
  uint local_28 [2];
  
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,
                     (uint)pipelineCommandId,local_28);
  if ((uVar2 == 1) && ((local_28[0] >> 6 & 1) == 0)) {
    local_28[0] = local_28[0] & 0xffff0000 | local_28[0] & 0x7f | (state_b0_8 & 0x1ff) << 7;
    uVar2 = SramRingView::writeElement<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,local_28);
    bVar1 = uVar2 == 1;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e438
 * symbol: setPipelineCommandDataHeaderStateCompleted
 * prototype: bool setPipelineCommandDataHeaderStateCompleted(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeaderCompletionType eCompletionType, SetPipelineCommandDataHeaderStateCompletedReportErrorsToPsp eReportSysErrorsToPsp)
 * body addresses: 172
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataHeaderStateCompleted
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               PipelineCommandDataHeaderCompletionType eCompletionType,
               SetPipelineCommandDataHeaderStateCompletedReportErrorsToPsp eReportSysErrorsToPsp)

{
  uint uVar1;
  bool bVar2;
  uint32_t uVar3;
  uint local_38 [2];
  
  uVar3 = ConstSramRingView::readElement<unsigned_int>
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,
                     (uint)pipelineCommandId,local_38);
  if ((uVar3 == 1) && ((local_38[0] & 0x440) != 0x40)) {
    uVar1 = (eReportSysErrorsToPsp & 1) << 0xb;
    if (eCompletionType != kPipelineCommandDataHeaderCompletionTypeSysError) {
      uVar1 = 0;
    }
    local_38[0] = ((eCompletionType & kPipelineCommandDataHeaderCompletionTypeCompletionWaitToFree)
                   << 4 | (eCompletionType &
                          (kPipelineCommandDataHeaderCompletionTypeAppError|
                           kPipelineCommandDataHeaderCompletionTypeSysError|
                          kPipelineCommandDataHeaderCompletionTypeCompletionDone)) << 8 | uVar1 |
                  local_38[0] & 0xffff003f) ^ 0x440;
    uVar3 = SramRingView::writeElement<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,local_38);
    bVar2 = uVar3 == 1;
  }
  else {
    bVar2 = false;
  }
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e4e4
 * symbol: setPipelineCommandDataHeaderStateClearWaitToFree
 * prototype: bool setPipelineCommandDataHeaderStateClearWaitToFree(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataHeaderStateClearWaitToFree
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId)

{
  bool bVar1;
  uint32_t uVar2;
  uint local_28 [2];
  
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,
                     (uint)pipelineCommandId,local_28);
  if ((uVar2 == 1) && ((~local_28[0] & 0xc0) == 0)) {
    local_28[0] = local_28[0] & 0xffffff7f;
    uVar2 = SramRingView::writeElement<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,local_28);
    bVar1 = uVar2 == 1;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e558
 * symbol: setPipelineCommandDataElement
 * prototype: bool setPipelineCommandDataElement(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t pipelineCmdElemIdx, uint32_t value)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataElement
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t pipelineCmdElemIdx,uint32_t value)

{
  bool bVar1;
  uint32_t uVar2;
  uint local_28;
  uint32_t local_24;
  
  local_24 = value;
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,
                     (uint)pipelineCommandId,&local_28);
  if ((uVar2 == 1) && (pipelineCmdElemIdx < (local_28 & 0x1f))) {
    uVar2 = SramRingView::writeElementsWrapped<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                       pipelineCmdElemIdx + 1,1,&local_24);
    bVar1 = uVar2 == 1;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e5d4
 * symbol: setPipelineCommandDataElements
 * prototype: bool setPipelineCommandDataElements(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t pipelineCmdElemIdxStart, uint32_t numElems, uint32_t * aValue)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataElements
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t pipelineCmdElemIdxStart,uint32_t numElems,uint32_t *aValue)

{
  bool bVar1;
  uint32_t uVar2;
  uint local_38 [2];
  
  uVar2 = ConstSramRingView::readElement<unsigned_int>
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,
                     (uint)pipelineCommandId,local_38);
  if ((uVar2 == 1) && (numElems + pipelineCmdElemIdxStart <= (local_38[0] & 0x1f))) {
    uVar2 = SramRingView::writeElementsWrapped<unsigned_int>
                      (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                       pipelineCmdElemIdxStart + 1,numElems,aValue);
    bVar1 = uVar2 == numElems;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e660
 * symbol: setPipelineCommandDataCommandInRingLocation
 * prototype: bool setPipelineCommandDataCommandInRingLocation(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, CommandInRingLocation cmdLoc)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::setPipelineCommandDataCommandInRingLocation
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               CommandInRingLocation cmdLoc)

{
  bool bVar1;
  PipelineCommandDataHeader local_30 [2];
  anon_union_8_2_653be89a_for_CommandInRingLocation_0 local_28;
  
  local_28 = cmdLoc.field_0;
  bVar1 = getPipelineCommandDataHeader
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                     local_30);
  if ((bVar1) && (((byte)local_30[0].field_0.asU32._0_1_ >> 5 & 1) == 0)) {
    bVar1 = setPipelineCommandDataElements
                      (sramRingView_PipelineCommandData,pipelineCommandId,0,2,local_28.asU32);
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e6c4
 * symbol: setPipelineCommandDataCommandInIndirectBufferLocation
 * prototype: bool setPipelineCommandDataCommandInIndirectBufferLocation(SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, CommandInIndirectBufferLocation * cmdLoc)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataCommandInIndirectBufferLocation
               (SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               CommandInIndirectBufferLocation *cmdLoc)

{
  bool bVar1;
  PipelineCommandDataHeader local_28 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                     local_28);
  if ((bVar1) && (((byte)local_28[0].field_0.asU32._0_1_ >> 5 & 1) != 0)) {
    bVar1 = setPipelineCommandDataElements
                      (sramRingView_PipelineCommandData,pipelineCommandId,0,4,(uint32_t *)cmdLoc);
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e728
 * symbol: setPipelineCommandDataCompleted
 * prototype: bool setPipelineCommandDataCompleted(ControllerRuntimeConfiguration * runtime_config, SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, uint32_t returnValue, SetPipelineCommandDataCompletedWaitToFree eWaitToFree)
 * body addresses: 268
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setPipelineCommandDataCompleted
               (ControllerRuntimeConfiguration *runtime_config,
               SramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               uint32_t returnValue,SetPipelineCommandDataCompletedWaitToFree eWaitToFree)

{
  uint32_t pipelineCmdElemIdx;
  bool bVar1;
  PipelineCommandDataHeaderCompletionType PVar2;
  PipelineCommandDataHeaderCompletionType PVar3;
  ulong local_60;
  uint local_58 [2];
  anon_union_4_4_08a11d99_for_PipelineCommandDataHeader_0 local_48 [2];
  
  bVar1 = getPipelineCommandDataHeader
                    (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
                     (PipelineCommandDataHeader *)&local_48[0].field_0);
  if (((bVar1) && ((local_48[0].asU32 >> 6 & 1) == 0)) &&
     (bVar1 = SramRingView::canWriteElementsWrapped
                        (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                         (local_48[0].asU32 & 0x1f) + 1), bVar1)) {
    pipelineCmdElemIdx = (local_48[0].asU32 >> 4 & 2) + 2;
    getPipelineCommandDataElement
              (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
               pipelineCmdElemIdx,local_58);
    PVar3 = kPipelineCommandDataHeaderCompletionTypeCompletionDone;
    if (((byte)local_48[0].asU32._0_1_ >> 5 & 1) == 0) {
      PVar3 = (local_58[0] >> 5 ^ ~kPipelineCommandDataHeaderCompletionTypeCompletion) &
              kPipelineCommandDataHeaderCompletionTypeCompletionDone;
    }
    local_60 = CONCAT44(returnValue,local_58[0]) & 0xffffffff0000007f;
    setPipelineCommandDataElements
              (sramRingView_PipelineCommandData,pipelineCommandId,pipelineCmdElemIdx,2,
               (uint32_t *)&local_60);
    PVar2 = kPipelineCommandDataHeaderCompletionTypeCompletion;
    if (eWaitToFree != kSetPipelineCommandDataCompletedNoWaitToFree) {
      PVar2 = kPipelineCommandDataHeaderCompletionTypeCompletionWaitToFree;
    }
    setPipelineCommandDataHeaderStateCompleted
              (sramRingView_PipelineCommandData,pipelineCommandId,PVar3 | PVar2,
               *(ushort *)((long)&runtime_config->field_0 + 10) & 1);
    bVar1 = true;
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e834
 * symbol: allocatePipelineCommandDataAndCommandRingExecutingCommand
 * prototype: uint16_t allocatePipelineCommandDataAndCommandRingExecutingCommand(ControllerRings * rings, SramRing * sramRing_CommandRingExecutingCommand, ControllerPipelineAllocator * pipeline_allocator, uint32_t iCommandRing, uint32_t iPipeline, CommandPipelineType eIsNotEOP, A53ControllerCommandHeader cmdHeader, uint32_t numCommandElems, uint32_t * aCommandElems, uint32_t pidCmd, uint32_t state_b0_8, uint32_t numStateElems, uint32_t * aStateElems, SramRingView * out_sramRingView_PipelineCommandData)
 * body addresses: 288
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint16_t A53::allocatePipelineCommandDataAndCommandRingExecutingCommand
                   (ControllerRings *rings,SramRing *sramRing_CommandRingExecutingCommand,
                   ControllerPipelineAllocator *pipeline_allocator,uint32_t iCommandRing,
                   uint32_t iPipeline,CommandPipelineType eIsNotEOP,
                   A53ControllerCommandHeader cmdHeader,uint32_t numCommandElems,
                   uint32_t *aCommandElems,uint32_t pidCmd,uint32_t state_b0_8,
                   uint32_t numStateElems,uint32_t *aStateElems,
                   SramRingView *out_sramRingView_PipelineCommandData)

{
  uint16_t commandRingExecutingCommandId;
  uint16_t uVar1;
  uint16_t uVar2;
  
  uVar2 = 0x7fff;
  if (*(ushort *)
       ((long)&(sramRing_CommandRingExecutingCommand->super_SramRingView).super_ConstSramRingView.
               field_0 + 4) + 1 !=
      ((sramRing_CommandRingExecutingCommand->super_SramRingView).super_ConstSramRingView.field_0.
       asU32[2] & 0x1ffff)) {
    commandRingExecutingCommandId =
         ConstSramRingView::getElementIndexTail
                   ((ConstSramRingView *)sramRing_CommandRingExecutingCommand);
    uVar1 = allocatePipelineCommandData
                      (rings,pipeline_allocator,iCommandRing,iPipeline,commandRingExecutingCommandId
                       ,cmdHeader,numCommandElems,aCommandElems,pidCmd,state_b0_8,numStateElems,
                       aStateElems,out_sramRingView_PipelineCommandData);
    if (uVar1 != 0x7fff) {
      SramRing::pushElement(sramRing_CommandRingExecutingCommand);
      (*pipeline_allocator->m_pfnInitCommandRingExecutingCommand)
                (pipeline_allocator->m_pController,iCommandRing,commandRingExecutingCommandId,
                 eIsNotEOP,iPipeline,uVar1);
      uVar2 = uVar1;
    }
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605e954
 * symbol: allocatePipelineCommandData
 * prototype: uint16_t allocatePipelineCommandData(ControllerRings * rings, ControllerPipelineAllocator * pipeline_allocator, uint32_t iCommandRing, uint32_t iPipeline, uint16_t commandRingExecutingCommandId, A53ControllerCommandHeader cmdHeader, uint32_t numCommandElems, uint32_t * aCommandElems, uint32_t pidCmd, uint32_t state_b0_8, uint32_t numStateElems, uint32_t * aStateElems, SramRingView * out_sramRingView_PipelineCommandData)
 * body addresses: 548
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint16_t A53::allocatePipelineCommandData
                   (ControllerRings *rings,ControllerPipelineAllocator *pipeline_allocator,
                   uint32_t iCommandRing,uint32_t iPipeline,uint16_t commandRingExecutingCommandId,
                   A53ControllerCommandHeader cmdHeader,uint32_t numCommandElems,
                   uint32_t *aCommandElems,uint32_t pidCmd,uint32_t state_b0_8,
                   uint32_t numStateElems,uint32_t *aStateElems,
                   SramRingView *out_sramRingView_PipelineCommandData)

{
  ulong uVar1;
  uint16_t pipelineCommandId;
  uint16_t uVar2;
  A53Controller_InputRingWithIndirectBufferHead *pAVar3;
  uint32_t pipelineCmdElemIdx;
  uint32_t uVar4;
  A53Controller_InputRingWithIndirectBufferHead *pAVar5;
  uint uVar6;
  uint uVar7;
  CommandInIndirectBufferLocation local_70;
  
  pAVar3 = (A53Controller_InputRingWithIndirectBufferHead *)pipeline_allocator->m_paInputRingHead;
  uVar6 = (rings->m_static_config).field_0.asU32 >> 6 & 0x1f;
  if (iCommandRing < uVar6) {
    if (pAVar3 == (A53Controller_InputRingWithIndirectBufferHead *)0x0) {
      pAVar5 = (A53Controller_InputRingWithIndirectBufferHead *)0x0;
      uVar7 = 0;
      uVar6 = (uint)rings->m_paInputRing[iCommandRing].field_0.field_0.m_head;
    }
    else {
      pAVar5 = (A53Controller_InputRingWithIndirectBufferHead *)0x0;
      uVar6 = (uint)*(ushort *)((long)&pAVar3->field_0 + (ulong)iCommandRing * 8);
      uVar7 = 0;
    }
  }
  else {
    if (pAVar3 == (A53Controller_InputRingWithIndirectBufferHead *)0x0) {
      pAVar3 = rings->m_paInputRingHeadIb;
    }
    pAVar5 = pAVar3 + (iCommandRing - uVar6);
    uVar6 = (pAVar5->field_0).asU32[0];
    uVar7 = uVar6 >> 0x1d & 1;
  }
  uVar4 = 2;
  pipelineCmdElemIdx = uVar4;
  if (uVar7 != 0) {
    pipelineCmdElemIdx = 4;
  }
  if (2 < numCommandElems + numStateElems + 1) {
    uVar4 = numCommandElems + numStateElems + 1;
  }
  pipelineCommandId =
       (*pipeline_allocator->m_pfnAllocatePipelineCommandData)
                 (pipeline_allocator->m_pController,iPipeline,
                  (PipelineCommandDataHeader)
                  (iCommandRing << 0x1b | (commandRingExecutingCommandId & 0x7ff) << 0x10 |
                   (state_b0_8 & 0x1ff) << 7 | uVar7 << 5 | pipelineCmdElemIdx + uVar4 & 0x1f),
                  out_sramRingView_PipelineCommandData);
  uVar2 = 0x7fff;
  if (pipelineCommandId != 0x7fff) {
    if (uVar7 == 0) {
      setPipelineCommandDataCommandInRingLocation
                (out_sramRingView_PipelineCommandData,pipelineCommandId,
                 (CommandInRingLocation)(CONCAT44(pidCmd,uVar6) & 0xffffffff0000ffff));
    }
    else {
      uVar1 = (pAVar5->field_0).asU64[0] >> 0x10;
      local_70.field_0._0_8_ =
           (ulong)*(ushort *)&pAVar5->field_0 | uVar1 & 0xffff0000 | uVar1 & 0xff00000000 |
           (pAVar5->field_0).asU64[0] >> 0x10 & 0xffffff0000000000 |
           (pAVar5->field_0).asU64[1] << 0x30;
      local_70.field_0._8_8_ =
           ((pAVar5->field_0).asU64[0] << 0x20 | (pAVar5->field_0).asU64[1] >> 0x10) &
           0x1fff0000ffffffff | (pAVar5->field_0).asU64[1] >> 0x10 & 0xffff00000000;
      setPipelineCommandDataCommandInIndirectBufferLocation
                (out_sramRingView_PipelineCommandData,pipelineCommandId,&local_70);
    }
    setPipelineCommandDataElement
              (out_sramRingView_PipelineCommandData,pipelineCommandId,pipelineCmdElemIdx,
               (uint)cmdHeader.field_0 & 0xfffff000 |
               (uint)cmdHeader.field_0 & 0xff | (numCommandElems & 0xf) << 8);
    if (numCommandElems != 0) {
      setPipelineCommandDataElements
                (out_sramRingView_PipelineCommandData,pipelineCommandId,pipelineCmdElemIdx | 1,
                 numCommandElems,aCommandElems);
    }
    uVar2 = pipelineCommandId;
    if (numStateElems != 0) {
      setPipelineCommandDataElements
                (out_sramRingView_PipelineCommandData,pipelineCommandId,
                 (pipelineCmdElemIdx | 1) + numCommandElems,numStateElems,aStateElems);
    }
  }
  return uVar2;
}


