/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/a53_ptdma.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06004434
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = 0x800000020;
  puVar1[1] = (ulong)len;
  puVar1[2] = -(paSrc >> 0x30 & 1) & 0x3000000000000 |
              paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20;
  puVar1[3] = 0xffff;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06010760
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06038ffc
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e4f0
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  uint32_t uVar1;
  DmaCommand local_30;
  
  local_30.field_0.asU64[3] = (uint64_t)pasid;
  local_30.field_0.asU64[0] = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  local_30.field_0.asU64[2] =
       -(paDst >> 0x30 & 1) & 0x3000000000000 |
       paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20;
  local_30.field_0.asU64[1] =
       -(paSrc >> 0x30 & 1) & 0x3000000000000 |
       paSrc & 0xffffffff | (paSrc >> 0x20 & 0xffff) << 0x20;
  uVar1 = ptdmaPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604e8b8
 * symbol: ptdmaPutCommand
 * prototype: uint32_t ptdmaPutCommand(PtdmaVqSubmitState * submit, DmaCommand * cmd)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::ptdmaPutCommand(PtdmaVqSubmitState *submit,DmaCommand *cmd)

{
  uint64_t *puVar1;
  uint uVar2;
  uint32_t uVar3;
  uint64_t uVar4;
  
  uVar4 = (cmd->field_0).asU64[1];
  puVar1 = (uint64_t *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = (cmd->field_0).asU64[0];
  puVar1[1] = uVar4;
  uVar4 = (cmd->field_0).asU64[3];
  puVar1[2] = (cmd->field_0).asU64[2];
  puVar1[3] = uVar4;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0604eccc
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  ulong *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (ulong *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5) | (ulong)((eWoC & 1) << 2);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052b90
 * symbol: ptdmaPutCommandZero
 * prototype: uint32_t ptdmaPutCommandZero(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandZero
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paDst,uint16_t pasid,
                   DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  uint32_t uVar1;
  DmaCommand local_30;
  
  local_30.field_0.asU64[3] = (uint64_t)pasid;
  local_30.field_0.asU64[0] = (ulong)len << 0x20;
  local_30.field_0.asU64[2] =
       -(paDst >> 0x30 & 1) & 0x3000000000000 |
       paDst & 0xffffffff | (paDst >> 0x20 & 0xffff) << 0x20;
  local_30.field_0.asU64[1] = 0x1000000000000;
  uVar1 = ptdmaPutCommand(submit,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06052e30
 * symbol: ptdmaPutCommand
 * prototype: uint32_t ptdmaPutCommand(PtdmaVqSubmitState * submit, DmaCommand * cmd)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::ptdmaPutCommand(PtdmaVqSubmitState *submit,DmaCommand *cmd)

{
  uint64_t *puVar1;
  uint uVar2;
  uint32_t uVar3;
  uint64_t uVar4;
  
  uVar4 = (cmd->field_0).asU64[1];
  puVar1 = (uint64_t *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = (cmd->field_0).asU64[0];
  puVar1[1] = uVar4;
  uVar4 = (cmd->field_0).asU64[3];
  puVar1[2] = (cmd->field_0).asU64[2];
  puVar1[3] = uVar4;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605d080
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606579c
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065d14
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066bf0
 * symbol: ptdmaPutCommandCopy
 * prototype: uint32_t ptdmaPutCommandCopy(PtdmaVqSubmitState * submit, uint32_t len, uint64_t paSrc, uint64_t paDst, uint16_t pasid, DmaFunction eDmaPrefetch, DmaWaitOnCompletion eWoC)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::ptdmaPutCommandCopy
                   (PtdmaVqSubmitState *submit,uint32_t len,uint64_t paSrc,uint64_t paDst,
                   uint16_t pasid,DmaFunction eDmaPrefetch,DmaWaitOnCompletion eWoC)

{
  undefined8 *puVar1;
  uint uVar2;
  uint32_t uVar3;
  
  puVar1 = (undefined8 *)((ulong)submit->m_offsetPut + (ulong)submit->m_vaQueue);
  *puVar1 = CONCAT44(len,(eDmaPrefetch & 0x7fff) << 5);
  puVar1[1] = -(paSrc >> 0x30 & 1) & 0x3000000000000 | paSrc & 0xffffffff | paSrc & 0xffff00000000;
  puVar1[2] = -(paDst >> 0x30 & 1) & 0x3000000000000 | paDst & 0xffffffff | paDst & 0xffff00000000;
  puVar1[3] = (ulong)pasid;
  uVar3 = submit->m_offsetPut;
  uVar2 = uVar3 + 0x20 & submit->m_maskVqdPointer;
  submit->m_offsetPut = uVar2;
  submit->m_numCommandsAvailable = submit->m_numCommandsAvailable - 1;
  if ((uVar2 & 0x3f) != 0) {
    return uVar3;
  }
  DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
  return uVar3;
}


