/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_sram_cache.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066edc
 * symbol: releaseWaitingLockInvalidateLine
 * prototype: void releaseWaitingLockInvalidateLine(SramCache4 * this, uint32_t cacheElemIdx)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void releaseWaitingLockInvalidateLine(SramCache4 * this, uint32_t
   cacheElemIdx) */

void __thiscall
A53::SramCache4::releaseWaitingLockInvalidateLine(SramCache4 *this,uint32_t cacheElemIdx)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  char cVar4;
  
  uVar2 = (this->field_0).asU32[0];
  uVar3 = uVar2 >> 0x10 & 0xff;
  uVar1 = uVar3 ^ cacheElemIdx * 0x55;
  uVar1 = (((uVar1 | uVar1 >> 1) ^ 0xffffffff) & 0x55) << 1;
  uVar1 = (uVar1 & 0xcccccccc) >> 2 | (uVar1 & 0x33333333) << 2;
  cVar4 = (char)(4 << (ulong)((uint)LZCOUNT((uVar1 >> 4 | (uVar1 & 0xf0f0f0f) << 4) << 0x18) & 0x1f)
                );
  *(undefined *)((long)&this->field_0 + (ulong)cacheElemIdx + 4) = 0;
  *(undefined4 *)((long)&this->field_0 + (ulong)cacheElemIdx * 4 + 0x10) = 0;
  *(byte *)((long)&this->field_0 + 2) =
       -cVar4 & (byte)(uVar2 >> 0x10) | (byte)cacheElemIdx | cVar4 - 1U & (byte)(uVar3 << 2);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066f38
 * symbol: updateForPtdmaCompletion
 * prototype: bool updateForPtdmaCompletion(SramCache4 * this, uint64_t vaSramCacheBase, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo, uint32_t cacheElemIdx)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForPtdmaCompletion(SramCache4 * this, uint64_t
   vaSramCacheBase, uint32_t ptdmaSizeofQueue, uint32_t ptdmaHeadLo, uint32_t ptdmaTailLo, uint32_t
   cacheElemIdx) */

bool __thiscall
A53::SramCache4::updateForPtdmaCompletion
          (SramCache4 *this,uint64_t vaSramCacheBase,uint32_t ptdmaSizeofQueue,uint32_t ptdmaHeadLo,
          uint32_t ptdmaTailLo,uint32_t cacheElemIdx)

{
  ulong uVar1;
  uint uVar2;
  ulong uVar3;
  
  if (((uint)*(ushort *)((long)&this->field_0 + (ulong)cacheElemIdx * 2 + 8) * 0x20 - ptdmaHeadLo &
      ptdmaSizeofQueue - 0x20) < (ptdmaTailLo - ptdmaHeadLo & ptdmaSizeofQueue - 0x20)) {
    return false;
  }
  uVar2 = (this->field_0).asU32[0] >> 0x18 & 0xf;
  uVar1 = vaSramCacheBase + (ushort)(this->field_0).asU32[0] + (ulong)(cacheElemIdx << uVar2);
  for (uVar3 = uVar1 & 0xffffffffffffffc0;
      uVar3 < ((1L << uVar2) + uVar1 + 0x3f & 0xffffffffffffffc0); uVar3 = uVar3 + 0x40) {
    DC_CIVAC(uVar3);
  }
  UnkSytemRegWrite(0,3,3,0xd,4,0);
  *(undefined2 *)((long)&this->field_0 + (ulong)cacheElemIdx * 2 + 8) = 0xffff;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066fc0
 * symbol: getCacheElementIdxIfHit
 * prototype: SramCacheLineStatus getCacheElementIdxIfHit(SramCache4 * this, uint32_t maskCacheElemPtdmaReadPending, uint32_t lineId, uint32_t * out_cacheElemIdx)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: SramCacheLineStatus getCacheElementIdxIfHit(SramCache4 * this, uint32_t
   maskCacheElemPtdmaReadPending, uint32_t lineId, uint32_t * out_cacheElemIdx) */

SramCacheLineStatus __thiscall
A53::SramCache4::getCacheElementIdxIfHit
          (SramCache4 *this,uint32_t maskCacheElemPtdmaReadPending,uint32_t lineId,
          uint32_t *out_cacheElemIdx)

{
  ulong uVar1;
  SramCacheLineStatus SVar2;
  
  if (lineId == 0) {
    return kSramCacheLineErrorInvalidArgs;
  }
  uVar1 = 0;
  while( true ) {
    if (3 < uVar1) {
      return kSramCacheLineMiss;
    }
    if ((*(uint32_t *)((long)&this->field_0 + uVar1 * 4 + 0x10) == lineId) &&
       (-1 < *(char *)((long)&this->field_0 + uVar1 + 4))) break;
    uVar1 = uVar1 + 1;
  }
  *out_cacheElemIdx = (uint)uVar1;
  SVar2 = kSramCacheLineHitWaitingForDma;
  if ((1 << (ulong)((uint)uVar1 & 0x1f) & maskCacheElemPtdmaReadPending) != 0) {
    if (((*(byte *)((long)&this->field_0 + uVar1 + 4) ^ 0xff) & 0x7f) == 0) {
      SVar2 = kSramCacheLineHitWaitingForDmaCountFull;
    }
    return SVar2;
  }
  return kSramCacheLineHitAvailableNow;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606703c
 * symbol: fillLineOnMiss
 * prototype: FillLineReturn fillLineOnMiss(SramCache4 * this, A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PfnTranslateLineIdToPhysicalAddress pfnTranslateLineIdToPhysicalAddress, void * pContext, PtdmaVqSubmitState * submitRead, uint32_t maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7, uint16_t pasid, uint32_t lineId)
 * body addresses: 420
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: FillLineReturn fillLineOnMiss(SramCache4 * this, A53_AddressTranslator
   * addressTranslator, uint64_t vaSramCacheBase, PfnTranslateLineIdToPhysicalAddress
   pfnTranslateLineIdToPhysicalAddress, void * pContext, PtdmaVqSubmitState * submitRead, uint32_t
   maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7, uint16_t pasid, uint32_t lineId) */

FillLineReturn __thiscall
A53::SramCache4::fillLineOnMiss
          (SramCache4 *this,A53_AddressTranslator *addressTranslator,uint64_t vaSramCacheBase,
          PfnTranslateLineIdToPhysicalAddress pfnTranslateLineIdToPhysicalAddress,void *pContext,
          PtdmaVqSubmitState *submitRead,uint32_t maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7,
          uint16_t pasid,uint32_t lineId)

{
  ulong *puVar1;
  uint uVar2;
  char cVar3;
  uint64_t uVar4;
  uint uVar5;
  ulong uVar6;
  uint uVar7;
  ulong uVar8;
  uint32_t in_stack_00000000;
  
  uVar6 = 0x80000001;
  if (in_stack_00000000 == 0) {
    uVar8 = 0;
    uVar6 = 0x80010001;
  }
  else {
    uVar8 = 4;
    for (uVar5 = 0; uVar7 = (uint)uVar8, uVar5 < 8; uVar5 = uVar5 + 2) {
      uVar7 = *(byte *)((long)&this->field_0 + 2) >> (ulong)(uVar5 & 0x1f) & 3;
      uVar8 = (ulong)uVar7;
      if ((*(char *)((long)&this->field_0 + uVar8 + 4) == '\0') &&
         ((0x10 << uVar8 & maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7) == 0)) goto LAB_060670c4;
    }
    if (uVar5 == 8) {
      uVar8 = 0;
      uVar6 = 0x80000002;
    }
    else {
LAB_060670c4:
      if (submitRead->m_numCommandsAvailable == 0) {
        uVar8 = 0;
      }
      else {
        uVar6 = 1;
        cVar3 = (char)(1 << (ulong)(uVar5 & 0x1f));
        *(byte *)((long)&this->field_0 + 2) =
             cVar3 - 1U & (byte)((this->field_0).asU32[0] >> 0x10) | (byte)(uVar7 << 6) |
             -cVar3 & (byte)((this->field_0).asU32[0] >> 0x12) & 0x3f;
        *(uint32_t *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x10) = in_stack_00000000;
        uVar4 = (*pfnTranslateLineIdToPhysicalAddress)(in_stack_00000000,pContext);
        uVar5 = (this->field_0).asU32[0];
        uVar2 = uVar5 >> 0x18 & 0xf;
        puVar1 = (ulong *)((ulong)submitRead->m_offsetPut + (ulong)submitRead->m_vaQueue);
        *puVar1 = (ulong)(uVar2 < 9) << 5 | (ulong)(uint)(1 << (ulong)uVar2) << 0x20;
        puVar1[1] = -(uVar4 >> 0x30 & 1) & 0x3000000000000 | uVar4 & 0xffffffffffff;
        puVar1[2] = (ulong)((int)vaSramCacheBase + (uVar5 & 0xffff) + (uVar7 << (ulong)uVar2)) &
                    0xfffff;
        puVar1[3] = (ulong)pasid;
        uVar2 = submitRead->m_offsetPut;
        uVar5 = uVar2 + 0x20 & submitRead->m_maskVqdPointer;
        submitRead->m_offsetPut = uVar5;
        submitRead->m_numCommandsAvailable = submitRead->m_numCommandsAvailable - 1;
        if ((uVar5 & 0x3f) == 0) {
          DC_CVAC((ulong)puVar1 & 0x1ffffffc0);
        }
        uVar8 = (ulong)(uVar2 >> 5 & 0xffff | uVar7 << 0x18 | 0x10000) << 0x20;
        *(short *)((long)&this->field_0 + (ulong)uVar7 * 2 + 8) = (short)(uVar2 >> 5);
        *(undefined *)((long)&this->field_0 + (ulong)uVar7 + 4) = 1;
      }
    }
  }
  return (FillLineReturn)(uVar8 | uVar6);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060671e0
 * symbol: fillLineIfHit
 * prototype: FillLineReturn fillLineIfHit(SramCache4 * this, uint32_t maskCacheElemPtdmaReadPending, uint32_t lineId)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: FillLineReturn fillLineIfHit(SramCache4 * this, uint32_t
   maskCacheElemPtdmaReadPending, uint32_t lineId) */

FillLineReturn __thiscall
A53::SramCache4::fillLineIfHit
          (SramCache4 *this,uint32_t maskCacheElemPtdmaReadPending,uint32_t lineId)

{
  byte bVar1;
  SramCacheLineStatus SVar2;
  ulong uVar3;
  ulong uVar4;
  byte *pbVar5;
  uint local_14;
  
  SVar2 = getCacheElementIdxIfHit(this,maskCacheElemPtdmaReadPending,lineId,&local_14);
  if (SVar2 == kSramCacheLineHitAvailableNow) {
    uVar3 = 0;
    uVar4 = (ulong)(local_14 << 0x18);
  }
  else if (SVar2 < kSramCacheLineHitAvailableNow) {
    uVar4 = 0;
    uVar3 = (ulong)(uint)SVar2;
  }
  else {
    pbVar5 = (byte *)((long)&this->field_0 + (ulong)local_14 + 4);
    bVar1 = *pbVar5;
    if ((~bVar1 & 0x7f) == 0) {
      uVar3 = 2;
      uVar4 = (ulong)(local_14 << 0x18);
    }
    else {
      uVar3 = 1;
      uVar4 = (ulong)(local_14 << 0x18);
      *pbVar5 = bVar1 + 1;
    }
  }
  return (FillLineReturn)(SramCacheLineStatus)(uVar3 | uVar4 << 0x20);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06067260
 * symbol: fillLine
 * prototype: FillLineReturn fillLine(SramCache4 * this, A53_AddressTranslator * addressTranslator, uint64_t vaSramCacheBase, PfnTranslateLineIdToPhysicalAddress pfnTranslateLineIdToPhysicalAddress, void * pContext, PtdmaVqSubmitState * submitRead, uint32_t maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7, uint16_t pasid, uint32_t lineId)
 * body addresses: 180
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: FillLineReturn fillLine(SramCache4 * this, A53_AddressTranslator *
   addressTranslator, uint64_t vaSramCacheBase, PfnTranslateLineIdToPhysicalAddress
   pfnTranslateLineIdToPhysicalAddress, void * pContext, PtdmaVqSubmitState * submitRead, uint32_t
   maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7, uint16_t pasid, uint32_t lineId) */

FillLineReturn __thiscall
A53::SramCache4::fillLine
          (SramCache4 *this,A53_AddressTranslator *addressTranslator,uint64_t vaSramCacheBase,
          PfnTranslateLineIdToPhysicalAddress pfnTranslateLineIdToPhysicalAddress,void *pContext,
          PtdmaVqSubmitState *submitRead,uint32_t maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7,
          uint16_t pasid,uint32_t lineId)

{
  FillLineReturn FVar1;
  uint32_t in_stack_00000000;
  
  FVar1 = fillLineIfHit(this,maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7,in_stack_00000000);
  if ((SramCacheLineStatus)FVar1._0_8_ == kSramCacheLineMiss) {
    FVar1 = fillLineOnMiss(this,addressTranslator,vaSramCacheBase,
                           pfnTranslateLineIdToPhysicalAddress,pContext,submitRead,
                           maskCacheElemPtdmaReadPending_b0_3_Locked_b4_7,pasid,0x80000000);
    return (FillLineReturn)FVar1._0_8_;
  }
  return (FillLineReturn)FVar1._0_8_;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06067314
 * symbol: releaseAllAvailableLines
 * prototype: uint32_t releaseAllAvailableLines(SramCache4 * this)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t releaseAllAvailableLines(SramCache4 * this) */

uint32_t __thiscall A53::SramCache4::releaseAllAvailableLines(SramCache4 *this)

{
  uint uVar1;
  byte bVar2;
  uint uVar3;
  long lVar4;
  
  uVar3 = 0;
  for (lVar4 = 0; lVar4 != 4; lVar4 = lVar4 + 1) {
    bVar2 = *(byte *)((long)&this->field_0 + lVar4 + 4);
    if ((bVar2 != 0) && (*(short *)((long)&this->field_0 + lVar4 * 2 + 8) == -1)) {
      uVar1 = bVar2 & 0x7f;
      if (uVar1 <= uVar3) {
        uVar1 = uVar3;
      }
      if ((char)bVar2 < '\0') {
        *(undefined4 *)((long)&this->field_0 + lVar4 * 4 + 0x10) = 0;
      }
      *(undefined *)((long)&this->field_0 + lVar4 + 4) = 0;
      uVar3 = uVar1;
    }
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606736c
 * symbol: acquireLineForRead
 * prototype: bool acquireLineForRead(SramCache4 * this, uint64_t vaSramCacheBase, uint32_t maskCacheElemPtdmaReadPending, uint32_t lineId, SramCacheLineAccessType eAccessReleaseLock, uint64_t * out_vaSramCacheLine)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool acquireLineForRead(SramCache4 * this, uint64_t vaSramCacheBase,
   uint32_t maskCacheElemPtdmaReadPending, uint32_t lineId, SramCacheLineAccessType
   eAccessReleaseLock, uint64_t * out_vaSramCacheLine) */

bool __thiscall
A53::SramCache4::acquireLineForRead
          (SramCache4 *this,uint64_t vaSramCacheBase,uint32_t maskCacheElemPtdmaReadPending,
          uint32_t lineId,SramCacheLineAccessType eAccessReleaseLock,uint64_t *out_vaSramCacheLine)

{
  bool bVar1;
  SramCacheLineStatus SVar2;
  uint32_t local_34;
  
  SVar2 = getCacheElementIdxIfHit(this,maskCacheElemPtdmaReadPending,lineId,&local_34);
  if (SVar2 == kSramCacheLineHitAvailableNow) {
    if (eAccessReleaseLock != kSramCacheLineAccessKeepWaitingLock) {
      releaseWaitingLock(this,local_34);
    }
    bVar1 = true;
    *out_vaSramCacheLine =
         vaSramCacheBase + (ushort)(this->field_0).asU32[0] +
         (ulong)(local_34 << (ulong)((this->field_0).asU32[0] >> 0x18 & 0xf));
  }
  else {
    bVar1 = false;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060673f4
 * symbol: releaseWaitingLock
 * prototype: bool releaseWaitingLock(SramCache4 * this, uint32_t cacheElemIdx)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool releaseWaitingLock(SramCache4 * this, uint32_t cacheElemIdx) */

bool __thiscall A53::SramCache4::releaseWaitingLock(SramCache4 *this,uint32_t cacheElemIdx)

{
  byte bVar1;
  byte *pbVar2;
  
  pbVar2 = (byte *)((long)&this->field_0 + (ulong)cacheElemIdx + 4);
  bVar1 = *pbVar2;
  if ((bVar1 & 0x7f) == 0) {
    return false;
  }
  if (bVar1 == 0x81) {
    releaseWaitingLockInvalidateLine(this,cacheElemIdx);
    return true;
  }
  *pbVar2 = bVar1 - 1;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606743c
 * symbol: invalidate
 * prototype: InvalidateReturn invalidate(SramCache4 * this, uint32_t maskCacheElemPtdmaReadPending, uint32_t * inout_maskCacheElemToInvalidate, uint32_t * inout_maskCacheElemToInvalidateRelease)
 * body addresses: 300
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: InvalidateReturn invalidate(SramCache4 * this, uint32_t
   maskCacheElemPtdmaReadPending, uint32_t * inout_maskCacheElemToInvalidate, uint32_t *
   inout_maskCacheElemToInvalidateRelease) */

InvalidateReturn __thiscall
A53::SramCache4::invalidate
          (SramCache4 *this,uint32_t maskCacheElemPtdmaReadPending,
          uint32_t *inout_maskCacheElemToInvalidate,uint32_t *inout_maskCacheElemToInvalidateRelease
          )

{
  uint uVar1;
  undefined uVar2;
  byte bVar3;
  uint uVar4;
  int iVar5;
  InvalidateReturn IVar6;
  byte bVar7;
  byte bVar8;
  uint uVar9;
  uint uVar10;
  uint uVar11;
  uint uVar12;
  ulong uVar13;
  byte *pbVar14;
  
  uVar9 = *inout_maskCacheElemToInvalidateRelease;
  uVar10 = *inout_maskCacheElemToInvalidate;
  uVar12 = 2;
  bVar3 = *(byte *)((long)&this->field_0 + 2);
  uVar11 = (uint)bVar3;
  do {
    if (7 < uVar12 - 2) {
      *inout_maskCacheElemToInvalidate = uVar10;
      *inout_maskCacheElemToInvalidateRelease = uVar9;
      uVar2 = 0xe4;
      if (uVar10 != 0) {
        uVar2 = (char)uVar11;
      }
      *(undefined *)((long)&this->field_0 + 2) = uVar2;
      IVar6.m_eInvalidateStatus._1_3_ = 0;
      IVar6.m_eInvalidateStatus._0_1_ = uVar10 != 0;
      return (InvalidateReturn)IVar6.m_eInvalidateStatus;
    }
    uVar1 = bVar3 >> (ulong)(uVar12 - 2 & 0x1f) & 3;
    uVar13 = (ulong)uVar1;
    uVar4 = 1 << uVar13;
    if ((uVar10 & uVar4) != 0) {
      if ((uVar4 & maskCacheElemPtdmaReadPending) == 0) {
        pbVar14 = (byte *)((long)&this->field_0 + uVar13 + 4);
        bVar8 = *pbVar14;
        if ((uVar4 & uVar9) == 0) {
          if (bVar8 == 0) goto LAB_060674d8;
LAB_06067524:
          *pbVar14 = bVar8 | 0x80;
        }
        else {
          bVar7 = bVar8;
          if (bVar8 < 0x82) {
            if (bVar8 == 0x81) {
              bVar7 = 0;
              bVar8 = 0;
              goto LAB_06067510;
            }
          }
          else {
            bVar8 = bVar8 - 1;
LAB_06067510:
            *pbVar14 = bVar8;
          }
          uVar9 = uVar9 & (uVar4 ^ 0xffffffff);
          if (bVar7 != 0) goto LAB_06067524;
LAB_060674d8:
          iVar5 = 1 << (ulong)(uVar12 & 0x1f);
          *(undefined4 *)((long)&this->field_0 + uVar13 * 4 + 0x10) = 0;
          uVar11 = iVar5 - 0x101U & uVar11 << 2 | uVar1 | 0x100U - iVar5 & uVar11;
        }
        uVar10 = uVar10 & (uVar4 ^ 0xffffffff);
      }
      else if ((uVar4 & uVar9) == 0) {
        pbVar14 = (byte *)((long)&this->field_0 + uVar13 + 4);
        bVar8 = *pbVar14;
        if ((~bVar8 & 0x7f) != 0) {
          uVar9 = uVar4 | uVar9;
          *pbVar14 = bVar8 + 1 | 0x80;
        }
      }
    }
    uVar12 = uVar12 + 2;
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06067568
 * symbol: getMaskCacheElemIdxMatchingLineId
 * prototype: uint32_t getMaskCacheElemIdxMatchingLineId(SramCache4 * this, uint32_t lineId, uint32_t maskLineIdCompare)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getMaskCacheElemIdxMatchingLineId(SramCache4 * this, uint32_t
   lineId, uint32_t maskLineIdCompare) */

uint32_t __thiscall
A53::SramCache4::getMaskCacheElemIdxMatchingLineId
          (SramCache4 *this,uint32_t lineId,uint32_t maskLineIdCompare)

{
  uint uVar1;
  long lVar2;
  
  uVar1 = 0;
  for (lVar2 = 4; lVar2 != 8; lVar2 = lVar2 + 1) {
    if ((((this->field_0).asU32[lVar2] & maskLineIdCompare) == lineId) &&
       (((long)*(char *)((long)&this->field_0 + lVar2) & 0x80000000U) == 0)) {
      uVar1 = 1 << (ulong)((int)lVar2 - 4U & 0x1f) | uVar1;
    }
  }
  return uVar1;
}


