/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_controller_trace.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c1e8
 * symbol: writeControllerTraceEvent_IbResume
 * prototype: void writeControllerTraceEvent_IbResume(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation, uint32_t ibLocationStart)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_IbResume
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t ibCommandId,
               uint64_t vaIndirectBufferBase,uint32_t numBufferElemsMinus1,uint16_t ringLocation,
               uint32_t ibLocationStart)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_28;
  undefined4 local_20;
  uint uStack_1c;
  uint local_18;
  uint uStack_14;
  
  local_28 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)ibCommandId << 0x10 |
             (ulong)((iCommandRing & 0x1f) << 0xb | 0x108));
  local_18 = numBufferElemsMinus1 & 0xffffff;
  uStack_14 = ibLocationStart & 0xffffff;
  uStack_1c = (uint)(vaIndirectBufferBase >> 0x20) & 0xffff | (uint)ringLocation << 0x10;
  local_20 = (undefined4)vaIndirectBufferBase;
  writeControllerTraceEvent
            (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
             pCallbackContext,(A53ControllerTraceEventHeader *)&local_28.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c24c
 * symbol: writeControllerTraceEvent_IbCall
 * prototype: void writeControllerTraceEvent_IbCall(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_IbCall
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t ibCommandId,
               uint64_t vaIndirectBufferBase,uint32_t numBufferElemsMinus1,uint16_t ringLocation)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_28;
  undefined4 local_20;
  uint uStack_1c;
  uint local_18;
  
  local_28 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)ibCommandId << 0x10 |
             (ulong)((iCommandRing & 0x1f) << 0xb | 0xc9));
  local_18 = numBufferElemsMinus1 & 0xffffff;
  uStack_1c = (uint)(vaIndirectBufferBase >> 0x20) & 0xffff | (uint)ringLocation << 0x10;
  local_20 = (undefined4)vaIndirectBufferBase;
  writeControllerTraceEvent
            (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
             pCallbackContext,(A53ControllerTraceEventHeader *)&local_28.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c2a8
 * symbol: writeControllerTraceEvent_IbChain
 * prototype: void writeControllerTraceEvent_IbChain(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_IbChain
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t ibCommandId,
               uint64_t vaIndirectBufferBase,uint32_t numBufferElemsMinus1)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_28;
  undefined4 local_20;
  uint uStack_1c;
  uint local_18;
  
  local_28 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)ibCommandId << 0x10 |
             (ulong)((iCommandRing & 0x1f) << 0xb | 0xca));
  local_18 = numBufferElemsMinus1 & 0xffffff;
  uStack_1c = (uint)(vaIndirectBufferBase >> 0x20) & 0xffff;
  local_20 = (undefined4)vaIndirectBufferBase;
  writeControllerTraceEvent
            (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
             pCallbackContext,(A53ControllerTraceEventHeader *)&local_28.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c2fc
 * symbol: writeControllerTraceEvent_IbReturn
 * prototype: void writeControllerTraceEvent_IbReturn(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t ibCommandId, uint16_t ringLocation)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_IbReturn
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t ibCommandId,
               uint16_t ringLocation)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_20;
  uint local_18;
  
  local_18 = (uint)ringLocation;
  local_20 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)ibCommandId << 0x10 |
             (ulong)((iCommandRing & 0x1f) << 0xb | 0x4b));
  writeControllerTraceEvent
            (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
             pCallbackContext,(A53ControllerTraceEventHeader *)&local_20.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c340
 * symbol: writeControllerTraceEvent_CommandExecuteEndError
 * prototype: void writeControllerTraceEvent_CommandExecuteEndError(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t execId, uint32_t pid, A53ControllerTraceIsAppErrorCode eIsAppErrorCode, uint8_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_CommandExecuteEndError
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t execId,uint32_t pid,
               A53ControllerTraceIsAppErrorCode eIsAppErrorCode,uint8_t eErrorCode,
               uint64_t addressError,uint16_t pasidError)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_28;
  uint32_t local_20;
  uint uStack_1c;
  undefined4 local_18;
  uint uStack_14;
  
  local_28 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)execId << 0x10 |
             (ulong)((iCommandRing & 0x1f) << 0xb | 0x10d));
  uStack_1c = eErrorCode & 0x7f | (eIsAppErrorCode & 1) << 7;
  local_20 = pid;
  uStack_14 = (uint)(addressError >> 0x20) & 0xffff | (uint)pasidError << 0x10;
  local_18 = (undefined4)addressError;
  writeControllerTraceEvent
            (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
             pCallbackContext,(A53ControllerTraceEventHeader *)&local_28.field_0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063708
 * symbol: spinWaitForPtdmaWriteSpace
 * prototype: void spinWaitForPtdmaWriteSpace(PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::spinWaitForPtdmaWriteSpace
               (PtdmaVqState *ptdmaQueueWrite,A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext)

{
  byte bVar1;
  A53_PtdmaCommandSourceTracker local_48;
  
  bVar1 = (ptdmaQueueWrite->m_submit).m_iVq;
  local_48 = ptdmaSourceTrackerWrite;
  do {
    if ((*(uint *)(&DAT_022c1000 + (ulong)bVar1 * 0x1000) >> 1 & 1) != 0) {
      return;
    }
    updateForPtdmaCompletions
              ((uint)bVar1,ptdmaQueueWrite,&local_48,pfnDmaCmdCompletedCallback,pCallbackContext);
  } while (((ptdmaQueueWrite->m_tail_lo + 0x20) - ptdmaQueueWrite->m_head_lo &
           (ptdmaQueueWrite->m_submit).m_maskVqdPointer) == 0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063790
 * symbol: writeControllerTraceEvent
 * prototype: void writeControllerTraceEvent(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, A53ControllerTraceEventHeader * pHeaderAndData)
 * body addresses: 680
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void A53::writeControllerTraceEvent
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               A53ControllerTraceEventHeader *pHeaderAndData)

{
  uint uVar1;
  OutputRing *this;
  uint64_t uVar2;
  uint64_t uVar3;
  uint64_t uVar4;
  uint64_t uVar5;
  uint64_t uVar6;
  uint8_t uVar7;
  uint16_t pasid;
  ushort uVar8;
  uint uVar9;
  uint uVar10;
  bool bVar11;
  uint32_t uVar12;
  IssuePutReturn IVar13;
  ControllerRingsState *pCVar14;
  int iVar15;
  ulong uVar16;
  uint uVar17;
  OutputRing *pOVar18;
  A53_AddressTranslator local_70 [2];
  A53_PtdmaCommandSourceTracker local_68;
  
  pCVar14 = rings->m_pRingsState;
  uVar17 = *(uint *)((long)&pCVar14->field_0 + 0x30);
  if ((uVar17 >> 0x16 & 1) == 0) {
    pOVar18 = rings->m_paOutputRing;
    uVar2 = (pCVar14->field_0).asU64[4];
    uVar4 = (pCVar14->field_0).field_0.m_maskTraceEventTypeFilter;
    uVar1 = ((pHeaderAndData->field_0).asU32[0] >> 6 & 0x1f) + 2;
    iVar15 = 1 << (ulong)(pOVar18[1].field_0.field_0.m_numCacheElemsLog2 & 0x1f);
    uVar3 = (pCVar14->field_0).asU64[2];
    uVar5 = (pCVar14->field_0).asU64[3];
    uVar9 = ((1 << (ulong)(pOVar18[1].field_0.field_0.m_numRingElemsLog2 & 0x1f)) + iVar15) - 1;
    uVar6 = (pCVar14->field_0).asU64[1];
    uVar10 = uVar9 - pOVar18[1].field_0.field_0.m_count;
    if (uVar10 < uVar1) {
      (pCVar14->field_0).asU64[0] = (pCVar14->field_0).asU64[0];
      (pCVar14->field_0).asU64[1] = uVar6;
      (pCVar14->field_0).asU64[2] = uVar3;
      (pCVar14->field_0).asU64[3] = uVar5;
      (pCVar14->field_0).asU64[4] = uVar2;
      (pCVar14->field_0).field_0.m_maskTraceEventTypeFilter = uVar4;
      *(uint *)((long)&pCVar14->field_0 + 0x30) = uVar17 | 0x800000;
      *(uint *)((long)&rings->m_pRingsState->field_0 + 0x30) =
           *(uint *)((long)&rings->m_pRingsState->field_0 + 0x30) | 0x400000;
    }
    else {
      this = pOVar18 + 1;
      if ((((uVar17 >> 0x18 & 1) == 0) && ((ulong)(uVar17 >> 0x1a) != 0)) &&
         ((ulong)uVar10 - (ulong)uVar1 < (ulong)(uVar17 >> 0x1a) * (ulong)uVar9 >> 6)) {
        (pCVar14->field_0).asU64[0] = (pCVar14->field_0).asU64[0];
        (pCVar14->field_0).asU64[1] = uVar6;
        (pCVar14->field_0).asU64[2] = uVar3;
        (pCVar14->field_0).asU64[3] = uVar5;
        (pCVar14->field_0).asU64[4] = uVar2;
        (pCVar14->field_0).field_0.m_maskTraceEventTypeFilter = uVar4;
        *(uint *)((long)&pCVar14->field_0 + 0x30) = uVar17 | 0x2000000;
        pCVar14 = rings->m_pRingsState;
        uVar17 = *(uint *)((long)&pCVar14->field_0 + 0x30);
        uVar2 = (pCVar14->field_0).asU64[0];
        uVar3 = (pCVar14->field_0).asU64[1];
        (pCVar14->field_0).asU64[4] = (pCVar14->field_0).asU64[4];
        (pCVar14->field_0).field_0.m_maskTraceEventTypeFilter =
             (pCVar14->field_0).field_0.m_maskTraceEventTypeFilter;
        (pCVar14->field_0).asU64[2] = (pCVar14->field_0).asU64[2];
        (pCVar14->field_0).asU64[3] = (pCVar14->field_0).asU64[3];
        (pCVar14->field_0).asU64[0] = uVar2;
        (pCVar14->field_0).asU64[1] = uVar3;
        *(uint *)((long)&pCVar14->field_0 + 0x30) = uVar17 | 0x1000000;
        iVar15 = 1 << (ulong)(pOVar18[1].field_0.field_0.m_numCacheElemsLog2 & 0x1f);
      }
      uVar17 = iVar15 - (uint)pOVar18[1].field_0.field_0.m_countDmaNotComplete;
      local_70[0].m_core = (rings->m_static_config).field_0.asU32 >> 0x1a & 1;
      pasid = *(uint16_t *)
               ((ulong)(rings->m_runtime_config).field_0.field_0.
                       m_vaSramA53Controller_BootConfiguration + 6);
      local_68 = ptdmaSourceTrackerWrite;
      while (uVar17 < uVar1) {
        if ((_DAT_022c4000 >> 1 & 1) != 0) {
          return;
        }
        uVar8 = pOVar18[1].field_0.field_0.m_countDmaNotIssued;
        uVar7 = pOVar18[1].field_0.field_0.m_countPtdmaCommand;
        uVar12 = OutputRing::getNumRingElemsAvailableToPut(this);
        if (((uVar8 != 0) && (uVar7 != '\x03')) &&
           ((uVar12 != 0 &&
            ((-((1 << (ulong)(pOVar18[1].field_0.field_0.m_numRingElemsLog2 & 0x1f)) + 0xfU &
               pOVar18[1].field_0.field_0.m_tail - (uint)uVar8) & 0xf) <= (uint)uVar8)))) {
          if ((ptdmaQueueWrite->m_submit).m_numCommandsAvailable == 0) {
            spinWaitForPtdmaWriteSpace
                      (ptdmaQueueWrite,local_68,pfnDmaCmdCompletedCallback,pCallbackContext);
          }
          IVar13 = OutputRing::issuePut(this,local_70,&ptdmaQueueWrite->m_submit,pasid,0xffffffff);
          if (IVar13.m_numElemsPut != 0) {
            uVar16 = (rings->m_pRingsState->field_0).asU64[3];
            (rings->m_pRingsState->field_0).asU64[3] =
                 uVar16 & 0xfffffffffffffff | (ulong)((uint)(uVar16 >> 0x3c) | 2) << 0x3c;
            if (IVar13.m_ptdmaCmdIdx < local_68.m_numCommands) {
              *(undefined4 *)
               (((ulong)IVar13 >> 0x20 & 0x3fffffff) * 4 + ((ulong)local_68 & 0xffffffff)) =
                   0xa0000601;
            }
            PtdmaVqState::submit(ptdmaQueueWrite);
          }
        }
        bVar11 = updateForPtdmaCompletions
                           ((uint)(ptdmaQueueWrite->m_submit).m_iVq,ptdmaQueueWrite,&local_68,
                            pfnDmaCmdCompletedCallback,pCallbackContext);
        if (bVar11) {
          uVar17 = (1 << (ulong)(pOVar18[1].field_0.field_0.m_numCacheElemsLog2 & 0x1f)) -
                   (uint)pOVar18[1].field_0.field_0.m_countDmaNotComplete;
        }
      }
      uVar12 = OutputRing::writeElements<unsigned_int>
                         (this,((pHeaderAndData->field_0).asU32[0] >> 6 & 0x1f) + 2,
                          (uint *)pHeaderAndData,0);
      OutputRing::pushElements(this,uVar12);
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063a38
 * symbol: writeElements<unsigned_int>
 * prototype: uint32_t writeElements<unsigned_int>(OutputRing * this, uint32_t numElems, uint * aElem, uint32_t indexFromTail)
 * body addresses: 112
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: writeElements<unsigned int>
   DWARF original prototype: uint32_t writeElements<unsigned_int>(OutputRing * this, uint32_t
   numElems, uint * aElem, uint32_t indexFromTail) */

uint32_t __thiscall
A53::OutputRing::writeElements<unsigned_int>
          (OutputRing *this,uint32_t numElems,uint *aElem,uint32_t indexFromTail)

{
  uint32_t uVar1;
  int iVar2;
  ulong uVar3;
  
  iVar2 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
  if (iVar2 - (uint)(this->field_0).field_0.m_countDmaNotComplete < indexFromTail + numElems) {
    numElems = 0;
  }
  else {
    uVar1 = (this->field_0).field_0.m_tail;
    for (uVar3 = 0; numElems != uVar3; uVar3 = uVar3 + 1) {
      *(uint *)((this->field_0).field_0.m_vaSramCache +
               (ulong)((uVar1 + indexFromTail + (int)uVar3 & iVar2 - 1U) <<
                      (ulong)((this->field_0).field_0.m_sizeofElemLog2 & 0x1f))) = aElem[uVar3];
    }
  }
  return numElems;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063aa8
 * symbol: writeControllerTraceEvent_Marker
 * prototype: void writeControllerTraceEvent_Marker(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t commandId, A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData)
 * body addresses: 236
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::writeControllerTraceEvent_Marker
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t commandId,
               A53ControllerCommandHeader *cmdHeader,uint32_t *aCmdData)

{
  uint *in_stack_00000000;
  undefined4 *in_stack_00000008;
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_58;
  uint local_50;
  undefined4 local_4c;
  undefined4 local_48;
  undefined4 local_44;
  undefined4 local_40;
  undefined4 local_3c;
  undefined4 local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  
  local_50 = *in_stack_00000000;
  local_58 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)commandId << 0x10 |
             (ulong)((local_50 >> 2 & 0x3c0) + 0x40 | (iCommandRing & 0x1f) << 0xb | 4));
  switch(local_50 >> 8 & 0xf) {
  default:
    local_14 = in_stack_00000008[0xe];
  case 0xe:
    local_18 = in_stack_00000008[0xd];
  case 0xd:
    local_1c = in_stack_00000008[0xc];
  case 0xc:
    local_20 = in_stack_00000008[0xb];
  case 0xb:
    local_24 = in_stack_00000008[10];
  case 10:
    local_28 = in_stack_00000008[9];
  case 9:
    local_2c = in_stack_00000008[8];
  case 8:
    local_30 = in_stack_00000008[7];
  case 7:
    local_34 = in_stack_00000008[6];
  case 6:
    local_38 = in_stack_00000008[5];
  case 5:
    local_3c = in_stack_00000008[4];
  case 4:
    local_40 = in_stack_00000008[3];
  case 3:
    local_44 = in_stack_00000008[2];
  case 2:
    local_48 = in_stack_00000008[1];
  case 1:
    local_4c = *in_stack_00000008;
  case 0:
    writeControllerTraceEvent
              (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
               pCallbackContext,(A53ControllerTraceEventHeader *)&local_58.field_0);
    return;
  }
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063b94
 * symbol: writeControllerTraceEvent_CommandExecuteBegin
 * prototype: void writeControllerTraceEvent_CommandExecuteBegin(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t commandId, uint16_t execId, uint32_t iPipeline, uint32_t pid, A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData)
 * body addresses: 256
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_CommandExecuteBegin
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t commandId,uint16_t execId,
               uint32_t iPipeline,uint32_t pid,A53ControllerCommandHeader *cmdHeader,
               uint32_t *aCmdData)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_60;
  uint32_t local_58;
  uint uStack_54;
  uint local_50;
  uint32_t local_4c;
  uint32_t local_48;
  uint32_t local_44;
  uint32_t local_40;
  uint32_t local_3c;
  uint32_t local_38;
  uint32_t local_34;
  uint32_t local_30;
  uint32_t local_2c;
  uint32_t local_28;
  uint32_t local_24;
  uint32_t local_20;
  uint32_t local_1c;
  uint32_t local_18;
  uint32_t local_14;
  
  local_50 = (cmdHeader->field_0).asU32;
  uStack_54 = (uint)execId | (iPipeline & 0xf) << 0x10;
  local_60 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)commandId << 0x10 |
             (ulong)((local_50 >> 2 & 0x3c0) + 0xc0 | (iCommandRing & 0x1f) << 0xb | 5));
  local_58 = pid;
  switch(local_50 >> 8 & 0xf) {
  default:
    local_14 = aCmdData[0xe];
  case 0xe:
    local_18 = aCmdData[0xd];
  case 0xd:
    local_1c = aCmdData[0xc];
  case 0xc:
    local_20 = aCmdData[0xb];
  case 0xb:
    local_24 = aCmdData[10];
  case 10:
    local_28 = aCmdData[9];
  case 9:
    local_2c = aCmdData[8];
  case 8:
    local_30 = aCmdData[7];
  case 7:
    local_34 = aCmdData[6];
  case 6:
    local_38 = aCmdData[5];
  case 5:
    local_3c = aCmdData[4];
  case 4:
    local_40 = aCmdData[3];
  case 3:
    local_44 = aCmdData[2];
  case 2:
    local_48 = aCmdData[1];
  case 1:
    local_4c = *aCmdData;
  case 0:
    writeControllerTraceEvent
              (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
               pCallbackContext,(A53ControllerTraceEventHeader *)&local_60.field_0);
    return;
  }
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06063c94
 * symbol: writeControllerTraceEvent_CommandExecuteEnd
 * prototype: void writeControllerTraceEvent_CommandExecuteEnd(ControllerRings * rings, PtdmaVqState * ptdmaQueueWrite, A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite, PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback, void * pCallbackContext, uint32_t timestamp100MHz, uint32_t iCommandRing, uint16_t execId, uint32_t pid, uint32_t returnValue)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void A53::writeControllerTraceEvent_CommandExecuteEnd
               (ControllerRings *rings,PtdmaVqState *ptdmaQueueWrite,
               A53_PtdmaCommandSourceTracker ptdmaSourceTrackerWrite,
               PtdmaCmdCompletedCallback pfnDmaCmdCompletedCallback,void *pCallbackContext,
               uint32_t timestamp100MHz,uint32_t iCommandRing,uint16_t execId,uint32_t pid,
               uint32_t returnValue)

{
  anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0 local_20;
  uint32_t local_18;
  uint32_t uStack_14;
  
  local_20 = (anon_union_8_2_653be89a_for_A53ControllerTraceEventHeader_0)
             ((ulong)timestamp100MHz << 0x20 | (ulong)execId << 0x10 |
             (ulong)((iCommandRing & 0x1f) << 0xb | 0x8c));
  local_18 = pid;
  uStack_14 = returnValue;
  writeControllerTraceEvent
            (rings,ptdmaQueueWrite,ptdmaSourceTrackerWrite,pfnDmaCmdCompletedCallback,
             pCallbackContext,(A53ControllerTraceEventHeader *)&local_20.field_0);
  return;
}


