/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/dram/../a53_psp_message_ring.cpp
 * Language recorded in DWARF: referenced source
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c5c0
 * symbol: pspMessageRing_writeError
 * prototype: void pspMessageRing_writeError(uint64_t vaSramA53Controller_PSP_MessageRing, uint32_t ringElemIdx, A53Controller_PSP_Error * error)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::pspMessageRing_writeError
               (uint64_t vaSramA53Controller_PSP_MessageRing,uint32_t ringElemIdx,
               A53Controller_PSP_Error *error)

{
  long lVar1;
  uint64_t uVar2;
  ulong uVar3;
  ulong uVar4;
  
  lVar1 = vaSramA53Controller_PSP_MessageRing + (ulong)ringElemIdx * 0x20;
  uVar2 = (error->field_0).asU64[1];
  *(uint64_t *)(lVar1 + 0x20) = (error->field_0).asU64[0];
  *(uint64_t *)(lVar1 + 0x28) = uVar2;
  uVar2 = (error->field_0).asU64[3];
  uVar4 = (ulong)(uint64_t *)(lVar1 + 0x20) & 0xffffffffffffffc0;
  uVar3 = lVar1 + 0x3fU & 0xffffffffffffffc0;
  *(uint64_t *)(lVar1 + 0x30) = (error->field_0).asU64[2];
  *(uint64_t *)(lVar1 + 0x38) = uVar2;
  DC_CVAC(vaSramA53Controller_PSP_MessageRing);
  if (uVar4 != vaSramA53Controller_PSP_MessageRing) {
    DC_CVAC(uVar4);
  }
  if (uVar3 != uVar4) {
    DC_CVAC(uVar3);
  }
  DataSynchronizationBarrier(3,3);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c60c
 * symbol: pspMessageRing_fakePspRingHeadAdvance
 * prototype: void pspMessageRing_fakePspRingHeadAdvance(uint64_t vaSramA53Controller_PSP_MessageRing)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::pspMessageRing_fakePspRingHeadAdvance(uint64_t vaSramA53Controller_PSP_MessageRing)

{
  int iVar1;
  int *piVar2;
  
  piVar2 = (int *)(*(ulong *)(vaSramA53Controller_PSP_MessageRing + 8) >> 0x20);
  iVar1 = *piVar2;
  if ((uint)(((int)*(undefined8 *)vaSramA53Controller_PSP_MessageRing + -1) - iVar1) <
      (uint)(1 << (ulong)((uint)((ulong)*(undefined8 *)vaSramA53Controller_PSP_MessageRing >> 0x20)
                         & 0x1f))) {
    *piVar2 = iVar1 + 1;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c644
 * symbol: pspMessageRing_allocateEntry
 * prototype: bool pspMessageRing_allocateEntry(uint32_t p2smsgIdx, uint32_t a53CoreIdx, uint64_t vaSramA53Controller_PSP_MessageRing, PushPspErrorBlocking eBlocking, uint32_t * out_ringElemIdx)
 * body addresses: 184
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pspMessageRing_allocateEntry
               (uint32_t p2smsgIdx,uint32_t a53CoreIdx,uint64_t vaSramA53Controller_PSP_MessageRing,
               PushPspErrorBlocking eBlocking,uint32_t *out_ringElemIdx)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  int *piVar5;
  uint uVar6;
  int iVar7;
  ulong uVar8;
  
  piVar5 = (int *)(*(ulong *)(vaSramA53Controller_PSP_MessageRing + 8) >> 0x20);
  DC_CIVAC((ulong)piVar5 & 0xffffffc0);
  UnkSytemRegWrite(0,3,3,0xd,4,0);
  iVar7 = *piVar5;
  uVar3 = 1 << (ulong)((uint)((ulong)*(undefined8 *)vaSramA53Controller_PSP_MessageRing >> 0x20) &
                      0x1f);
  uVar4 = (uint)*(undefined8 *)vaSramA53Controller_PSP_MessageRing;
  uVar6 = uVar4 - iVar7;
  if (uVar3 <= uVar6) {
    uVar8 = (ulong)(a53CoreIdx * 4 + 0x700);
    uVar1 = p2smsgIdx & 1 | 0xffe;
    if (uVar3 < uVar6) {
      *(uint *)(uVar8 + 0x2010000) = uVar1;
    }
    do {
      DC_CIVAC((ulong)piVar5 & 0xffffffc0);
      UnkSytemRegWrite(0,3,3,0xd,4,0);
      iVar2 = *piVar5;
      if ((iVar2 != iVar7) && (uVar6 = uVar4 - iVar2, iVar7 = iVar2, uVar3 < uVar6)) {
        *(uint *)(uVar8 + 0x2010000) = uVar1;
      }
    } while (uVar3 < uVar6 + eBlocking);
  }
  if (uVar6 != uVar3) {
    *(uint *)vaSramA53Controller_PSP_MessageRing = uVar4 + 1;
    *out_ringElemIdx = uVar3 - 1 & uVar4;
    return true;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c6fc
 * symbol: pspMessageRing_writeErrorAndInitiatePspInterrupt
 * prototype: void pspMessageRing_writeErrorAndInitiatePspInterrupt(uint32_t p2smsgIdx, uint32_t a53CoreIdx, uint64_t vaSramA53Controller_PSP_MessageRing, uint32_t ringElemIdx, A53Controller_PSP_Error * error)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::pspMessageRing_writeErrorAndInitiatePspInterrupt
               (uint32_t p2smsgIdx,uint32_t a53CoreIdx,uint64_t vaSramA53Controller_PSP_MessageRing,
               uint32_t ringElemIdx,A53Controller_PSP_Error *error)

{
  pspMessageRing_writeError(vaSramA53Controller_PSP_MessageRing,ringElemIdx,error);
  *(uint32_t *)((ulong)(p2smsgIdx * 4 + 0x700) + 0x2010000) =
       a53CoreIdx & 1 | (ringElemIdx & 0x3ff) << 2 | ((error->field_0).asU32[0] & 0x1f) << 0x14 |
       (error->field_0).asU32[2] << 0x19 | 2;
  pspMessageRing_fakePspRingHeadAdvance(vaSramA53Controller_PSP_MessageRing);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c778
 * symbol: pspMessageRing_pushError
 * prototype: bool pspMessageRing_pushError(uint32_t p2smsgIdx, uint32_t a53CoreIdx, uint64_t vaSramA53Controller_PSP_MessageRing, PushPspErrorBlocking eBlocking, A53Controller_PSP_Error * error)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pspMessageRing_pushError
               (uint32_t p2smsgIdx,uint32_t a53CoreIdx,uint64_t vaSramA53Controller_PSP_MessageRing,
               PushPspErrorBlocking eBlocking,A53Controller_PSP_Error *error)

{
  bool bVar1;
  uint32_t local_34;
  
  bVar1 = pspMessageRing_allocateEntry
                    (p2smsgIdx,a53CoreIdx,vaSramA53Controller_PSP_MessageRing,eBlocking,&local_34);
  if (bVar1) {
    pspMessageRing_writeErrorAndInitiatePspInterrupt
              (p2smsgIdx,a53CoreIdx,vaSramA53Controller_PSP_MessageRing,local_34,error);
  }
  return bVar1;
}


