/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/../controller/a53_dvm.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060065a8
 * symbol: dvmGetNumPow2Commands
 * prototype: uint32_t dvmGetNumPow2Commands(uint64_t sysva_base, uint64_t sysva_limit)
 * body addresses: 172
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::dvmGetNumPow2Commands(uint64_t sysva_base,uint64_t sysva_limit)

{
  int iVar1;
  uint uVar2;
  ulong uVar4;
  ulong uVar5;
  ulong uVar6;
  ulong uVar7;
  uint64_t uVar3;
  
  uVar5 = sysva_base >> 0xc & 0xfffffffff;
  uVar4 = sysva_limit >> 0xc & 0xfffffffff;
  uVar6 = uVar4 - uVar5;
  if (uVar4 < uVar5 || uVar6 == 0) {
    return 0;
  }
  if (((uVar6 | uVar5) & uVar6 - 1) != 0) {
    uVar6 = 0x8000000000000000 >> (LZCOUNT(uVar4 ^ uVar5) & 0x3fU);
    uVar7 = uVar6 - 1;
    uVar6 = uVar6 - (uVar7 & uVar5);
    uVar7 = uVar7 & uVar4;
    if ((uVar6 - 1 & uVar6) == 0) {
      iVar1 = 1;
    }
    else {
      uVar3 = CountBits64(uVar6);
      iVar1 = (int)uVar3;
    }
    if ((uVar7 + 0xfffffffff & uVar7) == 0) {
      uVar2 = (uint)(uVar7 != 0);
    }
    else {
      uVar3 = CountBits64(uVar7);
      uVar2 = (uint)uVar3;
    }
    return uVar2 + iVar1;
  }
  return 1;
}


