/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_interrupt_context_ring.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c3a8
 * symbol: interruptContextRing_pushCommandError
 * prototype: uint32_t interruptContextRing_pushCommandError(OutputRing * outputRing, uint32_t iInputCommandRing, uint16_t ringLocationError, uint16_t ibCommandIdError, uint32_t pid, uint32_t opCode, ErrorCodeType eErrorCodeType, uint32_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::interruptContextRing_pushCommandError
                   (OutputRing *outputRing,uint32_t iInputCommandRing,uint16_t ringLocationError,
                   uint16_t ibCommandIdError,uint32_t pid,uint32_t opCode,
                   ErrorCodeType eErrorCodeType,uint32_t eErrorCode,uint64_t addressError,
                   uint16_t pasidError)

{
  uint32_t uVar1;
  A53Controller_InterruptContextRingEntry local_30;
  
  local_30.field_0.asU64[1] = (uint64_t)(opCode & 0x7f);
  local_30.field_0.asU64[0] =
       (ulong)((iInputCommandRing & 0x1f) << 3) | (ulong)ringLocationError << 0x10 |
       (ulong)pid << 0x20 | (ulong)((eErrorCodeType & 1) << 0xf) | (ulong)((eErrorCode & 0x7f) << 8)
       | 1;
  local_30.field_0.asAppKernelEventFlag.m_bitPattern = (ulong)(ibCommandIdError & 0x1fff) << 0x30;
  local_30.field_0.asAppKernelEventQueue.m_udata =
       addressError & 0xffffffffffff | (ulong)pasidError << 0x30;
  uVar1 = interruptContextRing_pushEntry(outputRing,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c40c
 * symbol: interruptContextRing_pushEntry
 * prototype: uint32_t interruptContextRing_pushEntry(OutputRing * outputRing, A53Controller_InterruptContextRingEntry * entry)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::interruptContextRing_pushEntry
                   (OutputRing *outputRing,A53Controller_InterruptContextRingEntry *entry)

{
  ushort uVar1;
  uint32_t uVar2;
  uint32_t uVar3;
  
  uVar1 = *(ushort *)((long)&outputRing->field_0 + 0x28);
  uVar2 = OutputRing::pushElement<A53Controller_InterruptContextRingEntry>(outputRing,entry);
  uVar3 = (uint32_t)uVar1;
  if (uVar2 != 1) {
    uVar3 = 0xffffffff;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c434
 * symbol: interruptContextRing_pushCommandError
 * prototype: uint32_t interruptContextRing_pushCommandError(OutputRing * outputRing, uint32_t iInputCommandRing, uint16_t ringLocationError, uint64_t vaIndirectBufferBaseError, uint32_t numBufferElemsMinus1Error, uint32_t ibLocationError, uint16_t ibCommandIdError, uint32_t pid, uint32_t opCode, ErrorCodeType eErrorCodeType, uint32_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::interruptContextRing_pushCommandError
                   (OutputRing *outputRing,uint32_t iInputCommandRing,uint16_t ringLocationError,
                   uint64_t vaIndirectBufferBaseError,uint32_t numBufferElemsMinus1Error,
                   uint32_t ibLocationError,uint16_t ibCommandIdError,uint32_t pid,uint32_t opCode,
                   ErrorCodeType eErrorCodeType,uint32_t eErrorCode,uint64_t addressError,
                   uint16_t pasidError)

{
  uint32_t uVar1;
  A53Controller_InterruptContextRingEntry local_30;
  
  local_30.field_0.asAppKernelEventFlag.m_bitPattern =
       vaIndirectBufferBaseError & 0xffffffffffff | (ulong)(ibCommandIdError & 0x1fff) << 0x30;
  local_30.field_0.asU64[1] =
       (ulong)(ibLocationError << 8) | (ulong)opCode & 0x7f |
       (ulong)(numBufferElemsMinus1Error & 0xffffff) << 0x20 | 0x80;
  local_30.field_0.asU64[0] =
       (ulong)((eErrorCode & 0x7f) << 8 | (eErrorCodeType & 1) << 0xf) |
       (ulong)((iInputCommandRing & 0x1f) << 3) | (ulong)ringLocationError << 0x10 |
       (ulong)pid << 0x20 | 1;
  local_30.field_0.asAppKernelEventQueue.m_udata =
       addressError & 0xffffffffffff | (ulong)pasidError << 0x30;
  uVar1 = interruptContextRing_pushEntry(outputRing,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c4b4
 * symbol: interruptContextRing_pushAppKernelEventFlag
 * prototype: uint32_t interruptContextRing_pushAppKernelEventFlag(OutputRing * outputRing, uint32_t iInputCommandRing, uint16_t ringLocation, uint32_t pid, uint64_t ef, uint64_t bitPattern, uint32_t isClear)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::interruptContextRing_pushAppKernelEventFlag
                   (OutputRing *outputRing,uint32_t iInputCommandRing,uint16_t ringLocation,
                   uint32_t pid,uint64_t ef,uint64_t bitPattern,uint32_t isClear)

{
  uint32_t uVar1;
  A53Controller_InterruptContextRingEntry local_30;
  
  local_30.field_0.asAppKernelEventQueue.m_udata = 0;
  local_30.field_0.asU64[1] = ef & 0xffffffffffff;
  local_30.field_0.asU64[0] =
       (ulong)((iInputCommandRing & 0x1f) << 3) | (ulong)ringLocation << 0x10 | (ulong)pid << 0x20 |
       (ulong)((isClear & 1) << 8) | 2;
  local_30.field_0.asAppKernelEventFlag.m_bitPattern = bitPattern;
  uVar1 = interruptContextRing_pushEntry(outputRing,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c4fc
 * symbol: interruptContextRing_pushNotification
 * prototype: uint32_t interruptContextRing_pushNotification(OutputRing * outputRing, A53ControllerNotificationInterruptType eNotificationType, uint32_t payload)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::interruptContextRing_pushNotification
                   (OutputRing *outputRing,A53ControllerNotificationInterruptType eNotificationType,
                   uint32_t payload)

{
  uint32_t uVar1;
  A53Controller_InterruptContextRingEntry local_30;
  
  local_30.field_0.asAppKernelEventFlag.m_bitPattern = 0;
  local_30.field_0.asAppKernelEventQueue.m_udata = 0;
  local_30.field_0.asU64[0] = CONCAT44(payload,(eNotificationType & 0xff) << 8) | 4;
  local_30.field_0.asU64[1] = 0;
  uVar1 = interruptContextRing_pushEntry(outputRing,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066120
 * symbol: interruptContextRing_pushSystemCommandCompletion
 * prototype: uint32_t interruptContextRing_pushSystemCommandCompletion(OutputRing * outputRing, uint32_t iInputCommandRing, uint16_t ringLocation, uint32_t pid, uint32_t opCode, uint32_t returnValue)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::interruptContextRing_pushSystemCommandCompletion
                   (OutputRing *outputRing,uint32_t iInputCommandRing,uint16_t ringLocation,
                   uint32_t pid,uint32_t opCode,uint32_t returnValue)

{
  uint32_t uVar1;
  A53Controller_InterruptContextRingEntry local_30;
  
  local_30.field_0.asAppKernelEventFlag.m_bitPattern = 0;
  local_30.field_0.asAppKernelEventQueue.m_udata = 0;
  local_30.field_0.asU64[0] =
       (ulong)((iInputCommandRing & 0x1f) << 3) | (ulong)ringLocation << 0x10 | (ulong)pid << 0x20;
  local_30.field_0.asU64[1] = CONCAT44(returnValue,opCode) & 0xffffffff0000007f;
  uVar1 = interruptContextRing_pushEntry(outputRing,&local_30);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066168
 * symbol: interruptContextRing_pushEntry
 * prototype: uint32_t interruptContextRing_pushEntry(OutputRing * outputRing, A53Controller_InterruptContextRingEntry * entry)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::interruptContextRing_pushEntry
                   (OutputRing *outputRing,A53Controller_InterruptContextRingEntry *entry)

{
  ushort uVar1;
  uint32_t uVar2;
  uint32_t uVar3;
  
  uVar1 = *(ushort *)((long)&outputRing->field_0 + 0x28);
  uVar2 = OutputRing::pushElement<A53Controller_InterruptContextRingEntry>(outputRing,entry);
  uVar3 = (uint32_t)uVar1;
  if (uVar2 != 1) {
    uVar3 = 0xffffffff;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066190
 * symbol: interruptContextRing_pushAppKernelEventQueue
 * prototype: uint32_t interruptContextRing_pushAppKernelEventQueue(OutputRing * outputRing, uint32_t iInputCommandRing, uint16_t ringLocation, uint32_t pid, uint64_t eq, int32_t id, uint64_t udata)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::interruptContextRing_pushAppKernelEventQueue
                   (OutputRing *outputRing,uint32_t iInputCommandRing,uint16_t ringLocation,
                   uint32_t pid,uint64_t eq,int32_t id,uint64_t udata)

{
  uint32_t uVar1;
  undefined local_30 [20];
  undefined4 uStack_1c;
  undefined8 uStack_18;
  
  uStack_1c = 0;
  local_30._16_4_ = id;
  local_30._8_8_ = eq & 0xffffffffffff;
  local_30._0_8_ =
       (ulong)((iInputCommandRing & 0x1f) << 3) | (ulong)ringLocation << 0x10 | (ulong)pid << 0x20 |
       3;
  uStack_18 = udata;
  uVar1 = interruptContextRing_pushEntry
                    (outputRing,(A53Controller_InterruptContextRingEntry *)local_30);
  return uVar1;
}


