/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/a53_controller_pipeline_common.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00000000
 * symbol: readElement<unsigned_int>
 * prototype: uint32_t readElement<unsigned_int>(ConstSramRingView * this, uint32_t ringLocation, uint * elem)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElement<unsigned int>
   DWARF original prototype: uint32_t readElement<unsigned_int>(ConstSramRingView * this, uint32_t
   ringLocation, uint * elem)
   DWARF alternate signature: uint16_t getElementIndexFromHead(MmControllerPipelineRwRing * this,
   uint16_t indexFromHead)
   DWARF alternate signature: bool getPipelineCommandDataHeader(ConstSramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader *
   out_pipelineCmdDataHeader)
   DWARF alternate signature: bool peekCommandDataElements(ControllerRings * rings, uint32_t
   iCommandRing, uint32_t cmdDataElemIdx, uint32_t numCmdElems, uint32_t * aElem)
   DWARF alternate signature: void submit(PtdmaVqState * this)
   DWARF alternate signature: void mmControllerHaltAndError(MmController * this,
   MmControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError)
   DWARF alternate signature: bool peekElements<unsigned_int>(InputRing * this, uint32_t numElems,
   uint * aElem, uint32_t indexFromHead)
   DWARF alternate signature: bool peekElements<unsigned_int>(InputIndirectBuffer * this, uint32_t
   numElems, uint * aElem, uint32_t indexFromHead)
   DWARF alternate signature: uint32_t
   getIndexFromHeadFromRingLocation(MmControllerPipelineGcrPageLockRing * this, uint16_t
   ringLocation)
   DWARF alternate signature: void mm_trace_write_event_CommandExecuteBegin(MmController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t
   commandId, uint16_t commandRingExecutingCommandId, MmPipeline ePipeline, uint32_t pid,
   A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData)
   DWARF alternate signature: void reset(PipelineStageInfo * this)
   DWARF alternate signature: uint32_t readElementsWrapped<unsigned_int>(ConstSramRingView * this,
   uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, uint * aElem)
   DWARF alternate signature: void getPipelineStageInfo(MmPipelineApp * this, SramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId, A53ControllerCommandHeader
   cmdHeader, PipelineStageInfo * out_stageInfo)
   DWARF alternate signature: uint16_t getIndexFromHeadFromRingLocation(MmControllerPipelineRwRing *
   this, uint16_t ringLocation)
   DWARF alternate signature: uint32_t getIndexFromHeadFromRingLocation(ConstSramRingView * this,
   uint16_t ringLocation)
   DWARF alternate signature: uint16_t getElementIndexBackwardFromTail(MmControllerPipelineRwRing *
   this, Section section, uint16_t indexBeforeTail)
   DWARF alternate signature: uint16_t getElementIndexFromHead(MmControllerPipelineRwRing * this,
   Section section, uint16_t indexFromHead)
   DWARF alternate signature: uint16_t getElementIndexTail(MmControllerPipelineRwRing * this)
   DWARF alternate signature: bool canPushAndRead(MmControllerPipelineRwRing * this, uint32_t uid)
   DWARF alternate signature: bool canPushNElements(MmControllerPipelineRwRing * this, uint32_t
   numElems)
   DWARF alternate signature: bool popElements(MmControllerPipelineRwRing * this, uint32_t numElems)
   DWARF alternate signature: void advanceHead(MmControllerPipelineRwRing * this, uint32_t numElems)
   DWARF alternate signature: bool canPushPdeIndex(MmControllerPipelinePdeRing * this, uint16_t
   pdeIndex)
   DWARF alternate signature: void pushElement(MmControllerPipelinePdeRing * this, uint16_t
   pdeIndex)
   DWARF alternate signature: uint64_t vaAttributeToGpuvmPde(uint32_t attr)
   DWARF alternate signature: uint64_t vaAttributeToGpuvmPte(uint32_t attr)
   DWARF alternate signature: CompletionResult
   checkRingIdmaCompletion<A53::MmControllerPipeline16KiBPagePresentBitsRing>(MmControllerPipeline16KiBPagePresentBitsRing
   * ring, PipelineStageInfo * stageInfo, uint32_t ringIdx, uint32_t i2MiBOffsetEnd)
   DWARF alternate signature: CompletionResult
   checkRingIdmaCompletion<A53::MmControllerPipelineGpuVmPde0Ring>(MmControllerPipelineGpuVmPde0Ring
   * ring, PipelineStageInfo * stageInfo, uint32_t ringIdx, uint32_t i2MiBOffsetEnd)
   DWARF alternate signature: uint32_t readElement<unsigned_long>(MmControllerPipelineRwRing * this,
   Section section, uint32_t ringLocation, ulong * elem)
   DWARF alternate signature: void pushElement(MmControllerPipelineGpuVmPde0Ring * this, uint16_t
   gpuVmPde0Index, bool bNeedIdma)
   DWARF alternate signature: void pushElement(MmControllerPipeline16KiBPagePresentBitsRing * this,
   uint16_t ptIndex, uint32_t i2MiBOffset, bool bNeedIdma)
   DWARF alternate signature: void markWorkComplete(MmControllerPipelineRwRing * this, uint16_t
   elementIndex)
   DWARF alternate signature: uint32_t writeElement<unsigned_long>(MmControllerPipelineRwRing *
   this, Section section, uint32_t ringLocation, ulong * elem)
   DWARF alternate signature: bool canPushAndWriteNElements(MmControllerPipelineGpuVmPt0Ring * this,
   uint32_t numElems)
   DWARF alternate signature: void pushAndWritePte16KiB(MmPipelineApp * this, uint16_t ptIndex,
   uint8_t pte16KiBIndex, uint64_t pteStartEntry, uint32_t i2MiBOffset, PipelineStageInfo *
   stageInfo)
   DWARF alternate signature: void pushAndWriteGpuVmPt1(MmPipelineApp * this, uint16_t ptIndex,
   uint8_t gpuVmPt1Index, uint64_t pt1Entry, uint32_t i2MiBOffset, PipelineStageInfo * stageInfo)
   DWARF alternate signature: void pushAndWriteGpuVmPt0(MmPipelineApp * this, uint16_t ptIndex,
   uint8_t gpuVmPt016KiBIndex, uint64_t pt0Entry, uint32_t i2MiBOffset, PipelineStageInfo *
   stageInfo)
   DWARF alternate signature: uint32_t
   writeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, Section section,
   uint32_t ringLocation, PT_POOL_ENTRY * elem)
   DWARF alternate signature: uint32_t
   readElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, Section section, uint32_t
   ringLocation, PT_POOL_ENTRY * elem)
   DWARF alternate signature: void setStateBit(MmControllerPipelineRwRing * this, StateBitArray
   state, uint16_t elementIndex, bool bEnable)
   DWARF alternate signature: bool canPushAndWriteNElements(MmControllerPipelineRwRing * this,
   uint32_t numElems)
   DWARF alternate signature: void pushAndWriteElement(MmControllerPipelinePte16KiBRing * this,
   uint16_t ptIndex, uint8_t pte16KiBIndex, uint32_t i2MiBOffset, uint64_t pteStartEntry)
   DWARF alternate signature: uint32_t
   writeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t ringLocation, ElementData * elem)
   DWARF alternate signature: void
   storeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, ElementData * elem)
   DWARF alternate signature: void pushAndWriteElement(MmControllerPipelineGpuVmPt1Ring * this,
   uint16_t ptIndex, uint8_t gpuVmPt1Index, uint32_t i2MiBOffset, uint64_t pt1Entry)
   DWARF alternate signature: uint32_t writeElement<unsigned_long>(MmControllerPipelineRwRing *
   this, uint32_t ringLocation, ulong * elem)
   DWARF alternate signature: void pushAndWriteElement(MmControllerPipelineGpuVmPt0Ring * this,
   uint16_t ptIndex, uint8_t gpuVmPt016KiBIndex, uint32_t i2MiBOffset, uint64_t gpuVmPt0StartEntry)
   DWARF alternate signature: uint32_t
   writeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t ringLocation, ElementData * elem)
   DWARF alternate signature: void
   storeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, ElementData * elem)
   DWARF alternate signature: uint32_t readElement<unsigned_long>(MmControllerPipelineRwRing * this,
   uint32_t ringLocation, ulong * elem)
   DWARF alternate signature: uint32_t
   writeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t ringLocation,
   PT_POOL_ENTRY * elem)
   DWARF alternate signature: void storeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing
   * this, uint32_t iRingElem, PT_POOL_ENTRY * elem)
   DWARF alternate signature: uint32_t
   readElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t ringLocation,
   PT_POOL_ENTRY * elem)
   DWARF alternate signature: void loadElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, PT_POOL_ENTRY * elem)
   DWARF alternate signature: bool getCommandRingExecutingCommand(ConstSramRingView *
   sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId,
   CommandRingExecutingCommand * out_commandRingExecutingCommand)
   DWARF alternate signature: uint16_t getElementIndexTail(ConstSramRingView * this)
   DWARF alternate signature: uint32_t writeElement<unsigned_int>(SramRingView * this, uint32_t
   ringLocation, uint * elem)
   DWARF alternate signature: uint32_t readElement<unsigned_short>(ConstSramRingView * this,
   uint32_t ringLocation, unsigned short * elem)
   DWARF alternate signature: void IoController_BootConfiguration_getTitaniaMemory(uint64_t
   vaSramBootConfiguration, uint64_t * out_ttnvaTitania, uint64_t * out_sizeTitania, uint64_t *
   out_paSyshubTitania)
   DWARF alternate signature: void
   A53Controller_BootConfiguration_KernelShared_getRingSizes(uint64_t
   vaSramBootConfiguration_KernelShared, uint8_t * out_numElementsLog2InterruptContextRing, uint32_t
   kNumA53ControllerInputCommandRings, uint8_t * out_aNumElementsLog2CommandRing)
   DWARF alternate signature: void
   A53Controller_BootConfiguration_KernelShared_getPaDebugRingSizes(uint64_t
   vaSramBootConfiguration_KernelShared, uint32_t kNumA53ControllerPaDebugOutputRings, uint8_t *
   out_aNumElementsLog2PaDebugOutputRing)
   DWARF alternate signature: void IoController_BootConfiguration_Titania_getTitaniaMemory(uint64_t
   vaSramBootConfiguration_Titania, uint64_t * out_ttnvaTitania, uint64_t * out_sizeTitania,
   uint64_t * out_paSyshubTitania)
   DWARF alternate signature: void init(PtdmaVqState * this, uint32_t iVq, uint64_t
   vaSramPtdmaQueue)
   DWARF alternate signature: SramRingView
   getSramRingView_PipelineCommandData_DramPipeline_OpIssue(IoController * this, IoDramPipeline
   eIoDramPipeline)
   DWARF alternate signature: uint32_t getPipelineCommandData_pid(ConstSramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId)
   DWARF alternate signature: bool getSysNsid2CommandRingExecutingCommand(ConstSramRingView *
   sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId,
   SysNsid2CommandRingExecutingCommand * out_commandRingExecutingCommand)
   DWARF alternate signature: SramRingView getSramRingViewOfCache<14>(OutputRing * this, uint16_t
   ringLocationHead)
   DWARF alternate signature: void ConstSramRingView(ConstSramRingView * this, uint32_t vaSramRing,
   uint32_t sizeofElemLog2, uint16_t numRingElemsMinus1, uint16_t head, uint32_t count, uint32_t
   ringLocationSizeLog2)
   DWARF alternate signature: SramRingView getSramRingViewOfCache<14>(InputRing * this)
   DWARF alternate signature: uint64_t getVaSramCacheElemFromHead(InputRing * this, uint32_t
   indexFromHead)
   DWARF alternate signature: void
   IoController_BootConfiguration_getZcnVaTitaniaAndSyshubMmio(uint64_t vaSramBootConfiguration,
   uint64_t * out_zcnvaTitania, uint64_t * out_paSyshubMmioTitania)
   DWARF alternate signature: void
   IoController_BootConfiguration_Titania_getZcnVaTitaniaAndSyshubMmio(uint64_t
   vaSramBootConfiguration_Titania, uint64_t * out_zcnvaTitania, uint64_t * out_paSyshubMmioTitania)
   DWARF alternate signature: bool setCommandRingExecutingCommandCompleted(SramRingView *
   sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId)
   DWARF alternate signature: PeekCommandResult peekCommandInputRing(ControllerStaticConfiguration *
   static_config, InputRing * aInputRing, uint32_t iCommandRing, A53ControllerCommandHeader *
   out_cmdHeader)
   DWARF alternate signature: void
   setCommandRingCommandNotPreParsed(ControllerPipelineCommandRingPreParseState *
   controller_pre_parse_state, uint32_t iCommandRing)
   DWARF alternate signature: void
   setCommandRingPreParsedCommandType(ControllerPipelineCommandRingPreParseState *
   controller_pre_parse_state, uint32_t iCommandRing, A53ControllerCommandType eCommandType)
   DWARF alternate signature: bool popElements(SramRing * this, uint32_t numElems)
   DWARF alternate signature: bool pushElement(SramRing * this)
   DWARF alternate signature: bool pushElements(SramRing * this, uint32_t numElems)
   DWARF alternate signature: uint32_t writeElement<unsigned_short>(SramRingView * this, uint32_t
   ringLocation, unsigned short * elem)
   DWARF alternate signature: uint32_t writeElementsWrapped<unsigned_int>(SramRingView * this,
   uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, uint * aElem)
   DWARF alternate signature: void ioControllerHaltAndError(IoController * this,
   IoControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError)
   DWARF alternate signature: bool canPushInterrupt(IoController * this)
   DWARF alternate signature: bool getZcnCommandSource(IoController * this, ZcnQueue eZcnQueue,
   uint32_t iZcnCmd, DeviceOpSource * out_deviceOpSource)
   DWARF alternate signature: bool clearZcnCommandSource(IoController * this, ZcnQueue eZcnQueue,
   uint32_t iZcnCmdStart, uint32_t numZcnCmds)
   DWARF alternate signature: bool peekElement<unsigned_int>(InputRing * this, uint * elem, uint32_t
   indexFromHead)
   DWARF alternate signature: uint16_t getRingLocationTail(ConstSramRingView * this)
   DWARF alternate signature: void advanceHead(SramRing * this, uint32_t numElems)
   DWARF alternate signature: bool pushInterruptCommandError(IoController * this,
   IoControllerCommandRing eRing, uint16_t ringLocationError, uint16_t ibCommandIdError, uint32_t
   pid, uint32_t opCode, ErrorCodeType eErrorCodeType, uint8_t eErrorCode, uint64_t addressError,
   uint16_t pasidError)
   DWARF alternate signature: uint32_t zcnDriverAddCommandsCopyBuffer(ZcnDriver * zcnDriver,
   uint64_t vaSramCacheBase, ZcnCommandInfo deviceOpSource_notify, uint64_t mp4paSrc, uint64_t
   mp4paDst, uint16_t pasidSrcDst, uint64_t cycleSrcBufferAvailable, IoTraceCommandSource
   io_trace_source)
   DWARF alternate signature: uint16_t
   getPipelineCommandDataHeader_commandRingExecutingCommandId(ConstSramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId)
   DWARF alternate signature: bool isCommandRingAllocationToPipelineAllowed(IoController * this,
   IoControllerCommandRing eRing)
   DWARF alternate signature: bool pushElements(OutputRing * this, uint32_t numElements)
   DWARF alternate signature: SubmitDvmGcrResult submitDvmGcrSync(IoController * this,
   DeviceOpSource deviceOpSource)
   DWARF alternate signature: void advanceIoDeviceOpDataOpConsumeReadNvmBufferHead(IoController *
   this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader)
   DWARF alternate signature: void advanceIoDeviceOpDataOpConsumeIssueZcnHead(IoController * this,
   IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader)
   DWARF alternate signature: void advanceIoDeviceOpDataOpConsumeWaitForPtOdmaHead(IoController *
   this, IoDramPipeline eIoDramPipeline, IoDeviceOpHeader * ioDeviceOpHeader)
   DWARF alternate signature: void advanceTail(OutputRing * this, uint32_t numElements)
   DWARF alternate signature: ConstSramRingView
   getConstSramRingView_PipelineCommandData_DramPipeline_OpIssue(IoController * this, IoDramPipeline
   eIoDramPipeline)
   DWARF alternate signature: void io_trace_write_event_CommandExecuteBegin(IoController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, IoControllerCommandRing eSource, uint16_t
   commandId, uint16_t commandRingExecutingCommandId, IoControllerExecutionPipeline ePipeline,
   uint32_t pid, A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData)
   DWARF alternate signature: ConstSramRingView getSramRingViewOfCache<14>(OutputRing * this,
   uint16_t ringLocationHead)
   DWARF alternate signature: ConstSramRingView getSramRingViewOfCache<14>(InputRing * this)
   DWARF alternate signature: bool isCreated(NvmSubmissionQueue * this)
   DWARF alternate signature: void io_trace_write_event_ZcnCommandsSubmitted(IoController * this,
   ZcnQueue eZcnQueue, uint32_t offsetCmdStart, uint32_t numCmds)
   DWARF alternate signature: uint64_t getVaSramElementWrapped(ConstSramRingView * this, uint16_t
   ringLocationStart, uint32_t elemOffset)
   DWARF alternate signature: bool canWriteElementsWrapped(SramRingView * this, uint32_t
   ringLocationStart, uint32_t numElems)
   DWARF alternate signature: PeekCommandResult peekCommand(ControllerRings * rings, uint32_t
   iCommandRing, A53ControllerCommandHeader * out_cmdHeader)
   DWARF alternate signature: void popCommand(ControllerRings * rings, uint32_t iCommandRing,
   uint32_t numCmdElems)
   DWARF alternate signature: PeekCommandResult peekCommandInputRing(ControllerRings * rings,
   uint32_t iCommandRing, A53ControllerCommandHeader * out_cmdHeader)
   DWARF alternate signature: void popCommandInputRingWithIndirectBuffer(ControllerRings * rings,
   uint32_t iCommandRing, uint32_t numCmdElems)
   DWARF alternate signature: void popCommandInputRing(ControllerRings * rings, uint32_t
   iCommandRing, uint32_t numCmdElems)
   DWARF alternate signature: void
   popCommandInputRingWithIndirectBuffer(ControllerStaticConfiguration * static_config,
   InputIndirectBuffer * aInputIndirectBuffer, A53Controller_InputRingWithIndirectBufferHead *
   aInputRingHeadIb, ControllerRingsState * rings_state, uint32_t iCommandRing, uint32_t
   numCmdElems)
   DWARF alternate signature: bool canReadElementsWrapped(ConstSramRingView * this, uint32_t
   ringLocationStart, uint32_t numElems)
   DWARF alternate signature: bool peekElement<unsigned_int>(InputIndirectBuffer * this, uint *
   elem, uint32_t indexFromHead)
   DWARF alternate signature: uint32_t getNumRingElemsAvailableToPut(OutputRing * this)
   DWARF alternate signature: bool popElements(InputRing * this, uint32_t numElements)
   DWARF alternate signature: uint32_t
   pushElement<A53Controller_InterruptContextRingEntry>(OutputRing * this,
   A53Controller_InterruptContextRingEntry * elem)
   DWARF alternate signature: void storeElement<A53Controller_InterruptContextRingEntry>(OutputRing
   * this, uint32_t iCacheElem, A53Controller_InterruptContextRingEntry * elem) */

uint32_t __thiscall
A53::ConstSramRingView::readElement<unsigned_int>
          (ConstSramRingView *this,uint32_t ringLocation,uint *elem)

{
  ulong uVar1;
  int iVar2;
  undefined *puVar3;
  uint64_t *log;
  undefined8 *extraout_x18;
  undefined8 *extraout_x18_00;
  uint64_t uVar4;
  
  uVar1 = mpidr_el1;
  if ((uVar1 & 0xff) == 0) {
    uVar4 = 0x1800;
    log = &DAT_00001900;
    DAT_00001800 = &DAT_00001900;
    puVar3 = &__el3_stack_sram_core0_end;
    DAT_00001900 = 0x101;
  }
  else {
    uVar4 = 0x1c00;
    log = &DAT_00001d00;
    DAT_00001c00 = &DAT_00001d00;
    puVar3 = &__el3_stack_sram_core1_end;
    DAT_00001d00 = 0x101;
  }
  *(uint64_t *)(uVar4 + 0x80) = uVar4;
  *(undefined8 *)(uVar4 + 0x88) = 0x10d;
  tpidrro_el0 = uVar4;
  *log = 0x102;
  log[1] = 0;
  log[4] = uVar4;
  vbar_el3 = 0x1000;
  *log = 0x103;
  cptr_el3 = 0;
  *log = 0x104;
  scr_el3 = 0xc0f;
  *log = 0x105;
  uVar1 = UnkSytemRegRead(3,1,0xb,0,2);
  UnkSytemRegWrite(3,1,0xb,0,2,uVar1 | 0x400000);
  UnkSytemRegWrite(3,1,0xf,2,0,0x80ca000);
  uVar1 = UnkSytemRegRead(3,1,0xf,2,1);
  UnkSytemRegWrite(3,1,0xf,2,1,uVar1 | 0x40);
  uVar1 = daif;
  daif = uVar1 & 0xfffffffffffffe3f;
  *log = 0x106;
  *log = 0x107;
  iVar2 = el3_sram_boot(log);
  *extraout_x18 = 0x300;
  TLBI_ALLE3();
  IC_IALLU();
  invalidate_dcaches(iVar2);
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  ttbr0_el3 = 0x88000000;
  mair_el3 = 0xbbff440c0400;
  tcr_el3 = 0x2351f;
  InstructionSynchronizationBarrier();
  sctlr_el3 = 0x100d;
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  el3_sram_boot2(*(int64_t **)(puVar3 + 8));
  *extraout_x18_00 = 0x500;
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06001ab0
 * symbol: getPipelineCommandDataHeader
 * prototype: bool getPipelineCommandDataHeader(ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader * out_pipelineCmdDataHeader)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getPipelineCommandDataHeader
               (ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
               PipelineCommandDataHeader *out_pipelineCmdDataHeader)

{
  uint32_t uVar1;
  
  uVar1 = ConstSramRingView::readElement<unsigned_int>
                    (sramRingView_PipelineCommandData,(uint)pipelineCommandId,
                     (uint *)out_pipelineCmdDataHeader);
  return uVar1 == 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06001ad0
 * symbol: getCommandRingExecutingCommand
 * prototype: bool getCommandRingExecutingCommand(ConstSramRingView * sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId, CommandRingExecutingCommand * out_commandRingExecutingCommand)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::getCommandRingExecutingCommand
               (ConstSramRingView *sramRingView_CommandRingExecutingCommand,
               uint16_t commandRingExecutingCommandId,
               CommandRingExecutingCommand *out_commandRingExecutingCommand)

{
  uint32_t uVar1;
  
  uVar1 = ConstSramRingView::readElement<unsigned_short>
                    (sramRingView_CommandRingExecutingCommand,(uint)commandRingExecutingCommandId,
                     (unsigned_short *)out_commandRingExecutingCommand);
  return uVar1 == 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060061b4
 * symbol: setCommandRingCommandNotPreParsed
 * prototype: void setCommandRingCommandNotPreParsed(ControllerPipelineCommandRingPreParseState * controller_pre_parse_state, uint32_t iCommandRing)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::setCommandRingCommandNotPreParsed
               (ControllerPipelineCommandRingPreParseState *controller_pre_parse_state,
               uint32_t iCommandRing)

{
  *(uint *)((long)&controller_pre_parse_state->field_0 + 0x10) =
       *(uint *)((long)&controller_pre_parse_state->field_0 + 0x10) &
       ((uint)(1L << ((ulong)iCommandRing & 0x3f)) ^ 0xffffffff);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060061d0
 * symbol: setCommandRingPreParsedCommandType
 * prototype: void setCommandRingPreParsedCommandType(ControllerPipelineCommandRingPreParseState * controller_pre_parse_state, uint32_t iCommandRing, A53ControllerCommandType eCommandType)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::setCommandRingPreParsedCommandType
               (ControllerPipelineCommandRingPreParseState *controller_pre_parse_state,
               uint32_t iCommandRing,A53ControllerCommandType eCommandType)

{
  int iVar1;
  uint uVar2;
  
  uVar2 = iCommandRing >> 4 & 0x3ffffff;
  iVar1 = (iCommandRing & 0xf) << 2;
  (controller_pre_parse_state->field_0).m_amaskCommandTypeByInputRing[uVar2] =
       (controller_pre_parse_state->field_0).m_amaskCommandTypeByInputRing[uVar2] &
       (0xfL << iVar1 ^ 0xffffffffffffffffU) | (ulong)eCommandType << iVar1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006410
 * symbol: setCommandRingExecutingCommandCompleted
 * prototype: bool setCommandRingExecutingCommandCompleted(SramRingView * sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setCommandRingExecutingCommandCompleted
               (SramRingView *sramRingView_CommandRingExecutingCommand,
               uint16_t commandRingExecutingCommandId)

{
  uint32_t uVar1;
  
  uVar1 = SramRingView::writeElement<unsigned_short>
                    (sramRingView_CommandRingExecutingCommand,(uint)commandRingExecutingCommandId,
                     (unsigned_short *)&kCommandRingExecutingCommandDone);
  return uVar1 == 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06042db8
 * symbol: setCommandRingExecutingCommand
 * prototype: bool setCommandRingExecutingCommand(SramRingView * sramRingView_CommandRingExecutingCommand, uint16_t commandRingExecutingCommandId, CommandRingExecutingCommand commandRingExecutingCommand)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


bool A53::setCommandRingExecutingCommand
               (SramRingView *sramRingView_CommandRingExecutingCommand,
               uint16_t commandRingExecutingCommandId,
               CommandRingExecutingCommand commandRingExecutingCommand)

{
  uint32_t uVar1;
  anon_union_2_2_653be860_for_CommandRingExecutingCommand_0 local_18 [4];
  
  local_18[0] = commandRingExecutingCommand.field_0;
  uVar1 = SramRingView::writeElement<unsigned_short>
                    (sramRingView_CommandRingExecutingCommand,(uint)commandRingExecutingCommandId,
                     &local_18[0].asU16);
  return uVar1 == 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605f318
 * symbol: setCommandRingCommandPreParsed
 * prototype: void setCommandRingCommandPreParsed(ControllerPipelineCommandRingPreParseState * controller_pre_parse_state, uint32_t iCommandRing)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::setCommandRingCommandPreParsed
               (ControllerPipelineCommandRingPreParseState *controller_pre_parse_state,
               uint32_t iCommandRing)

{
  *(uint *)((long)&controller_pre_parse_state->field_0 + 0x10) =
       (uint)(1L << ((ulong)iCommandRing & 0x3f)) |
       *(uint *)((long)&controller_pre_parse_state->field_0 + 0x10);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605f334
 * symbol: setCommandRingCommandPreParseNotWaitingForCommandFetch
 * prototype: void setCommandRingCommandPreParseNotWaitingForCommandFetch(ControllerPipelineCommandRingPreParseState * controller_pre_parse_state, uint32_t iCommandRing)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::setCommandRingCommandPreParseNotWaitingForCommandFetch
               (ControllerPipelineCommandRingPreParseState *controller_pre_parse_state,
               uint32_t iCommandRing)

{
  *(uint *)((long)&controller_pre_parse_state->field_0 + 0x14) =
       *(uint *)((long)&controller_pre_parse_state->field_0 + 0x14) &
       ((uint)(1L << ((ulong)iCommandRing & 0x3f)) ^ 0xffffffff);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605fa98
 * symbol: releasePtdmaRead
 * prototype: bool releasePtdmaRead(ControllerPipelineCommon * controller_pipeline, uint32_t len, uint32_t ptdmaReadCacheIdx)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::releasePtdmaRead
               (ControllerPipelineCommon *controller_pipeline,uint32_t len,
               uint32_t ptdmaReadCacheIdx)

{
  bool bVar1;
  
  bVar1 = releasePtdmaRead(controller_pipeline->m_pSramRing_PtdmaReadCache,
                           controller_pipeline->m_pamaskPtdmaReadCacheElemsInUse,len,
                           ptdmaReadCacheIdx);
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605fab4
 * symbol: issuePtdmaRead
 * prototype: IssuePtdmaReadResult issuePtdmaRead(ControllerRings * rings, ControllerPipelineCommon * controller_pipeline, uint32_t len, uint64_t sysvaSrc, uint16_t pasid, A53DeviceOpSource source, uint32_t * out_ptdmaReadCacheIdx)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


IssuePtdmaReadResult
A53::issuePtdmaRead(ControllerRings *rings,ControllerPipelineCommon *controller_pipeline,
                   uint32_t len,uint64_t sysvaSrc,uint16_t pasid,A53DeviceOpSource source,
                   uint32_t *out_ptdmaReadCacheIdx)

{
  IssuePtdmaReadResult IVar1;
  
  IVar1 = issuePtdmaRead((ControllerStaticConfiguration)
                         *(anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0 *)
                          &(rings->m_static_config).field_0.field_0,&rings->m_runtime_config,
                         controller_pipeline->m_paPtdmaQueue,
                         controller_pipeline->m_aVaSramPtdmaCommandSource,
                         controller_pipeline->m_pSramRing_PtdmaReadCache,
                         controller_pipeline->m_pamaskPtdmaReadCacheElemsInUse,len,sysvaSrc,pasid,
                         source,out_ptdmaReadCacheIdx);
  return IVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06060384
 * symbol: issuePtdmaWrite
 * prototype: IssuePtdmaWriteResult issuePtdmaWrite(ControllerRings * rings, ControllerPipelineCommon * controller_pipeline, uint32_t len, uint64_t vaSramSrc, uint64_t sysvaDst, uint16_t pasid, A53DeviceOpSource source)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


IssuePtdmaWriteResult
A53::issuePtdmaWrite
          (ControllerRings *rings,ControllerPipelineCommon *controller_pipeline,uint32_t len,
          uint64_t vaSramSrc,uint64_t sysvaDst,uint16_t pasid,A53DeviceOpSource source)

{
  IssuePtdmaWriteResult IVar1;
  
  IVar1 = issuePtdmaWrite((ControllerStaticConfiguration)
                          *(anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0 *)
                           &(rings->m_static_config).field_0.field_0,&rings->m_runtime_config,
                          controller_pipeline->m_paPtdmaQueue,
                          controller_pipeline->m_aVaSramPtdmaCommandSource,
                          controller_pipeline->m_pfnDmaCmdCompletedCallback,
                          controller_pipeline->m_pContextDmaCmdCompletedCallback,len,vaSramSrc,
                          sysvaDst,pasid,source);
  return IVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06060f98
 * symbol: pushInterruptSysCommandError
 * prototype: bool pushInterruptSysCommandError(ControllerRings * rings, uint32_t iCommandRing, uint32_t pid, CommandInIndirectBufferLocation * cmdLoc, uint32_t opCode, A53ControllerSysErrorCode eSysErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pushInterruptSysCommandError
               (ControllerRings *rings,uint32_t iCommandRing,uint32_t pid,
               CommandInIndirectBufferLocation *cmdLoc,uint32_t opCode,
               A53ControllerSysErrorCode eSysErrorCode,uint64_t addressError,uint16_t pasidError)

{
  undefined8 uVar1;
  ulong uVar2;
  bool bVar3;
  
  uVar1 = *(undefined8 *)&cmdLoc->field_0;
  uVar2 = *(ulong *)((long)&cmdLoc->field_0 + 8);
  bVar3 = pushInterruptCommandError
                    (rings,iCommandRing,(uint16_t)uVar1,uVar2 & 0xffffffffffff,
                     (uint)((ulong)uVar1 >> 0x28),(uint)((ulong)uVar1 >> 0x10) & 0xffffff,
                     (uint16_t)(uVar2 >> 0x30),pid,opCode,kErrorCodeTypeSys,(uint8_t)eSysErrorCode,
                     addressError,pasidError);
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06060ffc
 * symbol: pushInterruptAppCommandError
 * prototype: bool pushInterruptAppCommandError(ControllerRings * rings, uint32_t iCommandRing, uint32_t pid, CommandInIndirectBufferLocation * cmdLoc, uint32_t opCode, A53ControllerAppErrorCode eAppErrorCode, uint64_t addressError)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pushInterruptAppCommandError
               (ControllerRings *rings,uint32_t iCommandRing,uint32_t pid,
               CommandInIndirectBufferLocation *cmdLoc,uint32_t opCode,
               A53ControllerAppErrorCode eAppErrorCode,uint64_t addressError)

{
  undefined8 uVar1;
  ulong uVar2;
  bool bVar3;
  
  uVar1 = *(undefined8 *)&cmdLoc->field_0;
  uVar2 = *(ulong *)((long)&cmdLoc->field_0 + 8);
  bVar3 = pushInterruptCommandError
                    (rings,iCommandRing,(uint16_t)uVar1,uVar2 & 0xffffffffffff,
                     (uint)((ulong)uVar1 >> 0x28),(uint)((ulong)uVar1 >> 0x10) & 0xffffff,
                     (uint16_t)(uVar2 >> 0x30),pid,opCode,kErrorCodeTypeApp,(uint8_t)eAppErrorCode,
                     addressError,(rings->m_runtime_config).field_0.field_0.m_pasidIndirect);
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06061060
 * symbol: pushInterruptSysCommandError
 * prototype: bool pushInterruptSysCommandError(ControllerRings * rings, uint32_t iCommandRing, CommandInRingLocation * cmdLoc, uint32_t opCode, A53ControllerSysErrorCode eSysErrorCode, uint64_t addressError)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pushInterruptSysCommandError
               (ControllerRings *rings,uint32_t iCommandRing,CommandInRingLocation *cmdLoc,
               uint32_t opCode,A53ControllerSysErrorCode eSysErrorCode,uint64_t addressError)

{
  bool bVar1;
  
  bVar1 = pushInterruptCommandError
                    (rings,iCommandRing,(uint16_t)(cmdLoc->field_0).asU32[0],0,0,0,0,
                     (cmdLoc->field_0).field_0.m_pid,opCode,kErrorCodeTypeSys,(uint8_t)eSysErrorCode
                     ,addressError,(uint16_t)((cmdLoc->field_0).asU32[0] >> 0x10));
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060610c0
 * symbol: pushInterruptSystemCommandCompletion
 * prototype: bool pushInterruptSystemCommandCompletion(ControllerRings * rings, uint32_t iCommandRing, CommandInRingLocation * cmdLoc, uint32_t opCode, uint32_t returnValue)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::pushInterruptSystemCommandCompletion
               (ControllerRings *rings,uint32_t iCommandRing,CommandInRingLocation *cmdLoc,
               uint32_t opCode,uint32_t returnValue)

{
  bool bVar1;
  anon_struct_8_3_e1c847e3_for_anon_union_8_2_653be89a_for_CommandInRingLocation_0_0 aVar2;
  
  aVar2 = (cmdLoc->field_0).field_0;
  bVar1 = canPushInterrupt(rings);
  if (bVar1) {
    interruptContextRing_pushSystemCommandCompletion
              (rings->m_paOutputRing,iCommandRing,aVar2._0_2_,aVar2.m_pid,opCode,returnValue);
    interruptContextRingWorkWasAdded(rings);
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060618a0
 * symbol: scrubPtdmaCommandSource
 * prototype: uint32_t scrubPtdmaCommandSource(ControllerStaticConfiguration static_config, ControllerPipelineCommon * controller_pipeline, A53DeviceOpSource deviceOpSource, uint32_t maskPtdmaVq, uint32_t maskDeviceOpSource)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t A53::scrubPtdmaCommandSource
                   (ControllerStaticConfiguration static_config,
                   ControllerPipelineCommon *controller_pipeline,A53DeviceOpSource deviceOpSource,
                   uint32_t maskPtdmaVq,uint32_t maskDeviceOpSource)

{
  uint32_t uVar1;
  
  uVar1 = scrubPtdmaCommandSource
                    (static_config,controller_pipeline->m_paPtdmaQueue,
                     controller_pipeline->m_aVaSramPtdmaCommandSource,deviceOpSource,maskPtdmaVq,
                     maskDeviceOpSource);
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060619a8
 * symbol: setCommandRingExecutingCommandCompleted
 * prototype: bool setCommandRingExecutingCommandCompleted(ControllerPipelineCommon * pipeline, uint32_t iCommandRing, uint16_t commandRingExecutingCommandId)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::setCommandRingExecutingCommandCompleted
               (ControllerPipelineCommon *pipeline,uint32_t iCommandRing,
               uint16_t commandRingExecutingCommandId)

{
  bool bVar1;
  
  bVar1 = setCommandRingExecutingCommandCompleted
                    (&pipeline->m_paSramRing_CommandRingExecutingCommand[iCommandRing].
                      super_SramRingView,commandRingExecutingCommandId);
  return bVar1;
}


