/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_output_ring.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066970
 * symbol: issuePut
 * prototype: IssuePutReturn issuePut(OutputRing * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint32_t maxElemsToPut)
 * body addresses: 436
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssuePutReturn issuePut(OutputRing * this, A53_AddressTranslator *
   addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint32_t maxElemsToPut) */

IssuePutReturn __thiscall
A53::OutputRing::issuePut
          (OutputRing *this,A53_AddressTranslator *addressTranslator,
          PtdmaVqSubmitState *submit_write,uint16_t pasid,uint32_t maxElemsToPut)

{
  uint64_t paDst;
  uint uVar1;
  byte bVar2;
  uint8_t uVar3;
  uint16_t uVar4;
  int iVar5;
  uint uVar6;
  uint uVar7;
  uint32_t uVar8;
  DmaWaitOnCompletion in_w6;
  ulong uVar9;
  ulong uVar10;
  uint uVar11;
  uint64_t uVar12;
  
  uVar6 = getNumRingElemsAvailableToPut(this,kDisallowWrapInDramRing);
  if (((uVar6 == 0) || ((this->field_0).field_0.m_countPtdmaCommand == '\x03')) ||
     (uVar7 = getNumCacheElemsAvailableForPut(this,kDisallowWrapInSramCache), uVar7 == 0)) {
    uVar9 = 0;
    uVar10 = 0;
  }
  else {
    if (maxElemsToPut <= uVar6) {
      uVar6 = maxElemsToPut;
    }
    iVar5 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
    bVar2 = (this->field_0).field_0.m_sizeofElemLog2;
    uVar1 = (this->field_0).field_0.m_tail - (uint)(this->field_0).field_0.m_countDmaNotIssued &
            (1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f)) - 1U;
    if (uVar6 <= uVar7) {
      uVar7 = uVar6;
    }
    uVar11 = 0x100 >> (ulong)(bVar2 & 0x1f);
    uVar6 = 0xffffffff;
    if (uVar11 < uVar7) {
      uVar6 = -uVar11;
    }
    uVar6 = uVar6 & uVar7;
    uVar12 = (this->field_0).field_0.m_vaSramCache;
    paDst = (this->field_0).field_0.m_paRing + (ulong)(uVar1 << (ulong)(bVar2 & 0x1f));
    uVar11 = (uint)bVar2;
    uVar10 = uVar12 + ((uVar1 & iVar5 - 1U) << (ulong)(uVar11 & 0x1f));
    uVar7 = uVar6 << (ulong)(uVar11 & 0x1f);
    uVar9 = uVar10 & 0xffffffffffffffc0;
    if (uVar10 + uVar7 <= uVar9) {
      for (; uVar9 < uVar12 + (uint)(iVar5 << (ulong)(uVar11 & 0x1f)); uVar9 = uVar9 + 0x40) {
        DC_CVAC(uVar9);
      }
      uVar9 = (this->field_0).field_0.m_vaSramCache;
    }
    for (; uVar9 < uVar10 + uVar7; uVar9 = uVar9 + 0x40) {
      DC_CVAC(uVar9);
    }
    DataSynchronizationBarrier(3,3);
    uVar8 = ptdmaPutCommandCopy(submit_write,uVar7,uVar10 & 0xfffff,paDst,pasid,
                                (uint)((((uint)uVar10 | (uint)paDst) & 7) == 0 &&
                                      (uVar7 < 0x101 && (uVar7 & 7) == 0)),in_w6);
    uVar7 = (uint)(this->field_0).field_0.m_countPtdmaCommand +
            (uint)(this->field_0).field_0.m_headPtdmaCommand;
    iVar5 = 0;
    if (2 < uVar7) {
      iVar5 = 3;
    }
    uVar7 = uVar7 - iVar5;
    *(short *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x32) = (short)(uVar8 >> 5);
    uVar10 = (ulong)(uVar8 >> 5) << 0x20;
    uVar3 = (this->field_0).field_0.m_countPtdmaCommand;
    uVar4 = (this->field_0).field_0.m_countDmaNotIssued;
    *(short *)((long)&this->field_0 + (ulong)uVar7 * 4 + 0x34) = (short)uVar6;
    uVar9 = (ulong)uVar6;
    (this->field_0).field_0.m_countPtdmaCommand = uVar3 + '\x01';
    (this->field_0).field_0.m_countDmaNotIssued = uVar4 - (short)uVar6;
  }
  return (IssuePutReturn)(uVar10 | uVar9);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066b24
 * symbol: getNumRingElemsAvailableToPut
 * prototype: uint32_t getNumRingElemsAvailableToPut(OutputRing * this, DisallowWrap eDisallowWrap)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumRingElemsAvailableToPut(OutputRing * this, DisallowWrap
   eDisallowWrap) */

uint32_t __thiscall
A53::OutputRing::getNumRingElemsAvailableToPut(OutputRing *this,DisallowWrap eDisallowWrap)

{
  ushort uVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  
  uVar1 = (this->field_0).field_0.m_countDmaNotIssued;
  iVar2 = 1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f);
  uVar4 = iVar2 - 1;
  uVar5 = (this->field_0).field_0.m_count - (uint)uVar1;
  uVar6 = uVar4 - uVar5;
  if (uVar4 < uVar5 || uVar6 == 0) {
    return 0;
  }
  uVar5 = uVar6;
  if ((((eDisallowWrap & 1) != 0) && (1 < uVar6)) &&
     (iVar3 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f),
     uVar5 = iVar3 - (iVar3 - 1U & (this->field_0).field_0.m_tail - (uint)uVar1), uVar6 <= uVar5)) {
    uVar5 = uVar6;
  }
  uVar6 = uVar5;
  if ((((eDisallowWrap >> 1 & 1) != 0) && (1 < uVar5)) &&
     (uVar6 = iVar2 - ((this->field_0).field_0.m_tail - (uint)uVar1 & uVar4), uVar5 <= uVar6)) {
    uVar6 = uVar5;
  }
  return uVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066bb0
 * symbol: getNumCacheElemsAvailableForPut
 * prototype: uint32_t getNumCacheElemsAvailableForPut(OutputRing * this, DisallowWrap eDisallowWrap)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumCacheElemsAvailableForPut(OutputRing * this,
   DisallowWrap eDisallowWrap) */

uint32_t __thiscall
A53::OutputRing::getNumCacheElemsAvailableForPut(OutputRing *this,DisallowWrap eDisallowWrap)

{
  ushort uVar1;
  int iVar2;
  uint uVar3;
  
  uVar1 = (this->field_0).field_0.m_countDmaNotIssued;
  uVar3 = (uint)uVar1;
  if (((eDisallowWrap & 1) != 0) && (1 < uVar1)) {
    iVar2 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
    uVar3 = iVar2 - (iVar2 - 1U & (this->field_0).field_0.m_tail - (uint)uVar1);
    if (uVar1 <= uVar3) {
      uVar3 = (uint)uVar1;
    }
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066c70
 * symbol: updateHeadFromMailbox
 * prototype: int32_t updateHeadFromMailbox(OutputRing * this, uint32_t head)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: int32_t updateHeadFromMailbox(OutputRing * this, uint32_t head) */

int32_t __thiscall A53::OutputRing::updateHeadFromMailbox(OutputRing *this,uint32_t head)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint32_t uVar5;
  uint uVar6;
  int iVar7;
  uint uVar8;
  uint uVar9;
  
  uVar4 = (this->field_0).field_0.m_count;
  uVar5 = (this->field_0).field_0.m_tail;
  uVar8 = 1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f);
  uVar6 = uVar8 - 1;
  uVar2 = uVar5 - uVar4 & uVar6;
  if (uVar2 == head) {
    uVar8 = 0;
  }
  else {
    uVar9 = (uint)(this->field_0).field_0.m_countDmaNotComplete;
    uVar1 = uVar8 + uVar9;
    uVar3 = uVar4 + ~uVar8;
    if (uVar4 < uVar1) {
      uVar3 = uVar9;
    }
    iVar7 = uVar5 - uVar3;
    uVar2 = iVar7 - uVar2 & uVar6;
    uVar6 = iVar7 - head & uVar6;
    if (head < uVar8 && uVar6 < uVar2 || head < uVar8 && uVar6 == uVar2) {
      uVar8 = (uint)(uVar1 <= uVar4);
      (this->field_0).field_0.m_count = (uVar4 - uVar2) + uVar6;
    }
    else {
      uVar8 = 0xffffffff;
    }
  }
  return uVar8;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066cf8
 * symbol: resetTailFromMailbox
 * prototype: int32_t resetTailFromMailbox(OutputRing * this, uint32_t head)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: int32_t resetTailFromMailbox(OutputRing * this, uint32_t head) */

int32_t __thiscall A53::OutputRing::resetTailFromMailbox(OutputRing *this,uint32_t head)

{
  int32_t iVar1;
  
  if ((head < (uint)(1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f))) &&
     ((this->field_0).field_0.m_countDmaNotComplete == (this->field_0).field_0.m_countDmaNotIssued))
  {
    iVar1 = 0;
    (this->field_0).field_0.m_tail = head;
    *(undefined4 *)((long)&this->field_0 + 0x2c) = 0;
    (this->field_0).field_0.m_count = 0;
  }
  else {
    iVar1 = -1;
  }
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066d38
 * symbol: updateForPtdmaCompletion
 * prototype: uint32_t updateForPtdmaCompletion(OutputRing * this, uint32_t ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo)
 * body addresses: 220
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t updateForPtdmaCompletion(OutputRing * this, uint32_t
   ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo) */

uint32_t __thiscall
A53::OutputRing::updateForPtdmaCompletion
          (OutputRing *this,uint32_t ptdmaQueueSize,uint32_t ptdmaHead_Lo,uint32_t ptdmaTail_Lo)

{
  uint8_t uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  byte bVar5;
  byte bVar6;
  uint16_t uVar7;
  uint uVar8;
  uint32_t uVar9;
  ulong uVar10;
  int iVar11;
  
  uVar7 = (this->field_0).field_0.m_countDmaNotComplete;
  if ((this->field_0).field_0.m_countDmaNotIssued != uVar7) {
    bVar5 = (this->field_0).field_0.m_headPtdmaCommand;
    uVar10 = (ulong)bVar5;
    uVar8 = (ptdmaQueueSize >> 5) - 1;
    uVar2 = uVar8 & ptdmaHead_Lo >> 5;
    uVar3 = uVar8 & ptdmaTail_Lo >> 5;
    uVar4 = uVar3 - uVar2 & uVar8;
    if (uVar4 <= (*(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x32) - uVar2 & uVar8)) {
      uVar9 = (uint32_t)*(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x34);
      bVar6 = (this->field_0).field_0.m_countPtdmaCommand;
      for (iVar11 = 0; iVar11 + 1U < (uint)bVar6; iVar11 = iVar11 + 1) {
        uVar2 = 0;
        if ((int)uVar10 != 2) {
          uVar2 = (int)uVar10 + 1;
        }
        uVar10 = (ulong)uVar2;
        if ((uVar3 - *(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x32) & uVar8) <= uVar4) break;
        uVar9 = uVar9 + *(ushort *)((long)&this->field_0 + uVar10 * 4 + 0x34);
      }
      uVar1 = bVar5 + (char)iVar11 + 0xfe;
      if (((uint)bVar5 + iVar11 + 1 & 0xff) < 3) {
        uVar1 = (char)((uint)bVar5 + iVar11) + '\x01';
      }
      (this->field_0).field_0.m_countDmaNotComplete = uVar7 - (short)uVar9;
      (this->field_0).field_0.m_headPtdmaCommand = uVar1;
      (this->field_0).field_0.m_countPtdmaCommand = (bVar6 - 1) - (char)iVar11;
      return uVar9;
    }
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066e14
 * symbol: updateForPtdmaTailUpdateCompletion
 * prototype: bool updateForPtdmaTailUpdateCompletion(OutputRing * this, uint32_t ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool updateForPtdmaTailUpdateCompletion(OutputRing * this, uint32_t
   ptdmaQueueSize, uint32_t ptdmaHead_Lo, uint32_t ptdmaTail_Lo) */

bool __thiscall
A53::OutputRing::updateForPtdmaTailUpdateCompletion
          (OutputRing *this,uint32_t ptdmaQueueSize,uint32_t ptdmaHead_Lo,uint32_t ptdmaTail_Lo)

{
  uint uVar1;
  uint uVar2;
  bool bVar3;
  
  uVar2 = (ptdmaQueueSize >> 5) - 1;
  uVar1 = uVar2 & ptdmaHead_Lo >> 5;
  bVar3 = ((uVar2 & ptdmaTail_Lo >> 5) - uVar1 & uVar2) <=
          ((this->field_0).field_0.m_ptdmaCmdTailUpdate - uVar1 & uVar2);
  if (bVar3) {
    (this->field_0).field_0.m_ptdmaCmdTailUpdate = 0xffff;
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06066e5c
 * symbol: issueTailUpdate
 * prototype: IssueTailUpdateReturn issueTailUpdate(OutputRing * this, A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid, uint64_t errorState_b30_63)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: IssueTailUpdateReturn issueTailUpdate(OutputRing * this,
   A53_AddressTranslator * addressTranslator, PtdmaVqSubmitState * submit_write, uint16_t pasid,
   uint64_t errorState_b30_63) */

IssueTailUpdateReturn __thiscall
A53::OutputRing::issueTailUpdate
          (OutputRing *this,A53_AddressTranslator *addressTranslator,
          PtdmaVqSubmitState *submit_write,uint16_t pasid,uint64_t errorState_b30_63)

{
  uint32_t uVar1;
  DmaWaitOnCompletion in_w6;
  
  **(ulong **)((long)&this->field_0 + 0x18) =
       errorState_b30_63 & 0xffffffffc0000000 |
       (ulong)((this->field_0).field_0.m_tail - (uint)(this->field_0).field_0.m_countDmaNotIssued) &
       0x3fffffff;
  DC_CVAC((this->field_0).field_0.m_vaSramTail & 0xffffffffffffffc0);
  DataSynchronizationBarrier(3,3);
  uVar1 = ptdmaPutCommandCopy(submit_write,8,(this->field_0).field_0.m_vaSramTail & 0xfffff,
                              (this->field_0).field_0.m_paTail,pasid,kDmaFunctionEnablePrefetch,
                              in_w6);
  (this->field_0).field_0.m_ptdmaCmdTailUpdate = (uint16_t)(uVar1 >> 5);
  return (IssueTailUpdateReturn)((ulong)(uVar1 >> 5) << 0x20 | 1);
}


