/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\a53_indirect_buffer_flat_cache.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064154
 * symbol: ibFlatCacheIssueIbFetch
 * prototype: IbFlatCacheIssueDmaFetchResult ibFlatCacheIssueIbFetch(InputIndirectBuffer * inputIndirectBuffer, uint32_t indirectBufferNumElemsRemaining, PtdmaVqState * ptdmaQueueRead, uint16_t pasidIbFetch, A53_AddressTranslator * addressTranslator, A53_PtdmaCommandSourceTracker * ptdmaSourceTrackerRead, uint32_t iInputRingPtdmaSource, uint32_t * out_numElemsAdded)
 * body addresses: 240
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IbFlatCacheIssueDmaFetchResult
A53::ibFlatCacheIssueIbFetch
          (InputIndirectBuffer *inputIndirectBuffer,uint32_t indirectBufferNumElemsRemaining,
          PtdmaVqState *ptdmaQueueRead,uint16_t pasidIbFetch,
          A53_AddressTranslator *addressTranslator,
          A53_PtdmaCommandSourceTracker *ptdmaSourceTrackerRead,uint32_t iInputRingPtdmaSource,
          uint32_t *out_numElemsAdded)

{
  ulong uVar1;
  uint32_t uVar2;
  byte bVar3;
  ulong uVar4;
  IssueFetchReturn IVar5;
  uint32_t maxElemsToFetch;
  IbFlatCacheIssueDmaFetchResult IVar6;
  ulong uVar7;
  
  *out_numElemsAdded = 0;
  if ((inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1 + 1 ==
      (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued) {
    IVar6 = kIbFlatCacheIssueDmaFetchResultWaitForIbCacheSpace;
  }
  else if ((inputIndirectBuffer->field_0).field_0.m_countPtdmaCommand == 6) {
    IVar6 = kIbFlatCacheIssueDmaFetchResultWaitForIbPtdmaCommand;
  }
  else {
    uVar2 = (inputIndirectBuffer->field_0).field_0.m_head;
    if ((inputIndirectBuffer->field_0).field_0.m_numBufferElems == uVar2) {
      IVar6 = kIbFlatCacheIssueDmaFetchResultEndInInputRing;
    }
    else {
      bVar3 = (inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2;
      maxElemsToFetch = 0x40;
      if (bVar3 < 8) {
        uVar1 = (inputIndirectBuffer->field_0).field_0.m_paBuffer +
                (ulong)(uVar2 << (ulong)(bVar3 & 0x1f));
        uVar7 = uVar1 + (0x40L << ((ulong)bVar3 & 0x3f)) & 0xffffffffffffff00;
        uVar4 = uVar7 - uVar1;
        maxElemsToFetch = (uint32_t)(uVar4 >> ((ulong)bVar3 & 0x3f));
        if (uVar7 < uVar1 || uVar4 == 0) {
          maxElemsToFetch = 0x40;
        }
      }
      IVar5 = InputIndirectBuffer::issueFetch
                        (inputIndirectBuffer,addressTranslator,&ptdmaQueueRead->m_submit,
                         pasidIbFetch,maxElemsToFetch);
      if ((IVar5.m_numElemsFetched != 0) &&
         (IVar5.m_ptdmaCmdIdx < ptdmaSourceTrackerRead->m_numCommands)) {
        *(uint32_t *)
         (((ulong)IVar5 >> 0x20 & 0x3fffffff) * 4 +
         (ulong)ptdmaSourceTrackerRead->m_vaSramPtdmaCommandSourceBase) =
             iInputRingPtdmaSource & 0xff | 0xa0001600;
      }
      IVar6 = kIbFlatCacheIssueDmaFetchResultEndInIndirectBuffer;
      *out_numElemsAdded = IVar5.m_numElemsFetched;
    }
  }
  return IVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064244
 * symbol: ibFlatCacheFlattenInputRing
 * prototype: IbFlatCacheIssueDmaFetchResult ibFlatCacheFlattenInputRing(InputRing * inputRing, InputIndirectBuffer * inputIndirectBuffer, uint32_t * inout_indirectBufferNumElemsRemaining, uint32_t * inout_isIbReadAheadInIndirectBuffer, PtdmaVqState * ptdmaQueueRead, A53_AddressTranslator * addressTranslator, A53_PtdmaCommandSourceTracker * ptdmaSourceTrackerRead, uint32_t iInputRingPtdmaSource, uint32_t * out_numElemsAdded)
 * body addresses: 1436
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IbFlatCacheIssueDmaFetchResult
A53::ibFlatCacheFlattenInputRing
          (InputRing *inputRing,InputIndirectBuffer *inputIndirectBuffer,
          uint32_t *inout_indirectBufferNumElemsRemaining,
          uint32_t *inout_isIbReadAheadInIndirectBuffer,PtdmaVqState *ptdmaQueueRead,
          A53_AddressTranslator *addressTranslator,
          A53_PtdmaCommandSourceTracker *ptdmaSourceTrackerRead,uint32_t iInputRingPtdmaSource,
          uint32_t *out_numElemsAdded)

{
  uint *puVar1;
  uint uVar2;
  ushort uVar3;
  ushort uVar4;
  int iVar5;
  uint uVar6;
  bool bVar7;
  IbFlatCacheIssueDmaFetchResult IVar8;
  uint uVar9;
  uint uVar10;
  uint32_t uVar11;
  uint uVar12;
  ulong uVar13;
  uint uVar14;
  uint *puVar15;
  ulong uVar16;
  uint64_t uVar17;
  uint64_t uVar18;
  int *in_stack_00000000;
  uint32_t local_7c;
  uint local_78;
  uint local_74;
  uint local_70;
  uint local_6c;
  uint local_68 [2];
  
  *in_stack_00000000 = 0;
  if ((inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1 + 1 ==
      (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued) {
LAB_06064294:
    IVar8 = kIbFlatCacheIssueDmaFetchResultWaitForIbCacheSpace;
  }
  else {
    if ((inputIndirectBuffer->field_0).field_0.m_countPtdmaCommand != 0) {
      return kIbFlatCacheIssueDmaFetchResultWaitForIbPtdmaCommand;
    }
    if (*inout_isIbReadAheadInIndirectBuffer != 0) {
      InputIndirectBuffer::insertIntoSramCache(inputIndirectBuffer,1,&local_78);
      *in_stack_00000000 = *in_stack_00000000 + 1;
      puVar1 = (uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                       (ulong)(local_78 <<
                              (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f
                                     )));
      *puVar1 = (uint)(inputRing->field_0).field_0.m_head << 0xc | 0xe;
      DC_CVAC((ulong)puVar1 & 0xffffffffffffffc0);
      DataSynchronizationBarrier(3,3);
      *inout_isIbReadAheadInIndirectBuffer = 0;
      if ((inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1 + 1 ==
          (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued) goto LAB_06064294;
      if ((inputIndirectBuffer->field_0).field_0.m_countPtdmaCommand != 0) {
        return kIbFlatCacheIssueDmaFetchResultWaitForIbPtdmaCommand;
      }
    }
    uVar3 = (inputRing->field_0).field_0.m_countDmaComplete;
    if (uVar3 != 0) {
      bVar7 = false;
      uVar9 = 0;
      do {
        uVar11 = uVar9;
        if (uVar3 <= uVar11) goto LAB_060643a0;
        InputRing::peekElement<unsigned_int>(inputRing,local_68,uVar11);
        uVar9 = uVar11 + (local_68[0] >> 8 & 0xf) + 1;
        if (uVar3 < uVar9) goto LAB_060643a0;
        uVar12 = (local_68[0] & 0x7f) - 0xb;
        bVar7 = (bool)(bVar7 | uVar12 < 4);
      } while (3 < uVar12);
      bVar7 = true;
LAB_060643a0:
      if (uVar11 != 0) {
        if ((ptdmaQueueRead->m_submit).m_numCommandsAvailable == 0) {
          return kIbFlatCacheIssueDmaFetchResultWaitForPtdmaReadSpace;
        }
        uVar17 = (inputRing->field_0).field_0.m_vaSramCache;
        uVar9 = ((inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1 + 1) -
                (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued;
        iVar5 = 1 << (ulong)((inputRing->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
        if (uVar9 <= uVar11) {
          uVar11 = uVar9;
        }
        uVar12 = iVar5 + 0xffffU & (uint)(inputRing->field_0).field_0.m_head;
        InputIndirectBuffer::insertIntoSramCache(inputIndirectBuffer,uVar11,&local_78);
        uVar2 = local_78;
        uVar13 = (ulong)local_78;
        uVar18 = (inputIndirectBuffer->field_0).field_0.m_vaSramCache;
        uVar3 = (inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1;
        uVar16 = uVar13;
        for (uVar9 = 0; uVar9 < uVar11; uVar9 = uVar9 + 1) {
          *(undefined4 *)(uVar18 + (uint)((int)uVar16 << 2)) =
               *(undefined4 *)(uVar17 + (uVar12 << 2));
          uVar12 = uVar12 + 1 & iVar5 - 1U;
          local_78 = local_78 + 1 & (uint)uVar3;
          uVar16 = (ulong)local_78;
        }
        *in_stack_00000000 = *in_stack_00000000 + uVar11;
        InputRing::popElements(inputRing,uVar11);
        uVar16 = (uVar13 & 0xfffffff0) * 4 + uVar18;
        if (local_78 <= uVar2) {
          for (uVar13 = uVar16; uVar16 = uVar18, uVar13 <= ((ulong)uVar3 & 0xfff0) * 4 + uVar18;
              uVar13 = uVar13 + 0x40) {
            DC_CVAC(uVar13);
          }
        }
        for (; uVar16 <= ((ulong)local_78 * 4 - 4 & 0xffffffffffffffc0) + uVar18;
            uVar16 = uVar16 + 0x40) {
          DC_CVAC(uVar16);
        }
        DataSynchronizationBarrier(3,3);
      }
      if (bVar7) {
        uVar9 = (inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1 + 1;
        uVar12 = (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued;
        if (uVar9 != uVar12) {
          if ((inputIndirectBuffer->field_0).field_0.m_countPtdmaCommand != 0) {
            return kIbFlatCacheIssueDmaFetchResultWaitForIbPtdmaCommand;
          }
          uVar2 = local_68[0] & 0x7f;
          uVar10 = 2;
          if (uVar2 != 0xc) {
            uVar10 = 3;
          }
          uVar6 = local_68[0] >> 8 & 0xf;
          if (1 < uVar2 - 0xb || uVar6 != uVar10) {
            InputRing::popElements(inputRing,uVar6 + 1);
            InputIndirectBuffer::insertIntoSramCache(inputIndirectBuffer,1,&local_78);
            *in_stack_00000000 = *in_stack_00000000 + 1;
            puVar1 = (uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                             (ulong)(local_78 <<
                                    (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2
                                           & 0x1f)));
            *puVar1 = local_68[0] & 0x7f | (local_68[0] >> 8 & 0xf) << 0xc;
            DC_CVAC((ulong)puVar1 & 0xffffffffffffffc0);
            DataSynchronizationBarrier(3,3);
            return kIbFlatCacheIssueDmaFetchResultEndAtParseError;
          }
          uVar10 = uVar6 + 2;
          if (uVar10 <= uVar9 - uVar12) {
            uVar3 = (inputRing->field_0).field_0.m_head;
            local_78 = local_68[0];
            uVar9 = local_68[0] >> 8;
            InputRing::peekElements<unsigned_int>(inputRing,uVar6,(uint *)((ulong)&local_78 | 4),1);
            uVar12 = (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued;
            uVar14 = (uint)(inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1;
            uVar9 = uVar9 + (uVar12 + (inputIndirectBuffer->field_0).field_0.m_headCache & uVar14) ^
                    local_74 >> 2;
            if ((uVar9 & 1) == 0) {
              uVar10 = uVar6 + 1;
            }
            if (uVar10 < (uVar14 + 1) - uVar12) {
              InputRing::popElements(inputRing,(local_68[0] >> 8 & 0xf) + 1);
              uVar12 = local_70;
              if (uVar2 == 0xc) {
                local_70 = 0;
                local_6c = uVar12;
              }
              uVar6 = local_6c & 0xffffff;
              InputIndirectBuffer::insertIntoSramCache(inputIndirectBuffer,uVar10 + 1,&local_7c);
              uVar4 = (inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1;
              *in_stack_00000000 = *in_stack_00000000 + uVar10 + 1;
              puVar1 = (uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                               (ulong)(local_7c <<
                                      (ulong)((inputIndirectBuffer->field_0).field_0.
                                              m_sizeofElemLog2 & 0x1f)));
              *puVar1 = local_68[0] & 0xfffff0ff | uVar10 << 8;
              *(uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                       (ulong)((local_7c + 1 & (uint)uVar4) <<
                              (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f
                                     ))) = local_74;
              uVar12 = local_7c + 2;
              if (uVar2 != 0xc) {
                *(uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                         (ulong)((uVar12 & uVar4) <<
                                (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 &
                                       0x1f))) = local_70;
                uVar12 = local_7c + 3;
              }
              uVar10 = (uint)uVar4;
              *(uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                       (ulong)((uVar12 & uVar10) <<
                              (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f
                                     ))) = uVar6;
              puVar15 = (uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                                (ulong)((uVar12 + 1 & uVar10) <<
                                       (ulong)((inputIndirectBuffer->field_0).field_0.
                                               m_sizeofElemLog2 & 0x1f)));
              *puVar15 = (uint)uVar3;
              if ((uVar9 & 1) != 0) {
                puVar15 = (uint *)((inputIndirectBuffer->field_0).field_0.m_vaSramCache +
                                  (ulong)((uVar12 + 2 & uVar10) <<
                                         (ulong)((inputIndirectBuffer->field_0).field_0.
                                                 m_sizeofElemLog2 & 0x1f)));
                *puVar15 = 0;
              }
              DC_CVAC(puVar1);
              DC_CVAC((ulong)puVar15 & 0xffffffffffffffc0);
              DataSynchronizationBarrier(3,3);
              if (((local_74 & 3) == 0) || (uVar2 != 0xc)) {
                uVar11 = uVar6 + 1;
                uVar16 = (ulong)local_74 & 0xfffffffc | (ulong)(local_78 >> 0x10) << 0x20 |
                         0x1000000000000;
                if (uVar16 + uVar11 * 4 < 0x1f00000000001) {
                  if (uVar2 == 0xc) {
                    (inputIndirectBuffer->field_0).field_0.m_paBuffer = uVar16;
                    (inputIndirectBuffer->field_0).field_0.m_numBufferElems = uVar11;
                    (inputIndirectBuffer->field_0).field_0.m_head = 0;
                  }
                  else {
                    if ((inputIndirectBuffer->field_0).field_0.m_countPtdmaCommand == 0) {
                      (inputIndirectBuffer->field_0).field_0.m_paBuffer = uVar16;
                      (inputIndirectBuffer->field_0).field_0.m_numBufferElems =
                           (local_6c & 0xffffff) + 1;
                      (inputIndirectBuffer->field_0).field_0.m_head = local_70 & 0xffffff;
                      (inputIndirectBuffer->field_0).field_0.m_ibCommandId =
                           (ushort)((local_74 & 3) << 4) | (ushort)(local_78 >> 0xc) & 0xf |
                           (ushort)(local_70 >> 0x12) & 0x1fc0;
                    }
                    uVar11 = uVar11 - (local_70 & 0xffffff);
                  }
                  *inout_indirectBufferNumElemsRemaining = uVar11;
                  *inout_isIbReadAheadInIndirectBuffer = 1;
                  return kIbFlatCacheIssueDmaFetchResultEndInIndirectBuffer;
                }
              }
              return kIbFlatCacheIssueDmaFetchResultEndAtParseError;
            }
          }
        }
        goto LAB_06064294;
      }
    }
    IVar8 = kIbFlatCacheIssueDmaFetchResultEndInInputRing;
  }
  return IVar8;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060647e0
 * symbol: ibFlatCacheHandlePtdmaFetchCompletion
 * prototype: IbFlatCacheHandlePtdmaFetchCompletionResult ibFlatCacheHandlePtdmaFetchCompletion(uint32_t numElemsCompleted, InputIndirectBuffer * inputIndirectBuffer, uint32_t * inout_indirectBufferNumElemsRemaining)
 * body addresses: 376
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IbFlatCacheHandlePtdmaFetchCompletionResult
A53::ibFlatCacheHandlePtdmaFetchCompletion
          (uint32_t numElemsCompleted,InputIndirectBuffer *inputIndirectBuffer,
          uint32_t *inout_indirectBufferNumElemsRemaining)

{
  uint uVar1;
  ushort uVar2;
  ushort uVar3;
  uint32_t uVar4;
  uint uVar5;
  IbFlatCacheHandlePtdmaFetchCompletionResult IVar6;
  ulong uVar7;
  uint indexFromHead;
  uint local_48;
  uint local_44;
  undefined4 local_38;
  
  uVar4 = *inout_indirectBufferNumElemsRemaining - numElemsCompleted;
  if (*inout_indirectBufferNumElemsRemaining < numElemsCompleted || uVar4 == 0) {
    uVar1 = (inputIndirectBuffer->field_0).field_0.m_head;
    uVar2 = (inputIndirectBuffer->field_0).field_0.m_countDmaIssued;
    uVar3 = (inputIndirectBuffer->field_0).field_0.m_countDmaComplete;
    *inout_indirectBufferNumElemsRemaining = 0;
    uVar5 = (uint)uVar2;
    indexFromHead = uVar5 - uVar1;
    if (uVar5 <= uVar1) {
      indexFromHead = 0;
    }
    do {
      InputIndirectBuffer::peekElement<unsigned_int>(inputIndirectBuffer,&local_38,indexFromHead);
      uVar4 = indexFromHead + 1;
      uVar1 = local_38 >> 8 & 0xf;
      indexFromHead = uVar1 + uVar4;
      if (uVar3 < indexFromHead) {
        return kIbFlatCacheHandlePtdmaFetchCompletionResultErrorParsingCommandData;
      }
      uVar5 = local_38 & 0x7f;
      if (uVar5 - 0xb < 2 || uVar5 == 0xe) {
        return kIbFlatCacheHandlePtdmaFetchCompletionResultErrorParsingCommandData;
      }
      if (uVar5 == 0xd) {
        if ((uVar1 == 2 && indexFromHead == uVar3) &&
           (InputIndirectBuffer::peekElements<unsigned_int>(inputIndirectBuffer,2,&local_48,uVar4),
           (local_48 & 3) == 0)) {
          uVar4 = (local_44 & 0xffffff) + 1;
          uVar7 = (ulong)CONCAT24(local_38._2_2_,local_48) | 0x1000000000000;
          if (uVar7 + uVar4 * 4 < 0x1f00000000001) {
            if (((*(int *)((long)&inputIndirectBuffer->field_0 + 8) +
                  (((uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued +
                    (uint)(inputIndirectBuffer->field_0).field_0.m_headCache &
                   (uint)(inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1) <<
                  (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f)) ^
                 local_48) >> 2 & 1) != 0) {
              InputIndirectBuffer::advanceCacheFetchPosition(inputIndirectBuffer,1);
            }
            (inputIndirectBuffer->field_0).field_0.m_paBuffer = uVar7;
            (inputIndirectBuffer->field_0).field_0.m_numBufferElems = uVar4;
            (inputIndirectBuffer->field_0).field_0.m_head = 0;
            *inout_indirectBufferNumElemsRemaining = uVar4;
            return kIbFlatCacheHandlePtdmaFetchCompletionResultSuccessParsedChainToIndirectBuffer;
          }
        }
        return kIbFlatCacheHandlePtdmaFetchCompletionResultErrorParsingCommandData;
      }
    } while (indexFromHead != uVar3);
    IVar6 = kIbFlatCacheHandlePtdmaFetchCompletionResultSuccessParsedReturnFromIndirectBuffer;
    (inputIndirectBuffer->field_0).field_0.m_paBuffer = 0;
    *(undefined8 *)((long)&inputIndirectBuffer->field_0 + 0x14) = 0;
  }
  else {
    IVar6 = kIbFlatCacheHandlePtdmaFetchCompletionResultSuccess;
    *inout_indirectBufferNumElemsRemaining = uVar4;
  }
  return IVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064958
 * symbol: advanceCacheFetchPosition
 * prototype: bool advanceCacheFetchPosition(InputIndirectBuffer * this, uint32_t numElems)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool advanceCacheFetchPosition(InputIndirectBuffer * this, uint32_t
   numElems) */

bool __thiscall
A53::InputIndirectBuffer::advanceCacheFetchPosition(InputIndirectBuffer *this,uint32_t numElems)

{
  bool bVar1;
  uint uVar2;
  
  uVar2 = (this->field_0).field_0.m_countDmaIssued + numElems;
  bVar1 = uVar2 <= (this->field_0).field_0.m_numCacheElemsMinus1 + 1;
  if (bVar1) {
    (this->field_0).field_0.m_countDmaIssued = (uint16_t)uVar2;
    (this->field_0).field_0.m_countDmaComplete =
         (this->field_0).field_0.m_countDmaComplete + (short)numElems;
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064994
 * symbol: ibFlatCachePeekCommand
 * prototype: IbFlatCachePeekCommandResult ibFlatCachePeekCommand(InputIndirectBuffer * inputIndirectBuffer, A53ControllerCommandHeader * out_cmdHeader)
 * body addresses: 160
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IbFlatCachePeekCommandResult
A53::ibFlatCachePeekCommand
          (InputIndirectBuffer *inputIndirectBuffer,A53ControllerCommandHeader *out_cmdHeader)

{
  uint uVar1;
  bool bVar2;
  IbFlatCachePeekCommandResult IVar3;
  uint uVar4;
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_28 [2];
  
  uVar4 = (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaComplete;
  if (uVar4 == 0) {
    (out_cmdHeader->field_0).asU32 = 0;
    IVar3 = kIbFlatCachePeekCommandResultNoCommand;
  }
  else {
    bVar2 = InputIndirectBuffer::peekElement<unsigned_int>(inputIndirectBuffer,&local_28[0].asU32,0)
    ;
    IVar3 = kIbFlatCachePeekCommandResultNoCommand;
    if (bVar2) {
      uVar1 = local_28[0].asU32 >> 8 & 0xf;
      (out_cmdHeader->field_0).asU32 = (uint32_t)local_28[0];
      if (uVar1 < uVar4) {
        IVar3 = kIbFlatCachePeekCommandResultCommand;
        if ((local_28[0].asU32 & 0x7f) - 0xb < 4) {
          IVar3 = kIbFlatCachePeekCommandResultIbToken;
        }
      }
      else {
        IVar3 = kIbFlatCachePeekCommandResultNoCommand;
        if (((inputIndirectBuffer->field_0).field_0.m_numBufferElems -
            (inputIndirectBuffer->field_0).field_0.m_head) +
            (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaIssued <= uVar1) {
          IVar3 = kIbFlatCachePeekCommandResultAppErrorIndirectBufferOverrun;
        }
      }
    }
  }
  return IVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064a34
 * symbol: ibFlatCachePopIbToken
 * prototype: IbFlatCachePopIbTokenResult ibFlatCachePopIbToken(InputIndirectBuffer * inputIndirectBuffer, A53Controller_InputRingWithIndirectBufferHead * inputRingHeadIb, uint8_t * inout_pNumElemsIbFlatCacheReadAhead, PfnIbFlatCachePeekCommandTraceEvent pfnTraceEvent, void * pContext)
 * body addresses: 892
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Type propagation algorithm not settling */
/* WARNING: Unknown calling convention */

IbFlatCachePopIbTokenResult
A53::ibFlatCachePopIbToken
          (InputIndirectBuffer *inputIndirectBuffer,
          A53Controller_InputRingWithIndirectBufferHead *inputRingHeadIb,
          uint8_t *inout_pNumElemsIbFlatCacheReadAhead,
          PfnIbFlatCachePeekCommandTraceEvent pfnTraceEvent,void *pContext)

{
  ulong uVar1;
  uint32_t numElems;
  long lVar2;
  ushort uVar3;
  uint uVar4;
  bool bVar5;
  uint uVar6;
  uint uVar7;
  ulong uVar8;
  uint32_t uVar9;
  ulong uVar10;
  uint numElements;
  uint uVar11;
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_80;
  uint uStack_7c;
  uint local_78;
  uint local_74;
  uint local_70;
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_68 [2];
  
  uVar3 = (inputIndirectBuffer->field_0).field_0.m_countDmaComplete;
  bVar5 = InputIndirectBuffer::peekElement<unsigned_int>(inputIndirectBuffer,&local_68[0].asU32,0);
  if (!bVar5) {
    return kIbFlatCachePopIbTokenResultInternalError;
  }
  uVar7 = local_68[0].asU32 >> 8 & 0xf;
  if (uVar3 <= uVar7) {
    return kIbFlatCachePopIbTokenResultInternalError;
  }
  uVar11 = local_68[0].asU32 & 0x7f;
  uVar4 = uVar11 - 0xb;
  if (3 < uVar4) {
    return kIbFlatCachePopIbTokenResultInternalError;
  }
  uVar8 = (inputRingHeadIb->field_0).asU64[0];
  numElements = uVar7 + 1;
  uVar6 = (uint)uVar8;
  if (2 < uVar4) {
    if (uVar11 == 0xe) {
      if ((uVar6 >> 0x1d & 1) == 0) {
        return kIbFlatCachePopIbTokenResultAppErrorInvalidOpCode;
      }
      if (((((uint)(byte)(uVar8 >> 0x38) | (int)(inputRingHeadIb->field_0).asU64[1] << 8) + 1 ^
           (uint)(uVar8 >> 0x20)) & 0xffffff) != 0) {
        return kIbFlatCachePopIbTokenResultAppErrorInvalidOpCode;
      }
      if (local_68[0].asU32 >> 0x1c != 0) {
        return kIbFlatCachePopIbTokenResultInternalError;
      }
      if (uVar7 != 0) {
        return kIbFlatCachePopIbTokenResultInternalError;
      }
      (inputRingHeadIb->field_0).asU64[0] =
           uVar8 & 0xdfff0000 | (ulong)(local_68[0].asU32 >> 0xc & 0xffff);
      (inputRingHeadIb->field_0).asU64[1] = 0;
      uVar11 = (uint)(inputIndirectBuffer->field_0).field_0.m_ibCommandId;
      if (pfnTraceEvent != readElement<unsigned_int>) {
        (*pfnTraceEvent)((A53ControllerCommandHeader)local_68[0].field_0,inputRingHeadIb,pContext);
      }
      numElements = 1;
    }
    else {
      uVar11 = 0xffffffff;
    }
    goto joined_r0x06064b78;
  }
  uVar9 = 4;
  if (uVar11 != 0xb) {
    uVar9 = 2;
  }
  numElems = 3;
  if (uVar11 != 0xc) {
    numElems = uVar9;
  }
  if (uVar4 < 2) {
    if ((uVar6 >> 0x1d & 1) != 0) {
      return kIbFlatCachePopIbTokenResultAppErrorInvalidOpCode;
    }
    if (uVar7 != numElems && uVar7 != numElems + 1) {
      if (local_68[0].asU32 >> 0x10 != 0) {
        return kIbFlatCachePopIbTokenResultInternalError;
      }
      if (uVar7 != 0) {
        return kIbFlatCachePopIbTokenResultInternalError;
      }
      uVar7 = local_68[0].asU32 >> 4 & 0xfffff00;
LAB_06064c38:
      return uVar7 | 0x80000003;
    }
  }
  else {
    if ((uVar6 >> 0x1d & 1) == 0) {
      return kIbFlatCachePopIbTokenResultAppErrorInvalidOpCode;
    }
    if (uVar7 != numElems) {
      uVar7 = uVar7 << 8;
      goto LAB_06064c38;
    }
  }
  local_80.field_0 = local_68[0].field_0;
  InputIndirectBuffer::peekElements<unsigned_int>
            (inputIndirectBuffer,numElems,(uint *)((ulong)&local_80 | 4),1);
  uVar6 = local_78;
  if (uVar11 == 0xb) {
LAB_06064bc4:
    if ((local_74 != 0xffffffff) && (local_74 >> 0x18 != 0)) {
      return kIbFlatCachePopIbTokenResultInternalError;
    }
    if (local_70 >> 0x10 != 0) {
      return kIbFlatCachePopIbTokenResultInternalError;
    }
    (inputRingHeadIb->field_0).asU64[0] =
         (inputRingHeadIb->field_0).asU64[0] & 0xffffffffffff0000 | (ulong)(local_70 & 0xffff);
    uVar6 = local_74;
  }
  else {
    local_70 = local_74;
    local_78 = 0;
    local_74 = uVar6;
    if (uVar4 < 2) goto LAB_06064bc4;
    uVar6 = uVar6 & 0xffffff;
  }
  if ((uVar11 != 0xb) && ((uStack_7c & 3) != 0)) {
    return kIbFlatCachePopIbTokenResultAppErrorInvalidIndirectBufferAddress;
  }
  lVar2 = 4;
  if (uVar6 != 0xffffffff) {
    lVar2 = (ulong)(uVar6 + 1) << 2;
  }
  uVar8 = (ulong)uStack_7c & 0xfffffffc | (ulong)(local_80.asU32 >> 0x10) << 0x20;
  if (0x1f00000000000 < (uVar8 | 0x1000000000000) + lVar2) {
    return kIbFlatCachePopIbTokenResultAppErrorInvalidIndirectBufferAddress;
  }
  uVar10 = (inputRingHeadIb->field_0).asU64[0];
  uVar1 = (ulong)(uVar6 >> 8 & 0xffff) | uVar8 << 0x10;
  uVar8 = (ulong)uVar6 << 0x38;
  (inputRingHeadIb->field_0).asU64[0] = uVar10 & 0xffffffffffffff | uVar8 | 0x20000000;
  (inputRingHeadIb->field_0).asU64[1] = uVar1;
  if (uVar11 == 0xb) {
    uVar11 = (uStack_7c & 3) << 4 | local_80.asU32 >> 0xc & 0xf | local_78 >> 0x12 & 0x1fc0;
    (inputRingHeadIb->field_0).asU64[0] =
         uVar8 | uVar10 & 0xe000ffff | 0x20000000 | (ulong)(local_78 & 0xffffff) << 0x20 |
         (ulong)(uVar11 << 0x10);
    (inputRingHeadIb->field_0).asU64[1] = uVar1;
  }
  else {
    uVar6 = 3;
    if (uVar11 != 0xc) {
      uVar6 = numElements;
    }
    (inputRingHeadIb->field_0).asU64[0] =
         uVar10 & 0xe000ffff | uVar8 | 0x20000000 |
         (ulong)((uVar6 + ((uint)uVar10 >> 0x10) & 0x1fff) << 0x10);
    (inputRingHeadIb->field_0).asU64[1] = uVar1;
    uVar11 = uVar6 + (inputIndirectBuffer->field_0).field_0.m_ibCommandId & 0xffff;
  }
  if (((*(int *)((long)&inputIndirectBuffer->field_0 + 8) +
        ((numElements + (inputIndirectBuffer->field_0).field_0.m_headCache &
         (uint)(inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1) <<
        (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f)) ^
       (uint)((ulong)uStack_7c & 0xfffffffc)) >> 2 & 1) != 0) {
    if (uVar4 < 2) {
      return kIbFlatCachePopIbTokenResultInternalError;
    }
    numElements = uVar7 + 2;
  }
  if (pfnTraceEvent != readElement<unsigned_int>) {
    (*pfnTraceEvent)((A53ControllerCommandHeader)local_68[0].field_0,inputRingHeadIb,pContext);
  }
joined_r0x06064b78:
  if (inout_pNumElemsIbFlatCacheReadAhead != (uint8_t *)0x0) {
    if (*inout_pNumElemsIbFlatCacheReadAhead < numElements) {
      return kIbFlatCachePopIbTokenResultInternalError;
    }
    *inout_pNumElemsIbFlatCacheReadAhead = *inout_pNumElemsIbFlatCacheReadAhead - (char)numElements;
  }
  InputIndirectBuffer::popElements(inputIndirectBuffer,numElements);
  if (uVar11 == 0xffffffff) {
    return kIbFlatCachePopIbTokenResultSuccess;
  }
  (inputIndirectBuffer->field_0).field_0.m_ibCommandId = (uint16_t)uVar11;
  return kIbFlatCachePopIbTokenResultSuccess;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064db0
 * symbol: popElements
 * prototype: bool popElements(InputIndirectBuffer * this, uint32_t numElements)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool popElements(InputIndirectBuffer * this, uint32_t numElements) */

bool __thiscall
A53::InputIndirectBuffer::popElements(InputIndirectBuffer *this,uint32_t numElements)

{
  ushort uVar1;
  short sVar2;
  bool bVar3;
  
  uVar1 = (this->field_0).field_0.m_countDmaComplete;
  bVar3 = numElements <= uVar1;
  sVar2 = (short)numElements;
  if (bVar3) {
    (this->field_0).field_0.m_countDmaComplete = uVar1 - sVar2;
    (this->field_0).field_0.m_countDmaIssued = (this->field_0).field_0.m_countDmaIssued - sVar2;
    (this->field_0).field_0.m_headCache =
         (this->field_0).field_0.m_headCache + sVar2 & (this->field_0).field_0.m_numCacheElemsMinus1
    ;
    (this->field_0).field_0.m_ibCommandId = (this->field_0).field_0.m_ibCommandId + sVar2;
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064e00
 * symbol: ibFlatCachePopCommand
 * prototype: bool ibFlatCachePopCommand(InputIndirectBuffer * inputIndirectBuffer, A53Controller_InputRingWithIndirectBufferHead * inputRingHeadIb, uint32_t numCmdElems, uint8_t * inout_pNumElemsIbFlatCacheReadAhead)
 * body addresses: 176
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::ibFlatCachePopCommand
               (InputIndirectBuffer *inputIndirectBuffer,
               A53Controller_InputRingWithIndirectBufferHead *inputRingHeadIb,uint32_t numCmdElems,
               uint8_t *inout_pNumElemsIbFlatCacheReadAhead)

{
  ulong uVar1;
  ulong uVar2;
  uint64_t uVar3;
  ulong uVar4;
  bool bVar5;
  ulong uVar6;
  
  if (inout_pNumElemsIbFlatCacheReadAhead != (uint8_t *)0x0) {
    if (*inout_pNumElemsIbFlatCacheReadAhead < numCmdElems) {
      return false;
    }
    *inout_pNumElemsIbFlatCacheReadAhead = *inout_pNumElemsIbFlatCacheReadAhead - (char)numCmdElems;
  }
  InputIndirectBuffer::popElements(inputIndirectBuffer,numCmdElems);
  uVar2 = (inputRingHeadIb->field_0).asU64[0];
  uVar3 = (inputRingHeadIb->field_0).asU64[1];
  uVar6 = uVar2 & 0xffffffffe000ffff |
          (ulong)((numCmdElems + ((uint)uVar2 >> 0x10) & 0x1fff) << 0x10);
  bVar5 = (uVar2 & 0x20000000) != 0;
  uVar1 = 0xffffffffffff0000;
  if (bVar5) {
    uVar1 = 0xff000000ffffffff;
  }
  uVar4 = (ulong)((uint)uVar2 + numCmdElems & 0xffff);
  if (bVar5) {
    uVar4 = (ulong)((int)(uVar2 >> 0x20) + numCmdElems & 0xffffff) << 0x20;
  }
  (inputRingHeadIb->field_0).asU64[0] = uVar6;
  (inputRingHeadIb->field_0).asU64[1] = uVar3;
  (inputRingHeadIb->field_0).asU64[0] = uVar1 & uVar6 | uVar4;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064eb0
 * symbol: ibFlatCacheReadAheadPeekCommand
 * prototype: IbFlatCachePeekCommandResult ibFlatCacheReadAheadPeekCommand(InputIndirectBuffer * inputIndirectBuffer, uint8_t numElemsIbFlatCacheReadAhead, A53ControllerCommandHeader * out_cmdHeader)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IbFlatCachePeekCommandResult
A53::ibFlatCacheReadAheadPeekCommand
          (InputIndirectBuffer *inputIndirectBuffer,uint8_t numElemsIbFlatCacheReadAhead,
          A53ControllerCommandHeader *out_cmdHeader)

{
  bool bVar1;
  IbFlatCachePeekCommandResult IVar2;
  uint uVar3;
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_28 [2];
  
  uVar3 = (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaComplete;
  if (0xfe < uVar3) {
    uVar3 = 0xff;
  }
  if ((numElemsIbFlatCacheReadAhead < uVar3) &&
     (bVar1 = InputIndirectBuffer::peekElement<unsigned_int>
                        (inputIndirectBuffer,&local_28[0].asU32,(uint)numElemsIbFlatCacheReadAhead),
     bVar1)) {
    (out_cmdHeader->field_0).asU32 = (uint32_t)local_28[0];
    if (uVar3 < (uint)numElemsIbFlatCacheReadAhead + (local_28[0].asU32 >> 8 & 0xf) + 1) {
      IVar2 = kIbFlatCachePeekCommandResultNoCommand;
    }
    else {
      IVar2 = kIbFlatCachePeekCommandResultCommand;
      if ((local_28[0].asU32 & 0x7f) - 0xb < 4) {
        IVar2 = kIbFlatCachePeekCommandResultIbToken;
      }
    }
  }
  else {
    IVar2 = kIbFlatCachePeekCommandResultNoCommand;
    (out_cmdHeader->field_0).asU32 = 0;
  }
  return IVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06064f44
 * symbol: ibFlatCacheReadAheadPopIbToken
 * prototype: bool ibFlatCacheReadAheadPopIbToken(InputIndirectBuffer * inputIndirectBuffer, uint8_t * inout_numElemsIbFlatCacheReadAhead, A53Controller_InputRingWithIndirectBufferHead * inputRingHeadIb_readAhead)
 * body addresses: 728
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::ibFlatCacheReadAheadPopIbToken
               (InputIndirectBuffer *inputIndirectBuffer,uint8_t *inout_numElemsIbFlatCacheReadAhead
               ,A53Controller_InputRingWithIndirectBufferHead *inputRingHeadIb_readAhead)

{
  uint32_t numElems;
  int iVar1;
  long lVar2;
  byte bVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  bool bVar7;
  uint uVar8;
  uint32_t uVar9;
  ulong uVar10;
  ulong uVar11;
  ulong uVar12;
  uint uVar13;
  uint uVar14;
  uint local_78;
  uint uStack_74;
  uint local_70;
  uint local_6c;
  uint local_68;
  uint local_58 [2];
  
  bVar3 = *inout_numElemsIbFlatCacheReadAhead;
  uVar8 = (uint)(inputIndirectBuffer->field_0).field_0.m_countDmaComplete;
  if (0xfe < uVar8) {
    uVar8 = 0xff;
  }
  if (uVar8 <= bVar3) {
    return false;
  }
  uVar13 = (uint)bVar3;
  bVar7 = InputIndirectBuffer::peekElement<unsigned_int>(inputIndirectBuffer,local_58,(uint)bVar3);
  if (!bVar7) {
    return false;
  }
  uVar5 = local_58[0] >> 8 & 0xf;
  uVar14 = uVar5 + 1 + uVar13;
  if (uVar8 < uVar14) {
    return false;
  }
  uVar10 = (inputRingHeadIb_readAhead->field_0).asU64[0];
  uVar8 = local_58[0] & 0x7f;
  uVar4 = uVar8 - 0xb;
  uVar11 = uVar10 & 0x20000000;
  if (2 < uVar4) {
    if (uVar8 != 0xe) {
      return false;
    }
    if (uVar11 == 0) {
      return false;
    }
    if (local_58[0] >> 0x1c != 0) {
      return false;
    }
    if (((((uint)(byte)(uVar10 >> 0x38) | (int)(inputRingHeadIb_readAhead->field_0).asU64[1] << 8) +
          1 ^ (uint)(uVar10 >> 0x20)) & 0xffffff | uVar5) != 0) {
      return false;
    }
    (inputRingHeadIb_readAhead->field_0).asU64[0] =
         uVar10 & 0xdfff0000 | (ulong)(local_58[0] >> 0xc & 0xffff);
    (inputRingHeadIb_readAhead->field_0).asU64[1] = 0;
    goto LAB_060650d8;
  }
  if ((uint)(uVar11 >> 0x1d) == (uint)(uVar4 < 2)) {
    return false;
  }
  uVar9 = 4;
  if (uVar8 != 0xb) {
    uVar9 = 2;
  }
  numElems = 3;
  if (uVar8 != 0xc) {
    numElems = uVar9;
  }
  if (uVar5 != numElems) {
    if (uVar5 != numElems + 1) {
      return false;
    }
    if (uVar11 != 0) {
      return false;
    }
  }
  local_78 = local_58[0];
  InputIndirectBuffer::peekElements<unsigned_int>
            (inputIndirectBuffer,numElems,(uint *)((ulong)&local_78 | 4),uVar13 + 1);
  uVar6 = local_70;
  if (uVar8 == 0xb) {
LAB_06065054:
    if ((local_6c != 0xffffffff) && (local_6c >> 0x18 != 0)) {
      return false;
    }
    if (local_68 >> 0x10 != 0) {
      return false;
    }
    (inputRingHeadIb_readAhead->field_0).asU64[0] =
         (inputRingHeadIb_readAhead->field_0).asU64[0] & 0xffffffffffff0000 |
         (ulong)(local_68 & 0xffff);
  }
  else {
    local_68 = local_6c;
    local_70 = 0;
    local_6c = uVar6;
    if (uVar4 < 2) goto LAB_06065054;
    local_6c = uVar6 & 0xffffff;
  }
  if ((uVar8 == 0xb) || ((uStack_74 & 3) == 0)) {
    lVar2 = 4;
    if (local_6c != 0xffffffff) {
      lVar2 = (ulong)(local_6c + 1) << 2;
    }
    uVar10 = (ulong)uStack_74 & 0xfffffffc | (ulong)(local_78 >> 0x10) << 0x20;
    if ((uVar10 | 0x1000000000000) + lVar2 < 0x1f00000000001) {
      uVar12 = (inputRingHeadIb_readAhead->field_0).asU64[0];
      uVar11 = (ulong)(local_6c >> 8 & 0xffff) | uVar10 << 0x10;
      uVar10 = (ulong)local_6c << 0x38;
      (inputRingHeadIb_readAhead->field_0).asU64[0] =
           uVar12 & 0xffffffffffffff | uVar10 | 0x20000000;
      (inputRingHeadIb_readAhead->field_0).asU64[1] = uVar11;
      if (uVar8 == 0xb) {
        uVar8 = (uStack_74 & 3) << 4 | local_78 >> 0xc & 0xf | local_70 >> 0x12 & 0x1fc0;
        uVar10 = uVar10 | uVar12 & 0xe000ffff | 0x20000000 | (ulong)(local_70 & 0xffffff) << 0x20;
      }
      else {
        iVar1 = 3;
        if (uVar8 != 0xc) {
          iVar1 = uVar5 + 1;
        }
        uVar10 = uVar12 & 0xe000ffff | uVar10 | 0x20000000;
        uVar8 = iVar1 + ((uint)uVar12 >> 0x10) & 0x1fff;
      }
      (inputRingHeadIb_readAhead->field_0).asU64[0] = uVar10 | uVar8 << 0x10;
      (inputRingHeadIb_readAhead->field_0).asU64[1] = uVar11;
      if (((*(int *)((long)&inputIndirectBuffer->field_0 + 8) +
            ((uVar14 + (inputIndirectBuffer->field_0).field_0.m_headCache &
             (uint)(inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1) <<
            (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f)) ^
           (uint)((ulong)uStack_74 & 0xfffffffc)) >> 2 & 1) != 0) {
        if (uVar4 < 2) {
          return false;
        }
        uVar14 = uVar5 + uVar13 + 2;
      }
LAB_060650d8:
      *inout_numElemsIbFlatCacheReadAhead = (uint8_t)uVar14;
      return true;
    }
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606521c
 * symbol: ibFlatCacheReadAheadPeekCommandData
 * prototype: bool ibFlatCacheReadAheadPeekCommandData(InputIndirectBuffer * inputIndirectBuffer, uint8_t numElemsIbFlatCacheReadAhead, uint32_t numElems, uint32_t * aElem, uint32_t indexFromHead_CmdData0_readAhead)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::ibFlatCacheReadAheadPeekCommandData
               (InputIndirectBuffer *inputIndirectBuffer,uint8_t numElemsIbFlatCacheReadAhead,
               uint32_t numElems,uint32_t *aElem,uint32_t indexFromHead_CmdData0_readAhead)

{
  bool bVar1;
  
  bVar1 = InputIndirectBuffer::peekElements<unsigned_int>
                    (inputIndirectBuffer,numElems,aElem,
                     indexFromHead_CmdData0_readAhead + numElemsIbFlatCacheReadAhead);
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06065230
 * symbol: ibFlatCacheReadAheadPopCommand
 * prototype: void ibFlatCacheReadAheadPopCommand(InputIndirectBuffer * inputIndirectBuffer, uint8_t * inout_numElemsIbFlatCacheReadAhead, A53Controller_InputRingWithIndirectBufferHead * inputRingHeadIb_readAhead, uint32_t numCmdElems)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::ibFlatCacheReadAheadPopCommand
               (InputIndirectBuffer *inputIndirectBuffer,uint8_t *inout_numElemsIbFlatCacheReadAhead
               ,A53Controller_InputRingWithIndirectBufferHead *inputRingHeadIb_readAhead,
               uint32_t numCmdElems)

{
  ulong uVar1;
  ulong uVar2;
  uint64_t uVar3;
  uint8_t uVar4;
  ulong uVar5;
  bool bVar6;
  ulong uVar7;
  
  uVar2 = (inputRingHeadIb_readAhead->field_0).asU64[0];
  uVar3 = (inputRingHeadIb_readAhead->field_0).asU64[1];
  bVar6 = (uVar2 & 0x20000000) != 0;
  uVar1 = 0xffffffffffff0000;
  if (bVar6) {
    uVar1 = 0xff000000ffffffff;
  }
  uVar4 = *inout_numElemsIbFlatCacheReadAhead;
  uVar7 = uVar2 & 0xffffffffe000ffff |
          (ulong)((numCmdElems + ((uint)uVar2 >> 0x10) & 0x1fff) << 0x10);
  uVar5 = (ulong)((uint)uVar2 + numCmdElems & 0xffff);
  if (bVar6) {
    uVar5 = (ulong)((int)(uVar2 >> 0x20) + numCmdElems & 0xffffff) << 0x20;
  }
  (inputRingHeadIb_readAhead->field_0).asU64[0] = uVar7;
  (inputRingHeadIb_readAhead->field_0).asU64[1] = uVar3;
  (inputRingHeadIb_readAhead->field_0).asU64[0] = uVar1 & uVar7 | uVar5;
  *inout_numElemsIbFlatCacheReadAhead = uVar4 + (char)numCmdElems;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060652a8
 * symbol: ibFlatCacheGetIbPositionFromHead
 * prototype: IbFlatCacheGetIbPositionFromHeadResult ibFlatCacheGetIbPositionFromHead(InputIndirectBuffer * inputIndirectBuffer, A53Controller_InputRingWithIndirectBufferHead * inputRingHeadIb, uint32_t indexFromHead_position, A53Controller_InputRingWithIndirectBufferHead * out_inputRingHeadIb_position)
 * body addresses: 852
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IbFlatCacheGetIbPositionFromHeadResult
A53::ibFlatCacheGetIbPositionFromHead
          (InputIndirectBuffer *inputIndirectBuffer,
          A53Controller_InputRingWithIndirectBufferHead *inputRingHeadIb,
          uint32_t indexFromHead_position,
          A53Controller_InputRingWithIndirectBufferHead *out_inputRingHeadIb_position)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint numElems;
  bool bVar4;
  ulong uVar5;
  uint uVar6;
  ulong uVar7;
  uint64_t uVar8;
  int iVar9;
  ulong uVar10;
  uint uVar11;
  uint uVar12;
  uint local_80;
  uint uStack_7c;
  uint local_78;
  uint local_74;
  uint local_70;
  uint local_68 [2];
  
  (out_inputRingHeadIb_position->field_0).asU64[1] = (inputRingHeadIb->field_0).asU64[1];
  (out_inputRingHeadIb_position->field_0).asU64[0] = (inputRingHeadIb->field_0).asU64[0];
  if (indexFromHead_position != 0) {
    uVar12 = 0;
    while (uVar12 < indexFromHead_position) {
      bVar4 = InputIndirectBuffer::peekElement<unsigned_int>(inputIndirectBuffer,local_68,uVar12);
      if (!bVar4) {
        return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
      }
      numElems = local_68[0] >> 8 & 0xf;
      iVar9 = numElems + 1;
      uVar11 = iVar9 + uVar12;
      if (indexFromHead_position < uVar11) {
        uVar5 = (out_inputRingHeadIb_position->field_0).asU64[0];
        uVar8 = (out_inputRingHeadIb_position->field_0).asU64[1];
        (out_inputRingHeadIb_position->field_0).asU64[0] =
             uVar5 & 0xff000000e000ffff |
             (ulong)(((indexFromHead_position - uVar12) + ((uint)uVar5 >> 0x10) & 0x1fff) << 0x10) |
             (ulong)((indexFromHead_position - uVar12) + (int)(uVar5 >> 0x20) & 0xffffff) << 0x20;
        (out_inputRingHeadIb_position->field_0).asU64[1] = uVar8;
        return kIbFlatCacheGetIbPositionFromHeadResultNotAtCommandBoundary;
      }
      uVar1 = local_68[0] & 0x7f;
      uVar3 = uVar1 - 0xb;
      if (uVar3 < 3) {
        if ((uint)(uVar3 == 2) !=
            (*(byte *)((long)&out_inputRingHeadIb_position->field_0 + 3) & 0x20) >> 5) {
          return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
        }
        uVar6 = 4;
        if (uVar1 != 0xb) {
          uVar6 = 2;
        }
        uVar2 = 3;
        if (uVar1 != 0xc) {
          uVar2 = uVar6;
        }
        if ((numElems != uVar2) && (1 < uVar3 || numElems != uVar2 + 1)) {
          return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
        }
        local_80 = local_68[0];
        InputIndirectBuffer::peekElements<unsigned_int>
                  (inputIndirectBuffer,numElems,(uint *)((ulong)&local_80 | 4),uVar12 + 1);
        uVar2 = local_74;
        uVar6 = local_78;
        if (uVar1 == 0xb) {
LAB_06065430:
          if (local_70 >> 0x10 != 0) {
            return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
          }
          uVar5 = (ulong)local_74;
          if ((local_74 != 0xffffffff) && (local_74 >> 0x18 != 0)) {
            return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
          }
          uVar10 = (out_inputRingHeadIb_position->field_0).asU64[0];
          uVar8 = (out_inputRingHeadIb_position->field_0).asU64[1];
          uVar7 = uVar10 & 0xffffffffffff0000 | (ulong)(local_70 & 0xffff);
          (out_inputRingHeadIb_position->field_0).asU64[0] = uVar7;
          if (uVar1 != 0xb) goto LAB_060654cc;
          uVar1 = local_80 >> 0xc & 0xf | (uStack_7c & 3) << 4 | local_78 >> 0x12 & 0x1fc0;
          uVar7 = uVar10 & 0xff000000e0000000 | (ulong)(local_70 & 0xffff) |
                  (ulong)(local_78 & 0xffffff) << 0x20;
        }
        else {
          uVar5 = (ulong)local_78;
          local_78 = 0;
          local_74 = uVar6;
          local_70 = uVar2;
          if (uVar3 < 2) goto LAB_06065430;
          uVar10 = (out_inputRingHeadIb_position->field_0).asU64[0];
          uVar8 = (out_inputRingHeadIb_position->field_0).asU64[1];
          uVar7 = uVar10 & 0xffffffffffff0000 | (ulong)(uVar2 & 0xffff);
          (out_inputRingHeadIb_position->field_0).asU64[0] = uVar7;
LAB_060654cc:
          (out_inputRingHeadIb_position->field_0).asU64[0] = uVar7 & 0xff000000ffffffff;
          (out_inputRingHeadIb_position->field_0).asU64[1] = uVar8;
          if (uVar1 == 0xc) {
            iVar9 = 3;
          }
          else {
            iVar9 = (local_68[0] >> 8 & 0xf) + 1;
          }
          uVar1 = iVar9 + (int)(uVar10 >> 0x10) & 0x1fff;
          uVar7 = uVar7 & 0xff000000e000ffff;
        }
        (out_inputRingHeadIb_position->field_0).asU64[0] = uVar7 | uVar1 << 0x10;
        (out_inputRingHeadIb_position->field_0).asU64[1] = uVar8;
        if (((*(int *)((long)&inputIndirectBuffer->field_0 + 8) +
              ((uVar11 + (inputIndirectBuffer->field_0).field_0.m_headCache &
               (uint)(inputIndirectBuffer->field_0).field_0.m_numCacheElemsMinus1) <<
              (ulong)((inputIndirectBuffer->field_0).field_0.m_sizeofElemLog2 & 0x1f)) ^
             uStack_7c & 0xfffffffc) >> 2 & 1) != 0) {
          if (uVar3 < 2) {
            return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
          }
          uVar11 = numElems + uVar12 + 2;
        }
        (out_inputRingHeadIb_position->field_0).asU64[0] =
             uVar7 & 0xffffffffffffff | (ulong)(uVar1 << 0x10) | uVar5 << 0x38 | 0x20000000;
        (out_inputRingHeadIb_position->field_0).asU64[1] =
             (ulong)((uint)uVar5 >> 8 & 0xffff) |
             (CONCAT44(local_80 >> 0x10,uStack_7c) & 0xfffffffffffffffc) << 0x10;
        uVar12 = uVar11;
      }
      else {
        uVar5 = (out_inputRingHeadIb_position->field_0).asU64[0];
        if (uVar1 == 0xe) {
          if (local_68[0] >> 0x1c != 0) {
            return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
          }
          if (numElems != 0) {
            return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
          }
          if (((uint)uVar5 >> 0x1d & 1) == 0) {
            return kIbFlatCacheGetIbPositionFromHeadResultErrorInvalidIbFlatCacheData;
          }
          uVar8 = 0;
          uVar10 = uVar5 & 0xdfff0000;
          uVar12 = local_68[0] >> 0xc & 0xffff;
        }
        else {
          uVar8 = (out_inputRingHeadIb_position->field_0).asU64[1];
          uVar10 = uVar5 & 0xff000000e000ffff |
                   (ulong)(iVar9 + (int)(uVar5 >> 0x20) & 0xffffff) << 0x20;
          uVar12 = (iVar9 + ((uint)uVar5 >> 0x10) & 0x1fff) << 0x10;
        }
        (out_inputRingHeadIb_position->field_0).asU64[0] = uVar10 | uVar12;
        (out_inputRingHeadIb_position->field_0).asU64[1] = uVar8;
        uVar12 = uVar11;
      }
    }
  }
  return kIbFlatCacheGetIbPositionFromHeadResultSuccess;
}


