/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\controller.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060675b4
 * symbol: controller_sram
 * prototype: int controller_sram(void)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int controller_sram(void)

{
  printf("%s()\n","controller_sram");
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060675dc
 * symbol: svc_write
 * prototype: int svc_write(void * base1, uint64_t size1, void * base2, uint64_t size2, void * base3, uint64_t size3)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int svc_write(void *base1,uint64_t size1,void *base2,uint64_t size2,void *base3,uint64_t size3)

{
  CallSupervisor(0);
  return 0;
}


