/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller\test.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060675e8
 * symbol: test_loader_el0_mm_mmu
 * prototype: int test_loader_el0_mm_mmu(void)
 * body addresses: 260
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int test_loader_el0_mm_mmu(void)

{
  int iVar1;
  
  printf("%s()\n","test_loader_el0_mm_mmu");
  printf("%s:->dev_pmu_init\n","test_loader_el0_mm_mmu");
  dev_pmu_init();
  printf("%s:->dev_pmu_setup_default\n","test_loader_el0_mm_mmu");
  dev_pmu_setup_default();
  pmcr_el0 = 7;
  printf("%s:start evaluation: %p+0x%08x\n",7,"test_loader_el0_mm_mmu_64k",&DAT_04040000,0x1000);
  for (iVar1 = 0; iVar1 != 0x10000; iVar1 = iVar1 + 0x1000) {
  }
  pmcr_el0 = 0;
  dev_pmu_report();
  pmcr_el0 = 7;
  printf("%s:start evaluation: %p+0x%08x\n",7,"test_loader_el0_mm_mmu_32m",0x10000000,0x200000);
  for (iVar1 = 0x10; iVar1 != 0; iVar1 = iVar1 + -1) {
  }
  pmcr_el0 = 0;
  dev_pmu_report();
  return 0;
}


