/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\a53.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111090
 * symbol: aarch64_DC_CVAC_range
 * prototype: void aarch64_DC_CVAC_range(void * base, uint64_t vsize)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_DC_CVAC_range(void *base,uint64_t vsize)

{
  while (vsize != 0) {
    vsize = vsize - 0x40;
    DC_CVAC(base);
    base = (void *)((long)base + 0x40);
  }
  return;
}


