/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\aarch64.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001110a8
 * symbol: aarch64_print_CurrentEL
 * prototype: void aarch64_print_CurrentEL(void)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_CurrentEL(void)

{
  uint uVar1;
  ulong uVar2;
  u_int uVar3;
  
  uVar2 = currentel;
  uVar1 = *(uint *)(&DAT_00120630 + (uVar2 >> 2 & 3 ^ 2) * 4);
  uVar3 = mp4_get_cpu();
  printf_low("%d:CurrentEl:      0x%08x: EL=%d\n",(ulong)uVar3,uVar2 & 0xffffffff,(ulong)uVar1);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001110f0
 * symbol: aarch64_print_SPSR_EL1
 * prototype: void aarch64_print_SPSR_EL1(void)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SPSR_EL1(void)

{
  uint v;
  u_int uVar1;
  
  v = aarch64_read_SPSR_EL1();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar1,"SPSR_EL1",(ulong)v);
  el3_reg_bit_name32_print(g_reg_SPSR_EL1,v);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111148
 * symbol: el3_reg_bit_name32_print
 * prototype: void el3_reg_bit_name32_print(el3_reg_bit_name32 * p, uint32_t v)
 * body addresses: 196
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void el3_reg_bit_name32_print(el3_reg_bit_name32 *p,uint32_t v)

{
  uint uVar1;
  uint uVar2;
  char *pcVar3;
  uint uVar4;
  ulong uVar5;
  char **ppcVar6;
  int iVar7;
  
  uVar5 = (ulong)v;
  ppcVar6 = &p->name;
  iVar7 = 1;
  while( true ) {
    uVar2 = ((el3_reg_bit_name32 *)(ppcVar6 + -1))->bit;
    uVar4 = (uint)uVar5;
    if ((uVar2 == 0) && (*ppcVar6 == (char *)0x0)) break;
    uVar1 = uVar2;
    if (*(uint32_t *)((long)ppcVar6 + -4) != 0) {
      uVar1 = *(uint32_t *)((long)ppcVar6 + -4);
    }
    if ((uVar1 & uVar4) == uVar2) {
      pcVar3 = *ppcVar6;
      if (pcVar3 != (char *)0x0) {
        if (iVar7 == 0) {
          printf_low(",");
          pcVar3 = *ppcVar6;
        }
        else {
          iVar7 = iVar7 + -1;
        }
        printf_low("%s",pcVar3);
      }
      uVar5 = (ulong)(uVar4 & (uVar1 ^ 0xffffffff));
    }
    ppcVar6 = ppcVar6 + 2;
  }
  if (uVar4 != 0) {
    printf_low("[0x%08x]",uVar5);
    return;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011120c
 * symbol: aarch64_print_SPSR_EL2
 * prototype: void aarch64_print_SPSR_EL2(void)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SPSR_EL2(void)

{
  uint v;
  u_int uVar1;
  
  v = aarch64_read_SPSR_EL2();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar1,"SPSR_EL2",(ulong)v);
  el3_reg_bit_name32_print(g_reg_SPSR_EL2,v);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111264
 * symbol: aarch64_print_SPSR_EL3
 * prototype: void aarch64_print_SPSR_EL3(void)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SPSR_EL3(void)

{
  ulong uVar1;
  u_int uVar2;
  
  uVar1 = spsr_el3;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar2,"SPSR_EL3",uVar1 & 0xffffffff);
  el3_reg_bit_name32_print(g_reg_SPSR_EL3,(uint32_t)uVar1);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001112b8
 * symbol: aarch64_print_ESR_EL1
 * prototype: void aarch64_print_ESR_EL1(void)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_ESR_EL1(void)

{
  uint v;
  u_int uVar1;
  
  v = aarch64_read_ESR_EL1();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar1,"ESR_EL1",(ulong)v);
  el3_reg_bit_name32_print(g_reg_ESR_ELx,v);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111310
 * symbol: aarch64_print_ESR_EL2
 * prototype: void aarch64_print_ESR_EL2(void)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_ESR_EL2(void)

{
  uint v;
  u_int uVar1;
  
  v = aarch64_read_ESR_EL2();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar1,"ESR_EL2",(ulong)v);
  el3_reg_bit_name32_print(g_reg_ESR_ELx,v);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111368
 * symbol: aarch64_print_ESR_EL3
 * prototype: void aarch64_print_ESR_EL3(void)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_ESR_EL3(void)

{
  uint v;
  u_int uVar1;
  
  v = aarch64_read_ESR_EL3();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar1,"ESR_EL3",(ulong)v);
  el3_reg_bit_name32_print(g_reg_ESR_ELx,v);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001113c0
 * symbol: aarch64_print_ISS_instruction_abort
 * prototype: void aarch64_print_ISS_instruction_abort(uint32_t iss)
 * body addresses: 172
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_ISS_instruction_abort(uint32_t iss)

{
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:SET =0x%08x\n",(ulong)uVar1,"aarch64_print_ISS_instruction_abort",
             (ulong)(iss & 0x1800));
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:IFSC=0x%08x\n",(ulong)uVar1,"aarch64_print_ISS_instruction_abort",
             (ulong)(iss & 0x1f));
  uVar1 = mp4_get_cpu();
  if (iss == 0x10) {
    printf_low("%d:%s:AARCH64_ESR_ELx_ISS_IFSC_SYNCHRONOUS_EXTERNAL_ABORT_NOT_ON_TRANS\n",
               (ulong)uVar1,"aarch64_print_ISS_instruction_abort");
    return;
  }
  printf_low("%d:%s:IFSC=0x%08x\n",(ulong)uVar1,"aarch64_print_ISS_instruction_abort",
             (ulong)(iss & 0x1f));
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011146c
 * symbol: aarch64_print_HCR_EL2
 * prototype: void aarch64_print_HCR_EL2(void)
 * body addresses: 228
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_HCR_EL2(void)

{
  ulong uVar1;
  u_int uVar2;
  char *pcVar3;
  ulong uVar4;
  ulong uVar5;
  char **ppcVar6;
  int iVar7;
  
  uVar5 = hcr_el2;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%016lx:",(ulong)uVar2,"HCR_EL2",uVar5);
  iVar7 = 1;
  for (ppcVar6 = &g_reg_HCR_EL2[0].name;
      (uVar4 = ((el3_reg_bit_name64 *)(ppcVar6 + -2))->bit, uVar4 != 0 || (*ppcVar6 != (char *)0x0))
      ; ppcVar6 = ppcVar6 + 3) {
    uVar1 = uVar4;
    if (ppcVar6[-1] != (char *)0x0) {
      uVar1 = (ulong)ppcVar6[-1];
    }
    if ((uVar1 & uVar5) == uVar4) {
      pcVar3 = *ppcVar6;
      if (pcVar3 != (char *)0x0) {
        if (iVar7 == 0) {
          printf_low(",");
          pcVar3 = *ppcVar6;
        }
        else {
          iVar7 = iVar7 + -1;
        }
        printf_low("%s",pcVar3);
      }
      uVar5 = uVar5 & (uVar1 ^ 0xffffffffffffffff);
    }
  }
  if (uVar5 != 0) {
    printf_low("[0x%016lx]",uVar5);
  }
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111550
 * symbol: aarch64_print_SCR_EL3
 * prototype: void aarch64_print_SCR_EL3(void)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SCR_EL3(void)

{
  ulong uVar1;
  u_int uVar2;
  
  uVar1 = scr_el3;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar2,"SCR_EL3",uVar1 & 0xffffffff);
  el3_reg_bit_name32_print(g_reg_SCR_EL3,(uint32_t)uVar1);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001115a4
 * symbol: aarch64_print_SCTLR_EL1
 * prototype: void aarch64_print_SCTLR_EL1(void)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SCTLR_EL1(void)

{
  ulong uVar1;
  u_int uVar2;
  
  uVar1 = sctlr_el1;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar2,"SCTLR_EL1",uVar1 & 0xffffffff);
  el3_reg_bit_name32_print(g_reg_SCTLR_EL1,(uint32_t)uVar1);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001115f8
 * symbol: aarch64_print_SCTLR_EL2
 * prototype: void aarch64_print_SCTLR_EL2(void)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SCTLR_EL2(void)

{
  ulong uVar1;
  u_int uVar2;
  
  uVar1 = sctlr_el2;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar2,"SCTLR_EL2",uVar1 & 0xffffffff);
  el3_reg_bit_name32_print(g_reg_SCTLR_EL2,(uint32_t)uVar1);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011164c
 * symbol: aarch64_print_SCTLR_EL3
 * prototype: void aarch64_print_SCTLR_EL3(void)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_print_SCTLR_EL3(void)

{
  ulong uVar1;
  u_int uVar2;
  
  uVar1 = sctlr_el3;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%08x:",(ulong)uVar2,"SCTLR_EL3",uVar1 & 0xffffffff);
  el3_reg_bit_name32_print(g_reg_SCTLR_EL2,(uint32_t)uVar1);
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001116a0
 * symbol: aarch64_read_ELR
 * prototype: uint64_t aarch64_read_ELR(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t aarch64_read_ELR(void)

{
  uint64_t uVar1;
  
  uVar1 = elr_el3;
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001116a4
 * symbol: aarch64_read_ESR
 * prototype: uint64_t aarch64_read_ESR(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t aarch64_read_ESR(void)

{
  uint64_t uVar1;
  
  uVar1 = esr_el3;
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001116a8
 * symbol: aarch64_read_FAR
 * prototype: uint64_t aarch64_read_FAR(void)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t aarch64_read_FAR(void)

{
  uint64_t uVar1;
  
  uVar1 = far_el3;
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001116b0
 * symbol: aarch64_address_translation_read
 * prototype: uint64_t aarch64_address_translation_read(void * va)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t aarch64_address_translation_read(void *va)

{
  undefined8 uVar1;
  uint64_t uVar2;
  
  uVar1 = AT_S1E3R(va);
  par_el1 = uVar1;
  uVar2 = par_el1;
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001116bc
 * symbol: aarch64_address_translation_write
 * prototype: uint64_t aarch64_address_translation_write(void * va)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t aarch64_address_translation_write(void *va)

{
  undefined8 uVar1;
  uint64_t uVar2;
  
  uVar1 = AT_S1E3W(va);
  par_el1 = uVar1;
  uVar2 = par_el1;
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001116c8
 * symbol: aarch64_ccahe_op_init
 * prototype: void aarch64_ccahe_op_init(void)
 * body addresses: 324
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void aarch64_ccahe_op_init(void)

{
  u_int uVar1;
  undefined8 uVar2;
  
  uVar2 = aarch64_read_CLIDR_EL1();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:CLIDR_EL1=0x%016lx\n",(ulong)uVar1,"aarch64_ccahe_op_init",uVar2);
  csselr_el1 = 0;
  InstructionSynchronizationBarrier();
  uVar2 = ccsidr_el1;
  g_L1D_NumSets = (uint)uVar2 >> 0xd & 0x7fff;
  g_L1D_Associativity = (uint)uVar2 >> 3 & 0x3ff;
  csselr_el1 = 1;
  InstructionSynchronizationBarrier();
  uVar2 = ccsidr_el1;
  g_L1I_NumSets = (uint)uVar2 >> 0xd & 0x7fff;
  g_L1I_Associativity = (uint)uVar2 >> 3 & 0x3ff;
  csselr_el1 = 2;
  InstructionSynchronizationBarrier();
  uVar2 = ccsidr_el1;
  g_L2D_NumSets = (uint)uVar2 >> 0xd & 0x7fff;
  g_L2D_Associativity = (uint)uVar2 >> 3 & 0x3ff;
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:g_L1D_NumSets       = 0x%08x\n",(ulong)uVar1,"aarch64_ccahe_op_init",
             (ulong)g_L1D_NumSets);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:g_L1D_Associativity = 0x%08x\n",(ulong)uVar1,"aarch64_ccahe_op_init",
             (ulong)g_L1D_Associativity);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:g_L1I_NumSets       = 0x%08x\n",(ulong)uVar1,"aarch64_ccahe_op_init",
             (ulong)g_L1I_NumSets);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:g_L1I_Associativity = 0x%08x\n",(ulong)uVar1,"aarch64_ccahe_op_init",
             (ulong)g_L1I_Associativity);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:g_L2D_NumSets       = 0x%08x\n",(ulong)uVar1,"aarch64_ccahe_op_init",
             (ulong)g_L2D_NumSets);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:g_L2D_Associativity = 0x%08x\n",(ulong)uVar1,"aarch64_ccahe_op_init",
             (ulong)g_L2D_Associativity);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011180c
 * symbol: aarch64_CISW_all
 * prototype: int aarch64_CISW_all(void)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int aarch64_CISW_all(void)

{
  uint32_t in_w1;
  
  aarch64_cache_op_set_way(cache_op_csw,in_w1);
  aarch64_cache_op_set_way(cache_op_isw,in_w1);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111830
 * symbol: aarch64_cache_op_set_way
 * prototype: int aarch64_cache_op_set_way(cache_op_sw_type_t op, uint32_t level)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int aarch64_cache_op_set_way(cache_op_sw_type_t op,uint32_t level)

{
  uint uVar1;
  uint uVar2;
  ulong uVar3;
  ulong uVar4;
  uint32_t *puVar5;
  uint32_t *puVar6;
  int iVar7;
  
  puVar5 = &g_L1D_NumSets;
  if (op == cache_op_csw) {
    uVar3 = 0;
    puVar6 = &g_L1D_Associativity;
    uVar2 = 0x1e;
  }
  else {
    if (op != cache_op_isw) {
      return op;
    }
    puVar6 = &g_L2D_Associativity;
    puVar5 = &g_L2D_NumSets;
    uVar2 = 0x1c;
    uVar3 = 2;
  }
  for (uVar4 = 0; uVar4 != *puVar5 + 1; uVar4 = uVar4 + 1) {
    iVar7 = 0;
    while (*puVar6 + 1 != iVar7) {
      uVar1 = iVar7 << (ulong)uVar2;
      iVar7 = iVar7 + 1;
      DC_CISW(uVar3 | (uVar4 & 0x3ffffff) << 6 | (ulong)uVar1);
    }
  }
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  return op;
}


