/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\arm_timer.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001147c4
 * symbol: arm_timer_init
 * prototype: int arm_timer_init(void)
 * body addresses: 164
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int arm_timer_init(void)

{
  undefined8 uVar1;
  ulong uVar2;
  u_int uVar3;
  
  uVar2 = cntkctl_el1;
  cntkctl_el1 = uVar2 & 0xfffffffe | 1;
  uVar3 = mp4_get_cpu();
  uVar1 = cntkctl_el1;
  printf_low("%d:%s:CNTKCTL_EL1 :    0x%08x\n",(ulong)uVar3,"arm_timer_init",uVar1);
  uVar3 = mp4_get_cpu();
  uVar1 = cntfrq_el0;
  printf_low("%d:%s:CNTFRQ_EL0 :     0x%08x\n",(ulong)uVar3,"arm_timer_init",uVar1);
  uVar3 = mp4_get_cpu();
  uVar1 = cntp_ctl_el0;
  printf_low("%d:%s:CNTP_CTL_EL0 :   0x%08x\n",(ulong)uVar3,"arm_timer_init",uVar1);
  uVar3 = mp4_get_cpu();
  uVar1 = cntpct_el0;
  printf_low("%d:%s:CNTPCT_EL0 :     0x%016lx\n",(ulong)uVar3,"arm_timer_init",uVar1);
  return 0;
}


