/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\boot.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00107b40
 * symbol: el3_print_common
 * prototype: void el3_print_common(void)
 * body addresses: 1224
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void el3_print_common(void)

{
  u_int uVar1;
  ulong uVar2;
  uint64_t uVar3;
  undefined8 uVar4;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"el3_print_common");
  aarch64_print_CurrentEL();
  uVar1 = mp4_get_cpu();
  uVar2 = aarch64_read_DAIF((ulong)uVar1);
  printf_low("%d:%s:DAIF:           0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar2 & 0xffffffff);
  uVar1 = mp4_get_cpu();
  uVar3 = aarch64_read_ELR();
  printf_low("%d:%s:ELR             0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar3);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_NZCV((ulong)uVar1);
  printf_low("%d:%s:NZCV            0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_SP_EL0((ulong)uVar1);
  printf_low("%d:%s:SP_EL0          0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_SP_EL1((ulong)uVar1);
  printf_low("%d:%s:SP_EL1          0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_SP_EL2((ulong)uVar1);
  printf_low("%d:%s:SP_EL2          0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_SPSR_EL1((ulong)uVar1);
  printf_low("%d:%s:SPSR_EL1        0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_SPSR_EL2((ulong)uVar1);
  printf_low("%d:%s:SPSR_EL2        0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = spsr_el3;
  printf_low("%d:%s:SPSR_EL3        0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_SPSel((ulong)uVar1);
  printf_low("%d:%s:SPSel           0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_MIDR_EL1((ulong)uVar1);
  printf_low("%d:%s:MIDR_EL1        0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_MPIDR_EL1((ulong)uVar1);
  printf_low("%d:%s:MPIDR_EL1       0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_CLIDR_EL1((ulong)uVar1);
  printf_low("%d:%s:CLIDR_EL1       0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_CONTEXTIDR_EL1((ulong)uVar1);
  printf_low("%d:%s:CONTEXTIDR_EL1  0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_CSSELR_EL1((ulong)uVar1);
  printf_low("%d:%s:CSSELR_EL1      0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_ESR_EL1((ulong)uVar1);
  printf_low("%d:%s:ESR_EL1         0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_ESR_EL2((ulong)uVar1);
  printf_low("%d:%s:ESR_EL2         0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = far_el1;
  printf_low("%d:%s:FAR_EL1         0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = far_el2;
  printf_low("%d:%s:FAR_EL2         0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = far_el3;
  printf_low("%d:%s:FAR_EL3         0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_VBAR_EL2((ulong)uVar1);
  printf_low("%d:%s:VBAR_EL2        0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = vbar_el3;
  printf_low("%d:%s:VBAR_EL3        0x%016lx\n",(ulong)uVar1,"el3_print_common",uVar4);
  aarch64_print_HCR_EL2();
  uVar1 = mp4_get_cpu();
  uVar4 = sctlr_el1;
  printf_low("%d:SCTLR_EL1       0x%016lx\n",(ulong)uVar1,uVar4);
  aarch64_print_SCTLR_EL2();
  uVar1 = mp4_get_cpu();
  uVar4 = sctlr_el3;
  printf_low("%d:SCTLR_EL3       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TCR_EL1((ulong)uVar1);
  printf_low("%d:TCR_EL1         0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TCR_EL2((ulong)uVar1);
  printf_low("%d:TCR_EL2         0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = tpidr_el0;
  printf_low("%d:TPIDR_EL0       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TPIDR_EL1((ulong)uVar1);
  printf_low("%d:TPIDR_EL1       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TPIDR_EL2((ulong)uVar1);
  printf_low("%d:TPIDR_EL2       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = tpidr_el3;
  printf_low("%d:TPIDR_EL3       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = tpidrro_el0;
  printf_low("%d:TPIDRRO_EL0     0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TTBR0_EL1((ulong)uVar1);
  printf_low("%d:TTBRO_EL1       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TTBR0_EL2((ulong)uVar1);
  printf_low("%d:TTBRO_EL2       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TTBR0_EL3((ulong)uVar1);
  printf_low("%d:TTBRO_EL3       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_TTBR1_EL1((ulong)uVar1);
  printf_low("%d:TTBR1_EL1       0x%016lx\n",(ulong)uVar1,uVar4);
  uVar1 = mp4_get_cpu();
  uVar4 = aarch64_read_CBAR_EL1((ulong)uVar1);
  printf_low("%d:CBAR_EL1        0x%016lx\n",(ulong)uVar1,uVar4);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00108008
 * symbol: el3_jmpbuf_enter
 * prototype: void * el3_jmpbuf_enter(el3_jmp_buf * n)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void * el3_jmpbuf_enter(el3_jmp_buf *n)

{
  el3_jmp_buf *peVar1;
  
  peVar1 = el3_jmpbufp;
  el3_jmpbufp = n;
  return peVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00108024
 * symbol: el3_jmpbuf_exit
 * prototype: void el3_jmpbuf_exit(el3_jmp_buf * n)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void el3_jmpbuf_exit(el3_jmp_buf *n)

{
  el3_jmpbufp = n;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00108034
 * symbol: el3_boot
 * prototype: int el3_boot(uint64_t * log, printf_func_t printf_func, uint32_t cp_param2)
 * body addresses: 2368
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Removing unreachable block (ram,0x00108108) */
/* WARNING: Unknown calling convention */

int el3_boot(uint64_t *log,printf_func_t printf_func,uint32_t cp_param2)

{
  ulong *log_another;
  int *piVar1;
  u_int uVar2;
  u_int uVar3;
  int iVar4;
  uint uVar5;
  dev_context_t *p;
  undefined8 uVar6;
  char *pcVar7;
  code *pcVar8;
  
  uVar2 = mp4_get_cpu();
  log_another = &DAT_00001d00;
  if (uVar2 == 0) {
    (*printf_func)("================================================\n");
    (*printf_func)("el3_boot(cp_param2 0x%08x) 0.5.0.01 [2018-11-13]\n",(ulong)cp_param2,0x50202,9);
    (*printf_func)("el3_bss:SKIP:  0x%08x-0x%08x\n",&g_count_0,&__loader_el3_bss_end);
    (*printf_func)("dev_bss:CLEAR:  0x%08x-0x%08x\n",EL2_VBAR,EL2_VBAR);
    g_param.core0_main = mm_controller_dram_entry;
    g_param.core0_dev_context = &g_dev_context_el3_core0;
    g_param.log0 = &DAT_00001900;
    g_param.core1_main = io_controller_dram_entry;
    g_param.core1_dev_context = &g_dev_context_el3_core1;
    g_param.log1 = &DAT_00001d00;
    DAT_00000050 = 0x91;
    el3_show_steps(printf_func,"el3_boot 1st entry",log,&DAT_00001d00);
    *log = 0x600;
    el3_show_steps(printf_func,"wait 0x600 ANOTHER CORE",log,&DAT_00001d00);
    do {
    } while (DAT_00001d00 < 0x600);
    el3_show_steps(printf_func,"after 0x600 ANOTHER CORE",log,&DAT_00001d00);
  }
  else {
    log_another = &DAT_00001900;
    *log = 0x6fe;
    do {
    } while (DAT_00001900 < 0x700);
    *log = 0x6ff;
  }
  uVar3 = mp4_get_cpu();
  if (uVar3 == 0) {
    if ((cp_param2 & 0x2000200) == 0x200) {
      (*printf_func)("USE PERICOM\n");
      pcVar8 = putchar_pericom;
    }
    else {
      pcVar8 = putchar_cp;
    }
    p = &g_dev_context_el3_core0;
    g_dev_context_el3_core0.dc_putchar_low_hook = pcVar8;
  }
  else {
    g_dev_context_el3_core1.dc_putchar_low_hook = putchar_cp;
    if (((cp_param2 >> 9 & 1) != 0) &&
       (g_dev_context_el3_core1.dc_putchar_low_hook = putchar_pericom, (cp_param2 & 0x20000) != 0))
    {
      g_dev_context_el3_core1.dc_putchar_low_hook = putchar_cp;
    }
    p = &g_dev_context_el3_core1;
  }
  dev_context_init_for_el3(p);
  mp4_debug_status_init();
  if (uVar2 == 0) {
    printf_low("----- %s -----\n","el3_boot 1st entry");
    printf_low("log        =%p, step=0x%016lx\n",log,*log);
    printf_low("log_another=%p, step=0x%016lx\n",log_another,*log_another);
    *log = 0x700;
    printf_low("----- %s -----\n","wait 0x700 ANOTHER CORE");
    printf_low("log        =%p, step=0x%016lx\n",log,*log);
    printf_low("log_another=%p, step=0x%016lx\n",log_another,*log_another);
    do {
    } while (*log_another < 0x700);
    el3_show_steps(printf_func,"after 0x700 ANOTHER CORE",log,log_another);
  }
  else {
    *log = 0x7fe;
    do {
    } while (*log_another < 0x800);
    *log = 0x7ff;
  }
  printf_low("================================================\n");
  printf_low("el3_boot(cp_param2 0x%08x) 0.5.0.01 [2018-11-13]\n",(ulong)cp_param2,0x50202,9);
  printf_low("call from printf_low\n");
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    cp_param_init();
    g_layout.msl_loader_el3_text.msi_begin = 0x100000;
    g_layout.msl_loader_el3_text.msi_end = (uint64_t)&__loader_el3_text_end;
    g_layout.msl_loader_el3_text.msi_page_size = 0x15000;
    g_layout.msl_loader_el3_text.msi_sram = 0x10000;
    g_layout.msl_loader_el3_text.msi_pa = (uint64_t)&DAT_88000000;
    g_layout.msl_loader_el3_data.msi_begin = (uint64_t)&g_layout;
    g_layout.msl_loader_el3_data.msi_end = (uint64_t)&__loader_el3_bss_end;
    g_layout.msl_loader_el3_data.msi_page_size = 0x2000;
    g_layout.msl_loader_el3_data.msi_sram = 0x25000;
    g_layout.msl_loader_el3_data.msi_pa = 0x88015000;
    g_layout.msl_loader_dev_text.msi_begin = (uint64_t)mp4_get_cpu;
    g_layout.msl_loader_dev_text.msi_end = (uint64_t)&__loader_dev_text_end;
    g_layout.msl_loader_dev_text.msi_pa = 0x88017000;
    g_layout.msl_loader_dev_data.msi_begin = (uint64_t)EL2_VBAR;
    g_layout.msl_loader_dev_text.msi_page_size = 0xd000;
    g_layout.msl_loader_dev_text.msi_sram = 0x27000;
    g_layout.msl_loader_dev_data.msi_end = (uint64_t)EL2_VBAR;
    g_layout.msl_loader_dev_data.msi_page_size = 0;
    g_layout.msl_loader_el2.msi_begin = (uint64_t)EL2_VBAR;
    g_layout.msl_loader_el2.msi_end = (uint64_t)&__loader_el2_end;
    g_layout.msl_loader_dev_data.msi_sram = 0x34000;
    g_layout.msl_loader_dev_data.msi_pa = 0x88024000;
    g_layout.msl_loader_el2.msi_page_size = 0x1000;
    g_layout.msl_loader_el2.msi_sram = 0x34000;
    g_layout.msl_loader_el2.msi_pa = 0x88024000;
    g_layout.msl_loader_el1.msi_begin = (uint64_t)EL1_VBAR;
    g_layout.msl_loader_el1.msi_end = (uint64_t)&__loader_el1_end;
    g_layout.msl_loader_el1.msi_page_size = 0x1000;
    g_layout.msl_loader_el1.msi_sram = 0x35000;
    g_layout.msl_loader_el1.msi_pa = 0x88025000;
    g_layout.msl_controller_dev_text.msi_begin = 0x6000000;
    g_layout.msl_controller_dev_text.msi_end = (uint64_t)&__controller_dev_text_end;
    g_layout.msl_controller_dev_text.msi_page_size = 0x6a000;
    g_layout.msl_controller_dev_text.msi_sram = 0x30000;
    g_layout.msl_controller_dev_data.msi_end = (uint64_t)&__controller_dev_data_end;
    g_layout.msl_controller_dev_data.msi_page_size = 0x1000;
    g_layout.msl_controller_dev_text.msi_pa = 0x88020000;
    g_layout.msl_controller_dev_data.msi_begin = (uint64_t)&g_dev_context_mm;
    g_layout.msl_controller_dev_data.msi_sram = 0x40000;
    g_layout.msl_controller_dev_data.msi_pa = 0x88030000;
    *log = 0x1000;
  }
  else {
    do {
    } while (*log_another < 0x1000);
  }
  printf_low("after 0x1000\n");
  uVar2 = mp4_get_cpu();
  piVar1 = &g_count_0;
  if (uVar2 != 0) {
    piVar1 = &g_count_1;
  }
  *piVar1 = 0;
  el3_jmpbufp = (el3_jmp_buf *)0x0;
  uVar2 = mp4_get_cpu();
  uVar6 = aarch64_read_CPUECTLR_EL1((ulong)uVar2);
  printf_low("%d:%s:CPUECTLR_EL1:   0x%016lx\n",(ulong)uVar2,"el3_boot",uVar6);
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2ca,1,"sizeof(int8_t) == 1");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2cb,1,"sizeof(uint8_t) == 1");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2cc,1,"sizeof(int16_t) == 2");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2cd,1,"sizeof(uint16_t) == 2");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2ce,1,"sizeof(int32_t) == 4");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2cf,1,"sizeof(uint32_t) == 4");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2d0,1,"sizeof(int64_t) == 8");
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\boot.c");
  el3_assert(pcVar7,"el3_boot",0x2d1,1,"sizeof(uint64_t) == 8");
  uVar6 = vbar_el3;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:_loader_el3_vector     : %p\n",(ulong)uVar2,"el3_boot",EL3_VBAR);
  vbar_el3 = 0x107000;
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    aarch64_ccahe_op_init();
    mmu_init_phase1();
    mmu_init_phase2a();
    *log = (uint64_t)&DAT_00001100;
  }
  else {
    do {
    } while (*log_another >> 8 < 0x11);
  }
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:after 0x1100\n",(ulong)uVar2,"el3_boot");
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    mmu_init_phase2b();
    syshub_init();
    *log = (uint64_t)&DAT_00001200;
  }
  else {
    do {
    } while (*log_another >> 9 < 9);
  }
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:after 0x1200\n",(ulong)uVar2,"el3_boot");
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    c2pmsg_init();
    dvm_init();
    arm_timer_init();
    mp4_timer_init();
    *log = (uint64_t)&DAT_00001300;
  }
  else {
    arm_timer_init();
    do {
    } while (*log_another >> 8 < 0x13);
  }
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:after 0x1300\n",(ulong)uVar2,"el3_boot");
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    msi_get_info_by_1st_core();
    syshub_init_after_main_param();
    smnif_init();
    gic_init_by_1st_core();
    gic_v2m_init();
    *log = (uint64_t)&DAT_000013ff;
    do {
    } while ((undefined *)*log_another < &DAT_000013ff);
    *log = (uint64_t)&DAT_00001400;
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:after step 0x1400!\n",(ulong)uVar2,"el3_boot");
    msi_send_command_sync(0,0x10030000);
  }
  else {
    *log = (uint64_t)&DAT_000013ff;
    do {
    } while ((undefined *)*log_another < &DAT_000013ff);
    *log = (uint64_t)&DAT_00001400;
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:after step 0x1400!\n",(ulong)uVar2,"el3_boot");
    gic_init_by_2nd_core();
    msi_get_info_by_2nd_core();
  }
  iVar4 = msi_has_internal_qaf();
  if (iVar4 == 0) {
    uVar5 = mp4_get_cpu();
    pcVar7 = "%d:%s:No QAF!!!\n";
  }
  else {
    iVar4 = cp_param_check(0x100);
    if (iVar4 != 0) goto LAB_001088e4;
    uVar2 = mp4_get_cpu();
    if (uVar2 == 0) {
      deci5s_mp4_start(0);
      msi_send_command_sync(0,0x10070000);
      *log = (uint64_t)&DAT_000015ff;
      do {
      } while ((undefined *)*log_another < &DAT_000015ff);
      *log = (uint64_t)&LAB_00001600;
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:after step 0x1600!\n",(ulong)uVar2,"el3_boot");
      *log = (uint64_t)&DAT_000016ff;
      do {
      } while ((undefined *)*log_another < &DAT_000016ff);
    }
    else {
      *log = (uint64_t)&DAT_000015ff;
      do {
      } while ((undefined *)*log_another < &DAT_000015ff);
      *log = (uint64_t)&LAB_00001600;
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:after step 0x1600!\n",(ulong)uVar2,"el3_boot");
      deci5s_mp4_start(1);
      *log = (uint64_t)&DAT_000016ff;
      do {
      } while ((undefined *)*log_another < &DAT_000016ff);
    }
    *log = (uint64_t)&LAB_00001700;
    uVar5 = mp4_get_cpu();
    pcVar7 = "%d:%s:after step 0x1700!\n";
  }
  printf_low(pcVar7,(ulong)uVar5,"el3_boot");
LAB_001088e4:
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    msi_send_command_sync(0,0x10080000);
    *log = (uint64_t)&DAT_000017ff;
    do {
    } while ((undefined *)*log_another < &DAT_000017ff);
  }
  else {
    *log = (uint64_t)&DAT_000017ff;
    do {
    } while ((undefined *)*log_another < &DAT_000017ff);
  }
  *log = 0x1800;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:after step 0x1800!\n",(ulong)uVar2,"el3_boot");
  el0_support(&g_param,cp_param2);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:STOP MP4/A53\n",(ulong)uVar2,"el3_boot");
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00108974
 * symbol: el3_show_steps
 * prototype: void el3_show_steps(printf_func_t printf_func, char * msg, uint64_t * log, uint64_t * log_another)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void el3_show_steps(printf_func_t printf_func,char *msg,uint64_t *log,uint64_t *log_another)

{
  (*printf_func)("----- %s -----\n");
  (*printf_func)("log        =%p, step=0x%016lx\n",log,*log);
                    /* WARNING: Could not recover jumptable at 0x001089d8. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*printf_func)("log_another=%p, step=0x%016lx\n",log_another,*log_another);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001089dc
 * symbol: el3_serror_handler
 * prototype: void el3_serror_handler(uint64_t x0, uint64_t vector)
 * body addresses: 5584
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void el3_serror_handler(uint64_t x0,uint64_t vector)

{
  int *piVar1;
  el3_jmp_buf *peVar2;
  uint uVar3;
  uint uVar4;
  u_int uVar5;
  u_int uVar6;
  uint uVar7;
  uint32_t v;
  uint32_t command;
  uint32_t bits;
  int iVar8;
  uint uVar9;
  dev_context_t *pdVar10;
  mp4_debug_status_t *status;
  long lVar11;
  ulong uVar12;
  uint64_t uVar13;
  ulong uVar14;
  undefined8 uVar15;
  uint64_t uVar16;
  ulong uVar17;
  char *pcVar18;
  uint64_t uVar19;
  uint64_t *puVar20;
  uint64_t *puVar21;
  undefined auStack_a0 [12];
  u_int local_94;
  ulong local_90;
  dev_context_t *local_88;
  uint64_t local_80;
  ulong local_78;
  long local_70;
  ulong local_68;
  
  pdVar10 = get_dev_context();
  status = mp4_debug_status_get();
  uVar5 = mp4_get_cpu();
  mp4_debug_status_c_set();
  piVar1 = &g_count_0;
  if (uVar5 != 0) {
    piVar1 = &g_count_1;
  }
  *piVar1 = *piVar1 + 1;
  uVar17 = currentel;
  if ((~(uint)uVar17 & 0xc) != 0) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:Invalid CurrentEL=0x%08x\n",(ulong)uVar5,"el3_serror_handler",
               uVar17 & 0xffffffff);
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  }
  local_68 = aarch64_read_ELR_EL1();
  lVar11 = aarch64_read_ELR_EL2();
  uVar12 = aarch64_read_ELR_EL3();
  uVar13 = aarch64_read_ESR();
  uVar15 = spsr_el3;
  uVar15 = tpidr_el3;
  uVar16 = uVar13;
  uVar19 = vector;
  switch(vector >> 7 | vector << 0x39) {
  case 0:
  case 1:
  case 2:
  case 3:
    break;
  case 4:
  case 5:
  case 6:
  case 7:
    uVar19 = vector - 0x200;
    break;
  case 8:
  case 9:
  case 10:
  case 0xb:
    uVar19 = vector - 0x400;
    break;
  case 0xc:
  case 0xd:
  case 0xe:
  case 0xf:
    uVar19 = vector - 0x600;
    break;
  default:
    uVar6 = mp4_get_cpu();
    uVar7 = printf_low("%d:%s:vector=0x%016lx",(ulong)uVar6,"el3_serror_handler",vector);
    uVar19 = 0;
    uVar16 = (ulong)uVar7;
  }
  if (3 < (uVar19 >> 7 | uVar19 << 0x39)) {
    uVar7 = printf_low("Unknown vecto_offsetr=0x%016lx");
    uVar16 = (uint64_t)uVar7;
  }
  if ((vector == 0x480) || (vector == 0x280)) {
    v = gic_read_GICC_IAR();
    if ((v == 0x53) || (v == 0x4e)) {
      command = msi_read_c2p_command(uVar5);
      bits = msi_read_c2p_arg1(uVar5);
      iVar8 = msi_has_internal_qaf();
      if (iVar8 != 0) {
        if (command >> 0xc == 0x20211) {
          deci_target_mp4_intr(bits);
        }
        else {
          uVar6 = mp4_get_cpu();
          printf_low("%d:%s:Unsupport command 0x%08x\n",(ulong)uVar6,"el3_serror_handler",
                     (ulong)command);
        }
      }
      msi_write_c2p_ack(uVar5,command);
    }
    else {
      uVar5 = mp4_get_cpu();
      printf_low("%d:%s:Unsupport IID = 0x%08x\n",(ulong)uVar5,"el3_serror_handler",(ulong)v);
    }
    gic_write_GICC_EOIR(v);
    if (vector == 0x480) {
      pdVar10 = get_dev_context();
      if (pdVar10->dc_dev_context_el0 != (dev_context_t *)0x0) {
        tpidrro_el0 = pdVar10->dc_dev_context_el0;
        pdVar10->dc_dev_context_el0 = (dev_context_t *)0x0;
      }
    }
    elr_el1 = 0;
    elr_el2 = 0;
    return;
  }
  local_70 = lVar11;
  if (local_68 == 0) {
    local_78 = 0;
  }
  else {
    uVar14 = aarch64_read_SPSR_EL1(uVar16);
    local_78 = aarch64_read_ESR_EL1();
    if (((uint)(local_78 >> 0x1a) & 0x3f) == 0x15) {
      svc_EL3((uint32_t)local_78,status);
      spsr_el3 = uVar14 & 0xffffffff;
      elr_el3 = local_68;
      pdVar10 = get_dev_context();
      if (pdVar10->dc_dev_context_el0 == (dev_context_t *)0x0) {
        return;
      }
      tpidrro_el0 = pdVar10->dc_dev_context_el0;
      pdVar10->dc_dev_context_el0 = (dev_context_t *)0x0;
      return;
    }
    uVar6 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport EC\n",(ulong)uVar6,"el3_serror_handler");
    aarch64_print_ESR_EL1();
  }
  uVar6 = mp4_get_cpu();
  printf_low("%d:%s:<<<<< <<<<< vector=0x%08x >>>>> >>>>>\n",(ulong)uVar6,"el3_serror_handler",
             vector);
  uVar6 = mp4_get_cpu();
  printf_low("%d:%s:(0x%016lx, 0x%016lx)\n",(ulong)uVar6,"el3_serror_handler",x0,vector);
  if (local_68 != 0) {
    uVar15 = far_el1;
    uVar6 = mp4_get_cpu();
    printf_low("%d:%s:----- EL1 -----\n",(ulong)uVar6,"el3_serror_handler");
    aarch64_print_SCTLR_EL1();
    aarch64_print_SPSR_EL1();
    aarch64_print_ESR_EL1();
    uVar6 = mp4_get_cpu();
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar6,"ELR_EL1",local_68);
    uVar6 = mp4_get_cpu();
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar6,"FAR_EL1",uVar15);
    if (((uint)(local_78 >> 0x1a) & 0x3f) == 0x24) {
      uVar6 = mp4_get_cpu();
      printf_low("%d:%s:AARCH64_ESR_ELx_EC_DATA_ABORT_LOW_EL\n",(ulong)uVar6,"el3_serror_handler");
      uVar7 = (uint)local_78;
      if ((uVar7 >> 0x19 & 1) != 0) {
        uVar6 = mp4_get_cpu();
        printf_low("%d:%s:- IL\n",(ulong)uVar6,"el3_serror_handler");
        uVar7 = (uint)local_78;
      }
      if ((uVar7 >> 6 & 1) != 0) {
        uVar6 = mp4_get_cpu();
        printf_low("%d:%s:- Write Operation\n",(ulong)uVar6,"el3_serror_handler");
        uVar7 = (uint)local_78;
      }
      if ((uVar7 & 0x3f) == 0x21) {
        uVar6 = mp4_get_cpu();
        printf_low("%d:%s:- Alignment fault\n",(ulong)uVar6,"el3_serror_handler");
      }
    }
  }
  lVar11 = local_70;
  local_94 = uVar5;
  local_88 = pdVar10;
  local_80 = uVar13;
  if (local_70 != 0) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:----- EL2 -----\n",(ulong)uVar5,"el3_serror_handler");
    aarch64_print_HCR_EL2();
    aarch64_print_SCTLR_EL2();
    aarch64_print_SPSR_EL2();
    aarch64_print_ESR_EL2();
    uVar5 = mp4_get_cpu();
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL2",lVar11);
    uVar5 = mp4_get_cpu();
    uVar15 = far_el2;
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"FAR_EL2",uVar15);
  }
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:----- EL3 -----\n",(ulong)uVar5,"el3_serror_handler");
  aarch64_print_SCR_EL3();
  aarch64_print_SCTLR_EL3();
  aarch64_print_SPSR_EL3();
  aarch64_print_ESR_EL3();
  uVar5 = mp4_get_cpu();
  printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL3",uVar12);
  uVar5 = mp4_get_cpu();
  uVar15 = far_el3;
  printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"FAR_EL3",uVar15);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:status->mds_1st_vector = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",
             status->mds_1st_vector);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:status->mds_1st_el\t = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",
             status->mds_1st_el);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:status->mds_1st_spsr\t = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",
             status->mds_1st_spsr);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:status->mds_1st_esr\t = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",
             status->mds_1st_esr);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:status->mds_1st_elr\t = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",
             status->mds_1st_elr);
  puVar21 = (uint64_t *)status->mds_sp;
  uVar7 = 0;
  puVar20 = status->mds_gpr + 0x1d;
  uVar16 = local_68;
  local_90 = uVar12;
  if (local_68 == 0) {
    uVar16 = uVar12;
  }
  for (; uVar7 < 0x10; uVar7 = uVar7 + 1) {
    puVar20 = (uint64_t *)*puVar20;
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:PC=0x%016lx:FP=0x%016lx:sp=0x%016lx\n",(ulong)uVar5,"show_backtrace",uVar16,
               puVar20,puVar21);
    uVar15 = AT_S1E3R(puVar20);
    par_el1 = uVar15;
    uVar12 = par_el1;
    if ((uVar12 & 1) != 0) break;
    puVar21 = puVar20 + 2;
    uVar16 = puVar20[1] - 4;
  }
  uVar7 = *(uint *)&status->mds_1st_el & 0xc;
  if (uVar7 == 0xc) {
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_ESR_EL3((ulong)uVar5);
    printf_low("%d:%s:ESR_EL3 =0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    uVar5 = mp4_get_cpu();
    uVar15 = spsr_el3;
    printf_low("%d:%s:SPSR_EL3=0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
  }
  else if (uVar7 == 8) {
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_ESR_EL2((ulong)uVar5);
    printf_low("%d:%s:ESR_EL2 =0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_SPSR_EL2((ulong)uVar5);
    iVar8 = printf_low("%d:%s:SPSR_EL2=0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    if (((uint)(local_80 >> 0x1a) & 0x3f) != 0x17) {
      uVar5 = mp4_get_cpu();
      printf_low("%d:%s:Invalid ESR_EL3.EC=0x%08x\n",(ulong)uVar5,"el3_serror_handler",
                 uVar17 & 0xffffffff);
      do {
                    /* WARNING: Do nothing block with infinite loop */
      } while( true );
    }
    uVar16 = aarch64_read_ESR_EL2(iVar8);
    uVar17 = aarch64_read_ELR_EL2();
    aarch64_read_SPSR_EL2();
  }
  else if (uVar7 == 4) {
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_ESR_EL1((ulong)uVar5);
    printf_low("%d:%s:ESR_EL1 =0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_SPSR_EL1((ulong)uVar5);
    iVar8 = printf_low("%d:%s:SPSR_EL1=0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    if (((uint)(local_80 >> 0x1a) & 0x3f) != 0x17) {
      uVar5 = mp4_get_cpu();
      printf_low("%d:%s:Invalid ESR_EL3.EC=0x%08x\n",(ulong)uVar5,"el3_serror_handler",
                 uVar17 & 0xffffffff);
      do {
                    /* WARNING: Do nothing block with infinite loop */
      } while( true );
    }
    uVar16 = aarch64_read_ESR_EL1(iVar8);
    uVar17 = aarch64_read_ELR_EL1();
    aarch64_read_SPSR_EL1();
  }
  else {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:Unknown mds_1st_el : 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",
               status->mds_1st_el);
    uVar16 = local_80;
    uVar17 = local_90;
  }
  pdVar10 = local_88;
  peVar2 = el3_jmpbufp;
  status->mds_1st_el = 0;
  if (peVar2 != (el3_jmp_buf *)0x0) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:Resume from %p\n",(ulong)uVar5,"el3_serror_handler",el3_jmpbufp);
    el3_longjmp(el3_jmpbufp,1);
  }
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:Exception: vector=0x%016lx, esr=0x%016lx, PC=0x%016lx\n",(ulong)uVar5,
             "el3_serror_handler",vector,uVar16 & 0xffffffff,uVar17);
  uVar19 = aarch64_read_ELR();
  printf_low("Exception: vector=0x%016lx, esr=0x%016lx, PC=0x%016lx\n",vector,uVar16 & 0xffffffff,
             uVar19);
  uVar19 = aarch64_read_ELR();
  printf_low("Exception: vector=0x%016lx, esr=0x%016lx, PC=0x%016lx\n",vector,uVar16 & 0xffffffff,
             uVar19);
  uVar7 = (uint)uVar16;
  if ((uVar7 >> 0x19 & 1) != 0) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:IL: Instruction Length (ESR 0x%08x)\n",(ulong)uVar5,"el3_serror_handler",
               uVar16 & 0xffffffff);
  }
  uVar5 = mp4_get_cpu();
  uVar15 = hcr_el2;
  printf_low("%d:%s:HCR_EL2  =0x%016x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
  uVar5 = mp4_get_cpu();
  uVar15 = scr_el3;
  printf_low("%d:%s:SCR_EL3  =0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
  uVar5 = mp4_get_cpu();
  uVar19 = aarch64_read_FAR();
  printf_low("%d:%s:FAR (Fault Address)=%p\n",(ulong)uVar5,"el3_serror_handler",uVar19);
  uVar15 = spsr_el3;
  uVar5 = mp4_get_cpu();
  uVar9 = uVar7 & 0xfc000000;
  printf_low("%d:----- ----- 0x%08x [0x%08x] ----- -----\n",(ulong)uVar5,uVar16 & 0xffffffff,
             (ulong)uVar9);
  if (uVar9 == 0x80000000) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:Instruction Abort from a lower exception level.\n",(ulong)uVar5,
               "el3_serror_handler");
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_ELR();
    printf_low("%d:%s:ESR=0x%016lx, PC=%p\n",(ulong)uVar5,"el3_serror_handler",uVar16 & 0xffffffff,
               uVar19);
    uVar5 = mp4_get_cpu();
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL1",local_68);
    uVar5 = mp4_get_cpu();
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL2",local_70);
    uVar5 = mp4_get_cpu();
    printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL3",local_90);
    aarch64_print_ISS_instruction_abort(uVar7 & 0x1ffffff);
    goto LAB_00109af4;
  }
  if (uVar9 == 0x84000000) {
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_ELR();
    printf_low("%d:%s:Instruction Abort wo EL: ESR=0x%016lx, PC=%p\n",(ulong)uVar5,
               "el3_serror_handler",uVar16 & 0xffffffff,uVar19);
    aarch64_print_SPSR_EL3();
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_FAR();
    printf_low("%d:%s:FAR (Fault Address)=%p\n",(ulong)uVar5,"el3_serror_handler",uVar19);
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_ELR();
    printf_low("%d:%s:Instruction Abort wo EL: ESR=0x%016lx, PC=%p\n",(ulong)uVar5,
               "el3_serror_handler",uVar16 & 0xffffffff,uVar19);
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_FAR();
    printf_low("%d:%s:FAR (Fault Address)=%p\n",(ulong)uVar5,"el3_serror_handler",uVar19);
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_SP_EL0((ulong)uVar5);
    printf_low("%d:%s:SP_EL0   =%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_SP_EL1((ulong)uVar5);
    printf_low("%d:%s:SP_EL1   =%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    uVar5 = mp4_get_cpu();
    uVar15 = aarch64_read_SP_EL2((ulong)uVar5);
    printf_low("%d:%s:SP_EL2   =%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
    uVar7 = (uint)local_78 & 0x3f;
    uVar5 = mp4_get_cpu();
    uVar17 = (ulong)uVar5;
    if (uVar7 != 0x21) {
      pcVar18 = "%d:%s:- DFSC: 0x%08x";
      uVar12 = (ulong)uVar7;
LAB_00109ab8:
      printf_low(pcVar18,uVar17,"el3_serror_handler",uVar12);
      goto LAB_00109af4;
    }
    pcVar18 = "%d:%s:- Alignment fault\n";
LAB_00109834:
    printf_low(pcVar18,uVar17,"el3_serror_handler");
    goto LAB_00109af4;
  }
  if (uVar9 == 0x88000000) {
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_ELR();
    printf_low("%d:%s:PC Alignment Exception: ESR=0x%016lx, PC=%p\n",(ulong)uVar5,
               "el3_serror_handler",uVar16 & 0xffffffff,uVar19);
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_FAR();
    pcVar18 = "%d:%s:FAR (Fault Address)=%p\n";
    printf_low("%d:%s:FAR (Fault Address)=%p\n",(ulong)uVar5,"el3_serror_handler",uVar19);
    uVar5 = mp4_get_cpu();
    uVar19 = aarch64_read_ELR();
    printf_low("%d:%s:PC Alignment Exception: ESR=0x%016lx, PC=%p\n",(ulong)uVar5,
               "el3_serror_handler",uVar16 & 0xffffffff,uVar19);
    uVar5 = mp4_get_cpu();
    uVar17 = (ulong)uVar5;
    uVar19 = aarch64_read_FAR();
  }
  else if (uVar9 == 0x90000000) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:Data Abort from a lower EL: ESR=0x%08x\n",(ulong)uVar5,"el3_serror_handler",
               uVar16 & 0xffffffff);
    uVar5 = mp4_get_cpu();
    uVar17 = (ulong)uVar5;
    uVar19 = aarch64_read_FAR();
    pcVar18 = "%d:%s:FAR (Fault Address)=%p\n";
  }
  else {
    if (uVar9 == 0x94000000) {
      uVar5 = mp4_get_cpu();
      printf_low("%d:AARCH64_ESR_ELx_EC_DATA_ABORT_WO_EL\n",(ulong)uVar5);
      uVar5 = mp4_get_cpu();
      printf_low("%d:Data Abort wo EL: ESR=0x%08x\n",(ulong)uVar5,uVar16 & 0xffffffff);
      uVar5 = mp4_get_cpu();
      uVar19 = aarch64_read_ELR();
      printf_low("%d:PC=%p\n",(ulong)uVar5,uVar19);
      uVar5 = mp4_get_cpu();
      uVar19 = aarch64_read_FAR();
      printf_low("%d:FAR (Fault Address)=%p\n",(ulong)uVar5,uVar19);
      uVar5 = mp4_get_cpu();
      printf_low("%d:ISS 0x%08x\n",(ulong)uVar5,(ulong)(uVar7 & 0x1ffffff));
      uVar5 = mp4_get_cpu();
      printf_low("%d:Data Abort wo EL: ESR=0x%08lx\n",(ulong)uVar5,uVar16 & 0xffffffff);
      uVar5 = mp4_get_cpu();
      uVar19 = aarch64_read_ELR();
      printf_low("%d:PC=%p\n",(ulong)uVar5,uVar19);
      uVar5 = mp4_get_cpu();
      uVar19 = aarch64_read_FAR();
      printf_low("%d:FAR (Fault Address)=%p\n",(ulong)uVar5,uVar19);
      uVar5 = mp4_get_cpu();
      printf_low("%d:ISS 0x%08x\n",(ulong)uVar5,(ulong)(uVar7 & 0x1ffffff));
      if ((uVar7 >> 6 & 1) != 0) {
        uVar5 = mp4_get_cpu();
        printf_low("%d:ESR: WnR\n",(ulong)uVar5);
      }
      if ((uVar7 & 0x3f) == 0x21) {
        uVar7 = mp4_get_cpu();
        pcVar18 = "%d:ESR: DFSC: Alignment fault\n";
      }
      else {
        if ((uVar7 & 0x3f) != 0x10) {
          uVar5 = mp4_get_cpu();
          printf_low("%d:ESR: DFSC: 0x%02x\n",(ulong)uVar5,(ulong)(uVar7 & 0x3f));
          goto LAB_00109af4;
        }
        uVar7 = mp4_get_cpu();
        pcVar18 = "%d:ESR: DFSC: Synchronous external abort, not on translation table walk\n";
      }
      printf_low(pcVar18,(ulong)uVar7);
      goto LAB_00109af4;
    }
    if (uVar9 == 0xbc000000) {
      uVar5 = mp4_get_cpu();
      uVar19 = aarch64_read_ELR();
      printf_low("%d:%s:SERROR_INTERRUPT in AArch64: PC=%p\n",(ulong)uVar5,"el3_serror_handler",
                 uVar19);
      uVar5 = mp4_get_cpu();
      printf_low("%d:%s:ISS 0x%08x\n",(ulong)uVar5,"el3_serror_handler",(ulong)(uVar7 & 0x1ffffff));
      if ((uVar7 >> 0x18 & 1) == 0) goto LAB_00109af4;
      uVar5 = mp4_get_cpu();
      uVar17 = (ulong)uVar5;
      pcVar18 = "%d:%s:IMPLEMENTATION DEFINED\n";
      goto LAB_00109834;
    }
    if (uVar9 != 0xf0000000) {
      if (uVar9 == 0x5c000000) {
        uVar5 = mp4_get_cpu();
        uVar12 = (ulong)uVar5;
        pcVar18 = "%d:%s:SMC: ESR=0x%016lx, ELR=%p\n";
      }
      else {
        if (uVar9 == 0x38000000) {
          uVar5 = mp4_get_cpu();
          printf_low("%d:%s:Illegal Execution State: ESR=0x%016lx, ELR=%p\n",(ulong)uVar5,
                     "el3_serror_handler",uVar16 & 0xffffffff,uVar17);
          if ((uVar7 >> 0x19 & 1) != 0) {
            uVar5 = mp4_get_cpu();
            printf_low("%d:%s:ESR.IL: Instruction Length\n",(ulong)uVar5,"el3_serror_handler");
          }
          aarch64_print_SPSR_EL3();
          if (((uint)uVar15 & 0x1f) == 0xd) {
            uVar5 = mp4_get_cpu();
            printf_low("%d:%s:%-16s = 0x%08x\n",(ulong)uVar5,"el3_serror_handler","SP (SP_EL3)",
                       auStack_a0);
          }
          uVar5 = mp4_get_cpu();
          uVar19 = aarch64_read_FAR();
          printf_low("%d:%s:FAR (Fault Address)=%p\n",(ulong)uVar5,"el3_serror_handler",uVar19);
          uVar5 = mp4_get_cpu();
          printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL1",local_68);
          uVar5 = mp4_get_cpu();
          printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL2",local_70);
          uVar5 = mp4_get_cpu();
          printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar5,"ELR_EL3",local_90);
          uVar5 = mp4_get_cpu();
          uVar15 = aarch64_read_SP_EL0((ulong)uVar5);
          printf_low("%d:%s:SP_EL0   =%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
          uVar5 = mp4_get_cpu();
          uVar15 = aarch64_read_SP_EL1((ulong)uVar5);
          printf_low("%d:%s:SP_EL1   =%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
          uVar5 = mp4_get_cpu();
          uVar15 = aarch64_read_SP_EL2((ulong)uVar5);
          printf_low("%d:%s:SP_EL2   =%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
          uVar5 = mp4_get_cpu();
          uVar15 = sctlr_el1;
          printf_low("%d:%s:SCTLR_EL1=%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
          uVar5 = mp4_get_cpu();
          uVar15 = sctlr_el3;
          printf_low("%d:%s:SCTLR_EL3=%p\n",(ulong)uVar5,"el3_serror_handler",uVar15);
          uVar5 = mp4_get_cpu();
          uVar15 = aarch64_read_SPSR_EL1((ulong)uVar5);
          printf_low("%d:%s:SPSR_EL1 =0x%08x\n",(ulong)uVar5,"el3_serror_handler",uVar15);
          uVar5 = mp4_get_cpu();
          uVar17 = (ulong)uVar5;
          uVar19 = aarch64_read_SPSR_EL2(uVar17);
          pcVar18 = "%d:%s:SPSR_EL2 =0x%08x\n";
          goto LAB_00109a34;
        }
        if (uVar9 == 0x54000000) {
          uVar5 = mp4_get_cpu();
          uVar12 = (ulong)uVar5;
          pcVar18 = "%d:%s:SVC: ESR=0x%016lx, ELR=%p\n";
        }
        else {
          if ((uVar16 & 0xfc000000) != 0) {
            uVar5 = mp4_get_cpu();
            printf_low("%d:%s:Unknown EC: 0x%08lx\n",(ulong)uVar5,"el3_serror_handler",(ulong)uVar9)
            ;
            uVar5 = mp4_get_cpu();
            uVar17 = (ulong)uVar5;
            pcVar18 = "%d:%s:Unknown EC: ESR=0x%08lx\n";
            uVar12 = uVar16 & 0xffffffff;
            goto LAB_00109ab8;
          }
          uVar5 = mp4_get_cpu();
          uVar12 = (ulong)uVar5;
          pcVar18 = "%d:%s:AARCH64_ESR_ELx_EC_UNKNOWN: ESR=0x%08x, ELR=%p\n";
        }
      }
      printf_low(pcVar18,uVar12,"el3_serror_handler",uVar16 & 0xffffffff,uVar17);
      goto LAB_00109af4;
    }
    uVar5 = mp4_get_cpu();
    uVar17 = (ulong)uVar5;
    uVar19 = aarch64_read_ELR();
    pcVar18 = "%d:%s:BRK instruction in AArch64: PC=%p\n";
  }
LAB_00109a34:
  printf_low(pcVar18,uVar17,"el3_serror_handler",uVar19);
LAB_00109af4:
  el3_print_common();
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x0]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x1]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[1]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x2]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[2]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x3]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[3]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x4]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[4]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x5]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[5]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x6]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[6]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x7]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[7]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x8]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[8]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x8]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[8]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x9]   = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[9]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x10]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[10]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x11]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0xb]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x12]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0xc]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x13]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0xd]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x14]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0xe]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x15]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0xf]);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x16]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x10])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x17]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x11])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x18]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x12])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x21]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x15])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x22]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x16])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x23]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x17])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x24]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x18])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x25]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x19])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x26]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x1a])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x27]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x1b])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x28]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x1c])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x29]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x1d])
  ;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:GPR[x30]  = 0x%016lx\n",(ulong)uVar5,"el3_serror_handler",status->mds_gpr[0x1e])
  ;
  uVar9 = _DAT_032305d0;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:mmMP4_SYSHUB_INT_STATUS=0x%08x\n",(ulong)uVar5,"el3_serror_handler",(ulong)uVar9
            );
  uVar4 = _DAT_032305e0;
  uVar3 = _DAT_032305d4;
  uVar7 = _DAT_03200090;
  if ((uVar9 & 1) == 0) {
    if ((uVar9 >> 1 & 1) == 0) {
      uVar9 = mp4_get_cpu();
      pcVar18 = "%d:%s:mmMP4_NS_PROT_FAULT_STATUS_0 = 0x%08x\n";
    }
    else {
      uVar5 = mp4_get_cpu();
      printf_low("%d:%s:mmMP4_SYSHUB_WR_INT_ADDR  = 0x%08x\n",(ulong)uVar5,"el3_serror_handler",
                 (ulong)uVar3);
      uVar7 = _DAT_032305dc;
      uVar9 = mp4_get_cpu();
      pcVar18 = "%d:%s:mmMP4_SYSHUB_WR_INT_OTHER = 0x%08x\n";
    }
  }
  else {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:mmMP4_SYSHUB_RD_INT_ADDR  = 0x%08x\n",(ulong)uVar5,"el3_serror_handler",
               (ulong)uVar4);
    uVar7 = _DAT_032305e4;
    uVar9 = mp4_get_cpu();
    pcVar18 = "%d:%s:mmMP4_SYSHUB_RD_INT_OTHER = 0x%08x\n";
  }
  printf_low(pcVar18,(ulong)uVar9,"el3_serror_handler",(ulong)uVar7);
  if (3 < pdVar10->dc_exception_nest) {
    uVar5 = mp4_get_cpu();
    printf_low("%d:%s:dc_exceion_nest=%d, Enter LOOP\n",(ulong)uVar5,"el3_serror_handler",
               (ulong)pdVar10->dc_exception_nest);
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  }
  pdVar10->dc_exception_nest = pdVar10->dc_exception_nest + 1;
  iVar8 = msi_has_internal_qaf();
  if ((iVar8 != 0) && (iVar8 = cp_param_check(0x100), iVar8 == 0)) {
    deci5s_mp4_panic_and_loop(local_94,uVar16 & 0xffffffff);
  }
  pdVar10->dc_exception_nest = pdVar10->dc_exception_nest - 1;
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:Enter LOOP\n",(ulong)uVar5,"el3_serror_handler");
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


