/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\boot_config.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00109fac
 * symbol: boot_config_io_io
 * prototype: int boot_config_io_io(IoController_BootConfiguration * dst, IoController_BootConfiguration * src)
 * body addresses: 248
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int boot_config_io_io(IoController_BootConfiguration *dst,IoController_BootConfiguration *src)

{
  void *pvVar1;
  void *pvVar2;
  u_int uVar3;
  
  uVar3 = mp4_get_cpu();
  printf_low("%d:%s:(dst %p, src %p)\n",(ulong)uVar3,"boot_config_io_io",dst,src);
  uVar3 = mp4_get_cpu();
  printf_low("%d:%s:->memcpy(%p, %p)\n",(ulong)uVar3,"boot_config_io_io",dst,src);
  memcpy(dst,src,0x38);
  uVar3 = mp4_get_cpu();
  pvVar1 = (void *)((long)&dst->field_0 + 0x38);
  pvVar2 = (void *)((long)&src->field_0 + 0x38);
  printf_low("%d:%s:->memcpy(%p, %p)\n",(ulong)uVar3,"boot_config_io_io",pvVar1,pvVar2);
  memcpy(pvVar1,pvVar2,8);
  uVar3 = mp4_get_cpu();
  pvVar1 = (void *)((long)&dst->field_0 + 0x50);
  pvVar2 = (void *)((long)&src->field_0 + 0x50);
  printf_low("%d:%s:->memcpy(%p, %p)\n",(ulong)uVar3,"boot_config_io_io",pvVar1,pvVar2);
  memcpy(pvVar1,pvVar2,0x20);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a0a4
 * symbol: boot_config_dram_entry
 * prototype: int boot_config_dram_entry(IoController_BootConfiguration * dst, uint64_t addr0, uint64_t newbase)
 * body addresses: 168
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int boot_config_dram_entry(IoController_BootConfiguration *dst,uint64_t addr0,uint64_t newbase)

{
  IoController_BootConfiguration *src;
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:(dst %p, addr0 %p, newbase 0x%016lx)\n",(ulong)uVar1,"boot_config_dram_entry",
             dst,addr0,newbase);
  src = (IoController_BootConfiguration *)((addr0 & 0x3ffffff) + newbase);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:offset 0x%016lx\n",(ulong)uVar1,"boot_config_dram_entry",addr0 & 0x3ffffff);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:src    0x%016lx\n",(ulong)uVar1,"boot_config_dram_entry",src);
  boot_config_io_io(dst,src);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a14c
 * symbol: bits_27_12
 * prototype: uint64_t bits_27_12(uint64_t v)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t bits_27_12(uint64_t v)

{
  u_int uVar1;
  
  if ((v & 0xfffffffff0000fff) != 0) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Warning: 0x%16lx\n",(ulong)uVar1,"bits_27_12",v);
  }
  return v >> 0xc & 0xffff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a194
 * symbol: bits_18_12
 * prototype: uint64_t bits_18_12(uint64_t v)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t bits_18_12(uint64_t v)

{
  u_int uVar1;
  
  if ((v & 0xfffffffffff80fff) != 0) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Warning: 0x%16lx\n",(ulong)uVar1,"bits_18_12",v);
  }
  return v >> 0xc & 0x7f;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a1dc
 * symbol: boot_config_mm_phase1
 * prototype: int boot_config_mm_phase1(void)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int boot_config_mm_phase1(void)

{
  u_int uVar1;
  MmController_BootConfiguration *pMVar2;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"boot_config_mm_phase1");
  pMVar2 = MmController_BootConfiguration_get();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:dst = %p\n",(ulong)uVar1,"boot_config_mm_phase1",pMVar2);
  (pMVar2->field_0).asU64[8] = 0x4820501c44264040;
  (pMVar2->field_0).asU64[9] = 0x389a00c118c04c00;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a260
 * symbol: boot_config_io_phase1
 * prototype: int boot_config_io_phase1(void)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int boot_config_io_phase1(void)

{
  u_int uVar1;
  IoController_BootConfiguration *pIVar2;
  
  pIVar2 = IoController_BootConfiguration_get();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:dst = %p\n",(ulong)uVar1,"boot_config_io_phase1",pIVar2);
  (pIVar2->field_0).asU64[8] = 0x4a23521e44264227;
  (pIVar2->field_0).asU64[9] = 0x3c99390118994e0c;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a2c8
 * symbol: boot_config_mm_phase2
 * prototype: int boot_config_mm_phase2(uint8_t * * out)
 * body addresses: 436
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int boot_config_mm_phase2(uint8_t **out)

{
  ulong uVar1;
  int iVar2;
  int iVar3;
  uint16_t uVar4;
  u_int uVar5;
  uint32_t uVar6;
  uint32_t uVar7;
  main_mp4_param_t *pmVar8;
  MmController_BootConfiguration *__dest;
  ulong uVar9;
  
  pmVar8 = msi_get_main_param();
  __dest = MmController_BootConfiguration_get();
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:Waiting SYNC MM driver by DVM_MAILBOX %d - %d\n",(ulong)uVar5,
             "boot_config_mm_phase2",0xe,0xf);
  do {
    uVar6 = dvm_read_mailbox(0xe);
    uVar7 = dvm_read_mailbox(0xf);
  } while ((uVar7 | uVar6) == 0);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:dvm_mailbox_l 0x%016lx\n",(ulong)uVar5,"boot_config_mm_phase2",(ulong)uVar6);
  uVar5 = mp4_get_cpu();
  printf_low("%d:%s:dvm_mailbox_h 0x%016lx\n",(ulong)uVar5,"boot_config_mm_phase2",(ulong)uVar7);
  memcpy(__dest,(void *)(ulong)(uint)((*(int *)&(pmVar8->mm4p_mm_param).mimi_iommu_addr + 0x48000000
                                      ) - *(int *)&(pmVar8->mm4p_mm_param).mimi_syshub_base),0x80);
  (__dest->field_0).asU64[7] = (__dest->field_0).asU64[7] & 0xfff00000ffffffff | 0x1800000000000;
  (__dest->field_0).asU64[0xe] = (__dest->field_0).asU64[0xe] & 0xffffffffffffe000 | 10;
  uVar4 = msi_get_vector_for_mm();
  uVar1 = (__dest->field_0).asU64[5];
  uVar9 = (__dest->field_0).asU64[4] & 0xf0000000000 |
          (__dest->field_0).asU64[4] & 0xffffffff | (ulong)(uVar4 & 0xff) << 0x20 |
          0x87f0000000000000;
  (__dest->field_0).asU64[4] = uVar9;
  (__dest->field_0).asU64[5] = uVar1 & 0xffffffffff7fffff;
  iVar2 = *(int *)&(pmVar8->mm4p_sdma0_mmio).mimi_iommu_addr;
  iVar3 = *(int *)&(pmVar8->mm4p_sdma0_mmio).mimi_syshub_base;
  (__dest->field_0).asU64[4] = uVar9;
  (__dest->field_0).asU64[5] =
       (ulong)((uint)((iVar2 + 0x28000000) - iVar3) >> 0xc) | uVar1 & 0xffffffffff700000;
  syshub_init_sdma();
  _DAT_03290038 = 0xfdec6005;
  _DAT_032900a0 = 0xfde6000c;
  _DAT_032900a8 = 0xfde60010;
  _DAT_032902a0 = pmVar8->mm4p_iommu_command_buffer_pa;
  _DAT_032902a8 = (undefined4)(pmVar8->mm4p_iommu_command_buffer_size >> 4);
  _DAT_032902b8 = (pmVar8->mm4p_sdma0_rb).mimi_pa;
  _DAT_032902c0 = (undefined4)(pmVar8->mm4p_sdma0_rb).mimi_physical_size;
  *out = (uint8_t *)__dest;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a47c
 * symbol: boot_config_io_phase2
 * prototype: int boot_config_io_phase2(uint8_t * * out)
 * body addresses: 1024
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int boot_config_io_phase2(uint8_t **out)

{
  ushort *puVar1;
  ulong base;
  int iVar2;
  u_int uVar3;
  uint32_t uVar4;
  uint32_t uVar5;
  IoController_BootConfiguration *dst;
  main_mp4_param_t *pmVar6;
  uint uVar7;
  uint uVar8;
  long lVar9;
  uint *puVar10;
  uint *puVar11;
  
  dst = IoController_BootConfiguration_get();
  pmVar6 = msi_get_main_param();
  _DAT_032902b8 = (pmVar6->mm4p_sdma0_rb).mimi_pa;
  _DAT_032902c0 = (undefined4)(pmVar6->mm4p_sdma0_rb).mimi_physical_size;
  iVar2 = cp_param_check(0x10000);
  uVar3 = mp4_get_cpu();
  if (iVar2 == 0) {
    printf_low("%d:%s:waiting DVM_MAILBOX_IO\n",(ulong)uVar3,"boot_config_io_phase2");
    do {
      uVar4 = dvm_read_mailbox(0x2e);
      uVar5 = dvm_read_mailbox(0x2f);
    } while ((uVar5 | uVar4) == 0);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:dvm_mailbox_l    0x%08x\n",(ulong)uVar3,"boot_config_io_phase2",(ulong)uVar4);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:dvm_mailbox_h    0x%08x\n",(ulong)uVar3,"boot_config_io_phase2",(ulong)uVar5);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:iommu_addr       0x%016lx\n",(ulong)uVar3,"boot_config_io_phase2",
               CONCAT44(uVar5,uVar4));
    base = (ulong)uVar4 & 0xfffffffffc000000 | (ulong)uVar5 << 0x20;
    syshub_init_for_io(base);
    lVar9 = CONCAT44(uVar5,uVar4) - base;
    puVar1 = (ushort *)(lVar9 + 0x54000000);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:syshub_base    0x%016lx\n",(ulong)uVar3,"boot_config_io_phase2",base);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:offset         0x%016lx\n",(ulong)uVar3,"boot_config_io_phase2",lVar9);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:src            0x%016lx\n",(ulong)uVar3,"boot_config_io_phase2",puVar1);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:(dsrt %p, src %p, newbase 0x%016lx)\n",(ulong)uVar3,"boot_config_header_init",
               dst,puVar1,0x54000000);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:version 0x%04x\n",(ulong)uVar3,"boot_config_header_init",(ulong)*puVar1);
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:num     0x%04x\n",(ulong)uVar3,"boot_config_header_init",
               (ulong)*(ushort *)(lVar9 + 0x54000002));
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:size    0x%08x\n",(ulong)uVar3,"boot_config_header_init",
               *(undefined8 *)(lVar9 + 0x54000008));
    puVar10 = (uint *)(lVar9 + 0x54000040);
    for (uVar7 = 0; uVar7 < *(ushort *)(lVar9 + 0x54000002); uVar7 = uVar7 + 1) {
      uVar8 = *puVar10 - 0x21;
      if (uVar8 < 0x31) {
        if ((1L << ((ulong)uVar8 & 0x3f) & 0x3f0001001fU) == 0) {
          if ((ulong)uVar8 != 0x30) goto LAB_0010a80c;
          uVar3 = mp4_get_cpu();
          printf_low("%d:%s:(dst %p, src %p, newbase 0x%016lx)\n",(ulong)uVar3,"boot_config_dram",
                     dst,puVar10,0x54000000);
          uVar3 = mp4_get_cpu();
          printf_low("%d:%s:type     0x%08x\n",(ulong)uVar3,"boot_config_dram",(ulong)*puVar10);
          uVar3 = mp4_get_cpu();
          printf_low("%d:%s:size     0x%08x\n",(ulong)uVar3,"boot_config_dram",(ulong)puVar10[1]);
          uVar3 = mp4_get_cpu();
          printf_low("%d:%s:num      0x%08x\n",(ulong)uVar3,"boot_config_dram",(ulong)puVar10[2]);
          puVar11 = puVar10 + 4;
          for (uVar8 = 0; uVar8 < puVar10[2]; uVar8 = uVar8 + 1) {
            uVar3 = mp4_get_cpu();
            printf_low("%d:%s:type     0x%08x\n",(ulong)uVar3,"boot_config_dram",(ulong)*puVar11);
            uVar3 = mp4_get_cpu();
            printf_low("%d:%s:size     0x%08x\n",(ulong)uVar3,"boot_config_dram",(ulong)puVar11[1]);
            uVar3 = mp4_get_cpu();
            printf_low("%d:%s:addr     0x%016lx\n",(ulong)uVar3,"boot_config_dram",
                       *(undefined8 *)(puVar11 + 2));
            uVar3 = mp4_get_cpu();
            printf_low("%d:%s:attr     0x%08x\n",(ulong)uVar3,"boot_config_dram",(ulong)puVar11[4]);
            uVar3 = mp4_get_cpu();
            printf_low("%d:%s:pasid    0x%04x\n",(ulong)uVar3,"boot_config_dram",
                       (ulong)*(ushort *)(puVar11 + 5));
            boot_config_dram_entry(dst,*(uint64_t *)(puVar11 + 2),0x54000000);
            puVar11 = puVar11 + 6;
          }
        }
      }
      else {
LAB_0010a80c:
        if (3 < *puVar10 - 0x11) {
          uVar3 = mp4_get_cpu();
          printf_low("%d:%s:Unknown type 0x%08x\n",(ulong)uVar3,"boot_config_header_init",
                     (ulong)*puVar10);
        }
      }
      puVar10 = (uint *)((long)puVar10 + (ulong)puVar10[1]);
    }
  }
  else {
    printf_low("%d:%s:SKIP!!! Waiting DVM_MAILBOX_IO\n",(ulong)uVar3,"boot_config_io_phase2");
  }
  *out = (uint8_t *)dst;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a87c
 * symbol: MmController_BootConfiguration_get
 * prototype: MmController_BootConfiguration * MmController_BootConfiguration_get(void)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

MmController_BootConfiguration * MmController_BootConfiguration_get(void)

{
  uint8_t *el0_va;
  MmController_BootConfiguration *pMVar1;
  
  pMVar1 = (MmController_BootConfiguration *)el0_va_to_el3_va((uint8_t *)&core1_boot_config);
  return pMVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a888
 * symbol: IoController_BootConfiguration_get
 * prototype: IoController_BootConfiguration * IoController_BootConfiguration_get(void)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

IoController_BootConfiguration * IoController_BootConfiguration_get(void)

{
  uint8_t *el0_va;
  IoController_BootConfiguration *pIVar1;
  
  pIVar1 = (IoController_BootConfiguration *)el0_va_to_el3_va((uint8_t *)&core0_boot_config);
  return pIVar1;
}


