/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\c2pmsg.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001148b4
 * symbol: c2pmsg_read
 * prototype: uint32_t c2pmsg_read(uint32_t no)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t c2pmsg_read(uint32_t no)

{
  uint32_t *puVar1;
  
  puVar1 = (uint32_t *)c2pmsg_addr64(no);
  return *puVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001148cc
 * symbol: c2pmsg_addr64
 * prototype: uint64_t c2pmsg_addr64(uint32_t ui)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t c2pmsg_addr64(uint32_t ui)

{
  u_int uVar1;
  uint uVar2;
  
  if (ui < 4) {
    uVar2 = ui * 4 + 0x3010500;
  }
  else if (ui < 0x14) {
    uVar2 = ui * 0x1000 + 0x30ec000;
  }
  else {
    uVar2 = 0x3010500;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Illegal C2MSG no %u\n",(ulong)uVar1,"c2pmsg_addr32",(ulong)ui);
  }
  return (ulong)uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114944
 * symbol: c2pmsg_write
 * prototype: void c2pmsg_write(uint32_t no, uint32_t data)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void c2pmsg_write(uint32_t no,uint32_t data)

{
  uint32_t *puVar1;
  
  puVar1 = (uint32_t *)c2pmsg_addr64(no);
  *puVar1 = data;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114968
 * symbol: c2pmsg_init
 * prototype: void c2pmsg_init(void)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void c2pmsg_init(void)

{
  undefined4 *puVar1;
  uint32_t ui;
  
  for (ui = 0; ui != 6; ui = ui + 1) {
    puVar1 = (undefined4 *)c2pmsg_addr64(ui);
    *puVar1 = 0;
  }
  return;
}


