/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\cp_param.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bc44
 * symbol: cp_param_check
 * prototype: int cp_param_check(uint32_t bit)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int cp_param_check(uint32_t bit)

{
  return g_param2 & bit;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bc54
 * symbol: cp_param_init
 * prototype: int cp_param_init(void)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int cp_param_init(void)

{
  uint uVar1;
  char *format;
  
  if (_DAT_d0000000 == 0x20) {
    if (_DAT_d0000004 == -0x701c92d0) {
      g_param2 = _DAT_d0000018;
      return 0;
    }
    uVar1 = mp4_get_cpu();
    format = "%d:%s:Invalid MAGIC1\n";
  }
  else {
    uVar1 = mp4_get_cpu();
    format = "%d:%s:size mismatch\n";
  }
  printf_low(format,(ulong)uVar1,"cp_param_init");
  return -1;
}


