/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\debug_status.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110120
 * symbol: mp4_debug_status_get
 * prototype: mp4_debug_status_t * mp4_debug_status_get(void)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

mp4_debug_status_t * mp4_debug_status_get(void)

{
  dev_context_t *pdVar1;
  
  pdVar1 = get_dev_context();
  return pdVar1->dc_debug_status;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110138
 * symbol: mp4_debug_status_get_reg
 * prototype: uint64_t mp4_debug_status_get_reg(u_int regid)
 * body addresses: 216
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t mp4_debug_status_get_reg(u_int regid)

{
  dev_context_t *pdVar1;
  mp4_debug_status_t *pmVar2;
  uint64_t *puVar3;
  
  pdVar1 = get_dev_context();
  pmVar2 = pdVar1->dc_debug_status;
  if (regid < 0x1f) {
    puVar3 = pmVar2->mds_gpr + regid;
  }
  else if (regid == 0xc01c) {
    puVar3 = &pmVar2->mds_far;
  }
  else if (regid == 0x21) {
    puVar3 = &pmVar2->mds_elr_mode;
  }
  else if (regid == 0x1001) {
    puVar3 = &pmVar2->mds_current_el;
  }
  else if (regid == 0x1002) {
    puVar3 = &pmVar2->mds_daif;
  }
  else if (regid == 0x100a) {
    puVar3 = &pmVar2->mds_nzcv;
  }
  else if (regid == 0xc010) {
    puVar3 = &pmVar2->mds_spsr;
  }
  else if (regid == 0xc01b) {
    puVar3 = &pmVar2->mds_esr;
  }
  else {
    if (regid != 0x1f) {
      return 0xffffffffffffffff;
    }
    puVar3 = &pmVar2->mds_sp;
  }
  return *puVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110210
 * symbol: mp4_debug_status_get_frame
 * prototype: int mp4_debug_status_get_frame(aarch64_frame_t * af)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mp4_debug_status_get_frame(aarch64_frame_t *af)

{
  dev_context_t *pdVar1;
  uint64_t uVar2;
  uint64_t uVar3;
  uint64_t uVar4;
  uint64_t uVar5;
  mp4_debug_status_t *pmVar6;
  
  pdVar1 = get_dev_context();
  pmVar6 = pdVar1->dc_debug_status;
  uVar2 = aarch64_read_ELR_EL1();
  uVar3 = aarch64_read_ELR_EL3();
  uVar4 = pmVar6->mds_gpr[0x1d];
  uVar5 = pmVar6->mds_sp;
  if (uVar2 != 0) {
    uVar3 = uVar2;
  }
  af->af_pc = uVar3;
  af->af_fp = uVar4;
  af->af_sp = uVar5;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110264
 * symbol: mp4_debug_status_show
 * prototype: void mp4_debug_status_show(void)
 * body addresses: 196
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mp4_debug_status_show(void)

{
  ulong uVar1;
  dev_context_t *pdVar2;
  ulong uVar3;
  mp4_debug_status_t *pmVar4;
  
  pdVar2 = get_dev_context();
  pmVar4 = pdVar2->dc_debug_status;
  printf_low("mds_vector  = 0x%016lx\n",pmVar4->mds_vector);
  uVar3 = 0;
  while (uVar3 != 0x1f) {
    if ((uVar3 & 3) == 0) {
      printf_low("mds_gpr[%2d] =",uVar3 & 0xffffffff);
    }
    printf_low(" 0x%016lx",pmVar4->mds_gpr[uVar3]);
    uVar1 = uVar3 + 1;
    if ((uVar3 == 0x1e) || (uVar3 = uVar1, (uVar1 & 3) == 0)) {
      printf_low("\n");
      uVar3 = uVar1;
    }
  }
  printf_low("mds_sp      = 0x%016lx\n",pmVar4->mds_sp);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110328
 * symbol: mp4_debug_status_putchar
 * prototype: int mp4_debug_status_putchar(int c)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mp4_debug_status_putchar(int c)

{
  uint64_t uVar1;
  dev_context_t *pdVar2;
  mp4_debug_status_t *pmVar3;
  
  pdVar2 = get_dev_context();
  pmVar3 = pdVar2->dc_debug_status;
  *(char *)((long)pmVar3->mds_gpr +
           pmVar3->mds_ttyp_buffer_last + pmVar3->mds_ttyp_buffer_offset + -0x10) = (char)c;
  uVar1 = pmVar3->mds_ttyp_buffer_last + 1;
  pmVar3->mds_ttyp_buffer_last = uVar1;
  if (uVar1 == pmVar3->mds_ttyp_buffer_size) {
    pmVar3->mds_ttyp_buffer_last = 0;
    pmVar3->mds_ttyp_buffer_count = pmVar3->mds_ttyp_buffer_count + 1;
  }
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110388
 * symbol: mp4_debug_status_init
 * prototype: void mp4_debug_status_init(void)
 * body addresses: 392
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mp4_debug_status_init(void)

{
  mp4_debug_status_t *pmVar1;
  undefined8 uVar2;
  byte bVar3;
  dev_context_t *pdVar4;
  mp4_debug_status_t *pmVar5;
  long lVar6;
  
  pdVar4 = get_dev_context();
  bVar3 = aarch64_read_MPIDR_EL1();
  pmVar1 = (mp4_debug_status_t *)0xec100000;
  pmVar5 = (mp4_debug_status_t *)&DAT_ec000000;
  if (bVar3 != 0) {
    pmVar5 = pmVar1;
  }
  pdVar4->dc_debug_status = pmVar5;
  pdVar4 = get_dev_context();
  pmVar5 = pdVar4->dc_debug_status;
  pmVar5->mds_magic1 = 0xcbb3d18a1aa5daef;
  pmVar5->mds_vector = 0;
  for (lVar6 = 0; lVar6 != 0xf8; lVar6 = lVar6 + 8) {
    *(undefined8 *)((long)pmVar5->mds_gpr + lVar6) = 0;
  }
  pmVar5->mds_spsr = 0;
  pmVar5->mds_esr = 0;
  pmVar5->mds_far = 0;
  pmVar5->mds_tpidrro_el0 = 0;
  pmVar5->mds_1st_vector = 0;
  pmVar5->mds_1st_el = 0;
  pmVar5->mds_1st_spsr = 0;
  pmVar5->mds_1st_esr = 0;
  pmVar5->mds_1st_elr = 0;
  pmVar5->mds_self_size = 0x238;
  pmVar5->mds_daif = (ulong)bVar3;
  pmVar5->mds_218 = 0;
  pmVar5->mds_magic2 = 0x1aa5daef675a1801;
  pmVar5->mds_ttyp_buffer_offset = 0x1000;
  pmVar5->mds_ttyp_buffer_last = 0;
  pmVar5->mds_mbox_t2c_count = 0;
  pmVar5->mds_mbox_t2c = 0x100000000;
  pmVar5->mds_ttyp_buffer_size = 0xf0000;
  pmVar5->mds_ttyp_buffer_count = 0;
  pmVar5->mds_phase = 0;
  pmVar5->mds_version = 0x400000002;
  if (bVar3 != 0) {
    pmVar1 = (mp4_debug_status_t *)&DAT_ec000000;
  }
  pmVar1->mds_ttyp_buffer_last = 0;
  pmVar1->mds_ttyp_buffer_count = 0;
  pmVar5->mds_magic3 = 0x8501dda72c7b400e;
  putchar_low(0x4d);
  putchar_low(0x50);
  putchar_low(0x34);
  putchar_low(0x21);
  putchar_low(10);
  mp4_debug_status_putchar(0x4d);
  mp4_debug_status_putchar(0x50);
  mp4_debug_status_putchar(0x34);
  mp4_debug_status_putchar(0xd);
  mp4_debug_status_putchar(10);
  printf_low("Hello MP4/A53!\n");
  printf_cp("Hello MP4/A53!\n");
  uVar2 = vbar_el3;
  printf_low("VBAR_EL3 0x%016lx\n",uVar2);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110510
 * symbol: mp4_debug_status_exit
 * prototype: void mp4_debug_status_exit(void)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mp4_debug_status_exit(void)

{
  dev_context_t *pdVar1;
  
  pdVar1 = get_dev_context();
  pdVar1->dc_debug_status->mds_mbox_t2c = 0xe00000000;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110530
 * symbol: mp4_debug_status_c_set
 * prototype: void mp4_debug_status_c_set(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mp4_debug_status_c_set(void)

{
  return;
}


