/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\deci_shm_mp4.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ed78
 * symbol: deci_shm_mp4_common
 * prototype: deci_shm_common_t * deci_shm_mp4_common(void)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_common_t * deci_shm_mp4_common(void)

{
  uint32_t uVar1;
  
  if (g_deci_shm_mp4 != (deci_shm_mp4_t *)0x0) {
    return (deci_shm_common_t *)g_deci_shm_mp4_data.dsm4_shm_common;
  }
  uVar1 = deci5s_get_cpu();
  printf_low("%d:%s:There is no g_deci_shm_mp4.\n",(ulong)uVar1,"deci_shm_mp4_common");
  return (deci_shm_common_t *)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010edc4
 * symbol: deci_shm_mp4_start
 * prototype: int deci_shm_mp4_start(uint32_t core)
 * body addresses: 304
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int deci_shm_mp4_start(uint32_t core)

{
  uint8_t *dsc;
  int iVar1;
  uint uVar2;
  u_int uVar3;
  deci_shm_node_t *pdVar4;
  char *file;
  
  if (core == 0) {
    g_deci_shm_mp4_data.dsm4_firm = &DAT_d0000000;
    g_deci_shm_mp4_data.dsm4_shm_common = (uint8_t *)0xe0000000;
    if ((_DAT_d0000004 == -0x701c92d0) && (_DAT_d000001c == -0x3074bd3d)) {
      g_deci_shm_mp4_data._16_8_ = _DAT_d0000010;
      g_deci_shm_mp4_data.dsm4_cp_param2 = _DAT_d0000018;
    }
    else {
      uVar3 = mp4_get_cpu();
      printf_low("%d:%s:NOT found firmware magic!!!",(ulong)uVar3,"deci_shm_mp4_start");
    }
    dsc = g_deci_shm_mp4_data.dsm4_shm_common;
    uVar2 = deci_shm_common_check((deci_shm_common_t *)g_deci_shm_mp4_data.dsm4_shm_common);
    if ((int)uVar2 < 1) {
      uVar3 = mp4_get_cpu();
      printf_low("%d:%s:deci_shm_common_check(%p) failed %d",(ulong)uVar3,"deci_shm_mp4_start",dsc,
                 (ulong)uVar2);
      iVar1 = -1;
    }
    else {
      pdVar4 = deci_shm_common_get_node_mp4((deci_shm_common_t *)dsc);
      file = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm_mp4.c"
                            );
      deci5s_assert(file,"deci_shm_mp4_start",0x9a,(uint)(pdVar4->dsn_magic1 == 0x8e7e62d6),
                    "node->dsn_magic1 == DECI_SHM_NODE_MAGIC1_MP4");
      iVar1 = 0;
      g_deci_shm_mp4 = &g_deci_shm_mp4_data;
    }
  }
  else {
    iVar1 = 0;
  }
  return iVar1;
}


