/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\deci_shm.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e028
 * symbol: deci_shm_mbox_get_op0
 * prototype: uint16_t deci_shm_mbox_get_op0(uint32_t mbox)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t deci_shm_mbox_get_op0(uint32_t mbox)

{
  return (uint16_t)(mbox >> 0x10);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e030
 * symbol: deci_shm_mbox_get_op1
 * prototype: uint16_t deci_shm_mbox_get_op1(uint32_t mbox)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t deci_shm_mbox_get_op1(uint32_t mbox)

{
  return (uint16_t)mbox;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e034
 * symbol: deci_shm_make_mbox0
 * prototype: uint32_t deci_shm_make_mbox0(uint16_t type, uint32_t bid)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci_shm_make_mbox0(uint16_t type,uint32_t bid)

{
  uint16_t uVar1;
  
  uVar1 = deci_shm_make_mbox_16b(type,bid);
  return (uint)uVar1 << 0x10 | 0xffff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e054
 * symbol: deci_shm_make_mbox_16b
 * prototype: uint16_t deci_shm_make_mbox_16b(uint16_t type, uint32_t bid)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t deci_shm_make_mbox_16b(uint16_t type,uint32_t bid)

{
  char *file;
  
  if (0xfff < (bid & 0xffff)) {
    printf_low("%s:req=0x%04x, id=0x%04x\n","deci_shm_make_mbox_16b",(ulong)type);
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(file,"deci_shm_make_mbox_16b",0x1b6,0,"0");
  }
  return (ushort)bid & 0xfff | type;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e0d0
 * symbol: deci_shm_make_mbox01
 * prototype: uint32_t deci_shm_make_mbox01(uint16_t type0, uint32_t bid0, uint16_t type1, uint32_t bid1)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci_shm_make_mbox01(uint16_t type0,uint32_t bid0,uint16_t type1,uint32_t bid1)

{
  uint16_t uVar1;
  uint16_t uVar2;
  
  uVar1 = deci_shm_make_mbox_16b(type0,bid0);
  uVar2 = deci_shm_make_mbox_16b(type1,bid1);
  return CONCAT22(uVar1,uVar2);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e110
 * symbol: deci_shm_common_get_ptr
 * prototype: uint8_t * deci_shm_common_get_ptr(deci_shm_common_t * dsc, uint32_t off)
 * body addresses: 176
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint8_t * deci_shm_common_get_ptr(deci_shm_common_t *dsc,uint32_t off)

{
  int c;
  char *pcVar1;
  
  pcVar1 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  c = deci_shm_common_check(dsc);
  deci5s_assert(pcVar1,"deci_shm_common_get_ptr",0x3a0,c,"deci_shm_common_check(dsc)");
  if (0x7c < off >> 0x15) {
    printf_low("%s:Illegal offset 0x%08x\n","deci_shm_common_get_ptr",(ulong)off);
    pcVar1 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(pcVar1,"deci_shm_common_get_ptr",0x3a3,0,"0");
  }
  return (uint8_t *)((long)&dsc->dsc_self_size + (ulong)off);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e1c0
 * symbol: deci_shm_common_check
 * prototype: int deci_shm_common_check(deci_shm_common_t * dsc)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_shm_common_check(deci_shm_common_t *dsc)

{
  int iVar1;
  
  iVar1 = deci_shm_common_get_version(dsc);
  return (int)(0 < iVar1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e1dc
 * symbol: deci_shm_common_v2_get_node_cp
 * prototype: deci_shm_node_t * deci_shm_common_v2_get_node_cp(deci_shm_common_v2_t * dsc2)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_v2_get_node_cp(deci_shm_common_v2_t *dsc2)

{
  deci_shm_common_target_t *pdVar1;
  deci_shm_node_t *pdVar2;
  char *file;
  
  pdVar1 = deci_shm_common_v2_find_target(dsc2,0xf470b785);
  if (pdVar1 == (deci_shm_common_target_t *)0x0) {
    printf_low("%s:deci_shm_common_v2_find_target() failed\n","deci_shm_common_v2_get_node_cp");
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(file,"deci_shm_common_v2_get_node_cp",0x64a,0,"0");
    pdVar2 = (deci_shm_node_t *)0x0;
  }
  else {
    pdVar2 = (deci_shm_node_t *)
             deci_shm_common_get_ptr((deci_shm_common_t *)dsc2,pdVar1->dsct_node_offset);
  }
  return pdVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e258
 * symbol: deci_shm_common_v2_find_target
 * prototype: deci_shm_common_target_t * deci_shm_common_v2_find_target(deci_shm_common_v2_t * dsc2, uint32_t magic)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_common_target_t * deci_shm_common_v2_find_target(deci_shm_common_v2_t *dsc2,uint32_t magic)

{
  deci_shm_common_target_t *pdVar1;
  char *file;
  uint uVar2;
  
  uVar2 = 0;
  pdVar1 = (deci_shm_common_target_t *)(&dsc2[1].dsc2_self_size + dsc2->dsc2_n_buf_size);
  while( true ) {
    if (dsc2->dsc2_n_node <= uVar2) {
      printf_low("%s:Cannot find magic = 0x%08x\n","deci_shm_common_v2_find_target",(ulong)magic);
      file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
      deci5s_assert(file,"deci_shm_common_v2_find_target",0x591,0,"0");
      return (deci_shm_common_target_t *)0x0;
    }
    if (pdVar1->dsct_magic == magic) break;
    pdVar1 = pdVar1 + 1;
    uVar2 = uVar2 + 1;
  }
  return pdVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e2e8
 * symbol: deci_shm_common_v2_get_node_main
 * prototype: deci_shm_node_t * deci_shm_common_v2_get_node_main(deci_shm_common_v2_t * dsc2)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_v2_get_node_main(deci_shm_common_v2_t *dsc2)

{
  deci_shm_common_target_t *pdVar1;
  deci_shm_node_t *pdVar2;
  char *file;
  
  pdVar1 = deci_shm_common_v2_find_target(dsc2,0x812c4d3d);
  if (pdVar1 == (deci_shm_common_target_t *)0x0) {
    printf_low("%s:deci_shm_common_v2_find_target() failed\n","deci_shm_common_v2_get_node_main");
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(file,"deci_shm_common_v2_get_node_main",0x658,0,"0");
    pdVar2 = (deci_shm_node_t *)0x0;
  }
  else {
    pdVar2 = (deci_shm_node_t *)
             deci_shm_common_get_ptr((deci_shm_common_t *)dsc2,pdVar1->dsct_node_offset);
  }
  return pdVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e364
 * symbol: deci_shm_common_v2_get_node_sycorax
 * prototype: deci_shm_node_t * deci_shm_common_v2_get_node_sycorax(deci_shm_common_v2_t * dsc2)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_v2_get_node_sycorax(deci_shm_common_v2_t *dsc2)

{
  deci_shm_common_target_t *pdVar1;
  deci_shm_node_t *pdVar2;
  char *file;
  
  pdVar1 = deci_shm_common_v2_find_target(dsc2,0xfbdf45e4);
  if (pdVar1 == (deci_shm_common_target_t *)0x0) {
    printf_low("%s:deci_shm_common_v2_find_target() failed\n","deci_shm_common_v2_get_node_sycorax")
    ;
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(file,"deci_shm_common_v2_get_node_sycorax",0x666,0,"0");
    pdVar2 = (deci_shm_node_t *)0x0;
  }
  else {
    pdVar2 = (deci_shm_node_t *)
             deci_shm_common_get_ptr((deci_shm_common_t *)dsc2,pdVar1->dsct_node_offset);
  }
  return pdVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e3e0
 * symbol: deci_shm_common_get_version
 * prototype: int deci_shm_common_get_version(deci_shm_common_t * dsc)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_shm_common_get_version(deci_shm_common_t *dsc)

{
  if (dsc->dsc_magic1 != 0x63267916) {
    printf_low("%s:%p: dsc_magic1 = 0x%08x != 0x%08x\n","deci_shm_common_get_version",dsc);
    return 0;
  }
  if (dsc[6].dsc_offset == 0x58d64767) {
    return 1;
  }
  return (uint)(dsc[3].dsc_magic1 == 0x158691ae) << 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e45c
 * symbol: deci_shm_common_get_offset
 * prototype: uint32_t deci_shm_common_get_offset(deci_shm_common_t * dsc, uint8_t * ptr)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci_shm_common_get_offset(deci_shm_common_t *dsc,uint8_t *ptr)

{
  int c;
  char *file;
  
  file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  c = deci_shm_common_check(dsc);
  deci5s_assert(file,"deci_shm_common_get_offset",0x708,c,"deci_shm_common_check(dsc)");
  return (int)ptr - (int)dsc;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e4c0
 * symbol: deci_shm_common_get_node_cp
 * prototype: deci_shm_node_t * deci_shm_common_get_node_cp(deci_shm_common_t * dsc)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_get_node_cp(deci_shm_common_t *dsc)

{
  deci_shm_node_t *pdVar1;
  
  pdVar1 = deci_shm_common_get_node(dsc,0xf470b785);
  return pdVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e4cc
 * symbol: deci_shm_common_get_node
 * prototype: deci_shm_node_t * deci_shm_common_get_node(deci_shm_common_t * dsc, uint32_t magic)
 * body addresses: 452
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_get_node(deci_shm_common_t *dsc,uint32_t magic)

{
  int iVar1;
  char *pcVar2;
  deci_shm_common_target_t *pdVar3;
  deci_shm_node_t *pdVar4;
  uint32_t off;
  
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar1 = deci_shm_common_check(dsc);
  deci5s_assert(pcVar2,"deci_shm_common_get_node",0x7c9,iVar1,"deci_shm_common_check(dsc)");
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar1 = deci_shm_common_check(dsc);
  deci5s_assert(pcVar2,"deci_shm_common_get_node_offset",0x7af,iVar1,"deci_shm_common_check(dsc)");
  iVar1 = deci_shm_common_get_version(dsc);
  if (iVar1 == 1) {
    if (magic == 0x812c4d3d) {
      off = dsc[4].dsc_offset;
    }
    else {
      if ((magic != 0x87661e49 && magic != 0x8fec3303) && magic != 0x43fe7688) {
        if (magic == 0xfbdf45e4) {
          off = dsc[4].dsc_magic1;
          goto LAB_0010e678;
        }
        if (magic == 0xf470b785) {
          off = dsc[4].dsc_self_size;
          goto LAB_0010e678;
        }
        printf_low("%s:Unknown magic 0x%08x\n","deci_shm_common_v1_get_node_offset",(ulong)magic);
        pcVar2 = deci5s_basename(
                                "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c"
                                );
        deci5s_assert(pcVar2,"deci_shm_common_v1_get_node_offset",0x489,0,"0");
      }
      off = 0;
    }
  }
  else {
    pdVar3 = deci_shm_common_v2_find_target((deci_shm_common_v2_t *)dsc,magic);
    if (pdVar3 == (deci_shm_common_target_t *)0x0) {
      printf_low("%s:deci_shm_common_v2_find_target() failed\n","deci_shm_common_v2_get_node_offset"
                );
      pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c"
                              );
      deci5s_assert(pcVar2,"deci_shm_common_v2_get_node_offset",0x610,0,"0");
      off = 0xffffffff;
    }
    else {
      off = pdVar3->dsct_node_offset;
    }
  }
LAB_0010e678:
  pdVar4 = (deci_shm_node_t *)deci_shm_common_get_ptr(dsc,off);
  return pdVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e690
 * symbol: deci_shm_common_get_node_main
 * prototype: deci_shm_node_t * deci_shm_common_get_node_main(deci_shm_common_t * dsc)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_get_node_main(deci_shm_common_t *dsc)

{
  int iVar1;
  char *file;
  deci_shm_node_t *pdVar2;
  
  file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar1 = deci_shm_common_check(dsc);
  deci5s_assert(file,"deci_shm_common_get_node_main",0x7d9,iVar1,"deci_shm_common_check(dsc)");
  iVar1 = deci_shm_common_get_version(dsc);
  if (iVar1 == 1) {
    pdVar2 = (deci_shm_node_t *)deci_shm_common_get_ptr(dsc,dsc[4].dsc_offset);
    return pdVar2;
  }
  pdVar2 = deci_shm_common_v2_get_node_main((deci_shm_common_v2_t *)dsc);
  return pdVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e70c
 * symbol: deci_shm_common_get_node_mp3
 * prototype: deci_shm_node_t * deci_shm_common_get_node_mp3(deci_shm_common_t * dsc)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_get_node_mp3(deci_shm_common_t *dsc)

{
  deci_shm_node_t *pdVar1;
  
  pdVar1 = deci_shm_common_get_node(dsc,0x8fec3303);
  return pdVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e718
 * symbol: deci_shm_common_get_node_mp4
 * prototype: deci_shm_node_t * deci_shm_common_get_node_mp4(deci_shm_common_t * dsc)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_shm_common_get_node_mp4(deci_shm_common_t *dsc)

{
  deci_shm_node_t *pdVar1;
  
  pdVar1 = deci_shm_common_get_node(dsc,0x43fe7688);
  return pdVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e724
 * symbol: deci_shm_common_get_ch_fix_cp_to_mp4
 * prototype: deci_shm_ch_node_fix_t * deci_shm_common_get_ch_fix_cp_to_mp4(deci_shm_common_t * dsc, uint ui)
 * body addresses: 400
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_fix_t * deci_shm_common_get_ch_fix_cp_to_mp4(deci_shm_common_t *dsc,uint ui)

{
  int iVar1;
  char *pcVar2;
  char *file;
  deci_shm_common_target_t *pdVar3;
  deci_shm_node_t *pdVar4;
  uint8_t *puVar5;
  u_int line;
  ulong uVar6;
  
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar1 = deci_shm_common_check(dsc);
  deci5s_assert(pcVar2,"deci_shm_common_get_index_ch_fix_mp4",0x730,iVar1,
                "deci_shm_common_check(dsc)");
  iVar1 = deci_shm_common_get_version(dsc);
  if (iVar1 == 1) {
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    pcVar2 = "deci_shm_common_get_index_ch_fix_mp4";
    line = 0x732;
  }
  else {
    pdVar3 = deci_shm_common_v2_find_target((deci_shm_common_v2_t *)dsc,0x43fe7688);
    if (pdVar3 != (deci_shm_common_target_t *)0x0) {
      uVar6 = (ulong)pdVar3->dsct_base_ch_fix;
      goto LAB_0010e808;
    }
    pcVar2 = "deci_shm_common_v2_get_base_ch_fix";
    printf_low("%s:deci_shm_common_v2_find_target() failed\n","deci_shm_common_v2_get_base_ch_fix");
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    line = 0x5be;
  }
  deci5s_assert(file,pcVar2,line,0,"0");
  uVar6 = 0;
LAB_0010e808:
  pdVar4 = deci_shm_common_get_node_cp(dsc);
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar2,"deci_shm_common_get_ch_fix_cp_to_target",0x96a,
                (uint)(pdVar4->dsn_magic1 == 0xc8f7e343),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_CP");
  puVar5 = deci_shm_common_get_ptr(dsc,pdVar4->dsn_ch_offset);
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar2,"deci_shm_common_get_ch_fix_cp_to_mp4",0x98e,
                (uint)(((deci_shm_ch_node_fix_t *)(puVar5 + (ulong)ui * 0x60 + uVar6 * 0x60))->
                       dscnf_magic == 0xcb9b4aba),
                "dscnf->dscnf_magic == DECI_SHM_CH_NODE_FIX_MAGIC_CP_TO_MP4");
  return (deci_shm_ch_node_fix_t *)(puVar5 + (ulong)ui * 0x60 + uVar6 * 0x60);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e8b4
 * symbol: deci_shm_common_get_ch_fix_mp4_to_cp
 * prototype: deci_shm_ch_node_fix_t * deci_shm_common_get_ch_fix_mp4_to_cp(deci_shm_common_t * dsc, uint ui)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_fix_t * deci_shm_common_get_ch_fix_mp4_to_cp(deci_shm_common_t *dsc,uint ui)

{
  deci_shm_node_t *pdVar1;
  char *file;
  uint8_t *puVar2;
  
  pdVar1 = deci_shm_common_get_node_mp4(dsc);
  file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(file,"deci_shm_common_get_ch_fix_mp4_to_cp",0x9cd,
                (uint)(pdVar1->dsn_magic1 == 0x8e7e62d6),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_MP4");
  puVar2 = deci_shm_common_get_ptr(dsc,pdVar1->dsn_ch_offset);
  return (deci_shm_ch_node_fix_t *)(puVar2 + (ulong)ui * 0x60);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e930
 * symbol: deci_shm_common_get_ch_ring_cp_to_mp4
 * prototype: deci_shm_ch_node_ring_t * deci_shm_common_get_ch_ring_cp_to_mp4(deci_shm_common_t * dsc, uint ui)
 * body addresses: 428
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_ring_t * deci_shm_common_get_ch_ring_cp_to_mp4(deci_shm_common_t *dsc,uint ui)

{
  uint uVar1;
  int iVar2;
  char *pcVar3;
  deci_shm_common_target_t *pdVar4;
  deci_shm_node_t *pdVar5;
  uint8_t *puVar6;
  uint32_t uVar7;
  ulong uVar8;
  
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar2 = deci_shm_common_check(dsc);
  deci5s_assert(pcVar3,"deci_shm_common_get_index_ch_ring_mp4",0x77d,iVar2,
                "deci_shm_common_check(dsc)");
  iVar2 = deci_shm_common_get_version(dsc);
  if (iVar2 == 1) {
    pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(pcVar3,"deci_shm_common_get_index_ch_ring_mp4",0x77f,0,"0");
    uVar8 = 0;
  }
  else {
    pdVar4 = deci_shm_common_v2_find_target((deci_shm_common_v2_t *)dsc,0x43fe7688);
    if (pdVar4 == (deci_shm_common_target_t *)0x0) {
      printf_low("%s:deci_shm_common_v2_find_target() failed\n",
                 "deci_shm_common_v2_get_base_ch_ring");
      pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c"
                              );
      deci5s_assert(pcVar3,"deci_shm_common_v2_get_base_ch_ring",0x5cd,0,"0");
      uVar7 = 0;
    }
    else {
      uVar7 = pdVar4->dsct_base_ch_ring;
    }
    uVar8 = (ulong)(uVar7 - dsc[1].dsc_magic1);
  }
  pdVar5 = deci_shm_common_get_node_cp(dsc);
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_cp_to_target",0x9ec,
                (uint)(pdVar5->dsn_magic1 == 0xc8f7e343),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_CP");
  puVar6 = deci_shm_common_get_ptr(dsc,pdVar5->dsn_ch_offset);
  uVar1 = pdVar5->dsn_n_ch_fix;
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_cp_to_mp4",0xa16,
                (uint)(((deci_shm_ch_node_ring_t *)
                       (puVar6 + (ulong)ui * 0x60 + uVar8 * 0x60 + (ulong)uVar1 * 0x60))->
                       dscnr_magic == 0x8e154c2a),
                "dscnr->dscnr_magic == DECI_SHM_CH_NODE_RING_MAGIC_CP_TO_MP4");
  return (deci_shm_ch_node_ring_t *)(puVar6 + (ulong)ui * 0x60 + uVar8 * 0x60 + (ulong)uVar1 * 0x60)
  ;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010eadc
 * symbol: deci_shm_common_get_ch_ring_mp4_to_cp
 * prototype: deci_shm_ch_node_ring_t * deci_shm_common_get_ch_ring_mp4_to_cp(deci_shm_common_t * dsc, uint ui)
 * body addresses: 196
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_ring_t * deci_shm_common_get_ch_ring_mp4_to_cp(deci_shm_common_t *dsc,uint ui)

{
  uint uVar1;
  int c;
  deci_shm_node_t *pdVar2;
  char *pcVar3;
  uint8_t *puVar4;
  
  pdVar2 = deci_shm_common_get_node_mp4(dsc);
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_mp4_to_cp",0xa59,
                (uint)(pdVar2->dsn_magic1 == 0x8e7e62d6),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_MP4");
  puVar4 = deci_shm_common_get_ptr(dsc,pdVar2->dsn_ch_offset);
  uVar1 = pdVar2->dsn_n_ch_fix;
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  c = deci_shm_ch_node_ring_check((deci_shm_ch_node_ring_t *)(puVar4 + (ulong)uVar1 * 0x60));
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_target_to_cp",0xa39,c,
                "deci_shm_ch_node_ring_check(dscnr)");
  return (deci_shm_ch_node_ring_t *)(puVar4 + (ulong)uVar1 * 0x60) + ui;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010eba0
 * symbol: deci_shm_buf_check
 * prototype: int deci_shm_buf_check(deci_shm_buf_t * buf)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_shm_buf_check(deci_shm_buf_t *buf)

{
  if (buf->dsb_self_size == 0x20) {
    return (int)(buf->dsb_magic == 0x15b50c6);
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ebcc
 * symbol: deci_shm_node_check_with_magic
 * prototype: int deci_shm_node_check_with_magic(deci_shm_node_t * dsn, uint32_t magic)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_shm_node_check_with_magic(deci_shm_node_t *dsn,uint32_t magic)

{
  uint32_t uVar1;
  
  if (dsn->dsn_self_size == 0x20) {
    if (dsn->dsn_magic1 == magic) {
      return 1;
    }
    uVar1 = deci5s_get_cpu();
    printf_low("%d:%s:Illegal magic 0x%08x != 0x%08x [expect]\n",(ulong)uVar1,
               "deci_shm_node_check_with_magic",(ulong)dsn->dsn_magic1,(ulong)magic);
  }
  else {
    uVar1 = deci5s_get_cpu();
    printf_low("%d:%s:Illegal self_size 0x%08x\n",(ulong)uVar1,"deci_shm_node_check_with_magic",
               (ulong)dsn->dsn_self_size);
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ec58
 * symbol: deci_shm_ch_node_fix_check_with_magic
 * prototype: int deci_shm_ch_node_fix_check_with_magic(deci_shm_ch_node_fix_t * dscnf, uint32_t magic)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_shm_ch_node_fix_check_with_magic(deci_shm_ch_node_fix_t *dscnf,uint32_t magic)

{
  if (dscnf->dscnf_self_size != 0x60) {
    return 0;
  }
  if (dscnf->dscnf_magic == magic) {
    return 1;
  }
  printf_low("%s:Unknown magic 0x%08x != 0x%08x [expect]\n","deci_shm_ch_node_fix_check_with_magic",
             (ulong)dscnf->dscnf_magic,(ulong)magic);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ecb4
 * symbol: deci_shm_ch_node_ring_check
 * prototype: int deci_shm_ch_node_ring_check(deci_shm_ch_node_ring_t * dscnr)
 * body addresses: 196
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_shm_ch_node_ring_check(deci_shm_ch_node_ring_t *dscnr)

{
  uint32_t uVar1;
  
  if (dscnr->dscnr_self_size != 0x60) {
    return 0;
  }
  uVar1 = dscnr->dscnr_magic;
  if (((((((((uVar1 == 0x89aabe53 || uVar1 == 0x8e154c2a) || uVar1 == 0xa97c5f30) ||
           uVar1 == 0xb7baa60c) || uVar1 == 0xdde744fe) || uVar1 == 0x2029fbd) ||
        uVar1 == 0x129c4ef8) || uVar1 == 0x530e0397) || uVar1 == 0x610a3c53) || uVar1 == 0x6feb0d6a)
  {
    return 1;
  }
  printf_low("%s:Unknown magic 0x%08x\n","deci_shm_ch_node_ring_check");
  return 0;
}


