/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\deci_target_mp4.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f018
 * symbol: deci_target_ch_fix_send_request
 * prototype: int deci_target_ch_fix_send_request(deci_target_ch_fix_t * dtcf, uint32_t psize, uint32_t hint)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_ch_fix_send_request(deci_target_ch_fix_t *dtcf,uint32_t psize,uint32_t hint)

{
  uint32_t mbox;
  uint32_t *puVar1;
  
  dtcf->dtcf_write_count = dtcf->dtcf_write_count + 1;
  dtcf->dtcf_total_write_size = dtcf->dtcf_total_write_size + (ulong)psize;
  puVar1 = dtcf->dtcf_t2c_cmd_data_size_ptr;
  *dtcf->dtcf_t2c_cmd_status_ptr = *dtcf->dtcf_t2c_cmd_status_ptr & 0xfff00000 | 0x20;
  *puVar1 = psize;
  mbox = deci_shm_make_mbox0(0x2000,dtcf->dtcf_t2c_cmd_bid);
  deci_target_ch_fix_write_mbox(dtcf,mbox,hint);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f08c
 * symbol: deci_target_ch_fix_write_mbox
 * prototype: int deci_target_ch_fix_write_mbox(deci_target_ch_fix_t * dtcf, uint32_t mbox, uint32_t hint)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int deci_target_ch_fix_write_mbox(deci_target_ch_fix_t *dtcf,uint32_t mbox,uint32_t hint)

{
  uint32_t uVar1;
  int iVar2;
  deci_target_md_t *pdVar3;
  
  uVar1 = dtcf->dtcf_sig_bit_t2c;
  pdVar3 = deci_target_get_md();
  (*pdVar3->dtmd_wait_clear_target_to_cp)(dtcf->dtcf_sig_no_t2c,dtcf->dtcf_sig_dst_t2c,uVar1);
  pdVar3 = deci_target_get_md();
  (*pdVar3->dtmd_int_to_cp)
            (dtcf->dtcf_sig_no_t2c,dtcf->dtcf_sig_dst_t2c,uVar1,dtcf->dtcf_mbox_t2c,mbox,hint);
  pdVar3 = deci_target_get_md();
                    /* WARNING: Could not recover jumptable at 0x0010f108. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar2 = (*pdVar3->dtmd_wait_clear_target_to_cp)
                    (dtcf->dtcf_sig_no_t2c,dtcf->dtcf_sig_dst_t2c,uVar1);
  return iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f10c
 * symbol: deci_target_ch_fix_send_reply
 * prototype: int deci_target_ch_fix_send_reply(deci_target_ch_fix_t * dtcf, deci5s_context_t * dc)
 * body addresses: 172
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_ch_fix_send_reply(deci_target_ch_fix_t *dtcf,deci5s_context_t *dc)

{
  uint uVar1;
  uint32_t mbox;
  uint32_t *puVar2;
  
  *dtcf->dtcf_c2t_cmd_status_ptr = *dtcf->dtcf_c2t_cmd_status_ptr & 0xfff00000 | 0x80000;
  if ((*(byte *)&dc->dc_result & 1) == 0) {
    mbox = deci_shm_make_mbox0(0x1000,dtcf->dtcf_c2t_cmd_bid);
  }
  else {
    puVar2 = dtcf->dtcf_c2t_res_data_size_ptr;
    uVar1 = *dtcf->dtcf_c2t_res_status_ptr;
    dtcf->dtcf_write_count = dtcf->dtcf_write_count + 1;
    dtcf->dtcf_total_write_size = dtcf->dtcf_total_write_size + (ulong)dc->dc_res_data_size;
    *dtcf->dtcf_c2t_res_status_ptr = uVar1 & 0xfff00000 | 0x20;
    *puVar2 = dc->dc_res_data_size;
    mbox = deci_shm_make_mbox01(0x1000,dtcf->dtcf_c2t_cmd_bid,0x4000,dtcf->dtcf_c2t_res_bid);
  }
  deci_target_ch_fix_write_mbox(dtcf,mbox,0);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f1b8
 * symbol: deci_target_ch_fix_handle_irq_poll
 * prototype: int deci_target_ch_fix_handle_irq_poll(deci_target_ch_fix_t * dtcf)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_ch_fix_handle_irq_poll(deci_target_ch_fix_t *dtcf)

{
  deci_target_ch_fix_handle_intr(dtcf);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f1d0
 * symbol: deci_target_ch_fix_handle_intr
 * prototype: int deci_target_ch_fix_handle_intr(deci_target_ch_fix_t * dtcf)
 * body addresses: 420
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int deci_target_ch_fix_handle_intr(deci_target_ch_fix_t *dtcf)

{
  uint16_t op;
  uint16_t op_00;
  uint32_t uVar1;
  int iVar2;
  char *pcVar3;
  char *file;
  u_int line;
  deci5s_ch_fix_t *pdVar4;
  uint uVar5;
  
  uVar1 = *dtcf->dtcf_mbox_c2t;
  deci_mp4_sig3_clear_int_from_emc(dtcf->dtcf_sig_bit_c2t);
  dtcf->dtcf_intr_count = dtcf->dtcf_intr_count + 1;
  if (uVar1 == 0x77777777) {
    uVar1 = deci5s_get_cpu();
    printf_low("%d:%s:DECI_SHM_MBOX_CLOSE\n",(ulong)uVar1,"deci_target_ch_fix_handle_mbox_intr");
    pcVar3 = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
    deci5s_assert(pcVar3,"deci_target_ch_fix_make_close",0x27d,1,"dtcf != NULL");
    iVar2 = (int)pcVar3;
    if (dtcf->dtcf_d5cf == (deci5s_ch_fix_t *)0x0) {
      file = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
      pcVar3 = "deci_target_ch_fix_make_close";
      line = 0x27f;
      goto LAB_0010f360;
    }
    pdVar4 = dtcf->dtcf_d5cf;
    uVar5 = pdVar4->d5cf_status & 0xfffffffd;
  }
  else {
    if (uVar1 != 0xdddddddd) {
      op = deci_shm_mbox_get_op0(uVar1);
      op_00 = deci_shm_mbox_get_op1(uVar1);
      deci_target_ch_fix_handle_op_intr(dtcf,op);
      iVar2 = deci_target_ch_fix_handle_op_intr(dtcf,op_00);
      return iVar2;
    }
    uVar1 = deci5s_get_cpu();
    printf_low("%d:%s:DECI_SHM_MBOX_OPEN\n",(ulong)uVar1,"deci_target_ch_fix_handle_mbox_intr");
    pcVar3 = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
    deci5s_assert(pcVar3,"deci_target_ch_fix_make_open",0x26f,1,"dtcf != NULL");
    iVar2 = (int)pcVar3;
    if (dtcf->dtcf_d5cf == (deci5s_ch_fix_t *)0x0) {
      file = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
      pcVar3 = "deci_target_ch_fix_make_open";
      line = 0x271;
LAB_0010f360:
      deci5s_assert(file,pcVar3,line,0,"0");
      return (int)file;
    }
    pdVar4 = dtcf->dtcf_d5cf;
    uVar5 = pdVar4->d5cf_status | 2;
  }
  pdVar4->d5cf_status = uVar5;
  return iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f374
 * symbol: deci_target_mp4_intr_with_cpu
 * prototype: int deci_target_mp4_intr_with_cpu(uint32_t cpu, uint32_t bits)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_mp4_intr_with_cpu(uint32_t cpu,uint32_t bits)

{
  deci_target_t *dts;
  deci_target_ch_fix_t *pdVar1;
  uint uVar2;
  ulong uVar3;
  
  dts = g_deci_target;
  uVar3 = (ulong)bits;
  while (uVar2 = (uint)uVar3, uVar2 != 0) {
    if ((uVar2 >> 8 & 1) == 0) {
      if ((uVar2 >> 9 & 1) == 0) {
        printf_low("%s:Unsupport SIG bits 0x%08x\n","deci_target_mp4_intr_with_cpu",uVar3);
        uVar3 = 0;
      }
      else {
        pdVar1 = deci_target_get_ch_fix(dts,1);
        deci_target_ch_fix_handle_intr(pdVar1);
        uVar3 = (ulong)(uVar2 & 0xfffffdff);
      }
    }
    else {
      pdVar1 = deci_target_get_ch_fix(dts,0);
      deci_target_ch_fix_handle_intr(pdVar1);
      uVar3 = (ulong)(uVar2 & 0xfffffeff);
    }
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f408
 * symbol: deci_target_get
 * prototype: deci_target_t * deci_target_get(void)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_target_t * deci_target_get(void)

{
  return g_deci_target;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f414
 * symbol: deci_target_get_ch_fix
 * prototype: deci_target_ch_fix_t * deci_target_get_ch_fix(deci_target_t * dts, u_int no)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_target_ch_fix_t * deci_target_get_ch_fix(deci_target_t *dts,u_int no)

{
  char *pcVar1;
  
  pcVar1 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar1,"deci_target_get_ch_fix",0x4d6,(uint)(dts != (deci_target_t *)0x0),
                "dts != NULL");
  pcVar1 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar1,"deci_target_get_ch_fix",0x4d7,
                (uint)(dts->dts_ch_fix_vec != (deci_target_ch_fix_t **)0x0),
                "dts->dts_ch_fix_vec != NULL");
  return dts->dts_ch_fix_vec[no];
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f4a0
 * symbol: deci_target_mp4_intr
 * prototype: int deci_target_mp4_intr(uint32_t bits)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_mp4_intr(uint32_t bits)

{
  deci_target_t *dts;
  deci_target_ch_fix_t *pdVar1;
  uint uVar2;
  ulong uVar3;
  
  dts = g_deci_target;
  uVar3 = (ulong)bits;
  while (uVar2 = (uint)uVar3, uVar2 != 0) {
    if ((uVar2 >> 8 & 1) == 0) {
      if ((uVar2 >> 9 & 1) == 0) {
        printf_low("%s:Unsupport SIG bits 0x%08x\n","deci_target_mp4_intr",uVar3);
        uVar3 = 0;
      }
      else {
        pdVar1 = deci_target_get_ch_fix(dts,1);
        deci_target_ch_fix_handle_intr(pdVar1);
        uVar3 = (ulong)(uVar2 & 0xfffffdff);
      }
    }
    else {
      pdVar1 = deci_target_get_ch_fix(dts,0);
      deci_target_ch_fix_handle_intr(pdVar1);
      uVar3 = (ulong)(uVar2 & 0xfffffeff);
    }
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f534
 * symbol: deci_target_mp4_poll
 * prototype: int deci_target_mp4_poll(void)
 * body addresses: 152
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_mp4_poll(void)

{
  deci_target_t *dts;
  bool bVar1;
  uint32_t uVar2;
  deci_target_ch_fix_t *dtcf;
  deci_target_ch_fix_t *dtcf_00;
  
  dts = g_deci_target;
  dtcf = deci_target_get_ch_fix(g_deci_target,0);
  dtcf_00 = deci_target_get_ch_fix(dts,1);
  bVar1 = false;
  while (!bVar1) {
    uVar2 = deci_mp4_sig3_read_int_from_emc();
    bVar1 = (dtcf->dtcf_sig_bit_c2t & uVar2) != 0;
    if (bVar1) {
      deci_target_ch_fix_handle_intr(dtcf);
    }
    if ((dtcf_00->dtcf_sig_bit_c2t & uVar2) != 0) {
      deci_target_ch_fix_handle_intr(dtcf_00);
      bVar1 = true;
    }
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010f5cc
 * symbol: deci_target_start
 * prototype: int deci_target_start(void)
 * body addresses: 1176
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_start(void)

{
  deci_target_md_t *pdVar1;
  uint32_t uVar2;
  int iVar3;
  char *pcVar4;
  deci_shm_common_t *dsc;
  deci_shm_node_t *pdVar5;
  deci_shm_node_t *dsn;
  deci_shm_ch_node_fix_t *dscnf;
  deci_shm_ch_node_fix_t *dscnf_00;
  deci_target_md_t *pdVar6;
  deci_shm_buf_t *pdVar7;
  uint8_t *puVar8;
  deci_target_ch_fix_t *pdVar9;
  uint uVar10;
  
  uVar2 = deci5s_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar2,"deci_target_start");
  if (g_deci_target == (deci_target_t *)0x0) {
    g_deci_target = &g_deci_target_data;
    pcVar4 = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
    deci5s_assert(pcVar4,"deci_target_init",0x4a6,1,"dts != NULL");
    g_deci_target_data.dts_n_ch_fix = 0;
    g_deci_target_data.dts_n_ch_ring = 0;
    g_deci_target_data.dts_ch_fix_vec = (deci_target_ch_fix_t **)0x0;
    g_deci_target_data.dts_ch_ring_vec = (deci_target_ch_ring_t **)0x0;
    deci_target_get_md();
    pdVar1 = g_deci_target_data.dts_md;
    dsc = (*(g_deci_target_data.dts_md)->dtmd_get_shm_common)();
    pdVar5 = deci_shm_common_get_node_cp(dsc);
    dsn = (*pdVar1->dtmd_get_shm_node_target)(dsc);
    uVar2 = dsn->dsn_n_ch_fix;
    g_deci_target_data.dts_n_ch_fix = dsn->dsn_n_ch_fix;
    g_deci_target_data.dts_n_ch_ring = dsn->dsn_n_ch_ring;
    pdVar9 = g_vec_deci_target_ch_fix;
    for (uVar10 = 0; uVar10 < uVar2; uVar10 = uVar10 + 1) {
      dscnf = (*pdVar1->dtmd_get_shm_ch_fix_cp_to_target)(dsc,uVar10);
      dscnf_00 = (*pdVar1->dtmd_get_shm_ch_fix_target_to_cp)(dsc,uVar10);
      if (dsc->dsc_magic1 != 0x63267916) {
        printf_low("%s:illegal dsc_magic1 0x%08x\n","deci_target_ch_fix_init");
      }
      if (pdVar5->dsn_magic1 != 0xc8f7e343) {
        printf_low("%s:illegal dsn_cp->dsn_magic1 0x%08x\n","deci_target_ch_fix_init");
      }
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      pdVar6 = deci_target_get_md();
      iVar3 = deci_shm_ch_node_fix_check_with_magic
                        (dscnf,pdVar6->dtmd_shm_ch_node_fix_cp_to_target_magic);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0x9e,iVar3,
                    "deci_shm_ch_node_fix_check_with_magic(dscnf_cp, deci_target_get_md()->dtmd_shm_ch_node_fix_cp_to_target_magic)"
                   );
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      pdVar6 = deci_target_get_md();
      iVar3 = deci_shm_node_check_with_magic(dsn,pdVar6->dtmd_shm_node_target_magic1);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0x9f,iVar3,
                    "deci_shm_node_check_with_magic(dsn_target, deci_target_get_md()->dtmd_shm_node_target_magic1)"
                   );
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      pdVar6 = deci_target_get_md();
      iVar3 = deci_shm_ch_node_fix_check_with_magic
                        (dscnf_00,pdVar6->dtmd_shm_ch_node_fix_target_to_cp_magic);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0xa1,iVar3,
                    "deci_shm_ch_node_fix_check_with_magic(dscnf_target, deci_target_get_md()->dtmd_shm_ch_node_fix_target_to_cp_magic)"
                   );
      pdVar9->dtcf_self_size = 0x128;
      pdVar9->dtcf_id = uVar10;
      pdVar9->dtcf_magic1 = 0x11609934;
      pdVar9->dtcf_intr_count = 0;
      pdVar9->dtcf_mbox_req_count = 0;
      pdVar9->dtcf_mbox_free_count = 0;
      pdVar9->dtcf_mbox_nop_count = 0;
      pdVar9->dtcf_read_count = 0;
      pdVar9->dtcf_write_count = 0;
      pdVar9->dtcf_total_read_size = 0;
      pdVar9->dtcf_total_write_size = 0;
      pdVar9->dtcf_ch_fix_c2t = dscnf;
      pdVar9->dtcf_ch_fix_t2c = dscnf_00;
      pdVar9->dtcf_mbox_c2t = &(dscnf->dscnf_mbox).dsm_mbox;
      pdVar9->dtcf_sig_no_c2t = (dscnf->dscnf_mbox).dsm_sig_no;
      pdVar9->dtcf_sig_dst_c2t = (dscnf->dscnf_mbox).dsm_sig_dst;
      pdVar9->dtcf_sig_bit_c2t = (dscnf->dscnf_mbox).dsm_sig_bit;
      pdVar9->dtcf_mbox_t2c = &(dscnf_00->dscnf_mbox).dsm_mbox;
      pdVar9->dtcf_sig_no_t2c = (dscnf_00->dscnf_mbox).dsm_sig_no;
      pdVar9->dtcf_sig_dst_t2c = (dscnf_00->dscnf_mbox).dsm_sig_dst;
      pdVar9->dtcf_sig_bit_t2c = (dscnf_00->dscnf_mbox).dsm_sig_bit;
      pdVar7 = (deci_shm_buf_t *)deci_shm_common_get_ptr(dsc,dscnf->dscnf_buf_spec_offset_cmd);
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      iVar3 = deci_shm_buf_check(pdVar7);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0xca,iVar3,"deci_shm_buf_check(buf)");
      pdVar9->dtcf_c2t_cmd_bid = pdVar7->dsb_id;
      puVar8 = deci_shm_common_get_ptr(dsc,pdVar7->dsb_buf_offset);
      pdVar9->dtcf_c2t_cmd_buf_ptr = puVar8;
      pdVar9->dtcf_c2t_cmd_buf_size = pdVar7->dsb_buf_size;
      pdVar9->dtcf_c2t_cmd_status_ptr = &dscnf->dscnf_buf_status_cmd;
      pdVar9->dtcf_c2t_cmd_data_size_ptr = &dscnf->dscnf_buf_data_size_cmd;
      pdVar7 = (deci_shm_buf_t *)deci_shm_common_get_ptr(dsc,dscnf_00->dscnf_buf_spec_offset_cmd);
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      iVar3 = deci_shm_buf_check(pdVar7);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0xd6,iVar3,"deci_shm_buf_check(buf)");
      pdVar9->dtcf_t2c_cmd_bid = pdVar7->dsb_id;
      puVar8 = deci_shm_common_get_ptr(dsc,pdVar7->dsb_buf_offset);
      pdVar9->dtcf_t2c_cmd_buf_ptr = puVar8;
      pdVar9->dtcf_t2c_cmd_buf_size = pdVar7->dsb_buf_size;
      pdVar9->dtcf_t2c_cmd_status_ptr = &dscnf_00->dscnf_buf_status_cmd;
      pdVar9->dtcf_t2c_cmd_data_size_ptr = &dscnf_00->dscnf_buf_data_size_cmd;
      pdVar7 = (deci_shm_buf_t *)deci_shm_common_get_ptr(dsc,dscnf_00->dscnf_buf_spec_offset_res);
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      iVar3 = deci_shm_buf_check(pdVar7);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0xe2,iVar3,"deci_shm_buf_check(buf)");
      pdVar9->dtcf_c2t_res_bid = pdVar7->dsb_id;
      puVar8 = deci_shm_common_get_ptr(dsc,pdVar7->dsb_buf_offset);
      pdVar9->dtcf_c2t_res_buf_ptr = puVar8;
      pdVar9->dtcf_c2t_res_buf_size = pdVar7->dsb_buf_size;
      pdVar9->dtcf_c2t_res_status_ptr = &dscnf_00->dscnf_buf_status_res;
      pdVar9->dtcf_c2t_res_data_size_ptr = &dscnf_00->dscnf_buf_data_size_res;
      pdVar7 = (deci_shm_buf_t *)deci_shm_common_get_ptr(dsc,dscnf->dscnf_buf_spec_offset_res);
      pcVar4 = deci5s_basename(
                              "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                              );
      iVar3 = deci_shm_buf_check(pdVar7);
      deci5s_assert(pcVar4,"deci_target_ch_fix_init",0xee,iVar3,"deci_shm_buf_check(buf)");
      pdVar9->dtcf_t2c_res_bid = pdVar7->dsb_id;
      puVar8 = deci_shm_common_get_ptr(dsc,pdVar7->dsb_buf_offset);
      pdVar9->dtcf_t2c_res_buf_ptr = puVar8;
      pdVar9->dtcf_t2c_res_buf_size = pdVar7->dsb_buf_size;
      pdVar9->dtcf_t2c_res_status_ptr = &dscnf->dscnf_buf_status_res;
      pdVar9->dtcf_t2c_res_data_size_ptr = &dscnf->dscnf_buf_data_size_res;
      pdVar9->dtcf_d5cf = (deci5s_ch_fix_t *)0x0;
      pdVar9->dtcf_magic2 = 0x7d7b6e04;
      uVar2 = g_deci_target_data.dts_n_ch_fix;
      g_vecp_deci_target_ch_fix[uVar10] = pdVar9;
      pdVar9 = pdVar9 + 1;
    }
    g_deci_target_data.dts_ch_fix_vec = g_vecp_deci_target_ch_fix;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fa64
 * symbol: deci_target_up
 * prototype: int deci_target_up(deci_target_t * dts, uint32_t core)
 * body addresses: 260
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_up(deci_target_t *dts,uint32_t core)

{
  deci_target_ch_fix_t *dtcf;
  char *pcVar1;
  char *format;
  ulong uVar2;
  int c;
  
  dtcf = deci_target_get_ch_fix(dts,core);
  pcVar1 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar1,"deci_target_up",0x53d,(uint)(dtcf != (deci_target_ch_fix_t *)0x0),
                "dtcf != NULL");
  pcVar1 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  if (dtcf->dtcf_self_size == 0x128) {
    if (dtcf->dtcf_magic1 == 0x11609934) {
      if (dtcf->dtcf_magic2 == 0x7d7b6e04) {
        c = 1;
        goto LAB_0010fb2c;
      }
      uVar2 = (ulong)dtcf->dtcf_magic2;
      format = "%s:illegal magic2 0x%08x\n";
    }
    else {
      uVar2 = (ulong)dtcf->dtcf_magic1;
      format = "%s:illegal magic1 0x%08x\n";
    }
  }
  else {
    uVar2 = (ulong)dtcf->dtcf_self_size;
    format = "%s:illegal self_size 0x%08x\n";
  }
  printf_low(format,"deci_target_ch_fix_check",uVar2);
  c = 0;
LAB_0010fb2c:
  deci5s_assert(pcVar1,"deci_target_up",0x53e,c,"deci_target_ch_fix_check(dtcf)");
  deci_target_ch_fix_write_mbox(dtcf,0xeeeeeeee,0);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fb68
 * symbol: deci_target_get_md_variable
 * prototype: deci_target_md_t * deci_target_get_md_variable(deci_target_t * dts)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_target_md_t * deci_target_get_md_variable(deci_target_t *dts)

{
  g_deci_target_md.dtmd_dts = dts;
  return &g_deci_target_md;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fb7c
 * symbol: deci_target_mp4_get_ch_fix
 * prototype: deci_target_ch_fix_t * deci_target_mp4_get_ch_fix(uint32_t id)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_target_ch_fix_t * deci_target_mp4_get_ch_fix(uint32_t id)

{
  deci_target_ch_fix_t *pdVar1;
  
  pdVar1 = deci_target_get_ch_fix(g_deci_target,id);
  return pdVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fb94
 * symbol: deci_target_mp4_start
 * prototype: int deci_target_mp4_start(uint32_t core)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_mp4_start(uint32_t core)

{
  if (core == 0) {
    deci_sig_mp4_start();
    deci_target_start();
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fbb4
 * symbol: deci_target_mp4_up
 * prototype: int deci_target_mp4_up(uint32_t core)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_mp4_up(uint32_t core)

{
  deci_target_up(g_deci_target,core);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fbe0
 * symbol: deci_target_get_md
 * prototype: deci_target_md_t * deci_target_get_md(void)
 * body addresses: 160
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_target_md_t * deci_target_get_md(void)

{
  char *pcVar1;
  
  pcVar1 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar1,"deci_target_get_md",0x60,(uint)(g_deci_target != (deci_target_t *)0x0),
                "g_deci_target != NULL");
  if (g_deci_target_data.dts_md == (deci_target_md_t *)0x0) {
    g_deci_target_md.dtmd_dts = g_deci_target;
    g_deci_target_data.dts_md = &g_deci_target_md;
  }
  pcVar1 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar1,"deci_target_get_md",100,
                (uint)(g_deci_target_data.dts_md != (deci_target_md_t *)0x0),
                "g_deci_target->dts_md != NULL");
  return g_deci_target_data.dts_md;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010fc80
 * symbol: deci_target_ch_fix_handle_op_intr
 * prototype: int deci_target_ch_fix_handle_op_intr(deci_target_ch_fix_t * dtcf, uint16_t op)
 * body addresses: 564
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int deci_target_ch_fix_handle_op_intr(deci_target_ch_fix_t *dtcf,uint16_t op)

{
  uint uVar1;
  uint32_t uVar2;
  char *file;
  deci_target_ch_fix_t *file_00;
  u_int line;
  deci5s_context_t dStack_78;
  
  uVar1 = (uint)op;
  switch((uVar1 & 0xf000) + 0x1000 >> 0xc & 0xf) {
  case 0:
    dtcf->dtcf_mbox_nop_count = dtcf->dtcf_mbox_nop_count + 1;
    break;
  default:
    uVar2 = deci5s_get_cpu();
    printf_low("%d:%s:Unknown op 0x%04x\n",(ulong)uVar2,"deci_target_ch_fix_handle_op_intr",
               (ulong)uVar1);
    file = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
    line = 0x262;
    goto LAB_0010fe4c;
  case 2:
    uVar1 = uVar1 & 0xfff;
    dtcf->dtcf_mbox_free_count = dtcf->dtcf_mbox_free_count + 1;
    if ((uVar1 != dtcf->dtcf_c2t_res_bid) && (uVar1 != dtcf->dtcf_t2c_cmd_bid)) {
      printf_low("%s:DECI_MBOX_FREE: bid=0x%08x != 0x%08x\n","deci_target_ch_fix_handle_op_intr",
                 (ulong)uVar1,(ulong)dtcf->dtcf_t2c_cmd_bid);
      printf_low("%s:DECI_MBOX_FREE: bid=0x%08x != 0x%08x\n","deci_target_ch_fix_handle_op_intr",
                 (ulong)uVar1,(ulong)dtcf->dtcf_c2t_res_bid);
    }
    file_00 = (deci_target_ch_fix_t *)
              deci5s_basename(
                             "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                             );
    if (uVar1 == dtcf->dtcf_c2t_res_bid) {
      uVar1 = 1;
    }
    else {
      uVar1 = (uint)(uVar1 == dtcf->dtcf_t2c_cmd_bid);
    }
    deci5s_assert((char *)file_00,"deci_target_ch_fix_handle_op_intr",0x24a,uVar1,
                  "(bid == dtcf->dtcf_c2t_res_bid) || (bid == dtcf->dtcf_t2c_cmd_bid)");
    *dtcf->dtcf_t2c_cmd_status_ptr = *dtcf->dtcf_t2c_cmd_status_ptr & 0xfff00000 | 2;
    dtcf = file_00;
    break;
  case 3:
    dtcf->dtcf_mbox_req_count = dtcf->dtcf_mbox_req_count + 1;
    deci5s_context_init(&dStack_78,1,dtcf->dtcf_id);
    dStack_78.dc_cmd_ptr = dtcf->dtcf_c2t_cmd_buf_ptr;
    dStack_78.dc_cmd_size = *dtcf->dtcf_c2t_cmd_data_size_ptr;
    dStack_78.dc_res_ptr = dtcf->dtcf_c2t_res_buf_ptr;
    dStack_78.dc_res_max = dtcf->dtcf_c2t_res_buf_size;
    dStack_78.dc_res_data_size = 0;
    dtcf->dtcf_read_count = dtcf->dtcf_read_count + 1;
    dtcf->dtcf_total_read_size = dtcf->dtcf_total_read_size + (ulong)dStack_78.dc_cmd_size;
    uVar1 = deci5s_context_handle_packet(&dStack_78);
    if (uVar1 != 0) {
      uVar2 = deci5s_get_cpu();
      printf_low("%d:%s:deci5s_context_handle_packet failed %d\n",(ulong)uVar2,
                 "deci_target_ch_fix_handle_request_intr",(ulong)uVar1);
    }
    uVar1 = deci_target_ch_fix_send_reply(dtcf,&dStack_78);
    dtcf = (deci_target_ch_fix_t *)(ulong)uVar1;
    break;
  case 5:
    file = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
    line = 600;
LAB_0010fe4c:
    deci5s_assert(file,"deci_target_ch_fix_handle_op_intr",line,0,"0");
    return (int)file;
  }
  return (int)dtcf;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010feb4
 * symbol: deci_target_mp4_int_to_cp
 * prototype: void deci_target_mp4_int_to_cp(uint32_t no, uint32_t dst, uint32_t bit, uint32_t * mbox, uint32_t val, uint32_t hint0)
 * body addresses: 252
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci_target_mp4_int_to_cp
               (uint32_t no,uint32_t dst,uint32_t bit,uint32_t *mbox,uint32_t val,uint32_t hint0)

{
  uint32_t uVar1;
  u_int core;
  deci_shm_common_t *dsc;
  char *pcVar2;
  
  dsc = deci_shm_mp4_common();
  if (no == 1) {
    if (dst == 2) {
      uVar1 = deci_shm_common_get_offset(dsc,(uint8_t *)mbox);
      core = mp4_get_cpu();
      msi_send_write_sig(core,bit,uVar1,val,hint0);
      return;
    }
  }
  else {
    uVar1 = deci5s_get_cpu();
    printf_low("%d:%s:no=0x%08x, dst=0x%08x, bit=0x%08x\n",(ulong)uVar1,"deci_target_mp4_int_to_cp",
               (ulong)no,(ulong)dst,(ulong)bit);
    pcVar2 = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
    deci5s_assert(pcVar2,"deci_target_mp4_int_to_cp",0x78b,0,"0");
  }
  pcVar2 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar2,"deci_target_mp4_int_to_cp",0x78e,0,"0");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ffb0
 * symbol: deci_target_mp4_clear_int_from_cp
 * prototype: void deci_target_mp4_clear_int_from_cp(uint32_t no, uint32_t dst, uint32_t bit)
 * body addresses: 152
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci_target_mp4_clear_int_from_cp(uint32_t no,uint32_t dst,uint32_t bit)

{
  uint32_t uVar1;
  char *file;
  
  if (no != 1 || dst != 3) {
    uVar1 = deci5s_get_cpu();
    printf_low("%d:%s:Unsupport combination: no %d, dst %d, bit 0x%08x\n",(ulong)uVar1,
               "deci_target_mp4_clear_int_from_cp",(ulong)no,(ulong)dst,(ulong)bit);
    file = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
    deci5s_assert(file,"deci_target_mp4_clear_int_from_cp",0x7ab,0,"0");
    return;
  }
  deci_mp4_sig3_clear_int_from_emc(bit);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110048
 * symbol: deci_target_mp4_wait_clear_target_to_cp
 * prototype: int deci_target_mp4_wait_clear_target_to_cp(uint32_t no, uint32_t dst, uint32_t bit)
 * body addresses: 192
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_target_mp4_wait_clear_target_to_cp(uint32_t no,uint32_t dst,uint32_t bit)

{
  int iVar1;
  char *pcVar2;
  code *pcVar3;
  int iVar4;
  
  if (no == 1 && dst == 2) {
    pcVar3 = deci_mp4_sig2_read_int_from_emc;
  }
  else {
    printf_low("%s:no=0x%08x, dst=0x%08x\n","deci_target_mp4_get_func",(ulong)no,(ulong)dst);
    pcVar2 = deci5s_basename(
                            "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                            );
    deci5s_assert(pcVar2,"deci_target_mp4_get_func",0x7c4,0,"0");
    pcVar3 = readElement<unsigned_int>;
  }
  iVar4 = 0xfffffff;
  do {
    iVar1 = (*pcVar3)();
    if (iVar1 == 0) {
      return 0;
    }
    iVar4 = iVar4 + 1;
  } while (iVar4 != 0);
  pcVar2 = deci5s_basename(
                          "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_target_mp4.c"
                          );
  deci5s_assert(pcVar2,"deci_target_mp4_wait_clear_target_to_cp",0x7da,0,"0");
  return -1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110108
 * symbol: deci_target_mp4_get_shm_common
 * prototype: deci_shm_common_t * deci_target_mp4_get_shm_common(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_common_t * deci_target_mp4_get_shm_common(void)

{
  uint32_t uVar1;
  
  if (g_deci_shm_mp4 != (deci_shm_mp4_t *)0x0) {
    return (deci_shm_common_t *)g_deci_shm_mp4_data.dsm4_shm_common;
  }
  uVar1 = deci5s_get_cpu();
  printf_low("%d:%s:There is no g_deci_shm_mp4.\n",(ulong)uVar1,"deci_shm_mp4_common");
  return (deci_shm_common_t *)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011010c
 * symbol: deci_target_mp4_get_shm_node_target
 * prototype: deci_shm_node_t * deci_target_mp4_get_shm_node_target(deci_shm_common_t * dsc)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_node_t * deci_target_mp4_get_shm_node_target(deci_shm_common_t *dsc)

{
  deci_shm_node_t *pdVar1;
  
  pdVar1 = deci_shm_common_get_node(dsc,0x43fe7688);
  return pdVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110110
 * symbol: deci_target_mp4_get_shm_ch_fix_cp_to_target
 * prototype: deci_shm_ch_node_fix_t * deci_target_mp4_get_shm_ch_fix_cp_to_target(deci_shm_common_t * dsc, uint ui)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_fix_t * deci_target_mp4_get_shm_ch_fix_cp_to_target(deci_shm_common_t *dsc,uint ui)

{
  int iVar1;
  char *pcVar2;
  char *file;
  deci_shm_common_target_t *pdVar3;
  deci_shm_node_t *pdVar4;
  uint8_t *puVar5;
  u_int line;
  ulong uVar6;
  
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar1 = deci_shm_common_check(dsc);
  deci5s_assert(pcVar2,"deci_shm_common_get_index_ch_fix_mp4",0x730,iVar1,
                "deci_shm_common_check(dsc)");
  iVar1 = deci_shm_common_get_version(dsc);
  if (iVar1 == 1) {
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    pcVar2 = "deci_shm_common_get_index_ch_fix_mp4";
    line = 0x732;
  }
  else {
    pdVar3 = deci_shm_common_v2_find_target((deci_shm_common_v2_t *)dsc,0x43fe7688);
    if (pdVar3 != (deci_shm_common_target_t *)0x0) {
      uVar6 = (ulong)pdVar3->dsct_base_ch_fix;
      goto LAB_0010e808;
    }
    pcVar2 = "deci_shm_common_v2_get_base_ch_fix";
    printf_low("%s:deci_shm_common_v2_find_target() failed\n","deci_shm_common_v2_get_base_ch_fix");
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    line = 0x5be;
  }
  deci5s_assert(file,pcVar2,line,0,"0");
  uVar6 = 0;
LAB_0010e808:
  pdVar4 = deci_shm_common_get_node_cp(dsc);
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar2,"deci_shm_common_get_ch_fix_cp_to_target",0x96a,
                (uint)(pdVar4->dsn_magic1 == 0xc8f7e343),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_CP");
  puVar5 = deci_shm_common_get_ptr(dsc,pdVar4->dsn_ch_offset);
  pcVar2 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar2,"deci_shm_common_get_ch_fix_cp_to_mp4",0x98e,
                (uint)(((deci_shm_ch_node_fix_t *)(puVar5 + (ulong)ui * 0x60 + uVar6 * 0x60))->
                       dscnf_magic == 0xcb9b4aba),
                "dscnf->dscnf_magic == DECI_SHM_CH_NODE_FIX_MAGIC_CP_TO_MP4");
  return (deci_shm_ch_node_fix_t *)(puVar5 + (ulong)ui * 0x60 + uVar6 * 0x60);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110114
 * symbol: deci_target_mp4_get_shm_ch_fix_target_to_cp
 * prototype: deci_shm_ch_node_fix_t * deci_target_mp4_get_shm_ch_fix_target_to_cp(deci_shm_common_t * dsc, uint ui)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_fix_t * deci_target_mp4_get_shm_ch_fix_target_to_cp(deci_shm_common_t *dsc,uint ui)

{
  deci_shm_node_t *pdVar1;
  char *file;
  uint8_t *puVar2;
  
  pdVar1 = deci_shm_common_get_node_mp4(dsc);
  file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(file,"deci_shm_common_get_ch_fix_mp4_to_cp",0x9cd,
                (uint)(pdVar1->dsn_magic1 == 0x8e7e62d6),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_MP4");
  puVar2 = deci_shm_common_get_ptr(dsc,pdVar1->dsn_ch_offset);
  return (deci_shm_ch_node_fix_t *)(puVar2 + (ulong)ui * 0x60);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110118
 * symbol: deci_target_mp4_get_shm_ch_ring_cp_to_target
 * prototype: deci_shm_ch_node_ring_t * deci_target_mp4_get_shm_ch_ring_cp_to_target(deci_shm_common_t * dsc, uint ui)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_ring_t *
deci_target_mp4_get_shm_ch_ring_cp_to_target(deci_shm_common_t *dsc,uint ui)

{
  uint uVar1;
  int iVar2;
  char *pcVar3;
  deci_shm_common_target_t *pdVar4;
  deci_shm_node_t *pdVar5;
  uint8_t *puVar6;
  uint32_t uVar7;
  ulong uVar8;
  
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  iVar2 = deci_shm_common_check(dsc);
  deci5s_assert(pcVar3,"deci_shm_common_get_index_ch_ring_mp4",0x77d,iVar2,
                "deci_shm_common_check(dsc)");
  iVar2 = deci_shm_common_get_version(dsc);
  if (iVar2 == 1) {
    pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
    deci5s_assert(pcVar3,"deci_shm_common_get_index_ch_ring_mp4",0x77f,0,"0");
    uVar8 = 0;
  }
  else {
    pdVar4 = deci_shm_common_v2_find_target((deci_shm_common_v2_t *)dsc,0x43fe7688);
    if (pdVar4 == (deci_shm_common_target_t *)0x0) {
      printf_low("%s:deci_shm_common_v2_find_target() failed\n",
                 "deci_shm_common_v2_get_base_ch_ring");
      pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c"
                              );
      deci5s_assert(pcVar3,"deci_shm_common_v2_get_base_ch_ring",0x5cd,0,"0");
      uVar7 = 0;
    }
    else {
      uVar7 = pdVar4->dsct_base_ch_ring;
    }
    uVar8 = (ulong)(uVar7 - dsc[1].dsc_magic1);
  }
  pdVar5 = deci_shm_common_get_node_cp(dsc);
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_cp_to_target",0x9ec,
                (uint)(pdVar5->dsn_magic1 == 0xc8f7e343),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_CP");
  puVar6 = deci_shm_common_get_ptr(dsc,pdVar5->dsn_ch_offset);
  uVar1 = pdVar5->dsn_n_ch_fix;
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_cp_to_mp4",0xa16,
                (uint)(((deci_shm_ch_node_ring_t *)
                       (puVar6 + (ulong)ui * 0x60 + uVar8 * 0x60 + (ulong)uVar1 * 0x60))->
                       dscnr_magic == 0x8e154c2a),
                "dscnr->dscnr_magic == DECI_SHM_CH_NODE_RING_MAGIC_CP_TO_MP4");
  return (deci_shm_ch_node_ring_t *)(puVar6 + (ulong)ui * 0x60 + uVar8 * 0x60 + (ulong)uVar1 * 0x60)
  ;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011011c
 * symbol: deci_target_mp4_get_shm_ch_ring_target_to_cp
 * prototype: deci_shm_ch_node_ring_t * deci_target_mp4_get_shm_ch_ring_target_to_cp(deci_shm_common_t * dsc, uint ui)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci_shm_ch_node_ring_t *
deci_target_mp4_get_shm_ch_ring_target_to_cp(deci_shm_common_t *dsc,uint ui)

{
  uint uVar1;
  int c;
  deci_shm_node_t *pdVar2;
  char *pcVar3;
  uint8_t *puVar4;
  
  pdVar2 = deci_shm_common_get_node_mp4(dsc);
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_mp4_to_cp",0xa59,
                (uint)(pdVar2->dsn_magic1 == 0x8e7e62d6),
                "dsn->dsn_magic1 == DECI_SHM_NODE_MAGIC1_MP4");
  puVar4 = deci_shm_common_get_ptr(dsc,pdVar2->dsn_ch_offset);
  uVar1 = pdVar2->dsn_n_ch_fix;
  pcVar3 = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_shm.c");
  c = deci_shm_ch_node_ring_check((deci_shm_ch_node_ring_t *)(puVar4 + (ulong)uVar1 * 0x60));
  deci5s_assert(pcVar3,"deci_shm_common_get_ch_ring_target_to_cp",0xa39,c,
                "deci_shm_ch_node_ring_check(dscnr)");
  return (deci_shm_ch_node_ring_t *)(puVar4 + (ulong)uVar1 * 0x60) + ui;
}


