/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\deci_sig_mp4.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010eef4
 * symbol: deci_mp4_sig1_write_int_to_sycorax
 * prototype: void deci_mp4_sig1_write_int_to_sycorax(uint32_t bit, uint32_t * dst, uint32_t val)
 * body addresses: 160
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci_mp4_sig1_write_int_to_sycorax(uint32_t bit,uint32_t *dst,uint32_t val)

{
  uint uVar1;
  deci_sig_mp4_t *pdVar2;
  uint32_t uVar3;
  char *file;
  
  pdVar2 = g_deci_sig_mp4;
  uVar1 = *(uint *)(g_deci_sig_mp4->dsim_sig2 + 0x14);
  if (uVar1 != 0) {
    uVar3 = deci5s_get_cpu();
    printf_low("%d:%s:SIG2 INT_FROM_CPUY has data 0x%08x\n",(ulong)uVar3,
               "deci_mp4_sig1_write_int_to_sycorax",(ulong)uVar1);
    file = deci5s_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci_sig_mp4.c"
                          );
    deci5s_assert(file,"deci_mp4_sig1_write_int_to_sycorax",0x29e,0,"0");
  }
  *dst = val;
  *(uint32_t *)(pdVar2->dsim_sig1 + 4) = bit;
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ef94
 * symbol: deci_mp4_sig2_read_int_from_emc
 * prototype: uint32_t deci_mp4_sig2_read_int_from_emc(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci_mp4_sig2_read_int_from_emc(void)

{
  return *(uint32_t *)(g_deci_sig_mp4->dsim_sig2 + 0x14);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010efa8
 * symbol: deci_mp4_sig3_read_int_from_emc
 * prototype: uint32_t deci_mp4_sig3_read_int_from_emc(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci_mp4_sig3_read_int_from_emc(void)

{
  return *(uint32_t *)(g_deci_sig_mp4->dsim_sig3 + 0x14);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010efbc
 * symbol: deci_mp4_sig3_clear_int_from_emc
 * prototype: void deci_mp4_sig3_clear_int_from_emc(uint32_t v)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci_mp4_sig3_clear_int_from_emc(uint32_t v)

{
  *(uint32_t *)(g_deci_sig_mp4->dsim_sig3 + 0x14) = v;
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010efd4
 * symbol: deci_sig_mp4_start
 * prototype: int deci_sig_mp4_start(void)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci_sig_mp4_start(void)

{
  g_deci_sig_mp4_data.dsim_base = 0xc1600000;
  g_deci_sig_mp4 = &g_deci_sig_mp4_data;
  g_deci_sig_mp4_data.dsim_msi = 0xc17c8400;
  g_deci_sig_mp4_data.dsim_sig1 = 0xc1683800;
  g_deci_sig_mp4_data.dsim_sig2 = 0xc1784000;
  g_deci_sig_mp4_data.dsim_sig3 = 0xc1784800;
  return 0;
}


