/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\deci5s_mp4.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bf78
 * symbol: deci5s_assert
 * prototype: void deci5s_assert(char * file, char * func, u_int line, int c, char * cstr)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void deci5s_assert(char *file,char *func,u_int line,int c,char *cstr)

{
  if (c != 0) {
    return;
  }
  printf_low("Assertion failed at <%s:%s:%d:%s>\n",file,func,(ulong)line);
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bfc4
 * symbol: deci5s_basename
 * prototype: char * deci5s_basename(char * f)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

char * deci5s_basename(char *f)

{
  char *pcVar1;
  char cVar2;
  char *pcVar3;
  char *pcVar4;
  
  pcVar3 = (char *)0x0;
  pcVar4 = f;
  while( true ) {
    pcVar1 = pcVar4 + 1;
    cVar2 = *pcVar4;
    if (cVar2 == '\0') break;
    pcVar4 = pcVar1;
    if (((cVar2 == '\\') || (cVar2 == '/')) && (*pcVar1 != '\0')) {
      pcVar3 = pcVar1;
    }
  }
  if (pcVar3 != (char *)0x0) {
    f = pcVar3;
  }
  return f;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bfc8
 * symbol: deci5s_get_cpu
 * prototype: uint32_t deci5s_get_cpu(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci5s_get_cpu(void)

{
  uint uVar1;
  
  uVar1 = aarch64_read_MPIDR_EL1();
  return uVar1 & 0xff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bfcc
 * symbol: deci5s_roundup64
 * prototype: uint32_t deci5s_roundup64(uint32_t orig)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t deci5s_roundup64(uint32_t orig)

{
  return orig + 7 & 0xfffffff8;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bfd8
 * symbol: deci5s_ch_fix_get_t2c_cmd_ptr
 * prototype: uint8_t * deci5s_ch_fix_get_t2c_cmd_ptr(deci5s_ch_fix_t * d5cf)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint8_t * deci5s_ch_fix_get_t2c_cmd_ptr(deci5s_ch_fix_t *d5cf)

{
  return d5cf->d5cf_low->dtcf_t2c_cmd_buf_ptr;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bfe4
 * symbol: deci5s_sdbgp_com_spec_vector_find
 * prototype: deci5s_sdbgp_command_spec_t * deci5s_sdbgp_com_spec_vector_find(deci5s_sdbgp_command_spec_t * vec, uint32_t type)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

deci5s_sdbgp_command_spec_t *
deci5s_sdbgp_com_spec_vector_find(deci5s_sdbgp_command_spec_t *vec,uint32_t type)

{
  deci5s_sdbgp_command_spec_t *pdVar1;
  deci5s_sdbgp_command_spec_t *pdVar2;
  
  pdVar2 = vec + -1;
  do {
    pdVar1 = pdVar2 + 1;
    pdVar2 = pdVar2 + 1;
  } while (pdVar1->dscs_type != 0x1ffffff && pdVar1->dscs_type != type);
  return pdVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c004
 * symbol: deci5s_sdbgp_context_alloc_res_command
 * prototype: int deci5s_sdbgp_context_alloc_res_command(deci5s_sdbgp_context_t * dsc)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_alloc_res_command(deci5s_sdbgp_context_t *dsc)

{
  int iVar1;
  
  iVar1 = deci5s_sdbgp_context_alloc_res_command_common
                    (dsc,dsc->dsc_cmd_command->type & 0xffffff | 0x2000000,
                     *(uint32_t *)&dsc->dsc_cmd_spec->dscs_res_size);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c01c
 * symbol: deci5s_sdbgp_context_alloc_res_command_common
 * prototype: int deci5s_sdbgp_context_alloc_res_command_common(deci5s_sdbgp_context_t * dsc, uint32_t type, uint32_t csize)
 * body addresses: 264
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_alloc_res_command_common
              (deci5s_sdbgp_context_t *dsc,uint32_t type,uint32_t csize)

{
  uint8_t *puVar1;
  uint uVar2;
  int iVar3;
  u_int uVar4;
  SceDeci5sSdbgpCommand *pSVar5;
  SceDeci5sSdbgpHeader *pSVar6;
  SceDeci5sSdbgpHeader *pSVar7;
  uint8_t *puVar8;
  deci5s_context_t *pdVar9;
  
  iVar3 = deci5s_context_check_overflow(dsc->dsc_dc,csize);
  if (iVar3 == 0) {
    uVar4 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_context_check_overflow() failed\n",(ulong)uVar4,
               "deci5s_sdbgp_context_alloc_res_command_common");
  }
  else {
    pSVar5 = dsc->dsc_res_command;
    if (pSVar5 == (SceDeci5sSdbgpCommand *)0x0) {
      pSVar7 = dsc->dsc_res_sdbgp;
      pSVar6 = pSVar7 + 1;
    }
    else {
      pSVar6 = (SceDeci5sSdbgpHeader *)(pSVar5 + pSVar5->total_size);
      pSVar7 = dsc->dsc_res_sdbgp;
    }
    dsc->dsc_res_command = (SceDeci5sSdbgpCommand *)pSVar6;
    puVar1 = (uint8_t *)((long)&pSVar6->self_size + (ulong)csize);
    pSVar7->n_command = pSVar7->n_command + 1;
    pSVar6->self_size = csize;
    pSVar6->total_size = pSVar6->self_size;
    pSVar6->sequence_no = type;
    pSVar6->packet_no = 0;
    pSVar6->attr = dsc->dsc_cmd_command->command_no;
    pSVar6->n_command = 0;
    pdVar9 = dsc->dsc_dc;
    uVar2 = pdVar9->dc_res_data_size + csize;
    pdVar9->dc_res_data_size = uVar2;
    pSVar7->total_size = pSVar7->total_size + csize;
    puVar8 = pdVar9->dc_res_ptr;
    dsc->dsc_res_info = puVar1;
    if (puVar8 + uVar2 == puVar1) {
      return 0;
    }
    printf_low("%s:mismatch [writep] %p and %p [res_info]\n",
               "deci5s_sdbgp_context_alloc_res_command_common");
  }
  return -1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c124
 * symbol: deci5s_context_init
 * prototype: void deci5s_context_init(deci5s_context_t * dc, uint32_t mode, uint32_t id)
 * body addresses: 152
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci5s_context_init(deci5s_context_t *dc,uint32_t mode,uint32_t id)

{
  char *file;
  deci5s_ch_fix_t *pdVar1;
  uint8_t *puVar2;
  deci_target_ch_fix_t *pdVar3;
  
  dc->dc_mode = mode;
  dc->dc_id = id;
  dc->dc_d5s = &g_d5s;
  if (mode == 1) {
    pdVar1 = g_d5s.d5s_ch_fix[id];
    dc->dc_ch_ring = (deci5s_ch_ring_t *)0x0;
    pdVar3 = pdVar1->d5cf_low;
    dc->dc_ch_fix = pdVar1;
    dc->dc_cmd_ptr = pdVar3->dtcf_c2t_cmd_buf_ptr;
    dc->dc_cmd_size = pdVar3->dtcf_c2t_cmd_buf_size;
    puVar2 = pdVar3->dtcf_c2t_res_buf_ptr;
    dc->dc_res_max = 0;
    dc->dc_res_ptr = puVar2;
  }
  else {
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci5s_mp4.c");
    deci5s_assert(file,"deci5s_context_init",0x9e2,0,"0");
  }
  dc->dc_result = 0;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c1bc
 * symbol: deci5s_context_handle_packet
 * prototype: int deci5s_context_handle_packet(deci5s_context_t * dc)
 * body addresses: 892
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_context_handle_packet(deci5s_context_t *dc)

{
  uint32_t uVar1;
  uint32_t uVar2;
  deci5s_sdbgp_command_spec_t *pdVar3;
  int iVar4;
  u_int uVar5;
  uint64_t uVar6;
  deci5s_sdbgp_command_spec_t *pdVar7;
  uint32_t uVar8;
  SceDeci5sHeader *cmd;
  SceDeci5sSdbgpCmd *pSVar9;
  SceDeci5sHeader *p;
  int *piVar10;
  uint uVar11;
  uint32_t uVar12;
  deci5s_sdbgp_context_t local_b8;
  
  piVar10 = (int *)dc->dc_cmd_ptr;
  if (*piVar10 != 0x73354450) {
    printf_low("%s:There is no DECI5S signature.\n","deci5s_context_handle_packet");
    printf_low("%s:Enable SKIP mode.\n","deci5s_context_handle_packet");
LAB_0010c254:
    dc->dc_result = dc->dc_result | 2;
    return -1;
  }
  iVar4 = piVar10[5];
  if (iVar4 + 0xeffefe00U < 2) {
    iVar4 = 0x10;
  }
  else if (iVar4 + 0xdffffe00U < 2) {
    iVar4 = 0x20;
  }
  else if (iVar4 == 0x200ffff) {
    iVar4 = 2;
  }
  else {
    printf_low("%s:Unsupport protocol_id  0x%08x\n","deci_header_to_protocol_type_mp4");
    iVar4 = 0;
  }
  uVar11 = dc->dc_mode;
  if (uVar11 == 2) {
    if (iVar4 == 2) {
      iVar4 = deci5s_context_handle_dcmp_packet(dc);
      return iVar4;
    }
    goto LAB_0010c254;
  }
  if (uVar11 != 1) {
    printf_low("%s:unsupport mode 0x%08x\n","deci5s_context_handle_packet",(ulong)uVar11);
    return -1;
  }
  if (iVar4 == 0x20) {
    local_b8.dsc_cmd = (SceDeci5sSdbgpCmd *)dc->dc_cmd_ptr;
    local_b8.dsc_res = (SceDeci5sSdbgpRes *)dc->dc_res_ptr;
    local_b8.dsc_cmd_sdbgp = &(local_b8.dsc_cmd)->sdbgp;
    pSVar9 = local_b8.dsc_cmd + 1;
    uVar8 = 0x40;
    local_b8.dsc_res_command = (SceDeci5sSdbgpCommand *)0x0;
    local_b8.dsc_res_info = (uint8_t *)0x0;
    uVar12 = 0x18;
    local_b8.dsc_cmd_spec = (deci5s_sdbgp_command_spec_t *)0x0;
    local_b8.dsc_res_sdbgp = &(local_b8.dsc_res)->sdbgp;
    dc->dc_res_data_size = 0x40;
    local_b8.dsc_dc = dc;
    local_b8.dsc_cmd_deci5s = (SceDeci5sHeader *)local_b8.dsc_cmd;
    local_b8.dsc_res_deci5s = (SceDeci5sHeader *)local_b8.dsc_res;
    for (uVar11 = 0; local_b8.dsc_cmd_command = (SceDeci5sSdbgpCommand *)pSVar9,
        uVar11 < (local_b8.dsc_cmd_sdbgp)->n_command; uVar11 = uVar11 + 1) {
      pdVar3 = (deci5s_sdbgp_command_spec_t *)&g_dev_context_el3_core1.dc_dev_context_el2;
      do {
        pdVar7 = pdVar3;
        pdVar3 = pdVar7 + 1;
      } while (pdVar7[1].dscs_type != 0x1ffffff &&
               pdVar7[1].dscs_type != (pSVar9->deci5s).packet_size);
      if (pdVar7[1].dscs_func == readElement<unsigned_int>) {
        uVar5 = mp4_get_cpu();
        printf_low("%d:%s:TODO: Unsupport Error: 0x%08x\n",(ulong)uVar5,
                   "deci5s_context_handle_sdbgp_packet",(ulong)(pSVar9->deci5s).packet_size);
        iVar4 = deci5s_sdbgp_context_alloc_res_command_common(&local_b8,0x2010001,0x20);
        if (iVar4 == 0) {
          local_b8.dsc_res_command[1].self_size = 0x10;
          local_b8.dsc_res_command[1].total_size = 0;
        }
      }
      else {
        local_b8.dsc_cmd_spec = pdVar7 + 1;
        (*pdVar7[1].dscs_func)(&local_b8);
      }
      uVar8 = (local_b8.dsc_res_command)->total_size + uVar8;
      uVar12 = (local_b8.dsc_res_command)->total_size + uVar12;
      pSVar9 = (SceDeci5sSdbgpCmd *)
               ((long)&((SceDeci5sHeader *)&(local_b8.dsc_cmd_command)->self_size)->signature +
               (ulong)((SceDeci5sHeader *)&(local_b8.dsc_cmd_command)->self_size)->self_size);
      local_b8.dsc_res_command =
           (SceDeci5sSdbgpCommand *)
           ((long)&(local_b8.dsc_res_command)->self_size +
           (ulong)(local_b8.dsc_res_command)->total_size);
    }
    uVar1 = (local_b8.dsc_cmd_sdbgp)->sequence_no;
    (local_b8.dsc_res_sdbgp)->self_size = 0x18;
    (local_b8.dsc_res_sdbgp)->total_size = uVar12;
    (local_b8.dsc_res_sdbgp)->sequence_no = uVar1;
    (local_b8.dsc_res_sdbgp)->packet_no = 0;
    (local_b8.dsc_res_sdbgp)->attr = 1;
    (local_b8.dsc_res_sdbgp)->n_command = uVar11;
    deci5s_header_init_p_cmd(local_b8.dsc_res_deci5s,uVar8,local_b8.dsc_cmd_deci5s);
    uVar12 = dc->dc_result;
    dc->dc_res_data_size = uVar8;
  }
  else {
    if (iVar4 != 0x10) {
      if (iVar4 == 2) {
        iVar4 = deci5s_context_handle_dcmp_packet(dc);
      }
      else {
        printf_low("%s:unsupport protocol type 0x%08x\n","deci5s_context_handle_packet");
        iVar4 = -1;
      }
      goto LAB_0010c514;
    }
    cmd = (SceDeci5sHeader *)dc->dc_cmd_ptr;
    p = (SceDeci5sHeader *)dc->dc_res_ptr;
    strncpy((char *)&p[2].attr,(char *)&cmd[2].attr,(ulong)cmd[2].src);
    uVar8 = cmd[2].src + 0x68;
    deci5s_header_init_p_cmd(p,uVar8,cmd);
    uVar1 = cmd[2].self_size;
    uVar2 = cmd[2].packet_size;
    uVar12 = cmd[2].src;
    p[1].dst = 0;
    p[1].protocol_id = 0;
    p[1].attr = 0;
    p[1].user_data = 0;
    p[1].timestamp = 0;
    p[1].signature = 0x40;
    p[1].self_size = 1;
    p[1].packet_size = 0;
    p[1].src = 0;
    p[2].signature = 0;
    p[2].self_size = uVar1;
    p[2].packet_size = uVar2;
    p[2].src = uVar12;
    uVar6 = deci5s_timestamp();
    p[2].dst = (int)uVar6;
    p[2].protocol_id = (int)(uVar6 >> 0x20);
    uVar12 = dc->dc_result;
    dc->dc_res_data_size = uVar8;
  }
  iVar4 = 0;
  dc->dc_result = uVar12 | 1;
LAB_0010c514:
  *piVar10 = 0;
  return iVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c538
 * symbol: deci5s_context_handle_dcmp_packet
 * prototype: int deci5s_context_handle_dcmp_packet(deci5s_context_t * dc)
 * body addresses: 532
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_context_handle_dcmp_packet(deci5s_context_t *dc)

{
  u_int uVar1;
  char *file;
  char *func;
  deci5s_ch_fix_t *pdVar2;
  deci5s_ch_ring_t *pdVar3;
  uint uVar4;
  uint8_t *puVar5;
  SceDeci5sDcmpProtocolInfo *pSVar6;
  
  puVar5 = dc->dc_cmd_ptr;
  switch(*(undefined4 *)(puVar5 + 0x2c)) {
  case 4:
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:(dc %p, cmd %p, dcmp %p)\n",(ulong)uVar1,
               "deci5s_context_handle_dcmp_link_start",dc,puVar5,puVar5 + 0x28);
    if (dc->dc_mode == 2) {
      pdVar3 = dc->dc_ch_ring;
      uVar4 = pdVar3->d5cr_status | 0x40;
LAB_0010c704:
      pdVar3->d5cr_status = uVar4;
      return 0;
    }
    if (dc->dc_mode != 1) {
      file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci5s_mp4.c");
      func = "deci5s_context_handle_dcmp_link_start";
      uVar1 = 0x2fe;
LAB_0010c730:
      deci5s_assert(file,func,uVar1,0,"0");
      return 0;
    }
    pdVar2 = dc->dc_ch_fix;
    uVar4 = pdVar2->d5cf_status | 0x40;
    break;
  case 5:
    pdVar2 = dc->dc_ch_fix;
    uVar4 = pdVar2->d5cf_status & 0xffffff0f;
    break;
  default:
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:UNKNOWN code = 0x%08x\n",(ulong)uVar1,"deci5s_context_handle_dcmp_packet",
               (ulong)*(uint *)(puVar5 + 0x2c));
    return -1;
  case 8:
    pSVar6 = (SceDeci5sDcmpProtocolInfo *)(puVar5 + 0x38);
    for (uVar4 = 0; uVar4 < *(uint *)(puVar5 + 0x34); uVar4 = uVar4 + 1) {
      deci5s_dcmp_protocol_info_print(pSVar6);
      pSVar6 = pSVar6 + 1;
    }
    if (dc->dc_mode == 2) {
      pdVar3 = dc->dc_ch_ring;
      uVar4 = pdVar3->d5cr_status | 0x200;
      goto LAB_0010c704;
    }
    if (dc->dc_mode != 1) {
      file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci5s_mp4.c");
      func = "deci5s_context_handle_dcmp_protocol_start";
      uVar1 = 0x32f;
      goto LAB_0010c730;
    }
    pdVar2 = dc->dc_ch_fix;
    uVar4 = pdVar2->d5cf_status | 0x200;
    break;
  case 9:
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:self_size  0x%08x\n",(ulong)uVar1,"deci5s_context_handle_dcmp_protocol_stop",
               (ulong)*(uint *)(puVar5 + 0x30));
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:count      0x%08x\n",(ulong)uVar1,"deci5s_context_handle_dcmp_protocol_stop",
               (ulong)*(uint *)(puVar5 + 0x34));
    pSVar6 = (SceDeci5sDcmpProtocolInfo *)(puVar5 + 0x38);
    for (uVar4 = 0; uVar4 < *(uint *)(puVar5 + 0x34); uVar4 = uVar4 + 1) {
      deci5s_dcmp_protocol_info_print(pSVar6);
      pSVar6 = pSVar6 + 1;
    }
    pdVar2 = dc->dc_ch_fix;
    uVar4 = pdVar2->d5cf_status & 0xfffff0ff;
  }
  pdVar2->d5cf_status = uVar4;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c74c
 * symbol: deci5s_mp4_start
 * prototype: int deci5s_mp4_start(uint32_t core)
 * body addresses: 676
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_mp4_start(uint32_t core)

{
  uint uVar1;
  uint32_t core_00;
  u_int uVar2;
  deci5s_ch_fix_t *d5cf;
  SceDeci5sHeader *pSVar3;
  
  deci_shm_mp4_start(core);
  deci_target_mp4_start(core);
  if (core == 0) {
    d5cf = &g_d5cf_core0;
    g_d5cf_core0.d5cf_low = deci_target_mp4_get_ch_fix(g_d5cf_core0.d5cf_id);
    (g_d5cf_core0.d5cf_low)->dtcf_d5cf = &g_d5cf_core0;
    core_00 = 0;
    g_d5s.d5s_ch_fix[0] = &g_d5cf_core0;
    g_d5s.d5s_ch_ring[0] = (deci5s_ch_ring_t *)0x0;
  }
  else {
    d5cf = &g_d5cf_core1;
    g_d5cf_core1.d5cf_low = deci_target_mp4_get_ch_fix(g_d5cf_core1.d5cf_id);
    (g_d5cf_core1.d5cf_low)->dtcf_d5cf = &g_d5cf_core1;
    g_d5s.d5s_ch_fix[1] = &g_d5cf_core1;
    g_d5s.d5s_ch_ring[1] = (deci5s_ch_ring_t *)0x0;
    core_00 = core;
  }
  deci_target_mp4_up(core_00);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:WAIT OPEN bit=0x%08x, 0x%08x\n",(ulong)uVar2,"deci5s_mp4_start",
             (ulong)d5cf->d5cf_low->dtcf_sig_bit_c2t,(ulong)d5cf->d5cf_sig_bit);
  do {
  } while ((d5cf->d5cf_status >> 1 & 1) == 0);
  msi_send_command_sync(core,0x10040000);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:=====================================================\n",(ulong)uVar2,
             "deci5s_mp4_start");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:LINK CONNECT\n",(ulong)uVar2,"deci5s_mp4_start");
  pSVar3 = (SceDeci5sHeader *)d5cf->d5cf_low->dtcf_t2c_cmd_buf_ptr;
  bzero(pSVar3,0x40);
  deci5s_header_init_psdp(pSVar3,0x40,d5cf->d5cf_node,0x40ff0100,0x200ffff);
  pSVar3[1].dst = 0;
  pSVar3[1].signature = 8;
  pSVar3[1].self_size = 2;
  pSVar3[1].packet_size = 0x10;
  pSVar3[1].src = 0;
  deci5s_ch_fix_send_request(d5cf,0x40,0);
  do {
  } while ((d5cf->d5cf_status >> 6 & 1) == 0);
  msi_send_command_sync(core,0x10050000);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:=====================================================\n",(ulong)uVar2,
             "deci5s_mp4_start");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:PROTOCOL REGISTER\n",(ulong)uVar2,"deci5s_mp4_start");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:(d5cf %p[%d])\n",(ulong)uVar2,"deci5s_ch_fix_send_dcmp_protocol",d5cf,
             (ulong)d5cf->d5cf_id);
  pSVar3 = (SceDeci5sHeader *)d5cf->d5cf_low->dtcf_t2c_cmd_buf_ptr;
  bzero(pSVar3,0x68);
  deci5s_header_init_psdp(pSVar3,0x68,d5cf->d5cf_node,0x40ff0100,0x200ffff);
  pSVar3[1].signature = 8;
  pSVar3[1].self_size = 6;
  pSVar3[1].packet_size = 8;
  pSVar3[1].src = 2;
  uVar1 = d5cf->d5cf_id;
  pSVar3[1].attr = 1;
  pSVar3[1].user_data = 1;
  pSVar3[1].timestamp = 1;
  pSVar3[2].packet_size = 1;
  pSVar3[2].src = 1;
  pSVar3[2].dst = 1;
  pSVar3[2].protocol_id = 0;
  pSVar3[1].dst = 0x18;
  pSVar3[1].protocol_id = uVar1 | 0x20000200;
  pSVar3[2].signature = 0x18;
  pSVar3[2].self_size = uVar1 | 0x10010200;
  deci5s_ch_fix_send_request(d5cf,0x68,0);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:SKIP WAITING PROTOCOL_START\n",(ulong)uVar2,"deci5s_mp4_start");
  msi_send_command_sync(core,0x10060000);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:<-0\n",(ulong)uVar2,"deci5s_mp4_start");
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010c9f0
 * symbol: deci5s_send_sttyp
 * prototype: int deci5s_send_sttyp(char * msg, uint64_t len)
 * body addresses: 532
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_send_sttyp(char *msg,uint64_t len)

{
  uint uVar1;
  deci5s_ch_fix_t *d5cf;
  uint uVar2;
  uint32_t uVar3;
  u_int uVar4;
  size_t sVar5;
  uint64_t uVar6;
  ulong uVar7;
  long lVar8;
  undefined8 *__s;
  int iVar9;
  deci_target_ch_fix_t *pdVar10;
  uint uVar11;
  
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:(msg %p, len 0x%08x)\n",(ulong)uVar4,"deci5s_send_sttyp",msg,len);
  uVar4 = mp4_get_cpu();
  d5cf = &g_d5cf_core0;
  if (uVar4 != 0) {
    d5cf = &g_d5cf_core1;
  }
  pdVar10 = d5cf->d5cf_low;
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:[%c - %c - %c - %c] %d\n",(ulong)uVar4,"deci5s_send_sttyp",(ulong)(byte)*msg,
             (ulong)(byte)msg[1],(ulong)(byte)msg[2],(ulong)(byte)msg[3],(ulong)pdVar10->dtcf_id);
  uVar11 = 0;
  while ((*pdVar10->dtcf_t2c_cmd_status_ptr & 0xfffff) != 2) {
    if (0xf0000000 < uVar11) {
      uVar4 = mp4_get_cpu();
      printf_low("%d:%s:TIMEOUT\n",(ulong)uVar4,"deci5s_send_sttyp");
    }
    uVar11 = uVar11 + 1;
  }
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:->deci5s_ch_fix_send_sttyp()\n",(ulong)uVar4,"deci5s_send_sttyp");
  __s = (undefined8 *)d5cf->d5cf_low->dtcf_t2c_cmd_buf_ptr;
  sVar5 = strnlen(msg,0x80);
  iVar9 = (int)sVar5;
  uVar1 = iVar9 + 7U & 0xfffffff8;
  uVar11 = uVar1 + 0x68;
  bzero(__s,(ulong)uVar11);
  *__s = 0x2873354450;
  uVar2 = d5cf->d5cf_id;
  __s[3] = 0;
  *(uint *)(__s + 1) = uVar11;
  *(uint *)((long)__s + 0xc) = uVar2 | 0x80ff0200;
  *(undefined4 *)(__s + 2) = 0x20ffffff;
  *(uint *)((long)__s + 0x14) = uVar2 | 0x10010200;
  uVar6 = deci5s_timestamp();
  uVar2 = d5cf->d5cf_id;
  __s[4] = uVar6;
  __s[6] = 0;
  __s[7] = 0;
  __s[8] = 0;
  __s[9] = 0;
  uVar3 = g_d5s_sttyp.d5ss_seq_no;
  *(int *)(__s + 0xb) = iVar9;
  *(uint *)((long)__s + 0x5c) = uVar1;
  *(undefined4 *)(__s + 5) = 0x40;
  *(uint *)((long)__s + 0x2c) = uVar2 | 0x83020100;
  *(undefined4 *)(__s + 10) = 0;
  *(uint32_t *)((long)__s + 0x54) = uVar3;
  uVar6 = deci5s_timestamp();
  __s[0xc] = uVar6;
  uVar7 = sVar5 & 0xffffffff;
  for (lVar8 = 0; iVar9 != (int)lVar8; lVar8 = lVar8 + 1) {
    *(char *)((long)__s + lVar8 + 0x68) = msg[lVar8];
  }
  for (; (uint)uVar7 < uVar1; uVar7 = uVar7 + 1) {
    *(undefined *)((long)__s + uVar7 + 0x68) = 0;
  }
  g_d5s_sttyp.d5ss_seq_no = g_d5s_sttyp.d5ss_seq_no + 1;
  deci5s_ch_fix_send_request(d5cf,uVar11,(uint)(byte)*msg);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010cc04
 * symbol: deci5s_mp4_panic_and_loop
 * prototype: int deci5s_mp4_panic_and_loop(uint32_t cpu, uint64_t pc)
 * body addresses: 440
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_mp4_panic_and_loop(uint32_t cpu,uint64_t pc)

{
  uint uVar1;
  deci5s_ch_fix_t *d5cf;
  uint32_t uVar2;
  int iVar3;
  uint32_t command;
  uint32_t bits;
  SceDeci5sHeader *pSVar4;
  
  d5cf = &g_d5cf_core0;
  if (cpu != 0) {
    d5cf = &g_d5cf_core1;
  }
  pSVar4 = (SceDeci5sHeader *)d5cf->d5cf_low->dtcf_t2c_cmd_buf_ptr;
  bzero(pSVar4,0x78);
  deci5s_header_init_psdp(pSVar4,0x78,d5cf->d5cf_node,0x20ff0100,d5cf->d5cf_sdbgp);
  pSVar4[1].timestamp = 0x4021001;
  pSVar4[2].signature = 0;
  pSVar4[2].self_size = 0;
  pSVar4[2].packet_size = 0x11111111;
  pSVar4[2].src = 0;
  pSVar4[2].dst = 0;
  pSVar4[2].protocol_id = 0;
  pSVar4[2].attr = (int)pc;
  pSVar4[2].user_data = (int)(pc >> 0x20);
  pSVar4[2].timestamp = 0;
  pSVar4[1].signature = 0x18;
  pSVar4[1].self_size = 0x50;
  pSVar4[1].packet_size = 0;
  pSVar4[1].src = 0;
  pSVar4[1].dst = 0;
  pSVar4[1].protocol_id = 1;
  pSVar4[1].attr = 0x38;
  pSVar4[1].user_data = 0x38;
  deci5s_ch_fix_send_request(d5cf,0x78,0);
  d5cf->d5cf_status = d5cf->d5cf_status | 0x10000;
  if ((deci5s_mp4_loop_first & 1) == 0) {
    g_d5s.d5s_ch_fix[cpu] = d5cf;
    deci5s_mp4_loop_first = 1;
  }
  while( true ) {
    do {
      uVar2 = g_d5s.d5s_status;
      iVar3 = msi_wait_command(cpu);
    } while (iVar3 < 0);
    command = msi_read_c2p_command(cpu);
    bits = msi_read_c2p_arg1(cpu);
    deci_target_mp4_intr_with_cpu(cpu,bits);
    msi_write_c2p_ack(cpu,command);
    uVar1 = d5cf->d5cf_status & 0x10000;
    if (((uVar2 & 1) != 0) && (uVar1 == 0)) break;
    if ((uVar1 >> 0xf | 4) != 6) {
      return 0;
    }
  }
  pSVar4 = (SceDeci5sHeader *)d5cf->d5cf_low->dtcf_t2c_cmd_buf_ptr;
  bzero(pSVar4,0x78);
  deci5s_header_init_psdp(pSVar4,0x78,d5cf->d5cf_node,0x20ff0100,d5cf->d5cf_sdbgp);
  pSVar4[1].signature = 0x18;
  pSVar4[1].self_size = 0x50;
  pSVar4[1].packet_size = 0;
  pSVar4[1].src = 0;
  *(undefined8 *)((long)&pSVar4[1].timestamp + 4) = 0;
  pSVar4[2].self_size = 0;
  pSVar4[2].packet_size = 0x11111111;
  pSVar4[2].src = 0;
  pSVar4[2].dst = 0;
  pSVar4[1].dst = 0;
  pSVar4[1].protocol_id = 1;
  pSVar4[1].attr = 0x38;
  pSVar4[1].user_data = 0x38;
  *(undefined4 *)&pSVar4[1].timestamp = 0x4021010;
  pSVar4[2].protocol_id = 0;
  pSVar4[2].attr = 0;
  pSVar4[2].user_data = 0;
  pSVar4[2].timestamp = 0;
  deci5s_ch_fix_send_request(d5cf,0x78,0);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010cdbc
 * symbol: deci5s_context_check_overflow
 * prototype: int deci5s_context_check_overflow(deci5s_context_t * dc, uint32_t csize)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_context_check_overflow(deci5s_context_t *dc,uint32_t csize)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  
  if (dc->dc_res_data_size < dc->dc_res_max) {
    if (csize < dc->dc_res_max - dc->dc_res_data_size) {
      return 1;
    }
    uVar3 = mp4_get_cpu();
    uVar2 = dc->dc_res_max;
    uVar1 = dc->dc_res_data_size + csize;
  }
  else {
    uVar3 = mp4_get_cpu();
    uVar2 = dc->dc_res_max;
    uVar1 = dc->dc_res_data_size;
  }
  printf_low("%d:%s:res_max 0x%08x <= 0x%08x res_data_size\n",(ulong)uVar3,
             "deci5s_context_check_overflow",(ulong)uVar2,(ulong)uVar1);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ce30
 * symbol: deci5s_dcmp_protocol_info_print
 * prototype: void deci5s_dcmp_protocol_info_print(SceDeci5sDcmpProtocolInfo * info)
 * body addresses: 204
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci5s_dcmp_protocol_info_print(SceDeci5sDcmpProtocolInfo *info)

{
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:self_size             0x%08x:0x%08lx\n",(ulong)uVar1,
             "deci5s_dcmp_protocol_info_print",(ulong)info->self_size,0x18);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:protocolNumber        0x%08x\n",(ulong)uVar1,"deci5s_dcmp_protocol_info_print",
             (ulong)info->protocolNumber);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:protocolVersion       0x%08x\n",(ulong)uVar1,"deci5s_dcmp_protocol_info_print",
             (ulong)info->protocolVersion);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:protocolVersionLimit  0x%08x\n",(ulong)uVar1,"deci5s_dcmp_protocol_info_print",
             (ulong)info->protocolVersionLimit);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:targetStatus          0x%08x\n",(ulong)uVar1,"deci5s_dcmp_protocol_info_print",
             (ulong)info->targetStatus);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:hostStatus            0x%08x\n",(ulong)uVar1,"deci5s_dcmp_protocol_info_print",
             (ulong)info->hostStatus);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010cefc
 * symbol: deci5s_header_init_p_cmd
 * prototype: void deci5s_header_init_p_cmd(SceDeci5sHeader * p, uint32_t psize, SceDeci5sHeader * cmd)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci5s_header_init_p_cmd(SceDeci5sHeader *p,uint32_t psize,SceDeci5sHeader *cmd)

{
  deci5s_header_init_psdp(p,psize,cmd->dst,cmd->src,cmd->protocol_id);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010cf10
 * symbol: deci5s_header_init_psdp
 * prototype: void deci5s_header_init_psdp(SceDeci5sHeader * deci5s, uint32_t packet_size, uint32_t src, uint32_t dst, uint32_t protocol_id)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void deci5s_header_init_psdp
               (SceDeci5sHeader *deci5s,uint32_t packet_size,uint32_t src,uint32_t dst,
               uint32_t protocol_id)

{
  uint64_t uVar1;
  
  deci5s->signature = 0x73354450;
  deci5s->self_size = 0x28;
  deci5s->packet_size = packet_size;
  deci5s->src = src;
  deci5s->dst = dst;
  deci5s->protocol_id = protocol_id;
  deci5s->attr = 0;
  deci5s->user_data = 0;
  uVar1 = deci5s_timestamp();
  deci5s->timestamp = uVar1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010cf60
 * symbol: deci5s_timestamp
 * prototype: uint64_t deci5s_timestamp(void)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t deci5s_timestamp(void)

{
  uint32_t uVar1;
  
  uVar1 = mp4_timer_get_cnt(0);
  return (ulong)uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010cf7c
 * symbol: deci5s_sdbgp_context_handle_get_conf
 * prototype: int deci5s_sdbgp_context_handle_get_conf(deci5s_sdbgp_context_t * dsc)
 * body addresses: 744
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_get_conf(deci5s_sdbgp_context_t *dsc)

{
  uint16_t uVar1;
  u_int uVar2;
  uint uVar3;
  uint32_t uVar4;
  long lVar5;
  undefined8 *puVar6;
  deci_target_ch_fix_t *pdVar7;
  deci5s_ch_ring_t *pdVar8;
  uint uVar9;
  uint *puVar10;
  deci5s_t *pdVar11;
  undefined8 *puVar12;
  
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:(dsc %p)\n",(ulong)uVar2,"deci5s_sdbgp_context_handle_get_conf",dsc);
  pdVar11 = dsc->dsc_dc->dc_d5s;
  uVar3 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar3 == 0) {
    uVar3 = deci5s_sdbgp_context_alloc_res_info(dsc,0x38);
    if (uVar3 == 0) {
      puVar12 = (undefined8 *)dsc->dsc_res_info;
      *puVar12 = 0x5020200000038;
      puVar12[1] = 0x2000000b7;
      *(undefined4 *)(puVar12 + 2) = 2;
      uVar4 = msi_get_msi_address32();
      *(uint32_t *)((long)puVar12 + 0x14) = uVar4;
      uVar1 = msi_get_vector_for_mm();
      *(uint *)(puVar12 + 3) = (uint)uVar1;
      uVar1 = msi_get_vector_for_io();
      *(uint *)((long)puVar12 + 0x1c) = (uint)uVar1;
      uVar1 = msi_get_vector_1st_core();
      *(uint *)(puVar12 + 4) = (uint)uVar1;
      uVar1 = msi_get_vector_2nd_core();
      *(uint *)((long)puVar12 + 0x24) = (uint)uVar1;
      for (lVar5 = 0; lVar5 != 0x10; lVar5 = lVar5 + 4) {
        *(undefined4 *)((long)puVar12 + lVar5 + 0x28) = 0;
      }
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:BUILD-ID: ID_SIZE:   0x%08x\n",(ulong)uVar2,
                 "deci5s_sdbgp_context_handle_get_conf",4);
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:BUILD-ID: HASH_SIZE: 0x%08x\n",(ulong)uVar2,
                 "deci5s_sdbgp_context_handle_get_conf",0x10);
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:BUILD-ID: TYPE:      0x%08x\n",(ulong)uVar2,
                 "deci5s_sdbgp_context_handle_get_conf",3);
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:BUILD-ID: ID:        0x%08x\n",(ulong)uVar2,
                 "deci5s_sdbgp_context_handle_get_conf",0x554e47);
      uVar3 = 0;
      for (puVar10 = &DAT_00114c50; puVar10 < &__loader_el3_text_end; puVar10 = puVar10 + 1) {
        uVar2 = mp4_get_cpu();
        printf_low("%d:%s:BUILD-ID: %p=0x%08x\n",(ulong)uVar2,"deci5s_sdbgp_context_handle_get_conf"
                   ,puVar10,(ulong)*puVar10);
        if (uVar3 < 4) {
          *(uint *)((long)puVar12 + (ulong)uVar3 * 4 + 0x28) = *puVar10;
        }
        uVar3 = uVar3 + 1;
      }
      for (uVar9 = 0; uVar9 < *(uint *)((long)puVar12 + 0xc); uVar9 = uVar9 + 1) {
        uVar3 = deci5s_sdbgp_context_alloc_res_info(dsc,0x18);
        if (uVar3 != 0) goto LAB_0010d22c;
        puVar6 = (undefined8 *)dsc->dsc_res_info;
        *puVar6 = 0x18;
        pdVar7 = (deci_target_ch_fix_t *)pdVar11->d5s_ch_fix[uVar9];
        if ((pdVar7 == (deci_target_ch_fix_t *)0x0) ||
           (pdVar7 = (deci_target_ch_fix_t *)pdVar7->dtcf_write_count,
           pdVar7 == (deci_target_ch_fix_t *)0x0)) {
          uVar4 = (uint32_t)pdVar7;
          puVar6[1] = 0;
          *(undefined4 *)(puVar6 + 2) = 0;
        }
        else {
          *(uint32_t *)(puVar6 + 1) = pdVar7->dtcf_c2t_cmd_buf_size;
          *(uint32_t *)((long)puVar6 + 0xc) = pdVar7->dtcf_c2t_res_buf_size;
          *(uint32_t *)(puVar6 + 2) = pdVar7->dtcf_t2c_cmd_buf_size;
          uVar4 = pdVar7->dtcf_t2c_res_buf_size;
        }
        *(uint32_t *)((long)puVar6 + 0x14) = uVar4;
      }
      for (uVar9 = 0; uVar9 < *(uint *)(puVar12 + 2); uVar9 = uVar9 + 1) {
        uVar3 = deci5s_sdbgp_context_alloc_res_info(dsc,0x18);
        if (uVar3 != 0) goto LAB_0010d22c;
        puVar6 = (undefined8 *)dsc->dsc_res_info;
        *puVar6 = 0x18;
        pdVar8 = pdVar11->d5s_ch_ring[uVar9];
        if (pdVar8 != (deci5s_ch_ring_t *)0x0) {
          pdVar8 = (deci5s_ch_ring_t *)(ulong)pdVar8->d5cr_t2c_cmd_buf_size;
        }
        *(int *)(puVar6 + 2) = (int)pdVar8;
        *(undefined4 *)((long)puVar6 + 0x14) = 0;
        puVar6[1] = 0;
      }
      uVar3 = 0;
    }
    else {
LAB_0010d22c:
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_info() failed\n",(ulong)uVar2,
                 "deci5s_sdbgp_context_handle_get_conf");
    }
  }
  else {
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_get_conf",(ulong)uVar3);
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d264
 * symbol: deci5s_sdbgp_context_handle_get_reg
 * prototype: int deci5s_sdbgp_context_handle_get_reg(deci5s_sdbgp_context_t * dsc)
 * body addresses: 312
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_get_reg(deci5s_sdbgp_context_t *dsc)

{
  uint32_t uVar1;
  uint32_t uVar2;
  u_int uVar3;
  uint uVar4;
  uint uVar5;
  uint64_t uVar6;
  char *format;
  ulong uVar7;
  uint32_t uVar8;
  undefined4 *puVar9;
  long lVar10;
  SceDeci5sSdbgpCommand *pSVar11;
  SceDeci5sSdbgpCommand *pSVar12;
  
  uVar3 = mp4_get_cpu();
  printf_low("%d:%s:(dsc %p)\n",(ulong)uVar3,"deci5s_sdbgp_context_handle_get_reg",dsc);
  uVar4 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar4 == 0) {
    pSVar11 = dsc->dsc_cmd_command;
    pSVar12 = dsc->dsc_res_command;
    uVar1 = pSVar11[1].self_size;
    uVar2 = pSVar11[1].total_size;
    uVar8 = pSVar11[1].type;
    pSVar12->type = 0x2050020;
    pSVar12[1].self_size = uVar1;
    pSVar12[1].total_size = uVar2;
    pSVar12[1].type = uVar8;
    pSVar12[1].flags = 0;
    for (lVar10 = 0; (uint)lVar10 < uVar8; lVar10 = lVar10 + 1) {
      uVar4 = deci5s_sdbgp_context_alloc_res_info(dsc,0x18);
      if (uVar4 != 0) {
        uVar5 = mp4_get_cpu();
        format = "%d:%s:deci5s_sdbgp_context_alloc_res_info(size 0x%08x) failed\n";
        uVar7 = 0x18;
        goto LAB_0010d37c;
      }
      puVar9 = (undefined4 *)dsc->dsc_res_info;
      *puVar9 = 0x10;
      uVar4 = (&pSVar11[1].command_no)[lVar10];
      *(undefined8 *)(puVar9 + 2) = 0x800000000;
      puVar9[1] = uVar4;
      uVar6 = mp4_debug_status_get_reg(uVar4 & 0xffff);
      uVar1 = pSVar12[1].flags;
      uVar8 = pSVar11[1].type;
      *(uint64_t *)(puVar9 + 4) = uVar6;
      pSVar12[1].flags = uVar1 + 1;
    }
    uVar4 = 0;
  }
  else {
    uVar5 = mp4_get_cpu();
    format = "%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n";
    uVar7 = (ulong)uVar4;
LAB_0010d37c:
    printf_low(format,(ulong)uVar5,"deci5s_sdbgp_context_handle_get_reg",uVar7);
  }
  return uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d39c
 * symbol: deci5s_sdbgp_context_handle_get_backtrace
 * prototype: int deci5s_sdbgp_context_handle_get_backtrace(deci5s_sdbgp_context_t * dsc)
 * body addresses: 368
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_get_backtrace(deci5s_sdbgp_context_t *dsc)

{
  undefined8 *puVar1;
  ulong uVar2;
  undefined8 uVar3;
  undefined8 *puVar4;
  bool bVar5;
  uint uVar6;
  u_int uVar7;
  int iVar8;
  undefined8 *puVar9;
  SceDeci5sSdbgpCommand *pSVar10;
  undefined8 *puVar11;
  aarch64_frame_t local_68;
  
  uVar6 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar6 == 0) {
    pSVar10 = dsc->dsc_res_command;
    pSVar10[1].self_size = 0;
    pSVar10[1].total_size = 0;
    pSVar10[1].type = 1;
    pSVar10[1].flags = 0;
    iVar8 = deci5s_sdbgp_context_alloc_res_info(dsc,0x18);
    if (iVar8 == 0) {
      puVar11 = (undefined8 *)dsc->dsc_res_info;
      *puVar11 = 0x18;
      puVar11[1] = 0;
      puVar11[2] = 0;
      pSVar10[1].flags = pSVar10[1].flags + 1;
      iVar8 = mp4_debug_status_get_frame(&local_68);
      aarch64_read_ELR_EL1(iVar8);
      uVar2 = spsr_el3;
      bVar5 = (uVar2 & 0x1f) == 0;
      for (uVar6 = 0; uVar6 < 0x20; uVar6 = uVar6 + 1) {
        if (bVar5) {
          uVar3 = AT_S1E1R(local_68.af_pc);
          par_el1 = uVar3;
          uVar2 = par_el1;
          if ((uVar2 & 1) != 0) {
            bVar5 = false;
          }
        }
        iVar8 = deci5s_sdbgp_context_alloc_res_info(dsc,0x20);
        puVar4 = (undefined8 *)local_68.af_fp;
        if (iVar8 == 0) {
          puVar9 = (undefined8 *)dsc->dsc_res_info;
          puVar1 = puVar11 + 2;
          if (bVar5) {
            puVar1 = (undefined8 *)((long)puVar11 + 0x14);
          }
          *puVar9 = 0x1000000000020;
          puVar9[1] = local_68.af_sp;
          puVar9[2] = local_68.af_pc;
          puVar9[3] = 0;
          *(int *)puVar1 = *(int *)puVar1 + 1;
        }
        if (bVar5) {
          local_68.af_fp = (uint64_t)el0_va_to_el3_va((uint8_t *)local_68.af_fp);
        }
        uVar3 = AT_S1E3R(local_68.af_fp);
        par_el1 = uVar3;
        uVar2 = par_el1;
        if ((uVar2 & 1) != 0) break;
        local_68.af_sp = (uint64_t)(puVar4 + 2);
        local_68.af_pc = *(long *)(local_68.af_fp + 8) - 4;
        local_68.af_fp = (uint64_t)*(undefined8 **)local_68.af_fp;
      }
    }
    uVar6 = 0;
  }
  else {
    uVar7 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar7,
               "deci5s_sdbgp_context_handle_get_backtrace",(ulong)uVar6);
  }
  return uVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d50c
 * symbol: deci5s_sdbgp_context_handle_address_translation
 * prototype: int deci5s_sdbgp_context_handle_address_translation(deci5s_sdbgp_context_t * dsc)
 * body addresses: 312
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_address_translation(deci5s_sdbgp_context_t *dsc)

{
  u_int uVar1;
  uint uVar2;
  undefined8 uVar3;
  SceDeci5sSdbgpCommand *pSVar4;
  SceDeci5sSdbgpCommand *pSVar5;
  undefined8 uVar6;
  
  pSVar5 = dsc->dsc_cmd_command;
  uVar1 = mp4_get_cpu();
  uVar3._0_4_ = pSVar5[1].self_size;
  uVar3._4_4_ = pSVar5[1].total_size;
  printf_low("%d:%s:cmd_command->virtual_address = 0x%016lx\n",(ulong)uVar1,
             "deci5s_sdbgp_context_handle_address_translation",uVar3);
  uVar2 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar2 == 0) {
    pSVar4 = dsc->dsc_res_command;
    uVar6._0_4_ = pSVar5[1].self_size;
    uVar6._4_4_ = pSVar5[1].total_size;
    pSVar4[1].self_size = (int)uVar6;
    pSVar4[1].total_size = (int)((ulong)uVar6 >> 0x20);
    pSVar4[1].type = 0;
    pSVar4[1].flags = 0;
    uVar3 = AT_S1E0R(uVar6);
    par_el1 = uVar3;
    uVar3 = par_el1;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:aarch64_AT_S1E0R = 0x%016lx\n",(ulong)uVar1,
               "deci5s_sdbgp_context_handle_address_translation",uVar3);
    pSVar4[1].command_no = (int)uVar3;
    pSVar4[1].packet_no = (int)((ulong)uVar3 >> 0x20);
    uVar3 = AT_S1E1W(uVar6);
    par_el1 = uVar3;
    uVar3 = par_el1;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:aarch64_AT_S1E0W = 0x%016lx\n",(ulong)uVar1,
               "deci5s_sdbgp_context_handle_address_translation",uVar3);
    pSVar4[2].self_size = (int)uVar3;
    pSVar4[2].total_size = (int)((ulong)uVar3 >> 0x20);
    uVar3 = AT_S1E3R(uVar6);
    par_el1 = uVar3;
    uVar3 = par_el1;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:aarch64_AT_S1E3R = 0x%016lx\n",(ulong)uVar1,
               "deci5s_sdbgp_context_handle_address_translation",uVar3);
    pSVar4[2].type = (int)uVar3;
    pSVar4[2].flags = (int)((ulong)uVar3 >> 0x20);
    uVar3 = AT_S1E3W(uVar6);
    par_el1 = uVar3;
    uVar3 = par_el1;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:aarch64_AT_S1E3W = 0x%016lx\n",(ulong)uVar1,
               "deci5s_sdbgp_context_handle_address_translation",uVar3);
    uVar2 = 0;
    pSVar4[2].command_no = (int)uVar3;
    pSVar4[2].packet_no = (int)((ulong)uVar3 >> 0x20);
  }
  else {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar1,
               "deci5s_sdbgp_context_handle_address_translation",(ulong)uVar2);
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d644
 * symbol: deci5s_sdbgp_context_handle_get_mmu
 * prototype: int deci5s_sdbgp_context_handle_get_mmu(deci5s_sdbgp_context_t * dsc)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_get_mmu(deci5s_sdbgp_context_t *dsc)

{
  undefined8 uVar1;
  uint uVar2;
  u_int uVar3;
  SceDeci5sSdbgpCommand *pSVar4;
  
  uVar2 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar2 == 0) {
    pSVar4 = dsc->dsc_res_command;
    pSVar4[1].self_size = 0;
    pSVar4[1].total_size = 0;
    uVar1 = mair_el3;
    pSVar4[1].command_no = (int)uVar1;
    pSVar4[1].packet_no = (int)((ulong)uVar1 >> 0x20);
  }
  else {
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar3,
               "deci5s_sdbgp_context_handle_get_mmu",(ulong)uVar2);
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d6a8
 * symbol: deci5s_sdbgp_context_handle_get_pmu
 * prototype: int deci5s_sdbgp_context_handle_get_pmu(deci5s_sdbgp_context_t * dsc)
 * body addresses: 528
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Type propagation algorithm not settling */
/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_get_pmu(deci5s_sdbgp_context_t *dsc)

{
  ulong uVar1;
  ulong uVar2;
  uint64_t uVar3;
  undefined8 uVar4;
  uint uVar5;
  u_int uVar6;
  SceDeci5sSdbgpMp4PMUCountInfo *pSVar7;
  SceDeci5sSdbgpCommand *pSVar8;
  
  uVar5 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar5 != 0) {
    uVar6 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar6,
               "deci5s_sdbgp_context_handle_get_pmu",(ulong)uVar5);
    return uVar5;
  }
  pSVar8 = dsc->dsc_res_command;
  pSVar8[1].self_size = 0;
  pSVar8[1].total_size = 0;
  uVar1 = pmcntenset_el0;
  uVar5 = (uint)uVar1;
  if ((int)uVar5 < 0) {
    pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc);
    if (pSVar7 == (SceDeci5sSdbgpMp4PMUCountInfo *)0x0) {
      return 0;
    }
    pSVar7->self_size = 0x10;
    pSVar7->type = 0x3ff;
    uVar2 = pmccntr_el0;
    pSVar7->count = uVar2 & 0xffffffff;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
  }
  if ((uVar1 & 1) != 0) {
    pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc);
    if (pSVar7 == (SceDeci5sSdbgpMp4PMUCountInfo *)0x0) {
      return 0;
    }
    pSVar7->self_size = 0x10;
    uVar4 = pmevtyper0_el0;
    pSVar7->type = (uint32_t)uVar4;
    uVar1 = pmevcntr0_el0;
    pSVar7->count = uVar1 & 0xffffffff;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
  }
  if ((uVar5 >> 1 & 1) != 0) {
    pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc);
    if (pSVar7 == (SceDeci5sSdbgpMp4PMUCountInfo *)0x0) {
      return 0;
    }
    pSVar7->self_size = 0x10;
    uVar4 = pmevtyper1_el0;
    pSVar7->type = (uint32_t)uVar4;
    uVar1 = pmevcntr1_el0;
    pSVar7->count = uVar1 & 0xffffffff;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
  }
  if ((uVar5 >> 2 & 1) != 0) {
    pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc);
    if (pSVar7 == (SceDeci5sSdbgpMp4PMUCountInfo *)0x0) {
      return 0;
    }
    pSVar7->self_size = 0x10;
    uVar4 = pmevtyper2_el0;
    pSVar7->type = (uint32_t)uVar4;
    uVar1 = pmevcntr2_el0;
    pSVar7->count = uVar1 & 0xffffffff;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
  }
  if ((uVar5 >> 3 & 1) != 0) {
    pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc);
    if (pSVar7 == (SceDeci5sSdbgpMp4PMUCountInfo *)0x0) {
      return 0;
    }
    pSVar7->self_size = 0x10;
    uVar4 = pmevtyper3_el0;
    pSVar7->type = (uint32_t)uVar4;
    uVar1 = pmevcntr3_el0;
    pSVar7->count = uVar1 & 0xffffffff;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
  }
  if ((uVar5 >> 4 & 1) != 0) {
    pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc);
    if (pSVar7 == (SceDeci5sSdbgpMp4PMUCountInfo *)0x0) {
      return 0;
    }
    pSVar7->self_size = 0x10;
    uVar4 = pmevtyper4_el0;
    pSVar7->type = (uint32_t)uVar4;
    uVar1 = pmevcntr4_el0;
    pSVar7->count = uVar1 & 0xffffffff;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
  }
  if (((uVar5 >> 5 & 1) != 0) &&
     (pSVar7 = deci5s_sdbgp_context_handle_get_pmu_count_info(dsc),
     pSVar7 != (SceDeci5sSdbgpMp4PMUCountInfo *)0x0)) {
    pSVar7->self_size = 0x10;
    uVar4 = pmevtyper5_el0;
    pSVar7->type = (uint32_t)uVar4;
    uVar3 = pmevcntr5_el0;
    pSVar7->count = uVar3;
    pSVar8[1].self_size = pSVar8[1].self_size + 1;
    return 0;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d8b8
 * symbol: deci5s_sdbgp_context_handle_get_syshub_tlb
 * prototype: int deci5s_sdbgp_context_handle_get_syshub_tlb(deci5s_sdbgp_context_t * dsc)
 * body addresses: 252
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_get_syshub_tlb(deci5s_sdbgp_context_t *dsc)

{
  uint uVar1;
  u_int uVar2;
  int iVar3;
  undefined4 *puVar4;
  SceDeci5sSdbgpCommand *pSVar5;
  uint32_t local_50;
  uint32_t local_4c;
  uint32_t local_48;
  uint32_t uStack_44;
  uint32_t local_38;
  uint32_t local_34;
  
  uVar1 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar1 == 0) {
    pSVar5 = dsc->dsc_res_command;
    pSVar5[1].self_size = 0;
    pSVar5[1].total_size = 0;
    for (uVar1 = 1; uVar1 < 0x3f; uVar1 = uVar1 + 1) {
      syshub_tlb_get(uVar1,&local_34,&local_38,&uStack_44,&local_48,&local_4c,&local_50);
      if (local_34 != 0) {
        iVar3 = deci5s_sdbgp_context_alloc_res_info(dsc,0x20);
        if (iVar3 != 0) {
          return iVar3;
        }
        puVar4 = (undefined4 *)dsc->dsc_res_info;
        *puVar4 = 0x20;
        puVar4[1] = uVar1;
        puVar4[2] = local_34;
        puVar4[3] = local_38;
        puVar4[4] = uStack_44;
        puVar4[5] = local_48;
        puVar4[6] = local_4c;
        puVar4[7] = local_50;
        pSVar5[1].self_size = pSVar5[1].self_size + 1;
      }
    }
    uVar1 = 0;
  }
  else {
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_get_syshub_tlb",(ulong)uVar1);
  }
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010d9b4
 * symbol: deci5s_sdbgp_context_handle_test
 * prototype: int deci5s_sdbgp_context_handle_test(deci5s_sdbgp_context_t * dsc)
 * body addresses: 1092
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_handle_test(deci5s_sdbgp_context_t *dsc)

{
  uint32_t uVar1;
  u_int uVar2;
  uint uVar3;
  main_mp4_param_t *pmVar4;
  undefined8 uVar5;
  ulong uVar6;
  uint *puVar7;
  SceDeci5sSdbgpCommand *pSVar8;
  SceDeci5sSdbgpCommand *pSVar9;
  
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar2,"deci5s_sdbgp_context_handle_test");
  uVar3 = deci5s_sdbgp_context_alloc_res_command(dsc);
  if (uVar3 == 0) {
    pSVar8 = dsc->dsc_cmd_command;
    pSVar9 = dsc->dsc_res_command;
    uVar1 = pSVar8[1].self_size;
    pSVar9[1].total_size = 0;
    pSVar9[1].type = 0;
    pSVar9[1].flags = 0;
    pSVar9->type = 0x2ff0001;
    pSVar9[1].self_size = uVar1;
    for (uVar6 = 0; uVar6 != 8; uVar6 = uVar6 + 1) {
      pSVar9[1].total_size = pSVar8[1].total_size;
      if (uVar6 < pSVar8[1].total_size) {
        uVar5 = *(undefined8 *)(&pSVar8[1].command_no + uVar6 * 2);
      }
      else {
        uVar5 = 0;
      }
      *(undefined8 *)(&pSVar9[1].command_no + uVar6 * 2) = uVar5;
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:res_command->arg[%d] = 0x%016lx\n",(ulong)uVar2,
                 "deci5s_sdbgp_context_handle_test",uVar6 & 0xffffffff,
                 *(undefined8 *)(&pSVar9[1].command_no + uVar6 * 2));
    }
    pmVar4 = msi_get_main_param();
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB10                          = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x28000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB10                          = 0x%016lx [IOMMU]\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x54000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mm4p->mm4p_iommu_mmio.mimi_iommu_addr = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(pmVar4->mm4p_iommu_mmio).mimi_iommu_addr);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB11                          = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x2c000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB11                          = 0x%016lx [IOMMU]\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x54000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mm4p->mm4p_sdma0_mmio.mimi_iommu_addr = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(pmVar4->mm4p_sdma0_mmio).mimi_iommu_addr);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB12                          = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x30000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB12                          = 0x%016lx [IOMMU]\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x54000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mm4p->mm4p_sdma1_mmio.mimi_iommu_addr = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(pmVar4->mm4p_sdma1_mmio).mimi_iommu_addr);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB15                          = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x3c000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB15                          = 0x%016lx [BYPASS]\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0xfc000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mm4p->mm4p_iommu_mmio.mini_pa         = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(pmVar4->mm4p_iommu_mmio).mimi_pa);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB16                          = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x40000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB16                          = 0x%016lx [BYPASS]\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x18000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mm4p->mm4p_sdma0_mmio.mimi_pa         = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(pmVar4->mm4p_sdma0_mmio).mimi_pa);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB17                          = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x44000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:SYSHUB_TLB17                          = 0x%016lx [BYPASS]\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",0x18000000);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mm4p->mm4p_sdna1_mmio.mimi_pa         = 0x%016lx\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(pmVar4->mm4p_sdma1_mmio).mimi_pa);
    uVar5._0_4_ = pSVar8[1].command_no;
    uVar5._4_4_ = pSVar8[1].packet_no;
    uVar3 = 0;
    switch(uVar5) {
    case 10:
      uVar2 = mp4_get_cpu();
      uVar6 = (ulong)uVar2;
      puVar7 = (uint *)0x28200018;
      break;
    case 0xb:
      uVar2 = mp4_get_cpu();
      uVar6 = (ulong)uVar2;
      puVar7 = (uint *)0x2c400018;
      break;
    case 0xc:
      uVar2 = mp4_get_cpu();
      uVar6 = (ulong)uVar2;
      puVar7 = (uint *)0x30600018;
      break;
    default:
      goto switchD_0010dcdc_caseD_d;
    case 0xf:
      uVar2 = mp4_get_cpu();
      uVar6 = (ulong)uVar2;
      puVar7 = (uint *)0x3dd88018;
      break;
    case 0x10:
      uVar2 = mp4_get_cpu();
      uVar6 = (ulong)uVar2;
      puVar7 = (uint *)0x40900000;
      break;
    case 0x11:
      uVar2 = mp4_get_cpu();
      uVar6 = (ulong)uVar2;
      puVar7 = (uint *)&DAT_44904000;
    }
    printf_low("%d:%s:p  = %p\n",uVar6,"deci5s_sdbgp_context_handle_test",puVar7);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:*p = 0x%08x\n",(ulong)uVar2,"deci5s_sdbgp_context_handle_test",(ulong)*puVar7)
    ;
    uVar3 = 0;
  }
  else {
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:deci5s_sdbgp_context_alloc_res_command() failed %d\n",(ulong)uVar2,
               "deci5s_sdbgp_context_handle_test",(ulong)uVar3);
  }
switchD_0010dcdc_caseD_d:
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010ddf8
 * symbol: deci5s_sdbgp_context_alloc_res_info
 * prototype: int deci5s_sdbgp_context_alloc_res_info(deci5s_sdbgp_context_t * dsc, uint32_t isize)
 * body addresses: 492
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_alloc_res_info(deci5s_sdbgp_context_t *dsc,uint32_t isize)

{
  uint32_t uVar1;
  uint uVar2;
  int iVar3;
  u_int uVar4;
  char *file;
  deci5s_context_t *pdVar5;
  SceDeci5sSdbgpCommand *pSVar6;
  SceDeci5sSdbgpHeader *pSVar7;
  SceDeci5sSdbgpHeader *pSVar8;
  SceDeci5sSdbgpCommand **ppSVar9;
  
  iVar3 = deci5s_sdbgp_context_check_overflow(dsc,isize);
  if (iVar3 == 0) {
    printf_low("%s:OVERFLOW\n","deci5s_sdbgp_context_alloc_res_info");
    ppSVar9 = &dsc->dsc_res_command;
    uVar2 = (*ppSVar9)->self_size;
    uVar1 = (*ppSVar9)->packet_no;
    deci5s_header_init_p_cmd(dsc->dsc_res_deci5s,dsc->dsc_dc->dc_res_data_size,dsc->dsc_cmd_deci5s);
    pSVar8 = dsc->dsc_res_sdbgp;
    pSVar8->attr = pSVar8->attr | 0x80000000;
    (*ppSVar9)->flags = (*ppSVar9)->flags | 0x80000000;
    uVar4 = mp4_get_cpu();
    printf_low("%d:%s:not implemented!\n",(ulong)uVar4,"deci5s_sdbgp_context_send");
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\deci5s_mp4.c");
    deci5s_assert(file,"deci5s_sdbgp_context_send",0x43f,0,"0");
    pSVar8 = dsc->dsc_res_sdbgp;
    pdVar5 = dsc->dsc_dc;
    pSVar8->total_size = pSVar8->self_size;
    pSVar8->packet_no = pSVar8->packet_no + 1;
    pSVar8->attr = 0;
    pSVar8->n_command = 0;
    pSVar7 = pSVar8 + 1;
    pSVar7->self_size = uVar2;
    *ppSVar9 = (SceDeci5sSdbgpCommand *)pSVar7;
    pSVar8[1].total_size = uVar2;
    pSVar6 = dsc->dsc_cmd_command;
    pSVar8[1].sequence_no = pSVar6->type & 0xffffff | 0x2000000;
    pSVar8[1].packet_no = 0;
    pSVar8[1].attr = pSVar6->command_no;
    pSVar8[1].n_command = uVar1 + 1;
    pdVar5->dc_res_data_size = uVar2 + 0x40;
    pSVar8->total_size = pSVar8->total_size + uVar2;
    pSVar8->n_command = pSVar8->n_command + 1;
    dsc->dsc_res_info = (uint8_t *)((long)&pSVar7->self_size + (ulong)uVar2);
    iVar3 = deci5s_sdbgp_context_check_overflow(dsc,isize);
    if (iVar3 == 0) {
      uVar4 = mp4_get_cpu();
      printf_low("%d:%s:OVERFLOW AGAIN\n",(ulong)uVar4,"deci5s_sdbgp_context_alloc_res_info");
      return -1;
    }
  }
  pdVar5 = dsc->dsc_dc;
  pSVar8 = dsc->dsc_res_sdbgp;
  uVar2 = pdVar5->dc_res_data_size;
  dsc->dsc_res_info = pdVar5->dc_res_ptr + uVar2;
  pdVar5->dc_res_data_size = uVar2 + isize;
  pSVar8->total_size = pSVar8->total_size + isize;
  dsc->dsc_res_command->total_size = dsc->dsc_res_command->total_size + isize;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010dfe4
 * symbol: deci5s_sdbgp_context_check_overflow
 * prototype: int deci5s_sdbgp_context_check_overflow(deci5s_sdbgp_context_t * dsc, uint32_t csize)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int deci5s_sdbgp_context_check_overflow(deci5s_sdbgp_context_t *dsc,uint32_t csize)

{
  int iVar1;
  
  iVar1 = deci5s_context_check_overflow(dsc->dsc_dc,csize);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010dfec
 * symbol: deci5s_sdbgp_context_handle_get_pmu_count_info
 * prototype: SceDeci5sSdbgpMp4PMUCountInfo * deci5s_sdbgp_context_handle_get_pmu_count_info(deci5s_sdbgp_context_t * dsc)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

SceDeci5sSdbgpMp4PMUCountInfo *
deci5s_sdbgp_context_handle_get_pmu_count_info(deci5s_sdbgp_context_t *dsc)

{
  int iVar1;
  SceDeci5sSdbgpMp4PMUCountInfo *pSVar2;
  
  iVar1 = deci5s_sdbgp_context_alloc_res_info(dsc,0x10);
  if (iVar1 == 0) {
    pSVar2 = (SceDeci5sSdbgpMp4PMUCountInfo *)dsc->dsc_res_info;
  }
  else {
    pSVar2 = (SceDeci5sSdbgpMp4PMUCountInfo *)0x0;
  }
  return pSVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010e020
 * symbol: deci5s_ch_fix_send_request
 * prototype: int deci5s_ch_fix_send_request(deci5s_ch_fix_t * d5cf, uint32_t psize, uint32_t hint0)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int deci5s_ch_fix_send_request(deci5s_ch_fix_t *d5cf,uint32_t psize,uint32_t hint0)

{
  int iVar1;
  
  iVar1 = deci_target_ch_fix_send_request(d5cf->d5cf_low,psize,hint0);
  return iVar1;
}


