/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\dev_context.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114a38
 * symbol: dev_context_init_for_el3
 * prototype: int dev_context_init_for_el3(dev_context_t * p)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int dev_context_init_for_el3(dev_context_t *p)

{
  tpidr_el3 = p;
  tpidrro_el0 = p;
  return 0;
}


