/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\dvm.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001149a0
 * symbol: dvm_read_mailbox
 * prototype: uint32_t dvm_read_mailbox(uint32_t no)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t dvm_read_mailbox(uint32_t no)

{
  return *(uint32_t *)(ulong)(no * 0x1000 + 0x30c0000);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001149b0
 * symbol: dvm_init
 * prototype: int dvm_init(void)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int dvm_init(void)

{
  long lVar1;
  
  for (lVar1 = 0; lVar1 != 0x30000; lVar1 = lVar1 + 0x1000) {
    *(undefined4 *)(&DAT_030c0000 + lVar1) = 0;
  }
  return 0;
}


