/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\el0_support.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010a894
 * symbol: el0_support
 * prototype: int el0_support(el3_param_t * param, uint32_t cp_param2)
 * body addresses: 3700
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int el0_support(el3_param_t *param,uint32_t cp_param2)

{
  int iVar1;
  u_int uVar2;
  int iVar3;
  uint uVar4;
  u_int uVar5;
  main_mp4_param_t *pmVar6;
  mmu_page_table_t *pmVar7;
  undefined8 uVar8;
  mmu_page_table_t *link_mpt;
  uint64_t uVar9;
  uint64_t uVar10;
  ulong uVar11;
  ulong uVar12;
  long lVar13;
  _func_int_el0_param_ptr_boot_config_header_ptr *p_Var14;
  dev_context_t *pdVar15;
  mmu_el0_io_t *pmVar16;
  uint8_t *local_70;
  uint8_t *puStack_68;
  
  mp4_get_cpu();
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    check_consistency();
  }
  uVar11 = sctlr_el1;
  sctlr_el1 = uVar11 & 0xfbf7bff8 | 0x4004000;
  uVar11 = sctlr_el2;
  sctlr_el2 = uVar11 & 0xfffffff8 | 0x4000;
  scr_el3 = 0x3d0e;
  uVar11 = hcr_el2;
  hcr_el2 = uVar11 & 0x7ffffffe | 0x8000038;
  vbar_el1 = 0x125000;
  vbar_el2 = 0x124000;
  uVar11 = mdcr_el2;
  mdcr_el2 = uVar11 & 0xffffffff | 6;
  uVar11 = mdcr_el3;
  mdcr_el3 = uVar11 & 0xffffffff | 0x20000;
  uVar11 = pmuserenr_el0;
  pmuserenr_el0 = uVar11 & 0xfffffff0 | 0xf;
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    lVar13 = -0x3dd000;
    tpidr_el1 = 0x125cb8;
    tpidr_el2 = 0x124c68;
    pdVar15 = &g_dev_context_mm;
  }
  else {
    param = (el3_param_t *)&param->core1_main;
    lVar13 = -0x1da000;
    tpidr_el1 = 0x125cf0;
    pdVar15 = &g_dev_context_io;
    tpidr_el2 = 0x124ca0;
  }
  lVar13 = (long)&core1_boot_config.field_0 + lVar13;
  p_Var14 = param->core0_main;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:sp_el0 = 0x%016lx\n",(ulong)uVar2,"el0_support",lVar13);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:entry  = 0x%016lx\n",(ulong)uVar2,"el0_support",p_Var14);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:dc     = 0x%016lx\n",(ulong)uVar2,"el0_support",pdVar15);
  sp_el0 = lVar13;
  sp_el1 = 0;
  sp_el2 = 0;
  uVar11 = spsr_el3;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:%-16s = 0x%08x\n",(ulong)uVar2,"el0_support","SPSR_EL3",uVar11 & 0xffffffff);
  uVar11 = (ulong)((uint)uVar11 & 0xffcffc20);
  spsr_el3 = uVar11;
  elr_el3 = p_Var14;
  aarch64_CISW_all();
  tcr_el1 = 0x200c0351f;
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    mmu_el0_common_phase1(&g_mmu_el0_mm.mem_mec);
    g_mmu_el0_mm.mem_level3_03200000 = mmu_page_table_mgr_alloc('\x01','\x03',0x3200000);
    g_mmu_el0_mm.mem_level3_03400000 = mmu_page_table_mgr_alloc('\x01','\x03',0x3400000);
    g_mmu_el0_mm.mem_level3_03A00000 = mmu_page_table_mgr_alloc('\x01','\x03',0x3a00000);
    g_mmu_el0_mm.mem_level3_04000000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4000000);
    g_mmu_el0_mm.mem_level3_04800000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4800000);
    g_mmu_el0_mm.mem_level3_04C00000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4c00000);
    g_mmu_el0_mm.mem_level3_04E00000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4e00000);
    g_mmu_el0_mm.mem_level3_05000000 = mmu_page_table_mgr_alloc('\x01','\x03',0x5000000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_03200000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_03400000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_03A00000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_04000000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_04800000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_04C00000);
    mmu_page_table_set_table
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,g_mmu_el0_mm.mem_level3_04E00000);
    pmVar7 = g_mmu_el0_mm.mem_mec.mec_level2_00000000;
    link_mpt = g_mmu_el0_mm.mem_level3_05000000;
    pmVar16 = (mmu_el0_io_t *)&g_mmu_el0_mm;
  }
  else {
    pmVar16 = &g_mmu_el0_io;
    mmu_el0_common_phase1(&g_mmu_el0_io.mei_mec);
    g_mmu_el0_io.mei_level2_40000000 = mmu_page_table_mgr_alloc('\x01','\x02',0x40000000);
    g_mmu_el0_io.mei_level3_03600000 = mmu_page_table_mgr_alloc('\x01','\x03',0x3600000);
    g_mmu_el0_io.mei_level3_03800000 = mmu_page_table_mgr_alloc('\x01','\x03',0x3800000);
    g_mmu_el0_io.mei_level3_03C00000 = mmu_page_table_mgr_alloc('\x01','\x03',0x3c00000);
    g_mmu_el0_io.mei_level3_04200000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4200000);
    g_mmu_el0_io.mei_level3_04400000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4400000);
    g_mmu_el0_io.mei_level3_04A00000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4a00000);
    g_mmu_el0_io.mei_level3_04E00000 = mmu_page_table_mgr_alloc('\x01','\x03',0x4e00000);
    g_mmu_el0_io.mei_level3_05200000 = mmu_page_table_mgr_alloc('\x01','\x03',0x5200000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level1_00000000,g_mmu_el0_io.mei_level2_40000000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_03600000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_03800000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_03C00000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_04200000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_04400000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_04A00000);
    mmu_page_table_set_table
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,g_mmu_el0_io.mei_level3_04E00000);
    pmVar7 = g_mmu_el0_io.mei_mec.mec_level2_00000000;
    link_mpt = g_mmu_el0_io.mei_level3_05200000;
  }
  mmu_page_table_set_table(pmVar7,link_mpt);
  TLBI_ALLE1();
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  ttbr0_el1 = ((pmVar16->mei_mec).mec_level1_00000000)->mpt_table_pbase;
  uVar8 = mair_el3;
  mair_el1 = uVar8;
  mair_el2 = uVar8;
  uVar12 = sctlr_el1;
  sctlr_el1 = uVar12 & 0xfff72ff0 | 0xd005;
  uVar12 = sctlr_el2;
  sctlr_el2 = uVar12 & 0xfff7eff9 | 0x1006;
  aarch64_DC_CIVAC_range_be(EL3_VBAR_ASM,&SRAM_END);
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    pmVar6 = msi_get_main_param();
    mmu_el0_common_phase2(&g_mmu_el0_mm.mem_mec);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,0x28000000,0x18000000,0x800000,
               map_mode_rw_rw,mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_mec.mec_level2_00000000,0x10000000,0x4000000,0x10000000,
               map_mode_rw_rw,mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_03200000,0x3200000,0x1000000,0x10000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_03A00000,0x3a00000,0xec000000,0x100000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_03A00000,0x3b01000,0xbd110000,0x1000,map_mode_rw_rw,
               mem_type_so);
    iVar3 = *(int *)&(pmVar6->mm4p_mm_param).mimi_iommu_addr;
    iVar1 = *(int *)&(pmVar6->mm4p_mm_param).mimi_syshub_base;
    uVar2 = mp4_get_cpu();
    uVar12 = (ulong)((iVar3 - iVar1) + 0x48000000);
    printf_low("%d:%s:EL0:MM:MAP: 0x%016lx -> 0x%016lx\n",(ulong)uVar2,"mmu_el0_mm_phase2",0x4001000
               ,uVar12);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_04000000,0x4001000,uVar12,0x50000,map_mode_rw_rw,mem_type_so)
    ;
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_04000000,0x4040000,0x40000,0x40000,map_mode_rw_rw,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_04000000,0x4080000,0x88500000,0x40000,map_mode_rw_rw,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_04800000,0x4820000,0x20000,0x3000,map_mode_rw_rw,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_04C00000,0x4c00000,0,0x6000,map_mode_rx_rx,mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_mm.mem_level3_04C00000,0x4c06000,0x6000,0x6000,map_mode_rw_rw,
               mem_type_memory);
    uVar9 = 0x501c000;
    uVar10 = 0x1c000;
    pmVar7 = g_mmu_el0_mm.mem_level3_05000000;
  }
  else {
    mmu_el0_common_phase2(&g_mmu_el0_io.mei_mec);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_mec.mec_level2_00000000,0x30000000,0x1fc00000,0x200000,
               map_mode_rw_rw,mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level2_40000000,0x40000000,0x15000000,0x2a00000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_mec.mec_level3_02200000,0x22e0000,0x32e0000,0x20000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_03800000,0x3800000,0x34200000,0x10000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_03C00000,0x3c00000,0xec100000,0x100000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_03C00000,0x3d01000,0xbd110000,0x1000,map_mode_rw_rw,
               mem_type_so);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_04200000,0x4227000,0x27000,0x19000,map_mode_rw_rw,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_04400000,0x4426000,0x26000,0x1000,map_mode_rw_rw,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_04A00000,0x4a23000,0x23000,0x3000,map_mode_rw_rw,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_04E00000,0x4e0c000,0xc000,0x8000,map_mode_rx_rx,
               mem_type_memory);
    mmu_page_table_map_range_bs
              (g_mmu_el0_io.mei_level3_04E00000,0x4e77000,0x14000,0x8000,map_mode_rw_rw,
               mem_type_memory);
    uVar9 = 0x521e000;
    uVar10 = 0x1e000;
    pmVar7 = g_mmu_el0_io.mei_level3_05200000;
  }
  mmu_page_table_map_range_bs(pmVar7,uVar9,uVar10,0x2000,map_mode_rx_rx,mem_type_memory);
  local_70 = (uint8_t *)0x0;
  puStack_68 = (uint8_t *)0x0;
  uVar2 = mp4_get_cpu();
  if (uVar2 == 0) {
    boot_config_mm_phase1();
    boot_config_mm_phase2(&puStack_68);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:(mem %p)\n",(ulong)uVar2,"mmu_el0_mm_phase3",&g_mmu_el0_mm);
    pmVar6 = msi_get_main_param();
    iVar3 = *(int *)&(pmVar6->mm4p_sdma0_mmio).mimi_iommu_addr;
    iVar1 = *(int *)&(pmVar6->mm4p_sdma0_mmio).mimi_syshub_base;
    uVar2 = mp4_get_cpu();
    uVar10 = (uint64_t)((iVar3 - iVar1) + 0x1100000);
    printf_low("%d:%s:EL0:MM:MAP: 0x%016lx -> 0x%016lx\n",(ulong)uVar2,"mmu_el0_mm_phase3",0x3400000
               ,uVar10);
    uVar9 = 0x3400000;
    pmVar7 = g_mmu_el0_mm.mem_level3_03400000;
  }
  else {
    boot_config_io_phase1();
    boot_config_io_phase2(&local_70);
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:(mei %p)\n",(ulong)uVar2,"mmu_el0_io_phase3",&g_mmu_el0_io);
    pmVar6 = msi_get_main_param();
    iVar3 = *(int *)&(pmVar6->mm4p_sdma1_mmio).mimi_iommu_addr;
    iVar1 = *(int *)&(pmVar6->mm4p_sdma1_mmio).mimi_syshub_base;
    uVar2 = mp4_get_cpu();
    uVar10 = (uint64_t)((iVar3 - iVar1) + 0x1100000);
    printf_low("%d:%s:EL0:IO:MAP: 0x%016lx -> 0x%016lx\n",(ulong)uVar2,"mmu_el0_io_phase3",0x3600000
               ,uVar10);
    uVar9 = 0x3600000;
    pmVar7 = g_mmu_el0_io.mei_level3_03600000;
  }
  mmu_page_table_map_range_bs(pmVar7,uVar9,uVar10,0x10000,map_mode_rw_rw,mem_type_so);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:===== ===== EL3 ===== =====\n",(ulong)uVar2,"el0_support");
  aarch64_print_SCR_EL3();
  aarch64_print_SCTLR_EL3();
  aarch64_print_SPSR_EL3();
  aarch64_print_ESR_EL3();
  uVar2 = mp4_get_cpu();
  uVar8 = tpidr_el3;
  printf_low("%d:%s:TPIDR_EL3   = %p\n",(ulong)uVar2,"el0_support",uVar8);
  uVar2 = mp4_get_cpu();
  uVar8 = aarch64_read_ELR_EL3((ulong)uVar2);
  printf_low("%d:%s:ELR_EL3     = %p\n",(ulong)uVar2,"el0_support",uVar8);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:===== ===== EL2 ===== =====\n",(ulong)uVar2,"el0_support");
  aarch64_print_HCR_EL2();
  aarch64_print_SCTLR_EL2();
  aarch64_print_SPSR_EL2();
  aarch64_print_ESR_EL2();
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:===== ===== EL1 ===== =====\n",(ulong)uVar2,"el0_support");
  uVar2 = mp4_get_cpu();
  uVar8 = aarch64_read_CLIDR_EL1((ulong)uVar2);
  printf_low("%d:%s:%-16s = 0x%016lx\n",(ulong)uVar2,"el0_support","CLIDR_EL1",uVar8);
  csselr_el1 = 0;
  uVar2 = mp4_get_cpu();
  uVar8 = ccsidr_el1;
  printf_low("%d:%s:%-16s = 0x%08x\n",(ulong)uVar2,"el0_support","CCSIDR_EL1",uVar8);
  csselr_el1 = 1;
  uVar2 = mp4_get_cpu();
  uVar8 = ccsidr_el1;
  printf_low("%d:%s:%-16s = 0x%08x\n",(ulong)uVar2,"el0_support","CCSIDR_EL1",uVar8);
  csselr_el1 = 2;
  uVar2 = mp4_get_cpu();
  uVar8 = ccsidr_el1;
  printf_low("%d:%s:%-16s = 0x%08x\n",(ulong)uVar2,"el0_support","CCSIDR_EL1",uVar8);
  aarch64_print_SCTLR_EL1();
  aarch64_print_SPSR_EL1();
  aarch64_print_ESR_EL1();
  uVar2 = mp4_get_cpu();
  uVar8 = aarch64_read_ELR_EL1((ulong)uVar2);
  printf_low("%d:%s:%-16s = 0x%016lx\n",(ulong)uVar2,"el0_support","ELR_EL1",uVar8);
  uVar2 = mp4_get_cpu();
  uVar8 = far_el1;
  printf_low("%d:%s:%-16s = 0x%016lx\n",(ulong)uVar2,"el0_support","FAR_EL1",uVar8);
  uVar2 = mp4_get_cpu();
  uVar8 = aarch64_read_TCR_EL1((ulong)uVar2);
  printf_low("%d:%s:%-16s = 0x%016lx\n",(ulong)uVar2,"el0_support","TCR_EL1",uVar8);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:===== ===== EL0 ===== =====\n",(ulong)uVar2,"el0_support");
  uVar2 = mp4_get_cpu();
  uVar8 = tpidr_el0;
  printf_low("%d:%s:TPIDR_EL0   = %p\n",(ulong)uVar2,"el0_support",uVar8);
  uVar2 = mp4_get_cpu();
  uVar8 = tpidrro_el0;
  printf_low("%d:%s:TPIDRRO_EL0 = %p\n",(ulong)uVar2,"el0_support",uVar8);
  uVar2 = mp4_get_cpu();
  uVar8 = aarch64_read_SP_EL0((ulong)uVar2);
  printf_low("%d:%s:SP_EL0      = %p\n",(ulong)uVar2,"el0_support",uVar8);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:===== ===== EL3 ===== =====\n",(ulong)uVar2,"el0_support");
  uVar2 = mp4_get_cpu();
  uVar8 = aarch64_read_ELR_EL3((ulong)uVar2);
  printf_low("%d:%-16s = 0x%016lx\n",(ulong)uVar2,"ELR_EL3",uVar8);
  uVar2 = mp4_get_cpu();
  uVar8 = spsr_el3;
  printf_low("%d:%-16s = 0x%08x\n",(ulong)uVar2,"SPSR_EL3",uVar8);
  uVar8 = AT_S1E3R(0x6000000);
  par_el1 = uVar8;
  uVar8 = AT_S1E1R(0x6000000);
  par_el1 = uVar8;
  iVar3 = cp_param_check(0x8000);
  if (iVar3 != 0) {
    iVar3 = msi_test();
  }
  uVar4 = aarch64_read_DAIF(iVar3);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:DAIF = 0x%08x\n",(ulong)uVar2,"el0_support",(ulong)uVar4);
  aarch64_write_DAIF(uVar4 | 0x800);
  pmevtyper0_el0 = 0x8000001;
  pmevtyper1_el0 = 0x8000002;
  pmevtyper2_el0 = 0x8000003;
  pmevtyper3_el0 = 0x8000005;
  pmevtyper4_el0 = 0x14;
  pmevtyper5_el0 = 0x6000004;
  pmcntenset_el0 = 0x8000003f;
  pmcr_el0 = 7;
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar2,"el0_mmu_get_map");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:MAIR: 0x00\n",(ulong)uVar2,"el0_mmu_get_map");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:\tDevice-nGnRnE memory\n",(ulong)uVar2,"el0_mmu_get_map");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:MAIR: 0xFF\n",(ulong)uVar2,"el0_mmu_get_map");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:\tNormal memory, Outer Write-Back Non-transient, Outer Read/Write-Allocate policy.\n"
             ,(ulong)uVar2,"el0_mmu_get_map");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:\tNormal memory, Inner Write-Back Non-transient, Inner Read/Write-Allocate policy.\n"
             ,(ulong)uVar2,"el0_mmu_get_map");
  uVar2 = mp4_get_cpu();
  uVar5 = mp4_get_cpu();
  if (uVar2 == 0) {
    printf_low("%d:%s:(mem %p)\n",(ulong)uVar5,"mmu_el0_mm_get_map",&g_mmu_el0_mm);
    mmu_el0_common_get_map_low(&g_mmu_el0_mm.mem_mec);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_03200000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_03400000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_03A00000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_04000000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_04800000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_04C00000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_04E00000);
    mmu_page_table_get_map(g_mmu_el0_mm.mem_level3_05000000);
    mmu_el0_common_get_map_high(&g_mmu_el0_mm.mem_mec);
  }
  else {
    printf_low("%d:%s:(mei %p)\n",(ulong)uVar5,"mmu_el0_io_get_map",&g_mmu_el0_io);
    mmu_el0_common_get_map_low(&g_mmu_el0_io.mei_mec);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_03600000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_03800000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_03C00000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_04200000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_04400000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_04A00000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_04E00000);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level3_05200000);
    mmu_el0_common_get_map_high(&g_mmu_el0_io.mei_mec);
    mmu_page_table_get_map(g_mmu_el0_io.mei_level2_40000000);
  }
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:*************************************************************\n",(ulong)uVar2,
             "el0_support");
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:call eret: 0x%016lx: spsr_el3 0x%08x\n",(ulong)uVar2,"el0_support",p_Var14,
             uVar11);
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:*************************************************************\n",(ulong)uVar2,
             "el0_support");
  spsr_el3 = uVar11;
  elr_el3 = p_Var14;
  tpidrro_el0 = pdVar15;
  aarch64_CISW_all();
  IC_IALLU();
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  IC_IALLU();
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  ExceptionReturn();
  return cp_param2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010b728
 * symbol: el0_va_to_el3_va
 * prototype: uint8_t * el0_va_to_el3_va(uint8_t * el0_va0)
 * body addresses: 360
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint8_t * el0_va_to_el3_va(uint8_t *el0_va0)

{
  undefined8 uVar1;
  ulong uVar2;
  ulong uVar3;
  u_int uVar4;
  char *pcVar5;
  uint8_t *puVar6;
  
  uVar1 = AT_S1E1R(el0_va0);
  par_el1 = uVar1;
  uVar2 = par_el1;
  if ((uVar2 & 1) == 0) {
    puVar6 = (uint8_t *)(uVar2 & 0xfffffffff000 | (ulong)el0_va0 & 0xfff);
    if ("" < puVar6) {
      if (((undefined *)(uVar2 & 0xfffffc000000) != &DAT_88000000) && ((uint8_t *)0x7ffff < puVar6))
      {
        uVar4 = mp4_get_cpu();
        printf_low("%d:%s:pa: 0x%016lx (not SRAM)\n",(ulong)uVar4,"el0_va_to_el3_va",puVar6);
        pcVar5 = mp4_basename(
                             "I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\el0_support.c"
                             );
        el3_assert(pcVar5,"el0_va_to_el3_va",0x573,0,"0");
      }
    }
    else {
      uVar4 = mp4_get_cpu();
      printf_low("%d:%s:S1E1R: PAR_EL1: 0x%016lx <- %p\n",(ulong)uVar4,"el0_va_to_el3_va",uVar2,
                 el0_va0);
      puVar6 = (uint8_t *)0x4200000;
    }
    uVar1 = AT_S1E3R(puVar6);
    par_el1 = uVar1;
    uVar3 = par_el1;
    if ((uVar2 & 0xfffffffff000) != (uVar3 & 0xfffffffff000)) {
      uVar4 = mp4_get_cpu();
      printf_low("%d:%s:pa0 0x%016lx != 0x%016lx pa3 (0x%016lx)\n",(ulong)uVar4,"el0_va_to_el3_va",
                 uVar2,uVar3,puVar6);
      pcVar5 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\el0_support.c"
                           );
      el3_assert(pcVar5,"el0_va_to_el3_va",0x57c,0,"0");
    }
  }
  else {
    pcVar5 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\el0_support.c");
    el3_assert(pcVar5,"el0_va_to_el3_va",0x55f,0,"0");
    puVar6 = (uint8_t *)0x0;
  }
  return puVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010b890
 * symbol: mmu_el0_common_phase1
 * prototype: int mmu_el0_common_phase1(mmu_el0_common_t * mec)
 * body addresses: 200
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_el0_common_phase1(mmu_el0_common_t *mec)

{
  int iVar1;
  mmu_page_table_t *pmVar2;
  
  pmVar2 = mmu_page_table_mgr_alloc('\x01','\x01',0);
  mec->mec_level1_00000000 = pmVar2;
  pmVar2 = mmu_page_table_mgr_alloc('\x01','\x02',0);
  mec->mec_level2_00000000 = pmVar2;
  pmVar2 = mmu_page_table_mgr_alloc('\x01','\x03',0);
  mec->mec_level3_00000000 = pmVar2;
  pmVar2 = mmu_page_table_mgr_alloc('\x01','\x03',0x2000000);
  mec->mec_level3_02000000 = pmVar2;
  pmVar2 = mmu_page_table_mgr_alloc('\x01','\x03',0x2200000);
  mec->mec_level3_02200000 = pmVar2;
  pmVar2 = mmu_page_table_mgr_alloc('\x01','\x03',0x3000000);
  mec->mec_level3_03000000 = pmVar2;
  mmu_page_table_set_table(mec->mec_level1_00000000,mec->mec_level2_00000000);
  mmu_page_table_set_table(mec->mec_level2_00000000,mec->mec_level3_00000000);
  mmu_page_table_set_table(mec->mec_level2_00000000,mec->mec_level3_02000000);
  mmu_page_table_set_table(mec->mec_level2_00000000,mec->mec_level3_02200000);
  iVar1 = mmu_page_table_set_table(mec->mec_level2_00000000,mec->mec_level3_03000000);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010b958
 * symbol: mmu_el0_common_phase2
 * prototype: int mmu_el0_common_phase2(mmu_el0_common_t * mec)
 * body addresses: 484
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_el0_common_phase2(mmu_el0_common_t *mec)

{
  int iVar1;
  uint64_t pbegin;
  
  mmu_page_table_map_range_be
            (mec->mec_level3_00000000,0x1000,0x1000,0x10000,map_mode_rx_rx,mem_type_memory);
  mmu_page_table_map_range_be
            (mec->mec_level3_00000000,0x125000,0x88025000,0x125d28,map_mode_rx_rx,mem_type_memory);
  mmu_page_table_map_range_be
            (mec->mec_level3_00000000,0x124000,0x88024000,0x124cd8,map_mode_rx_rx,mem_type_memory);
  mmu_page_table_map_range_bs
            (mec->mec_level2_00000000,0x6000000,0x88200000,0x200000,map_mode_rx_rx,mem_type_memory);
  mmu_page_table_map_range_bs
            (mec->mec_level2_00000000,0x6200000,0x88400000,0x200000,map_mode_rw_rw,mem_type_memory);
  pbegin = mmu_va_to_pa(mp4_get_cpu);
  mmu_page_table_map_range_be
            (mec->mec_level3_00000000,0x117000,pbegin,0x1232d0,map_mode_rx_rx,mem_type_memory);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02000000,0x2010000,0x3010000,0x10000,map_mode_rw_rw,mem_type_so);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02000000,0x2060000,0x3060000,0x10000,map_mode_rw_rw,mem_type_so);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02000000,0x2070000,0x3070000,0x10000,map_mode_rw_rw,mem_type_so);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02000000,0x20c0000,0x30c0000,0x30000,map_mode_rw_rw,mem_type_so);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02200000,0x2200000,0x3200000,0x1000,map_mode_rw_rw,mem_type_so);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02200000,0x2290000,0x3290000,0x10000,map_mode_rw_rw,mem_type_so);
  mmu_page_table_map_range_bs
            (mec->mec_level3_02200000,0x22c0000,0x32c0000,0x10000,map_mode_rw_rw,mem_type_so);
  iVar1 = mmu_page_table_map_range_bs
                    (mec->mec_level3_03000000,0x3000000,0xf6e00000,0x200000,map_mode_rw_rw,
                     mem_type_so);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bb3c
 * symbol: mmu_el0_common_get_map_low
 * prototype: int mmu_el0_common_get_map_low(mmu_el0_common_t * mec)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_el0_common_get_map_low(mmu_el0_common_t *mec)

{
  u_int uVar1;
  int iVar2;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:(mec %p)\n",(ulong)uVar1,"mmu_el0_common_get_map_low",mec);
  mmu_page_table_get_map(mec->mec_level3_00000000);
  mmu_page_table_get_map(mec->mec_level3_02000000);
  mmu_page_table_get_map(mec->mec_level3_02200000);
  iVar2 = mmu_page_table_get_map(mec->mec_level3_03000000);
  return iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bb94
 * symbol: mmu_el0_common_get_map_high
 * prototype: int mmu_el0_common_get_map_high(mmu_el0_common_t * mec)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_el0_common_get_map_high(mmu_el0_common_t *mec)

{
  u_int uVar1;
  int iVar2;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:(mec %p)\n",(ulong)uVar1,"mmu_el0_common_get_map_high",mec);
  mmu_page_table_get_map(mec->mec_level2_00000000);
  iVar2 = mmu_page_table_get_map(mec->mec_level1_00000000);
  return iVar2;
}


