/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\gic.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113774
 * symbol: uint32_set_field
 * prototype: uint32_t uint32_set_field(uint32_t src, uint32_t mask, uint32_t value)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t uint32_set_field(uint32_t src,uint32_t mask,uint32_t value)

{
  return value & mask | src & (mask ^ 0xffffffff);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113784
 * symbol: gic_read_GICC_IAR
 * prototype: uint32_t gic_read_GICC_IAR(void)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t gic_read_GICC_IAR(void)

{
  uint32_t *puVar1;
  
  puVar1 = (uint32_t *)0x32a200c;
  if (g_cbar_el1 == '\0') {
    puVar1 = (uint32_t *)0x200c;
  }
  return *puVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001137a8
 * symbol: gic_write_GICC_EOIR
 * prototype: void gic_write_GICC_EOIR(uint32_t v)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void gic_write_GICC_EOIR(uint32_t v)

{
  uint32_t *puVar1;
  
  puVar1 = (uint32_t *)0x32a2010;
  if (g_cbar_el1 == '\0') {
    puVar1 = (uint32_t *)0x2010;
  }
  *puVar1 = v;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001137cc
 * symbol: gic_read_GICC_RPR
 * prototype: uint32_t gic_read_GICC_RPR(void)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t gic_read_GICC_RPR(void)

{
  uint32_t *puVar1;
  
  gic_print_gicc_reg("GICC_RPR",0x14);
  puVar1 = (uint32_t *)0x32a2014;
  if (g_cbar_el1 == '\0') {
    puVar1 = (uint32_t *)0x2014;
  }
  return *puVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011380c
 * symbol: gic_print_gicc_reg
 * prototype: int gic_print_gicc_reg(char * name, uint32_t offset)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int gic_print_gicc_reg(char *name,uint32_t offset)

{
  long lVar1;
  int iVar2;
  
  lVar1 = 0x32a0000;
  if (g_cbar_el1 == '\0') {
    lVar1 = 0;
  }
  iVar2 = gic_print_reg(name,*(uint32_t *)(lVar1 + (ulong)(offset + 0x2000)));
  return iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011382c
 * symbol: gic_read_GICC_HPPIR
 * prototype: uint32_t gic_read_GICC_HPPIR(void)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t gic_read_GICC_HPPIR(void)

{
  uint32_t *puVar1;
  
  puVar1 = (uint32_t *)0x32a2018;
  if (g_cbar_el1 == '\0') {
    puVar1 = (uint32_t *)0x2018;
  }
  return *puVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113850
 * symbol: gic_check
 * prototype: int gic_check(void)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int gic_check(void)

{
  gic_status_check(&g_gic_status_core0);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113870
 * symbol: gic_status_check
 * prototype: int gic_status_check(gic_status * gs)
 * body addresses: 740
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int gic_status_check(gic_status *gs)

{
  long lVar1;
  uint uVar2;
  u_int uVar3;
  uint uVar4;
  gic_status *pgVar5;
  long lVar6;
  ulong uVar7;
  undefined *puVar8;
  
  pgVar5 = gs;
  if (gs->gs_count == 0) {
    for (lVar6 = 0; lVar6 != 0x10; lVar6 = lVar6 + 4) {
      lVar1 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar1 = 0;
      }
      *(undefined4 *)((long)gs->gsd_igroupr + lVar6) =
           *(undefined4 *)(&LAB_00001080 + lVar1 + lVar6);
    }
    for (lVar6 = 0; lVar6 != 0x20; lVar6 = lVar6 + 4) {
      lVar1 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar1 = 0;
      }
      *(undefined4 *)((long)gs->gsd_isenabler + lVar6) =
           *(undefined4 *)(&DAT_00001100 + lVar1 + lVar6);
    }
    for (lVar6 = 0; lVar6 != 0x20; lVar6 = lVar6 + 4) {
      lVar1 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar1 = 0;
      }
      *(undefined4 *)((long)gs->gsd_ispendr + lVar6) =
           *(undefined4 *)(&DAT_00001200 + lVar1 + lVar6);
    }
    for (lVar6 = 0; lVar6 != 0x20; lVar6 = lVar6 + 4) {
      lVar1 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar1 = 0;
      }
      *(undefined4 *)((long)gs->gsd_isactiver + lVar6) =
           *(undefined4 *)(&DAT_00001300 + lVar1 + lVar6);
    }
  }
  else {
    puVar8 = &LAB_00001080;
    for (uVar7 = 0; uVar7 != 4; uVar7 = uVar7 + 1) {
      uVar4 = gs->gsd_igroupr[uVar7];
      lVar6 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar6 = 0;
      }
      uVar2 = *(uint *)(puVar8 + lVar6);
      if (uVar4 != uVar2) {
        uVar3 = mp4_get_cpu();
        uVar4 = printf_low("%d:%s:GICD_IGROUPR[%d]   : 0x%08x => 0x%08x\n",(ulong)uVar3,
                           "gic_status_check",uVar7 & 0xffffffff,(ulong)uVar4,(ulong)uVar2);
        pgVar5 = (gic_status *)(ulong)uVar4;
        gs->gsd_igroupr[uVar7] = uVar2;
      }
      puVar8 = puVar8 + 4;
    }
    puVar8 = &DAT_00001100;
    for (uVar7 = 0; uVar7 != 8; uVar7 = uVar7 + 1) {
      uVar4 = gs->gsd_isenabler[uVar7];
      lVar6 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar6 = 0;
      }
      uVar2 = *(uint *)(puVar8 + lVar6);
      if (uVar4 != uVar2) {
        uVar3 = mp4_get_cpu();
        uVar4 = printf_low("%d:%s:GICD_ISENABLER[%d] : 0x%08x => 0x%08x\n",(ulong)uVar3,
                           "gic_status_check",uVar7 & 0xffffffff,(ulong)uVar4,(ulong)uVar2);
        pgVar5 = (gic_status *)(ulong)uVar4;
        gs->gsd_isenabler[uVar7] = uVar2;
      }
      puVar8 = puVar8 + 4;
    }
    uVar7 = 0;
    puVar8 = &DAT_00001200;
    lVar6 = 0x32a0000;
    if (g_cbar_el1 == '\0') {
      lVar6 = 0;
    }
    for (; (uint)uVar7 < 8; uVar7 = uVar7 + 1) {
      uVar4 = gs->gsd_ispendr[uVar7];
      uVar2 = *(uint *)(puVar8 + lVar6);
      if (uVar4 != uVar2) {
        uVar3 = mp4_get_cpu();
        printf_low("%d:%s:GICD_ISPENDR[%d]   : 0x%08x => 0x%08x\n",(ulong)uVar3,"gic_status_check",
                   uVar7 & 0xffffffff,(ulong)uVar4,(ulong)uVar2);
        gs->gsd_ispendr[uVar7] = uVar2;
        do {
                    /* WARNING: Do nothing block with infinite loop */
        } while( true );
      }
      puVar8 = (undefined *)(ulong)((int)puVar8 + 4);
    }
    puVar8 = &DAT_00001300;
    for (uVar7 = 0; uVar7 != 8; uVar7 = uVar7 + 1) {
      uVar4 = gs->gsd_isactiver[uVar7];
      lVar6 = 0x32a0000;
      if (g_cbar_el1 == '\0') {
        lVar6 = 0;
      }
      uVar2 = *(uint *)(puVar8 + lVar6);
      if (uVar4 != uVar2) {
        uVar3 = mp4_get_cpu();
        uVar4 = printf_low("%d:%s:GICD_ISACTIVER[%d] : 0x%08x => 0x%08x\n",(ulong)uVar3,
                           "gic_status_check",uVar7 & 0xffffffff,(ulong)uVar4,(ulong)uVar2);
        pgVar5 = (gic_status *)(ulong)uVar4;
        gs->gsd_isactiver[uVar7] = uVar2;
      }
      puVar8 = puVar8 + 4;
    }
  }
  gs->gs_count = gs->gs_count + 1;
  return (int)pgVar5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113b54
 * symbol: gic_init_by_1st_core
 * prototype: int gic_init_by_1st_core(void)
 * body addresses: 248
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int gic_init_by_1st_core(void)

{
  undefined4 *puVar1;
  code *pcVar2;
  code *pcVar3;
  long lVar4;
  long lVar5;
  uint *puVar6;
  
  puVar6 = (uint *)&DAT_032a1080;
  aarch64_read_CBAR_EL1();
  g_cbar_el1 = '\x01';
  g_gic_status_core0.gs_count = 0;
  g_gic_status_core1.gs_count = 0;
  gic_check();
  gic_enable_irq(0x4e,0);
  gic_enable_irq(0x53,1);
  lVar5 = 0;
  if (g_cbar_el1 == '\0') {
    puVar6 = (uint *)&LAB_00001080;
  }
  *puVar6 = *puVar6 & 0xfffffffe;
  for (; lVar5 != 0x28; lVar5 = lVar5 + 4) {
    lVar4 = 0x32a0000;
    if (g_cbar_el1 == '\0') {
      lVar4 = 0;
    }
    *(undefined4 *)(lVar4 + lVar5 + 0x1c00) = 0xaaaaaaaa;
  }
  pcVar3 = (code *)&DAT_032a1000;
  puVar1 = (undefined4 *)&DAT_032a2004;
  pcVar2 = (code *)&DAT_032a2000;
  if (g_cbar_el1 == '\0') {
    pcVar3 = EL3_VBAR_ASM;
    puVar1 = (undefined4 *)0x2004;
    pcVar2 = _boot;
  }
  *puVar1 = 0xff;
  *(undefined4 *)pcVar3 = 1;
  *(undefined4 *)pcVar2 = 1;
  gic_check();
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113c4c
 * symbol: gic_enable_irq
 * prototype: uint32_t gic_enable_irq(u_int irq, uint32_t cpu)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


uint32_t gic_enable_irq(u_int irq,uint32_t cpu)

{
  long lVar1;
  uint uVar2;
  long lVar3;
  
  lVar3 = 0x32a0000;
  if (g_cbar_el1 == '\0') {
    lVar3 = 0;
  }
  lVar1 = lVar3 + (ulong)(irq >> 3 & 0x1ffffffc);
  uVar2 = irq + 0x1800 & 0xfffffffc;
  *(uint *)(&DAT_00001100 + lVar1) = *(uint *)(&DAT_00001100 + lVar1) | 1 << (ulong)(irq & 0x1f);
  *(uint *)(lVar3 + (ulong)uVar2) =
       *(uint *)(lVar3 + (ulong)uVar2) | 1 << (ulong)((irq & 3) * 8 + cpu & 0x1f);
  return irq;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113cac
 * symbol: gic_init_by_2nd_core
 * prototype: int gic_init_by_2nd_core(void)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int gic_init_by_2nd_core(void)

{
  undefined4 *puVar1;
  code *pcVar2;
  uint uVar3;
  u_int uVar4;
  code *pcVar5;
  
  pcVar5 = (code *)&DAT_032a2000;
  puVar1 = (undefined4 *)&DAT_032a2004;
  pcVar2 = pcVar5;
  if (g_cbar_el1 == '\0') {
    puVar1 = (undefined4 *)0x2004;
    pcVar2 = _boot;
  }
  *puVar1 = 0xff;
  uVar3 = *(uint *)pcVar2;
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:GICC_CTLR = 0x%08x\n",(ulong)uVar4,"gic_init_by_2nd_core",(ulong)uVar3);
  if (g_cbar_el1 == '\0') {
    pcVar5 = _boot;
  }
  *(uint *)pcVar5 = 1;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113d38
 * symbol: gic_sgi1
 * prototype: void gic_sgi1(void)
 * body addresses: 680
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void gic_sgi1(void)

{
  long lVar1;
  uint *puVar2;
  uint uVar3;
  u_int uVar4;
  ulong uVar5;
  uint *puVar6;
  undefined *puVar7;
  
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar4,"gic_sgi1");
  uVar4 = mp4_get_cpu();
  uVar5 = aarch64_read_DAIF((ulong)uVar4);
  printf_low("%d:%s:DAIF: 0x%016lx\n",(ulong)uVar4,"gic_sgi1",uVar5 & 0xffffffff);
  gic_print_gicd_reg("GICD_CTLR",0);
  gic_print_gicd_reg("GICD_TYPER",4);
  gic_print_gicd_reg("GICD_IIDR",8);
  puVar7 = &LAB_00001080;
  for (uVar5 = 0; uVar5 != 8; uVar5 = uVar5 + 1) {
    uVar4 = mp4_get_cpu();
    lVar1 = 0x32a0000;
    if (g_cbar_el1 == '\0') {
      lVar1 = 0;
    }
    printf_low("%d:%s:GICD_IGROUPR[%d] = 0x%08x\n",(ulong)uVar4,"gic_print_gicd",uVar5 & 0xffffffff,
               (ulong)*(uint *)(puVar7 + lVar1));
    puVar7 = puVar7 + 4;
  }
  puVar7 = &DAT_00001100;
  for (uVar5 = 0; uVar5 != 8; uVar5 = uVar5 + 1) {
    uVar4 = mp4_get_cpu();
    lVar1 = 0x32a0000;
    if (g_cbar_el1 == '\0') {
      lVar1 = 0;
    }
    printf_low("%d:%s:GICD_ISENABLER[%d] = 0x%08x\n",(ulong)uVar4,"gic_print_gicd",
               uVar5 & 0xffffffff,(ulong)*(uint *)(puVar7 + lVar1));
    puVar7 = puVar7 + 4;
  }
  puVar7 = &DAT_00001200;
  for (uVar5 = 0; uVar5 != 8; uVar5 = uVar5 + 1) {
    uVar4 = mp4_get_cpu();
    lVar1 = 0x32a0000;
    if (g_cbar_el1 == '\0') {
      lVar1 = 0;
    }
    printf_low("%d:%s:GICD_ISPENDR[%d]   = 0x%08x\n",(ulong)uVar4,"gic_print_gicd",
               uVar5 & 0xffffffff,(ulong)*(uint *)(puVar7 + lVar1));
    puVar7 = puVar7 + 4;
  }
  gic_print_gicd_reg("GICD_ISACTIVER0",0x300);
  gic_print_gicd_reg("GICD_ITARGETSR0",0x800);
  puVar7 = &DAT_00001400;
  for (uVar5 = 0; uVar5 != 8; uVar5 = uVar5 + 1) {
    uVar4 = mp4_get_cpu();
    lVar1 = 0x32a0000;
    if (g_cbar_el1 == '\0') {
      lVar1 = 0;
    }
    printf_low("%d:%s:GICD_IPRIORITYR[%d]   = 0x%08x\n",(ulong)uVar4,"gic_print_gicd",
               uVar5 & 0xffffffff,(ulong)*(uint *)(puVar7 + lVar1));
    puVar7 = puVar7 + 4;
  }
  gic_print_gicc_reg("GICC_CTLR",0);
  gic_print_gicc_reg("GICC_IAR",0xc);
  gic_print_gicc_reg("GICC_IIDR",0xfc);
  puVar6 = (uint *)0x32a1f00;
  puVar2 = puVar6;
  if (g_cbar_el1 == '\0') {
    puVar2 = (uint *)&UNK_00001f00;
  }
  uVar3 = *puVar2 & 0xfc00fff0 | 0x30001;
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:GICD_SGIR <= 0x%08x\n",(ulong)uVar4,"gic_sgi01",(ulong)uVar3);
  if (g_cbar_el1 == '\0') {
    puVar6 = (uint *)&UNK_00001f00;
  }
  *puVar6 = uVar3;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113fe0
 * symbol: gic_core1
 * prototype: void gic_core1(void)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void gic_core1(void)

{
  u_int uVar1;
  ulong uVar2;
  
  uVar1 = mp4_get_cpu();
  uVar2 = aarch64_read_DAIF((ulong)uVar1);
  printf_low("%d:%s:DAIF: 0x%016lx\n",(ulong)uVar1,"gic_core1",uVar2 & 0xffffffff);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:Enter LOOP\n",(ulong)uVar1,"gic_core1");
  do {
    gic_status_check(&g_gic_status_core1);
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114048
 * symbol: gic_print_reg
 * prototype: int gic_print_reg(char * name, uint32_t v)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int gic_print_reg(char *name,uint32_t v)

{
  u_int uVar1;
  int iVar2;
  
  uVar1 = mp4_get_cpu();
  iVar2 = printf_low("%d:%s:%-16s  0x%08x\n",(ulong)uVar1,"gic_print_reg",name,(ulong)v);
  return iVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114088
 * symbol: gic_print_gicd_reg
 * prototype: int gic_print_gicd_reg(char * name, uint32_t offset)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int gic_print_gicd_reg(char *name,uint32_t offset)

{
  long lVar1;
  int iVar2;
  
  lVar1 = 0x32a0000;
  if (g_cbar_el1 == '\0') {
    lVar1 = 0;
  }
  iVar2 = gic_print_reg(name,*(uint32_t *)(lVar1 + (ulong)(offset + 0x1000)));
  return iVar2;
}


