/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\misc.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001149d8
 * symbol: el3_assert
 * prototype: void el3_assert(char * file, char * func, u_int line, int c, char * cstr)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void el3_assert(char *file,char *func,u_int line,int c,char *cstr)

{
  u_int uVar1;
  int iVar2;
  
  if (c != 0) {
    return;
  }
  uVar1 = mp4_get_cpu();
  iVar2 = printf_low("Assertion failed at <%s:%s:%d:%s> on %d\n",file,func,(ulong)line,cstr,
                     (ulong)uVar1);
  aarch64_BRK(iVar2);
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}


