/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\mmu.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001118c0
 * symbol: mmu_va_to_pa
 * prototype: uint64_t mmu_va_to_pa(void * va)
 * body addresses: 192
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t mmu_va_to_pa(void *va)

{
  u_int uVar1;
  uint64_t uVar2;
  char *file;
  
  uVar2 = aarch64_address_translation_read(va);
  if ((uVar2 & 1) == 0) {
    uVar2 = uVar2 & 0xfffffffff000;
  }
  else {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:WARNING!!!: READ: 0x%016lx -> 0x%016lx\n",(ulong)uVar1,"mmu_va_to_pa",va,uVar2
              );
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:FST = 0x%016lx\n",(ulong)uVar1,"mmu_va_to_pa",uVar2 & 0x7e);
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:PAR = 0x%016lx\n",(ulong)uVar1,"mmu_va_to_pa",uVar2 & 0xfffffffff000);
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(file,"mmu_va_to_pa",0x57,0,"0");
    uVar2 = 0xffffffffffffffff;
  }
  return uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111980
 * symbol: mmu_page_table_init_table
 * prototype: int mmu_page_table_init_table(mmu_page_table_t * mpt)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_init_table(mmu_page_table_t *mpt)

{
  pte_t *ppVar1;
  pte_t *ppVar2;
  
  ppVar2 = mpt->mpt_table;
  ppVar1 = ppVar2 + 0x200;
  for (; ppVar2 < ppVar1; ppVar2 = ppVar2 + 1) {
    *ppVar2 = 0;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001119a0
 * symbol: mmu_page_table_set_table
 * prototype: int mmu_page_table_set_table(mmu_page_table_t * mpt, mmu_page_table_t * link_mpt)
 * body addresses: 356
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_set_table(mmu_page_table_t *mpt,mmu_page_table_t *link_mpt)

{
  int iVar1;
  u_int uVar2;
  char *pcVar3;
  pte_t *ppVar4;
  uint64_t va;
  ulong uVar5;
  
  pcVar3 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar3,"mmu_page_table_set_table",0x1b8,(uint)(mpt != (mmu_page_table_t *)0x0),
             "mpt != NULL");
  pcVar3 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar3,"mmu_page_table_set_table",0x1b9,(uint)(link_mpt != (mmu_page_table_t *)0x0),
             "link_mpt != NULL");
  pcVar3 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar3,"mmu_page_table_set_table",0x1ba,(uint)(mpt->mpt_el == link_mpt->mpt_el),
             "mpt->mpt_el == link_mpt->mpt_el");
  pcVar3 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar3,"mmu_page_table_set_table",0x1bb,
             (uint)(mpt->mpt_level + 1 == (uint)link_mpt->mpt_level),
             "mpt->mpt_level + 1 == link_mpt->mpt_level");
  va = link_mpt->mpt_vbase;
  ppVar4 = mmu_page_table_get_ppte(mpt,va);
  if (ppVar4 == (pte_t *)0x0) {
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:mmu_page_table_get_ppte(va 0x%016lx) failed\n",(ulong)uVar2,
               "mmu_page_table_set_table",va);
    iVar1 = -1;
  }
  else {
    uVar5 = *ppVar4;
    pcVar3 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar3,"mmu_page_table_set_table",0x1c3,(uint)((uVar5 & 3) == 0),
               "(pte & VMSAv8_64_TYPE_MASK) == VMSAv8_64_TYPE_INVALID");
    iVar1 = 0;
    *ppVar4 = link_mpt->mpt_table_pbase | 3;
    DC_CVAC((ulong)ppVar4 & 0xffffffffffffffc0);
  }
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111b04
 * symbol: mmu_page_table_get_ppte
 * prototype: pte_t * mmu_page_table_get_ppte(mmu_page_table_t * mpt, uint64_t va)
 * body addresses: 216
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

pte_t * mmu_page_table_get_ppte(mmu_page_table_t *mpt,uint64_t va)

{
  char *pcVar1;
  ulong uVar2;
  
  pcVar1 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar1,"mmu_page_table_get_index",0x198,(uint)(mpt->mpt_vbase <= va),
             "mpt->mpt_vbase <= base");
  if ((ulong)mpt->mpt_level < 4) {
    uVar2 = (ulong)mpt->mpt_level * -9 + 0x27;
  }
  else {
    pcVar1 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar1,"mmu_page_table_get_entry_shift",0xf9,0,"0");
    uVar2 = 0xffffffffffffffff;
  }
  uVar2 = va - mpt->mpt_vbase >> (uVar2 & 0x3f);
  pcVar1 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar1,"mmu_page_table_get_index",0x19b,(uint)((uint)uVar2 < 0x200),
             "pte_index < VMSAv8_64_4K_MAX_PTE");
  return mpt->mpt_table + (uVar2 & 0xffffffff);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111bdc
 * symbol: mmu_page_table_map_range_be
 * prototype: int mmu_page_table_map_range_be(mmu_page_table_t * mpt, uint64_t vbegin, uint64_t pbegin, uint64_t vend, mmu_map_mode_t mode, mmu_mem_type_t mem)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_map_range_be
              (mmu_page_table_t *mpt,uint64_t vbegin,uint64_t pbegin,uint64_t vend,
              mmu_map_mode_t mode,mmu_mem_type_t mem)

{
  mmu_mem_type_t in_w6;
  
  mmu_page_table_op_range_be(mpt,(mmu_op_t)vbegin,pbegin,vend,(ulong)mode,mem,in_w6);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00111bf4
 * symbol: mmu_page_table_op_range_be
 * prototype: int mmu_page_table_op_range_be(mmu_page_table_t * mpt, mmu_op_t op, uint64_t vbegin, uint64_t pbegin, uint64_t vend, mmu_map_mode_t mode, mmu_mem_type_t mem)
 * body addresses: 2116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_page_table_op_range_be
              (mmu_page_table_t *mpt,mmu_op_t op,uint64_t vbegin,uint64_t pbegin,uint64_t vend,
              mmu_map_mode_t mode,mmu_mem_type_t mem)

{
  int iVar1;
  int iVar2;
  bool bVar3;
  int iVar4;
  ulong va;
  pte_t *ppVar5;
  char *pcVar6;
  uint64_t uVar7;
  char *file;
  ulong begin;
  u_int line;
  ulong uVar8;
  pte_t *ppVar9;
  ulong uVar10;
  pte_t pVar11;
  
  begin = (ulong)op;
  mmu_page_table_check_be(mpt,begin,pbegin);
  va = mmu_page_table_get_vbase(mpt,begin);
  ppVar5 = mmu_page_table_get_ppte(mpt,va);
  iVar4 = 0;
  iVar2 = (int)vend + -1;
  ppVar9 = ppVar5;
  do {
    iVar1 = 0x10;
    if (((((uint)va | (uint)vbegin) & 0xffff) != 0 || mpt->mpt_level != '\x03') ||
        pbegin - va >> 0x10 == 0) {
      iVar1 = iVar4;
    }
    iVar4 = 0;
    if (iVar1 != 0) {
      iVar4 = iVar1 + -1;
    }
    uVar10 = vbegin | (ulong)(iVar1 != 0) << 0x34;
    switch(iVar2) {
    case 0:
      uVar8 = 0x40000000000780;
      break;
    case 1:
      uVar8 = 0x40000000000700;
      break;
    case 2:
      pVar11 = uVar10 | 0x780;
      goto LAB_00111dcc;
    case 3:
      pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
      el3_assert(pcVar6,"mmu_page_table_set_map",0x223,(uint)(mpt->mpt_el == '\x01'),
                 "mpt->mpt_el == MMU_EL1");
      uVar8 = 0x400000000007c0;
      break;
    case 4:
      pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
      el3_assert(pcVar6,"mmu_page_table_set_map",0x22a,(uint)(mpt->mpt_el == '\x01'),
                 "mpt->mpt_el == MMU_EL1");
      uVar8 = 0x40000000000740;
      break;
    case 5:
      pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
      el3_assert(pcVar6,"mmu_page_table_set_map",0x230,(uint)(mpt->mpt_el == '\x01'),
                 "mpt->mpt_el == MMU_EL1");
      pVar11 = uVar10 | 0x7c0;
      goto LAB_00111dcc;
    default:
      pVar11 = uVar10 | 0x300;
      pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
      el3_assert(pcVar6,"mmu_page_table_set_map",0x236,0,"0");
      goto LAB_00111dcc;
    }
    pVar11 = uVar10 | uVar8;
LAB_00111dcc:
    if (mode == map_mode_ro) {
      pVar11 = pVar11 & 0xffffffffffffffe3 | 0x10;
    }
    else if (mode == map_mode_rw) {
      pVar11 = pVar11 & 0xffffffffffffffe3;
    }
    else {
      pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
      el3_assert(pcVar6,"mmu_page_table_set_map",0x242,0,"0");
    }
    if (mpt->mpt_level - 1 < 2) {
      pVar11 = pVar11 | 1;
    }
    else if (mpt->mpt_level == 3) {
      pVar11 = pVar11 | 3;
    }
    else {
      pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
      el3_assert(pcVar6,"mmu_page_table_set_map",0x24f,0,"0");
    }
    *ppVar9 = pVar11;
    uVar7 = mmu_page_table_get_entry_size(mpt);
    va = uVar7 + va;
    uVar7 = mmu_page_table_get_entry_size(mpt);
    if (pbegin <= va) {
      ppVar9 = (pte_t *)((ulong)ppVar5 & 0xffffffffffffffc0);
      do {
        DC_CVAC(ppVar9);
        ppVar9 = ppVar9 + 8;
      } while (ppVar9 < ppVar5);
      iVar4 = mmu_page_table_sync_all(mpt);
      switch(iVar2) {
      case 0:
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2ed,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ok) == 0"
                  );
        file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_write_ng);
        pcVar6 = "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ng) == 0"
        ;
        line = 0x2ee;
        bVar3 = iVar4 == 0;
        break;
      case 1:
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2f1,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ok) == 0"
                  );
        file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_write_ok);
        pcVar6 = "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ok) == 0"
        ;
        bVar3 = iVar4 == 0;
        line = 0x2f2;
        break;
      case 2:
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2f5,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ok) == 0"
                  );
        file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_write_ng);
        pcVar6 = "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ng) == 0"
        ;
        bVar3 = iVar4 == 0;
        line = 0x2f6;
        break;
      case 3:
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2f9,(uint)(mpt->mpt_el == '\x01'),
                   "mpt->mpt_el == MMU_EL1");
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2fa,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ok) == 0"
                  );
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_write_ng);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2fb,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ng) == 0"
                  );
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_el0_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x2fc,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_el0_read_ok) == 0"
                  );
        file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_el0_write_ng);
        pcVar6 = 
        "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_el0_write_ng) == 0";
        line = 0x2fd;
        bVar3 = iVar4 == 0;
        break;
      case 4:
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x300,(uint)(mpt->mpt_el == '\x01'),
                   "mpt->mpt_el == MMU_EL1");
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x301,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ok) == 0"
                  );
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_write_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x302,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ok) == 0"
                  );
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_el0_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x303,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_el0_read_ok) == 0"
                  );
        file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_el0_write_ok);
        pcVar6 = 
        "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_el0_write_ok) == 0";
        bVar3 = iVar4 == 0;
        line = 0x304;
        break;
      case 5:
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x307,(uint)(mpt->mpt_el == '\x01'),
                   "mpt->mpt_el == MMU_EL1");
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x308,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ok) == 0"
                  );
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_write_ng);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x309,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ng) == 0"
                  );
        pcVar6 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_el0_read_ok);
        el3_assert(pcVar6,"mmu_page_table_op_range_be",0x30a,(uint)(iVar4 == 0),
                   "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_el0_read_ok) == 0"
                  );
        file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
        iVar4 = mmu_page_table_access_check_range_be(mpt,begin,pbegin,mmu_access_el0_write_ng);
        pcVar6 = 
        "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_el0_write_ng) == 0";
        bVar3 = iVar4 == 0;
        line = 0x30b;
        break;
      default:
        return iVar4;
      }
      el3_assert(file,"mmu_page_table_op_range_be",line,(uint)bVar3,pcVar6);
      return (int)file;
    }
    vbegin = uVar7 + vbegin;
    ppVar9 = ppVar9 + 1;
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112438
 * symbol: mmu_page_table_map_range_bs
 * prototype: int mmu_page_table_map_range_bs(mmu_page_table_t * mpt, uint64_t vbegin, uint64_t pbegin, uint64_t vsize, mmu_map_mode_t mode, mmu_mem_type_t mem)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_map_range_bs
              (mmu_page_table_t *mpt,uint64_t vbegin,uint64_t pbegin,uint64_t vsize,
              mmu_map_mode_t mode,mmu_mem_type_t mem)

{
  mmu_mem_type_t in_w6;
  
  mmu_page_table_op_range_be(mpt,(mmu_op_t)vbegin,pbegin,vsize + vbegin,(ulong)mode,mem,in_w6);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112454
 * symbol: mmu_page_table_get_map
 * prototype: int mmu_page_table_get_map(mmu_page_table_t * mpt)
 * body addresses: 496
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_get_map(mmu_page_table_t *mpt)

{
  uint uVar1;
  pte_t *ppVar2;
  uint8_t uVar3;
  bool bVar4;
  bool bVar5;
  bool bVar6;
  u_int uVar7;
  ulong uVar8;
  ulong uVar9;
  ulong uVar10;
  uint64_t uVar11;
  uint64_t pte_vsize;
  ulong uVar12;
  uint64_t map_pte;
  long lVar13;
  ulong map_pa0;
  uint64_t map_va;
  uint64_t map_size;
  
  uVar3 = mpt->mpt_level;
  uVar11 = mpt->mpt_vbase;
  ppVar2 = mpt->mpt_table;
  if (uVar3 == '\0') {
    uVar9 = 0xff8000000000;
    pte_vsize = 0x8000000000;
  }
  else {
    if (uVar3 != '\x02') {
      if (uVar3 == '\x01') {
        uVar9 = 0xffffc0000000;
        pte_vsize = 0x40000000;
        bVar5 = true;
      }
      else {
        uVar9 = 0xfffffffff000;
        bVar5 = false;
        pte_vsize = 0x1000;
      }
      goto LAB_001124d8;
    }
    uVar9 = 0xffffffe00000;
    pte_vsize = 0x200000;
  }
  bVar5 = true;
LAB_001124d8:
  lVar13 = 0;
  map_va = 0;
  uVar12 = 0;
  map_pa0 = 0;
  map_size = 0;
  map_pte = 0;
  do {
    if ((int)lVar13 == 0x1000) {
      if (map_pte != 0) {
        mmu_page_table_show_map((uint)mpt->mpt_el,map_va,map_size,map_pa0,map_pte,pte_vsize);
      }
      return 0;
    }
    uVar10 = *(ulong *)((long)ppVar2 + lVar13);
    uVar1 = (uint)uVar10 & 3;
    if ((uVar10 & 3) == 0) {
joined_r0x00112554:
      if (map_pte != 0) {
        bVar4 = false;
LAB_0011258c:
        mmu_page_table_show_map((uint)mpt->mpt_el,map_va,map_size,map_pa0,map_pte,pte_vsize);
        map_pte = 0;
        uVar12 = 0;
        map_pa0 = 0;
        map_va = uVar11;
        map_size = 0;
        if (bVar4) goto LAB_001125c8;
      }
    }
    else {
      if (uVar1 == 3) {
        if (bVar5) goto joined_r0x00112554;
      }
      else if (uVar1 != 1) {
        uVar7 = mp4_get_cpu();
        printf_low("%d:%s:0x%016lx: OTHERS\n",(ulong)uVar7,"mmu_page_table_get_map",uVar11);
        goto joined_r0x00112554;
      }
      if (map_pte != 0) {
        uVar8 = uVar10 & uVar9;
        bVar6 = map_pte != (uVar10 & ~uVar9);
        bVar4 = bVar6 || uVar12 != uVar8;
        if (bVar6 || uVar12 != uVar8) goto LAB_0011258c;
        map_size = map_size + pte_vsize;
        if (!bVar6 && uVar12 == uVar8) goto LAB_001125e0;
      }
LAB_001125c8:
      uVar12 = uVar10 & uVar9;
      map_pte = uVar10 & ~uVar9;
      map_pa0 = uVar12;
      map_va = uVar11;
      map_size = pte_vsize;
    }
LAB_001125e0:
    uVar11 = uVar11 + pte_vsize;
    uVar12 = uVar12 + pte_vsize;
    lVar13 = lVar13 + 8;
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112644
 * symbol: mmu_page_table_show_map
 * prototype: void mmu_page_table_show_map(uint32_t el, uint64_t map_va, uint64_t map_size, uint64_t map_pa0, uint64_t map_pte, uint64_t pte_vsize)
 * body addresses: 1088
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mmu_page_table_show_map
               (uint32_t el,uint64_t map_va,uint64_t map_size,uint64_t map_pa0,uint64_t map_pte,
               uint64_t pte_vsize)

{
  uint uVar1;
  u_int uVar2;
  char *format;
  undefined *puVar3;
  undefined *puVar4;
  uint64_t uVar5;
  ulong uVar6;
  uint uVar7;
  ulong uVar8;
  ulong uVar9;
  ulong uVar10;
  
  uVar2 = mp4_get_cpu();
  printf_low("%d:%s:MAP: 0x%016lx+0x%016lx: 0x%016lx: 0x%016lx: ",(ulong)uVar2,
             "mmu_page_table_show_map",map_va,map_size,map_pa0,map_pte);
  if ((map_pte >> 0x34 & 1) == 0) {
    uVar8 = map_pte & 0xfffffffffffffffc;
    uVar5 = pte_vsize;
  }
  else {
    uVar8 = map_pte & 0xffeffffffffffffc;
    uVar5 = 0x10000;
    if (pte_vsize != 0x1000) {
      uVar5 = pte_vsize;
    }
  }
  if (el == 2) {
    uVar10 = mair_el2;
    uVar9 = sctlr_el2;
  }
  else if (el == 3) {
    uVar10 = mair_el3;
    uVar9 = sctlr_el3;
  }
  else {
    uVar10 = mair_el1;
    uVar9 = sctlr_el1;
  }
  if (uVar5 == 0x1000000000000) {
    format = "256T: ";
LAB_00112770:
    printf_low(format);
  }
  else {
    if (uVar5 == 0x10000) {
      format = " 64K: ";
      goto LAB_00112770;
    }
    if (uVar5 == 0x200000) {
      format = "  2M: ";
      goto LAB_00112770;
    }
    if (uVar5 == 0x40000000) {
      format = "  1G: ";
      goto LAB_00112770;
    }
    if (uVar5 == 0x8000000000) {
      format = "512G: ";
      goto LAB_00112770;
    }
    if (uVar5 == 0x1000) {
      format = "  4K: ";
      goto LAB_00112770;
    }
    printf_low("0x%016lx: ",uVar5);
  }
  uVar7 = (uint)uVar8;
  uVar1 = uVar7 >> 2 & 7;
  uVar6 = uVar8 & 0xffffffffffffffe0;
  printf_low("%2d:0x%02x: ",(ulong)uVar1,(ulong)((uint)(uVar10 >> (uVar1 << 3)) & 0xff));
  if (el != 1) {
    if ((uVar8 >> 0x36 & 1) == 0) {
      if ((uVar7 >> 7 & 1) == 0) {
        puVar4 = &UNK_0011ed0c;
        if ((uVar9 & 0x80000) != 0) {
          puVar4 = &DAT_0011f3a8;
        }
      }
      else {
        uVar6 = 0xffffffffffffff60;
LAB_001128ac:
        uVar6 = uVar8 & uVar6;
        puVar4 = &DAT_0011c9b0;
      }
    }
    else if ((uVar7 >> 7 & 1) == 0) {
      uVar6 = 0xffbfffffffffffe0;
LAB_00112864:
      uVar6 = uVar8 & uVar6;
      puVar4 = &DAT_0011f3a8;
    }
    else {
      uVar6 = 0xffbfffffffffff60;
LAB_00112908:
      uVar6 = uVar8 & uVar6;
      puVar4 = &DAT_00119aff;
    }
LAB_00112914:
    puVar3 = &DAT_00119340;
    goto LAB_0011291c;
  }
  if ((uVar8 >> 0x36 & 1) == 0) {
    if ((uVar8 >> 0x35 & 1) == 0) {
      if ((uVar7 >> 7 & 1) == 0) {
        if ((uVar7 >> 6 & 1) != 0) {
          uVar6 = uVar8 & 0xffffffffffffffa0;
          puVar4 = &DAT_0011f3a8;
          puVar3 = &UNK_0011ed0c;
          if ((uVar9 & 0x80000) != 0) {
            puVar3 = puVar4;
          }
          goto LAB_0011291c;
        }
        puVar4 = &UNK_0011ed0c;
        if ((uVar9 & 0x80000) != 0) {
          puVar4 = &DAT_0011f3a8;
        }
      }
      else {
        if ((uVar7 >> 6 & 1) != 0) {
          uVar6 = 0xffffffffffffff20;
          puVar4 = &DAT_0011c9b0;
          goto LAB_00112a60;
        }
        uVar6 = uVar8 & 0xffffffffffffff60;
        puVar4 = &DAT_0011c9b0;
      }
    }
    else if ((uVar7 >> 7 & 1) == 0) {
      puVar4 = &DAT_0011f3a8;
      if ((uVar7 >> 6 & 1) != 0) {
        uVar6 = uVar8 & 0xffdfffffffffffa0;
        puVar3 = &UNK_0011ed0c;
        if ((uVar9 & 0x80000) != 0) {
          puVar3 = &DAT_0011f3a8;
        }
        goto LAB_0011291c;
      }
      uVar6 = uVar8 & 0xffdfffffffffffe0;
    }
    else {
      if ((uVar7 >> 6 & 1) != 0) {
        uVar6 = uVar8 & 0xffdfffffffffff20;
        puVar4 = &DAT_00119aff;
        puVar3 = &DAT_0011c9b0;
        goto LAB_0011291c;
      }
      uVar6 = uVar8 & 0xffdfffffffffff60;
      puVar4 = &DAT_00119aff;
    }
    puVar3 = &DAT_0011f06d;
  }
  else {
    if ((uVar8 >> 0x35 & 1) == 0) {
      uVar6 = 0xffbfffffffffff60;
      if ((uVar7 >> 7 & 1) != 0) {
        if ((uVar7 >> 6 & 1) != 0) {
          uVar6 = uVar8 & 0xffbfffffffffff20;
          puVar4 = &DAT_0011c9b0;
          puVar3 = &DAT_00119aff;
          goto LAB_0011291c;
        }
        goto LAB_001128ac;
      }
      if ((uVar7 >> 6 & 1) == 0) {
        uVar6 = uVar8 & 0xffbfffffffffffe0;
        puVar4 = &UNK_0011ed0c;
        if ((uVar9 & 0x80000) != 0) {
          puVar4 = &DAT_0011f3a8;
        }
        goto LAB_00112914;
      }
      uVar6 = 0xffbfffffffffffa0;
      puVar4 = &DAT_0011f3a8;
    }
    else if ((uVar7 >> 7 & 1) == 0) {
      if ((uVar7 >> 6 & 1) == 0) {
        uVar6 = 0xff9fffffffffffe0;
        goto LAB_00112864;
      }
      uVar6 = 0xff9fffffffffffa0;
      puVar4 = &UNK_0011fb74;
    }
    else {
      uVar6 = 0xff9fffffffffff20;
      if ((uVar7 >> 6 & 1) == 0) {
        uVar6 = 0xff9fffffffffff60;
        goto LAB_00112908;
      }
      puVar4 = &DAT_00119aff;
    }
LAB_00112a60:
    uVar6 = uVar8 & uVar6;
    puVar3 = puVar4;
  }
LAB_0011291c:
  printf_low("U=%3s: ",puVar3);
  printf_low("P=%3s: ",puVar4);
  if (((uint)uVar6 >> 0xb & 1) != 0) {
    uVar6 = uVar6 & 0xfffffffffffff7e0;
    printf_low("nG,");
  }
  if (((uint)uVar6 >> 10 & 1) != 0) {
    uVar6 = uVar6 & 0xfffffffffffffbff;
    printf_low("AF,");
  }
  if ((uVar6 & 0x300) != 0) {
    uVar6 = uVar6 & 0xfffffffffffffcff;
    printf_low("SH,");
  }
  if (((uint)uVar6 >> 5 & 1) != 0) {
    uVar6 = uVar6 & 0xffffffffffffffdf;
    printf_low("NS,");
  }
  if (uVar6 != 0) {
    printf_low(": 0x%016lx\n",uVar6);
  }
  printf_low("\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112a84
 * symbol: mmu_init_phase1
 * prototype: void mmu_init_phase1(void)
 * body addresses: 452
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mmu_init_phase1(void)

{
  undefined8 uVar1;
  uint8_t uVar2;
  bool bVar3;
  u_int uVar4;
  uint uVar5;
  ulong uVar6;
  char *pcVar7;
  pte_t *ppVar8;
  
  uVar6 = aarch64_read_TCR_EL3();
  uVar1 = mair_el3;
  aarch64_read_TTBR0_EL3(uVar1);
  if ((uVar6 & 0xc000) != 0) {
    uVar4 = mp4_get_cpu();
    printf_low("%d:%s:TCR 0x%08x\n",(ulong)uVar4,"mmu_init_phase1",uVar6 & 0xffffffff);
    pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar7,"mmu_init_phase1",0x59b,0,"0");
  }
  mmu_page_table_init(&g_mmu_page_table_el3_level3,'\x03','\x03',0,(pte_t *)&_page_table_el3_level3)
  ;
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:UNMAP 0x00000000 - 0x00001000\n",(ulong)uVar4,"mmu_init_phase1");
  aarch64_DC_CIVAC_range_be((void *)0x0,EL3_VBAR_ASM);
  ppVar8 = mmu_page_table_get_ppte(&g_mmu_page_table_el3_level3,0);
  uVar2 = g_mmu_page_table_el3_level3.mpt_el;
  bVar3 = g_mmu_page_table_el3_level3.mpt_el == '\x03';
  *ppVar8 = *ppVar8 & 0xfffffffffffffffc;
  if (bVar3) {
    TLBI_VALE3IS(0);
  }
  else if (uVar2 == '\x02') {
    TLBI_VALE2IS(0);
  }
  else if (uVar2 == '\x01') {
    TLBI_VALE1IS(0);
  }
  else {
    pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar7,"mmu_page_table_sync_va",0xbd,0,"0");
  }
  TLBI_ALLE3();
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  pcVar7 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  uVar5 = mmu_page_table_access_check_read(&g_mmu_page_table_el3_level3,0,(uint64_t *)0x0);
  el3_assert(pcVar7,"mmu_init_phase1",0x5a7,uVar5 >> 0x1f,
             "mmu_page_table_access_check_read(mpt, 0x0, NULL) < 0");
  mmu_page_table_init(&g_mmu_page_table_el3_level2,'\x03','\x02',0,(pte_t *)&_page_table_el3_level2)
  ;
  mmu_page_table_init(&g_mmu_page_table_el3_level2_2,'\x03','\x02',0x40000000,(pte_t *)&DAT_00102000
                     );
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112c48
 * symbol: mmu_page_table_init
 * prototype: int mmu_page_table_init(mmu_page_table_t * mpt, uint8_t el, uint8_t level, uint64_t vaddr, pte_t * pte0)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_page_table_init(mmu_page_table_t *mpt,uint8_t el,uint8_t level,uint64_t vaddr,pte_t *pte0)

{
  uint64_t uVar1;
  
  mpt->mpt_el = el;
  mpt->mpt_level = level;
  mpt->mpt_vbase = vaddr;
  mpt->mpt_table = pte0;
  uVar1 = mmu_va_to_pa(pte0);
  mpt->mpt_table_pbase = uVar1;
  return (int)uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112c7c
 * symbol: mmu_page_table_access_check_read
 * prototype: int mmu_page_table_access_check_read(mmu_page_table_t * mpt, uint64_t va, uint64_t * pa)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_access_check_read(mmu_page_table_t *mpt,uint64_t va,uint64_t *pa)

{
  uint8_t uVar1;
  undefined8 uVar2;
  uint64_t uVar3;
  char *file;
  
  uVar1 = mpt->mpt_el;
  if (uVar1 == '\x03') {
    uVar2 = AT_S1E3R(va);
    par_el1 = uVar2;
  }
  else if (uVar1 == '\x02') {
    uVar2 = AT_S1E2R(va);
    par_el1 = uVar2;
  }
  else if (uVar1 == '\x01') {
    uVar2 = AT_S1E1R(va);
    par_el1 = uVar2;
  }
  else {
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(file,"mmu_page_table_access_check_read",0x139,0,"0");
  }
  uVar3 = par_el1;
  if (pa != (uint64_t *)0x0) {
    *pa = uVar3;
  }
  return -((uint)uVar3 & 1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112d04
 * symbol: mmu_page_table_mgr_alloc
 * prototype: mmu_page_table_t * mmu_page_table_mgr_alloc(uint8_t el, uint8_t level, uint64_t va)
 * body addresses: 384
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

mmu_page_table_t * mmu_page_table_mgr_alloc(uint8_t el,uint8_t level,uint64_t va)

{
  pte_t *ppVar1;
  mmu_page_table_t *mpt;
  mmu_page_table_mgr_t *pmVar2;
  uint uVar3;
  u_int uVar4;
  char *pcVar5;
  uint32_t uVar6;
  pte_t *ppVar7;
  
  uVar4 = mp4_get_cpu();
  pmVar2 = &g_mmu_page_table_mgr_core0;
  if (uVar4 != 0) {
    pmVar2 = &g_mmu_page_table_mgr_core1;
  }
  uVar6 = pmVar2->mptm_table_max;
  if (uVar6 == 0) {
    uVar6 = (uint32_t)((ulong)((long)pmVar2->mptm_ptr_end - (long)pmVar2->mptm_ptr_begin) >> 0xc);
    pmVar2->mptm_table_max = uVar6;
  }
  if (pmVar2->mptm_table_count < uVar6) {
    uVar3 = pmVar2->mptm_mpt_count;
    if (uVar3 < pmVar2->mptm_mpt_max) {
      pmVar2->mptm_mpt_count = uVar3 + 1;
      mpt = pmVar2->mptm_mpt + uVar3;
      mmu_page_table_init(mpt,0xff,0xff,0,pmVar2->mptm_ptr_cur);
      pmVar2->mptm_ptr_cur = pmVar2->mptm_ptr_cur + 0x200;
      pmVar2->mptm_table_count = pmVar2->mptm_table_count + 1;
      if (mpt != (mmu_page_table_t *)0x0) {
        ppVar7 = mpt->mpt_table;
        mpt->mpt_el = el;
        mpt->mpt_level = level;
        mpt->mpt_vbase = va & 0xffffffffffe00000;
        ppVar1 = ppVar7 + 0x200;
        for (; ppVar7 < ppVar1; ppVar7 = ppVar7 + 1) {
          *ppVar7 = 0;
        }
        return mpt;
      }
      goto LAB_00112e40;
    }
  }
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:.mptm_table_count=0x%02x, .mptm_table_max=0x%02x\n",(ulong)uVar4,
             "mmu_page_table_mgr_alloc_core",(ulong)pmVar2->mptm_table_count,
             (ulong)pmVar2->mptm_table_max);
  uVar4 = mp4_get_cpu();
  printf_low("%d:%s:.mptm_mpt_count=0x%02x, .mptm_mpt_max=0x%02x\n",(ulong)uVar4,
             "mmu_page_table_mgr_alloc_core",(ulong)pmVar2->mptm_mpt_count,
             (ulong)pmVar2->mptm_mpt_max);
  pcVar5 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar5,"mmu_page_table_mgr_alloc_core",0x603,0,"0");
LAB_00112e40:
  pcVar5 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(pcVar5,"mmu_page_table_mgr_alloc",0x61c,0,"0");
  return (mmu_page_table_t *)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112e84
 * symbol: mmu_init_phase2a
 * prototype: void mmu_init_phase2a(void)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mmu_init_phase2a(void)

{
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112e88
 * symbol: mmu_init_phase2b
 * prototype: void mmu_init_phase2b(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mmu_init_phase2b(void)

{
  mmu_map_mode_t in_w4;
  mmu_mem_type_t in_w5;
  
  mmu_el3_level2_0_op_range_be(0x6000000,0x88200000,0x6200000,2,in_w4,in_w5);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112e9c
 * symbol: mmu_init_phase3
 * prototype: void mmu_init_phase3(void)
 * body addresses: 156
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mmu_init_phase3(void)

{
  u_int uVar1;
  mmu_map_mode_t in_w4;
  mmu_mem_type_t in_w5;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"mmu_init_phase3");
  mmu_el3_level2_0_op_range_be(0x40200000,mmu_op_map,0x40400000,3,in_w4,in_w5);
  mmu_el3_level2_0_op_range_be(0x40400000,mmu_op_map,0x40600000,2,in_w4,in_w5);
  mmu_el3_level2_0_unmap_range_be(0x40600000,0x44000000);
  mmu_el3_level2_0_unmap_range_be(0x50000000,0x80000000);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:<-\n",(ulong)uVar1,"mmu_init_phase3");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00112f38
 * symbol: mmu_el3_level2_0_unmap_range_be
 * prototype: int mmu_el3_level2_0_unmap_range_be(uint64_t vbegin, uint64_t vend)
 * body addresses: 304
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_el3_level2_0_unmap_range_be(uint64_t vbegin,uint64_t vend)

{
  mmu_page_table_t *mpt;
  int iVar1;
  ulong va;
  pte_t *ppVar2;
  uint64_t uVar3;
  char *pcVar4;
  
  mpt = &g_mmu_page_table_el3_level2;
  if (vbegin >> 0x1e != 0) {
    mpt = &g_mmu_page_table_el3_level2_2;
  }
  mmu_page_table_check_be(mpt,vbegin,vend);
  va = mmu_page_table_get_vbase(mpt,vbegin);
  ppVar2 = mmu_page_table_get_ppte(mpt,va);
  do {
    *ppVar2 = *ppVar2 & 0xfffffffffffffffc;
    uVar3 = mmu_page_table_get_entry_size(mpt);
    va = uVar3 + va;
    ppVar2 = ppVar2 + 1;
  } while (va < vend);
  mmu_page_table_sync_all(mpt);
  pcVar4 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  iVar1 = mmu_page_table_access_check_range_be(mpt,vbegin,vend,mmu_access_read_ng);
  el3_assert(pcVar4,"mmu_page_table_unmap_range_be",0x343,(uint)(iVar1 == 0),
             "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_read_ng) == 0");
  pcVar4 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  iVar1 = mmu_page_table_access_check_range_be(mpt,vbegin,vend,mmu_access_write_ng);
  el3_assert(pcVar4,"mmu_page_table_unmap_range_be",0x344,(uint)(iVar1 == 0),
             "mmu_page_table_access_check_range_be(mpt, vbegin, vend, mmu_access_write_ng) == 0");
  return (int)pcVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113068
 * symbol: mmu_init_phase4
 * prototype: void mmu_init_phase4(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mmu_init_phase4(void)

{
  ulong uVar1;
  
  uVar1 = sctlr_el3;
  sctlr_el3 = uVar1 & 0xffffffff | 0x80000;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011307c
 * symbol: mmu_page_table_check_be
 * prototype: int mmu_page_table_check_be(mmu_page_table_t * mpt, uint64_t begin, uint64_t end)
 * body addresses: 616
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_page_table_check_be(mmu_page_table_t *mpt,uint64_t begin,uint64_t end)

{
  u_int uVar1;
  char *pcVar2;
  char *file;
  uint c;
  long lVar3;
  
  if ((ulong)(long)(char)mpt->mpt_level < 4) {
    lVar3 = *(long *)(&DAT_001206a0 + (long)(char)mpt->mpt_level * 8);
  }
  else {
    pcVar2 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar2,"mmu_page_table_get_table_vsize",0xd4,0,"0");
    lVar3 = -1;
  }
  if (begin < end) {
    if (begin < mpt->mpt_vbase) {
      uVar1 = mp4_get_cpu();
      printf_low("%d:%s:req:  begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be"
                 ,begin,end);
      uVar1 = mp4_get_cpu();
      printf_low("%d:%s:table:begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be"
                 ,mpt->mpt_vbase,mpt->mpt_vbase + lVar3);
    }
    pcVar2 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar2,"mmu_page_table_check_be",0x1e6,(uint)(mpt->mpt_vbase <= begin),
               "mpt->mpt_vbase <= begin");
    if (mpt->mpt_vbase + lVar3 <= begin) {
      uVar1 = mp4_get_cpu();
      printf_low("%d:%s:req:  begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be"
                 ,begin,end);
      uVar1 = mp4_get_cpu();
      printf_low("%d:%s:table:begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be"
                 ,mpt->mpt_vbase,mpt->mpt_vbase + lVar3);
    }
    pcVar2 = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(pcVar2,"mmu_page_table_check_be",0x1ec,(uint)(begin < mpt->mpt_vbase + lVar3),
               "begin < mpt->mpt_vbase + table_size");
    if (mpt->mpt_vbase + lVar3 < end) {
      uVar1 = mp4_get_cpu();
      printf_low("%d:%s:req:  begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be"
                 ,begin,end);
      uVar1 = mp4_get_cpu();
      printf_low("%d:%s:table:begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be"
                 ,mpt->mpt_vbase,mpt->mpt_vbase + lVar3);
    }
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    pcVar2 = "end <= mpt->mpt_vbase + table_size";
    uVar1 = 0x1f2;
    c = (uint)(end <= mpt->mpt_vbase + lVar3);
  }
  else {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:begin=0x%016lx, end=0x%016lx\n",(ulong)uVar1,"mmu_page_table_check_be",begin,
               end);
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    pcVar2 = "0";
    uVar1 = 0x1df;
    c = 0;
  }
  el3_assert(file,"mmu_page_table_check_be",uVar1,c,pcVar2);
  return (int)file;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001132e4
 * symbol: mmu_page_table_get_vbase
 * prototype: uint64_t mmu_page_table_get_vbase(mmu_page_table_t * mpt, uint64_t va)
 * body addresses: 112
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t mmu_page_table_get_vbase(mmu_page_table_t *mpt,uint64_t va)

{
  uint8_t uVar1;
  char *file;
  
  uVar1 = mpt->mpt_level;
  if (uVar1 == '\x03') {
    return va & 0xfffffffffffff000;
  }
  if (uVar1 != '\x02') {
    if (uVar1 == '\x01') {
      return va & 0xffffffffc0000000;
    }
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(file,"mmu_page_table_get_vbase",0x126,0,"0");
    return 0xffffffffffffffff;
  }
  return va & 0xffffffffffe00000;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113354
 * symbol: mmu_page_table_sync_all
 * prototype: int mmu_page_table_sync_all(mmu_page_table_t * mpt)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_page_table_sync_all(mmu_page_table_t *mpt)

{
  uint8_t uVar1;
  
  uVar1 = mpt->mpt_el;
  if (uVar1 == '\x03') {
    TLBI_ALLE3();
  }
  else if (uVar1 == '\x02') {
    TLBI_ALLE2();
  }
  else if (uVar1 == '\x01') {
    TLBI_ALLE1();
  }
  else {
    mpt = (mmu_page_table_t *)
          mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert((char *)mpt,"mmu_page_table_sync_all",0xa7,0,"0");
  }
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  return (int)mpt;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001133c8
 * symbol: mmu_page_table_access_check_range_be
 * prototype: int mmu_page_table_access_check_range_be(mmu_page_table_t * mpt, uint64_t vbegin, uint64_t vend, mmu_access_check_t type)
 * body addresses: 424
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_access_check_range_be
              (mmu_page_table_t *mpt,uint64_t vbegin,uint64_t vend,mmu_access_check_t type)

{
  int iVar1;
  u_int uVar2;
  ulong va;
  char *format;
  uint64_t uVar3;
  ulong uVar4;
  int iVar5;
  uint64_t local_68;
  
  va = mmu_page_table_get_vbase(mpt,vbegin);
  iVar5 = 0;
  do {
    if (vend <= va) {
      return iVar5;
    }
    switch(type) {
    case mmu_access_read_ok:
      iVar1 = mmu_page_table_access_check_read(mpt,va,&local_68);
      break;
    case mmu_access_read_ng:
      iVar1 = mmu_page_table_access_check_read(mpt,va,&local_68);
      goto joined_r0x001134bc;
    case mmu_access_write_ok:
      iVar1 = mmu_page_table_access_check_write(mpt,va,&local_68);
      goto joined_r0x001134e4;
    case mmu_access_write_ng:
      iVar1 = mmu_page_table_access_check_write(mpt,va,&local_68);
      goto joined_r0x00113510;
    case mmu_access_el0_read_ok:
      iVar1 = mmu_page_table_access_check_el0_read(mpt,va,&local_68);
      break;
    case mmu_access_el0_read_ng:
      iVar1 = mmu_page_table_access_check_el0_read(mpt,va,&local_68);
joined_r0x001134bc:
      if (iVar1 == 0) goto LAB_001134c0;
      goto switchD_00113430_caseD_8;
    case mmu_access_el0_write_ok:
      iVar1 = mmu_page_table_access_check_el0_write(mpt,va,&local_68);
joined_r0x001134e4:
      if (iVar1 != 0) {
        uVar2 = mp4_get_cpu();
        uVar4 = (ulong)uVar2;
        format = "%d:%s:WARNING!!!: WRITE NG: 0x%016lx -> 0x%016lx\n";
        goto LAB_00113528;
      }
      goto switchD_00113430_caseD_8;
    case mmu_access_el0_write_ng:
      iVar1 = mmu_page_table_access_check_el0_write(mpt,va,&local_68);
joined_r0x00113510:
      if (iVar1 == 0) {
        uVar2 = mp4_get_cpu();
        uVar4 = (ulong)uVar2;
        format = "%d:%s:WARNING!!!: WRITE OK: 0x%016lx -> 0x%016lx\n";
        goto LAB_00113528;
      }
    default:
      goto switchD_00113430_caseD_8;
    }
    if (iVar1 != 0) {
LAB_001134c0:
      uVar2 = mp4_get_cpu();
      uVar4 = (ulong)uVar2;
      format = "%d:%s:WARNING!!!: READ NG: 0x%016lx -> 0x%016lx\n";
LAB_00113528:
      printf_low(format,uVar4,"mmu_page_table_access_check_range_be",va,local_68);
      iVar5 = -1;
    }
switchD_00113430_caseD_8:
    uVar3 = mmu_page_table_get_entry_size(mpt);
    va = uVar3 + va;
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113570
 * symbol: mmu_page_table_get_entry_size
 * prototype: uint64_t mmu_page_table_get_entry_size(mmu_page_table_t * mpt)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t mmu_page_table_get_entry_size(mmu_page_table_t *mpt)

{
  char *file;
  
  if ((ulong)(long)(char)mpt->mpt_level < 4) {
    return *(uint64_t *)(&DAT_001206e0 + (long)(char)mpt->mpt_level * 8);
  }
  file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(file,"mmu_page_table_get_entry_size",0xe7,0,"0");
  return 0xffffffffffffffff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001135c8
 * symbol: mmu_page_table_access_check_write
 * prototype: int mmu_page_table_access_check_write(mmu_page_table_t * mpt, uint64_t va, uint64_t * pa)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_access_check_write(mmu_page_table_t *mpt,uint64_t va,uint64_t *pa)

{
  uint8_t uVar1;
  undefined8 uVar2;
  uint64_t uVar3;
  char *file;
  
  uVar1 = mpt->mpt_el;
  if (uVar1 == '\x03') {
    uVar2 = AT_S1E3W(va);
    par_el1 = uVar2;
  }
  else if (uVar1 == '\x02') {
    uVar2 = AT_S1E2W(va);
    par_el1 = uVar2;
  }
  else if (uVar1 == '\x01') {
    uVar2 = AT_S1E1W(va);
    par_el1 = uVar2;
  }
  else {
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
    el3_assert(file,"mmu_page_table_access_check_write",0x155,0,"0");
  }
  uVar3 = par_el1;
  if (pa != (uint64_t *)0x0) {
    *pa = uVar3;
  }
  return -((uint)uVar3 & 1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113650
 * symbol: mmu_page_table_access_check_el0_read
 * prototype: int mmu_page_table_access_check_el0_read(mmu_page_table_t * mpt, uint64_t va, uint64_t * pa)
 * body addresses: 112
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_access_check_el0_read(mmu_page_table_t *mpt,uint64_t va,uint64_t *pa)

{
  undefined8 uVar1;
  uint64_t uVar2;
  char *file;
  
  file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(file,"mmu_page_table_access_check_el0_read",0x166,(uint)(mpt->mpt_el == '\x01'),
             "mpt->mpt_el == MMU_EL1");
  uVar1 = AT_S1E0R(va);
  par_el1 = uVar1;
  uVar2 = par_el1;
  if (pa != (uint64_t *)0x0) {
    *pa = uVar2;
  }
  return -((uint)uVar2 & 1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001136c0
 * symbol: mmu_page_table_access_check_el0_write
 * prototype: int mmu_page_table_access_check_el0_write(mmu_page_table_t * mpt, uint64_t va, uint64_t * pa)
 * body addresses: 112
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mmu_page_table_access_check_el0_write(mmu_page_table_t *mpt,uint64_t va,uint64_t *pa)

{
  undefined8 uVar1;
  uint64_t uVar2;
  char *file;
  
  file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\mmu.c");
  el3_assert(file,"mmu_page_table_access_check_el0_write",0x176,(uint)(mpt->mpt_el == '\x01'),
             "mpt->mpt_el == MMU_EL1");
  uVar1 = AT_S1E0W(va);
  par_el1 = uVar1;
  uVar2 = par_el1;
  if (pa != (uint64_t *)0x0) {
    *pa = uVar2;
  }
  return -((uint)uVar2 & 1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00113730
 * symbol: mmu_el3_level2_0_op_range_be
 * prototype: int mmu_el3_level2_0_op_range_be(uint64_t vbegin, mmu_op_t op, uint64_t pbegin, uint64_t vend, mmu_map_mode_t mode, mmu_mem_type_t mem)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int mmu_el3_level2_0_op_range_be
              (uint64_t vbegin,mmu_op_t op,uint64_t pbegin,uint64_t vend,mmu_map_mode_t mode,
              mmu_mem_type_t mem)

{
  mmu_page_table_t *mpt;
  int iVar1;
  mmu_mem_type_t in_w6;
  
  mpt = &g_mmu_page_table_el3_level2;
  if (vbegin >> 0x1e != 0) {
    mpt = &g_mmu_page_table_el3_level2_2;
  }
  iVar1 = mmu_page_table_op_range_be
                    (mpt,(mmu_op_t)vbegin,(ulong)op,pbegin,vend & 0xffffffff,map_mode_ro,in_w6);
  return iVar1;
}


