/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\mp4_timer.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114868
 * symbol: mp4_timer_get_cnt
 * prototype: uint32_t mp4_timer_get_cnt(uint id)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t mp4_timer_get_cnt(uint id)

{
  return *(uint32_t *)(ulong)(id * 0x24 + 0x3200420);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114880
 * symbol: mp4_timer_init
 * prototype: int mp4_timer_init(void)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mp4_timer_init(void)

{
  long lVar1;
  
  for (lVar1 = 0; lVar1 != 0x90; lVar1 = lVar1 + 0x24) {
    *(undefined4 *)(lVar1 + 0x3200400) = 0x100;
    *(undefined4 *)(lVar1 + 0x3200400) = 1;
  }
  return 0;
}


