/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\msi.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110534
 * symbol: msi_write_scratch0
 * prototype: void msi_write_scratch0(uint32_t v)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void msi_write_scratch0(uint32_t v)

{
  _DAT_03010050 = v;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110544
 * symbol: msi_write_scratch1
 * prototype: void msi_write_scratch1(uint32_t v)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void msi_write_scratch1(uint32_t v)

{
  _DAT_03010054 = v;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110554
 * symbol: msi_write_scratch2
 * prototype: void msi_write_scratch2(uint32_t v)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void msi_write_scratch2(uint32_t v)

{
  _DAT_03010058 = v;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110564
 * symbol: msi_write_scratch3
 * prototype: void msi_write_scratch3(uint32_t v)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void msi_write_scratch3(uint32_t v)

{
  _DAT_0301005c = v;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110574
 * symbol: msi_write_p2c_command
 * prototype: void msi_write_p2c_command(uint32_t core, uint32_t v)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void msi_write_p2c_command(uint32_t core,uint32_t v)

{
  uint uVar1;
  u_int uVar2;
  
  if (core == 1) {
    uVar1 = 0x30f1000;
  }
  else {
    if (core != 0) {
      uVar2 = mp4_get_cpu();
      printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar2,"msi_write_p2c_command",
                 (ulong)core);
    }
    uVar1 = 0x3010500;
  }
  *(uint32_t *)(ulong)uVar1 = v;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001105d8
 * symbol: msi_read_c2p_command
 * prototype: uint32_t msi_read_c2p_command(uint32_t core)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t msi_read_c2p_command(uint32_t core)

{
  u_int uVar1;
  uint32_t *puVar2;
  
  puVar2 = (uint32_t *)&DAT_030f6000;
  if (core == 1) {
    puVar2 = (uint32_t *)&DAT_030fb000;
  }
  else if (core != 0) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_read_c2p_command",(ulong)core
              );
  }
  return *puVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110634
 * symbol: msi_read_c2p_arg1
 * prototype: uint32_t msi_read_c2p_arg1(uint32_t core)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t msi_read_c2p_arg1(uint32_t core)

{
  u_int uVar1;
  uint32_t *puVar2;
  
  puVar2 = (uint32_t *)&DAT_030f7000;
  if (core == 1) {
    puVar2 = (uint32_t *)&DAT_030fc000;
  }
  else if (core != 0) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_read_c2p_arg1",(ulong)core);
  }
  return *puVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110690
 * symbol: msi_write_c2p_ack
 * prototype: void msi_write_c2p_ack(uint32_t core, uint32_t command)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void msi_write_c2p_ack(uint32_t core,uint32_t command)

{
  u_int uVar1;
  uint32_t *puVar2;
  
  puVar2 = (uint32_t *)&DAT_030fa000;
  if (core == 1) {
    puVar2 = (uint32_t *)&DAT_030ff000;
  }
  else if (core != 0) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_write_c2p_ack",(ulong)core);
  }
  *puVar2 = command;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001106f8
 * symbol: msi_send_command_nosync
 * prototype: int msi_send_command_nosync(uint32_t core, uint32_t command0)
 * body addresses: 316
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int msi_send_command_nosync(uint32_t core,uint32_t command0)

{
  uint v;
  u_int uVar1;
  uint32_t uVar2;
  uint32_t uVar3;
  
  if (core == 1) {
    g_msi_p2c_count_core1 = g_msi_p2c_count_core1 + 1;
    g_msi_p2c_prev_core1 = command0 & 0xfffff000 | g_msi_p2c_count_core1 & 0xff;
    msi_write_p2c_command(1,g_msi_p2c_prev_core1);
    uVar2 = g_msi_vector + 3;
    uVar3 = g_msi_addr;
  }
  else if (core == 0) {
    g_msi_p2c_count_core0 = g_msi_p2c_count_core0 + 1;
    g_msi_p2c_prev_core0 = command0 & 0xfffff000 | g_msi_p2c_count_core0 & 0xff;
    msi_write_p2c_command(0,g_msi_p2c_prev_core0);
    uVar3 = g_msi_addr;
    uVar2 = g_msi_vector;
  }
  else {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_make_command",(ulong)core);
    g_msi_p2c_count_core0 = g_msi_p2c_count_core0 + 1;
    v = command0 & 0xfffff000 | g_msi_p2c_count_core0 & 0xff;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_set_prev",(ulong)core);
    g_msi_p2c_prev_core0 = v;
    msi_write_p2c_command(core,v);
    uVar3 = g_msi_addr;
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_send",(ulong)core);
    uVar2 = g_msi_vector;
  }
  *(uint32_t *)(ulong)(uVar3 + 0xf8000000) = uVar2;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110834
 * symbol: msi_send_command_sync
 * prototype: int msi_send_command_sync(uint32_t core, uint32_t command)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int msi_send_command_sync(uint32_t core,uint32_t command)

{
  uint32_t uVar1;
  uint32_t uVar2;
  
  uVar1 = msi_get_prev(core);
  if (uVar1 != 0) {
    do {
      uVar2 = msi_read_p2c_ack(core);
    } while (uVar2 != uVar1);
  }
  msi_send_command_nosync(core,command);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110890
 * symbol: msi_get_prev
 * prototype: uint32_t msi_get_prev(uint32_t core)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t msi_get_prev(uint32_t core)

{
  u_int uVar1;
  uint32_t *puVar2;
  
  if (core != 0) {
    if (core == 1) {
      puVar2 = &g_msi_p2c_prev_core1;
      goto LAB_001108e0;
    }
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_get_prev",(ulong)core);
  }
  puVar2 = &g_msi_p2c_prev_core0;
LAB_001108e0:
  return *puVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001108f0
 * symbol: msi_read_p2c_ack
 * prototype: uint32_t msi_read_p2c_ack(uint32_t core)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t msi_read_p2c_ack(uint32_t core)

{
  u_int uVar1;
  uint32_t *puVar2;
  
  puVar2 = (uint32_t *)&DAT_030f0000;
  if (core == 1) {
    puVar2 = (uint32_t *)&DAT_030f5000;
  }
  else if (core != 0) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar1,"msi_read_p2c_ack",(ulong)core);
  }
  return *puVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110948
 * symbol: msi_send_write_sig
 * prototype: int msi_send_write_sig(uint32_t core, uint32_t arg1, uint32_t arg2, uint32_t arg3, uint32_t hint0)
 * body addresses: 324
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int msi_send_write_sig(uint32_t core,uint32_t arg1,uint32_t arg2,uint32_t arg3,uint32_t hint0)

{
  uint32_t uVar1;
  uint32_t uVar2;
  u_int uVar3;
  uint32_t *puVar4;
  
  uVar1 = msi_get_prev(core);
  if (uVar1 != 0) {
    do {
      uVar2 = msi_read_p2c_ack(core);
    } while (uVar2 != uVar1);
  }
  if (core == 0) {
    puVar4 = (uint32_t *)&DAT_0301050c;
    _DAT_03010504 = arg1;
    _DAT_03010508 = arg2;
  }
  else if (core == 1) {
    puVar4 = (uint32_t *)&DAT_030f4000;
    _DAT_030f2000 = arg1;
    _DAT_030f3000 = arg2;
  }
  else {
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar3,"msi_write_p2c_arg1",(ulong)core);
    _DAT_03010504 = arg1;
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar3,"msi_write_p2c_arg2",(ulong)core);
    _DAT_03010508 = arg2;
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar3,"msi_write_p2c_arg3",(ulong)core);
    puVar4 = (uint32_t *)&DAT_0301050c;
  }
  *puVar4 = arg3;
  _DAT_03010050 = hint0;
  _DAT_03010054 = hint0;
  _DAT_03010058 = hint0;
  _DAT_0301005c = hint0;
  msi_send_command_nosync(core,0x10213000);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110a8c
 * symbol: msi_has_internal_qaf
 * prototype: int msi_has_internal_qaf(void)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int msi_has_internal_qaf(void)

{
  return g_flags & 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110a9c
 * symbol: msi_get_msi_address32
 * prototype: uint32_t msi_get_msi_address32(void)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t msi_get_msi_address32(void)

{
  return g_msi_addr;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110aac
 * symbol: msi_get_msi_offset
 * prototype: uint32_t msi_get_msi_offset(void)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t msi_get_msi_offset(void)

{
  return g_msi_offset;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110abc
 * symbol: msi_get_vector_for_mm
 * prototype: uint16_t msi_get_vector_for_mm(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t msi_get_vector_for_mm(void)

{
  return (short)g_msi_vector + 2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110ad0
 * symbol: msi_get_vector_for_io
 * prototype: uint16_t msi_get_vector_for_io(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t msi_get_vector_for_io(void)

{
  return (short)g_msi_vector + 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110ae4
 * symbol: msi_get_vector_1st_core
 * prototype: uint16_t msi_get_vector_1st_core(void)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t msi_get_vector_1st_core(void)

{
  return (uint16_t)g_msi_vector;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110af4
 * symbol: msi_get_vector_2nd_core
 * prototype: uint16_t msi_get_vector_2nd_core(void)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t msi_get_vector_2nd_core(void)

{
  return (short)g_msi_vector + 3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110b08
 * symbol: msi_get_main_param
 * prototype: main_mp4_param_t * msi_get_main_param(void)
 * body addresses: 12
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

main_mp4_param_t * msi_get_main_param(void)

{
  return (main_mp4_param_t *)&DAT_88000c00;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110b14
 * symbol: msi_get_info_by_1st_core
 * prototype: int msi_get_info_by_1st_core(void)
 * body addresses: 796
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int msi_get_info_by_1st_core(void)

{
  u_int uVar1;
  char *file;
  
  _DAT_03010500 = 0x10110000;
  do {
  } while (_DAT_030f6000 >> 0xc != 0x20113);
  g_msi_addr = _DAT_030f8000;
  g_msi_vector = _DAT_030f9000;
  _DAT_030fa000 = _DAT_030f6000;
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_self_size                 = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",(ulong)_DAT_88000c00);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_magic                     = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",(ulong)_DAT_88000c04);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_flags                     = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",(ulong)_DAT_88000c08);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_reserved                  = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",(ulong)_DAT_88000c0c);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_cyclecount                = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c10);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_msi_address               = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",CONCAT44(uRam0000000088000c1c,_DAT_88000c18));
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_msi_vector_loader0        = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c20);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_msi_io                    = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c28);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_msi_mm                    = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c30);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_msi_vector_loader1        = 0x%08x\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c38);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_pasid_kernel              = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c40);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_mm_rings_ioma             = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c48);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_mapper_page_table_pa      = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c50);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_mapper_page_table_ioma    = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c58);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_iommu_command_buffer_pa   = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c60);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mm4p_iommu_command_buffer_size = 0x%016lx\n",(ulong)uVar1,
             "msi_get_info_by_1st_core",_DAT_88000c68);
  mp4_iommu_map_info_print((mp4_iommu_map_info_t *)0x88000c88,"g6_fix");
  mp4_iommu_map_info_print((mp4_iommu_map_info_t *)0x88000d30,"iommu_mmio");
  mp4_iommu_map_info_print((mp4_iommu_map_info_t *)0x88000d68,"sdma0_mmio");
  mp4_iommu_map_info_print((mp4_iommu_map_info_t *)0x88000da0,"sdma1_mmio");
  mp4_iommu_map_info_print((mp4_iommu_map_info_t *)0x88000dd8,"sdma0_rb");
  mp4_iommu_map_info_print((mp4_iommu_map_info_t *)0x88000e10,"sdma1_rb");
  if (_DAT_88000c00 != 0x248) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:Invalid mm4p_self_size = 0x%08x != 0x%08x\n",(ulong)uVar1,
               "msi_get_info_by_1st_core",(ulong)_DAT_88000c00,0x248);
    file = mp4_basename("I:\\a53_sys\\releases_00.70\\mp4\\a53\\src\\loader\\el3\\msi.c");
    el3_assert(file,"msi_get_info_by_1st_core",0x278,0,"0");
  }
  g_flags = _DAT_88000c08;
  g_msi_addr = _DAT_88000c18;
  g_msi_offset = _DAT_88000c18 + 0x4000000;
  g_msi_vector = (uint32_t)_DAT_88000c20;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110e30
 * symbol: mp4_iommu_map_info_print
 * prototype: void mp4_iommu_map_info_print(mp4_iommu_map_info_t * mimi, char * member)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mp4_iommu_map_info_print(mp4_iommu_map_info_t *mimi,char *member)

{
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:%s.mimi_pa         = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_print",member,
             mimi->mimi_pa);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:%s.mimi_iommu_addr = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_print",member,
             mimi->mimi_iommu_addr);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:%s.mimi_iommu_size = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_print",member,
             mimi->mimi_iommu_size);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110ebc
 * symbol: msi_get_info_by_2nd_core
 * prototype: int msi_get_info_by_2nd_core(void)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int msi_get_info_by_2nd_core(void)

{
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110ec4
 * symbol: msi_wait_command
 * prototype: int msi_wait_command(uint32_t cpu)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int msi_wait_command(uint32_t cpu)

{
  uint32_t uVar1;
  u_int uVar2;
  uint32_t uVar3;
  uint32_t *puVar4;
  
  puVar4 = (uint32_t *)&DAT_030fa000;
  if (cpu == 1) {
    puVar4 = (uint32_t *)&DAT_030ff000;
  }
  else if (cpu != 0) {
    uVar2 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport core=0x%08x Use 0\n",(ulong)uVar2,"msi_read_c2p_ack",(ulong)cpu);
  }
  uVar1 = *puVar4;
  do {
    uVar3 = msi_read_c2p_command(cpu);
  } while (uVar3 == uVar1);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00110f44
 * symbol: msi_test
 * prototype: int msi_test(void)
 * body addresses: 332
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int msi_test(void)

{
  u_int uVar1;
  int *piVar2;
  uint uVar3;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"msi_test");
  mp4_get_cpu();
  piVar2 = (int *)(ulong)(g_msi_offset + 0xf4000000);
  for (uVar3 = 0; uVar3 != 10; uVar3 = uVar3 + 1) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:MSI TEST: %d: write 0x%08x + 1 to %p\n",(ulong)uVar1,"msi_test",(ulong)uVar3,
               (ulong)g_msi_vector,piVar2);
    *piVar2 = g_msi_vector + 1;
  }
  for (uVar3 = 0; uVar3 != 10; uVar3 = uVar3 + 1) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:MSI TEST: %d: write 0x%08x + 2 to %p\n",(ulong)uVar1,"msi_test",(ulong)uVar3,
               (ulong)g_msi_vector,piVar2);
    *piVar2 = g_msi_vector + 2;
  }
  for (uVar3 = 0; uVar3 != 10; uVar3 = uVar3 + 1) {
    uVar1 = mp4_get_cpu();
    printf_low("%d:%s:MSI TEST: %d: write 0x%08x + 3 to %p\n",(ulong)uVar1,"msi_test",(ulong)uVar3,
               (ulong)g_msi_vector,piVar2);
    *piVar2 = g_msi_vector + 3;
  }
  return 0;
}


