/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\pericom.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bf3c
 * symbol: putchar_pericom
 * prototype: int putchar_pericom(int c)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int putchar_pericom(int c)

{
  uint8_t *base;
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  base = (uint8_t *)0xbd110000;
  if (uVar1 != 0) {
    base = (uint8_t *)0xbd110200;
  }
  pericom_putchar(base,c);
  return c;
}


