/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\printf_EL3.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bcd0
 * symbol: printf_low
 * prototype: int printf_low(char * format, ...)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int printf_low(char *format,...)

{
  int iVar1;
  
  iVar1 = prnt(putchar_low_hook,(void *)0x0,format,(va_list *)&stack0xffffffffffffffb0);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bd3c
 * symbol: putchar_low_hook
 * prototype: void putchar_low_hook(void * pfd, int ch)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void putchar_low_hook(void *pfd,int ch)

{
  if ((ch | 1U) == 0x201) {
    return;
  }
  putchar_low(ch);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bd54
 * symbol: printf_cp
 * prototype: int printf_cp(char * format, ...)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int printf_cp(char *format,...)

{
  int iVar1;
  
  iVar1 = prnt(putchar_cp_hook,(void *)0x0,format,(va_list *)&stack0xffffffffffffffb0);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bdc0
 * symbol: putchar_cp_hook
 * prototype: void putchar_cp_hook(void * pfd, int ch)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void putchar_cp_hook(void *pfd,int ch)

{
  if ((ch | 1U) == 0x201) {
    return;
  }
  putchar_cp(ch);
  return;
}


