/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\putchar_low.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bed0
 * symbol: putchar_low
 * prototype: int putchar_low(int c)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int putchar_low(int c)

{
  dev_context_t *pdVar1;
  
  pdVar1 = get_dev_context();
  if (c == 10) {
    (*pdVar1->dc_putchar_low_hook)(0xd);
  }
  (*pdVar1->dc_putchar_low_hook)(c);
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bf18
 * symbol: putchar_cp
 * prototype: int putchar_cp(int c)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int putchar_cp(int c)

{
  mp4_debug_status_putchar(c);
  return c;
}


