/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\puts_EL3.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bdd8
 * symbol: write_EL3
 * prototype: int write_EL3(char * msg, uint64_t len)
 * body addresses: 192
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int write_EL3(char *msg,uint64_t len)

{
  code *pcVar1;
  u_int uVar2;
  int iVar3;
  uint8_t *puVar4;
  uint32_t bit;
  ulong uVar5;
  
  puVar4 = el0_va_to_el3_va((uint8_t *)msg);
  uVar2 = mp4_get_cpu();
  bit = 0x2000000;
  if (uVar2 != 0) {
    bit = 0x20000;
  }
  iVar3 = cp_param_check(bit);
  pcVar1 = putchar_cp;
  if (iVar3 != 0) {
    pcVar1 = putchar_pericom;
  }
  (*pcVar1)(0x45);
  (*pcVar1)(0x4c);
  (*pcVar1)(0x30);
  (*pcVar1)(0x3a);
  (*pcVar1)(uVar2 + 0x30);
  (*pcVar1)(0x3a);
  for (uVar5 = 0; (uVar5 & 0xffffffff) < len; uVar5 = uVar5 + 1) {
    (*pcVar1)(puVar4[uVar5]);
  }
  return (int)len;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010be98
 * symbol: puts_EL3
 * prototype: int puts_EL3(char * msg)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int puts_EL3(char *msg)

{
  size_t len;
  
  len = strnlen(msg,0x200);
  deci5s_send_sttyp(msg,len);
  return (int)len;
}


