/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\smnif.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001146e4
 * symbol: smnif_init
 * prototype: int smnif_init(void)
 * body addresses: 224
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int smnif_init(void)

{
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"smnif_init");
  _DAT_03220000 = 0x24;
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:mmSMNIF_TLB_0: 0x%08x = 0x%08x\n",(ulong)uVar1,"smnif_init",&DAT_03220000,
             (ulong)_DAT_03220000);
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:addr:0x%08x = 0x%08x\n",(ulong)uVar1,"smnif_init",&DAT_0100a000,
             (ulong)_DAT_0100a000);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:addr:0x%08x = 0x%08x\n",(ulong)uVar1,"smnif_init",&DAT_01000018,
             (ulong)_DAT_01000018);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:addr:0x%08x = 0x%08x\n",(ulong)uVar1,"smnif_init",&DAT_0100001c,
             (ulong)_DAT_0100001c);
  return 0;
}


