/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\svc.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0010bbdc
 * symbol: svc_EL3
 * prototype: int svc_EL3(uint32_t esr_el1, mp4_debug_status_t * status)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int svc_EL3(uint32_t esr_el1,mp4_debug_status_t *status)

{
  int iVar1;
  int iVar2;
  u_int uVar3;
  
  if ((esr_el1 & 0xffff) == 0x152) {
    iVar1 = write_EL3((char *)status->mds_gpr[0],status->mds_gpr[1]);
    iVar2 = 0;
    status->mds_gpr[0] = (long)iVar1;
  }
  else {
    uVar3 = mp4_get_cpu();
    printf_low("%d:%s:Unsupport imm16\n",(ulong)uVar3,"svc_EL3");
    aarch64_print_ESR_EL1();
    iVar2 = -1;
  }
  return iVar2;
}


