/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/el3\syshub.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001140b0
 * symbol: writel
 * prototype: void writel(uint64_t addr, uint32_t val)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void writel(uint64_t addr,uint32_t val)

{
  *(uint32_t *)addr = val;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001140b8
 * symbol: readl
 * prototype: uint32_t readl(uint64_t addr)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t readl(uint64_t addr)

{
  return *(uint32_t *)addr;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001140c0
 * symbol: syshub_init
 * prototype: int syshub_init(void)
 * body addresses: 216
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int syshub_init(void)

{
  _DAT_03230040 = 0x14;
  _DAT_03230044 = 0x12;
  _DAT_03230048 = 0x40;
  _DAT_0323004c = 0x40;
  _DAT_032303f0 = 0xffffffff;
  _DAT_032304e8 = 0xc1800003;
  _DAT_03230060 = 0x14;
  _DAT_03230064 = 0x12;
  _DAT_03230068 = 0x40;
  _DAT_0323006c = 0x40;
  _DAT_032303f8 = 0xffffffff;
  _DAT_032304f0 = 0xc1800003;
  syshub_tlb_init_iommu(8,0x53a00000,0x200000);
  _DAT_032302b0 = 0x18;
  _DAT_032302b4 = 0x12;
  _DAT_032302b8 = 0x40;
  _DAT_032302bc = 0x40;
  _DAT_0323048c = 0xffffffff;
  _DAT_03230584 = 0xc1800003;
  _DAT_032302c0 = 0x14;
  _DAT_032302c4 = 0x12;
  _DAT_032302c8 = 0x40;
  _DAT_032302cc = 0x40;
  _DAT_03230490 = 0xffffffff;
  _DAT_03230588 = 0xc1800003;
  _DAT_032302d0 = 0x14;
  _DAT_032302d4 = 0x12;
  _DAT_032302d8 = 0;
  _DAT_032302dc = 0;
  _DAT_03230494 = 0xffffffff;
  _DAT_0323058c = 0xc1800003;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114198
 * symbol: syshub_tlb_init_iommu
 * prototype: void syshub_tlb_init_iommu(int tlb, uint64_t phy_addr, uint32_t seg_size)
 * body addresses: 372
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void syshub_tlb_init_iommu(int tlb,uint64_t phy_addr,uint32_t seg_size)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  
  if (seg_size == 0x20000) {
    uVar4 = 0;
    goto LAB_00114270;
  }
  if (seg_size != 0x4000000) {
    if (seg_size == 0x80000) {
      uVar4 = 4;
      goto LAB_00114270;
    }
    if (seg_size == 0x100000) {
      uVar4 = 6;
      goto LAB_00114270;
    }
    if (seg_size == 0x200000) {
      uVar4 = 8;
      goto LAB_00114270;
    }
    if (seg_size == 0x400000) {
      uVar4 = 10;
      goto LAB_00114270;
    }
    if (seg_size == 0x800000) {
      uVar4 = 0xc;
      goto LAB_00114270;
    }
    if (seg_size == 0x1000000) {
      uVar4 = 0xe;
      goto LAB_00114270;
    }
    if (seg_size == 0x2000000) {
      uVar4 = 0x10;
      goto LAB_00114270;
    }
    if (seg_size == 0x40000) {
      uVar4 = 2;
      goto LAB_00114270;
    }
    printf_low("Unsupport seg_size 0x%08x\n",(ulong)seg_size);
  }
  uVar4 = 0x12;
LAB_00114270:
  uVar1 = (uint)phy_addr & 0xfc000000;
  iVar2 = tlb + -1;
  uVar3 = (uint)phy_addr - uVar1;
  if (uVar3 != 0) {
    uVar4 = uVar4 | uVar3 >> 0xc & 0xfffe0;
    printf_low("tlb=%d, 0x%08x, offset=0x%08x, tlb1=0x%08x\n",(ulong)(uint)tlb,(ulong)uVar1,
               (ulong)uVar3,(ulong)uVar4);
  }
  uVar1 = iVar2 * 0x10 + 0x3230000;
  *(int *)(ulong)uVar1 = (int)(phy_addr >> 0x1a);
  *(uint *)(ulong)(uVar1 | 4) = uVar4;
  *(undefined4 *)(ulong)(uVar1 | 8) = 0x40;
  *(undefined4 *)(ulong)(uVar1 | 0xc) = 0x40;
  *(undefined4 *)(ulong)(iVar2 * 4 + 0x32303e0) = 0xffffffff;
  if (tlb != 0x3e) {
    *(undefined4 *)(ulong)(iVar2 * 4 + 0x32304d8) = 0xc1800003;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011430c
 * symbol: syshub_init_after_main_param
 * prototype: int syshub_init_after_main_param(void)
 * body addresses: 428
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int syshub_init_after_main_param(void)

{
  u_int uVar1;
  main_mp4_param_t *pmVar2;
  uint64_t uVar3;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"syshub_init_after_main_param");
  pmVar2 = msi_get_main_param();
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: mm4p_mapper_page_table_ioma     = 0x%016lx\n",(ulong)uVar1,
             "syshub_init_after_main_param",pmVar2->mm4p_mapper_page_table_ioma);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: mm4p_iommu_mmio.mimi_iommu_addr = 0x%016lx\n",(ulong)uVar1,
             "syshub_init_after_main_param",(pmVar2->mm4p_iommu_mmio).mimi_iommu_addr);
  uVar3 = pmVar2->mm4p_mapper_page_table_ioma;
  syshub_tlb_init_iommu(1,uVar3,0x4000000);
  syshub_tlb_init_iommu(2,uVar3 + 0x4000000,0x4000000);
  syshub_tlb_init_iommu(3,uVar3 + 0x8000000,0x4000000);
  syshub_tlb_init_iommu(4,uVar3 + 0xc000000,0x4000000);
  syshub_tlb_init_iommu(5,pmVar2->mm4p_scf_buf_iommu_addr,0x4000000);
  syshub_tlb_init_iommu(6,pmVar2->mm4p_mapper_private_ioma,0x2000000);
  uVar3 = (pmVar2->mm4p_iommu_mmio).mimi_iommu_addr;
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:SYSHUB TLB10 = mm4p_iommu_mmio_ioma = 0x%016lx\n",(ulong)uVar1,
             "syshub_init_after_main_param",uVar3);
  _DAT_03230090 = 0x15;
  _DAT_03230094 = 0x12;
  _DAT_03230098 = 0x40;
  _DAT_0323009c = 0x40;
  _DAT_03230404 = 0xffffffff;
  _DAT_032304fc = 0xc1800003;
  _DAT_032300e0 = 0x3f;
  _DAT_032300e4 = 0x12;
  _DAT_032300e8 = 4;
  _DAT_032300ec = 4;
  _DAT_03230418 = 0xffffffff;
  _DAT_03230510 = 0xc1800003;
  mp4_iommu_map_info_printf(&pmVar2->mm4p_mm_param,"mm_param");
  mp4_iommu_map_info_printf(&pmVar2->mm4p_io_param,"io_param");
  syshub_tlb_init_iommu(0x12,(pmVar2->mm4p_mm_param).mimi_syshub_base,0x4000000);
  syshub_tlb_init_iommu(0x13,(pmVar2->mm4p_io_param).mimi_syshub_base,0x4000000);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001144b8
 * symbol: mp4_iommu_map_info_printf
 * prototype: void mp4_iommu_map_info_printf(mp4_iommu_map_info_t * mimi, char * name)
 * body addresses: 236
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mp4_iommu_map_info_printf(mp4_iommu_map_info_t *mimi,char *name)

{
  u_int uVar1;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: %s.mimi_pa            = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_printf",
             name,mimi->mimi_pa);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: %s.mimi_pa_base       = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_printf",
             name,mimi->mimi_pa_base);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: %s.mimi_iommu_addr    = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_printf",
             name,mimi->mimi_iommu_addr);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: %s.mimi_physical_size = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_printf",
             name,mimi->mimi_physical_size);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: %s.mimi_iommu_size    = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_printf",
             name,mimi->mimi_iommu_size);
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s: %s.mimi_syshub_base   = 0x%016lx\n",(ulong)uVar1,"mp4_iommu_map_info_printf",
             name,mimi->mimi_syshub_base);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001145a4
 * symbol: syshub_init_sdma
 * prototype: int syshub_init_sdma(void)
 * body addresses: 192
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int syshub_init_sdma(void)

{
  u_int uVar1;
  main_mp4_param_t *pmVar2;
  
  uVar1 = mp4_get_cpu();
  printf_low("%d:%s:()\n",(ulong)uVar1,"syshub_init_sdma");
  pmVar2 = msi_get_main_param();
  mp4_iommu_map_info_printf(&pmVar2->mm4p_sdma0_mmio,"sdma0_mmio");
  mp4_iommu_map_info_printf(&pmVar2->mm4p_sdma1_mmio,"sdma0_mmio");
  mp4_iommu_map_info_printf(&pmVar2->mm4p_sdma0_rb,"sdma1_rb");
  mp4_iommu_map_info_printf(&pmVar2->mm4p_sdma1_rb,"sdma1_rb");
  syshub_tlb_init_iommu(0xb,(pmVar2->mm4p_sdma0_mmio).mimi_syshub_base,0x4000000);
  syshub_tlb_init_iommu(0xc,(pmVar2->mm4p_sdma1_mmio).mimi_syshub_base,0x4000000);
  syshub_tlb_init_iommu(0x10,(pmVar2->mm4p_sdma0_rb).mimi_syshub_base,0x4000000);
  syshub_tlb_init_iommu(0x11,(pmVar2->mm4p_sdma1_rb).mimi_syshub_base,0x4000000);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00114664
 * symbol: syshub_init_for_io
 * prototype: int syshub_init_for_io(uint64_t base)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int syshub_init_for_io(uint64_t base)

{
  syshub_tlb_init_iommu(0x15,base,0x4000000);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011468c
 * symbol: syshub_tlb_get
 * prototype: void syshub_tlb_get(uint32_t tlb, uint32_t * tlb0, uint32_t * tlb1, uint32_t * tlb2, uint32_t * tlb3, uint32_t * sub, uint32_t * attr1)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void syshub_tlb_get(uint32_t tlb,uint32_t *tlb0,uint32_t *tlb1,uint32_t *tlb2,uint32_t *tlb3,
                   uint32_t *sub,uint32_t *attr1)

{
  int iVar1;
  uint uVar2;
  
  uVar2 = (tlb - 1) * 0x10 + 0x3230000;
  iVar1 = (tlb - 1) * 4;
  *tlb0 = *(uint32_t *)(ulong)uVar2;
  *tlb1 = *(uint32_t *)(ulong)(uVar2 | 4);
  *tlb2 = *(uint32_t *)(ulong)(uVar2 | 8);
  *tlb3 = *(uint32_t *)(ulong)(uVar2 | 0xc);
  *sub = *(uint32_t *)(ulong)(iVar1 + 0x32303e0);
  *attr1 = *(uint32_t *)(ulong)(iVar1 + 0x32304d8);
  return;
}


