/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\aarch64.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011843c
 * symbol: aarch64_DC_CVAC_range_be
 * prototype: int aarch64_DC_CVAC_range_be(void * vbegin, void * vend)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int aarch64_DC_CVAC_range_be(void *vbegin,void *vend)

{
  void *pvVar1;
  
  for (pvVar1 = (void *)((ulong)vbegin & 0xffffffffffffffc0); pvVar1 < vend;
      pvVar1 = (void *)((long)pvVar1 + 0x40)) {
    DC_CVAC(pvVar1);
  }
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00118464
 * symbol: aarch64_DC_CVAC_range_bs
 * prototype: int aarch64_DC_CVAC_range_bs(void * vbegin, uint64_t vsize)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int aarch64_DC_CVAC_range_bs(void *vbegin,uint64_t vsize)

{
  ulong uVar1;
  
  for (uVar1 = (ulong)vbegin & 0xffffffffffffffc0; uVar1 < (long)vbegin + vsize;
      uVar1 = uVar1 + 0x40) {
    DC_CVAC(uVar1);
  }
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00118490
 * symbol: aarch64_DC_IVAC_range_be
 * prototype: int aarch64_DC_IVAC_range_be(void * vbegin, void * vend)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int aarch64_DC_IVAC_range_be(void *vbegin,void *vend)

{
  void *pvVar1;
  
  for (pvVar1 = (void *)((ulong)vbegin & 0xffffffffffffffc0); pvVar1 < vend;
      pvVar1 = (void *)((long)pvVar1 + 0x40)) {
    DC_IVAC(pvVar1);
  }
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001184b8
 * symbol: aarch64_DC_CIVAC_range_be
 * prototype: int aarch64_DC_CIVAC_range_be(void * vbegin, void * vend)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int aarch64_DC_CIVAC_range_be(void *vbegin,void *vend)

{
  void *pvVar1;
  
  for (pvVar1 = (void *)((ulong)vbegin & 0xffffffffffffffc0); pvVar1 < vend;
      pvVar1 = (void *)((long)pvVar1 + 0x40)) {
    DC_CIVAC(pvVar1);
  }
  UnkSytemRegWrite(0,3,3,0xf,4,0);
  InstructionSynchronizationBarrier();
  return 0;
}


