/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\bzero.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117f70
 * symbol: bzero
 * prototype: void bzero(void * __s, size_t __n)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void bzero(void *__s,size_t __n)

{
  for (; __n != 0; __n = __n - 1) {
    *(undefined *)__s = 0;
  }
  return;
}


