/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\context.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00118314
 * symbol: get_dev_context
 * prototype: dev_context_t * get_dev_context(void)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

dev_context_t * get_dev_context(void)

{
  dev_context_t *pdVar1;
  
  pdVar1 = (dev_context_t *)tpidrro_el0;
  return pdVar1;
}


