/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\context_EL0.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011831c
 * symbol: dev_context_init
 * prototype: int dev_context_init(dev_context_t * dc, sttyp_putchar_context_t * spc, uint32_t cpu, uint32_t cp_param2, char * buf, uint64_t len, mp4_debug_status_t * mds)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int dev_context_init(dev_context_t *dc,sttyp_putchar_context_t *spc,uint32_t cpu,uint32_t cp_param2,
                    char *buf,uint64_t len,mp4_debug_status_t *mds)

{
  uint8_t *puVar1;
  uint uVar2;
  uint uVar3;
  
  dc->dc_dev_context_el0 = (dev_context_t *)0x0;
  dc->dc_dev_context_el1 = (dev_context_t *)0x0;
  dc->dc_dev_context_el2 = (dev_context_t *)0x0;
  dc->dc_exception_nest = 0;
  dc->dc_putchar_low_hook = svc_putchar;
  dc->dc_sttyp_putchar_context = spc;
  uVar3 = 0x2000000;
  if (cpu != 0) {
    uVar3 = 0x20000;
  }
  spc->spc_cpu = cpu;
  spc->spc_buf = buf;
  spc->spc_size = len;
  spc->spc_count = 0;
  spc->spc_mds_el0 = mds;
  uVar2 = 0x3b01000;
  if (cpu != 0) {
    uVar2 = 0x3d01200;
  }
  puVar1 = (uint8_t *)0x0;
  if ((uVar3 & cp_param2) != 0) {
    puVar1 = (uint8_t *)(ulong)uVar2;
  }
  spc->spc_pericom = puVar1;
  spc->spc_begin = spc_begin;
  spc->spc_putchar = spc_putchar;
  spc->spc_end = spc_end;
  dev_pmu_init();
  dev_pmu_setup_default();
  pmcr_el0 = 7;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001183b0
 * symbol: spc_begin
 * prototype: int spc_begin(sttyp_putchar_context_t * spc)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int spc_begin(sttyp_putchar_context_t *spc)

{
  spc->spc_count = 0;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001183c0
 * symbol: spc_putchar
 * prototype: int spc_putchar(sttyp_putchar_context_t * spc, int c)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int spc_putchar(sttyp_putchar_context_t *spc,int c)

{
  if (spc->spc_count < spc->spc_size) {
    spc->spc_buf[spc->spc_count] = (char)c;
    spc->spc_count = spc->spc_count + 1;
  }
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001183e8
 * symbol: spc_end
 * prototype: int spc_end(sttyp_putchar_context_t * spc)
 * body addresses: 84
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int spc_end(sttyp_putchar_context_t *spc)

{
  ulong uVar1;
  ulong vsize;
  
  uVar1 = spc->spc_count;
  vsize = uVar1;
  if (uVar1 < spc->spc_size) {
    spc->spc_buf[uVar1] = '\0';
    vsize = spc->spc_count;
  }
  aarch64_DC_CVAC_range_bs(spc->spc_buf,vsize);
  svc_sttyp_write(spc->spc_buf,spc->spc_count);
  spc->spc_count = 0;
  return (int)uVar1;
}


