/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\ctype.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117f18
 * symbol: toupper
 * prototype: int toupper(int __c)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int toupper(int __c)

{
  if ((uint)__c < 0x80 && (ulong)(uint)__c - 0x61 < 0x19 ||
      (uint)__c < 0x80 && (ulong)(uint)__c - 0x61 == 0x19) {
    __c = __c + -0x20;
  }
  return __c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117f34
 * symbol: sceMp4LookCtypeTable
 * prototype: int sceMp4LookCtypeTable(uint c)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int sceMp4LookCtypeTable(uint c)

{
  if (c < 0x80) {
    return (int)"         \b\b\b\b\b                  \x18\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x04\x04\x04\x04\x04\x04\x04\x04\x04\x04\x10\x10\x10\x10\x10\x10\x10AAAAAA\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x10\x10\x10\x10\x10\x10BBBBBB\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x10\x10\x10\x10 "
                [c];
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117f54
 * symbol: tolower
 * prototype: int tolower(int __c)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int tolower(int __c)

{
  if ((uint)__c < 0x80 && (ulong)(uint)__c - 0x41 < 0x19 ||
      (uint)__c < 0x80 && (ulong)(uint)__c - 0x41 == 0x19) {
    __c = __c + 0x20;
  }
  return __c;
}


