/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\dev.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117000
 * symbol: mp4_get_cpu
 * prototype: u_int mp4_get_cpu(void)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

u_int mp4_get_cpu(void)

{
  uint uVar1;
  
  uVar1 = aarch64_read_MPIDR_EL1();
  return uVar1 & 0xff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117018
 * symbol: mp4_basename
 * prototype: char * mp4_basename(char * f)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

char * mp4_basename(char *f)

{
  char *pcVar1;
  char cVar2;
  char *last;
  char *pcVar3;
  char *pcVar4;
  
  pcVar3 = (char *)0x0;
  pcVar4 = f;
  while( true ) {
    pcVar1 = pcVar4 + 1;
    cVar2 = *pcVar4;
    if (cVar2 == '\0') break;
    pcVar4 = pcVar1;
    if (((cVar2 == '\\') || (cVar2 == '/')) && (*pcVar1 != '\0')) {
      pcVar3 = pcVar1;
    }
  }
  if (pcVar3 != (char *)0x0) {
    f = pcVar3;
  }
  return f;
}


