/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\memcpy.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001182f4
 * symbol: memcpy
 * prototype: void * memcpy(void * __dest, void * __src, size_t __n)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


void * memcpy(void *__dest,void *__src,size_t __n)

{
  size_t sVar1;
  
  for (sVar1 = 0; __n != sVar1; sVar1 = sVar1 + 1) {
    *(undefined *)((long)__dest + sVar1) = *(undefined *)((long)__src + sVar1);
  }
  return __dest;
}


