/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\pericom.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001184e0
 * symbol: pericom_putchar
 * prototype: void pericom_putchar(uint8_t * base, int c)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void pericom_putchar(uint8_t *base,int c)

{
  int iVar1;
  int iVar2;
  int iVar3;
  
  iVar3 = 0x10000000;
  iVar2 = -250000;
  do {
    if ((base[5] >> 5 & 1) != 0) goto LAB_00118510;
    iVar3 = iVar3 + 1;
    iVar1 = iVar2;
  } while (iVar3 != 0);
  do {
    if ((base[5] >> 5 & 1) != 0) break;
    iVar1 = iVar1 + 1;
  } while (iVar1 != 0);
LAB_00118510:
  *base = (uint8_t)c;
  iVar3 = iVar2;
  do {
    if ((base[5] >> 6 & 1) != 0) {
      return;
    }
    iVar3 = iVar3 + 1;
  } while (iVar3 != 0);
  do {
    if ((base[5] >> 5 & 1) != 0) {
      return;
    }
    iVar2 = iVar2 + 1;
  } while (iVar2 != 0);
  return;
}


