/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\pmu.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117058
 * symbol: dev_pmu_init
 * prototype: int dev_pmu_init(void)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int dev_pmu_init(void)

{
  undefined8 uVar1;
  
  uVar1 = pmcr_el0;
  printf("PMCR_EL0      = 0x%08x\n",uVar1);
  uVar1 = pmuserenr_el0;
  printf("PMUSERENR_EL0 = 0x%08x\n",uVar1);
  uVar1 = pmccntr_el0;
  printf("PMCCNTR_EL0   = 0x%08X [0x41033000]\n",uVar1);
  uVar1 = pmceid0_el0;
  printf("PMCEID0_EL0   = 0x%08X [0x67FFBFFF]\n",uVar1);
  uVar1 = pmceid1_el0;
  printf("PMCEID1_EL0   = 0x%08X [0x00000000]\n",uVar1);
  uVar1 = pmevtyper0_el0;
  printf("PMCCFILTR_EL0 = 0x%08X [0x00000000]\n",uVar1);
  uVar1 = pmccfiltr_el0;
  printf("PMCCFILTR_EL0 = 0x%08X [0x00000000]\n",uVar1);
  pmccfiltr_el0 = uVar1;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001170ec
 * symbol: dev_pmu_setup_default
 * prototype: int dev_pmu_setup_default(void)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int dev_pmu_setup_default(void)

{
  pmevtyper0_el0 = 0x8000001;
  pmevtyper1_el0 = 0x8000002;
  pmevtyper2_el0 = 0x8000003;
  pmevtyper3_el0 = 0x8000008;
  pmevtyper4_el0 = 0x8000015;
  pmevtyper5_el0 = 0x8000017;
  pmcntenset_el0 = 0x8000003f;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117144
 * symbol: dev_pmu_report
 * prototype: int dev_pmu_report(void)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int dev_pmu_report(void)

{
  undefined8 uVar1;
  undefined8 uVar2;
  
  uVar1 = pmcr_el0;
  printf("PMU (Performance Monitor Unit) REPORT\n",uVar1);
  uVar1 = pmcr_el0;
  printf("    PMCR_EL0                     - 0x%08X\n",uVar1);
  uVar1 = pmccntr_el0;
  printf("    0x%08x - PMCCNTR_EL0 [Cycle Count]\n",uVar1);
  uVar2 = pmevtyper0_el0;
  uVar1 = pmevcntr0_el0;
  pmu_print_count((uint32_t)uVar2,(uint32_t)uVar1);
  uVar2 = pmevtyper1_el0;
  uVar1 = pmevcntr1_el0;
  pmu_print_count((uint32_t)uVar2,(uint32_t)uVar1);
  uVar2 = pmevtyper2_el0;
  uVar1 = pmevcntr2_el0;
  pmu_print_count((uint32_t)uVar2,(uint32_t)uVar1);
  uVar2 = pmevtyper3_el0;
  uVar1 = pmevcntr3_el0;
  pmu_print_count((uint32_t)uVar2,(uint32_t)uVar1);
  uVar2 = pmevtyper4_el0;
  uVar1 = pmevcntr4_el0;
  pmu_print_count((uint32_t)uVar2,(uint32_t)uVar1);
  uVar2 = pmevtyper5_el0;
  uVar1 = pmevcntr5_el0;
  pmu_print_count((uint32_t)uVar2,(uint32_t)uVar1);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001171d0
 * symbol: pmu_print_count
 * prototype: void pmu_print_count(uint32_t type, uint32_t count)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void pmu_print_count(uint32_t type,uint32_t count)

{
  char *pcVar1;
  
  if ((type & 0x3ff) < 0x18) {
    pcVar1 = (&PTR_s_Instruction_architecturally_exec_001185c0)[(long)((ulong)type << 0x36) >> 0x36]
    ;
  }
  else {
    pcVar1 = "Unknown";
  }
  printf("    0x%08x - 0x%08x  [%s]\n",(ulong)count,(ulong)type,pcVar1);
  return;
}


