/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\printf.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117d9c
 * symbol: printf_sttyp
 * prototype: int printf_sttyp(char * format, ...)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int printf_sttyp(char *format,...)

{
  int iVar1;
  
  iVar1 = prnt(putchar_sttyp_hook,(void *)0x0,format,(va_list *)&stack0xffffffffffffffb0);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117e08
 * symbol: putchar_sttyp_hook
 * prototype: void putchar_sttyp_hook(void * pfd, int ch)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void putchar_sttyp_hook(void *pfd,int ch)

{
  if (ch == 0x201) {
    putchar_sttyp_end();
    return;
  }
  if (ch == 0x200) {
    putchar_sttyp_begin();
    return;
  }
  putchar_sttyp(ch);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117e28
 * symbol: printf_titania_uart_el0
 * prototype: int printf_titania_uart_el0(char * format, ...)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int printf_titania_uart_el0(char *format,...)

{
  int iVar1;
  
  iVar1 = prnt(putchar_titania_uart_hook_el0,(void *)0x0,format,(va_list *)&stack0xffffffffffffffb0)
  ;
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117e94
 * symbol: putchar_titania_uart_hook_el0
 * prototype: void putchar_titania_uart_hook_el0(void * pfd, int ch)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void putchar_titania_uart_hook_el0(void *pfd,int ch)

{
  if ((ch | 1U) == 0x201) {
    return;
  }
  putchar_titania_uart_el0(ch);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117eac
 * symbol: printf
 * prototype: int printf(char * __format, ...)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int printf(char *__format,...)

{
  int iVar1;
  
  iVar1 = prnt(putchar_sttyp_hook,(void *)0x0,__format,(va_list *)&stack0xffffffffffffffb0);
  return iVar1;
}


