/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\prnt.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011720c
 * symbol: prnt
 * prototype: int prnt(prnt_putchar_handler_t pf, void * pfd, char * fmt0, va_list * argp)
 * body addresses: 2960
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int prnt(prnt_putchar_handler_t pf,void *pfd,char *fmt0,va_list *argp)

{
  int *piVar1;
  char cVar2;
  bool bVar3;
  ulong uVar4;
  bool bVar5;
  bool bVar6;
  bool bVar7;
  uint uVar8;
  int iVar9;
  byte *pbVar10;
  undefined4 *puVar11;
  char **ppcVar12;
  uint *puVar13;
  ulong *puVar14;
  ulong uVar15;
  int *piVar16;
  char *pcVar17;
  int iVar18;
  int iVar19;
  byte bVar20;
  char *pcVar21;
  int iVar22;
  size_t sVar23;
  int iVar24;
  int iVar25;
  int iVar26;
  char buf [21];
  ulong local_c0;
  ulong local_b8;
  char *local_b0;
  uint local_7c;
  char local_78 [20];
  char local_64;
  char acStack_63 [3];
  
  if (fmt0 == (char *)0x0) {
    (*pf)(pfd,0x66);
    (*pf)(pfd,0x6d);
    (*pf)(pfd,0x74);
    (*pf)(pfd,0x30);
    (*pf)(pfd,0x20);
    (*pf)(pfd,0x69);
    (*pf)(pfd,0x73);
    (*pf)(pfd,0x20);
    (*pf)(pfd,0x4e);
    (*pf)(pfd,0x55);
    (*pf)(pfd,0x4c);
    (*pf)(pfd,0x4c);
    (*pf)(pfd,10);
    return 0;
  }
  (*pf)(pfd,0x200);
  piVar1 = &argp->__gr_offs;
  local_c0 = 0;
  local_b8 = 0;
  iVar24 = 0;
  local_b0 = "0123456789abcdef";
  for (; bVar20 = *fmt0, bVar20 != 0x25; fmt0 = (char *)((byte *)fmt0 + 1)) {
joined_r0x001174d8:
    if (bVar20 == 0) {
      (*pf)(pfd,0x201);
      return iVar24;
    }
LAB_00117294:
    (*pf)(pfd,(int)bVar20);
    iVar26 = 1;
LAB_00117bb4:
    iVar24 = iVar26 + iVar24;
  }
  iVar26 = 0;
  local_7c = 0;
  bVar6 = false;
  bVar5 = false;
  bVar7 = false;
  iVar22 = -1;
  iVar19 = 0;
switchD_001172dc_caseD_2b:
  iVar9 = iVar19;
  pbVar10 = (byte *)fmt0;
  bVar3 = false;
  fmt0 = (char *)(pbVar10 + 1);
  bVar20 = *fmt0;
  iVar19 = 0x2b;
  pcVar21 = acStack_63;
  switch(bVar20) {
  case 0x2a:
    iVar26 = *piVar1;
    if ((iVar26 < 0) && (*piVar1 = iVar26 + 8, iVar26 + 8 < 1)) {
      piVar16 = (int *)((long)argp->__gr_top + (long)iVar26);
    }
    else {
      piVar16 = (int *)argp->__stack;
      argp->__stack = piVar16 + 2;
    }
    iVar26 = *piVar16;
    iVar19 = iVar9;
    if (-1 < iVar26) goto switchD_001172dc_caseD_2b;
    iVar26 = -iVar26;
switchD_001172dc_caseD_2d:
    local_7c = local_7c | 0x10;
    iVar19 = iVar9;
    goto switchD_001172dc_caseD_2b;
  case 0x2b:
    goto switchD_001172dc_caseD_2b;
  case 0x2c:
  case 0x2f:
  case 0x3a:
  case 0x3b:
  case 0x3c:
  case 0x3d:
  case 0x3e:
  case 0x3f:
  case 0x40:
  case 0x41:
  case 0x42:
  case 0x43:
  case 0x45:
  case 0x46:
  case 0x47:
  case 0x48:
  case 0x49:
  case 0x4a:
  case 0x4b:
  case 0x4d:
  case 0x4e:
  case 0x50:
  case 0x51:
  case 0x52:
  case 0x53:
  case 0x54:
  case 0x56:
  case 0x57:
    goto LAB_00117294;
  case 0x2d:
    goto switchD_001172dc_caseD_2d;
  case 0x2e:
    pbVar10 = pbVar10 + 2;
    bVar20 = *pbVar10;
    if (bVar20 == 0x2a) {
      iVar22 = *piVar1;
      if ((iVar22 < 0) && (*piVar1 = iVar22 + 8, iVar22 + 8 < 1)) {
        piVar16 = (int *)((long)argp->__gr_top + (long)iVar22);
      }
      else {
        piVar16 = (int *)argp->__stack;
        argp->__stack = piVar16 + 2;
      }
      iVar22 = *piVar16;
      fmt0 = (char *)pbVar10;
    }
    else {
      iVar22 = 0;
      while (-1 < (char)bVar20) {
        uVar8 = sceMp4LookCtypeTable((uint)bVar20);
        if ((uVar8 >> 2 & 1) == 0) break;
        pbVar10 = (byte *)fmt0 + 2;
        fmt0 = (char *)((byte *)fmt0 + 1);
        iVar22 = (uint)bVar20 + iVar22 * 10 + -0x30;
        bVar20 = *pbVar10;
      }
    }
    iVar19 = iVar9;
    if (iVar22 < 0) {
      iVar22 = -1;
    }
    goto switchD_001172dc_caseD_2b;
  case 0x30:
    local_7c = local_7c | 0x20;
    iVar19 = iVar9;
    goto switchD_001172dc_caseD_2b;
  case 0x31:
  case 0x32:
  case 0x33:
  case 0x34:
  case 0x35:
  case 0x36:
  case 0x37:
  case 0x38:
  case 0x39:
    iVar26 = 0;
    pbVar10 = (byte *)fmt0;
    do {
      uVar8 = (uint)bVar20;
      bVar20 = pbVar10[1];
      iVar26 = iVar26 * 10 + uVar8 + -0x30;
      fmt0 = (char *)pbVar10;
      iVar19 = iVar9;
      if ((char)bVar20 < '\0') break;
      uVar8 = sceMp4LookCtypeTable((uint)bVar20);
      pbVar10 = pbVar10 + 1;
    } while ((uVar8 >> 2 & 1) != 0);
    goto switchD_001172dc_caseD_2b;
  case 0x44:
    bVar7 = true;
joined_r0x001174f0:
    if (bVar5) {
      iVar19 = *piVar1;
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        puVar14 = (ulong *)argp->__stack;
        argp->__stack = puVar14 + 1;
      }
      uVar15 = *puVar14;
      local_b8 = -uVar15;
      if (-1 < (long)uVar15) {
        local_b8 = uVar15;
      }
      iVar19 = 0x2d;
      if (-1 < (long)uVar15) {
        iVar19 = iVar9;
      }
      uVar15 = 10;
      goto LAB_0011790c;
    }
    iVar19 = *piVar1;
    if (bVar7) {
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        puVar14 = (ulong *)argp->__stack;
        argp->__stack = puVar14 + 1;
      }
      uVar15 = *puVar14;
    }
    else {
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        puVar13 = (uint *)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        puVar13 = (uint *)argp->__stack;
        argp->__stack = puVar13 + 2;
      }
      uVar15 = (ulong)*puVar13;
    }
    local_c0 = -uVar15;
    if (-1 < (long)uVar15) {
      local_c0 = uVar15;
    }
    iVar19 = 0x2d;
    if (-1 < (long)uVar15) {
      iVar19 = iVar9;
    }
    uVar15 = 10;
    goto LAB_001178e4;
  case 0x4c:
    bVar5 = true;
    iVar19 = iVar9;
    goto switchD_001172dc_caseD_2b;
  case 0x4f:
    bVar7 = true;
joined_r0x0011763c:
    if (bVar5) {
      iVar19 = *piVar1;
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        puVar14 = (ulong *)argp->__stack;
        argp->__stack = puVar14 + 1;
      }
      local_b8 = *puVar14;
      uVar15 = 8;
    }
    else {
      iVar19 = *piVar1;
      if (bVar7) {
        if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
          puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
        }
        else {
          puVar14 = (ulong *)argp->__stack;
          argp->__stack = puVar14 + 1;
        }
        local_c0 = *puVar14;
      }
      else {
        if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
          puVar13 = (uint *)((long)argp->__gr_top + (long)iVar19);
        }
        else {
          puVar13 = (uint *)argp->__stack;
          argp->__stack = puVar13 + 2;
        }
        local_c0 = (ulong)*puVar13;
      }
      uVar15 = 8;
    }
    goto LAB_001178dc;
  case 0x55:
    bVar7 = true;
joined_r0x00117598:
    if (bVar5) {
      iVar19 = *piVar1;
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        puVar14 = (ulong *)argp->__stack;
        argp->__stack = puVar14 + 1;
      }
      local_b8 = *puVar14;
      uVar15 = 10;
    }
    else {
      iVar19 = *piVar1;
      if (bVar7) {
        if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
          puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
        }
        else {
          puVar14 = (ulong *)argp->__stack;
          argp->__stack = puVar14 + 1;
        }
        local_c0 = *puVar14;
      }
      else {
        if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
          puVar13 = (uint *)((long)argp->__gr_top + (long)iVar19);
        }
        else {
          puVar13 = (uint *)argp->__stack;
          argp->__stack = puVar13 + 2;
        }
        local_c0 = (ulong)*puVar13;
      }
      uVar15 = 10;
    }
LAB_001178dc:
    iVar19 = 0;
    if (bVar5) {
LAB_0011790c:
      uVar8 = local_7c & 0xffffffdf;
      if (iVar22 < 0) {
        uVar8 = local_7c;
      }
      pcVar17 = &local_64;
      local_7c = uVar8;
      if ((iVar22 == 0) && (local_b8 == 0)) {
        local_b8 = 0;
      }
      else {
        do {
          pcVar21 = pcVar17;
          bVar7 = uVar15 <= local_b8;
          uVar4 = 0;
          if (uVar15 != 0) {
            uVar4 = local_b8 / uVar15;
          }
          cVar2 = local_b0[local_b8 - uVar4 * uVar15];
          pcVar17 = pcVar21 + -1;
          *pcVar21 = cVar2;
          local_b8 = uVar4;
        } while (bVar7);
        if ((((int)uVar15 == 8) && (bVar6)) && (cVar2 != '0')) {
          local_b0 = "0123456789abcdef";
          *pcVar17 = '0';
          pcVar21 = pcVar17;
        }
        else {
          local_b0 = "0123456789abcdef";
        }
      }
    }
    else {
LAB_001178e4:
      uVar8 = local_7c & 0xffffffdf;
      if (iVar22 < 0) {
        uVar8 = local_7c;
      }
      if ((iVar22 != 0) || (local_c0 != 0)) {
        iVar9 = (int)uVar15;
        do {
          pcVar17 = pcVar21;
          if (iVar9 == 8) {
            cVar2 = local_b0[local_c0 & 7];
            pcVar17[-1] = cVar2;
            local_c0 = local_c0 >> 3;
          }
          else if (iVar9 == 0x10) {
            cVar2 = local_b0[local_c0 & 0xf];
            pcVar17[-1] = cVar2;
            local_c0 = local_c0 >> 4;
          }
          else if (iVar9 == 10) {
            cVar2 = local_b0[local_c0 % 10];
            pcVar17[-1] = cVar2;
            local_c0 = local_c0 / 10;
          }
          else {
            uVar4 = 0;
            if (uVar15 != 0) {
              uVar4 = local_c0 / uVar15;
            }
            cVar2 = local_b0[local_c0 & iVar9 - 1];
            pcVar17[-1] = cVar2;
            local_c0 = uVar4;
          }
          pcVar21 = pcVar17 + -1;
        } while (local_c0 != 0);
        local_b0 = "0123456789abcdef";
        pcVar21 = pcVar17 + -1;
        if ((cVar2 != '0' && iVar9 == 8) && bVar6) {
          pcVar17[-2] = '0';
          local_b0 = "0123456789abcdef";
          pcVar21 = pcVar17 + -2;
        }
      }
      local_c0 = 0;
      local_7c = uVar8;
    }
    sVar23 = (size_t)(uint)((int)acStack_63 - (int)pcVar21);
LAB_00117a78:
    iVar9 = (int)sVar23;
    if (iVar19 != 0) {
      iVar9 = iVar9 + 1;
    }
    iVar25 = iVar9 + 2;
    if (!bVar3) {
      iVar25 = iVar9;
    }
    iVar9 = iVar22;
    if (iVar22 <= iVar25) {
      iVar9 = iVar25;
    }
    if (((local_7c & 0x30) == 0) && (iVar18 = iVar9, iVar26 != 0)) {
      for (; iVar18 < iVar26; iVar18 = iVar18 + 1) {
        (*pf)(pfd,0x20);
      }
    }
    if (iVar19 != 0) {
      (*pf)(pfd,iVar19);
    }
    if (bVar3) {
      (*pf)(pfd,0x30);
      bVar20 = *fmt0;
      if (bVar20 == 0x70) {
        bVar20 = 0x78;
      }
      (*pf)(pfd,(int)bVar20);
    }
    iVar19 = iVar9;
    if ((local_7c & 0x30) == 0x20) {
      for (; iVar19 < iVar26; iVar19 = iVar19 + 1) {
        (*pf)(pfd,0x30);
      }
    }
    for (; iVar25 < iVar22; iVar25 = iVar25 + 1) {
      (*pf)(pfd,0x30);
    }
    while (iVar22 = (int)sVar23, sVar23 = (size_t)(iVar22 - 1), 0 < iVar22) {
      (*pf)(pfd,(int)*pcVar21);
      pcVar21 = pcVar21 + 1;
    }
    iVar22 = iVar9;
    if ((local_7c >> 4 & 1) != 0) {
      for (; iVar22 < iVar26; iVar22 = iVar22 + 1) {
        (*pf)(pfd,0x20);
      }
    }
    if (iVar26 <= iVar9) {
      iVar26 = iVar9;
    }
    goto LAB_00117bb4;
  case 0x58:
    local_b0 = "0123456789ABCDEF";
LAB_00117788:
    if (!bVar5) {
      iVar19 = *piVar1;
      if (bVar7) {
        if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
          puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
        }
        else {
          puVar14 = (ulong *)argp->__stack;
          argp->__stack = puVar14 + 1;
        }
        local_c0 = *puVar14;
      }
      else {
        if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
          puVar13 = (uint *)((long)argp->__gr_top + (long)iVar19);
        }
        else {
          puVar13 = (uint *)argp->__stack;
          argp->__stack = puVar13 + 2;
        }
        local_c0 = (ulong)*puVar13;
      }
      bVar3 = (bool)(local_c0 != 0 & bVar6);
      uVar15 = 0x10;
      goto LAB_001178dc;
    }
    iVar19 = *piVar1;
    if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
      puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
    }
    else {
      puVar14 = (ulong *)argp->__stack;
      argp->__stack = puVar14 + 1;
    }
    local_b8 = *puVar14;
    bVar3 = (bool)(local_b8 != 0 & bVar6);
    uVar15 = 0x10;
    iVar19 = iVar9;
    goto LAB_0011790c;
  default:
    switch(bVar20) {
    case 99:
      iVar22 = *piVar1;
      if ((iVar22 < 0) && (*piVar1 = iVar22 + 8, iVar22 + 8 < 1)) {
        puVar11 = (undefined4 *)((long)argp->__gr_top + (long)iVar22);
      }
      else {
        puVar11 = (undefined4 *)argp->__stack;
        argp->__stack = puVar11 + 2;
      }
      iVar22 = 0;
      iVar19 = 0;
      pcVar21 = local_78;
      sVar23 = 1;
      local_78[0] = (char)*puVar11;
      goto LAB_00117a78;
    case 100:
    case 0x69:
      goto joined_r0x001174f0;
    case 0x65:
    case 0x66:
    case 0x67:
    case 0x6a:
    case 0x6b:
    case 0x6d:
    case 0x6e:
    case 0x71:
    case 0x72:
    case 0x74:
    case 0x76:
    case 0x77:
      goto LAB_00117294;
    case 0x68:
      iVar19 = iVar9;
      break;
    case 0x6c:
      if (bVar7) {
        bVar5 = true;
      }
      bVar7 = !bVar7;
      iVar19 = iVar9;
      break;
    case 0x6f:
      goto joined_r0x0011763c;
    case 0x70:
      iVar19 = *piVar1;
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        puVar14 = (ulong *)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        puVar14 = (ulong *)argp->__stack;
        argp->__stack = puVar14 + 1;
      }
      local_c0 = *puVar14;
      iVar19 = 0x12;
      if (iVar26 != 0) {
        iVar19 = iVar26;
      }
      uVar15 = 0x10;
      local_7c = local_7c | 0x60;
      bVar3 = true;
      iVar26 = iVar19;
      goto LAB_001178dc;
    case 0x73:
      iVar19 = *piVar1;
      if ((iVar19 < 0) && (*piVar1 = iVar19 + 8, iVar19 + 8 < 1)) {
        ppcVar12 = (char **)((long)argp->__gr_top + (long)iVar19);
      }
      else {
        ppcVar12 = (char **)argp->__stack;
        argp->__stack = ppcVar12 + 1;
      }
      pcVar21 = "(null)";
      if (*ppcVar12 != (char *)0x0) {
        pcVar21 = *ppcVar12;
      }
      sVar23 = (size_t)iVar22;
      if (iVar22 < 0) {
        sVar23 = 0xffffffff;
      }
      sVar23 = strnlen(pcVar21,sVar23);
      iVar22 = 0;
      iVar19 = 0;
      goto LAB_00117a78;
    case 0x75:
      goto joined_r0x00117598;
    case 0x78:
      goto LAB_00117788;
    default:
      if (bVar20 != 0x20) {
        if (bVar20 == 0x23) goto code_r0x00117350;
        goto joined_r0x001174d8;
      }
      iVar19 = 0x20;
      if (iVar9 != 0) {
        iVar19 = iVar9;
      }
    }
    goto switchD_001172dc_caseD_2b;
  }
code_r0x00117350:
  bVar6 = true;
  iVar19 = iVar9;
  goto switchD_001172dc_caseD_2b;
}


