/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\putchar.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117fe4
 * symbol: putchar_titania_uart_el0
 * prototype: int putchar_titania_uart_el0(int c)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int putchar_titania_uart_el0(int c)

{
  do {
  } while ((_DAT_0382010c >> 0xb & 1) != 0);
  _DAT_03820104 = c & 0xff;
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00118000
 * symbol: putchar
 * prototype: int putchar(int __c)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int putchar(int __c)

{
  dev_context_t *pdVar1;
  
  pdVar1 = get_dev_context();
  (*pdVar1->dc_putchar_low_hook)(__c);
  return __c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00118030
 * symbol: sttyp_putchar_context_get
 * prototype: sttyp_putchar_context_t * sttyp_putchar_context_get(void)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

sttyp_putchar_context_t * sttyp_putchar_context_get(void)

{
  dev_context_t *pdVar1;
  
  pdVar1 = get_dev_context();
  return pdVar1->dc_sttyp_putchar_context;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00118048
 * symbol: set_sttyp_putchar_context
 * prototype: void set_sttyp_putchar_context(sttyp_putchar_context_t * spc)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void set_sttyp_putchar_context(sttyp_putchar_context_t *spc)

{
  dev_context_t *pdVar1;
  
  pdVar1 = get_dev_context();
  pdVar1->dc_sttyp_putchar_context = spc;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011806c
 * symbol: putchar_sttyp_begin
 * prototype: int putchar_sttyp_begin(void)
 * body addresses: 448
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int putchar_sttyp_begin(void)

{
  ulong uVar1;
  uint uVar2;
  dev_context_t *pdVar3;
  ulong uVar4;
  int iVar5;
  sttyp_putchar_context_t *psVar6;
  
  pdVar3 = get_dev_context();
  psVar6 = pdVar3->dc_sttyp_putchar_context;
  putchar_el0_direct(0x45);
  putchar_el0_direct(0x4c);
  putchar_el0_direct(0x30);
  putchar_el0_direct(0x3a);
  putchar_el0_direct(psVar6->spc_cpu + 0x30);
  putchar_el0_direct(0x3a);
  putchar_el0_direct(0x3a);
  uVar1 = cntpct_el0;
  iVar5 = 0;
  do {
    uVar4 = uVar1 >> 0x3c;
    switch(iVar5) {
    case 0:
      break;
    case 1:
      uVar4 = uVar1 >> 0x38 & 0xf;
      break;
    case 2:
      uVar4 = uVar1 >> 0x34 & 0xf;
      break;
    case 3:
      uVar4 = uVar1 >> 0x30 & 0xf;
      break;
    case 4:
      uVar4 = uVar1 >> 0x2c & 0xf;
      break;
    case 5:
      uVar4 = uVar1 >> 0x28 & 0xf;
      break;
    case 6:
      uVar4 = uVar1 >> 0x24 & 0xf;
      break;
    case 7:
      uVar4 = uVar1 >> 0x20 & 0xf;
      break;
    case 8:
      uVar4 = uVar1 >> 0x1c & 0xf;
      break;
    case 9:
      uVar4 = uVar1 >> 0x18 & 0xf;
      break;
    case 10:
      uVar4 = uVar1 >> 0x14 & 0xf;
      break;
    case 0xb:
      uVar4 = uVar1 >> 0x10 & 0xf;
      break;
    case 0xc:
      uVar4 = uVar1 >> 0xc & 0xf;
      break;
    case 0xd:
      uVar4 = uVar1 >> 8 & 0xf;
      break;
    case 0xe:
      uVar4 = uVar1 >> 4 & 0xf;
      break;
    case 0xf:
      uVar4 = uVar1 & 0xf;
      break;
    case 0x10:
      putchar_el0_direct(0x3a);
      putchar_el0_direct(0x20);
      return 0;
    default:
      uVar2 = 0;
      goto LAB_001181cc;
    }
    uVar2 = (uint)uVar4;
    if (uVar4 < 10) {
LAB_001181cc:
      uVar2 = uVar2 | 0x30;
    }
    else {
      uVar2 = uVar2 + 0x57;
    }
    putchar_el0_direct(uVar2);
    iVar5 = iVar5 + 1;
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0011822c
 * symbol: putchar_el0_direct
 * prototype: int putchar_el0_direct(int c)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int putchar_el0_direct(int c)

{
  uint64_t uVar1;
  dev_context_t *pdVar2;
  uint8_t *base;
  mp4_debug_status_t *pmVar3;
  
  pdVar2 = get_dev_context();
  base = pdVar2->dc_sttyp_putchar_context->spc_pericom;
  if (base != (uint8_t *)0x0) {
    pericom_putchar(base,c);
    return (int)base;
  }
  pmVar3 = pdVar2->dc_sttyp_putchar_context->spc_mds_el0;
  *(char *)((long)pmVar3->mds_gpr +
           pmVar3->mds_ttyp_buffer_last + pmVar3->mds_ttyp_buffer_offset + -0x10) = (char)c;
  uVar1 = pmVar3->mds_ttyp_buffer_last + 1;
  pmVar3->mds_ttyp_buffer_last = uVar1;
  if (uVar1 == pmVar3->mds_ttyp_buffer_size) {
    pmVar3->mds_ttyp_buffer_last = 0;
    pmVar3->mds_ttyp_buffer_count = pmVar3->mds_ttyp_buffer_count + 1;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001182a4
 * symbol: putchar_sttyp
 * prototype: int putchar_sttyp(int c)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int putchar_sttyp(int c)

{
  get_dev_context();
  putchar_el0_direct(c);
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001182d0
 * symbol: putchar_sttyp_end
 * prototype: int putchar_sttyp_end(void)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int putchar_sttyp_end(void)

{
  return 0;
}


