/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\puts.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117fe0
 * symbol: puts
 * prototype: int puts(char * __s)
 * body addresses: 4
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


int puts(char *__s)

{
  CallSupervisor(0x111);
  return (int)__s;
}


