/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\strncpy.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117fa8
 * symbol: strncpy
 * prototype: char * strncpy(char * __dest, char * __src, size_t __n)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


char * strncpy(char *__dest,char *__src,size_t __n)

{
  ulong uVar1;
  
  for (uVar1 = 0; (uVar1 < __n && (__src[uVar1] != '\0')); uVar1 = uVar1 + 1) {
    __dest[uVar1] = __src[uVar1];
  }
  for (; uVar1 < __n; uVar1 = uVar1 + 1) {
    __dest[uVar1] = '\0';
  }
  return __dest;
}


