/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\strnlen.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x00117f84
 * symbol: strnlen
 * prototype: size_t strnlen(char * __string, size_t __maxlen)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


size_t strnlen(char *__string,size_t __maxlen)

{
  ulong uVar1;
  
  for (uVar1 = 0; (uVar1 < __maxlen && (__string[uVar1] != '\0')); uVar1 = uVar1 + 1) {
  }
  return uVar1;
}


