/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/loader/dev\titania_uart.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x001182d8
 * symbol: putchar_titania_uart_el3
 * prototype: int putchar_titania_uart_el3(int c)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int putchar_titania_uart_el3(int c)

{
  do {
  } while ((_DAT_a101010c >> 0xb & 1) != 0);
  _DAT_a1010104 = c & 0xff;
  return c;
}


