/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/dram\a53_mm_controller_rw_ring__dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003bd8
 * symbol: getElementIndexBackwardFromTail
 * prototype: uint16_t getElementIndexBackwardFromTail(MmControllerPipelineRwRing * this, Section section, uint16_t indexBeforeTail)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexBackwardFromTail(MmControllerPipelineRwRing *
   this, Section section, uint16_t indexBeforeTail) */

uint16_t __thiscall
A53::MmControllerPipelineRwRing::getElementIndexBackwardFromTail
          (MmControllerPipelineRwRing *this,Section section,uint16_t indexBeforeTail)

{
  ushort uVar1;
  int iVar2;
  ushort uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1;
  iVar2 = ((uint)(this->field_0).field_0.m_head - (uint)indexBeforeTail) +
          (uint)*(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0x14);
  uVar3 = 0;
  if ((int)(uint)uVar1 <= iVar2) {
    uVar3 = uVar1;
  }
  return (short)iVar2 - uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003c08
 * symbol: getElementIndexFromHead
 * prototype: uint16_t getElementIndexFromHead(MmControllerPipelineRwRing * this, Section section, uint16_t indexFromHead)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexFromHead(MmControllerPipelineRwRing * this,
   Section section, uint16_t indexFromHead) */

uint16_t __thiscall
A53::MmControllerPipelineRwRing::getElementIndexFromHead
          (MmControllerPipelineRwRing *this,Section section,uint16_t indexFromHead)

{
  ushort uVar1;
  uint uVar2;
  ushort uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1;
  uVar2 = (uint)(this->field_0).field_0.m_head + (uint)indexFromHead +
          (uint)*(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0xe);
  uVar3 = 0;
  if (uVar1 <= uVar2) {
    uVar3 = uVar1;
  }
  return (short)uVar2 - uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003c38
 * symbol: getElementIndexBackwardFromTail
 * prototype: uint16_t getElementIndexBackwardFromTail(MmControllerPipelineRwRing * this, uint16_t indexBeforeTail)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexBackwardFromTail(MmControllerPipelineRwRing *
   this, uint16_t indexBeforeTail) */

uint16_t __thiscall
A53::MmControllerPipelineRwRing::getElementIndexBackwardFromTail
          (MmControllerPipelineRwRing *this,uint16_t indexBeforeTail)

{
  ushort uVar1;
  int iVar2;
  ushort uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1;
  iVar2 = ((uint)(this->field_0).field_0.m_head - (uint)indexBeforeTail) +
          (uint)(this->field_0).field_0.m_count;
  uVar3 = 0;
  if ((int)(uint)uVar1 <= iVar2) {
    uVar3 = uVar1;
  }
  return (short)iVar2 - uVar3;
}


