/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/dram\a53_mm_controller__dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060001b0
 * symbol: setVaSramMmController_BootConfiguration
 * prototype: bool setVaSramMmController_BootConfiguration(MmController * this, uint64_t vaSramMmController_BootConfiguration)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool setVaSramMmController_BootConfiguration(MmController * this,
   uint64_t vaSramMmController_BootConfiguration) */

bool __thiscall
A53::MMC::MmController::setVaSramMmController_BootConfiguration
          (MmController *this,uint64_t vaSramMmController_BootConfiguration)

{
  if ((MmController_BootConfiguration *)vaSramMmController_BootConfiguration == &core1_boot_config)
  {
    (this->m_runtime_config).field_0.field_0.m_vaSramA53Controller_BootConfiguration = 0x4c00000;
  }
  return (MmController_BootConfiguration *)vaSramMmController_BootConfiguration ==
         &core1_boot_config;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06001300
 * symbol: submit
 * prototype: void submit(PtdmaVqState * this)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void submit(PtdmaVqState * this) */

void __thiscall A53::PtdmaVqState::submit(PtdmaVqState *this)

{
  ulong uVar1;
  
  uVar1 = (ulong)(this->m_submit).m_offsetPut + (ulong)(this->m_submit).m_vaQueue;
  if ((uVar1 & 0x3f) != 0) {
    DC_CVAC(uVar1 & 0x1ffffffc0);
  }
  DataSynchronizationBarrier(3,3);
  *(uint32_t *)((ulong)(this->m_submit).m_iVq * 0x1000 + 0x22c1004) =
       (this->m_submit).m_offsetPut + (this->m_submit).m_paQueue;
  this->m_tail_lo = (this->m_submit).m_offsetPut + (this->m_submit).m_paQueue;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060013f8
 * symbol: mmControllerHaltAndError
 * prototype: void mmControllerHaltAndError(MmController * this, MmControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mmControllerHaltAndError(MmController * this,
   MmControllerSysErrorCode eErrorCode, uint64_t addressError, uint16_t pasidError) */

void __thiscall
A53::MMC::MmController::mmControllerHaltAndError
          (MmController *this,MmControllerSysErrorCode eErrorCode,uint64_t addressError,
          uint16_t pasidError)

{
  ControllerRings local_78;
  
  local_78.m_pRingsState = &this->m_rings_state;
  local_78.m_static_config.field_0.asU32 =
       (anon_union_4_2_653be89a_for_ControllerStaticConfiguration_0)0x10271840;
  local_78.m_paInputIndirectBuffer = this->m_aInputIndirectBuffer;
  local_78.m_runtime_config.field_0.asU32[2] = (this->m_runtime_config).field_0.asU32[2];
  local_78.m_runtime_config.field_0._0_8_ = *(undefined8 *)&(this->m_runtime_config).field_0;
  local_78.m_paInputRingHead = this->m_aInputRingHead;
  local_78.m_paInputRingHeadIb = this->m_aInputRingHeadIb;
  local_78.m_paIndirectBufferNumElemsRemaining = this->m_aIndirectBufferNumElemsRemaining;
  local_78.m_paCommandRingErrorState = this->m_aCommandRingErrorState;
  local_78.m_pInterruptContextRingTail = &this->m_InterruptContextRingTail;
  local_78.m_paOutputRing = this->m_aOutputRing;
  local_78.m_pContext_HandleControllerRingsEvent = &this->m_commandRingPreParseState;
  local_78.m_pfnHandleControllerRingsEvent = handleControllerRingsEvent;
  local_78.m_paInputRing = this->m_aInputRing;
  controllerHaltAndError(&local_78,eErrorCode,addressError,pasidError);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06001510
 * symbol: init
 * prototype: int init(PtdmaVqState * this, EVP_PKEY_CTX * ctx)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void init(PtdmaVqState * this, uint32_t iVq, uint64_t vaSramPtdmaQueue)
    */

int __thiscall A53::PtdmaVqState::init(PtdmaVqState *this,EVP_PKEY_CTX *ctx)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  uint8_t uVar4;
  uint uVar5;
  uint32_t in_w2;
  ulong uVar6;
  
  uVar6 = (ulong)(uint)((int)ctx << 0xc);
  uVar1 = *(uint *)(&DAT_022c1000 + uVar6);
  (this->m_submit).m_reserved = 0;
  (this->m_submit).m_numCommandsUntilDone = 0;
  uVar1 = uVar1 >> 3 & 0xf;
  uVar4 = (char)uVar1 + '\x06';
  iVar3 = 0x40 << (ulong)uVar1;
  uVar5 = iVar3 - 0x20;
  (this->m_submit).m_sizeofQueueLog2 = uVar4;
  uVar1 = *(uint *)(uVar6 + 0x22c1008) & 0x7fffffff;
  this->m_head_lo = uVar1;
  uVar2 = *(uint *)(uVar6 + 0x22c1004);
  (this->m_submit).m_sizeofQueueLog2 = uVar4;
  (this->m_submit).m_iVq = (uint8_t)ctx;
  this->m_tail_lo = uVar2;
  (this->m_submit).m_maskVqdPointer = uVar5;
  (this->m_submit).m_offsetPut = uVar2 & uVar5;
  (this->m_submit).m_paQueue = uVar2 & 0x1fU - iVar3;
  (this->m_submit).m_vaQueue = in_w2;
  (this->m_submit).m_numCommandsAvailable = (uint16_t)(((uVar1 - uVar2) + 0x1fffe0 & uVar5) >> 5);
  return (int)this;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060023ac
 * symbol: peekElements<unsigned_int>
 * prototype: bool peekElements<unsigned_int>(InputIndirectBuffer * this, uint32_t numElems, uint * aElem, uint32_t indexFromHead)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: peekElements<unsigned int>
   DWARF original prototype: bool peekElements<unsigned_int>(InputIndirectBuffer * this, uint32_t
   numElems, uint * aElem, uint32_t indexFromHead) */

bool __thiscall
A53::InputIndirectBuffer::peekElements<unsigned_int>
          (InputIndirectBuffer *this,uint32_t numElems,uint *aElem,uint32_t indexFromHead)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  ulong uVar4;
  
  if ((uint)(this->field_0).field_0.m_countDmaComplete < indexFromHead + numElems) {
    return false;
  }
  uVar2 = (uint)(this->field_0).field_0.m_numCacheElemsMinus1;
  uVar3 = (this->field_0).field_0.m_headCache + indexFromHead & uVar2;
  for (uVar4 = (ulong)numElems; uVar4 != 0; uVar4 = uVar4 - 1) {
    uVar1 = uVar3 & uVar2;
    uVar3 = uVar3 + 1;
    *aElem = *(uint *)((this->field_0).field_0.m_vaSramCache +
                      (ulong)(uVar1 << (ulong)((this->field_0).field_0.m_sizeofElemLog2 & 0x1f)));
    aElem = aElem + 1;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06002408
 * symbol: peekElements<unsigned_int>
 * prototype: bool peekElements<unsigned_int>(InputRing * this, uint32_t numElems, uint * aElem, uint32_t indexFromHead)
 * body addresses: 104
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: peekElements<unsigned int>
   DWARF original prototype: bool peekElements<unsigned_int>(InputRing * this, uint32_t numElems,
   uint * aElem, uint32_t indexFromHead) */

bool __thiscall
A53::InputRing::peekElements<unsigned_int>
          (InputRing *this,uint32_t numElems,uint *aElem,uint32_t indexFromHead)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  ulong uVar4;
  
  if ((uint)(this->field_0).field_0.m_countDmaComplete < indexFromHead + numElems) {
    return false;
  }
  uVar2 = (1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f)) - 1;
  uVar3 = (this->field_0).field_0.m_head + indexFromHead & uVar2;
  for (uVar4 = (ulong)numElems; uVar4 != 0; uVar4 = uVar4 - 1) {
    uVar1 = uVar3 & uVar2;
    uVar3 = uVar3 + 1;
    *aElem = *(uint *)((this->field_0).field_0.m_vaSramCache +
                      (ulong)(uVar1 << (ulong)((this->field_0).field_0.m_sizeofElemLog2 & 0x1f)));
    aElem = aElem + 1;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06002470
 * symbol: readElement<unsigned_int>
 * prototype: uint32_t readElement<unsigned_int>(ConstSramRingView * this, uint32_t ringLocation, uint * elem)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElement<unsigned int>
   DWARF original prototype: uint32_t readElement<unsigned_int>(ConstSramRingView * this, uint32_t
   ringLocation, uint * elem) */

uint32_t __thiscall
A53::ConstSramRingView::readElement<unsigned_int>
          (ConstSramRingView *this,uint32_t ringLocation,uint *elem)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  
  uVar5 = *(ulong *)((long)&this->field_0 + 4);
  uVar4 = (uint)uVar5;
  uVar2 = uVar4 & 0xffff;
  uVar3 = (uint)(uVar5 >> 0x20);
  if ((uVar5 >> 0x33 & 0x1f) == 0) {
    if (uVar2 < ringLocation) {
      return 0;
    }
    iVar1 = uVar2 + 1;
    if (((uint)(uVar5 >> 0x10) & 0xffff) <= ringLocation) {
      iVar1 = 0;
    }
    uVar4 = (ringLocation - (uVar4 >> 0x10)) + iVar1;
  }
  else {
    uVar4 = ringLocation - (uVar4 >> 0x10);
    ringLocation = uVar2 & ringLocation;
    uVar4 = (1 << (ulong)(uVar3 >> 0x13 & 0x1f)) - 1U & uVar4;
  }
  if ((uVar3 & 0x1ffff) <= uVar4) {
    return 0;
  }
  *elem = *(uint *)((ulong)(this->field_0).field_0.m_vaSramRing +
                   (ulong)(ringLocation << (uVar5 >> 0x38 & 0xf)));
  return 1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060024ec
 * symbol: readElement<unsigned_short>
 * prototype: uint32_t readElement<unsigned_short>(ConstSramRingView * this, uint32_t ringLocation, unsigned short * elem)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElement<unsigned short>
   DWARF original prototype: uint32_t readElement<unsigned_short>(ConstSramRingView * this, uint32_t
   ringLocation, unsigned short * elem) */

uint32_t __thiscall
A53::ConstSramRingView::readElement<unsigned_short>
          (ConstSramRingView *this,uint32_t ringLocation,unsigned_short *elem)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  
  uVar5 = *(ulong *)((long)&this->field_0 + 4);
  uVar4 = (uint)uVar5;
  uVar2 = uVar4 & 0xffff;
  uVar3 = (uint)(uVar5 >> 0x20);
  if ((uVar5 >> 0x33 & 0x1f) == 0) {
    if (uVar2 < ringLocation) {
      return 0;
    }
    iVar1 = uVar2 + 1;
    if (((uint)(uVar5 >> 0x10) & 0xffff) <= ringLocation) {
      iVar1 = 0;
    }
    uVar4 = (ringLocation - (uVar4 >> 0x10)) + iVar1;
  }
  else {
    uVar4 = ringLocation - (uVar4 >> 0x10);
    ringLocation = uVar2 & ringLocation;
    uVar4 = (1 << (ulong)(uVar3 >> 0x13 & 0x1f)) - 1U & uVar4;
  }
  if ((uVar3 & 0x1ffff) <= uVar4) {
    return 0;
  }
  *elem = *(unsigned_short *)
           ((ulong)(this->field_0).field_0.m_vaSramRing +
           (ulong)(ringLocation << (uVar5 >> 0x38 & 0xf)));
  return 1;
}


