/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/dram\a53_mm_controller_pipeline_app__dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060028e8
 * symbol: calcMetadataSize
 * prototype: uint32_t calcMetadataSize(MmControllerPipelineRwRing * this, uint16_t numRingElemsMinus1, bool b2MiBIndexMetadata)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t calcMetadataSize(MmControllerPipelineRwRing * this, uint16_t
   numRingElemsMinus1, bool b2MiBIndexMetadata) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::calcMetadataSize
          (MmControllerPipelineRwRing *this,uint16_t numRingElemsMinus1,bool b2MiBIndexMetadata)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  uint32_t uVar4;
  
  uVar1 = numRingElemsMinus1 + 1;
  iVar2 = uVar1 * 4;
  if (!b2MiBIndexMetadata) {
    iVar2 = 0;
  }
  uVar3 = uVar1 >> 3;
  if ((numRingElemsMinus1 + 1 & 7) != 0) {
    uVar3 = uVar3 + 1;
  }
  uVar4 = HashTable::calcSize(&this->m_hashTable,(uint16_t)uVar1);
  return iVar2 + uVar1 * 4 + uVar3 * 4 + uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06002944
 * symbol: setSramRing
 * prototype: void setSramRing(MmControllerPipelineRwRing * this, uint8_t sizeofElemLog2, uint16_t numRingElemsMinus1, uint64_t vaSramRing, uint64_t vaSramMetadata, bool b2MiBIndexMetadata)
 * body addresses: 164
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setSramRing(MmControllerPipelineRwRing * this, uint8_t
   sizeofElemLog2, uint16_t numRingElemsMinus1, uint64_t vaSramRing, uint64_t vaSramMetadata, bool
   b2MiBIndexMetadata) */

void __thiscall
A53::MmControllerPipelineRwRing::setSramRing
          (MmControllerPipelineRwRing *this,uint8_t sizeofElemLog2,uint16_t numRingElemsMinus1,
          uint64_t vaSramRing,uint64_t vaSramMetadata,bool b2MiBIndexMetadata)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  long lVar4;
  uint uVar5;
  
  uVar1 = (uint)numRingElemsMinus1 * 4 + 4;
  uVar3 = uVar1;
  if (!b2MiBIndexMetadata) {
    uVar3 = 0xffffffff;
  }
  uVar5 = uVar3 & 0xffff;
  uVar2 = numRingElemsMinus1 + 1;
  (this->field_0).field_0.m_numRingElemsMinus1 = numRingElemsMinus1;
  (this->field_0).field_0.m_i2MiBMetadataOffset = (uint16_t)uVar3;
  if (!b2MiBIndexMetadata) {
    uVar5 = 0;
  }
  (this->field_0).field_0.m_vaSramRing = (uint32_t)vaSramRing;
  (this->field_0).field_0.m_vaSramMetadata = (uint32_t)vaSramMetadata;
  uVar3 = uVar2 >> 3;
  lVar4 = 0;
  uVar5 = uVar5 + uVar1;
  if ((numRingElemsMinus1 + 1 & 7) != 0) {
    uVar3 = uVar3 + 1;
  }
  for (; lVar4 != 8; lVar4 = lVar4 + 2) {
    *(short *)((long)&this->field_0 + lVar4 + 0x1e) = (short)uVar5;
    uVar5 = uVar3 + (uVar5 & 0xffff);
  }
  HashTable::setup(&this->m_hashTable,(ulong)((uint32_t)vaSramMetadata + (uVar5 & 0xffff)),
                   (uint16_t)uVar2,hashFunc);
  *(ushort *)((long)&this->field_0 + 10) =
       *(ushort *)((long)&this->field_0 + 10) & 0xfff0 | sizeofElemLog2 & 0xf;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060029e8
 * symbol: calcSramSize
 * prototype: uint32_t calcSramSize(MmControllerPipelineGcrPageLockRing * this, uint16_t numRingElemsMinus1)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t calcSramSize(MmControllerPipelineGcrPageLockRing * this,
   uint16_t numRingElemsMinus1) */

uint32_t __thiscall
A53::MmControllerPipelineGcrPageLockRing::calcSramSize
          (MmControllerPipelineGcrPageLockRing *this,uint16_t numRingElemsMinus1)

{
  uint uVar1;
  int iVar2;
  uint32_t uVar3;
  
  uVar1 = numRingElemsMinus1 + 1;
  uVar3 = HashTable::calcSize(&this->m_hashTable,(uint16_t)uVar1);
  iVar2 = uVar1 * 6 + (uVar1 >> 3);
  if ((numRingElemsMinus1 + 1 & 7) != 0) {
    iVar2 = iVar2 + 1;
  }
  return iVar2 + uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06002a30
 * symbol: setSramRing
 * prototype: void setSramRing(MmControllerPipelineGcrPageLockRing * this, uint16_t numRingElemsMinus1, uint64_t vaSramRing)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setSramRing(MmControllerPipelineGcrPageLockRing * this, uint16_t
   numRingElemsMinus1, uint64_t vaSramRing) */

void __thiscall
A53::MmControllerPipelineGcrPageLockRing::setSramRing
          (MmControllerPipelineGcrPageLockRing *this,uint16_t numRingElemsMinus1,uint64_t vaSramRing
          )

{
  uint uVar1;
  uint uVar2;
  
  uVar1 = numRingElemsMinus1 + 1;
  uVar2 = (uint32_t)vaSramRing + (uVar1 >> 3) + (uVar1 * 6 & 0xfffe);
  (this->field_0).field_0.m_vaSram = (uint32_t)vaSramRing;
  if ((numRingElemsMinus1 + 1 & 7) != 0) {
    uVar2 = uVar2 + 1;
  }
  (this->field_0).field_0.m_numRingElemsMinus1 = numRingElemsMinus1;
  (this->field_0).field_0.m_contiguousRangeBitsOffset = (uint16_t)(uVar1 * 6);
  (this->field_0).field_0.m_smallPageRangeOffset = (uint16_t)uVar1 * 4;
  HashTable::setup(&this->m_hashTable,(ulong)uVar2,(uint16_t)uVar1,hashFunc);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060030f4
 * symbol: readElementsWrapped<unsigned_int>
 * prototype: uint32_t readElementsWrapped<unsigned_int>(ConstSramRingView * this, uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, uint * aElem)
 * body addresses: 300
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElementsWrapped<unsigned int>
   DWARF original prototype: uint32_t readElementsWrapped<unsigned_int>(ConstSramRingView * this,
   uint32_t ringLocationBase, uint32_t elemOffsetStart, uint32_t numElems, uint * aElem) */

uint32_t __thiscall
A53::ConstSramRingView::readElementsWrapped<unsigned_int>
          (ConstSramRingView *this,uint32_t ringLocationBase,uint32_t elemOffsetStart,
          uint32_t numElems,uint *aElem)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  ulong uVar5;
  long lVar6;
  uint uVar7;
  
  uVar5 = *(ulong *)((long)&this->field_0 + 4);
  uVar4 = (uint)uVar5;
  uVar2 = uVar4 & 0xffff;
  uVar1 = uVar2 + 1;
  uVar7 = (uint)(uVar5 >> 0x20);
  if ((uVar5 >> 0x33 & 0x1f) == 0) {
    if (uVar2 < ringLocationBase) {
      return 0;
    }
    if ((ulong)uVar1 < (ulong)numElems + (ulong)elemOffsetStart) {
      return 0;
    }
    uVar3 = uVar1;
    if (((uint)(uVar5 >> 0x10) & 0xffff) <= ringLocationBase) {
      uVar3 = 0;
    }
    uVar3 = (ringLocationBase - (uVar4 >> 0x10)) + uVar3;
  }
  else {
    uVar3 = (1 << (ulong)(uVar7 >> 0x13 & 0x1f)) - 1U & ringLocationBase - (uVar4 >> 0x10);
    if ((uVar7 & 0x1ffff) <= uVar3) {
      return 0;
    }
    ringLocationBase = uVar2 & ringLocationBase;
  }
  if (numElems == 0) {
    return 0;
  }
  if ((uVar7 & 0x1ffff) < numElems + elemOffsetStart + uVar3) {
    return 0;
  }
  uVar7 = uVar1;
  if (ringLocationBase + elemOffsetStart <= uVar2) {
    uVar7 = 0;
  }
  uVar7 = (ringLocationBase + elemOffsetStart) - uVar7;
  uVar2 = uVar7 + numElems;
  if (uVar1 < uVar2) {
    for (; uVar7 <= (ushort)uVar5; uVar7 = uVar7 + 1) {
      *aElem = *(uint *)((ulong)(this->field_0).field_0.m_vaSramRing +
                        (ulong)(uVar7 << (uVar5 >> 0x38 & 0xf)));
      uVar5 = *(ulong *)((long)&this->field_0 + 4);
      aElem = aElem + 1;
    }
    for (lVar6 = 0; uVar2 - uVar1 != (int)lVar6; lVar6 = lVar6 + 1) {
      aElem[lVar6] = *(uint *)((ulong)(this->field_0).field_0.m_vaSramRing +
                              (ulong)(uint)((int)lVar6 <<
                                           (ulong)(*(byte *)((long)&this->field_0 + 0xb) & 0xf)));
    }
    return numElems;
  }
  for (; uVar7 < uVar2; uVar7 = uVar7 + 1) {
    *aElem = *(uint *)((ulong)(this->field_0).field_0.m_vaSramRing +
                      (ulong)(uVar7 << (ulong)(*(byte *)((long)&this->field_0 + 0xb) & 0xf)));
    aElem = aElem + 1;
  }
  return numElems;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003220
 * symbol: reset
 * prototype: void reset(PipelineStageInfo * this)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void reset(PipelineStageInfo * this) */

void __thiscall A53::MMC::MmPipelineApp::PipelineStageInfo::reset(PipelineStageInfo *this)

{
  long lVar1;
  
  for (lVar1 = 0xc; lVar1 != 0x34; lVar1 = lVar1 + 8) {
    *(ulong *)((long)this->m_pInfo + lVar1 + -0xc) =
         *(ulong *)((long)this->m_pInfo + lVar1 + -0xc) | 0xfffff;
  }
  for (lVar1 = 0; lVar1 != 0x20; lVar1 = lVar1 + 4) {
    *(undefined4 *)((long)&this->m_pRingInfo[0].m_elementIndex + lVar1) = 0xffff;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003264
 * symbol: getPipelineStageInfo
 * prototype: void getPipelineStageInfo(MmPipelineApp * this, SramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, A53ControllerCommandHeader cmdHeader, PipelineStageInfo * out_stageInfo)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void getPipelineStageInfo(MmPipelineApp * this, SramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId, A53ControllerCommandHeader
   cmdHeader, PipelineStageInfo * out_stageInfo) */

void __thiscall
A53::MMC::MmPipelineApp::getPipelineStageInfo
          (MmPipelineApp *this,SramRingView *sramRingView_PipelineCommandData,
          uint16_t pipelineCommandId,A53ControllerCommandHeader cmdHeader,
          PipelineStageInfo *out_stageInfo)

{
  getPipelineCommandDataElements
            (&sramRingView_PipelineCommandData->super_ConstSramRingView,pipelineCommandId,
             ((uint)cmdHeader.field_0 >> 8 & 0xf) + 5,0x15,(uint32_t *)out_stageInfo);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003280
 * symbol: getIndexFromHeadFromRingLocation
 * prototype: uint32_t getIndexFromHeadFromRingLocation(ConstSramRingView * this, uint16_t ringLocation)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getIndexFromHeadFromRingLocation(ConstSramRingView * this,
   uint16_t ringLocation) */

uint32_t __thiscall
A53::ConstSramRingView::getIndexFromHeadFromRingLocation
          (ConstSramRingView *this,uint16_t ringLocation)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  ulong uVar4;
  ulong uVar5;
  
  uVar4 = *(ulong *)((long)&this->field_0 + 4);
  uVar5 = uVar4 >> 0x33 & 0x1f;
  uVar3 = (uint)ringLocation - ((uint)uVar4 >> 0x10);
  iVar2 = 0;
  if ((uint)ringLocation < ((uint)(uVar4 >> 0x10) & 0xffff)) {
    iVar2 = ((uint)uVar4 & 0xffff) + 1;
  }
  uVar1 = iVar2 + uVar3;
  if ((int)uVar5 != 0) {
    uVar1 = (1 << uVar5) - 1U & uVar3;
  }
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060032c0
 * symbol: getIndexFromHeadFromRingLocation
 * prototype: uint16_t getIndexFromHeadFromRingLocation(MmControllerPipelineRwRing * this, uint16_t ringLocation)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getIndexFromHeadFromRingLocation(MmControllerPipelineRwRing *
   this, uint16_t ringLocation) */

uint16_t __thiscall
A53::MmControllerPipelineRwRing::getIndexFromHeadFromRingLocation
          (MmControllerPipelineRwRing *this,uint16_t ringLocation)

{
  ushort uVar1;
  short sVar2;
  
  uVar1 = (this->field_0).field_0.m_head;
  if (ringLocation < uVar1) {
    sVar2 = (this->field_0).field_0.m_numRingElemsMinus1 + 1;
  }
  else {
    sVar2 = 0;
  }
  return (ringLocation - uVar1) + sVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060032f0
 * symbol: getIndexFromHeadFromRingLocation
 * prototype: uint32_t getIndexFromHeadFromRingLocation(MmControllerPipelineGcrPageLockRing * this, uint16_t ringLocation)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   getIndexFromHeadFromRingLocation(MmControllerPipelineGcrPageLockRing * this, uint16_t
   ringLocation) */

uint32_t __thiscall
A53::MmControllerPipelineGcrPageLockRing::getIndexFromHeadFromRingLocation
          (MmControllerPipelineGcrPageLockRing *this,uint16_t ringLocation)

{
  ushort uVar1;
  uint uVar2;
  
  uVar1 = (this->field_0).field_0.m_head;
  if ((uint)uVar1 < (uint)ringLocation || (uint)uVar1 == (uint)ringLocation) {
    uVar2 = 0;
  }
  else {
    uVar2 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  }
  return ((uint)ringLocation - (uint)uVar1) + uVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003424
 * symbol: hashFunc
 * prototype: uint16_t hashFunc(uint32_t key)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t A53::MmControllerPipelineRwRing::hashFunc(uint32_t key)

{
  int iVar1;
  
  iVar1 = (key ^ key >> 0x10) * 0x45d9f3b;
  return ((ushort)iVar1 ^ (ushort)((uint)iVar1 >> 0x10)) * -0x60c5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003440
 * symbol: hashFunc
 * prototype: uint16_t hashFunc(uint32_t key)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint16_t A53::MmControllerPipelineGcrPageLockRing::hashFunc(uint32_t key)

{
  int iVar1;
  
  iVar1 = (key ^ key >> 0x10) * 0x45d9f3b;
  return ((ushort)iVar1 ^ (ushort)((uint)iVar1 >> 0x10)) * -0x60c5;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600345c
 * symbol: getElementIndexFromHead
 * prototype: uint16_t getElementIndexFromHead(MmControllerPipelineRwRing * this, uint16_t indexFromHead)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexFromHead(MmControllerPipelineRwRing * this,
   uint16_t indexFromHead) */

uint16_t __thiscall
A53::MmControllerPipelineRwRing::getElementIndexFromHead
          (MmControllerPipelineRwRing *this,uint16_t indexFromHead)

{
  uint uVar1;
  ushort uVar2;
  ushort uVar3;
  
  uVar2 = (this->field_0).field_0.m_numRingElemsMinus1 + 1;
  uVar1 = (uint)(this->field_0).field_0.m_head + (uint)indexFromHead;
  uVar3 = 0;
  if (uVar2 <= uVar1) {
    uVar3 = uVar2;
  }
  return (short)uVar1 - uVar3;
}


