/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/dram\mm_controller_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003cac
 * symbol: mm_controller_dram_entry
 * prototype: int mm_controller_dram_entry(uint64_t cp_param2)
 * body addresses: 372
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

int mm_controller_dram_entry(uint64_t cp_param2)

{
  uint uVar1;
  
  dev_context_init(&g_dev_context_mm,&g_sttyp_putchar_context_mm,0,(uint32_t)cp_param2,buf,0x200,
                   (mp4_debug_status_t *)0x3a00000);
  printf("%s(cp_param2 0x%016lx)\n","mm_controller_dram_entry",cp_param2);
  printf("%s: Loader Version 0x%08x: 0x%08x\n","mm_controller_dram",0x401,10);
  printf("SP: 0x%08llx in stack [0x%08lx:0x%08lx]\n",&stack0xffffffffffffffd0,0x4822000,0x4824000);
  printf("bc=%p\n",&core1_boot_config);
  printf("%s(%p)\n","MmController_BootConfiguration_show",&core1_boot_config);
  printf("m_kernelShared\n");
  A53Controller_BootConfiguration_KernelShared_show
            ((A53Controller_BootConfiguration_KernelShared *)&core1_boot_config);
  printf("m_private\n");
  A53Controller_BootConfiguration_PrivateDram_print(&core1_boot_config.field_0.field_0.m_private);
  printf("m_aslr\n");
  A53Controller_BootConfiguration_ASLR_print(&core1_boot_config.field_0.field_0.m_aslr);
  controller_dram();
  mm_controller_dev();
  controller_dev();
  mm_controller_sram();
  if ((core1_boot_config.field_0.asU32[8] & 1) == 0) {
    aarch64_BRK_with_arg(0xf0);
    return 0;
  }
  printf("Sending MSI iteratively\n");
  uVar1 = 0;
  do {
    _DAT_03000164 = core1_boot_config.field_0.asU32[9] & 0xff | _DAT_03000164;
    printf("sent MSI: %d\n",(ulong)uVar1);
    uVar1 = uVar1 + 1;
  } while( true );
}


