/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/../../controller/mm_controller/a53_mmc_bootconfiguration.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060014c8
 * symbol: MmController_BootConfiguration_getAddressInfo
 * prototype: void MmController_BootConfiguration_getAddressInfo(uint64_t vaSramBootConfiguration, uint64_t * out_appPageTableBasePA, uint64_t * out_gameBudgetPA, uint64_t * out_mapperManagedVA, uint64_t * out_mapperManagedVAEnd, uint64_t * out_multimapApertureVA, uint64_t * out_multimapApertureVAEnd)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53::MmController_BootConfiguration_getAddressInfo
               (uint64_t vaSramBootConfiguration,uint64_t *out_appPageTableBasePA,
               uint64_t *out_gameBudgetPA,uint64_t *out_mapperManagedVA,
               uint64_t *out_mapperManagedVAEnd,uint64_t *out_multimapApertureVA,
               uint64_t *out_multimapApertureVAEnd)

{
  ulong uVar1;
  ulong uVar2;
  ulong uVar3;
  
  uVar1 = *(ulong *)(vaSramBootConfiguration + 0x50);
  uVar2 = *(ulong *)(vaSramBootConfiguration + 0x58);
  uVar3 = *(ulong *)(vaSramBootConfiguration + 0x60);
  *out_appPageTableBasePA = (uVar1 & 0xffff) << 0x15;
  *out_gameBudgetPA = (uVar1 & 0xffff0000) << 5;
  *out_mapperManagedVA = uVar1 >> 0xb & 0x1ffffffe00000;
  *out_mapperManagedVAEnd = (uVar2 & 0xfffffff) << 0x15;
  *out_multimapApertureVA = uVar2 >> 7 & 0x1ffffffe00000;
  *out_multimapApertureVAEnd = (uVar3 & 0xfffffff) << 0x15;
  return;
}


