/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\a53_mm_controller_mm_trace.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006e38
 * symbol: mm_trace_write_event_OnCommandCompletion
 * prototype: void mm_trace_write_event_OnCommandCompletion(MmController * this, ControllerRings * rings, MmPipeline ePipeline, ConstSramRingView * sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader pipelineCmdDataHeader)
 * body addresses: 212
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_OnCommandCompletion(MmController * this,
   ControllerRings * rings, MmPipeline ePipeline, ConstSramRingView *
   sramRingView_PipelineCommandData, uint16_t pipelineCommandId, PipelineCommandDataHeader
   pipelineCmdDataHeader) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_OnCommandCompletion
          (MmController *this,ControllerRings *rings,MmPipeline ePipeline,
          ConstSramRingView *sramRingView_PipelineCommandData,uint16_t pipelineCommandId,
          PipelineCommandDataHeader pipelineCmdDataHeader)

{
  uint32_t uVar1;
  ushort commandRingExecutingCommandId;
  uint64_t uVar2;
  uint in_w5;
  undefined4 uStack_50;
  uint32_t local_4c;
  ulong local_48;
  
  getPipelineCommandDataElements(sramRingView_PipelineCommandData,pipelineCommandId,0,4,&uStack_50);
  uVar1 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
  if (uVar1 == 0xffffffff || uVar1 == local_4c) {
    uVar2 = readSystemClock(this);
    commandRingExecutingCommandId = (ushort)(in_w5 >> 0x10) & 0x7ff;
    if ((in_w5 & 0x300) == 0) {
      mm_trace_write_event_CommandExecuteEnd
                (this,rings,(uint32_t)uVar2,in_w5 >> 0x1b,commandRingExecutingCommandId,local_4c,
                 (uint32_t)(local_48 >> 0x20));
    }
    else {
      mm_trace_write_event_CommandExecuteEndError
                (this,rings,(uint32_t)uVar2,in_w5 >> 0x1b,commandRingExecutingCommandId,local_4c,
                 ((uint)local_48 >> 7 ^ 0xffffffff) & 1,(byte)(local_48 >> 8) & 0x7f,
                 local_48 >> 0x10,uStack_50._2_2_);
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006f0c
 * symbol: mm_trace_write_event_CommandExecuteEnd
 * prototype: void mm_trace_write_event_CommandExecuteEnd(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, uint32_t pid, uint32_t returnValue)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_CommandExecuteEnd(MmController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t
   commandRingExecutingCommandId, uint32_t pid, uint32_t returnValue) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_CommandExecuteEnd
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t commandRingExecutingCommandId,uint32_t pid,
          uint32_t returnValue)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_CommandExecuteEnd
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,
             commandRingExecutingCommandId,pid,returnValue);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006f90
 * symbol: mm_trace_write_event_CommandExecuteEndError
 * prototype: void mm_trace_write_event_CommandExecuteEndError(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t commandRingExecutingCommandId, uint32_t pid, MmTraceIsAppErrorCode eIsAppErrorCode, uint8_t eErrorCode, uint64_t addressError, uint16_t pasidError)
 * body addresses: 156
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_CommandExecuteEndError(MmController * this,
   ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t
   commandRingExecutingCommandId, uint32_t pid, MmTraceIsAppErrorCode eIsAppErrorCode, uint8_t
   eErrorCode, uint64_t addressError, uint16_t pasidError) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_CommandExecuteEndError
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t commandRingExecutingCommandId,uint32_t pid,
          MmTraceIsAppErrorCode eIsAppErrorCode,uint8_t eErrorCode,uint64_t addressError,
          uint16_t pasidError)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_CommandExecuteEndError
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,
             commandRingExecutingCommandId,pid,eIsAppErrorCode,eErrorCode,addressError,pasidError);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600702c
 * symbol: mm_trace_write_event_executeSopCommandsAndPreParseNextCommand
 * prototype: void mm_trace_write_event_executeSopCommandsAndPreParseNextCommand(MmController * this, ControllerRings * rings, ControllerPipelineCommon * pipeline, uint32_t iCommandRing, A53ControllerTraceEventType eEventType, A53ControllerCommandHeader cmdHeader, A53ControllerCommandHasPid eHasPid, uint32_t errorCode_or_returnValue)
 * body addresses: 780
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void
   mm_trace_write_event_executeSopCommandsAndPreParseNextCommand(MmController * this,
   ControllerRings * rings, ControllerPipelineCommon * pipeline, uint32_t iCommandRing,
   A53ControllerTraceEventType eEventType, A53ControllerCommandHeader cmdHeader,
   A53ControllerCommandHasPid eHasPid, uint32_t errorCode_or_returnValue) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_executeSopCommandsAndPreParseNextCommand
          (MmController *this,ControllerRings *rings,ControllerPipelineCommon *pipeline,
          uint32_t iCommandRing,A53ControllerTraceEventType eEventType,
          A53ControllerCommandHeader cmdHeader,A53ControllerCommandHasPid eHasPid,
          uint32_t errorCode_or_returnValue)

{
  uint32_t uVar1;
  uint uVar2;
  uint32_t timestamp100MHz;
  uint64_t uVar3;
  uint32_t uVar4;
  MmController_InputRingWithIndirectBufferHead *pMVar5;
  ushort ibCommandId;
  uint32_t aCmdData [15];
  uint32_t local_a4 [15];
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_68 [2];
  anon_union_4_2_653be89a_for_A53ControllerCommandHeader_0 local_58 [2];
  
  local_58[0] = cmdHeader.field_0;
  uVar3 = readSystemClock(this);
  uVar2 = iCommandRing - 1;
  if (uVar2 < 3) {
    pMVar5 = this->m_aInputRingHeadIb + uVar2;
    ibCommandId = *(ushort *)((long)&this->m_aInputRingHeadIb[uVar2].field_0 + 2) & 0x1fff;
  }
  else {
    ibCommandId = this->m_aInputRing[iCommandRing].field_0.field_0.m_head;
    pMVar5 = (MmController_InputRingWithIndirectBufferHead *)0x0;
  }
  timestamp100MHz = (uint32_t)uVar3;
  switch(eEventType) {
  case kA53ControllerTraceEventTypeMarker:
  case kA53ControllerTraceEventTypeCommandExecuteBegin:
    uVar2 = (uint)cmdHeader.field_0 >> 8 & 0xf;
    if (uVar2 != 0) {
      peekCommandDataElements(rings,iCommandRing,0,uVar2,local_a4);
    }
    if (eEventType == kA53ControllerTraceEventTypeMarker) {
      mm_trace_write_event_Marker
                (this,rings,timestamp100MHz,iCommandRing,ibCommandId,
                 (A53ControllerCommandHeader *)&local_58[0].field_0,local_a4);
    }
    else {
      local_68[0].field_0 = local_58[0].field_0;
      if (eHasPid == kA53ControllerCommandDefaultPid) {
        uVar4 = 0;
      }
      else {
        uVar4 = local_a4[(local_58[0].asU32 >> 8 & 0xf) - 1];
        local_68[0].asU32 =
             local_58[0].asU32 & 0xfffff000 |
             local_58[0].asU32 & 0xff | (local_58[0].asU32 + 0xf00 >> 8 & 0xf) << 8;
      }
      uVar1 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
      if ((uVar1 == 0) || (uVar4 == uVar1)) {
        mm_trace_write_event_CommandExecuteBegin
                  (this,rings,timestamp100MHz,iCommandRing,ibCommandId,0xffff,0xf,uVar4,
                   (A53ControllerCommandHeader *)&local_68[0].field_0,local_a4);
      }
    }
    break;
  case kA53ControllerTraceEventTypeIbResume:
    uVar3 = (pMVar5->field_0).asU64[0];
    mm_trace_write_event_IbResume
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId - 4,
               (pMVar5->field_0).asU64[1] >> 0x10,
               (uint)(byte)(uVar3 >> 0x38) | ((uint)(pMVar5->field_0).asU64[1] & 0xffff) << 8,
               (uint16_t)uVar3,(uint)(uVar3 >> 0x20) & 0xffffff);
    break;
  case kA53ControllerTraceEventTypeIbCall:
    mm_trace_write_event_IbCall
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId - 3,
               (pMVar5->field_0).asU64[1] >> 0x10,
               (uint)(byte)((pMVar5->field_0).asU64[0] >> 0x38) |
               ((uint)(pMVar5->field_0).asU64[1] & 0xffff) << 8,(uint16_t)(pMVar5->field_0).asU64[0]
              );
    return;
  case kA53ControllerTraceEventTypeIbChain:
    mm_trace_write_event_IbChain
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId - 3,
               (pMVar5->field_0).asU64[1] >> 0x10,
               (uint)*(byte *)((long)&pMVar5->field_0 + 7) |
               ((uint)(pMVar5->field_0).asU64[1] & 0xffff) << 8);
    return;
  case kA53ControllerTraceEventTypeIbReturn:
    mm_trace_write_event_IbReturn
              (this,rings,timestamp100MHz,iCommandRing,ibCommandId,*(uint16_t *)&pMVar5->field_0);
    return;
  case kA53ControllerTraceEventTypeCommandExecuteEnd:
  case kA53ControllerTraceEventTypeCommandExecuteEndError:
    local_a4[0] = 0;
    if (eHasPid != kA53ControllerCommandDefaultPid) {
      peekCommandDataElements
                (rings,iCommandRing,((uint)cmdHeader.field_0 >> 8 & 0xf) - 1,1,local_a4);
    }
    uVar4 = (this->m_rings_state).field_0.field_0.m_tracePidFilter;
    if ((uVar4 == 0) || (local_a4[0] == uVar4)) {
      if (eEventType == kA53ControllerTraceEventTypeCommandExecuteEnd) {
        mm_trace_write_event_CommandExecuteEnd
                  (this,rings,timestamp100MHz,iCommandRing,0xffff,local_a4[0],
                   errorCode_or_returnValue);
      }
      else {
        mm_trace_write_event_CommandExecuteEndError
                  (this,rings,timestamp100MHz,iCommandRing,0xffff,local_a4[0],
                   errorCode_or_returnValue >> 7 & 1,(byte)errorCode_or_returnValue & 0x7f,0,0);
      }
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06007338
 * symbol: mm_trace_write_event_Marker
 * prototype: void mm_trace_write_event_Marker(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t commandId, A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_Marker(MmController * this, ControllerRings *
   rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t commandId,
   A53ControllerCommandHeader * cmdHeader, uint32_t * aCmdData) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_Marker
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t commandId,A53ControllerCommandHeader *cmdHeader,
          uint32_t *aCmdData)

{
  ulong uVar1;
  uint uVar2;
  A53ControllerCommandHeader *unaff_x29;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_Marker
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,commandId,unaff_x29,aCmdData
            );
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060073b8
 * symbol: mm_trace_write_event_IbResume
 * prototype: void mm_trace_write_event_IbResume(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation, uint32_t ibLocationStart)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_IbResume(MmController * this, ControllerRings
   * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId,
   uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation, uint32_t
   ibLocationStart) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_IbResume
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t ibCommandId,uint64_t vaIndirectBufferBase,
          uint32_t numBufferElemsMinus1,uint16_t ringLocation,uint32_t ibLocationStart)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbResume
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,
             vaIndirectBufferBase,numBufferElemsMinus1,ringLocation,ibLocationStart);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600744c
 * symbol: mm_trace_write_event_IbCall
 * prototype: void mm_trace_write_event_IbCall(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation)
 * body addresses: 140
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_IbCall(MmController * this, ControllerRings *
   rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId, uint64_t
   vaIndirectBufferBase, uint32_t numBufferElemsMinus1, uint16_t ringLocation) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_IbCall
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t ibCommandId,uint64_t vaIndirectBufferBase,
          uint32_t numBufferElemsMinus1,uint16_t ringLocation)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbCall
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,
             vaIndirectBufferBase,numBufferElemsMinus1,ringLocation);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060074d8
 * symbol: mm_trace_write_event_IbChain
 * prototype: void mm_trace_write_event_IbChain(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId, uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_IbChain(MmController * this, ControllerRings
   * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId,
   uint64_t vaIndirectBufferBase, uint32_t numBufferElemsMinus1) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_IbChain
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t ibCommandId,uint64_t vaIndirectBufferBase,
          uint32_t numBufferElemsMinus1)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbChain
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,
             vaIndirectBufferBase,numBufferElemsMinus1);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600755c
 * symbol: mm_trace_write_event_IbReturn
 * prototype: void mm_trace_write_event_IbReturn(MmController * this, ControllerRings * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId, uint16_t ringLocation)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void mm_trace_write_event_IbReturn(MmController * this, ControllerRings
   * rings, uint32_t timestamp100MHz, MmControllerCommandRing eSource, uint16_t ibCommandId,
   uint16_t ringLocation) */

void __thiscall
A53::MMC::MmController::mm_trace_write_event_IbReturn
          (MmController *this,ControllerRings *rings,uint32_t timestamp100MHz,
          MmControllerCommandRing eSource,uint16_t ibCommandId,uint16_t ringLocation)

{
  ulong uVar1;
  uint uVar2;
  
  uVar2 = (uint)this->m_aPtdmaQueue[1].m_submit.m_sizeofQueueLog2;
  uVar1 = 0;
  if (uVar2 != 0) {
    uVar1 = (ulong)(uint)(1 << (ulong)(uVar2 - 5 & 0x1f)) << 0x20;
  }
  writeControllerTraceEvent_IbReturn
            (rings,this->m_aPtdmaQueue + 1,
             (A53_PtdmaCommandSourceTracker)(uVar1 | this->m_aVaSramPtdmaCommandSource[1]),
             callback_dmaWriteCmdCompleted,this,timestamp100MHz,eSource,ibCommandId,ringLocation);
  return;
}


