/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/a53_mm_controller_pipeline_app.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600ac30
 * symbol: initPtPoolEntry
 * prototype: PT_POOL_ENTRY initPtPoolEntry(uint64_t index16K, uint64_t index16K_end)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

PT_POOL_ENTRY A53::MMC::initPtPoolEntry(uint64_t index16K,uint64_t index16K_end)

{
  ulong uVar1;
  ulong uVar2;
  ulong uVar3;
  ulong uVar4;
  PT_POOL_ENTRY PVar5;
  
  uVar2 = -1L << (index16K & 0x3f);
  uVar4 = (1L << (index16K_end & 0x3f)) - 1;
  if (index16K < 0x40) {
    uVar1 = 0xffffffffffffffff;
  }
  else {
    uVar1 = uVar2;
    uVar2 = 0;
  }
  uVar3 = uVar4;
  if (0x7f < index16K_end) {
    uVar3 = 0xffffffffffffffff;
  }
  uVar3 = uVar3 & uVar1;
  if (index16K_end < 0x40) {
    uVar3 = 0;
    uVar2 = uVar4 & uVar2;
  }
  PVar5.mask_present[1] = uVar3;
  PVar5.mask_present[0] = uVar2;
  return (PT_POOL_ENTRY)PVar5.mask_present;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600f7f8
 * symbol: initPtPoolEntry
 * prototype: PT_POOL_ENTRY initPtPoolEntry(uint64_t index16K, uint64_t index16K_end)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

PT_POOL_ENTRY A53::MMC::initPtPoolEntry(uint64_t index16K,uint64_t index16K_end)

{
  ulong uVar1;
  ulong uVar2;
  ulong uVar3;
  ulong uVar4;
  PT_POOL_ENTRY PVar5;
  
  uVar2 = -1L << (index16K & 0x3f);
  uVar4 = (1L << (index16K_end & 0x3f)) - 1;
  if (index16K < 0x40) {
    uVar1 = 0xffffffffffffffff;
  }
  else {
    uVar1 = uVar2;
    uVar2 = 0;
  }
  uVar3 = uVar4;
  if (0x7f < index16K_end) {
    uVar3 = 0xffffffffffffffff;
  }
  uVar3 = uVar3 & uVar1;
  if (index16K_end < 0x40) {
    uVar3 = 0;
    uVar2 = uVar4 & uVar2;
  }
  PVar5.mask_present[1] = uVar3;
  PVar5.mask_present[0] = uVar2;
  return (PT_POOL_ENTRY)PVar5.mask_present;
}


