/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\a53_mm_controller_pipeline_multimap.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cd24
 * symbol: checkPdeStageCompletion_MultiMap
 * prototype: CompletionResult checkPdeStageCompletion_MultiMap(MmPipelineApp * pPipeline, PipelineStageInfo * stageInfo, uint32_t stage, PipelineExecutionInputCommandData * pInputCommandData)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkPdeStageCompletion_MultiMap
          (MmPipelineApp *pPipeline,PipelineStageInfo *stageInfo,uint32_t stage,
          PipelineExecutionInputCommandData *pInputCommandData)

{
  return (CompletionResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cd2c
 * symbol: checkPtPresentAndGpuVmPde0StageCompletion_MultiMap
 * prototype: CompletionResult checkPtPresentAndGpuVmPde0StageCompletion_MultiMap(MmPipelineApp * pPipeline, PipelineStageInfo * stageInfo, uint32_t stage, PipelineExecutionInputCommandData * pInputCommandData)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkPtPresentAndGpuVmPde0StageCompletion_MultiMap
          (MmPipelineApp *pPipeline,PipelineStageInfo *stageInfo,uint32_t stage,
          PipelineExecutionInputCommandData *pInputCommandData)

{
  return (CompletionResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cd34
 * symbol: checkFinalWorkStageCompletion_MultiMap
 * prototype: CompletionResult checkFinalWorkStageCompletion_MultiMap(MmPipelineApp * pPipeline, PipelineStageInfo * stageInfo, uint32_t stage, PipelineExecutionInputCommandData * pInputCommandData)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkFinalWorkStageCompletion_MultiMap
          (MmPipelineApp *pPipeline,PipelineStageInfo *stageInfo,uint32_t stage,
          PipelineExecutionInputCommandData *pInputCommandData)

{
  return (CompletionResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cd3c
 * symbol: executePdeStage_MultiMap
 * prototype: ExecuteResult executePdeStage_MultiMap(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executePdeStage_MultiMap
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  MmControllerPipelinePdeRing *this;
  bool bVar1;
  uint16_t uVar2;
  
  if (pPipeline->m_pRingLock[0] == pipelineCommandId || pPipeline->m_pRingLock[0] == 0x7fff) {
    this = &pPipeline->m_pdeRing;
    bVar1 = MmControllerPipelinePdeRing::canPushPdeIndex(this,(uint16_t)i2MiBOffset);
    if (bVar1) {
      uVar2 = MmControllerPipelineRwRing::getElementIndexTail
                        (&this->super_MmControllerPipelineRwRing);
      MmControllerPipelinePdeRing::pushElement(this,(uint16_t)i2MiBOffset);
      if (stageInfo->m_pRingInfo[0].m_elementIndex == 0xffff) {
        stageInfo->m_pRingInfo[0].m_elementIndex = uVar2;
      }
      stageInfo->m_pRingInfo[0].m_elementCount = stageInfo->m_pRingInfo[0].m_elementCount + 1;
      return (ExecuteResult)0x0;
    }
  }
  return (ExecuteResult)0x1000000000000;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cdcc
 * symbol: executePtPresentAndGpuVmPde0Stage_MultiMap
 * prototype: ExecuteResult executePtPresentAndGpuVmPde0Stage_MultiMap(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executePtPresentAndGpuVmPde0Stage_MultiMap
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cdd4
 * symbol: executeFinalWorkStage_MultiMap
 * prototype: ExecuteResult executeFinalWorkStage_MultiMap(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executeFinalWorkStage_MultiMap
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cddc
 * symbol: executeDvmStage_MultiMap
 * prototype: ExecuteResult executeDvmStage_MultiMap(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executeDvmStage_MultiMap
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cde4
 * symbol: postexecutePtPresentAndGpuVmPde0Stage_MultiMmap
 * prototype: ExecuteResult postexecutePtPresentAndGpuVmPde0Stage_MultiMmap(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, PipelineStageInfo * stageInfo, uint16_t pipelineCommandId)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::postexecutePtPresentAndGpuVmPde0Stage_MultiMmap
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,PipelineStageInfo *stageInfo,
          uint16_t pipelineCommandId)

{
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cdec
 * symbol: postexecutePteAndGpuVmPt1StageStage_MultiMap
 * prototype: ExecuteResult postexecutePteAndGpuVmPt1StageStage_MultiMap(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, PipelineStageInfo * stageInfo, uint16_t pipelineCommandId)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::postexecutePteAndGpuVmPt1StageStage_MultiMap
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,PipelineStageInfo *stageInfo,
          uint16_t pipelineCommandId)

{
  return (ExecuteResult)0x0;
}


