/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller/a53_mm_controller_pipeline_translation.h
 * Language recorded in DWARF: .h (header)
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600a9e8
 * symbol: vaAttributeToPde
 * prototype: uint64_t vaAttributeToPde(uint32_t attr)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::MMC::vaAttributeToPde(uint32_t attr)

{
  return (ulong)(attr >> 10) << 0x3f |
         (ulong)(attr & 0x11e | 0x81) | ((ulong)(attr >> 7) & 1) << 0x10 |
         ((ulong)(attr >> 0x11) & 1) << 0x36 | ((ulong)(attr >> 0x12) & 1) << 0x37;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600aa20
 * symbol: vaAttributeToGpuvmPde
 * prototype: uint64_t vaAttributeToGpuvmPde(uint32_t attr)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::MMC::vaAttributeToGpuvmPde(uint32_t attr)

{
  return (ulong)(attr >> 7) & 0x70 | (ulong)(attr >> 3) & 4 | ((ulong)(attr >> 0xe) & 7) << 0x30 |
         0x40000000000003;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600af5c
 * symbol: vaAttributeToPte
 * prototype: uint64_t vaAttributeToPte(uint32_t attr)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::MMC::vaAttributeToPte(uint32_t attr)

{
  return (ulong)(attr >> 10) << 0x3f |
         (ulong)(attr & 0x19e | 1) | ((ulong)(attr >> 0x11) & 1) << 0x36 |
         ((ulong)(attr >> 0x12) & 1) << 0x37;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600af88
 * symbol: vaAttributeToGpuvmPte
 * prototype: uint64_t vaAttributeToGpuvmPte(uint32_t attr)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::MMC::vaAttributeToGpuvmPte(uint32_t attr)

{
  return (ulong)(attr >> 7) & 0x70 | (ulong)(attr >> 3) & 4 | ((ulong)(attr >> 0xe) & 7) << 0x30 |
         0x40000000000003;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600f7cc
 * symbol: pdeToVaAttribute
 * prototype: uint32_t pdeToVaAttribute(uint64_t pde)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::pdeToVaAttribute(uint64_t pde)

{
  return (uint)pde & 0x17e | (uint)(pde >> 9) & 0x80 | (uint)(pde >> 0x35) & 0x400 | 0x201;
}


