/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\a53_mm_controller_pipeline_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009a4c
 * symbol: increment16KiBPaPageMultimapCount
 * prototype: uint32_t increment16KiBPaPageMultimapCount(uint32_t pa16KiBPageIndex)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::increment16KiBPaPageMultimapCount(uint32_t pa16KiBPageIndex)

{
  uint32_t uVar1;
  int iVar2;
  
  iVar2 = *(int *)((ulong)(pa16KiBPageIndex << 2) + 0x28000000);
  if (iVar2 != -1) {
    uVar1 = iVar2 + 1;
    *(uint32_t *)((ulong)(pa16KiBPageIndex << 2) + 0x28000000) = uVar1;
    return uVar1;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009a78
 * symbol: decrement16KiBPaPageMultimapCount
 * prototype: uint32_t decrement16KiBPaPageMultimapCount(uint32_t pa16KiBPageIndex)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::decrement16KiBPaPageMultimapCount(uint32_t pa16KiBPageIndex)

{
  int iVar1;
  uint32_t uVar2;
  
  iVar1 = *(int *)((ulong)(pa16KiBPageIndex << 2) + 0x28000000);
  if (iVar1 != 0) {
    uVar2 = iVar1 - 1;
    *(uint32_t *)((ulong)(pa16KiBPageIndex << 2) + 0x28000000) = uVar2;
    return uVar2;
  }
  return 0xffffffff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009aa0
 * symbol: get16KiBPaPageMultimapCount
 * prototype: uint32_t get16KiBPaPageMultimapCount(uint32_t pa16KiBPageIndex)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::get16KiBPaPageMultimapCount(uint32_t pa16KiBPageIndex)

{
  return *(uint32_t *)((ulong)(pa16KiBPageIndex << 2) + 0x28000000);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009ab0
 * symbol: increment2MiBPaPageMultimapCount
 * prototype: uint32_t increment2MiBPaPageMultimapCount(uint16_t pa2MiBPageIndex)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::increment2MiBPaPageMultimapCount(uint16_t pa2MiBPageIndex)

{
  uint32_t uVar1;
  uint32_t *puVar2;
  
  puVar2 = (uint32_t *)((ulong)pa2MiBPageIndex << 2 | 0x28340000);
  uVar1 = *puVar2;
  if (uVar1 != 0xffffffff) {
    uVar1 = uVar1 + 1;
    *puVar2 = uVar1;
    return uVar1;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009adc
 * symbol: decrement2MiBPaPageMultimapCount
 * prototype: uint32_t decrement2MiBPaPageMultimapCount(uint16_t pa2MiBPageIndex)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::decrement2MiBPaPageMultimapCount(uint16_t pa2MiBPageIndex)

{
  uint32_t uVar1;
  uint32_t *puVar2;
  
  puVar2 = (uint32_t *)((ulong)pa2MiBPageIndex << 2 | 0x28340000);
  uVar1 = *puVar2;
  if (uVar1 != 0) {
    uVar1 = uVar1 - 1;
    *puVar2 = uVar1;
    return uVar1;
  }
  return 0xffffffff;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009b04
 * symbol: get2MiBPaPageMultimapCount
 * prototype: uint32_t get2MiBPaPageMultimapCount(uint16_t pa2MiBPageIndex)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t A53::MMC::get2MiBPaPageMultimapCount(uint16_t pa2MiBPageIndex)

{
  return *(uint32_t *)((ulong)pa2MiBPageIndex << 2 | 0x28340000);
}


