/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\a53_mm_controller_gcr_ring.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006864
 * symbol: isLocked
 * prototype: bool isLocked(MmControllerPipelineGcrPageLockRing * this, uint32_t va2MiBOffset, uint32_t seqId)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isLocked(MmControllerPipelineGcrPageLockRing * this, uint32_t
   va2MiBOffset, uint32_t seqId) */

bool __thiscall
A53::MmControllerPipelineGcrPageLockRing::isLocked
          (MmControllerPipelineGcrPageLockRing *this,uint32_t va2MiBOffset,uint32_t seqId)

{
  bool bVar1;
  uint16_t uVar2;
  Iterator IStack_38;
  
  HashTable::find(&this->m_hashTable,va2MiBOffset);
  while( true ) {
    bVar1 = HashTable::Iterator::isEnd(&IStack_38);
    if (bVar1) {
      return false;
    }
    uVar2 = HashTable::Iterator::getVal(&IStack_38);
    bVar1 = MMC::MmPipelineApp::IsGreater
                      (seqId,*(uint *)((ulong)(this->field_0).field_0.m_vaSram + (ulong)uVar2 * 4)
                             >> 0x14);
    if (bVar1) break;
    HashTable::Iterator::next(&IStack_38);
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060068e0
 * symbol: IsGreater
 * prototype: bool IsGreater(uint32_t seqId1, uint32_t seqId2)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

bool A53::MMC::MmPipelineApp::IsGreater(uint32_t seqId1,uint32_t seqId2)

{
  if ((seqId2 < seqId1) && (seqId1 - seqId2 < 0x800)) {
    return true;
  }
  return seqId1 < seqId2 && 0x800 < seqId2 - seqId1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006910
 * symbol: isLocked
 * prototype: bool isLocked(MmControllerPipelineGcrPageLockRing * this, uint32_t va2MiBOffset, uint8_t index16KiB, uint32_t seqId)
 * body addresses: 180
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isLocked(MmControllerPipelineGcrPageLockRing * this, uint32_t
   va2MiBOffset, uint8_t index16KiB, uint32_t seqId) */

bool __thiscall
A53::MmControllerPipelineGcrPageLockRing::isLocked
          (MmControllerPipelineGcrPageLockRing *this,uint32_t va2MiBOffset,uint8_t index16KiB,
          uint32_t seqId)

{
  ushort uVar1;
  bool bVar2;
  uint16_t uVar3;
  Iterator IStack_48;
  
  HashTable::find(&this->m_hashTable,va2MiBOffset);
  while( true ) {
    bVar2 = HashTable::Iterator::isEnd(&IStack_48);
    if (bVar2) {
      return false;
    }
    uVar3 = HashTable::Iterator::getVal(&IStack_48);
    bVar2 = MMC::MmPipelineApp::IsGreater
                      (seqId,*(uint *)((ulong)(this->field_0).field_0.m_vaSram + (ulong)uVar3 * 4)
                             >> 0x14);
    if (((bVar2) &&
        (uVar1 = *(ushort *)
                  ((ulong)(this->field_0).field_0.m_vaSram + (ulong)uVar3 * 2 +
                  (ulong)(this->field_0).field_0.m_smallPageRangeOffset),
        (ushort)index16KiB < (uVar1 >> 7 & 0xff))) && ((uVar1 & 0x7f) <= (ushort)index16KiB)) break;
    HashTable::Iterator::next(&IStack_48);
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060069c4
 * symbol: notifyGcrCompletion
 * prototype: uint32_t notifyGcrCompletion(MmControllerPipelineGcrPageLockRing * this, uint32_t maxNumToCheck)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t notifyGcrCompletion(MmControllerPipelineGcrPageLockRing *
   this, uint32_t maxNumToCheck) */

uint32_t __thiscall
A53::MmControllerPipelineGcrPageLockRing::notifyGcrCompletion
          (MmControllerPipelineGcrPageLockRing *this,uint32_t maxNumToCheck)

{
  bool bVar1;
  bool bVar2;
  uint uVar3;
  
  bVar1 = getContiguousRangeFlag(this,(this->field_0).field_0.m_head);
  uVar3 = 0;
  while (((uVar3 < maxNumToCheck && ((this->field_0).field_0.m_gcrTailCount != 0)) &&
         (bVar2 = getContiguousRangeFlag(this,(this->field_0).field_0.m_head), bVar1 == bVar2))) {
    popElements(this,1);
    uVar3 = uVar3 + 1;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006a3c
 * symbol: getContiguousRangeFlag
 * prototype: bool getContiguousRangeFlag(MmControllerPipelineGcrPageLockRing * this, uint16_t elementIndex)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool getContiguousRangeFlag(MmControllerPipelineGcrPageLockRing * this,
   uint16_t elementIndex) */

bool __thiscall
A53::MmControllerPipelineGcrPageLockRing::getContiguousRangeFlag
          (MmControllerPipelineGcrPageLockRing *this,uint16_t elementIndex)

{
  return (1 << (ulong)(elementIndex & 7) &
         (uint)*(byte *)(ulong)((this->field_0).field_0.m_vaSram + (uint)(elementIndex >> 3) +
                               (uint)(this->field_0).field_0.m_contiguousRangeBitsOffset)) != 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006a6c
 * symbol: popElements
 * prototype: bool popElements(MmControllerPipelineGcrPageLockRing * this, uint32_t numElems)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool popElements(MmControllerPipelineGcrPageLockRing * this, uint32_t
   numElems) */

bool __thiscall
A53::MmControllerPipelineGcrPageLockRing::popElements
          (MmControllerPipelineGcrPageLockRing *this,uint32_t numElems)

{
  bool bVar1;
  
  bVar1 = numElems <= (this->field_0).field_0.m_count;
  if (bVar1) {
    HashTable::remove(&this->m_hashTable,
                      (char *)(ulong)(*(uint *)((ulong)(this->field_0).field_0.m_vaSram +
                                               (ulong)(this->field_0).field_0.m_head * 4) & 0xfffff)
                     );
    advanceHead(this,numElems);
  }
  return bVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006ac8
 * symbol: issueGcr
 * prototype: SubmitDvmGcrResult issueGcr(MmControllerPipelineGcrPageLockRing * this, ControllerStaticConfiguration static_config, ControllerPipelineDvmState * dvmState, uint16_t pipelineCommandId, uint16_t issueStartElement, uint16_t issueLastElement, uint8_t vmid)
 * body addresses: 132
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: SubmitDvmGcrResult issueGcr(MmControllerPipelineGcrPageLockRing * this,
   ControllerStaticConfiguration static_config, ControllerPipelineDvmState * dvmState, uint16_t
   pipelineCommandId, uint16_t issueStartElement, uint16_t issueLastElement, uint8_t vmid) */

SubmitDvmGcrResult __thiscall
A53::MmControllerPipelineGcrPageLockRing::issueGcr
          (MmControllerPipelineGcrPageLockRing *this,ControllerStaticConfiguration static_config,
          ControllerPipelineDvmState *dvmState,uint16_t pipelineCommandId,uint16_t issueStartElement
          ,uint16_t issueLastElement,uint8_t vmid)

{
  SubmitDvmGcrResult SVar1;
  ulong uVar2;
  ulong uVar3;
  
  uVar2 = (ulong)(this->field_0).field_0.m_vaSram;
  uVar3 = (ulong)(this->field_0).field_0.m_smallPageRangeOffset;
  SVar1 = fakeSubmitDvmGcrForMapper
                    (static_config,dvmState,
                     this->m_bigCoreMapperManagedVA +
                     (ulong)(*(int *)(uVar2 + (ulong)issueStartElement * 4) << 0x15 |
                            (*(ushort *)(uVar2 + (ulong)issueStartElement * 2 + uVar3) & 0x7f) <<
                            0xe) | 0x1000000000000,
                     this->m_bigCoreMapperManagedVA +
                     (ulong)((*(ushort *)(uVar2 + (ulong)issueLastElement * 2 + uVar3) >> 7 & 0xff)
                             * 0x4000 + *(int *)(uVar2 + (ulong)issueLastElement * 4) * 0x200000) |
                     0x1000000000000,(DvmFifoCtrlGcr)(vmid & 0xf | 0x1c3f20),
                     (A53DeviceOpSource)(pipelineCommandId & 0x7fff | 0xd6000000),0xffffffff);
  return SVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006b4c
 * symbol: handleGcr
 * prototype: SubmitDvmGcrResult handleGcr(MmControllerPipelineGcrPageLockRing * this, ControllerStaticConfiguration static_config, ControllerPipelineDvmState * dvmState, uint16_t pipelineCommandId, uint32_t i2MiBTlbiProgress, uint16_t startElementIndex, uint16_t lastElementIndex, uint8_t vmid)
 * body addresses: 572
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: SubmitDvmGcrResult handleGcr(MmControllerPipelineGcrPageLockRing *
   this, ControllerStaticConfiguration static_config, ControllerPipelineDvmState * dvmState,
   uint16_t pipelineCommandId, uint32_t i2MiBTlbiProgress, uint16_t startElementIndex, uint16_t
   lastElementIndex, uint8_t vmid) */

SubmitDvmGcrResult __thiscall
A53::MmControllerPipelineGcrPageLockRing::handleGcr
          (MmControllerPipelineGcrPageLockRing *this,ControllerStaticConfiguration static_config,
          ControllerPipelineDvmState *dvmState,uint16_t pipelineCommandId,uint32_t i2MiBTlbiProgress
          ,uint16_t startElementIndex,uint16_t lastElementIndex,uint8_t vmid)

{
  uint uVar1;
  ushort uVar2;
  short sVar3;
  short sVar4;
  uint16_t issueLastElement;
  uint16_t uVar5;
  uint16_t uVar6;
  uint32_t uVar7;
  SubmitDvmGcrResult SVar8;
  uint uVar9;
  ulong uVar10;
  short sVar11;
  uint uVar12;
  uint uVar13;
  uint uVar14;
  ushort uVar15;
  int iVar16;
  int local_68;
  
  uVar7 = getIndexFromHeadFromRingLocation(this,startElementIndex);
  if ((this->field_0).field_0.m_gcrTailCount < uVar7) {
    uVar12 = 0;
  }
  else {
    uVar7 = getIndexFromHeadFromRingLocation(this,lastElementIndex);
    uVar9 = (uint)(this->field_0).field_0.m_gcrTailCount;
    uVar12 = 0;
    if (uVar9 <= uVar7) {
      uVar12 = (uVar7 + 1) - uVar9 & 0xffff;
    }
  }
  uVar9 = 0;
  local_68 = 0;
  iVar16 = 0;
  uVar13 = 0;
  uVar15 = 0x80;
  uVar14 = 0xffffffff;
  while( true ) {
    sVar3 = (short)uVar13;
    sVar4 = (short)iVar16;
    if (uVar12 <= uVar9) break;
    uVar5 = getElementIndexFromHead(this,(short)uVar9 + (this->field_0).field_0.m_gcrTailCount);
    uVar10 = (ulong)(this->field_0).field_0.m_vaSram;
    uVar1 = *(uint *)(uVar10 + (ulong)uVar5 * 4) & 0xfffff;
    if (i2MiBTlbiProgress <= uVar1) break;
    uVar2 = *(ushort *)
             (uVar10 + (ulong)uVar5 * 2 + (ulong)(this->field_0).field_0.m_smallPageRangeOffset);
    if (((uVar14 != 0xffffffff && uVar14 != uVar1 - 1) ||
        ((uVar15 != (uVar2 & 0x7f) && ((uVar15 != 0x80 || ((uVar2 & 0x7f) != 0)))))) &&
       (uVar13 = uVar9, iVar16 != 0)) {
      uVar6 = getElementIndexFromHead(this,sVar3 + (this->field_0).field_0.m_gcrTailCount);
      issueLastElement =
           getElementIndexFromHead
                     (this,(sVar4 + sVar3 + (this->field_0).field_0.m_gcrTailCount) - 1);
      SVar8 = issueGcr(this,static_config,dvmState,pipelineCommandId,uVar6,issueLastElement,vmid);
      if (SVar8 != kSubmitDvmGcrResultSuccess) {
        return SVar8;
      }
      local_68 = iVar16 + local_68;
      iVar16 = 0;
      *(byte *)((long)&this->field_0 + 0x10) = *(byte *)((long)&this->field_0 + 0x10) ^ 1;
    }
    setContiguousRangeFlag(this,uVar5,(bool)(*(byte *)((long)&this->field_0 + 0x10) & 1));
    iVar16 = iVar16 + 1;
    uVar9 = uVar9 + 1;
    uVar15 = uVar2 >> 7 & 0xff;
    uVar14 = uVar1;
  }
  sVar11 = (short)local_68;
  if (iVar16 != 0) {
    uVar5 = getElementIndexFromHead(this,sVar3 + (this->field_0).field_0.m_gcrTailCount);
    uVar6 = getElementIndexFromHead
                      (this,(sVar4 + sVar3 + (this->field_0).field_0.m_gcrTailCount) - 1);
    SVar8 = issueGcr(this,static_config,dvmState,pipelineCommandId,uVar5,uVar6,vmid);
    if (SVar8 != kSubmitDvmGcrResultSuccess) {
      return SVar8;
    }
    sVar11 = sVar4 + sVar11;
    *(byte *)((long)&this->field_0 + 0x10) = *(byte *)((long)&this->field_0 + 0x10) ^ 1;
  }
  (this->field_0).field_0.m_gcrTailCount = sVar11 + (this->field_0).field_0.m_gcrTailCount;
  return kSubmitDvmGcrResultSuccess;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006d88
 * symbol: getElementIndexFromHead
 * prototype: uint16_t getElementIndexFromHead(MmControllerPipelineGcrPageLockRing * this, uint16_t indexFromHead)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getElementIndexFromHead(MmControllerPipelineGcrPageLockRing *
   this, uint16_t indexFromHead) */

uint16_t __thiscall
A53::MmControllerPipelineGcrPageLockRing::getElementIndexFromHead
          (MmControllerPipelineGcrPageLockRing *this,uint16_t indexFromHead)

{
  uint uVar1;
  ushort uVar2;
  ushort uVar3;
  
  uVar2 = (this->field_0).field_0.m_numRingElemsMinus1 + 1;
  uVar1 = (uint)(this->field_0).field_0.m_head + (uint)indexFromHead;
  uVar3 = 0;
  if (uVar2 <= uVar1) {
    uVar3 = uVar2;
  }
  return (short)uVar1 - uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006dac
 * symbol: setContiguousRangeFlag
 * prototype: void setContiguousRangeFlag(MmControllerPipelineGcrPageLockRing * this, uint16_t elementIndex, bool bIsSmallPage)
 * body addresses: 60
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setContiguousRangeFlag(MmControllerPipelineGcrPageLockRing * this,
   uint16_t elementIndex, bool bIsSmallPage) */

void __thiscall
A53::MmControllerPipelineGcrPageLockRing::setContiguousRangeFlag
          (MmControllerPipelineGcrPageLockRing *this,uint16_t elementIndex,bool bIsSmallPage)

{
  byte bVar1;
  byte bVar2;
  byte *pbVar3;
  
  pbVar3 = (byte *)(ulong)((this->field_0).field_0.m_vaSram + (uint)(elementIndex >> 3) +
                          (uint)(this->field_0).field_0.m_contiguousRangeBitsOffset);
  bVar1 = (byte)(1 << (ulong)(elementIndex & 7));
  bVar2 = bVar1 ^ 0xff;
  if (!bIsSmallPage) {
    bVar1 = 0;
  }
  *pbVar3 = *pbVar3 & bVar2 | bVar1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006de8
 * symbol: validate
 * prototype: bool validate(MmControllerPipelineGcrPageLockRing * this, MmControllerPipelineSramMetadata * sramMetadata, uint64_t bigCorePageTableBasePA, uint16_t elementIndexStart, uint16_t elementCount)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool validate(MmControllerPipelineGcrPageLockRing * this,
   MmControllerPipelineSramMetadata * sramMetadata, uint64_t bigCorePageTableBasePA, uint16_t
   elementIndexStart, uint16_t elementCount) */

bool __thiscall
A53::MmControllerPipelineGcrPageLockRing::validate
          (MmControllerPipelineGcrPageLockRing *this,MmControllerPipelineSramMetadata *sramMetadata,
          uint64_t bigCorePageTableBasePA,uint16_t elementIndexStart,uint16_t elementCount)

{
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06006df0
 * symbol: advanceHead
 * prototype: void advanceHead(MmControllerPipelineGcrPageLockRing * this, uint32_t numElems)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void advanceHead(MmControllerPipelineGcrPageLockRing * this, uint32_t
   numElems) */

void __thiscall
A53::MmControllerPipelineGcrPageLockRing::advanceHead
          (MmControllerPipelineGcrPageLockRing *this,uint32_t numElems)

{
  uint uVar1;
  ushort uVar2;
  uint16_t uVar3;
  
  uVar2 = (this->field_0).field_0.m_numRingElemsMinus1;
  uVar1 = (this->field_0).field_0.m_head + numElems;
  (this->field_0).field_0.m_count = (this->field_0).field_0.m_count - (short)numElems;
  (this->field_0).field_0.m_gcrTailCount = (this->field_0).field_0.m_gcrTailCount - (short)numElems;
  uVar3 = (uint16_t)uVar1;
  (this->field_0).field_0.m_head = uVar3;
  if ((uint)uVar2 < (uVar1 & 0xffff)) {
    (this->field_0).field_0.m_head = (uVar3 - 1) - uVar2;
  }
  return;
}


