/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\a53_mm_controller_pipeline_map.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009b18
 * symbol: checkPtPresentAndGpuVmPde0StageCompletion_Map
 * prototype: CompletionResult checkPtPresentAndGpuVmPde0StageCompletion_Map(MmPipelineApp * pPipeline, PipelineStageInfo * stageInfo, uint32_t stage, PipelineExecutionInputCommandData * pInputCommandData)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkPtPresentAndGpuVmPde0StageCompletion_Map
          (MmPipelineApp *pPipeline,PipelineStageInfo *stageInfo,uint32_t stage,
          PipelineExecutionInputCommandData *pInputCommandData)

{
  CompletionResult CVar1;
  CompletionResult CVar2;
  CompletionResult CVar3;
  
  CVar1 = checkRingIdmaCompletion<A53::MmControllerPipeline16KiBPagePresentBitsRing>
                    (&pPipeline->m_16KiBpagePresentBitsRing,stageInfo,1,
                     *(uint *)&stageInfo->m_pInfo[1].field_0x4 & 0xfffff);
  CVar2 = checkRingIdmaCompletion<A53::MmControllerPipelineGpuVmPde0Ring>
                    (&pPipeline->m_gpuVmPde0Ring,stageInfo,3,
                     *(uint *)&stageInfo->m_pInfo[1].field_0x4 & 0xfffff);
  CVar3 = (CompletionResult)0x0;
  if ((((uint)CVar1 & 0x300000) == 0x100000) && (((uint)CVar2 & 0x300000) == 0x100000)) {
    if (((uint)CVar1 & 0xfffff) <= ((uint)CVar2 & 0xfffff)) {
      CVar2 = CVar1;
    }
    CVar3 = (CompletionResult)((uint)CVar2 & 0xfffff | 0x100000);
  }
  return CVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009ba8
 * symbol: checkRingIdmaCompletion<A53::MmControllerPipeline16KiBPagePresentBitsRing>
 * prototype: CompletionResult checkRingIdmaCompletion<A53::MmControllerPipeline16KiBPagePresentBitsRing>(MmControllerPipeline16KiBPagePresentBitsRing * ring, PipelineStageInfo * stageInfo, uint32_t ringIdx, uint32_t i2MiBOffsetEnd)
 * body addresses: 168
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkRingIdmaCompletion<A53::MmControllerPipeline16KiBPagePresentBitsRing>
          (MmControllerPipeline16KiBPagePresentBitsRing *ring,PipelineStageInfo *stageInfo,
          uint32_t ringIdx,uint32_t i2MiBOffsetEnd)

{
  ushort indexFromHead;
  uint16_t uVar1;
  CompletionResult CVar2;
  uint16_t *puVar3;
  
  puVar3 = &stageInfo->m_pRingInfo[ringIdx].m_elementCount;
  if (*puVar3 == 0) {
LAB_06009c2c:
    CVar2 = (CompletionResult)(i2MiBOffsetEnd & 0xfffff | 0x100000);
  }
  else {
    indexFromHead = (ring->super_MmControllerPipelineRwRing).field_0.field_0.m_pTailCount[1];
    if ((uint)indexFromHead !=
        (uint)(ring->super_MmControllerPipelineRwRing).field_0.field_0.m_pHeadCount[1]) {
      uVar1 = MmControllerPipelineRwRing::getIndexFromHeadFromRingLocation
                        (&ring->super_MmControllerPipelineRwRing,
                         stageInfo->m_pRingInfo[ringIdx].m_elementIndex);
      if ((uint)uVar1 <= (uint)indexFromHead && (uint)indexFromHead != (uint)uVar1) {
        if ((uint)indexFromHead < (uint)*puVar3 + (uint)uVar1) {
          uVar1 = MmControllerPipelineRwRing::getElementIndexFromHead
                            (&ring->super_MmControllerPipelineRwRing,indexFromHead);
          i2MiBOffsetEnd =
               *(uint *)((ulong)((ring->super_MmControllerPipelineRwRing).field_0.field_0.
                                 m_vaSramMetadata +
                                (uint)(ring->super_MmControllerPipelineRwRing).field_0.field_0.
                                      m_i2MiBMetadataOffset) + (ulong)uVar1 * 4) & 0xfffff;
        }
        goto LAB_06009c2c;
      }
    }
    CVar2 = (CompletionResult)0x0;
  }
  return CVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009c50
 * symbol: checkRingIdmaCompletion<A53::MmControllerPipelineGpuVmPde0Ring>
 * prototype: CompletionResult checkRingIdmaCompletion<A53::MmControllerPipelineGpuVmPde0Ring>(MmControllerPipelineGpuVmPde0Ring * ring, PipelineStageInfo * stageInfo, uint32_t ringIdx, uint32_t i2MiBOffsetEnd)
 * body addresses: 160
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkRingIdmaCompletion<A53::MmControllerPipelineGpuVmPde0Ring>
          (MmControllerPipelineGpuVmPde0Ring *ring,PipelineStageInfo *stageInfo,uint32_t ringIdx,
          uint32_t i2MiBOffsetEnd)

{
  ushort indexFromHead;
  uint16_t uVar1;
  CompletionResult CVar2;
  uint16_t *puVar3;
  
  puVar3 = &stageInfo->m_pRingInfo[ringIdx].m_elementCount;
  if (*puVar3 == 0) {
LAB_06009ccc:
    CVar2 = (CompletionResult)(i2MiBOffsetEnd & 0xfffff | 0x100000);
  }
  else {
    indexFromHead = (ring->super_MmControllerPipelineRwRing).field_0.field_0.m_pTailCount[1];
    if ((uint)indexFromHead !=
        (uint)(ring->super_MmControllerPipelineRwRing).field_0.field_0.m_pHeadCount[1]) {
      uVar1 = MmControllerPipelineRwRing::getIndexFromHeadFromRingLocation
                        (&ring->super_MmControllerPipelineRwRing,
                         stageInfo->m_pRingInfo[ringIdx].m_elementIndex);
      if ((uint)uVar1 <= (uint)indexFromHead && (uint)indexFromHead != (uint)uVar1) {
        if ((uint)indexFromHead < (uint)*puVar3 + (uint)uVar1) {
          uVar1 = MmControllerPipelineRwRing::getElementIndexFromHead
                            (&ring->super_MmControllerPipelineRwRing,indexFromHead);
          i2MiBOffsetEnd =
               *(uint *)((ulong)(ring->super_MmControllerPipelineRwRing).field_0.field_0.
                                m_vaSramMetadata + (ulong)uVar1 * 4) & 0xfffff;
        }
        goto LAB_06009ccc;
      }
    }
    CVar2 = (CompletionResult)0x0;
  }
  return CVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009cf0
 * symbol: checkFinalWorkStageCompletion_Map
 * prototype: CompletionResult checkFinalWorkStageCompletion_Map(MmPipelineApp * pPipeline, PipelineStageInfo * stageInfo, uint32_t stage, PipelineExecutionInputCommandData * pInputCommandData)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

CompletionResult
A53::MMC::MmPipelineApp::checkFinalWorkStageCompletion_Map
          (MmPipelineApp *pPipeline,PipelineStageInfo *stageInfo,uint32_t stage,
          PipelineExecutionInputCommandData *pInputCommandData)

{
  ulong uVar1;
  uint16_t uVar2;
  uint uVar3;
  uint16_t *puVar4;
  CompletionResult CVar5;
  
  uVar3 = 0xffffffff;
  puVar4 = &stageInfo->m_pRingInfo[0].m_elementCount;
  do {
    uVar3 = uVar3 + 1;
    if (7 < uVar3) {
      uVar1 = ((pInputCommandData->m_va + 0x1fffff) - pPipeline->m_bigCoreMapperManagedVA) +
              pInputCommandData->m_vaSize;
      CVar5 = (CompletionResult)((uint)(uVar1 >> 0x15) & 0xfffff | 0x100000);
      if ((*(uint *)stageInfo & 0xfffff) != (uint)(uVar1 >> 0x15)) {
        CVar5 = (CompletionResult)0x0;
      }
      return CVar5;
    }
    uVar2 = *puVar4;
    puVar4 = puVar4 + 2;
  } while (uVar2 == 0);
  return (CompletionResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06009d54
 * symbol: executePtPresentAndGpuVmPde0Stage_Map
 * prototype: ExecuteResult executePtPresentAndGpuVmPde0Stage_Map(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 720
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Type propagation algorithm not settling */
/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executePtPresentAndGpuVmPde0Stage_Map
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  uint uVar1;
  uint uVar2;
  MmControllerPipelineGpuVmPde0Ring *pMVar3;
  MmControllerPipeline16KiBPagePresentBitsRing *this;
  uint uVar4;
  ushort uVar5;
  bool bVar6;
  uint16_t uVar7;
  uint16_t uVar8;
  ulong uVar9;
  uint64_t uVar10;
  ulong uVar11;
  byte local_58;
  uint7 uStack_57;
  
  uVar5 = stageInfo->m_pRingInfo[0].m_elementIndex;
  uVar2 = (pPipeline->m_pdeRing).super_MmControllerPipelineRwRing.field_0.field_0.
          m_numRingElemsMinus1 + 1;
  uVar1 = (uint)uVar5 +
          (i2MiBOffset -
           *(int *)((ulong)(pPipeline->m_pdeRing).super_MmControllerPipelineRwRing.field_0.field_0.
                           m_vaSramMetadata + (ulong)uVar5 * 4) & 0xffff);
  uVar4 = 0;
  if ((uVar2 & 0xffff) <= uVar1) {
    uVar4 = uVar2 & 0xffff;
  }
  MmControllerPipelineRwRing::readElement<unsigned_long>
            (&(pPipeline->m_pdeRing).super_MmControllerPipelineRwRing,kWork,uVar1 - uVar4 & 0xffff,
             (ulong *)&local_58);
  uVar9 = pInputCommandData->m_va;
  bVar6 = false;
  uVar11 = uVar9;
  if (uVar9 - pPipeline->m_bigCoreMapperManagedVA >> 0x15 != (ulong)i2MiBOffset) {
    uVar11 = pPipeline->m_bigCoreMapperManagedVA + (ulong)i2MiBOffset * 0x200000;
  }
  if ((uVar11 & 0x1fffff) == 0) {
    bVar6 = (uVar11 + 0x200000 & 0xffffffffffe00000) <= pInputCommandData->m_vaSize + uVar9;
  }
  uVar10 = (pInputCommandData->field_4).asMapDirect.m_dmemOffset16KPages;
  if (uVar10 == 0xffffffffffffffff) {
    if (bVar6) goto LAB_06009e2c;
  }
  else if ((bool)(bVar6 & (((int)uVar11 - (int)uVar9) + (int)uVar10 * 0x4000 & 0x1fffffU) == 0)) {
LAB_06009e2c:
    if ((local_58 & 1) == 0) {
      if (pPipeline->m_pRingLock[3] != pipelineCommandId && pPipeline->m_pRingLock[3] != 0x7fff) {
        return (ExecuteResult)0xc01000000000000;
      }
      pMVar3 = &pPipeline->m_gpuVmPde0Ring;
      bVar6 = MmControllerPipelineRwRing::canPushNElements
                        (&pMVar3->super_MmControllerPipelineRwRing,1);
      if (!bVar6) {
        return (ExecuteResult)0xc01000000000000;
      }
      uVar7 = MmControllerPipelineRwRing::getElementIndexTail
                        (&pMVar3->super_MmControllerPipelineRwRing);
      MmControllerPipelineGpuVmPde0Ring::pushElement(pMVar3,(uint16_t)i2MiBOffset,false);
      if (stageInfo->m_pRingInfo[3].m_elementIndex == 0xffff) {
        stageInfo->m_pRingInfo[3].m_elementIndex = uVar7;
      }
      stageInfo->m_pRingInfo[3].m_elementCount = stageInfo->m_pRingInfo[3].m_elementCount + 1;
      return (ExecuteResult)0x0;
    }
    uVar9 = 0x4d000000000000;
    goto LAB_06009f38;
  }
  this = &pPipeline->m_16KiBpagePresentBitsRing;
  uVar7 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing);
  if ((local_58 & 1) == 0) {
    if (pPipeline->m_pRingLock[1] != pipelineCommandId && pPipeline->m_pRingLock[1] != 0x7fff) {
      return (ExecuteResult)0x401000000000000;
    }
    bVar6 = MmControllerPipelineRwRing::canPushNElements(&this->super_MmControllerPipelineRwRing,1);
    if (!bVar6) {
      return (ExecuteResult)0x401000000000000;
    }
    if (pPipeline->m_pRingLock[3] != pipelineCommandId && pPipeline->m_pRingLock[3] != 0x7fff) {
      return (ExecuteResult)0xc01000000000000;
    }
    pMVar3 = &pPipeline->m_gpuVmPde0Ring;
    bVar6 = MmControllerPipelineRwRing::canPushNElements
                      (&pMVar3->super_MmControllerPipelineRwRing,1);
    if (!bVar6) {
      return (ExecuteResult)0xc01000000000000;
    }
    uVar8 = MmControllerPipelineSramMetadata::getFreePageTable(&pPipeline->m_sramMetadata);
    if (uVar8 == 0x4cc8) {
      uVar9 = 0x5d000000000000;
LAB_06009f38:
      return (ExecuteResult)(uVar9 | uVar11 & 0xffffffffffff);
    }
    MmControllerPipeline16KiBPagePresentBitsRing::pushElement(this,uVar8,i2MiBOffset,false);
    uVar8 = MmControllerPipelineRwRing::getElementIndexTail
                      (&pMVar3->super_MmControllerPipelineRwRing);
    MmControllerPipelineGpuVmPde0Ring::pushElement(pMVar3,(uint16_t)i2MiBOffset,false);
    if (stageInfo->m_pRingInfo[3].m_elementIndex == 0xffff) {
      stageInfo->m_pRingInfo[3].m_elementIndex = uVar8;
    }
    stageInfo->m_pRingInfo[3].m_elementCount = stageInfo->m_pRingInfo[3].m_elementCount + 1;
  }
  else {
    if (pPipeline->m_pRingLock[1] != pipelineCommandId && pPipeline->m_pRingLock[1] != 0x7fff) {
      return (ExecuteResult)0x401000000000000;
    }
    uVar11 = (((ulong)uStack_57 & 0xffff0) * 0x100 + 0xf7fa000) -
             pPipeline->m_bigCorePageTableBasePA;
    bVar6 = MmControllerPipelineRwRing::canPushAndRead
                      (&this->super_MmControllerPipelineRwRing,(uint)uVar11 >> 0xc & 0xffff);
    if (!bVar6) {
      return (ExecuteResult)0x401000000000000;
    }
    MmControllerPipeline16KiBPagePresentBitsRing::pushElement
              (this,(uint16_t)(uVar11 >> 0xc),i2MiBOffset,true);
  }
  if (stageInfo->m_pRingInfo[1].m_elementIndex == 0xffff) {
    stageInfo->m_pRingInfo[1].m_elementIndex = uVar7;
  }
  stageInfo->m_pRingInfo[1].m_elementCount = stageInfo->m_pRingInfo[1].m_elementCount + 1;
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600a024
 * symbol: readElement<unsigned_long>
 * prototype: uint32_t readElement<unsigned_long>(MmControllerPipelineRwRing * this, Section section, uint32_t ringLocation, ulong * elem)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElement<unsigned long>
   DWARF original prototype: uint32_t readElement<unsigned_long>(MmControllerPipelineRwRing * this,
   Section section, uint32_t ringLocation, ulong * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::readElement<unsigned_long>
          (MmControllerPipelineRwRing *this,Section section,uint32_t ringLocation,ulong *elem)

{
  uint16_t uVar1;
  uint32_t uVar2;
  
  uVar1 = getIndexFromHeadFromRingLocation(this,(uint16_t)ringLocation);
  if ((*(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0xe) <= uVar1) &&
     (uVar1 < *(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0x14))) {
    uVar2 = readElement<unsigned_long>(this,ringLocation,elem);
    return uVar2;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600a0a4
 * symbol: pushElement
 * prototype: void pushElement(MmControllerPipelineGpuVmPde0Ring * this, uint16_t gpuVmPde0Index, bool bNeedIdma)
 * body addresses: 124
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushElement(MmControllerPipelineGpuVmPde0Ring * this, uint16_t
   gpuVmPde0Index, bool bNeedIdma) */

void __thiscall
A53::MmControllerPipelineGpuVmPde0Ring::pushElement
          (MmControllerPipelineGpuVmPde0Ring *this,uint16_t gpuVmPde0Index,bool bNeedIdma)

{
  uint16_t uVar1;
  UidMetadata metadata;
  
  if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_numRingElemsMinus1 + 1 ==
      (uint)(this->super_MmControllerPipelineRwRing).field_0.field_0.m_count) {
    MmControllerPipelineRwRing::popElements(&this->super_MmControllerPipelineRwRing,1);
  }
  uVar1 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing);
  metadata.field_0.asU32._1_3_ = 0;
  metadata.field_0.asU32._0_1_ = bNeedIdma;
  MmControllerPipelineRwRing::setupMetadata
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,metadata,0xffffffff,bNeedIdma,true)
  ;
  (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count =
       (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count + 1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600a120
 * symbol: pushElement
 * prototype: void pushElement(MmControllerPipeline16KiBPagePresentBitsRing * this, uint16_t ptIndex, uint32_t i2MiBOffset, bool bNeedIdma)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushElement(MmControllerPipeline16KiBPagePresentBitsRing * this,
   uint16_t ptIndex, uint32_t i2MiBOffset, bool bNeedIdma) */

void __thiscall
A53::MmControllerPipeline16KiBPagePresentBitsRing::pushElement
          (MmControllerPipeline16KiBPagePresentBitsRing *this,uint16_t ptIndex,uint32_t i2MiBOffset,
          bool bNeedIdma)

{
  uint16_t uVar1;
  
  if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_numRingElemsMinus1 + 1 ==
      (uint)(this->super_MmControllerPipelineRwRing).field_0.field_0.m_count) {
    MmControllerPipelineRwRing::popElements(&this->super_MmControllerPipelineRwRing,1);
  }
  uVar1 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing);
  MmControllerPipelineRwRing::setupMetadata
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,(UidMetadata)i2MiBOffset,
             i2MiBOffset,bNeedIdma,true);
  (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count =
       (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count + 1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600a1a0
 * symbol: executePteAndGpuVmPtStage_Map
 * prototype: ExecuteResult executePteAndGpuVmPtStage_Map(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 2120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Type propagation algorithm not settling */
/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executePteAndGpuVmPtStage_Map
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  uint uVar1;
  MmControllerPipelinePdeRing *stageInfo_00;
  uint uVar2;
  ulong uVar3;
  ushort uVar4;
  ushort uVar5;
  bool bMulti;
  bool bVar6;
  uint16_t uVar7;
  uint32_t uVar8;
  uint64_t uVar9;
  uint64_t uVar10;
  ControllerPipelineCommon *pCVar11;
  ControllerRuntimeConfiguration *runtime_config_00;
  ControllerRuntimeConfiguration *paPageIndex16K;
  ControllerRuntimeConfiguration *index16K_end;
  uint uVar12;
  ulong uVar13;
  ControllerRuntimeConfiguration *index16K;
  ControllerRuntimeConfiguration *indexVa16K;
  ExecuteResult EVar14;
  ulong uVar15;
  PT_POOL_ENTRY *ptPoolEntry;
  uint uVar16;
  uint64_t uVar18;
  PT_POOL_ENTRY PVar19;
  PA_ALLOC_BLOCK PVar20;
  PA_ALLOC_BLOCK PVar21;
  uint32_t in_stack_fffffffffffffee8;
  uint64_t local_d0;
  ControllerPipelineCommon *local_c0;
  uint64_t local_a8;
  PA_ALLOC_BLOCK local_98;
  PT_POOL_ENTRY local_88;
  PT_POOL_ENTRY local_78;
  ulong local_68;
  ulong uVar17;
  
  uVar4 = stageInfo->m_pRingInfo[0].m_elementIndex;
  ptPoolEntry = (PT_POOL_ENTRY *)(ulong)i2MiBOffset;
  stageInfo_00 = &pPipeline->m_pdeRing;
  uVar5 = (pPipeline->m_pdeRing).super_MmControllerPipelineRwRing.field_0.field_0.
          m_numRingElemsMinus1 + 1;
  uVar1 = (uint)uVar4 +
          (i2MiBOffset -
           *(int *)((ulong)(pPipeline->m_pdeRing).super_MmControllerPipelineRwRing.field_0.field_0.
                           m_vaSramMetadata + (ulong)uVar4 * 4) & 0xffff);
  uVar12 = 0;
  if (uVar5 <= uVar1) {
    uVar12 = (uint)uVar5;
  }
  uVar1 = uVar1 - uVar12;
  uVar12 = uVar1 & 0xffff;
  MmControllerPipelineRwRing::readElement<unsigned_long>
            (&stageInfo_00->super_MmControllerPipelineRwRing,kWork,uVar12,&local_68);
  uVar3 = pInputCommandData->m_va;
  uVar15 = pInputCommandData->m_vaSize + uVar3;
  if ((PT_POOL_ENTRY *)(uVar3 - pPipeline->m_bigCoreMapperManagedVA >> 0x15) != ptPoolEntry) {
    uVar3 = pPipeline->m_bigCoreMapperManagedVA + (ulong)i2MiBOffset * 0x200000;
  }
  uVar13 = uVar3 + 0x200000 & 0xffffffffffe00000;
  uVar9 = vaAttributeToPde(*(uint *)&pInputCommandData->field_0x10 & 0xfffff);
  uVar10 = vaAttributeToGpuvmPde(*(uint *)&pInputCommandData->field_0x10 & 0xfffff);
  bMulti = false;
  if (uVar3 < pPipeline->m_bigCoreMultimapApertureVAEnd) {
    bMulti = pPipeline->m_bigCoreMultimapApertureVA <= uVar3;
  }
  bVar6 = (uVar3 & 0x1fffff) != 0;
  if (pInputCommandData->field_4 ==
      (anon_union_8_2_c1c81101_for_PipelineExecutionInputCommandData_4)0xffffffffffffffff) {
    if (!bVar6 && uVar15 >= uVar13) {
      uVar7 = MmControllerPipelineSramMetadata::allocate2MiBPaPage
                        (&pPipeline->m_sramMetadata,bMulti,false);
      uVar16 = (uint)uVar7;
      if (uVar7 == 0xffff) {
        uVar15 = 0x55000000000000;
        goto LAB_0600a528;
      }
      goto LAB_0600a2f8;
    }
LAB_0600a39c:
    index16K_end = (ControllerRuntimeConfiguration *)(uVar15 >> 0xe & 0x7f);
    if (uVar13 <= uVar15) {
      index16K_end = (ControllerRuntimeConfiguration *)&N_ENTRY_INVALID1;
      uVar15 = uVar13;
    }
    if (pPipeline->m_pRingLock[2] != pipelineCommandId && pPipeline->m_pRingLock[2] != 0x7fff) {
      return (ExecuteResult)0x801000000000000;
    }
    index16K = (ControllerRuntimeConfiguration *)(uVar3 >> 0xe & 0x7f);
    uVar8 = (uint32_t)((long)index16K_end - (long)index16K);
    bVar6 = MmControllerPipelineRwRing::canPushAndWriteNElements
                      (&(pPipeline->m_pte16KiBRing).super_MmControllerPipelineRwRing,uVar8);
    if (!bVar6) {
      return (ExecuteResult)0x801000000000000;
    }
    if (pPipeline->m_pRingLock[4] != pipelineCommandId && pPipeline->m_pRingLock[4] != 0x7fff) {
      return (ExecuteResult)0x1001000000000000;
    }
    bVar6 = MmControllerPipelineRwRing::canPushAndWriteNElements
                      (&(pPipeline->m_gpuVmPt1Ring).super_MmControllerPipelineRwRing,
                       (int)((ulong)((long)index16K_end - (long)index16K) >> 2) + 2);
    if (!bVar6) {
      return (ExecuteResult)0x1001000000000000;
    }
    bVar6 = MmControllerPipelineGpuVmPt0Ring::canPushAndWriteNElements
                      (&pPipeline->m_gpuVmPt0Ring,uVar8 + 6);
    if (!bVar6) {
      return (ExecuteResult)0x1401000000000000;
    }
    if ((local_68 & 1) == 0) {
      uVar8 = MmControllerPipeline16KiBPagePresentBitsRing::searchForElement
                        (&pPipeline->m_16KiBpagePresentBitsRing,kWork,i2MiBOffset,
                         stageInfo->m_pRingInfo[1].m_elementIndex,
                         stageInfo->m_pRingInfo[1].m_elementCount);
      local_78.mask_present[0] = 0;
      local_78.mask_present[1] = 0;
      uVar16 = *(uint *)((ulong)(pPipeline->m_16KiBpagePresentBitsRing).
                                super_MmControllerPipelineRwRing.field_0.field_0.m_vaSramMetadata +
                        (ulong)((uVar8 & 0xffff) << 2)) & 0x7fff;
      local_c0 = (ControllerPipelineCommon *)(ulong)uVar16;
      local_88.mask_present[0] =
           pPipeline->m_bigCorePageTableBasePA + (ulong)(uVar16 * 0x1000 + 0x806000) &
           0xffffffffff000 | 0xc0000000000007;
      MmControllerPipelineRwRing::writeElement<unsigned_long>
                (&stageInfo_00->super_MmControllerPipelineRwRing,kWork,uVar12,local_88.mask_present)
      ;
      uVar5 = stageInfo->m_pRingInfo[3].m_elementIndex;
      local_98.pa = pPipeline->m_bigCorePageTableBasePA + (ulong)(uVar16 * 0x100 + 0x54ce000) &
                    0xffffffffffc0 | 0x2000000000000007;
      uVar16 = (pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing.field_0.field_0.
               m_numRingElemsMinus1 + 1;
      uVar12 = (uint)uVar5 +
               (i2MiBOffset -
                *(int *)((ulong)(pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing.
                                field_0.field_0.m_vaSramMetadata + (ulong)uVar5 * 4) & 0xffff);
      uVar2 = 0;
      if ((uVar16 & 0xffff) <= uVar12) {
        uVar2 = uVar16 & 0xffff;
      }
      uVar12 = uVar12 - uVar2;
      MmControllerPipelineRwRing::writeElement<unsigned_long>
                (&(pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing,kWork,
                 uVar12 & 0xffff,&local_98.pa);
      MmControllerPipelineRwRing::markWorkComplete
                (&(pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing,(uint16_t)uVar12);
    }
    else {
      local_c0 = (ControllerPipelineCommon *)
                 (((local_68 & 0xffff000) + 0xf7fa000) - pPipeline->m_bigCorePageTableBasePA >> 0xc)
      ;
      uVar7 = MmControllerPipeline16KiBPagePresentBitsRing::findMostRecent
                        (&pPipeline->m_16KiBpagePresentBitsRing,kWork,(uint16_t)local_c0);
      uVar8 = (uint32_t)uVar7;
      MmControllerPipelineRwRing::readElement<A53::MMC::PT_POOL_ENTRY>
                (&(pPipeline->m_16KiBpagePresentBitsRing).super_MmControllerPipelineRwRing,kWork,
                 (uint)uVar7,&local_78);
    }
    PVar19 = initPtPoolEntry((uint64_t)index16K,(uint64_t)index16K_end);
    if ((local_78.mask_present[1] & PVar19.mask_present[1] |
        local_78.mask_present[0] & PVar19.mask_present[0]) != 0) {
      uVar15 = 0x4d000000000000;
LAB_0600a528:
      return (ExecuteResult)(uVar15 | uVar3 & 0xffffffffffff);
    }
    local_88.mask_present[1] = local_78.mask_present[1] | PVar19.mask_present[1];
    local_88.mask_present[0] = local_78.mask_present[0] | PVar19.mask_present[0];
    MmControllerPipelineRwRing::writeElement<A53::MMC::PT_POOL_ENTRY>
              (&(pPipeline->m_16KiBpagePresentBitsRing).super_MmControllerPipelineRwRing,kWork,uVar8
               ,&local_88);
    MmControllerPipelineRwRing::markWorkComplete
              (&(pPipeline->m_16KiBpagePresentBitsRing).super_MmControllerPipelineRwRing,
               (uint16_t)uVar8);
    if (pInputCommandData->field_4 ==
        (anon_union_8_2_c1c81101_for_PipelineExecutionInputCommandData_4)0xffffffffffffffff) {
      runtime_config_00 = index16K;
      paPageIndex16K = index16K_end;
      PVar20 = MmControllerPipelineSramMetadata::allocate16KiBPaBlock
                         (&pPipeline->m_sramMetadata,pPipeline->m_bigCoreGameBudgetPA,
                          (uint64_t)index16K,(uint64_t)index16K_end,bMulti);
      local_d0 = PVar20.size;
      if (local_d0 != 0) goto LAB_0600a684;
LAB_0600a9d8:
      uVar13 = 0x55000000000000;
    }
    else {
      uVar13 = (uVar3 - pInputCommandData->m_va) + (long)pInputCommandData->field_4 * 0x4000;
      paPageIndex16K = (ControllerRuntimeConfiguration *)(uVar13 >> 0xe & 0x7f);
      runtime_config_00 = (ControllerRuntimeConfiguration *)(uVar13 >> 0x15);
      PVar20 = MmControllerPipelineSramMetadata::allocate16KiBPaBlockDirect
                         (&pPipeline->m_sramMetadata,pPipeline->m_bigCoreGameBudgetPA,
                          (uint16_t)runtime_config_00,(uint64_t)paPageIndex16K,
                          (ulong)((int)paPageIndex16K + ((uint)((int)uVar15 - (int)uVar3) >> 0xe)) &
                          0xffff,bMulti);
      local_d0 = PVar20.size;
LAB_0600a684:
      pCVar11 = (ControllerPipelineCommon *)PVar20.size;
      uVar13 = 0x55000000000000;
      uVar15 = (ulong)index16K >> 2;
      uVar7 = (uint16_t)local_c0;
      local_98 = PVar20;
      if ((uVar3 & 0xc000) != 0) {
        index16K = (ControllerRuntimeConfiguration *)
                   MapPartialPt1(pPipeline,pCVar11,runtime_config_00,(uint16_t)paPageIndex16K,
                                 i2MiBOffset,(uint64_t)index16K,(uint64_t)index16K_end,uVar15,
                                 ptPoolEntry,(PipelineStageInfo *)stageInfo_00,0,
                                 (PA_ALLOC_BLOCK *)stageInfo,SUB81(uVar15,0),
                                 in_stack_fffffffffffffee8,SUB81(local_c0,0));
        if (index16K == (ControllerRuntimeConfiguration *)0xffffffffffffffff) goto LAB_0600a9dc;
        PVar20.size = (uint64_t)pCVar11;
        PVar20.pa = local_98.pa;
        uVar15 = uVar15 + 1;
        local_d0 = local_98.size;
      }
      pCVar11 = (ControllerPipelineCommon *)PVar20.size;
      PVar21.size = local_d0;
      PVar21.pa = PVar20.pa;
      uVar9 = vaAttributeToPte(*(uint *)&pInputCommandData->field_0x10 & 0xfffff);
      uVar10 = vaAttributeToGpuvmPte(*(uint *)&pInputCommandData->field_0x10 & 0xfffff);
      while( true ) {
        local_d0 = PVar21.size;
        uVar13 = 0x55000000000000;
        if ((ulong)index16K_end >> 2 <= uVar15) break;
        if ((local_d0 == 0) &&
           (PVar21 = MmControllerPipelineSramMetadata::allocate16KiBPaBlock
                               (&pPipeline->m_sramMetadata,pPipeline->m_bigCoreGameBudgetPA,
                                (uint64_t)index16K,(uint64_t)index16K_end,bMulti),
           index16K == (ControllerRuntimeConfiguration *)0xffffffffffffffff)) goto LAB_0600a9dc;
        pCVar11 = local_c0;
        if ((((undefined  [16])PVar21 & (undefined  [16])0xffff) == (undefined  [16])0x0) &&
           (PVar21.size >> 0x10 != 0)) {
          paPageIndex16K = (ControllerRuntimeConfiguration *)(PVar21.pa + (uVar10 | 0x200));
          pushAndWriteGpuVmPt1
                    (pPipeline,uVar7,(uint8_t)uVar15,(uint64_t)paPageIndex16K,i2MiBOffset,stageInfo)
          ;
          uVar13 = 0;
          while( true ) {
            uVar18 = PVar21.pa;
            runtime_config_00 =
                 (ControllerRuntimeConfiguration *)((long)&index16K->field_0 + uVar13);
            indexVa16K = runtime_config_00;
            if (3 < uVar13) break;
            paPageIndex16K = (ControllerRuntimeConfiguration *)(uVar9 + uVar18);
            pCVar11 = local_c0;
            pushAndWritePte16KiB
                      (pPipeline,uVar7,(uint8_t)runtime_config_00,(uint64_t)paPageIndex16K,
                       i2MiBOffset,stageInfo);
            if ((bMulti) && (uVar8 = increment16KiBPaPageMultimapCount(0), uVar8 == 0)) {
              uVar13 = 0x65000000000000;
              goto LAB_0600a9dc;
            }
            PVar21.size = PVar21.size - 0x4000;
            PVar21.pa = uVar18 + 0x4000;
            uVar13 = uVar13 + 1;
          }
        }
        else {
          uVar13 = 0;
          while( true ) {
            indexVa16K = (ControllerRuntimeConfiguration *)((long)&index16K->field_0 + uVar13);
            if (3 < uVar13) break;
            if ((PVar21.size == 0) &&
               (PVar21 = MmControllerPipelineSramMetadata::allocate16KiBPaBlock
                                   (&pPipeline->m_sramMetadata,pPipeline->m_bigCoreGameBudgetPA,
                                    (uint64_t)indexVa16K,(uint64_t)index16K_end,bMulti),
               indexVa16K == (ControllerRuntimeConfiguration *)0xffffffffffffffff))
            goto LAB_0600a9d8;
            local_a8 = PVar21.pa;
            pushAndWritePte16KiB
                      (pPipeline,uVar7,(uint8_t)indexVa16K,local_a8 + uVar9,i2MiBOffset,stageInfo);
            pushAndWriteGpuVmPt0
                      (pPipeline,uVar7,(uint8_t)indexVa16K,
                       local_a8 + (uVar10 & 0xfffffffffffff87f | 0x80),i2MiBOffset,stageInfo);
            if ((bMulti) && (uVar8 = increment16KiBPaPageMultimapCount(0), uVar8 == 0)) {
              uVar13 = 0x65000000000000;
              goto LAB_0600a9dc;
            }
            uVar13 = uVar13 + 1;
            PVar21.size = PVar21.size - 0x4000;
            PVar21.pa = local_a8 + 0x4000;
          }
          runtime_config_00 = (ControllerRuntimeConfiguration *)(uVar15 & 0xffffffff);
          paPageIndex16K =
               (ControllerRuntimeConfiguration *)
               (uVar10 & 2 |
                (ulong)((uint)local_c0 & 0xffff) * 0x800 + 0x599a800 + uVar15 * 0x40 +
                pPipeline->m_bigCorePageTableBasePA | 0x900000000000005);
          pushAndWriteGpuVmPt1
                    (pPipeline,uVar7,(uint8_t)runtime_config_00,(uint64_t)paPageIndex16K,i2MiBOffset
                     ,stageInfo);
        }
        uVar15 = uVar15 + 1;
        index16K = indexVa16K;
      }
      local_98 = PVar21;
      if ((index16K_end <= index16K) ||
         (uVar9 = MapPartialPt1(pPipeline,pCVar11,runtime_config_00,(uint16_t)paPageIndex16K,
                                i2MiBOffset,(uint64_t)index16K,(uint64_t)index16K_end,uVar15,
                                ptPoolEntry,(PipelineStageInfo *)stageInfo_00,0,
                                (PA_ALLOC_BLOCK *)stageInfo,PVar21.size,in_stack_fffffffffffffee8,
                                SUB81(local_c0,0)), uVar9 != 0xffffffffffffffff)) goto LAB_0600a388;
    }
LAB_0600a9dc:
    EVar14 = (ExecuteResult)(uVar3 & 0xffffffffffff | uVar13);
  }
  else {
    uVar17 = (uVar3 - pInputCommandData->m_va) + (long)pInputCommandData->field_4 * 0x4000;
    if ((bVar6 || uVar15 < uVar13) || (uVar17 & 0x1fffff) != 0) goto LAB_0600a39c;
    uVar17 = uVar17 >> 0x15;
    uVar16 = (uint)uVar17;
    MmControllerPipelineSramMetadata::allocate2MiBPaPageDirect
              (&pPipeline->m_sramMetadata,(uint16_t)uVar17,bMulti);
LAB_0600a2f8:
    uVar15 = pPipeline->m_bigCoreGameBudgetPA + (ulong)(uVar16 & 0xffff) * 0x200000;
    local_78.mask_present[0] = uVar15 & 0xfffffffe00000 | uVar9;
    MmControllerPipelineRwRing::writeElement<unsigned_long>
              (&stageInfo_00->super_MmControllerPipelineRwRing,kWork,uVar12,local_78.mask_present);
    uVar5 = stageInfo->m_pRingInfo[3].m_elementIndex;
    uVar16 = (pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing.field_0.field_0.
             m_numRingElemsMinus1 + 1;
    uVar12 = (uint)uVar5 +
             (i2MiBOffset -
              *(int *)((ulong)(pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing.field_0.
                              field_0.m_vaSramMetadata + (ulong)uVar5 * 4) & 0xffff);
    uVar2 = 0;
    if ((uVar16 & 0xffff) <= uVar12) {
      uVar2 = uVar16 & 0xffff;
    }
    uVar12 = uVar12 - uVar2;
    local_88.mask_present[0] = uVar15 & 0xffffffffffc0 | uVar10;
    MmControllerPipelineRwRing::writeElement<unsigned_long>
              (&(pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing,kWork,uVar12 & 0xffff,
               local_88.mask_present);
    MmControllerPipelineRwRing::markWorkComplete
              (&(pPipeline->m_gpuVmPde0Ring).super_MmControllerPipelineRwRing,(uint16_t)uVar12);
LAB_0600a388:
    MmControllerPipelineRwRing::markWorkComplete
              (&stageInfo_00->super_MmControllerPipelineRwRing,(uint16_t)uVar1);
    EVar14 = (ExecuteResult)0x0;
  }
  return EVar14;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600aa50
 * symbol: writeElement<unsigned_long>
 * prototype: uint32_t writeElement<unsigned_long>(MmControllerPipelineRwRing * this, Section section, uint32_t ringLocation, ulong * elem)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: writeElement<unsigned long>
   DWARF original prototype: uint32_t writeElement<unsigned_long>(MmControllerPipelineRwRing * this,
   Section section, uint32_t ringLocation, ulong * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::writeElement<unsigned_long>
          (MmControllerPipelineRwRing *this,Section section,uint32_t ringLocation,ulong *elem)

{
  uint16_t uVar1;
  uint32_t uVar2;
  
  uVar1 = getIndexFromHeadFromRingLocation(this,(uint16_t)ringLocation);
  if ((*(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0xe) <= uVar1) &&
     (uVar1 < *(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0x14))) {
    uVar2 = writeElement<unsigned_long>(this,ringLocation,elem);
    return uVar2;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600aad0
 * symbol: markWorkComplete
 * prototype: void markWorkComplete(MmControllerPipelineRwRing * this, uint16_t elementIndex)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void markWorkComplete(MmControllerPipelineRwRing * this, uint16_t
   elementIndex) */

void __thiscall
A53::MmControllerPipelineRwRing::markWorkComplete
          (MmControllerPipelineRwRing *this,uint16_t elementIndex)

{
  setStateBit(this,kNeedWork,elementIndex,false);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600aae4
 * symbol: canPushAndWriteNElements
 * prototype: bool canPushAndWriteNElements(MmControllerPipelineGpuVmPt0Ring * this, uint32_t numElems)
 * body addresses: 204
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool canPushAndWriteNElements(MmControllerPipelineGpuVmPt0Ring * this,
   uint32_t numElems) */

bool __thiscall
A53::MmControllerPipelineGpuVmPt0Ring::canPushAndWriteNElements
          (MmControllerPipelineGpuVmPt0Ring *this,uint32_t numElems)

{
  uint uVar1;
  ushort uVar2;
  bool bVar3;
  uint16_t uVar4;
  uint16_t uVar5;
  
  if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_numRingElemsMinus1 + 1 <
      ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_count + numElems) -
      (uint)(this->super_MmControllerPipelineRwRing).field_0.field_0.m_pHeadCount[0]) {
LAB_0600ab98:
    bVar3 = false;
  }
  else {
    uVar4 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing)
    ;
    if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_pTailCount[0] !=
        (this->super_MmControllerPipelineRwRing).field_0.field_0.m_pHeadCount[0]) {
      uVar2 = *(ushort *)((long)&(this->super_MmControllerPipelineRwRing).field_0 + 10);
      uVar5 = MmControllerPipelineRwRing::getElementIndexBackwardFromTail
                        (&this->super_MmControllerPipelineRwRing,kOdma,1);
      uVar1 = (uint)uVar4 << (uVar2 & 0xf) & 0xffffffc0;
      if ((uVar1 == ((uint)uVar5 <<
                     (*(ushort *)((long)&(this->super_MmControllerPipelineRwRing).field_0 + 10) &
                     0xf) & 0xffffffc0)) ||
         (uVar4 = MmControllerPipelineRwRing::getElementIndexFromHead
                            (&this->super_MmControllerPipelineRwRing,kOdma,0),
         uVar1 == ((uint)uVar4 <<
                   (*(ushort *)((long)&(this->super_MmControllerPipelineRwRing).field_0 + 10) & 0xf)
                  & 0xffffffc0))) goto LAB_0600ab98;
    }
    bVar3 = true;
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600abb0
 * symbol: readElement<A53::MMC::PT_POOL_ENTRY>
 * prototype: uint32_t readElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, Section section, uint32_t ringLocation, PT_POOL_ENTRY * elem)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   readElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, Section section, uint32_t
   ringLocation, PT_POOL_ENTRY * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::readElement<A53::MMC::PT_POOL_ENTRY>
          (MmControllerPipelineRwRing *this,Section section,uint32_t ringLocation,
          PT_POOL_ENTRY *elem)

{
  uint16_t uVar1;
  uint32_t uVar2;
  
  uVar1 = getIndexFromHeadFromRingLocation(this,(uint16_t)ringLocation);
  if ((*(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0xe) <= uVar1) &&
     (uVar1 < *(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0x14))) {
    uVar2 = readElement<A53::MMC::PT_POOL_ENTRY>(this,ringLocation,elem);
    return uVar2;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600ac78
 * symbol: writeElement<A53::MMC::PT_POOL_ENTRY>
 * prototype: uint32_t writeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, Section section, uint32_t ringLocation, PT_POOL_ENTRY * elem)
 * body addresses: 128
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   writeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, Section section,
   uint32_t ringLocation, PT_POOL_ENTRY * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::writeElement<A53::MMC::PT_POOL_ENTRY>
          (MmControllerPipelineRwRing *this,Section section,uint32_t ringLocation,
          PT_POOL_ENTRY *elem)

{
  uint16_t uVar1;
  uint32_t uVar2;
  
  uVar1 = getIndexFromHeadFromRingLocation(this,(uint16_t)ringLocation);
  if ((*(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0xe) <= uVar1) &&
     (uVar1 < *(ushort *)((long)&this->field_0 + (ulong)section * 2 + 0x14))) {
    uVar2 = writeElement<A53::MMC::PT_POOL_ENTRY>(this,ringLocation,elem);
    return uVar2;
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600acf8
 * symbol: MapPartialPt1
 * prototype: uint64_t MapPartialPt1(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, uint32_t i2MiBOffset, uint64_t indexVa16K, uint64_t indexVa16K_end, uint64_t indexVaPt1, PT_POOL_ENTRY * ptPoolEntry, PipelineStageInfo * stageInfo, uint16_t ptPoolIndex, PA_ALLOC_BLOCK * alloc, bool bIsInMultimapAperture, uint32_t attr, bool bClearPrefixPt0)
 * body addresses: 612
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint64_t A53::MMC::MmPipelineApp::MapPartialPt1
                   (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
                   ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
                   uint32_t i2MiBOffset,uint64_t indexVa16K,uint64_t indexVa16K_end,
                   uint64_t indexVaPt1,PT_POOL_ENTRY *ptPoolEntry,PipelineStageInfo *stageInfo,
                   uint16_t ptPoolIndex,PA_ALLOC_BLOCK *alloc,bool bIsInMultimapAperture,
                   uint32_t attr,bool bClearPrefixPt0)

{
  ulong uVar1;
  ulong uVar2;
  bool bVar3;
  uint64_t uVar4;
  uint64_t uVar5;
  uint64_t uVar6;
  ulong uVar7;
  PT_POOL_ENTRY PVar8;
  PA_ALLOC_BLOCK PVar9;
  ulong *in_stack_00000000;
  PipelineStageInfo *in_stack_00000008;
  uint16_t in_stack_00000010;
  PA_ALLOC_BLOCK *in_stack_00000018;
  byte in_stack_00000020;
  uint32_t in_stack_00000028;
  byte in_stack_00000030;
  
  uVar4 = vaAttributeToPte(in_stack_00000028);
  vaAttributeToGpuvmPde(in_stack_00000028);
  uVar5 = vaAttributeToGpuvmPte(in_stack_00000028);
  PVar8 = initPtPoolEntry(indexVa16K & 0xfffffffffffffffc,(indexVa16K & 0xfffffffffffffffc) + 4);
  if ((PVar8.mask_present[0] & *in_stack_00000000) == 0) {
    bVar3 = (in_stack_00000000[1] & PVar8.mask_present[1]) != 0;
  }
  else {
    bVar3 = true;
  }
  uVar1 = indexVaPt1 * 8 + 8;
  uVar7 = indexVa16K_end * 2;
  uVar2 = uVar1;
  if (uVar7 < uVar1 || uVar7 - uVar1 == 0) {
    uVar2 = uVar7;
  }
  if (!bVar3) {
    if ((in_stack_00000030 & 1) != 0) {
      for (uVar7 = (indexVaPt1 & 0x1fffffffffffffff) << 2; uVar7 < indexVa16K; uVar7 = uVar7 + 1) {
        pushAndWriteGpuVmPt0
                  (pPipeline,in_stack_00000010,(uint8_t)uVar7,0,i2MiBOffset,in_stack_00000008);
      }
    }
    for (uVar7 = uVar2 >> 1; uVar7 < uVar1 >> 1; uVar7 = uVar7 + 1) {
      pushAndWriteGpuVmPt0
                (pPipeline,in_stack_00000010,(uint8_t)uVar7,0,i2MiBOffset,in_stack_00000008);
    }
    pushAndWriteGpuVmPt1
              (pPipeline,in_stack_00000010,(uint8_t)indexVaPt1,
               uVar5 & 2 |
               indexVaPt1 * 0x40 + (ulong)in_stack_00000010 * 0x800 +
               pPipeline->m_bigCorePageTableBasePA + 0x599a800 | 0x900000000000005,i2MiBOffset,
               in_stack_00000008);
  }
  do {
    if (uVar2 >> 1 <= indexVa16K) {
      return indexVa16K;
    }
    if (in_stack_00000018->size == 0) {
      PVar9 = MmControllerPipelineSramMetadata::allocate16KiBPaBlock
                        (&pPipeline->m_sramMetadata,pPipeline->m_bigCoreGameBudgetPA,indexVa16K,
                         indexVa16K_end,(bool)(in_stack_00000020 & 1));
      uVar6 = PVar9.pa;
      *in_stack_00000018 = PVar9;
      if (PVar9.size == 0) {
        return 0xffffffffffffffff;
      }
    }
    else {
      uVar6 = in_stack_00000018->pa;
    }
    pushAndWritePte16KiB
              (pPipeline,in_stack_00000010,(uint8_t)indexVa16K,uVar6 + uVar4,i2MiBOffset,
               in_stack_00000008);
    pushAndWriteGpuVmPt0
              (pPipeline,in_stack_00000010,(uint8_t)indexVa16K,
               in_stack_00000018->pa + (uVar5 & 0xfffffffffffff87f | 0x80),i2MiBOffset,
               in_stack_00000008);
    if ((in_stack_00000020 & 1) != 0) {
      increment16KiBPaPageMultimapCount(0);
    }
    indexVa16K = indexVa16K + 1;
    in_stack_00000018->pa = in_stack_00000018->pa + 0x4000;
    in_stack_00000018->size = in_stack_00000018->size - 0x4000;
  } while( true );
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600afb8
 * symbol: pushAndWriteGpuVmPt1
 * prototype: void pushAndWriteGpuVmPt1(MmPipelineApp * this, uint16_t ptIndex, uint8_t gpuVmPt1Index, uint64_t pt1Entry, uint32_t i2MiBOffset, PipelineStageInfo * stageInfo)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushAndWriteGpuVmPt1(MmPipelineApp * this, uint16_t ptIndex,
   uint8_t gpuVmPt1Index, uint64_t pt1Entry, uint32_t i2MiBOffset, PipelineStageInfo * stageInfo) */

void __thiscall
A53::MMC::MmPipelineApp::pushAndWriteGpuVmPt1
          (MmPipelineApp *this,uint16_t ptIndex,uint8_t gpuVmPt1Index,uint64_t pt1Entry,
          uint32_t i2MiBOffset,PipelineStageInfo *stageInfo)

{
  MmControllerPipelineGpuVmPt1Ring *this_00;
  uint16_t elementIndex;
  
  this_00 = &this->m_gpuVmPt1Ring;
  elementIndex = MmControllerPipelineRwRing::getElementIndexTail
                           (&this_00->super_MmControllerPipelineRwRing);
  MmControllerPipelineGpuVmPt1Ring::pushAndWriteElement
            (this_00,ptIndex,gpuVmPt1Index,i2MiBOffset,pt1Entry);
  if (stageInfo->m_pRingInfo[4].m_elementIndex == 0xffff) {
    stageInfo->m_pRingInfo[4].m_elementIndex = elementIndex;
  }
  stageInfo->m_pRingInfo[4].m_elementCount = stageInfo->m_pRingInfo[4].m_elementCount + 1;
  MmControllerPipelineRwRing::markWorkComplete
            (&this_00->super_MmControllerPipelineRwRing,elementIndex);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b048
 * symbol: pushAndWritePte16KiB
 * prototype: void pushAndWritePte16KiB(MmPipelineApp * this, uint16_t ptIndex, uint8_t pte16KiBIndex, uint64_t pteStartEntry, uint32_t i2MiBOffset, PipelineStageInfo * stageInfo)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushAndWritePte16KiB(MmPipelineApp * this, uint16_t ptIndex,
   uint8_t pte16KiBIndex, uint64_t pteStartEntry, uint32_t i2MiBOffset, PipelineStageInfo *
   stageInfo) */

void __thiscall
A53::MMC::MmPipelineApp::pushAndWritePte16KiB
          (MmPipelineApp *this,uint16_t ptIndex,uint8_t pte16KiBIndex,uint64_t pteStartEntry,
          uint32_t i2MiBOffset,PipelineStageInfo *stageInfo)

{
  MmControllerPipelinePte16KiBRing *this_00;
  uint16_t elementIndex;
  
  this_00 = &this->m_pte16KiBRing;
  elementIndex = MmControllerPipelineRwRing::getElementIndexTail
                           (&this_00->super_MmControllerPipelineRwRing);
  MmControllerPipelinePte16KiBRing::pushAndWriteElement
            (this_00,ptIndex,pte16KiBIndex,i2MiBOffset,pteStartEntry);
  if (stageInfo->m_pRingInfo[2].m_elementIndex == 0xffff) {
    stageInfo->m_pRingInfo[2].m_elementIndex = elementIndex;
  }
  stageInfo->m_pRingInfo[2].m_elementCount = stageInfo->m_pRingInfo[2].m_elementCount + 1;
  MmControllerPipelineRwRing::markWorkComplete
            (&this_00->super_MmControllerPipelineRwRing,elementIndex);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b0d8
 * symbol: pushAndWriteGpuVmPt0
 * prototype: void pushAndWriteGpuVmPt0(MmPipelineApp * this, uint16_t ptIndex, uint8_t gpuVmPt016KiBIndex, uint64_t pt0Entry, uint32_t i2MiBOffset, PipelineStageInfo * stageInfo)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushAndWriteGpuVmPt0(MmPipelineApp * this, uint16_t ptIndex,
   uint8_t gpuVmPt016KiBIndex, uint64_t pt0Entry, uint32_t i2MiBOffset, PipelineStageInfo *
   stageInfo) */

void __thiscall
A53::MMC::MmPipelineApp::pushAndWriteGpuVmPt0
          (MmPipelineApp *this,uint16_t ptIndex,uint8_t gpuVmPt016KiBIndex,uint64_t pt0Entry,
          uint32_t i2MiBOffset,PipelineStageInfo *stageInfo)

{
  MmControllerPipelineGpuVmPt0Ring *this_00;
  uint16_t elementIndex;
  
  this_00 = &this->m_gpuVmPt0Ring;
  elementIndex = MmControllerPipelineRwRing::getElementIndexTail
                           (&this_00->super_MmControllerPipelineRwRing);
  MmControllerPipelineGpuVmPt0Ring::pushAndWriteElement
            (this_00,ptIndex,gpuVmPt016KiBIndex,i2MiBOffset,pt0Entry);
  if (stageInfo->m_pRingInfo[5].m_elementIndex == 0xffff) {
    stageInfo->m_pRingInfo[5].m_elementIndex = elementIndex;
  }
  stageInfo->m_pRingInfo[5].m_elementCount = stageInfo->m_pRingInfo[5].m_elementCount + 1;
  MmControllerPipelineRwRing::markWorkComplete
            (&this_00->super_MmControllerPipelineRwRing,elementIndex);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b168
 * symbol: executeDvmStage_Map
 * prototype: ExecuteResult executeDvmStage_Map(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, uint16_t pipelineCommandId, PipelineStageInfo * stageInfo, PipelineExecutionInputCommandData * pInputCommandData, uint32_t i2MiBOffset, bool bCurTransferLast2MiBChunk)
 * body addresses: 144
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::executeDvmStage_Map
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,uint16_t pipelineCommandId,
          PipelineStageInfo *stageInfo,PipelineExecutionInputCommandData *pInputCommandData,
          uint32_t i2MiBOffset,bool bCurTransferLast2MiBChunk)

{
  ExecuteResult EVar1;
  
  if (((*(uint *)&stageInfo->field_0x4 ^ *(uint *)&stageInfo->field_0x8) & 0xfffff) == 0) {
    if ((int)((pInputCommandData->m_va + pInputCommandData->m_vaSize + 0x1fffff) -
              pPipeline->m_bigCoreMapperManagedVA >> 0x15) - 1U == i2MiBOffset) {
      EVar1 = submitDvmTlbi(controller_pipeline,pipelineCommandId,pInputCommandData->m_va,
                            pInputCommandData->m_vaSize);
      if (((ulong)EVar1 & 0x7000000000000) == 0) {
        *(uint *)&stageInfo->field_0x8 =
             *(uint *)&stageInfo->field_0x8 & 0xfff00000 | i2MiBOffset + 1 & 0xfffff;
      }
    }
    else {
      EVar1 = (ExecuteResult)0x0;
    }
  }
  else {
    EVar1 = (ExecuteResult)0x3000000000000;
  }
  return EVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b1f8
 * symbol: postexecutePtPresentAndGpuVmPde0Stage_Map
 * prototype: ExecuteResult postexecutePtPresentAndGpuVmPde0Stage_Map(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, PipelineStageInfo * stageInfo, uint16_t pipelineCommandId)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::postexecutePtPresentAndGpuVmPde0Stage_Map
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,PipelineStageInfo *stageInfo,
          uint16_t pipelineCommandId)

{
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b200
 * symbol: postexecutePteAndGpuVmPtStageStage_Map
 * prototype: ExecuteResult postexecutePteAndGpuVmPtStageStage_Map(MmPipelineApp * pPipeline, ControllerPipelineCommon * controller_pipeline, ControllerRuntimeConfiguration * runtime_config, PipelineStageInfo * stageInfo, uint16_t pipelineCommandId)
 * body addresses: 8
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

ExecuteResult
A53::MMC::MmPipelineApp::postexecutePteAndGpuVmPtStageStage_Map
          (MmPipelineApp *pPipeline,ControllerPipelineCommon *controller_pipeline,
          ControllerRuntimeConfiguration *runtime_config,PipelineStageInfo *stageInfo,
          uint16_t pipelineCommandId)

{
  return (ExecuteResult)0x0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b208
 * symbol: setStateBit
 * prototype: void setStateBit(MmControllerPipelineRwRing * this, StateBitArray state, uint16_t elementIndex, bool bEnable)
 * body addresses: 64
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setStateBit(MmControllerPipelineRwRing * this, StateBitArray
   state, uint16_t elementIndex, bool bEnable) */

void __thiscall
A53::MmControllerPipelineRwRing::setStateBit
          (MmControllerPipelineRwRing *this,StateBitArray state,uint16_t elementIndex,bool bEnable)

{
  byte bVar1;
  byte bVar2;
  byte *pbVar3;
  
  pbVar3 = (byte *)(ulong)((this->field_0).field_0.m_vaSramMetadata + (uint)(elementIndex >> 3) +
                          (uint)*(ushort *)((long)&this->field_0 + (ulong)state * 2 + 0x1e));
  bVar1 = (byte)(1 << (ulong)(elementIndex & 7));
  bVar2 = bVar1 ^ 0xff;
  if (!bEnable) {
    bVar1 = 0;
  }
  *pbVar3 = *pbVar3 & bVar2 | bVar1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b248
 * symbol: canPushAndWriteNElements
 * prototype: bool canPushAndWriteNElements(MmControllerPipelineRwRing * this, uint32_t numElems)
 * body addresses: 180
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool canPushAndWriteNElements(MmControllerPipelineRwRing * this,
   uint32_t numElems) */

bool __thiscall
A53::MmControllerPipelineRwRing::canPushAndWriteNElements
          (MmControllerPipelineRwRing *this,uint32_t numElems)

{
  uint uVar1;
  ushort uVar2;
  bool bVar3;
  uint16_t uVar4;
  uint16_t uVar5;
  
  bVar3 = canPushNElements(this,numElems);
  if (bVar3) {
    uVar4 = getElementIndexTail(this);
    if ((this->field_0).field_0.m_pTailCount[2] != (this->field_0).field_0.m_pHeadCount[2]) {
      uVar2 = *(ushort *)((long)&this->field_0 + 10);
      uVar5 = getElementIndexBackwardFromTail(this,kIdma,1);
      uVar1 = (uint)uVar4 << (uVar2 & 0xf) & 0xffffffc0;
      if ((uVar1 == ((uint)uVar5 << (*(ushort *)((long)&this->field_0 + 10) & 0xf) & 0xffffffc0)) ||
         (uVar4 = getElementIndexFromHead(this,kIdma,0),
         uVar1 == ((uint)uVar4 << (*(ushort *)((long)&this->field_0 + 10) & 0xf) & 0xffffffc0)))
      goto LAB_0600b2e4;
    }
    bVar3 = true;
  }
  else {
LAB_0600b2e4:
    bVar3 = false;
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b2fc
 * symbol: pushAndWriteElement
 * prototype: void pushAndWriteElement(MmControllerPipelineGpuVmPt1Ring * this, uint16_t ptIndex, uint8_t gpuVmPt1Index, uint32_t i2MiBOffset, uint64_t pt1Entry)
 * body addresses: 200
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushAndWriteElement(MmControllerPipelineGpuVmPt1Ring * this,
   uint16_t ptIndex, uint8_t gpuVmPt1Index, uint32_t i2MiBOffset, uint64_t pt1Entry) */

void __thiscall
A53::MmControllerPipelineGpuVmPt1Ring::pushAndWriteElement
          (MmControllerPipelineGpuVmPt1Ring *this,uint16_t ptIndex,uint8_t gpuVmPt1Index,
          uint32_t i2MiBOffset,uint64_t pt1Entry)

{
  uint16_t uVar1;
  uint64_t local_38;
  
  local_38 = pt1Entry;
  if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_numRingElemsMinus1 + 1 ==
      (uint)(this->super_MmControllerPipelineRwRing).field_0.field_0.m_count) {
    MmControllerPipelineRwRing::popElements(&this->super_MmControllerPipelineRwRing,1);
  }
  uVar1 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing);
  (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count =
       (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count + 1;
  MmControllerPipelineRwRing::writeElement<unsigned_long>
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,&local_38);
  MmControllerPipelineRwRing::setupMetadata
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,(UidMetadata)i2MiBOffset,
             i2MiBOffset,false,false);
  DC_CIVAC((ulong)(((uint)uVar1 <<
                   (*(ushort *)((long)&(this->super_MmControllerPipelineRwRing).field_0 + 10) & 0xf)
                   ) + (this->super_MmControllerPipelineRwRing).field_0.field_0.m_vaSramRing &
                  0xffffffc0));
  UnkSytemRegWrite(0,3,3,0xd,4,0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b3c4
 * symbol: writeElement<unsigned_long>
 * prototype: uint32_t writeElement<unsigned_long>(MmControllerPipelineRwRing * this, uint32_t ringLocation, ulong * elem)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: writeElement<unsigned long>
   DWARF original prototype: uint32_t writeElement<unsigned_long>(MmControllerPipelineRwRing * this,
   uint32_t ringLocation, ulong * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::writeElement<unsigned_long>
          (MmControllerPipelineRwRing *this,uint32_t ringLocation,ulong *elem)

{
  uint uVar1;
  ushort uVar2;
  uint32_t uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  if (ringLocation < uVar1) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = 0;
    if (uVar2 <= ringLocation) {
      uVar1 = 0;
    }
    if ((ringLocation - uVar2) + uVar1 < (uint)(this->field_0).field_0.m_count) {
      uVar3 = 1;
      *(ulong *)((ulong)(this->field_0).field_0.m_vaSramRing +
                (ulong)(ringLocation << (*(ushort *)((long)&this->field_0 + 10) & 0xf))) = *elem;
    }
  }
  else {
    uVar3 = 0;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b428
 * symbol: pushAndWriteElement
 * prototype: void pushAndWriteElement(MmControllerPipelinePte16KiBRing * this, uint16_t ptIndex, uint8_t pte16KiBIndex, uint32_t i2MiBOffset, uint64_t pteStartEntry)
 * body addresses: 248
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushAndWriteElement(MmControllerPipelinePte16KiBRing * this,
   uint16_t ptIndex, uint8_t pte16KiBIndex, uint32_t i2MiBOffset, uint64_t pteStartEntry) */

void __thiscall
A53::MmControllerPipelinePte16KiBRing::pushAndWriteElement
          (MmControllerPipelinePte16KiBRing *this,uint16_t ptIndex,uint8_t pte16KiBIndex,
          uint32_t i2MiBOffset,uint64_t pteStartEntry)

{
  uint16_t uVar1;
  ElementData local_60;
  
  if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_numRingElemsMinus1 + 1 ==
      (uint)(this->super_MmControllerPipelineRwRing).field_0.field_0.m_count) {
    MmControllerPipelineRwRing::popElements(&this->super_MmControllerPipelineRwRing,1);
  }
  if (pteStartEntry == 0) {
    A53_MEMSET_ZERO((uint64_t)&local_60,0x20);
  }
  else {
    local_60.m_pte[1] = pteStartEntry + 0x1000;
    local_60.m_pte[2] = pteStartEntry + 0x2000;
    local_60.m_pte[3] = pteStartEntry + 0x3000;
    local_60.m_pte[0] = pteStartEntry;
  }
  uVar1 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing);
  (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count =
       (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count + 1;
  MmControllerPipelineRwRing::writeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,&local_60);
  MmControllerPipelineRwRing::setupMetadata
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,(UidMetadata)i2MiBOffset,
             i2MiBOffset,false,false);
  DC_CIVAC((ulong)(((uint)uVar1 <<
                   (*(ushort *)((long)&(this->super_MmControllerPipelineRwRing).field_0 + 10) & 0xf)
                   ) + (this->super_MmControllerPipelineRwRing).field_0.field_0.m_vaSramRing &
                  0xffffffc0));
  UnkSytemRegWrite(0,3,3,0xd,4,0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b520
 * symbol: writeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>
 * prototype: uint32_t writeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(MmControllerPipelineRwRing * this, uint32_t ringLocation, ElementData * elem)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   writeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t ringLocation, ElementData * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::writeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>
          (MmControllerPipelineRwRing *this,uint32_t ringLocation,ElementData *elem)

{
  uint uVar1;
  ushort uVar2;
  uint32_t uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  if (ringLocation < uVar1) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = 0;
    if (uVar2 <= ringLocation) {
      uVar1 = 0;
    }
    if ((ringLocation - uVar2) + uVar1 < (uint)(this->field_0).field_0.m_count) {
      storeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(this,ringLocation,elem);
      uVar3 = 1;
    }
  }
  else {
    uVar3 = 0;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b57c
 * symbol: storeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>
 * prototype: void storeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(MmControllerPipelineRwRing * this, uint32_t iRingElem, ElementData * elem)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void
   storeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, ElementData * elem) */

void __thiscall
A53::MmControllerPipelineRwRing::storeElement<A53::MmControllerPipelinePte16KiBRing::ElementData>
          (MmControllerPipelineRwRing *this,uint32_t iRingElem,ElementData *elem)

{
  uint64_t *puVar1;
  uint64_t uVar2;
  uint64_t uVar3;
  uint64_t uVar4;
  uint64_t *pDst;
  
  pDst = (uint64_t *)(ulong)*(ushort *)((long)&this->field_0 + 10);
  uVar3 = elem->m_pte[1];
  puVar1 = (uint64_t *)
           ((ulong)(iRingElem << ((ulong)pDst & 0xf)) + (ulong)(this->field_0).field_0.m_vaSramRing)
  ;
  uVar2 = elem->m_pte[2];
  uVar4 = elem->m_pte[3];
  *puVar1 = elem->m_pte[0];
  puVar1[1] = uVar3;
  puVar1[2] = uVar2;
  puVar1[3] = uVar4;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b5a4
 * symbol: pushAndWriteElement
 * prototype: void pushAndWriteElement(MmControllerPipelineGpuVmPt0Ring * this, uint16_t ptIndex, uint8_t gpuVmPt016KiBIndex, uint32_t i2MiBOffset, uint64_t gpuVmPt0StartEntry)
 * body addresses: 236
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushAndWriteElement(MmControllerPipelineGpuVmPt0Ring * this,
   uint16_t ptIndex, uint8_t gpuVmPt016KiBIndex, uint32_t i2MiBOffset, uint64_t gpuVmPt0StartEntry)
    */

void __thiscall
A53::MmControllerPipelineGpuVmPt0Ring::pushAndWriteElement
          (MmControllerPipelineGpuVmPt0Ring *this,uint16_t ptIndex,uint8_t gpuVmPt016KiBIndex,
          uint32_t i2MiBOffset,uint64_t gpuVmPt0StartEntry)

{
  uint16_t uVar1;
  ElementData local_50;
  
  if ((this->super_MmControllerPipelineRwRing).field_0.field_0.m_numRingElemsMinus1 + 1 ==
      (uint)(this->super_MmControllerPipelineRwRing).field_0.field_0.m_count) {
    MmControllerPipelineRwRing::popElements(&this->super_MmControllerPipelineRwRing,1);
  }
  if (gpuVmPt0StartEntry == 0) {
    A53_MEMSET_ZERO((uint64_t)&local_50,0x10);
  }
  else {
    local_50.m_gpuVmPt0[1] = gpuVmPt0StartEntry + 0x2000;
    local_50.m_gpuVmPt0[0] = gpuVmPt0StartEntry;
  }
  uVar1 = MmControllerPipelineRwRing::getElementIndexTail(&this->super_MmControllerPipelineRwRing);
  (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count =
       (this->super_MmControllerPipelineRwRing).field_0.field_0.m_count + 1;
  MmControllerPipelineRwRing::writeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,&local_50);
  MmControllerPipelineRwRing::setupMetadata
            (&this->super_MmControllerPipelineRwRing,(uint)uVar1,(UidMetadata)i2MiBOffset,
             i2MiBOffset,false,false);
  DC_CIVAC((ulong)(((uint)uVar1 <<
                   (*(ushort *)((long)&(this->super_MmControllerPipelineRwRing).field_0 + 10) & 0xf)
                   ) + (this->super_MmControllerPipelineRwRing).field_0.field_0.m_vaSramRing &
                  0xffffffc0));
  UnkSytemRegWrite(0,3,3,0xd,4,0);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b690
 * symbol: writeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>
 * prototype: uint32_t writeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(MmControllerPipelineRwRing * this, uint32_t ringLocation, ElementData * elem)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   writeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t ringLocation, ElementData * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::writeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>
          (MmControllerPipelineRwRing *this,uint32_t ringLocation,ElementData *elem)

{
  uint uVar1;
  ushort uVar2;
  uint32_t uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  if (ringLocation < uVar1) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = 0;
    if (uVar2 <= ringLocation) {
      uVar1 = 0;
    }
    if ((ringLocation - uVar2) + uVar1 < (uint)(this->field_0).field_0.m_count) {
      storeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(this,ringLocation,elem);
      uVar3 = 1;
    }
  }
  else {
    uVar3 = 0;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b6ec
 * symbol: storeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>
 * prototype: void storeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(MmControllerPipelineRwRing * this, uint32_t iRingElem, ElementData * elem)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void
   storeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, ElementData * elem) */

void __thiscall
A53::MmControllerPipelineRwRing::storeElement<A53::MmControllerPipelineGpuVmPt0Ring::ElementData>
          (MmControllerPipelineRwRing *this,uint32_t iRingElem,ElementData *elem)

{
  uint64_t *puVar1;
  uint64_t uVar2;
  uint64_t *pDst;
  
  pDst = (uint64_t *)(ulong)*(ushort *)((long)&this->field_0 + 10);
  uVar2 = elem->m_gpuVmPt0[1];
  puVar1 = (uint64_t *)
           ((ulong)(iRingElem << ((ulong)pDst & 0xf)) + (ulong)(this->field_0).field_0.m_vaSramRing)
  ;
  *puVar1 = elem->m_gpuVmPt0[0];
  puVar1[1] = uVar2;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b70c
 * symbol: readElement<unsigned_long>
 * prototype: uint32_t readElement<unsigned_long>(MmControllerPipelineRwRing * this, uint32_t ringLocation, ulong * elem)
 * body addresses: 100
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original name: readElement<unsigned long>
   DWARF original prototype: uint32_t readElement<unsigned_long>(MmControllerPipelineRwRing * this,
   uint32_t ringLocation, ulong * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::readElement<unsigned_long>
          (MmControllerPipelineRwRing *this,uint32_t ringLocation,ulong *elem)

{
  uint uVar1;
  ushort uVar2;
  uint32_t uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  if (ringLocation < uVar1) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = 0;
    if (uVar2 <= ringLocation) {
      uVar1 = 0;
    }
    if ((ringLocation - uVar2) + uVar1 < (uint)(this->field_0).field_0.m_count) {
      uVar3 = 1;
      *elem = *(ulong *)((ulong)(this->field_0).field_0.m_vaSramRing +
                        (ulong)(ringLocation << (*(ushort *)((long)&this->field_0 + 10) & 0xf)));
    }
  }
  else {
    uVar3 = 0;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b770
 * symbol: readElement<A53::MMC::PT_POOL_ENTRY>
 * prototype: uint32_t readElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t ringLocation, PT_POOL_ENTRY * elem)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   readElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t ringLocation,
   PT_POOL_ENTRY * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::readElement<A53::MMC::PT_POOL_ENTRY>
          (MmControllerPipelineRwRing *this,uint32_t ringLocation,PT_POOL_ENTRY *elem)

{
  uint uVar1;
  ushort uVar2;
  uint32_t uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  if (ringLocation < uVar1) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = 0;
    if (uVar2 <= ringLocation) {
      uVar1 = 0;
    }
    if ((ringLocation - uVar2) + uVar1 < (uint)(this->field_0).field_0.m_count) {
      loadElement<A53::MMC::PT_POOL_ENTRY>(this,ringLocation,elem);
      uVar3 = 1;
    }
  }
  else {
    uVar3 = 0;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b7cc
 * symbol: loadElement<A53::MMC::PT_POOL_ENTRY>
 * prototype: void loadElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t iRingElem, PT_POOL_ENTRY * elem)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void loadElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, PT_POOL_ENTRY * elem) */

void __thiscall
A53::MmControllerPipelineRwRing::loadElement<A53::MMC::PT_POOL_ENTRY>
          (MmControllerPipelineRwRing *this,uint32_t iRingElem,PT_POOL_ENTRY *elem)

{
  uint64_t *puVar1;
  uint64_t uVar2;
  
  puVar1 = (uint64_t *)
           ((ulong)(iRingElem << (*(ushort *)((long)&this->field_0 + 10) & 0xf)) +
           (ulong)(this->field_0).field_0.m_vaSramRing);
  uVar2 = puVar1[1];
  elem->mask_present[0] = *puVar1;
  elem->mask_present[1] = uVar2;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b7ec
 * symbol: writeElement<A53::MMC::PT_POOL_ENTRY>
 * prototype: uint32_t writeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t ringLocation, PT_POOL_ENTRY * elem)
 * body addresses: 92
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   writeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t ringLocation,
   PT_POOL_ENTRY * elem) */

uint32_t __thiscall
A53::MmControllerPipelineRwRing::writeElement<A53::MMC::PT_POOL_ENTRY>
          (MmControllerPipelineRwRing *this,uint32_t ringLocation,PT_POOL_ENTRY *elem)

{
  uint uVar1;
  ushort uVar2;
  uint32_t uVar3;
  
  uVar1 = (this->field_0).field_0.m_numRingElemsMinus1 + 1 & 0xffff;
  if (ringLocation < uVar1) {
    uVar2 = (this->field_0).field_0.m_head;
    uVar3 = 0;
    if (uVar2 <= ringLocation) {
      uVar1 = 0;
    }
    if ((ringLocation - uVar2) + uVar1 < (uint)(this->field_0).field_0.m_count) {
      storeElement<A53::MMC::PT_POOL_ENTRY>(this,ringLocation,elem);
      uVar3 = 1;
    }
  }
  else {
    uVar3 = 0;
  }
  return uVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b848
 * symbol: storeElement<A53::MMC::PT_POOL_ENTRY>
 * prototype: void storeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing * this, uint32_t iRingElem, PT_POOL_ENTRY * elem)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void storeElement<A53::MMC::PT_POOL_ENTRY>(MmControllerPipelineRwRing *
   this, uint32_t iRingElem, PT_POOL_ENTRY * elem) */

void __thiscall
A53::MmControllerPipelineRwRing::storeElement<A53::MMC::PT_POOL_ENTRY>
          (MmControllerPipelineRwRing *this,uint32_t iRingElem,PT_POOL_ENTRY *elem)

{
  uint64_t *puVar1;
  uint64_t uVar2;
  uint64_t *pDst;
  
  pDst = (uint64_t *)(ulong)*(ushort *)((long)&this->field_0 + 10);
  uVar2 = elem->mask_present[1];
  puVar1 = (uint64_t *)
           ((ulong)(iRingElem << ((ulong)pDst & 0xf)) + (ulong)(this->field_0).field_0.m_vaSramRing)
  ;
  *puVar1 = elem->mask_present[0];
  puVar1[1] = uVar2;
  return;
}


