/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\a53_mm_controller_pipeline_metadata.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003480
 * symbol: MmControllerPipelineSramMetadata
 * prototype: void MmControllerPipelineSramMetadata(MmControllerPipelineSramMetadata * this)
 * body addresses: 16
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void MmControllerPipelineSramMetadata(MmControllerPipelineSramMetadata
   * this) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::MmControllerPipelineSramMetadata
          (MmControllerPipelineSramMetadata *this)

{
  this->m_autoPa2MiBPagesOffset = 0xffffffffffffffff;
  this->m_directPa2MiBPagesOffset = 0xffffffffffffffff;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06003490
 * symbol: setupSram
 * prototype: uint64_t setupSram(MmControllerPipelineSramMetadata * this, uint64_t vaSram)
 * body addresses: 328
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint64_t setupSram(MmControllerPipelineSramMetadata * this, uint64_t
   vaSram) */

uint64_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::setupSram
          (MmControllerPipelineSramMetadata *this,uint64_t vaSram)

{
  uint64_t uVar1;
  uint uVar2;
  byte bVar3;
  long lVar4;
  uint64_t uVar5;
  uint64_t uVar6;
  uint16_t index;
  
  uVar6 = vaSram;
  for (lVar4 = 0; lVar4 != 10; lVar4 = lVar4 + 1) {
    uVar2 = (&Metadata::kMetadataSizes)[lVar4];
    this->m_pSramVA[lVar4] = uVar6;
    uVar6 = uVar6 + uVar2;
  }
  A53_MEMSET_ZERO(vaSram,uVar6 - vaSram);
  uVar1 = this->m_pSramVA[5];
  uVar5 = this->m_pSramVA[6];
  this->m_pListPointersSramVA[0] = this->m_pSramVA[4];
  this->m_pListPointersSramVA[1] = uVar1;
  this->m_pListPointersSramVA[2] = uVar1;
  this->m_pListPointersSramVA[3] = uVar5;
  this->m_pListPointersSramVA[4] = uVar5;
  *(undefined4 *)this->m_pListPointersRootIndex = 0x68696868;
  this->m_pListPointersRootIndex[4] = 'i';
  for (lVar4 = 0; lVar4 != 5; lVar4 = lVar4 + 1) {
    bVar3 = this->m_pListPointersRootIndex[lVar4];
    this->m_pListRootSramVA[lVar4] = this->m_pListPointersSramVA[lVar4] + (ulong)bVar3 * 2;
    *(ushort *)(this->m_pListPointersSramVA[lVar4] + (ulong)bVar3 * 2) =
         CONCAT11(this->m_pListPointersRootIndex[lVar4],this->m_pListPointersRootIndex[lVar4]);
  }
  A53_MEMSET(this->m_pSramVA[0],0x340,'\0');
  A53_MEMSET(this->m_pSramVA[1],0x340,'\0');
  A53_MEMSET(this->m_pSramVA[2],0x340,'\0');
  A53_MEMSET(this->m_pSramVA[7],0x1a000,'\0');
  A53_MEMSET(this->m_pSramVA[8],0x999,0xff);
  this->m_freePtPoolHead = 0x4cc8;
  for (index = 0x133; index < 0x134; index = index - 1) {
    pushToFreePtPool(this,index);
  }
  return uVar6;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060035d8
 * symbol: validate
 * prototype: bool validate(MmControllerPipelineSramMetadata * this)
 * body addresses: 932
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool validate(MmControllerPipelineSramMetadata * this) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::validate(MmControllerPipelineSramMetadata *this)

{
  int *piVar1;
  byte bVar2;
  ushort uVar3;
  uint uVar4;
  ulong uVar5;
  bool bVar6;
  LinkedList LVar7;
  uint8_t paGroupIdx;
  uint uVar8;
  uint64_t uVar9;
  ulong uVar10;
  ulong uVar11;
  int iVar12;
  uint64_t uVar13;
  ulong uVar14;
  long lVar15;
  long lVar16;
  long lVar17;
  ulong uVar18;
  uint32_t pTestListCount [5];
  uint32_t pListCount [5];
  ulong local_78;
  ulong uStack_70;
  undefined8 local_68;
  int local_60;
  int local_5c;
  int local_58;
  int local_54 [5];
  
  uVar8 = 0;
  while (uVar8 < 5) {
    bVar2 = this->m_pListPointersRootIndex[uVar8];
    uVar3 = *(ushort *)this->m_pListRootSramVA[uVar8];
    iVar12 = 1;
    local_54[uVar8] = 0;
    uVar10 = (ulong)uVar3;
    uVar14 = (ulong)bVar2;
    uVar11 = uVar10;
    while (uVar18 = uVar14, uVar14 = uVar10 >> 8, (uint)(uVar10 >> 8) != (uint)bVar2) {
      if (((uint)uVar10 & 0xff) != (uint)(byte)uVar11) {
        return false;
      }
      uVar13 = this->m_pListPointersSramVA[uVar8];
      local_54[uVar8] = iVar12;
      iVar12 = iVar12 + 1;
      uVar10 = (ulong)*(ushort *)(uVar13 + uVar14 * 2);
      uVar11 = uVar18;
    }
    uVar8 = uVar8 + 1;
    if ((uint)uVar18 != (uint)(byte)uVar3) {
      return false;
    }
  }
  if (this->m_autoPa2MiBPagesOffset != 0xffffffffffffffff) {
    A53_MEMSET_ZERO((uint64_t)&local_68,0x14);
    uVar13 = this->m_autoPa2MiBPagesOffset;
    for (uVar8 = (uint)uVar13 & 0xffffffc0; uVar9 = this->m_autoPa2MiBPagesSize,
        (ulong)uVar8 < uVar9 + uVar13; uVar8 = uVar8 + 0x40) {
      uVar4 = uVar8 >> 6;
      lVar15 = *(long *)(this->m_pSramVA[0] + (ulong)uVar4 * 8);
      lVar16 = *(long *)(this->m_pSramVA[1] + (ulong)uVar4 * 8);
      lVar17 = *(long *)(this->m_pSramVA[2] + (ulong)uVar4 * 8);
      paGroupIdx = (uint8_t)uVar4;
      if (lVar15 != 0) {
        local_68._0_4_ = (int)local_68 + 1;
        bVar6 = checkList(this,kHasEmptyGroupList,paGroupIdx);
        if (!bVar6) {
          return false;
        }
      }
      if (lVar17 == -1) {
LAB_0600375c:
        if (lVar16 == 0) {
          if (lVar15 != 0) goto LAB_0600379c;
          local_58 = local_58 + 1;
          bVar6 = checkList(this,kHasMultiFullGroupList,paGroupIdx);
          if (!bVar6) {
            return false;
          }
          LVar7 = kHasMultiPartialGroupList;
        }
        else {
          local_5c = local_5c + 1;
          bVar6 = checkList(this,kHasMultiPartialGroupList,paGroupIdx);
          if (!bVar6) {
            return false;
          }
          LVar7 = kHasMultiFullGroupList;
        }
        bVar6 = checkList(this,LVar7,paGroupIdx);
        if (bVar6) {
          return false;
        }
      }
      else {
        if (lVar16 == 0) {
          if (lVar15 == 0) {
            local_60 = local_60 + 1;
            bVar6 = checkList(this,kHasNonMultiFullGroupList,paGroupIdx);
            if (!bVar6) {
              return false;
            }
            LVar7 = kHasNonMultiPartialGroupList;
            goto LAB_06003740;
          }
        }
        else {
          local_68._4_4_ = local_68._4_4_ + 1;
          bVar6 = checkList(this,kHasNonMultiPartialGroupList,paGroupIdx);
          if (!bVar6) {
            return false;
          }
          LVar7 = kHasNonMultiFullGroupList;
LAB_06003740:
          bVar6 = checkList(this,LVar7,paGroupIdx);
          if (bVar6) {
            return false;
          }
        }
        if (lVar17 != 0) goto LAB_0600375c;
      }
LAB_0600379c:
      uVar13 = this->m_autoPa2MiBPagesOffset;
    }
    lVar15 = 0;
    while ((uint)lVar15 < 5) {
      piVar1 = local_54 + lVar15;
      lVar16 = lVar15 * 4;
      lVar15 = lVar15 + 1;
      if (*piVar1 != *(int *)((long)&local_68 + lVar16)) {
        return false;
      }
    }
    for (uVar14 = uVar13 & 0xffffffff; uVar14 < uVar9 + uVar13; uVar14 = (ulong)((uint)uVar14 + 1))
    {
      uVar18 = *(ulong *)(this->m_pSramVA[0] + (uVar14 >> 6) * 8);
      uVar10 = *(ulong *)(this->m_pSramVA[1] + (uVar14 >> 6) * 8);
      getPaPageState(this,(uint16_t)uVar14,&local_78,&uStack_70);
      uVar11 = 1L << ((uint)uVar14 & 0x3f);
      if ((uVar18 & uVar11) == 0) {
        if ((uVar10 & uVar11) == 0) {
          if ((local_78 != uStack_70 || local_78 != 0xffffffffffffffff) &&
              (local_78 != uStack_70 || local_78 != 0)) {
            return false;
          }
        }
        else {
          if ((uStack_70 | local_78) == 0) {
            return false;
          }
          if ((uStack_70 & local_78) == 0xffffffffffffffff) {
            return false;
          }
        }
      }
      else if ((uStack_70 | local_78) != 0) {
        return false;
      }
      uVar13 = this->m_autoPa2MiBPagesOffset;
      uVar9 = this->m_autoPa2MiBPagesSize;
    }
  }
  uVar13 = this->m_directPa2MiBPagesOffset;
  if (uVar13 != 0xffffffffffffffff) {
    for (uVar14 = uVar13 & 0xffffffff; uVar14 < this->m_directPa2MiBPagesSize + uVar13;
        uVar14 = (ulong)((uint)uVar14 + 1)) {
      uVar18 = *(ulong *)(this->m_pSramVA[0] + (uVar14 >> 6) * 8);
      uVar10 = *(ulong *)(this->m_pSramVA[1] + (uVar14 >> 6) * 8);
      getPaPageState(this,(uint16_t)uVar14,&local_68,(uint64_t *)&local_60);
      uVar11 = 1L << ((uint)uVar14 & 0x3f);
      if ((uVar18 & uVar11) == 0) {
        uVar18 = CONCAT44(local_68._4_4_,(int)local_68);
        uVar5 = CONCAT44(local_5c,local_60);
        if ((uVar10 & uVar11) == 0) {
          if ((uVar18 != uVar5 || uVar18 != 0xffffffffffffffff) && (uVar18 != uVar5 || uVar18 != 0))
          {
            return false;
          }
        }
        else {
          if ((uVar5 | uVar18) == 0) {
            return false;
          }
          if ((uVar5 & uVar18) == 0xffffffffffffffff) {
            return false;
          }
        }
      }
      else if ((CONCAT44(local_5c,local_60) | CONCAT44(local_68._4_4_,(int)local_68)) != 0) {
        return false;
      }
      uVar13 = this->m_directPa2MiBPagesOffset;
    }
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b868
 * symbol: verify2MiBPaPageUsageState
 * prototype: bool verify2MiBPaPageUsageState(MmControllerPipelineSramMetadata * this, uint32_t pa2MiBPagesOffset, uint32_t pa2MiBPagesSize, PaPageUsageState state)
 * body addresses: 256
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool verify2MiBPaPageUsageState(MmControllerPipelineSramMetadata *
   this, uint32_t pa2MiBPagesOffset, uint32_t pa2MiBPagesSize, PaPageUsageState state) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::verify2MiBPaPageUsageState
          (MmControllerPipelineSramMetadata *this,uint32_t pa2MiBPagesOffset,
          uint32_t pa2MiBPagesSize,PaPageUsageState state)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  bool bVar6;
  uint64_t uVar7;
  
  uVar7 = this->m_pSramVA[3];
  uVar1 = pa2MiBPagesSize + pa2MiBPagesOffset;
  uVar5 = (uint)state | (uint)state << 4 | (uint)state << 6 | (uint)state << 2;
  uVar3 = pa2MiBPagesOffset >> 2;
  uVar4 = uVar1 >> 2;
  if (((pa2MiBPagesOffset & 3) != 0) || (((pa2MiBPagesSize & 3) != 0 && (uVar3 == uVar4)))) {
    uVar2 = 0xff;
    if (uVar3 == uVar4) {
      uVar2 = 0xff << (ulong)((uVar1 & 3) * -2 + 8 & 0x1f) & 0xff;
    }
    if (((uVar5 ^ *(byte *)(uVar7 + uVar3)) & 0xffU >> (ulong)((pa2MiBPagesOffset & 3) << 1) & uVar2
        ) != 0) {
      return false;
    }
  }
  if ((uVar3 != uVar4) &&
     ((bVar6 = A53_MEMCMP_U8(uVar7 + (pa2MiBPagesOffset + 3 >> 2),
                             (ulong)((uVar1 & 0xfffffffc) - (pa2MiBPagesOffset + 3 & 0xfffffffc) >>
                                    2),(uint8_t)uVar5), !bVar6 ||
      (((uVar1 & 3) != 0 &&
       (uVar1 = 0xff << (ulong)((uVar1 & 3) * -2 + 8 & 0x1f),
       (uVar1 & *(byte *)(uVar7 + uVar4)) != (uVar1 & uVar5 & 0xff))))))) {
    return false;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600b968
 * symbol: modify2MiBPaPageUsageState
 * prototype: bool modify2MiBPaPageUsageState(MmControllerPipelineSramMetadata * this, uint32_t pa2MiBPagesOffset, uint32_t pa2MiBPagesSize, PaPageUsageState state)
 * body addresses: 548
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool modify2MiBPaPageUsageState(MmControllerPipelineSramMetadata *
   this, uint32_t pa2MiBPagesOffset, uint32_t pa2MiBPagesSize, PaPageUsageState state) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::modify2MiBPaPageUsageState
          (MmControllerPipelineSramMetadata *this,uint32_t pa2MiBPagesOffset,
          uint32_t pa2MiBPagesSize,PaPageUsageState state)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  PaPageUsageState val;
  uint uVar4;
  PaPageUsageState PVar5;
  ulong uVar6;
  uint uVar7;
  uint64_t uVar8;
  
  uVar8 = this->m_pSramVA[3];
  uVar1 = pa2MiBPagesSize + pa2MiBPagesOffset;
  val = state | state << 4 | state << 6 | state << 2;
  uVar2 = pa2MiBPagesOffset >> 2;
  uVar4 = uVar1 >> 2;
  if (((pa2MiBPagesOffset & 3) != 0) || (((pa2MiBPagesSize & 3) != 0 && (uVar2 == uVar4)))) {
    PVar5 = ~kPaPageUsageStateNone;
    if (uVar2 == uVar4) {
      PVar5 = (PaPageUsageState)(0xff << (ulong)((uVar1 & 3) * -2 + 8 & 0x1f));
    }
    *(PaPageUsageState *)(uVar2 + uVar8) =
         val & (PaPageUsageState)(0xff >> (ulong)((pa2MiBPagesOffset & 3) << 1)) & PVar5 |
         *(PaPageUsageState *)(uVar8 + uVar2);
  }
  if (uVar2 != uVar4) {
    A53_MEMSET(uVar8 + (pa2MiBPagesOffset + 3 >> 2),
               (ulong)((uVar1 & 0xfffffffc) - (pa2MiBPagesOffset + 3 & 0xfffffffc) >> 2),val);
    if ((uVar1 & 3) != 0) {
      *(PaPageUsageState *)(uVar8 + uVar4) =
           val & (PaPageUsageState)(0xff << (ulong)((uVar1 & 3) * -2 + 8 & 0x1f)) |
           *(PaPageUsageState *)(uVar8 + uVar4);
    }
  }
  uVar2 = pa2MiBPagesOffset & 0x3f;
  uVar4 = pa2MiBPagesOffset >> 6 & 0xff;
  uVar3 = uVar1 >> 6 & 0xff;
  if ((uVar2 != 0) || (((uVar1 & 0x3f) != 0 && (uVar4 == uVar3)))) {
    uVar6 = 0xffffffffffffffff;
    if (uVar4 == uVar3) {
      uVar6 = 0xffffffffffffffff >> ((ulong)(0x40 - (uVar1 & 0x3f)) & 0x3f);
    }
    *(ulong *)(this->m_pSramVA[0] + (ulong)uVar4 * 8) =
         uVar6 & -1L << uVar2 | *(ulong *)(this->m_pSramVA[0] + (ulong)uVar4 * 8);
  }
  uVar7 = pa2MiBPagesOffset >> 6;
  if ((uVar4 != uVar3) && ((uVar1 & 0x3f) != 0)) {
    *(ulong *)(this->m_pSramVA[0] + (ulong)uVar3 * 8) =
         *(ulong *)(this->m_pSramVA[0] + (ulong)uVar3 * 8) |
         0xffffffffffffffffU >> ((ulong)(0x40 - (uVar1 & 0x3f)) & 0x3f);
  }
  uVar4 = uVar7;
  if (uVar2 != 0) {
    uVar4 = uVar7 + 1;
  }
  uVar2 = uVar1 >> 6;
  for (; (uVar4 & 0xff) < uVar3; uVar4 = (uVar4 & 0xff) + 1) {
    *(undefined8 *)(this->m_pSramVA[0] + (ulong)(uVar4 & 0xff) * 8) = 0xffffffffffffffff;
  }
  if (state == kPaPageUsageStateAuto) {
    if ((uVar1 & 0x3f) != 0) {
      uVar2 = uVar2 + 1;
    }
    for (; (uVar7 & 0xff) < (uVar2 & 0xff); uVar7 = uVar7 + 1) {
      pushToPaPageGroupList(this,(uint8_t)uVar7,kHasEmptyGroupList,kPageListEnd);
    }
    this->m_autoPa2MiBPagesOffset = (ulong)pa2MiBPagesOffset;
    this->m_autoPa2MiBPagesSize = (ulong)pa2MiBPagesSize;
  }
  else if (state == kPaPageUsageStateDirect) {
    this->m_directPa2MiBPagesOffset = (ulong)pa2MiBPagesOffset;
    this->m_directPa2MiBPagesSize = (ulong)pa2MiBPagesSize;
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bb8c
 * symbol: pushToPaPageGroupList
 * prototype: void pushToPaPageGroupList(MmControllerPipelineSramMetadata * this, uint8_t index, LinkedList list, PageListPos pos)
 * body addresses: 120
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushToPaPageGroupList(MmControllerPipelineSramMetadata * this,
   uint8_t index, LinkedList list, PageListPos pos) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::pushToPaPageGroupList
          (MmControllerPipelineSramMetadata *this,uint8_t index,LinkedList list,PageListPos pos)

{
  uint8_t *puVar1;
  byte bVar2;
  byte bVar3;
  uint8_t local_8 [4];
  uint8_t local_4 [4];
  
  puVar1 = this->m_pListPointersRootIndex + list;
  if (pos != kPageListStart) {
    puVar1 = local_4;
  }
  local_4[0] = *(uint8_t *)this->m_pListRootSramVA[list];
  bVar2 = *puVar1;
  puVar1 = local_8;
  if (pos != kPageListStart) {
    puVar1 = this->m_pListPointersRootIndex + list;
  }
  local_8[0] = ((uint8_t *)this->m_pListRootSramVA[list])[1];
  bVar3 = *puVar1;
  *(uint8_t *)(((ulong)bVar2 << 1 | 1) + this->m_pListPointersSramVA[list]) = index;
  *(uint8_t *)(this->m_pListPointersSramVA[list] + (ulong)bVar3 * 2) = index;
  *(ushort *)(this->m_pListPointersSramVA[list] + (ulong)index * 2) = CONCAT11(bVar3,bVar2);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bc04
 * symbol: getUsageState
 * prototype: PaPageUsageState getUsageState(MmControllerPipelineSramMetadata * this, uint16_t pa2MiBPageIndex)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: PaPageUsageState getUsageState(MmControllerPipelineSramMetadata * this,
   uint16_t pa2MiBPageIndex) */

PaPageUsageState __thiscall
A53::MMC::MmControllerPipelineSramMetadata::getUsageState
          (MmControllerPipelineSramMetadata *this,uint16_t pa2MiBPageIndex)

{
  uint uVar1;
  
  uVar1 = ((uint)pa2MiBPageIndex << 1 ^ 0xffffffff) & 6;
  return (PaPageUsageState)
         ((3 << (ulong)uVar1 & (uint)*(byte *)(this->m_pSramVA[3] + (ulong)(pa2MiBPageIndex >> 2)))
         >> (ulong)uVar1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bc30
 * symbol: allocate2MiBPaPage
 * prototype: uint16_t allocate2MiBPaPage(MmControllerPipelineSramMetadata * this, bool bMulti, bool bMarkAsPartial)
 * body addresses: 284
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t allocate2MiBPaPage(MmControllerPipelineSramMetadata * this,
   bool bMulti, bool bMarkAsPartial) */

uint16_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::allocate2MiBPaPage
          (MmControllerPipelineSramMetadata *this,bool bMulti,bool bMarkAsPartial)

{
  byte index;
  bool bVar1;
  byte *pbVar2;
  ulong uVar3;
  LinkedList LVar4;
  ulong uVar5;
  ulong uVar6;
  ulong uVar7;
  uint16_t uVar8;
  
  if (bMulti) {
    pbVar2 = (byte *)this->m_pListRootSramVA[0];
  }
  else {
    pbVar2 = (byte *)(this->m_pListRootSramVA[0] + 1);
  }
  index = *pbVar2;
  uVar7 = (ulong)index;
  if (index == this->m_pListPointersRootIndex[0]) {
    uVar8 = 0xffff;
  }
  else {
    uVar3 = *(ulong *)(this->m_pSramVA[0] + uVar7 * 8);
    uVar5 = (uVar3 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar3 & 0x5555555555555555) << 1;
    uVar5 = (uVar5 & 0xcccccccccccccccc) >> 2 | (uVar5 & 0x3333333333333333) << 2;
    uVar5 = (uVar5 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar5 & 0xf0f0f0f0f0f0f0f) << 4;
    uVar5 = (uVar5 & 0xff00ff00ff00ff00) >> 8 | (uVar5 & 0xff00ff00ff00ff) << 8;
    uVar5 = (uVar5 & 0xffff0000ffff0000) >> 0x10 | (uVar5 & 0xffff0000ffff) << 0x10;
    uVar6 = LZCOUNT(uVar5 >> 0x20 | uVar5 << 0x20);
    uVar5 = 1L << (uVar6 & 0x3f);
    uVar3 = uVar3 & (uVar5 ^ 0xffffffffffffffff);
    uVar8 = (short)uVar6 + (ushort)index * 0x40;
    *(ulong *)(this->m_pSramVA[0] + uVar7 * 8) = uVar3;
    if (bMarkAsPartial) {
      uVar6 = *(ulong *)(this->m_pSramVA[1] + uVar7 * 8);
      bVar1 = uVar6 == 0;
      *(ulong *)(this->m_pSramVA[1] + uVar7 * 8) = uVar6 | uVar5;
    }
    else {
      bVar1 = false;
    }
    if (uVar3 == 0) {
      if (*(long *)(this->m_pSramVA[1] + uVar7 * 8) == 0) {
        LVar4 = kHasMultiFullGroupList;
        if (!bMulti) {
          LVar4 = kHasNonMultiFullGroupList;
        }
        moveToPaPageGroupList(this,index,kHasEmptyGroupList,LVar4,kPageListStart);
      }
      else {
        removeFromPaPageGroupList(this,index,kHasEmptyGroupList);
      }
    }
    if (bVar1) {
      LVar4 = kHasMultiPartialGroupList;
      if (!bMulti) {
        LVar4 = kHasNonMultiPartialGroupList;
      }
      pushToPaPageGroupList(this,index,LVar4,bMulti);
    }
  }
  return uVar8;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bd4c
 * symbol: peekPaGroupListEnd
 * prototype: uint8_t peekPaGroupListEnd(MmControllerPipelineSramMetadata * this, LinkedList list)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint8_t peekPaGroupListEnd(MmControllerPipelineSramMetadata * this,
   LinkedList list) */

uint8_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::peekPaGroupListEnd
          (MmControllerPipelineSramMetadata *this,LinkedList list)

{
  return *(uint8_t *)this->m_pListRootSramVA[list];
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bd60
 * symbol: peekPaGroupList
 * prototype: uint8_t peekPaGroupList(MmControllerPipelineSramMetadata * this, LinkedList list)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint8_t peekPaGroupList(MmControllerPipelineSramMetadata * this,
   LinkedList list) */

uint8_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::peekPaGroupList
          (MmControllerPipelineSramMetadata *this,LinkedList list)

{
  return *(uint8_t *)(this->m_pListRootSramVA[list] + 1);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bd74
 * symbol: moveToPaPageGroupList
 * prototype: void moveToPaPageGroupList(MmControllerPipelineSramMetadata * this, uint8_t index, LinkedList fromList, LinkedList toList, PageListPos pos)
 * body addresses: 164
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void moveToPaPageGroupList(MmControllerPipelineSramMetadata * this,
   uint8_t index, LinkedList fromList, LinkedList toList, PageListPos pos) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::moveToPaPageGroupList
          (MmControllerPipelineSramMetadata *this,uint8_t index,LinkedList fromList,
          LinkedList toList,PageListPos pos)

{
  uint8_t *puVar1;
  byte bVar2;
  byte bVar3;
  ushort uVar4;
  uint8_t local_8 [4];
  uint8_t local_4 [4];
  
  uVar4 = *(ushort *)(this->m_pListPointersSramVA[fromList] + (ulong)index * 2);
  *(char *)(this->m_pListPointersSramVA[fromList] + (ulong)((uVar4 & 0xff) << 1) + 1) =
       (char)(uVar4 >> 8);
  *(char *)(this->m_pListPointersSramVA[fromList] + (ulong)(uVar4 >> 8) * 2) = (char)uVar4;
  puVar1 = this->m_pListPointersRootIndex + toList;
  if (pos != kPageListStart) {
    puVar1 = local_4;
  }
  local_4[0] = *(uint8_t *)this->m_pListRootSramVA[toList];
  bVar2 = *puVar1;
  puVar1 = local_8;
  if (pos != kPageListStart) {
    puVar1 = this->m_pListPointersRootIndex + toList;
  }
  local_8[0] = ((uint8_t *)this->m_pListRootSramVA[toList])[1];
  bVar3 = *puVar1;
  *(uint8_t *)(((ulong)bVar2 << 1 | 1) + this->m_pListPointersSramVA[toList]) = index;
  *(uint8_t *)(this->m_pListPointersSramVA[toList] + (ulong)bVar3 * 2) = index;
  *(ushort *)(this->m_pListPointersSramVA[toList] + (ulong)index * 2) = CONCAT11(bVar3,bVar2);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600be18
 * symbol: removeFromPaPageGroupList
 * prototype: void removeFromPaPageGroupList(MmControllerPipelineSramMetadata * this, uint8_t index, LinkedList list)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void removeFromPaPageGroupList(MmControllerPipelineSramMetadata * this,
   uint8_t index, LinkedList list) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::removeFromPaPageGroupList
          (MmControllerPipelineSramMetadata *this,uint8_t index,LinkedList list)

{
  ushort uVar1;
  
  uVar1 = *(ushort *)(this->m_pListPointersSramVA[list] + (ulong)index * 2);
  *(char *)(this->m_pListPointersSramVA[list] + (ulong)((uVar1 & 0xff) << 1) + 1) =
       (char)(uVar1 >> 8);
  *(char *)(this->m_pListPointersSramVA[list] + (ulong)(uVar1 >> 8) * 2) = (char)uVar1;
  *(ushort *)(this->m_pListPointersSramVA[list] + (ulong)index * 2) = CONCAT11(index,index);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600be5c
 * symbol: allocate2MiBPaPageDirect
 * prototype: bool allocate2MiBPaPageDirect(MmControllerPipelineSramMetadata * this, uint16_t paPageIndex, bool bIsInMultimapAperture)
 * body addresses: 276
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool allocate2MiBPaPageDirect(MmControllerPipelineSramMetadata * this,
   uint16_t paPageIndex, bool bIsInMultimapAperture) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::allocate2MiBPaPageDirect
          (MmControllerPipelineSramMetadata *this,uint16_t paPageIndex,bool bIsInMultimapAperture)

{
  ulong *puVar1;
  ulong uVar2;
  ulong uVar3;
  bool bVar4;
  uint32_t uVar5;
  uint uVar6;
  ulong uVar7;
  
  puVar1 = (ulong *)(this->m_pSramVA[7] + (ulong)paPageIndex * 0x10);
  uVar7 = *puVar1;
  uVar2 = puVar1[1];
  if (bIsInMultimapAperture) {
    uVar5 = get2MiBPaPageMultimapCount(paPageIndex);
    bVar4 = is2MiBPaPage(this,paPageIndex);
    if (uVar5 == 0xffffffff) {
      return false;
    }
    if (bVar4 && uVar5 == 0) {
      return false;
    }
    if ((uVar2 | uVar7) != 0) {
      uVar6 = 0;
      while ((uVar7 != 0 || ((uVar2 != 0 && (uVar6 = uVar6 + 1, uVar7 = uVar2, uVar6 < 2))))) {
        uVar3 = (uVar7 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar7 & 0x5555555555555555) << 1;
        uVar3 = (uVar3 & 0xcccccccccccccccc) >> 2 | (uVar3 & 0x3333333333333333) << 2;
        uVar3 = (uVar3 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar3 & 0xf0f0f0f0f0f0f0f) << 4;
        uVar3 = (uVar3 & 0xff00ff00ff00ff00) >> 8 | (uVar3 & 0xff00ff00ff00ff) << 8;
        uVar3 = (uVar3 & 0xffff0000ffff0000) >> 0x10 | (uVar3 & 0xffff0000ffff) << 0x10;
        uVar5 = get16KiBPaPageMultimapCount
                          ((uint)LZCOUNT(uVar3 >> 0x20 | uVar3 << 0x20) |
                           (uint)paPageIndex << 7 | uVar6 << 6);
        if (uVar5 == 0) {
          return false;
        }
        uVar7 = uVar7 - 1 & uVar7;
      }
    }
    increment2MiBPaPageMultimapCount(paPageIndex);
  }
  else {
    bVar4 = is2MiBPaPage(this,paPageIndex);
    if ((uVar2 | uVar7) != 0) {
      return false;
    }
    if (bVar4) {
      return false;
    }
  }
  unmarkPa2MiBPage(this,paPageIndex,kEmptyState,false);
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bf70
 * symbol: getPaPageState
 * prototype: void getPaPageState(MmControllerPipelineSramMetadata * this, uint16_t pa2MiBPageIndex, uint64_t * out_mask0, uint64_t * out_mask1)
 * body addresses: 28
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void getPaPageState(MmControllerPipelineSramMetadata * this, uint16_t
   pa2MiBPageIndex, uint64_t * out_mask0, uint64_t * out_mask1) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::getPaPageState
          (MmControllerPipelineSramMetadata *this,uint16_t pa2MiBPageIndex,uint64_t *out_mask0,
          uint64_t *out_mask1)

{
  uint64_t *puVar1;
  uint64_t uVar2;
  
  puVar1 = (uint64_t *)(this->m_pSramVA[7] + (ulong)pa2MiBPageIndex * 0x10);
  uVar2 = puVar1[1];
  *out_mask0 = *puVar1;
  *out_mask1 = uVar2;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bf8c
 * symbol: is2MiBPaPage
 * prototype: bool is2MiBPaPage(MmControllerPipelineSramMetadata * this, uint16_t pa2MiBPageIndex)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool is2MiBPaPage(MmControllerPipelineSramMetadata * this, uint16_t
   pa2MiBPageIndex) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::is2MiBPaPage
          (MmControllerPipelineSramMetadata *this,uint16_t pa2MiBPageIndex)

{
  return (1 << (ulong)(pa2MiBPageIndex & 7) &
         (uint)(*(byte *)(this->m_pSramVA[1] + (ulong)(pa2MiBPageIndex >> 3)) |
               *(byte *)(this->m_pSramVA[0] + (ulong)(pa2MiBPageIndex >> 3)))) == 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bfc0
 * symbol: unmarkPa2MiBPage
 * prototype: uint64_t unmarkPa2MiBPage(MmControllerPipelineSramMetadata * this, uint16_t paPageIdx, PageState state, bool bValidate)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint64_t unmarkPa2MiBPage(MmControllerPipelineSramMetadata * this,
   uint16_t paPageIdx, PageState state, bool bValidate) */

uint64_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::unmarkPa2MiBPage
          (MmControllerPipelineSramMetadata *this,uint16_t paPageIdx,PageState state,bool bValidate)

{
  ulong uVar1;
  ulong uVar2;
  
  uVar2 = (ulong)(paPageIdx >> 3) & 0x1ff8;
  uVar1 = *(ulong *)(this->m_pSramVA[state] + uVar2) &
          (1L << (paPageIdx & 0x3f) ^ 0xffffffffffffffffU);
  *(ulong *)(this->m_pSramVA[state] + uVar2) = uVar1;
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600bfec
 * symbol: makeEmpty_2MiBPaPage
 * prototype: void makeEmpty_2MiBPaPage(MmControllerPipelineSramMetadata * this, bool bMulti, uint16_t pa2MiBPageIndex)
 * body addresses: 224
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void makeEmpty_2MiBPaPage(MmControllerPipelineSramMetadata * this, bool
   bMulti, uint16_t pa2MiBPageIndex) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::makeEmpty_2MiBPaPage
          (MmControllerPipelineSramMetadata *this,bool bMulti,uint16_t pa2MiBPageIndex)

{
  uint8_t index;
  ulong uVar1;
  LinkedList LVar2;
  ulong uVar3;
  ulong uVar4;
  ulong uVar5;
  
  uVar3 = (ulong)(pa2MiBPageIndex >> 6);
  uVar5 = *(ulong *)(this->m_pSramVA[0] + uVar3 * 8);
  uVar4 = *(ulong *)(this->m_pSramVA[1] + uVar3 * 8);
  if (uVar5 == 0) {
    index = (uint8_t)(pa2MiBPageIndex >> 6);
    pushToPaPageGroupList(this,index,kHasEmptyGroupList,bMulti);
    if (uVar4 == 0) {
      LVar2 = kHasMultiFullGroupList;
      if (!bMulti) {
        LVar2 = kHasNonMultiFullGroupList;
      }
      removeFromPaPageGroupList(this,index,LVar2);
    }
  }
  uVar1 = 1L << (pa2MiBPageIndex & 0x3f);
  uVar4 = uVar4 & (uVar1 ^ 0xffffffffffffffff);
  *(ulong *)(this->m_pSramVA[0] + uVar3 * 8) = uVar5 | uVar1;
  *(ulong *)(this->m_pSramVA[1] + uVar3 * 8) = uVar4;
  if (uVar4 != 0) {
    return;
  }
  LVar2 = kHasMultiPartialGroupList;
  if (!bMulti) {
    LVar2 = kHasNonMultiPartialGroupList;
  }
  removeFromPaPageGroupList(this,(uint8_t)(pa2MiBPageIndex >> 6),LVar2);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c0cc
 * symbol: makeEmpty_2MiBPaPage_Direct
 * prototype: void makeEmpty_2MiBPaPage_Direct(MmControllerPipelineSramMetadata * this, uint16_t pa2MiBPageIndex)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void makeEmpty_2MiBPaPage_Direct(MmControllerPipelineSramMetadata *
   this, uint16_t pa2MiBPageIndex) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::makeEmpty_2MiBPaPage_Direct
          (MmControllerPipelineSramMetadata *this,uint16_t pa2MiBPageIndex)

{
  ulong uVar1;
  ulong uVar2;
  ulong uVar3;
  
  uVar1 = (ulong)(pa2MiBPageIndex >> 3) & 0x1ff8;
  uVar3 = 1L << (pa2MiBPageIndex & 0x3f);
  uVar2 = *(ulong *)(this->m_pSramVA[1] + uVar1);
  *(ulong *)(this->m_pSramVA[0] + uVar1) = *(ulong *)(this->m_pSramVA[0] + uVar1) | uVar3;
  *(ulong *)(this->m_pSramVA[1] + uVar1) = uVar2 & (uVar3 ^ 0xffffffffffffffff);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c104
 * symbol: makePartial_2MiBPaPage
 * prototype: void makePartial_2MiBPaPage(MmControllerPipelineSramMetadata * this, bool bMulti, uint16_t pa2MiBPageIndex)
 * body addresses: 176
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void makePartial_2MiBPaPage(MmControllerPipelineSramMetadata * this,
   bool bMulti, uint16_t pa2MiBPageIndex) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::makePartial_2MiBPaPage
          (MmControllerPipelineSramMetadata *this,bool bMulti,uint16_t pa2MiBPageIndex)

{
  uint8_t index;
  LinkedList LVar1;
  ulong uVar2;
  ulong uVar3;
  long lVar4;
  
  uVar2 = (ulong)(pa2MiBPageIndex >> 3 & 0x7f8);
  uVar3 = *(ulong *)(this->m_pSramVA[1] + uVar2);
  if (uVar3 == 0) {
    index = (uint8_t)(pa2MiBPageIndex >> 6);
    lVar4 = *(long *)(this->m_pSramVA[0] + uVar2);
    LVar1 = kHasMultiPartialGroupList;
    if (!bMulti) {
      LVar1 = kHasNonMultiPartialGroupList;
    }
    pushToPaPageGroupList(this,index,LVar1,bMulti);
    if (lVar4 == 0) {
      LVar1 = kHasMultiFullGroupList;
      if (!bMulti) {
        LVar1 = kHasNonMultiFullGroupList;
      }
      removeFromPaPageGroupList(this,index,LVar1);
    }
  }
  *(ulong *)(this->m_pSramVA[1] + uVar2) = uVar3 | 1L << ((ulong)pa2MiBPageIndex & 0x3f);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c1b4
 * symbol: makePartial_2MiBPaPage_Direct
 * prototype: void makePartial_2MiBPaPage_Direct(MmControllerPipelineSramMetadata * this, uint16_t pa2MiBPageIndex)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void makePartial_2MiBPaPage_Direct(MmControllerPipelineSramMetadata *
   this, uint16_t pa2MiBPageIndex) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::makePartial_2MiBPaPage_Direct
          (MmControllerPipelineSramMetadata *this,uint16_t pa2MiBPageIndex)

{
  uint uVar1;
  
  uVar1 = pa2MiBPageIndex >> 3 & 0x7f8;
  *(ulong *)(this->m_pSramVA[1] + (ulong)uVar1) =
       *(ulong *)(this->m_pSramVA[1] + (ulong)uVar1) | 1L << (pa2MiBPageIndex & 0x3f);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c1dc
 * symbol: allocate16KiBPaBlock
 * prototype: PA_ALLOC_BLOCK allocate16KiBPaBlock(MmControllerPipelineSramMetadata * this, uint64_t bigCoreGameBudgetPAStart, uint64_t indexVa16K, uint64_t indexVa16K_end, bool bIsInMultimapAperture)
 * body addresses: 824
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: PA_ALLOC_BLOCK allocate16KiBPaBlock(MmControllerPipelineSramMetadata *
   this, uint64_t bigCoreGameBudgetPAStart, uint64_t indexVa16K, uint64_t indexVa16K_end, bool
   bIsInMultimapAperture) */

PA_ALLOC_BLOCK __thiscall
A53::MMC::MmControllerPipelineSramMetadata::allocate16KiBPaBlock
          (MmControllerPipelineSramMetadata *this,uint64_t bigCoreGameBudgetPAStart,
          uint64_t indexVa16K,uint64_t indexVa16K_end,bool bIsInMultimapAperture)

{
  ulong *puVar1;
  ulong uVar2;
  ulong uVar3;
  uint16_t uVar4;
  uint64_t uVar5;
  uint64_t uVar6;
  LinkedList toList;
  uint uVar7;
  uint uVar8;
  uint8_t *puVar9;
  ulong uVar10;
  ulong uVar11;
  LinkedList toList_00;
  byte index;
  PA_PAGE_STATE_2MB PVar12;
  PA_ALLOC_BLOCK PVar13;
  ulong local_70 [2];
  
  uVar7 = 3;
  if (!bIsInMultimapAperture) {
    uVar7 = 1;
  }
  index = *(byte *)(this->m_pListRootSramVA[uVar7] + 1);
  toList = (LinkedList)uVar7;
  if ((uint)index == (uint)this->m_pListPointersRootIndex[uVar7]) {
    if (bIsInMultimapAperture) {
      puVar9 = (uint8_t *)this->m_pListRootSramVA[0];
    }
    else {
      puVar9 = (uint8_t *)(this->m_pListRootSramVA[0] + 1);
    }
    if (*puVar9 != this->m_pListPointersRootIndex[0]) {
      uVar4 = allocate2MiBPaPage(this,bIsInMultimapAperture,true);
      uVar7 = (uint)uVar4;
      if (bIsInMultimapAperture) {
        uVar11 = (ulong)(uVar4 >> 3) & 0x1ff8;
        *(ulong *)(this->m_pSramVA[2] + uVar11) =
             *(ulong *)(this->m_pSramVA[2] + uVar11) | 1L << (uVar7 & 0x3f);
      }
      PVar12 = initPaPageState(indexVa16K,indexVa16K_end);
      uVar5 = bigCoreGameBudgetPAStart + indexVa16K * 0x4000 + (ulong)uVar7 * 0x200000;
      uVar6 = (indexVa16K_end - indexVa16K) * 0x4000;
      *(uint64_t (*) [2])(this->m_pSramVA[7] + (ulong)uVar7 * 0x10) = PVar12.mask;
      goto LAB_0600c4f4;
    }
    uVar8 = 3;
    if (bIsInMultimapAperture) {
      uVar8 = 1;
    }
    index = *(byte *)(this->m_pListRootSramVA[uVar8] + 1);
    if ((uint)index == (uint)this->m_pListPointersRootIndex[uVar8]) {
      uVar5 = 0;
      uVar6 = 0;
      goto LAB_0600c4f4;
    }
    uVar11 = *(ulong *)(this->m_pSramVA[1] + (ulong)index * 8);
    uVar11 = (uVar11 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar11 & 0x5555555555555555) << 1;
    uVar11 = (uVar11 & 0xcccccccccccccccc) >> 2 | (uVar11 & 0x3333333333333333) << 2;
    uVar11 = (uVar11 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar11 & 0xf0f0f0f0f0f0f0f) << 4;
    uVar11 = (uVar11 & 0xff00ff00ff00ff00) >> 8 | (uVar11 & 0xff00ff00ff00ff) << 8;
    uVar11 = (uVar11 & 0xffff0000ffff0000) >> 0x10 | (uVar11 & 0xffff0000ffff) << 0x10;
    uVar7 = (int)LZCOUNT(uVar11 >> 0x20 | uVar11 << 0x20) + (uint)index * 0x40;
    if (bIsInMultimapAperture) {
      moveToPaPageGroupList(this,index,(LinkedList)uVar8,toList,kPageListStart);
      *(ulong *)(this->m_pSramVA[2] + (ulong)(uVar7 >> 6) * 8) =
           *(ulong *)(this->m_pSramVA[2] + (ulong)(uVar7 >> 6) * 8) | 1L << (uVar7 & 0x3f);
    }
  }
  else {
    uVar11 = *(ulong *)(this->m_pSramVA[1] + (ulong)index * 8);
    uVar11 = (uVar11 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar11 & 0x5555555555555555) << 1;
    uVar11 = (uVar11 & 0xcccccccccccccccc) >> 2 | (uVar11 & 0x3333333333333333) << 2;
    uVar11 = (uVar11 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar11 & 0xf0f0f0f0f0f0f0f) << 4;
    uVar11 = (uVar11 & 0xff00ff00ff00ff00) >> 8 | (uVar11 & 0xff00ff00ff00ff) << 8;
    uVar11 = (uVar11 & 0xffff0000ffff0000) >> 0x10 | (uVar11 & 0xffff0000ffff) << 0x10;
    uVar7 = (int)LZCOUNT(uVar11 >> 0x20 | uVar11 << 0x20) + (uint)index * 0x40;
  }
  puVar1 = (ulong *)(this->m_pSramVA[7] + (ulong)uVar7 * 0x10);
  uVar11 = *puVar1;
  uVar3 = puVar1[1];
  local_70[0] = uVar11;
  local_70[1] = uVar3;
  uVar6 = indexVa16K;
  if ((*(ulong *)((long)local_70 + (indexVa16K >> 3 & 0x1ffffffffffffff8)) &
      1L << (indexVa16K & 0x3f)) != 0) {
    uVar10 = 0x1111111111111111 << (indexVa16K & 3);
    uVar2 = uVar10 & (uVar11 ^ 0xffffffffffffffff);
    if (uVar2 == 0) {
      uVar10 = uVar10 & (uVar3 ^ 0xffffffffffffffff);
      if (uVar10 == 0) {
        uVar2 = (~uVar3 & 0xaaaaaaaaaaaaaaaa) >> 1 | (~uVar3 & 0x5555555555555555) << 1;
        uVar2 = (uVar2 & 0xcccccccccccccccc) >> 2 | (uVar2 & 0x3333333333333333) << 2;
        uVar2 = (uVar2 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar2 & 0xf0f0f0f0f0f0f0f) << 4;
        uVar2 = (uVar2 & 0xff00ff00ff00ff00) >> 8 | (uVar2 & 0xff00ff00ff00ff) << 8;
        uVar2 = (uVar2 & 0xffff0000ffff0000) >> 0x10 | (uVar2 & 0xffff0000ffff) << 0x10;
        uVar10 = (~uVar11 & 0xaaaaaaaaaaaaaaaa) >> 1 | (~uVar11 & 0x5555555555555555) << 1;
        uVar10 = (uVar10 & 0xcccccccccccccccc) >> 2 | (uVar10 & 0x3333333333333333) << 2;
        uVar10 = (uVar10 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar10 & 0xf0f0f0f0f0f0f0f) << 4;
        uVar10 = (uVar10 & 0xff00ff00ff00ff00) >> 8 | (uVar10 & 0xff00ff00ff00ff) << 8;
        uVar10 = (uVar10 & 0xffff0000ffff0000) >> 0x10 | (uVar10 & 0xffff0000ffff) << 0x10;
        uVar6 = LZCOUNT(uVar2 >> 0x20 | uVar2 << 0x20) + 0x40;
        if (uVar11 != 0xffffffffffffffff) {
          uVar6 = LZCOUNT(uVar10 >> 0x20 | uVar10 << 0x20);
        }
      }
      else {
        uVar2 = (uVar10 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar10 & 0x5555555555555555) << 1;
        uVar2 = (uVar2 & 0xcccccccccccccccc) >> 2 | (uVar2 & 0x3333333333333333) << 2;
        uVar2 = (uVar2 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar2 & 0xf0f0f0f0f0f0f0f) << 4;
        uVar2 = (uVar2 & 0xff00ff00ff00ff00) >> 8 | (uVar2 & 0xff00ff00ff00ff) << 8;
        uVar2 = (uVar2 & 0xffff0000ffff0000) >> 0x10 | (uVar2 & 0xffff0000ffff) << 0x10;
        uVar6 = LZCOUNT(uVar2 >> 0x20 | uVar2 << 0x20) + 0x40;
      }
    }
    else {
      uVar2 = (uVar2 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar2 & 0x5555555555555555) << 1;
      uVar2 = (uVar2 & 0xcccccccccccccccc) >> 2 | (uVar2 & 0x3333333333333333) << 2;
      uVar2 = (uVar2 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar2 & 0xf0f0f0f0f0f0f0f) << 4;
      uVar2 = (uVar2 & 0xff00ff00ff00ff00) >> 8 | (uVar2 & 0xff00ff00ff00ff) << 8;
      uVar2 = (uVar2 & 0xffff0000ffff0000) >> 0x10 | (uVar2 & 0xffff0000ffff) << 0x10;
      uVar6 = LZCOUNT(uVar2 >> 0x20 | uVar2 << 0x20);
    }
    indexVa16K_end = (uVar6 - indexVa16K) + indexVa16K_end;
    if (0x7f < indexVa16K_end) {
      indexVa16K_end = 0x80;
    }
  }
  PVar12 = initPaPageState(uVar6,indexVa16K_end);
  uVar2 = PVar12.mask[0] & uVar11;
  if (uVar2 == 0) {
    uVar10 = PVar12.mask[1] & uVar3;
    uVar2 = (uVar10 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar10 & 0x5555555555555555) << 1;
    uVar2 = (uVar2 & 0xcccccccccccccccc) >> 2 | (uVar2 & 0x3333333333333333) << 2;
    uVar2 = (uVar2 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar2 & 0xf0f0f0f0f0f0f0f) << 4;
    uVar2 = (uVar2 & 0xff00ff00ff00ff00) >> 8 | (uVar2 & 0xff00ff00ff00ff) << 8;
    uVar2 = (uVar2 & 0xffff0000ffff0000) >> 0x10 | (uVar2 & 0xffff0000ffff) << 0x10;
    if (uVar10 != 0) {
      indexVa16K_end = LZCOUNT(uVar2 >> 0x20 | uVar2 << 0x20) + 0x40;
    }
  }
  else {
    uVar2 = (uVar2 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar2 & 0x5555555555555555) << 1;
    uVar2 = (uVar2 & 0xcccccccccccccccc) >> 2 | (uVar2 & 0x3333333333333333) << 2;
    uVar2 = (uVar2 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar2 & 0xf0f0f0f0f0f0f0f) << 4;
    uVar2 = (uVar2 & 0xff00ff00ff00ff00) >> 8 | (uVar2 & 0xff00ff00ff00ff) << 8;
    uVar2 = (uVar2 & 0xffff0000ffff0000) >> 0x10 | (uVar2 & 0xffff0000ffff) << 0x10;
    indexVa16K_end = LZCOUNT(uVar2 >> 0x20 | uVar2 << 0x20);
  }
  PVar12 = initPaPageState(uVar6,indexVa16K_end);
  local_70[0] = PVar12.mask[0] | uVar11;
  local_70[1] = PVar12.mask[1] | uVar3;
  *puVar1 = local_70[0];
  puVar1[1] = local_70[1];
  if (((local_70[1] & local_70[0]) == 0xffffffffffffffff) &&
     (uVar5 = unmarkPa2MiBPage(this,(uint16_t)uVar7,kPartialState,false), uVar5 == 0)) {
    if (*(long *)(this->m_pSramVA[0] + (ulong)(uVar7 >> 6)) == 0) {
      toList_00 = kHasMultiFullGroupList;
      if (!bIsInMultimapAperture) {
        toList_00 = kHasNonMultiFullGroupList;
      }
      moveToPaPageGroupList(this,index,toList,toList_00,kPageListStart);
    }
    else {
      removeFromPaPageGroupList(this,index,toList);
    }
  }
  uVar5 = bigCoreGameBudgetPAStart + (ulong)uVar7 * 0x200000 + uVar6 * 0x4000;
  uVar6 = (indexVa16K_end - uVar6) * 0x4000;
LAB_0600c4f4:
  PVar13.size = uVar6;
  PVar13.pa = uVar5;
  return PVar13;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c514
 * symbol: markPa2MiBPage
 * prototype: uint64_t markPa2MiBPage(MmControllerPipelineSramMetadata * this, uint16_t paPageIdx, PageState state, bool bValidate)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint64_t markPa2MiBPage(MmControllerPipelineSramMetadata * this,
   uint16_t paPageIdx, PageState state, bool bValidate) */

uint64_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::markPa2MiBPage
          (MmControllerPipelineSramMetadata *this,uint16_t paPageIdx,PageState state,bool bValidate)

{
  ulong uVar1;
  ulong uVar2;
  
  uVar2 = (ulong)(paPageIdx >> 3) & 0x1ff8;
  uVar1 = *(ulong *)(this->m_pSramVA[state] + uVar2) | 1L << (paPageIdx & 0x3f);
  *(ulong *)(this->m_pSramVA[state] + uVar2) = uVar1;
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c540
 * symbol: initPaPageState
 * prototype: PA_PAGE_STATE_2MB initPaPageState(uint64_t firstIndex, uint64_t lastIndex)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

PA_PAGE_STATE_2MB A53::MMC::initPaPageState(uint64_t firstIndex,uint64_t lastIndex)

{
  ulong uVar1;
  ulong uVar2;
  ulong uVar3;
  ulong uVar4;
  PA_PAGE_STATE_2MB PVar5;
  
  uVar2 = -1L << (firstIndex & 0x3f);
  uVar4 = (1L << (lastIndex & 0x3f)) - 1;
  if (firstIndex < 0x40) {
    uVar1 = 0xffffffffffffffff;
  }
  else {
    uVar1 = uVar2;
    uVar2 = 0;
  }
  uVar3 = uVar4;
  if (0x7f < lastIndex) {
    uVar3 = 0xffffffffffffffff;
  }
  uVar3 = uVar3 & uVar1;
  if (lastIndex < 0x40) {
    uVar3 = 0;
    uVar2 = uVar4 & uVar2;
  }
  PVar5.mask[1] = uVar3;
  PVar5.mask[0] = uVar2;
  return (PA_PAGE_STATE_2MB)PVar5.mask;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c588
 * symbol: setPaPageState
 * prototype: void setPaPageState(MmControllerPipelineSramMetadata * this, uint16_t pa2MiBPageIndex, uint64_t mask0, uint64_t mask1)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void setPaPageState(MmControllerPipelineSramMetadata * this, uint16_t
   pa2MiBPageIndex, uint64_t mask0, uint64_t mask1) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::setPaPageState
          (MmControllerPipelineSramMetadata *this,uint16_t pa2MiBPageIndex,uint64_t mask0,
          uint64_t mask1)

{
  uint64_t *pDst;
  
  pDst = (uint64_t *)this->m_pSramVA[7];
  pDst[(ulong)pa2MiBPageIndex * 2] = mask0;
  (pDst + (ulong)pa2MiBPageIndex * 2)[1] = mask1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c59c
 * symbol: allocatePageIdxFromGroup
 * prototype: uint16_t allocatePageIdxFromGroup(MmControllerPipelineSramMetadata * this, uint16_t groupIdx, PageState state, bool bUnMarkState)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t allocatePageIdxFromGroup(MmControllerPipelineSramMetadata *
   this, uint16_t groupIdx, PageState state, bool bUnMarkState) */

uint16_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::allocatePageIdxFromGroup
          (MmControllerPipelineSramMetadata *this,uint16_t groupIdx,PageState state,
          bool bUnMarkState)

{
  ulong uVar1;
  ulong uVar2;
  
  uVar1 = *(ulong *)(this->m_pSramVA[state] + (ulong)groupIdx * 8);
  uVar2 = (uVar1 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar1 & 0x5555555555555555) << 1;
  uVar2 = (uVar2 & 0xcccccccccccccccc) >> 2 | (uVar2 & 0x3333333333333333) << 2;
  uVar2 = (uVar2 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar2 & 0xf0f0f0f0f0f0f0f) << 4;
  uVar2 = (uVar2 & 0xff00ff00ff00ff00) >> 8 | (uVar2 & 0xff00ff00ff00ff) << 8;
  uVar2 = (uVar2 & 0xffff0000ffff0000) >> 0x10 | (uVar2 & 0xffff0000ffff) << 0x10;
  uVar2 = LZCOUNT(uVar2 >> 0x20 | uVar2 << 0x20);
  if (bUnMarkState) {
    *(ulong *)(this->m_pSramVA[state] + (ulong)groupIdx * 8) =
         uVar1 & (1L << (uVar2 & 0x3f) ^ 0xffffffffffffffffU);
  }
  return (short)uVar2 + groupIdx * 0x40;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600c5d0
 * symbol: allocate16KiBPaBlockDirect
 * prototype: PA_ALLOC_BLOCK allocate16KiBPaBlockDirect(MmControllerPipelineSramMetadata * this, uint64_t bigCoreGameBudgetPAStart, uint16_t paPageIndex, uint64_t paPageIndex16K, uint64_t paPageIndex16KEnd, bool bIsInMultimapAperture)
 * body addresses: 1092
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: PA_ALLOC_BLOCK
   allocate16KiBPaBlockDirect(MmControllerPipelineSramMetadata * this, uint64_t
   bigCoreGameBudgetPAStart, uint16_t paPageIndex, uint64_t paPageIndex16K, uint64_t
   paPageIndex16KEnd, bool bIsInMultimapAperture) */

PA_ALLOC_BLOCK __thiscall
A53::MMC::MmControllerPipelineSramMetadata::allocate16KiBPaBlockDirect
          (MmControllerPipelineSramMetadata *this,uint64_t bigCoreGameBudgetPAStart,
          uint16_t paPageIndex,uint64_t paPageIndex16K,uint64_t paPageIndex16KEnd,
          bool bIsInMultimapAperture)

{
  ulong uVar1;
  bool bVar2;
  uint32_t uVar3;
  uint64_t uVar4;
  uint16_t pa2MiBPageIndex;
  uint64_t uVar5;
  ulong uVar6;
  ulong *puVar7;
  uint uVar8;
  ulong uVar9;
  ulong uVar10;
  ulong *puVar11;
  ulong uVar12;
  uint uVar13;
  ulong uVar14;
  ulong uVar15;
  ulong uVar16;
  ulong uVar17;
  ulong uVar18;
  PA_PAGE_STATE_2MB PVar19;
  PA_ALLOC_BLOCK PVar20;
  
  uVar6 = (ulong)paPageIndex;
  puVar11 = (ulong *)(this->m_pSramVA[7] + uVar6 * 0x10);
  uVar12 = *puVar11;
  puVar7 = puVar11 + 1;
  uVar18 = *puVar7;
  if (paPageIndex16KEnd < 0x80 || paPageIndex16KEnd - 0x80 == 0) {
    PVar19 = initPaPageState(paPageIndex16K,paPageIndex16KEnd);
    uVar15 = PVar19.mask[0] & uVar12;
    uVar9 = PVar19.mask[1] & uVar18;
    if (bIsInMultimapAperture) {
      uVar4 = paPageIndex16K;
      if ((uVar15 | uVar9) == 0) {
LAB_0600c870:
        for (; uVar4 < paPageIndex16KEnd; uVar4 = uVar4 + 1) {
          increment16KiBPaPageMultimapCount((uint32_t)uVar4);
        }
        puVar11 = (ulong *)(this->m_pSramVA[7] + uVar6 * 0x10);
        puVar7 = puVar11 + 1;
LAB_0600c888:
        uVar12 = PVar19.mask[0] | uVar12;
        *puVar11 = uVar12;
        uVar18 = PVar19.mask[1] | uVar18;
        *puVar7 = uVar18;
LAB_0600c980:
        unmarkPa2MiBPage(this,paPageIndex,kEmptyState,false);
        if ((uVar12 & uVar18) == 0xffffffffffffffff) {
          unmarkPa2MiBPage(this,paPageIndex,kPartialState,false);
        }
        else {
          uVar12 = (ulong)(paPageIndex >> 3) & 0x1ff8;
          *(ulong *)(this->m_pSramVA[1] + uVar12) =
               *(ulong *)(this->m_pSramVA[1] + uVar12) | 1L << (paPageIndex & 0x3f);
        }
        uVar4 = bigCoreGameBudgetPAStart + uVar6 * 0x200000 + paPageIndex16K * 0x4000;
        uVar5 = (paPageIndex16KEnd - paPageIndex16K) * 0x4000;
        goto LAB_0600c9f4;
      }
      uVar13 = 0;
      do {
        if ((uVar15 == 0) && ((uVar9 == 0 || (uVar13 = uVar13 + 1, uVar15 = uVar9, 1 < uVar13))))
        goto LAB_0600c870;
        uVar10 = (uVar15 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar15 & 0x5555555555555555) << 1;
        uVar10 = (uVar10 & 0xcccccccccccccccc) >> 2 | (uVar10 & 0x3333333333333333) << 2;
        uVar10 = (uVar10 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar10 & 0xf0f0f0f0f0f0f0f) << 4;
        uVar10 = (uVar10 & 0xff00ff00ff00ff00) >> 8 | (uVar10 & 0xff00ff00ff00ff) << 8;
        uVar10 = (uVar10 & 0xffff0000ffff0000) >> 0x10 | (uVar10 & 0xffff0000ffff) << 0x10;
        uVar3 = get16KiBPaPageMultimapCount
                          ((uint)LZCOUNT(uVar10 >> 0x20 | uVar10 << 0x20) |
                           (uint)paPageIndex << 7 | uVar13 << 6);
      } while (1 < uVar3 + 1);
    }
    else if ((uVar15 | uVar9) == 0) goto LAB_0600c888;
  }
  else {
    pa2MiBPageIndex = paPageIndex + 1;
    bVar2 = is2MiBPaPage(this,pa2MiBPageIndex);
    if (bIsInMultimapAperture) {
      if ((!bVar2) || (uVar3 = get2MiBPaPageMultimapCount(pa2MiBPageIndex), uVar3 != 0)) {
LAB_0600c714:
        uVar15 = -1L << (paPageIndex16K & 0x3f);
        if (paPageIndex16K < 0x40) {
          uVar9 = 0xffffffffffffffff;
        }
        else {
          uVar9 = uVar15;
          uVar15 = 0;
        }
        uVar10 = uVar12 & uVar15;
        uVar16 = uVar18 & uVar9;
        if (bIsInMultimapAperture) {
          if ((uVar16 | uVar10) == 0) {
LAB_0600c7a8:
            PVar19 = initPaPageState(0,paPageIndex16KEnd - 0x80);
            uVar4 = this->m_pSramVA[7];
            uVar13 = paPageIndex + 1;
            puVar11 = (ulong *)(uVar4 + (ulong)(ushort)uVar13 * 0x10);
            uVar10 = *puVar11;
            uVar16 = puVar11[1];
            if (bIsInMultimapAperture) {
              uVar17 = uVar10 & PVar19.mask[0];
              uVar14 = uVar16 & PVar19.mask[1];
              uVar4 = paPageIndex16K;
              if ((uVar14 | uVar17) != 0) {
                uVar8 = 0;
                do {
                  if ((uVar17 == 0) &&
                     ((uVar14 == 0 || (uVar8 = uVar8 + 1, uVar17 = uVar14, 1 < uVar8))))
                  goto LAB_0600c8cc;
                  uVar1 = (uVar17 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar17 & 0x5555555555555555) << 1;
                  uVar1 = (uVar1 & 0xcccccccccccccccc) >> 2 | (uVar1 & 0x3333333333333333) << 2;
                  uVar1 = (uVar1 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar1 & 0xf0f0f0f0f0f0f0f) << 4;
                  uVar1 = (uVar1 & 0xff00ff00ff00ff00) >> 8 | (uVar1 & 0xff00ff00ff00ff) << 8;
                  uVar1 = (uVar1 & 0xffff0000ffff0000) >> 0x10 | (uVar1 & 0xffff0000ffff) << 0x10;
                  uVar3 = get16KiBPaPageMultimapCount
                                    ((uint)LZCOUNT(uVar1 >> 0x20 | uVar1 << 0x20) |
                                     (uVar13 & 0xffff) << 7 | uVar8 << 6);
                } while (1 < uVar3 + 1);
                goto LAB_0600c850;
              }
LAB_0600c8cc:
              for (; uVar4 < paPageIndex16KEnd; uVar4 = uVar4 + 1) {
                increment16KiBPaPageMultimapCount((uint32_t)uVar4);
              }
              uVar4 = this->m_pSramVA[7];
            }
            uVar10 = uVar10 | PVar19.mask[0];
            uVar12 = uVar12 | uVar15;
            puVar11 = (ulong *)(uVar4 + uVar6 * 0x10);
            uVar18 = uVar18 | uVar9;
            *puVar11 = uVar12;
            puVar11[1] = uVar18;
            uVar16 = uVar16 | PVar19.mask[1];
            puVar11 = (ulong *)(this->m_pSramVA[7] + ((ulong)uVar13 & 0xffff) * 0x10);
            *puVar11 = uVar10;
            puVar11[1] = uVar16;
            unmarkPa2MiBPage(this,pa2MiBPageIndex,kEmptyState,false);
            if ((uVar16 & uVar10) == 0xffffffffffffffff) {
              unmarkPa2MiBPage(this,paPageIndex,kPartialState,false);
            }
            else {
              uVar15 = (ulong)(uVar13 >> 3) & 0x1ff8;
              *(ulong *)(this->m_pSramVA[1] + uVar15) =
                   *(ulong *)(this->m_pSramVA[1] + uVar15) | 1L << (uVar13 & 0x3f);
            }
            goto LAB_0600c980;
          }
          uVar13 = 0;
          do {
            if ((uVar10 == 0) &&
               ((uVar16 == 0 || (uVar13 = uVar13 + 1, uVar10 = uVar16, 1 < uVar13))))
            goto LAB_0600c7a8;
            uVar17 = (uVar10 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar10 & 0x5555555555555555) << 1;
            uVar17 = (uVar17 & 0xcccccccccccccccc) >> 2 | (uVar17 & 0x3333333333333333) << 2;
            uVar17 = (uVar17 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar17 & 0xf0f0f0f0f0f0f0f) << 4;
            uVar17 = (uVar17 & 0xff00ff00ff00ff00) >> 8 | (uVar17 & 0xff00ff00ff00ff) << 8;
            uVar17 = (uVar17 & 0xffff0000ffff0000) >> 0x10 | (uVar17 & 0xffff0000ffff) << 0x10;
            uVar3 = get16KiBPaPageMultimapCount
                              ((uint)LZCOUNT(uVar17 >> 0x20 | uVar17 << 0x20) |
                               (uint)paPageIndex << 7 | uVar13 << 6);
          } while (1 < uVar3 + 1);
        }
        else if ((uVar16 | uVar10) == 0) goto LAB_0600c7a8;
      }
    }
    else if (!bVar2) goto LAB_0600c714;
  }
LAB_0600c850:
  uVar4 = 0;
  uVar5 = 0;
LAB_0600c9f4:
  PVar20.size = uVar5;
  PVar20.pa = uVar4;
  return PVar20;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600ca14
 * symbol: free16KiBPa
 * prototype: void free16KiBPa(MmControllerPipelineSramMetadata * this, uint64_t pa, uint64_t bigCoreGameBudgetPA, bool bMulti)
 * body addresses: 296
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void free16KiBPa(MmControllerPipelineSramMetadata * this, uint64_t pa,
   uint64_t bigCoreGameBudgetPA, bool bMulti) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::free16KiBPa
          (MmControllerPipelineSramMetadata *this,uint64_t pa,uint64_t bigCoreGameBudgetPA,
          bool bMulti)

{
  ulong *puVar1;
  ulong *puVar2;
  uint16_t pa2MiBPageIndex;
  PaPageUsageState PVar3;
  uint32_t uVar4;
  ulong uVar5;
  ulong uVar6;
  ulong uVar7;
  ulong local_48;
  ulong local_38;
  
  uVar5 = pa - bigCoreGameBudgetPA;
  puVar1 = (ulong *)(this->m_pSramVA[7] + (uVar5 >> 0x11 & 0xffff0));
  puVar2 = &local_38;
  if ((uVar5 & 0x100000) != 0) {
    puVar2 = &local_48;
  }
  local_38 = *puVar1;
  uVar7 = puVar1[1] & *puVar1;
  local_48 = puVar1[1];
  *puVar2 = *puVar2 & (1L << (uVar5 >> 0xe & 0x3f) ^ 0xffffffffffffffffU);
  uVar6 = local_48 | local_38;
  *puVar1 = local_38;
  puVar1[1] = local_48;
  if (((uVar7 == 0xffffffffffffffff) || (uVar6 == 0)) &&
     ((pa2MiBPageIndex = (uint16_t)(uVar5 >> 0x15), uVar7 == 0 ||
      ((!bMulti || (uVar4 = get2MiBPaPageMultimapCount(pa2MiBPageIndex), uVar4 == 0)))))) {
    PVar3 = getUsageState(this,pa2MiBPageIndex);
    if (PVar3 == kPaPageUsageStateAuto) {
      if (uVar7 == 0xffffffffffffffff) {
        makePartial_2MiBPaPage(this,bMulti,pa2MiBPageIndex);
      }
      else if (uVar6 == 0) {
        makeEmpty_2MiBPaPage(this,bMulti,pa2MiBPageIndex);
      }
    }
    else if (uVar7 == 0xffffffffffffffff) {
      makePartial_2MiBPaPage_Direct(this,pa2MiBPageIndex);
    }
    else if (uVar6 == 0) {
      makeEmpty_2MiBPaPage_Direct(this,pa2MiBPageIndex);
    }
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cb3c
 * symbol: getFreePageTable
 * prototype: uint16_t getFreePageTable(MmControllerPipelineSramMetadata * this)
 * body addresses: 96
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t getFreePageTable(MmControllerPipelineSramMetadata * this) */

uint16_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::getFreePageTable(MmControllerPipelineSramMetadata *this)

{
  ushort uVar1;
  ulong uVar2;
  ulong uVar3;
  uint16_t uVar4;
  
  uVar1 = this->m_freePtPoolHead;
  if (uVar1 == 0x4cc8) {
    uVar4 = 0xffff;
  }
  else {
    uVar2 = *(ulong *)(this->m_pSramVA[8] + (ulong)uVar1 * 8);
    uVar3 = (uVar2 & 0xaaaaaaaaaaaaaaaa) >> 1 | (uVar2 & 0x5555555555555555) << 1;
    uVar3 = (uVar3 & 0xcccccccccccccccc) >> 2 | (uVar3 & 0x3333333333333333) << 2;
    uVar3 = (uVar3 & 0xf0f0f0f0f0f0f0f0) >> 4 | (uVar3 & 0xf0f0f0f0f0f0f0f) << 4;
    uVar3 = (uVar3 & 0xff00ff00ff00ff00) >> 8 | (uVar3 & 0xff00ff00ff00ff) << 8;
    uVar3 = (uVar3 & 0xffff0000ffff0000) >> 0x10 | (uVar3 & 0xffff0000ffff) << 0x10;
    uVar3 = LZCOUNT(uVar3 >> 0x20 | uVar3 << 0x20);
    uVar2 = uVar2 & (1L << (uVar3 & 0x3f) ^ 0xffffffffffffffffU);
    uVar4 = (short)uVar3 + uVar1 * 0x40;
    *(ulong *)(this->m_pSramVA[8] + (ulong)uVar1 * 8) = uVar2;
    if (uVar2 == 0) {
      popFromFreePtPool(this);
    }
  }
  return uVar4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cb9c
 * symbol: popFromFreePtPool
 * prototype: uint16_t popFromFreePtPool(MmControllerPipelineSramMetadata * this)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint16_t popFromFreePtPool(MmControllerPipelineSramMetadata * this) */

uint16_t __thiscall
A53::MMC::MmControllerPipelineSramMetadata::popFromFreePtPool
          (MmControllerPipelineSramMetadata *this)

{
  ushort uVar1;
  
  uVar1 = this->m_freePtPoolHead;
  if ((undefined *)(ulong)uVar1 != &DAT_00004cc8) {
    this->m_freePtPoolHead = *(uint16_t *)(this->m_pSramVA[9] + (long)(undefined *)(ulong)uVar1 * 2)
    ;
  }
  return uVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cbc0
 * symbol: deallocatePageTable
 * prototype: void deallocatePageTable(MmControllerPipelineSramMetadata * this, uint16_t ptPoolIndex)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void deallocatePageTable(MmControllerPipelineSramMetadata * this,
   uint16_t ptPoolIndex) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::deallocatePageTable
          (MmControllerPipelineSramMetadata *this,uint16_t ptPoolIndex)

{
  uint uVar1;
  ulong uVar2;
  
  uVar1 = ptPoolIndex >> 3 & 0x7f8;
  uVar2 = *(ulong *)(this->m_pSramVA[8] + (ulong)uVar1);
  *(ulong *)(this->m_pSramVA[8] + (ulong)uVar1) = uVar2 | 1L << ((ulong)ptPoolIndex & 0x3f);
  if (uVar2 != 0) {
    return;
  }
  *(uint16_t *)(this->m_pSramVA[9] + (ulong)ptPoolIndex * 2) = this->m_freePtPoolHead;
  this->m_freePtPoolHead = ptPoolIndex;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cc04
 * symbol: pushToFreePtPool
 * prototype: void pushToFreePtPool(MmControllerPipelineSramMetadata * this, uint16_t index)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void pushToFreePtPool(MmControllerPipelineSramMetadata * this, uint16_t
   index) */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::pushToFreePtPool
          (MmControllerPipelineSramMetadata *this,uint16_t index)

{
  *(uint16_t *)(this->m_pSramVA[9] + (ulong)index * 2) = this->m_freePtPoolHead;
  this->m_freePtPoolHead = index;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cc1c
 * symbol: isPageTableFree
 * prototype: bool isPageTableFree(MmControllerPipelineSramMetadata * this, uint16_t ptPoolIndex)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool isPageTableFree(MmControllerPipelineSramMetadata * this, uint16_t
   ptPoolIndex) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::isPageTableFree
          (MmControllerPipelineSramMetadata *this,uint16_t ptPoolIndex)

{
  return (1L << (ptPoolIndex & 0x3f) &
         *(ulong *)(this->m_pSramVA[8] + (ulong)(ptPoolIndex >> 3 & 0x7f8))) != 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cc44
 * symbol: checkList
 * prototype: bool checkList(MmControllerPipelineSramMetadata * this, LinkedList list, uint8_t paGroupIdx)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool checkList(MmControllerPipelineSramMetadata * this, LinkedList
   list, uint8_t paGroupIdx) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::checkList
          (MmControllerPipelineSramMetadata *this,LinkedList list,uint8_t paGroupIdx)

{
  byte bVar1;
  ushort *puVar2;
  
  puVar2 = (ushort *)this->m_pListRootSramVA[list];
  while( true ) {
    if ((ushort)this->m_pListPointersRootIndex[list] == *puVar2 >> 8) {
      return false;
    }
    bVar1 = (byte)(*puVar2 >> 8);
    if (bVar1 == paGroupIdx) break;
    puVar2 = (ushort *)(this->m_pListPointersSramVA[list] + (ulong)bVar1 * 2);
  }
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600cc94
 * symbol: updateCRC
 * prototype: void updateCRC(MmControllerPipelineSramMetadata * this, uint32_t pid)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void updateCRC(MmControllerPipelineSramMetadata * this, uint32_t pid)
    */

void __thiscall
A53::MMC::MmControllerPipelineSramMetadata::updateCRC
          (MmControllerPipelineSramMetadata *this,uint32_t pid)

{
  uint32_t uVar1;
  long lVar2;
  undefined4 *puVar3;
  int iVar4;
  
  lVar2 = 0;
  uVar1 = crc32w(0,pid,0x4c11db7);
  while ((int)lVar2 != 0xcc) {
    puVar3 = (undefined4 *)((long)this->m_pSramVA + lVar2);
    lVar2 = lVar2 + 4;
    uVar1 = crc32w(uVar1,*puVar3,0x4c11db7);
  }
  puVar3 = (undefined4 *)this->m_pSramVA[0];
  for (iVar4 = -0x6fae; iVar4 != 0; iVar4 = iVar4 + 1) {
    uVar1 = crc32w(uVar1,*puVar3,0x4c11db7);
    puVar3 = puVar3 + 1;
  }
  this->m_crc = uVar1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0600ccd8
 * symbol: checkCRC
 * prototype: bool checkCRC(MmControllerPipelineSramMetadata * this, uint32_t pid)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool checkCRC(MmControllerPipelineSramMetadata * this, uint32_t pid) */

bool __thiscall
A53::MMC::MmControllerPipelineSramMetadata::checkCRC
          (MmControllerPipelineSramMetadata *this,uint32_t pid)

{
  uint32_t uVar1;
  long lVar2;
  undefined4 *puVar3;
  int iVar4;
  
  lVar2 = 0;
  uVar1 = crc32w(0,pid,0x4c11db7);
  while ((int)lVar2 != 0xcc) {
    puVar3 = (undefined4 *)((long)this->m_pSramVA + lVar2);
    lVar2 = lVar2 + 4;
    uVar1 = crc32w(uVar1,*puVar3,0x4c11db7);
  }
  puVar3 = (undefined4 *)this->m_pSramVA[0];
  for (iVar4 = -0x6fae; iVar4 != 0; iVar4 = iVar4 + 1) {
    uVar1 = crc32w(uVar1,*puVar3,0x4c11db7);
    puVar3 = puVar3 + 1;
  }
  return this->m_crc == uVar1;
}


