/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/mm_controller\mm_controller_sram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060129cc
 * symbol: mm_controller_run
 * prototype: void mm_controller_run(void)
 * body addresses: 164
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void mm_controller_run(void)

{
  bool bVar1;
  MmController MStack_7f8;
  
  printf("mm_controller_run(): vaSramMmController=0x%08llx, vaSRAM_MmController_BootConfiguration=0x%08llx\n"
         ,0x40400c0,&core1_boot_config);
  A53::MMC::MmController::MmController(&MStack_7f8);
  printf("mm_controller_run(): pMmController->clear()\n");
  A53::MMC::MmController::clear(&MStack_7f8);
  printf("mm_controller_run(): pMmController->startup()\n");
  bVar1 = A53::MMC::MmController::startup(&MStack_7f8,0x4c00000);
  if (bVar1) {
    printf("mm_controller_run(): do { pMmController->execute() } while (true);\n");
    do {
      A53::MMC::MmController::execute(&MStack_7f8);
    } while( true );
  }
  printf("mm_controller_run(): pMmController->startup() failed!\n");
  printf("mm_controller_run(): pMmController->~MmController();\n");
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06012a70
 * symbol: mm_controller_sram
 * prototype: int mm_controller_sram(void)
 * body addresses: 300
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int mm_controller_sram(void)

{
  ulong uVar1;
  
  printf("%s()\n","mm_controller_sram");
  controller_sram();
  printf("========== MM bootconfig ===========\n");
  printf("m_addressInfo:\n");
  printf("\tm_appPageTableBasePA_2M: %lx # %lx\n",
         (ulong)(ushort)core1_boot_config.field_0.asU64[10]._0_2_,
         (ulong)(ushort)core1_boot_config.field_0.asU64[10]._0_2_ << 0x15);
  printf("\tm_gameBudgetPA_2M: %lx # %lx\n",(ulong)(ushort)core1_boot_config.field_0.asU64[10]._2_2_
         ,(ulong)(ushort)core1_boot_config.field_0.asU64[10]._2_2_ << 0x15);
  printf("\tm_mapperManagedVA_2M: %lx # %lx\n",
         (ulong)core1_boot_config.field_0.asU32[0x15] & 0xfffffff,
         ((ulong)core1_boot_config.field_0.asU32[0x15] & 0xfffffff) << 0x15);
  printf("\tm_mapperManagedVAEnd_2M: %lx # %lx\n",core1_boot_config.field_0.asU64[0xb] & 0xfffffff,
         (core1_boot_config.field_0.asU64[0xb] & 0xfffffff) << 0x15);
  uVar1 = core1_boot_config.field_0.asU64[0xb] >> 0x1c & 0xfffffff;
  printf("\tm_multimapApertureVA_2M: %lx # %lx\n",uVar1,uVar1 << 0x15);
  printf("\tm_multimapApertureVAEnd_2M: %lx # %lx\n",
         core1_boot_config.field_0.asU64[0xc] & 0xfffffff,
         (core1_boot_config.field_0.asU64[0xc] & 0xfffffff) << 0x15);
  printf("\tm_pidApp=%ld\n",(ulong)core1_boot_config.field_0.asU32[0x1a]);
  printf("\tm_pasidIndirect=%ld\n",(ulong)(ushort)core1_boot_config.field_0.asU64[0xd]._4_2_);
  printf("m_misc:\n");
  printf("\tm_offsetSmnIfSystemMmioIommu4K=0x%lx # 0x%lx\n",
         core1_boot_config.field_0.asU64[0xe] & 0x1fff,
         (core1_boot_config.field_0.asU64[0xe] & 0x1fff) << 0xc);
  mm_controller_run();
  return 0;
}


