/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/dram\a53_interrupt_context_ring__dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c530
 * symbol: pushElement<A53Controller_InterruptContextRingEntry>
 * prototype: uint32_t pushElement<A53Controller_InterruptContextRingEntry>(OutputRing * this, A53Controller_InterruptContextRingEntry * elem)
 * body addresses: 108
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t
   pushElement<A53Controller_InterruptContextRingEntry>(OutputRing * this,
   A53Controller_InterruptContextRingEntry * elem) */

uint32_t __thiscall
A53::OutputRing::pushElement<A53Controller_InterruptContextRingEntry>
          (OutputRing *this,A53Controller_InterruptContextRingEntry *elem)

{
  uint uVar1;
  bool bVar2;
  
  uVar1 = 1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f);
  bVar2 = (this->field_0).field_0.m_countDmaNotComplete < uVar1;
  if (bVar2) {
    storeElement<A53Controller_InterruptContextRingEntry>
              (this,(this->field_0).field_0.m_tail & uVar1 - 1,elem);
    advanceTail(this,1);
  }
  return (uint)bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c59c
 * symbol: storeElement<A53Controller_InterruptContextRingEntry>
 * prototype: void storeElement<A53Controller_InterruptContextRingEntry>(OutputRing * this, uint32_t iCacheElem, A53Controller_InterruptContextRingEntry * elem)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: void storeElement<A53Controller_InterruptContextRingEntry>(OutputRing *
   this, uint32_t iCacheElem, A53Controller_InterruptContextRingEntry * elem) */

void __thiscall
A53::OutputRing::storeElement<A53Controller_InterruptContextRingEntry>
          (OutputRing *this,uint32_t iCacheElem,A53Controller_InterruptContextRingEntry *elem)

{
  uint64_t *puVar1;
  uint64_t uVar2;
  uint64_t uVar3;
  uint64_t uVar4;
  uint64_t *pDst;
  
  uVar3 = (elem->field_0).asU64[1];
  puVar1 = (uint64_t *)
           ((this->field_0).field_0.m_vaSramCache +
           (ulong)(iCacheElem << (ulong)((this->field_0).field_0.m_sizeofElemLog2 & 0x1f)));
  uVar2 = (elem->field_0).asAppKernelEventFlag.m_bitPattern;
  uVar4 = (elem->field_0).asAppKernelEventQueue.m_udata;
  *puVar1 = (elem->field_0).asU64[0];
  puVar1[1] = uVar3;
  puVar1[2] = uVar2;
  puVar1[3] = uVar4;
  return;
}


