/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/dram\a53_controller_rings_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605b814
 * symbol: getNumRingElemsAvailableToWrite
 * prototype: uint32_t getNumRingElemsAvailableToWrite(OutputRing * this)
 * body addresses: 40
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint32_t getNumRingElemsAvailableToWrite(OutputRing * this) */

uint32_t __thiscall A53::OutputRing::getNumRingElemsAvailableToWrite(OutputRing *this)

{
  return (((1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f)) + -1) -
         (this->field_0).field_0.m_count) +
         (1 << (ulong)((this->field_0).field_0.m_numCacheElemsLog2 & 0x1f));
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605ba60
 * symbol: discardHeadCommand
 * prototype: bool discardHeadCommand(PtdmaVqState * this, uint32_t * out_discard_start_lo, uint32_t * out_discard_end_lo)
 * body addresses: 184
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool discardHeadCommand(PtdmaVqState * this, uint32_t *
   out_discard_start_lo, uint32_t * out_discard_end_lo) */

bool __thiscall
A53::PtdmaVqState::discardHeadCommand
          (PtdmaVqState *this,uint32_t *out_discard_start_lo,uint32_t *out_discard_end_lo)

{
  uint uVar1;
  byte bVar2;
  bool bVar3;
  uint uVar4;
  ulong uVar5;
  long lVar6;
  
  uVar5 = (ulong)(this->m_submit).m_iVq;
  if ((*(uint *)(&DAT_022c1000 + uVar5 * 0x1000) >> 1 & 1) == 0) {
    bVar3 = false;
  }
  else {
    lVar6 = uVar5 * 0x1000;
    this->m_tail_lo = *(uint32_t *)(lVar6 + 0x22c1004);
    uVar4 = *(uint *)(lVar6 + 0x22c1008) & 0x7fffffff;
    this->m_head_lo = uVar4;
    *out_discard_start_lo = uVar4;
    uVar4 = this->m_head_lo;
    if (uVar4 != this->m_tail_lo) {
      uVar1 = (this->m_submit).m_maskVqdPointer;
      bVar2 = (this->m_submit).m_iVq;
      uVar4 = uVar1 & uVar4 + 0x20 | uVar4 & (uVar1 ^ 0xffffffff);
      this->m_head_lo = uVar4;
      *(uint *)((ulong)bVar2 * 0x1000 + 0x22c1008) = uVar4 & 0x7fffffff;
      *(uint32_t *)((ulong)(this->m_submit).m_iVq * 0x1000 + 0x22c1014) = this->m_head_lo;
      uVar4 = this->m_head_lo;
    }
    *out_discard_end_lo = uVar4;
    bVar3 = true;
    (this->m_submit).m_numCommandsAvailable =
         (uint16_t)
         (((this->m_head_lo - (this->m_submit).m_offsetPut) + 0x1fffe0 &
          (this->m_submit).m_maskVqdPointer) >> 5);
  }
  return bVar3;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605bb18
 * symbol: restartBegin
 * prototype: bool restartBegin(PtdmaVqState * this)
 * body addresses: 80
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool restartBegin(PtdmaVqState * this) */

bool __thiscall A53::PtdmaVqState::restartBegin(PtdmaVqState *this)

{
  long lVar1;
  
  lVar1 = (ulong)(this->m_submit).m_iVq * 0x1000;
  if ((*(uint *)(&DAT_022c1000 + lVar1) >> 1 & 1) == 0) {
    return false;
  }
  *(uint32_t *)(lVar1 + 0x22c1004) = this->m_head_lo;
  lVar1 = (ulong)(this->m_submit).m_iVq * 0x1000;
  *(uint *)(&DAT_022c1000 + lVar1) = *(uint *)(&DAT_022c1000 + lVar1) & 0xffff0078 | 1;
  return true;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605bb68
 * symbol: restartEnd
 * prototype: bool restartEnd(PtdmaVqState * this)
 * body addresses: 52
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool restartEnd(PtdmaVqState * this) */

bool __thiscall A53::PtdmaVqState::restartEnd(PtdmaVqState *this)

{
  long lVar1;
  
  lVar1 = (ulong)(this->m_submit).m_iVq * 0x1000;
  if ((*(uint *)(&DAT_022c1000 + lVar1) >> 1 & 1) == 0) {
    *(uint32_t *)(lVar1 + 0x22c1004) = this->m_tail_lo;
    return true;
  }
  return false;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c034
 * symbol: getPaRingElementBackwardFromTail
 * prototype: uint64_t getPaRingElementBackwardFromTail(OutputRing * this, uint32_t indexBeforeTail)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: uint64_t getPaRingElementBackwardFromTail(OutputRing * this, uint32_t
   indexBeforeTail) */

uint64_t __thiscall
A53::OutputRing::getPaRingElementBackwardFromTail(OutputRing *this,uint32_t indexBeforeTail)

{
  return ((ulong)((1 << (ulong)((this->field_0).field_0.m_numRingElemsLog2 & 0x1f)) - 1U &
                 (this->field_0).field_0.m_tail - indexBeforeTail) <<
         ((ulong)(this->field_0).field_0.m_sizeofElemLog2 & 0x3f)) +
         (this->field_0).field_0.m_paRing;
}


