/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/dram\a53_controller_pipeline_common_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06059ffc
 * symbol: discardOverFetch
 * prototype: bool discardOverFetch(InputIndirectBuffer * this, uint32_t numElems)
 * body addresses: 56
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool discardOverFetch(InputIndirectBuffer * this, uint32_t numElems) */

bool __thiscall
A53::InputIndirectBuffer::discardOverFetch(InputIndirectBuffer *this,uint32_t numElems)

{
  ushort uVar1;
  bool bVar2;
  
  uVar1 = (this->field_0).field_0.m_countDmaComplete;
  bVar2 = numElems <= uVar1;
  if (bVar2) {
    (this->field_0).field_0.m_countDmaComplete = uVar1 - (short)numElems;
    (this->field_0).field_0.m_head = (this->field_0).field_0.m_numBufferElems;
    (this->field_0).field_0.m_countDmaIssued =
         (this->field_0).field_0.m_countDmaIssued - (short)numElems;
  }
  return bVar2;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605a334
 * symbol: canWriteElementsWrapped
 * prototype: bool canWriteElementsWrapped(SramRingView * this, uint32_t ringLocationStart, uint32_t numElems)
 * body addresses: 116
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* DWARF original prototype: bool canWriteElementsWrapped(SramRingView * this, uint32_t
   ringLocationStart, uint32_t numElems) */

bool __thiscall
A53::SramRingView::canWriteElementsWrapped
          (SramRingView *this,uint32_t ringLocationStart,uint32_t numElems)

{
  uint uVar1;
  uint uVar2;
  ulong uVar3;
  uint uVar4;
  
  uVar3 = *(ulong *)((long)&(this->super_ConstSramRingView).field_0 + 4);
  uVar1 = (uint)(uVar3 >> 0x20);
  uVar2 = (uint)uVar3;
  if ((uVar3 >> 0x33 & 0x1f) == 0) {
    uVar4 = (uVar2 & 0xffff) + 1;
    if ((uVar2 & 0xffff) < ringLocationStart || uVar4 < numElems) {
      return false;
    }
    if (((uint)(uVar3 >> 0x10) & 0xffff) <= ringLocationStart) {
      uVar4 = 0;
    }
    uVar4 = (ringLocationStart - (uVar2 >> 0x10)) + uVar4;
  }
  else {
    uVar4 = (1 << (ulong)(uVar1 >> 0x13 & 0x1f)) - 1U & ringLocationStart - (uVar2 >> 0x10);
    if ((uVar1 & 0x1ffff) <= uVar4) {
      return false;
    }
  }
  return uVar4 + numElems <= (uVar1 & 0x1ffff);
}


