/*
 * A53-RE recovered compilation unit.
 * Original path: I:/a53_sys/releases_00.70/mp4/a53/src/controller/dram\controller_dram.cpp
 * Language recorded in DWARF: C++
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605c7e0
 * symbol: A53Controller_BootConfiguration_KernelShared_show
 * prototype: void A53Controller_BootConfiguration_KernelShared_show(A53Controller_BootConfiguration_KernelShared * ks)
 * body addresses: 952
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53Controller_BootConfiguration_KernelShared_show
               (A53Controller_BootConfiguration_KernelShared *ks)

{
  uint uVar1;
  
  printf("%s()\n","A53Controller_BootConfiguration_KernelShared_show");
  printf("m_vaPaDebug4K   = 0x%09llx\n",(ks->field_0).asU64[0] & 0xfffffffff);
  printf("m_sizePaDebug4K = 0x%03llx\n",(ks->field_0).asU64[0] >> 0x24 & 0xfff);
  printf("m_pasidPaDebug  = 0x%04llx\n",(ulong)*(ushort *)((long)&ks->field_0 + 6));
  printf("m_sysvaRings    = 0x%012llx\n",(ks->field_0).asU64[1] & 0xffffffffffff);
  printf("m_pasidKernel   = 0x%04llx\n",(ulong)*(ushort *)((long)&ks->field_0 + 0xe));
  printf("m_sizeRings     = 0x%06llx\n",(ulong)((ks->field_0).asU32[4] & 0xffffff));
  printf("m_sizeInterruptContextRingLog2Minus1 = 0x%llx\n",
         (ulong)(*(byte *)((long)&ks->field_0 + 0x13) & 0xf));
  printf("m_sizeInputRing0Log2Minus1           = 0x%llx\n",(ks->field_0).asU32[4] >> 0x1c);
  printf("m_sizeInputRing1Log2Minus1           = 0x%llx\n",(ulong)((ks->field_0).asU32[5] & 0xf));
  printf("m_sizeInputRing2Log2Minus1           = 0x%llx\n",(ks->field_0).asU64[2] >> 0x24 & 0xf);
  printf("m_sizeInputRing3Log2Minus1           = 0x%llx\n",(ks->field_0).asU64[2] >> 0x28 & 0xf);
  printf("m_sizeInputRing4Log2Minus1           = 0x%llx\n",(ks->field_0).asU64[2] >> 0x2c & 0xf);
  printf("m_sizeInputRing5Log2Minus1           = 0x%llx\n",
         (ulong)(*(uint *)((long)&ks->field_0 + 0x16) & 0xf));
  printf("m_sizeInputRing6Log2Minus1           = 0x%llx\n",(ks->field_0).asU64[2] >> 0x34 & 0xf);
  printf("m_sizeInputRing7Log2Minus1           = 0x%llx\n",
         (ulong)(*(uint *)((long)&ks->field_0 + 0x17) & 0xf));
  printf("m_sizeInputRing8Log2Minus1           = 0x%llx\n",(ks->field_0).asU64[2] >> 0x3c);
  printf("m_sizeInputRing9Log2Minus1           = 0x%llx\n",(ulong)((ks->field_0).asU32[6] & 0xf));
  printf("m_sizeInputRing10Log2Minus1          = 0x%llx\n",
         (ulong)((ks->field_0).asU32[6] >> 4 & 0xf));
  printf("m_sizeInputRing11Log2Minus1          = 0x%llx\n",
         (ulong)((ks->field_0).asU32[6] >> 8 & 0xf));
  printf("m_sizeInputRing12Log2Minus1          = 0x%llx\n",
         (ulong)((ks->field_0).asU32[6] >> 0xc & 0xf));
  printf("m_sizeInputRing13Log2Minus1          = 0x%llx\n",
         (ulong)(*(ushort *)((long)&ks->field_0 + 0x1a) & 0xf));
  printf("m_sizeInputRing14Log2Minus1          = 0x%llx\n",
         (ulong)((ks->field_0).asU32[6] >> 0x14 & 0xf));
  printf("m_sizeInputRing15Log2Minus1          = 0x%llx\n",
         (ulong)(*(byte *)((long)&ks->field_0 + 0x1b) & 0xf));
  printf("m_sizeInputRing16Log2Minus1          = 0x%llx\n",(ks->field_0).asU32[6] >> 0x1c);
  printf("m_sizeInputRing17Log2Minus1          = 0x%llx\n",(ulong)((ks->field_0).asU32[7] & 0xf));
  printf("m_sizeInputRing18Log2Minus1          = 0x%llx\n",(ks->field_0).asU64[3] >> 0x24 & 0xf);
  printf("m_sizeInputRing19Log2Minus1          = 0x%llx\n",(ks->field_0).asU64[3] >> 0x28 & 0xf);
  printf("m_sizeInputRing20Log2Minus1          = 0x%llx\n",(ks->field_0).asU64[3] >> 0x2c & 0xf);
  printf("m_sizeInputRing21Log2Minus1          = 0x%llx\n",
         (ulong)(*(ushort *)((long)&ks->field_0 + 0x1e) & 0xf));
  printf("RESERVED BITS[244:245]               = 0x%llx\n",(ks->field_0).asU64[3] >> 0x34 & 3);
  printf("m_sizeOutputRing1Log2Minus1          = 0x%02llx\n",(ks->field_0).asU64[3] >> 0x36 & 0x1f);
  printf("m_sizeOutputRing2Log2Minus1          = 0x%02llx\n",(ks->field_0).asU64[3] >> 0x3b);
  printf("m_bootParams                     = 0x%08llx\n",(ulong)(ks->field_0).asU32[8]);
  printf("m_msiInterrupt                   = 0x%02llx\n",(ulong)*(byte *)((long)&ks->field_0 + 0x24)
        );
  printf("RESERVED BITS[296:299]           = 0x%01llx\n",(ks->field_0).asU64[4] >> 0x28 & 0xf);
  printf("m_offsetSyshubIfSystemMmioMsi4K  = 0x%05llx (PA:0x%08llx)\n",
         (ks->field_0).asU64[4] >> 0x2c,
         ((long)(ks->field_0).asU64[4] >> 0x20) + 0x4000000U & 0xfffffffffffff000);
  uVar1 = (uint)(ks->field_0).asU64[5];
  if ((uVar1 >> 0x17 & 1) == 0) {
    printf("m_offsetSyshubIfSystemMmioSdma4K = 0x%05llx (PA:0x%08llx)\n",(ulong)(uVar1 & 0xfffff),
           ((long)((ks->field_0).asU64[5] << 0x2c) >> 0x20) + 0x4000000);
    printf("RESERVED BITS[340:342]           = 0x%llx\n",(ks->field_0).asU64[5] >> 0x14 & 7);
  }
  else {
    uVar1 = (ks->field_0).asU32[10] & 0x7fffff;
    printf("m_offsetSmnIfSystemMmioSdma4B    = 0x%06llx (PA:0x%08llx)\n",(ulong)uVar1,
           (ulong)(uVar1 * 4 + 0x1000000));
  }
  printf("m_useSmnIfForSdma                = 0x%llx\n",(ulong)((ks->field_0).asU32[10] >> 0x17 & 1))
  ;
  printf("RESERVED BITS[344:347]           = 0x%llx\n",(ks->field_0).asU64[5] >> 0x18 & 0xf);
  printf("m_sysvaKernelStart4K             = 0x%09llx\n",(ks->field_0).asU64[5] >> 0x1c);
  printf("m_sysvaKernelEnd4K               = 0x%09llx\n",(ks->field_0).asU64[6] & 0xfffffffff);
  printf("RESERVED BITS[420:447]           = 0x%07llx\n",(ks->field_0).asU64[6] >> 0x24);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605cb98
 * symbol: A53Controller_BootConfiguration_PrivateDram_print
 * prototype: void A53Controller_BootConfiguration_PrivateDram_print(A53Controller_BootConfiguration_PrivateDram * pd)
 * body addresses: 148
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53Controller_BootConfiguration_PrivateDram_print
               (A53Controller_BootConfiguration_PrivateDram *pd)

{
  printf("%s()\n","A53Controller_BootConfiguration_PrivateDram_print");
  printf("m_offsetSyshubIfDramPrivateReadOnly4K = 0x%05llx (PA:0x%08llx)\n",
         (ulong)((pd->field_0).asU32[0] & 0xfffff),
         (long)(int)((pd->field_0).asU32[0] << 0xc) + 0x4000000);
  printf("m_sizeDramPrivateReadOnly4K           = 0x%03llx\n",(pd->field_0).asU32[0] >> 0x14);
  printf("m_offsetSyshubIfDramPrivate4K         = 0x%05llx (PA:0x%08llx)\n",
         (pd->field_0).asU64[0] >> 0x20 & 0xfffff,
         ((long)(((pd->field_0).asU64[0] >> 0x20) << 0x2c) >> 0x20) + 0x4000000);
  printf("m_sizeDramPrivate4K                   = 0x%03llx\n",(pd->field_0).asU64[0] >> 0x34);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605cc2c
 * symbol: A53Controller_BootConfiguration_ASLR_print
 * prototype: void A53Controller_BootConfiguration_ASLR_print(A53Controller_BootConfiguration_ASLR * aslr)
 * body addresses: 284
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void A53Controller_BootConfiguration_ASLR_print(A53Controller_BootConfiguration_ASLR *aslr)

{
  printf("%s\n","A53Controller_BootConfiguration_ASLR_print");
  printf("m_vaHeap4K         = 0x%04llx\n",(ulong)*(ushort *)&aslr->field_0);
  printf("m_vaSharedHeap4K   = 0x%04llx\n",(ulong)*(ushort *)((long)&aslr->field_0 + 2));
  printf("m_vaSwapCode4K     = 0x%04llx\n",(ulong)*(ushort *)((long)&aslr->field_0 + 4));
  printf("m_vaStack4K        = 0x%04llx\n",(ulong)*(ushort *)((long)&aslr->field_0 + 6));
  printf("m_vaFixedCode4K    = 0x%04llx\n",(ulong)*(ushort *)((long)&aslr->field_0 + 8));
  printf("m_sizeHeap4K       = 0x%02llx\n",(ulong)(*(ushort *)((long)&aslr->field_0 + 10) & 0x7f));
  printf("m_sizeSharedHeap4K = 0x%01llx\n",(ulong)((aslr->field_0).asU32[2] >> 0x17 & 0xf));
  printf("m_sizeStack4K      = 0x%01llx\n",(ulong)((aslr->field_0).asU32[2] >> 0x1b & 0xf));
  printf("m_sizeSwapCode4K   = 0x%02llx\n",(aslr->field_0).asU64[1] >> 0x1f & 0x3f);
  printf("m_sizeFixedCode4K  = 0x%02llx\n",(aslr->field_0).asU64[1] >> 0x25 & 0x3f);
  printf("m_paHeap4K         = 0x%02llx\n",(aslr->field_0).asU64[1] >> 0x2b & 0x7f);
  printf("m_paSharedHeap4K   = 0x%02llx\n",(aslr->field_0).asU64[1] >> 0x32 & 0x7f);
  printf("m_paSwapCode4K     = 0x%02llx\n",(aslr->field_0).asU64[1] >> 0x39);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0605cd48
 * symbol: controller_dram
 * prototype: int controller_dram(void)
 * body addresses: 68
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int controller_dram(void)

{
  printf("controller_dram() %p\n","controller_dram");
  printf("%s()\n","controller_dram");
  return 0;
}


