/*
 * A53-RE recovered compilation unit.
 * Original path: I:\a53_sys\releases_00.70\mp4\a53\src\loader\reset\sram.c
 * Language recorded in DWARF: C
 * Function bodies below are generated semantic recovery artifacts.
 * They are intentionally kept separate from hand-validated source.
 */

/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606778c
 * symbol: putchar_el3_sram_core
 * prototype: int putchar_el3_sram_core(int c)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: c_local */

int putchar_el3_sram_core(int c)

{
  uint32_t uVar1;
  uint32_t *base;
  undefined4 in_stack_ffffffffffffffe8;
  int c_local;
  
  do {
    uVar1 = uart_get_stat((uint32_t *)CONCAT44(c,in_stack_ffffffffffffffe8));
  } while ((uVar1 >> 0xb & 1) != 0);
  uart_set_data((uint32_t *)CONCAT44(c,in_stack_ffffffffffffffe8),0);
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060677d4
 * symbol: uart_get_stat
 * prototype: uint32_t uart_get_stat(uint32_t * base)
 * body addresses: 24
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t uart_get_stat(uint32_t *base)

{
  long in_x0;
  
  return *(uint32_t *)(in_x0 + 0xc);
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060677ec
 * symbol: uart_set_data
 * prototype: void uart_set_data(uint32_t * base, int data)
 * body addresses: 36
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void uart_set_data(uint32_t *base,int data)

{
  long in_x0;
  uint in_w1;
  
  *(uint *)(in_x0 + 4) = in_w1 & 0xff;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06067810
 * symbol: putchar_el3_sram
 * prototype: int putchar_el3_sram(int c)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: c_local */

int putchar_el3_sram(int c)

{
  int c_local;
  
  if (c == 10) {
    putchar_el3_sram_core(0xd);
  }
  putchar_el3_sram_core(c);
  return c;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06067858
 * symbol: puts_el3_sram
 * prototype: int puts_el3_sram(char * s0)
 * body addresses: 136
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: s0_local */

int puts_el3_sram(char *s0)

{
  byte bVar1;
  int c;
  int n;
  char *s;
  int local_24;
  byte *local_20;
  char *s0_local;
  
  local_24 = 0;
  for (local_20 = (byte *)s0; *local_20 != 0; local_20 = local_20 + 1) {
    bVar1 = *local_20;
    if (bVar1 == 10) {
      putchar_el3_sram_core(0xd);
    }
    putchar_el3_sram_core((uint)bVar1);
    local_24 = local_24 + 1;
  }
  return local_24;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060678e0
 * symbol: strnlen_el3_sram
 * prototype: size_t strnlen_el3_sram(char * s, size_t maxlen)
 * body addresses: 88
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

size_t strnlen_el3_sram(char *s,size_t maxlen)

{
  char *in_x0;
  ulong in_x1;
  size_t n;
  ulong local_18;
  char *local_8;
  
  local_18 = 0;
  for (local_8 = in_x0; (local_18 < in_x1 && (*local_8 != '\0')); local_8 = local_8 + 1) {
    local_18 = local_18 + 1;
  }
  return local_18;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06067938
 * symbol: printf_el3_sram
 * prototype: int printf_el3_sram(char * format, ...)
 * body addresses: 156
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: r */
/* WARNING: Variable defined which should be unmapped: format_local */

int printf_el3_sram(char *format,...)

{
  int iVar1;
  va_list local_60;
  va_list ap;
  int r;
  char *format_local;
  
  local_60.__gr_top = &local_60;
  local_60.__gr_offs = -0x38;
  local_60.__vr_offs = 0;
  local_60.__stack = register0x00000008;
  iVar1 = prnt_el3_sram(putchar_el3_sram_hook,(void *)0x0,format,&local_60);
  return iVar1;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060679d4
 * symbol: prnt_el3_sram
 * prototype: int prnt_el3_sram(prnt_putchar_handler_t pf, void * pfd, char * fmt0, va_list * argp)
 * body addresses: 4708
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: pf_local */

int prnt_el3_sram(prnt_putchar_handler_t pf,void *pfd,char *fmt0,va_list *argp)

{
  byte *pbVar1;
  int iVar2;
  byte bVar3;
  ulong uVar4;
  bool bVar5;
  bool bVar6;
  bool bVar7;
  bool bVar8;
  uint uVar9;
  size_t sVar10;
  char *pcVar11;
  ulong uVar12;
  int local_2d0;
  int local_2cc;
  undefined8 in_stack_fffffffffffffd38;
  int *in_stack_fffffffffffffd40;
  undefined4 in_stack_fffffffffffffd48;
  int in_stack_fffffffffffffd4c;
  ulong local_2a8;
  ulong *local_2a0;
  ulong *local_288;
  int *local_270;
  ulong local_258;
  ulong *local_250;
  ulong *local_238;
  ulonglong *local_208;
  ulong *local_1f0;
  int *local_1d8;
  ulong local_1c0;
  ulong *local_1b8;
  ulong *local_1a0;
  int *local_188;
  ulong local_170;
  ulong *local_168;
  ulong *local_150;
  undefined4 *local_138;
  int local_118;
  int *local_110;
  int *local_f8;
  undefined local_c0 [16];
  char buf [21];
  char *digs;
  char sign;
  int width;
  int size;
  int realsz;
  int prec;
  int fpprec;
  int flags;
  int fieldsz;
  int dprec;
  uint base;
  ulonglong _ulonglong;
  ulong _ulong;
  char *t;
  char *tt;
  byte *pbStack_48;
  int n;
  int cnt;
  int ch;
  char *fmt;
  char *fmt0_local;
  void *pfd_local;
  prnt_putchar_handler_t pf_local;
  
  _dprec = 0;
  _flags = 0;
  if (fmt0 == (char *)0x0) {
    puts_el3_sram("fmt0 is NULL\n");
    pfd_local._4_4_ = 0;
  }
  else {
    buf._8_8_ = s_0123456789abcdef_0011d371;
    (*pf)(pfd,0x200);
    tt._0_4_ = 0;
    for (pbStack_48 = (byte *)fmt0; bVar3 = *pbStack_48, bVar3 != 0; pbStack_48 = pbStack_48 + 1) {
      if (bVar3 == 0x25) {
        size = 0;
        bVar7 = false;
        bVar6 = false;
        bVar5 = false;
        prec = 0;
        width = 0;
        stack0xffffffffffffff64 = 0;
        _sign = -1;
        buf[0x10] = '\0';
        t._4_4_ = stack0xffffffffffffff64;
LAB_06067ac0:
        stack0xffffffffffffff64 = t._4_4_;
        bVar8 = false;
        pbVar1 = pbStack_48 + 1;
        t._4_4_ = stack0xffffffffffffff64;
        switch(pbStack_48[1]) {
        case 0:
          (*pf)(pfd,0x201);
          return (int)tt;
        default:
          (*pf)(pfd,(int)*pbVar1);
          tt._0_4_ = (int)tt + 1;
          pbStack_48 = pbVar1;
          break;
        case 0x20:
          pbStack_48 = pbVar1;
          if (buf[0x10] == '\0') {
            buf[0x10] = ' ';
          }
          goto LAB_06067ac0;
        case 0x23:
          bVar7 = true;
          pbStack_48 = pbVar1;
          goto LAB_06067ac0;
        case 0x2a:
          iVar2 = argp->__gr_offs;
          if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
            local_f8 = (int *)((long)argp->__gr_top + (long)iVar2);
          }
          else {
            local_f8 = (int *)argp->__stack;
            argp->__stack = local_f8 + 2;
          }
          t._4_4_ = *local_f8;
          pbStack_48 = pbVar1;
          if (-1 < t._4_4_) goto LAB_06067ac0;
          unique0x100000dc = -t._4_4_;
        case 0x2d:
          size = size | 0x10;
          t._4_4_ = stack0xffffffffffffff64;
          pbStack_48 = pbVar1;
          goto LAB_06067ac0;
        case 0x2b:
          buf[0x10] = '+';
          pbStack_48 = pbVar1;
          goto LAB_06067ac0;
        case 0x2e:
          if (pbStack_48[2] == 0x2a) {
            iVar2 = argp->__gr_offs;
            if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
              local_110 = (int *)((long)argp->__gr_top + (long)iVar2);
            }
            else {
              local_110 = (int *)argp->__stack;
              argp->__stack = local_110 + 2;
            }
            t._4_4_ = *local_110;
            pbStack_48 = pbStack_48 + 2;
          }
          else {
            t._4_4_ = 0;
            pbStack_48 = pbStack_48 + 2;
            while( true ) {
              bVar8 = false;
              if (*pbStack_48 < 0x80) {
                uVar9 = sram_sceMp4LookCtypeTable((uint)in_stack_fffffffffffffd38);
                bVar8 = (uVar9 & 4) != 0;
              }
              if (!bVar8) break;
              t._4_4_ = t._4_4_ * 10 + (*pbStack_48 - 0x30);
              pbStack_48 = pbStack_48 + 1;
            }
            pbStack_48 = pbStack_48 + -1;
          }
          if (t._4_4_ < 0) {
            local_118 = -1;
          }
          else {
            local_118 = t._4_4_;
          }
          _sign = local_118;
          t._4_4_ = stack0xffffffffffffff64;
          goto LAB_06067ac0;
        case 0x30:
          size = size | 0x20;
          pbStack_48 = pbVar1;
          goto LAB_06067ac0;
        case 0x31:
        case 0x32:
        case 0x33:
        case 0x34:
        case 0x35:
        case 0x36:
        case 0x37:
        case 0x38:
        case 0x39:
          t._4_4_ = 0;
          do {
            pbStack_48 = pbVar1;
            t._4_4_ = t._4_4_ * 10 + (*pbStack_48 - 0x30);
            bVar8 = false;
            if (pbStack_48[1] < 0x80) {
              uVar9 = sram_sceMp4LookCtypeTable((uint)in_stack_fffffffffffffd38);
              bVar8 = (uVar9 & 4) != 0;
            }
            pbVar1 = pbStack_48 + 1;
          } while (bVar8);
          goto LAB_06067ac0;
        case 0x44:
          bVar5 = true;
        case 100:
        case 0x69:
          fpprec = 10;
          if (bVar6) {
            iVar2 = argp->__gr_offs;
            if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
              local_150 = (ulong *)((long)argp->__gr_top + (long)iVar2);
            }
            else {
              local_150 = (ulong *)argp->__stack;
              argp->__stack = local_150 + 1;
            }
            _flags = *local_150;
            if ((long)_flags < 0) {
              _flags = -_flags;
              buf[0x10] = '-';
            }
LAB_06068860:
            prec = _sign;
            if (-1 < _sign) {
              size = size & 0xffffffdf;
            }
            pcVar11 = buf + 5;
            if ((_flags != 0) || (_sign != 0)) {
              do {
                _ulong = (ulong)pcVar11;
                uVar12 = (ulong)(uint)fpprec;
                uVar4 = 0;
                if (uVar12 != 0) {
                  uVar4 = _flags / uVar12;
                }
                pcVar11 = (char *)(_ulong - 1);
                *(undefined *)(_ulong - 1) = *(undefined *)(buf._8_8_ + (_flags - uVar4 * uVar12));
                uVar4 = 0;
                if ((ulong)(uint)fpprec != 0) {
                  uVar4 = _flags / (uint)fpprec;
                }
                _flags = uVar4;
              } while (uVar4 != 0);
              buf._8_8_ = s_0123456789abcdef_0011d371;
              if (((bVar7) && (fpprec == 8)) && (*pcVar11 != '0')) {
                *(undefined *)(_ulong - 2) = 0x30;
                pcVar11 = (char *)(_ulong - 2);
              }
            }
            _ulong = (ulong)pcVar11;
            _ulonglong = _ulong;
            digs._0_4_ = ((int)&stack0xfffffffffffffff0 + -0x9b) - (int)_ulong;
          }
          else {
            if (bVar5) {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_168 = (ulong *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_168 = (ulong *)argp->__stack;
                argp->__stack = local_168 + 1;
              }
              local_170 = *local_168;
            }
            else {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_188 = (int *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_188 = (int *)argp->__stack;
                argp->__stack = local_188 + 2;
              }
              local_170 = (ulong)*local_188;
            }
            _dprec = local_170;
            if ((long)local_170 < 0) {
              _dprec = -local_170;
              buf[0x10] = '-';
            }
LAB_06068684:
            prec = _sign;
            if (-1 < _sign) {
              size = size & 0xffffffdf;
            }
            _ulong = (ulong)(buf + 5);
            if ((_dprec != 0) || (_sign != 0)) {
              do {
                uVar4 = _ulong;
                if (fpprec == 8) {
                  *(undefined *)(_ulong - 1) = *(undefined *)(buf._8_8_ + (_dprec & 7));
                  uVar12 = _dprec >> 3;
                }
                else if (fpprec == 10) {
                  *(undefined *)(_ulong - 1) = *(undefined *)(buf._8_8_ + _dprec % 10);
                  in_stack_fffffffffffffd38 = 10;
                  uVar12 = _dprec / 10;
                }
                else if (fpprec == 0x10) {
                  *(undefined *)(_ulong - 1) = *(undefined *)(buf._8_8_ + (_dprec & 0xf));
                  uVar12 = _dprec >> 4;
                }
                else {
                  *(undefined *)(_ulong - 1) = *(undefined *)(buf._8_8_ + (_dprec & fpprec - 1));
                  uVar12 = 0;
                  if ((ulong)(uint)fpprec != 0) {
                    uVar12 = _dprec / (uint)fpprec;
                  }
                }
                _dprec = uVar12;
                _ulong = _ulong - 1;
              } while (_dprec != 0);
              buf._8_8_ = s_0123456789abcdef_0011d371;
              if (((bVar7) && (fpprec == 8)) && (*(char *)_ulong != '0')) {
                _ulong = uVar4 - 2;
                *(undefined *)(uVar4 - 2) = 0x30;
              }
            }
            _ulonglong = _ulong;
            digs._0_4_ = ((int)&stack0xfffffffffffffff0 + -0x9b) - (int)_ulong;
          }
LAB_0606894c:
          realsz = (int)digs;
          if (buf[0x10] != '\0') {
            realsz = (int)digs + 1;
          }
          if (bVar8) {
            realsz = realsz + 2;
          }
          if (realsz < prec) {
            local_2cc = prec;
          }
          else {
            local_2cc = realsz;
          }
          if (((size & 0x30U) == 0) && (stack0xffffffffffffff64 != 0)) {
            for (t._4_4_ = local_2cc; t._4_4_ < stack0xffffffffffffff64; t._4_4_ = t._4_4_ + 1) {
              (*pf)(pfd,0x20);
            }
          }
          if (buf[0x10] != '\0') {
            (*pf)(pfd,(int)buf[0x10]);
          }
          if (bVar8) {
            (*pf)(pfd,0x30);
            if (*pbVar1 == 0x70) {
              (*pf)(pfd,0x78);
            }
            else {
              (*pf)(pfd,(int)*pbVar1);
            }
          }
          if ((size & 0x30U) == 0x20) {
            for (t._4_4_ = local_2cc; t._4_4_ < stack0xffffffffffffff64; t._4_4_ = t._4_4_ + 1) {
              (*pf)(pfd,0x30);
            }
          }
          for (t._4_4_ = realsz; t._4_4_ < prec; t._4_4_ = t._4_4_ + 1) {
            (*pf)(pfd,0x30);
          }
          t._4_4_ = (int)digs;
          while (t._4_4_ = t._4_4_ + -1, -1 < t._4_4_) {
            (*pf)(pfd,(int)*(undefined *)_ulonglong);
            _ulonglong = _ulonglong + 1;
          }
          while (width = width + -1, -1 < width) {
            (*pf)(pfd,0x30);
          }
          if (((uint)size >> 4 & 1) != 0) {
            for (t._4_4_ = local_2cc; t._4_4_ < stack0xffffffffffffff64; t._4_4_ = t._4_4_ + 1) {
              (*pf)(pfd,0x20);
            }
          }
          if (local_2cc < stack0xffffffffffffff64) {
            local_2d0 = stack0xffffffffffffff64;
          }
          else {
            local_2d0 = local_2cc;
          }
          tt._0_4_ = (int)tt + local_2d0;
          pbStack_48 = pbVar1;
          break;
        case 0x4c:
          bVar6 = true;
          pbStack_48 = pbVar1;
          goto LAB_06067ac0;
        case 0x4f:
          bVar5 = true;
        case 0x6f:
          fpprec = 8;
          if (bVar6) {
            iVar2 = argp->__gr_offs;
            if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
              local_1a0 = (ulong *)((long)argp->__gr_top + (long)iVar2);
            }
            else {
              local_1a0 = (ulong *)argp->__stack;
              argp->__stack = local_1a0 + 1;
            }
            _flags = *local_1a0;
          }
          else {
            if (bVar5) {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_1b8 = (ulong *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_1b8 = (ulong *)argp->__stack;
                argp->__stack = local_1b8 + 1;
              }
              local_1c0 = *local_1b8;
            }
            else {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_1d8 = (int *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_1d8 = (int *)argp->__stack;
                argp->__stack = local_1d8 + 2;
              }
              local_1c0 = (ulong)*local_1d8;
            }
            _dprec = local_1c0;
          }
LAB_06068670:
          buf[0x10] = '\0';
          if (!bVar6) goto LAB_06068684;
          goto LAB_06068860;
        case 0x55:
          bVar5 = true;
        case 0x75:
          fpprec = 10;
          if (bVar6) {
            iVar2 = argp->__gr_offs;
            if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
              local_238 = (ulong *)((long)argp->__gr_top + (long)iVar2);
            }
            else {
              local_238 = (ulong *)argp->__stack;
              argp->__stack = local_238 + 1;
            }
            _flags = *local_238;
          }
          else {
            if (bVar5) {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_250 = (ulong *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_250 = (ulong *)argp->__stack;
                argp->__stack = local_250 + 1;
              }
              local_258 = *local_250;
            }
            else {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_270 = (int *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_270 = (int *)argp->__stack;
                argp->__stack = local_270 + 2;
              }
              local_258 = (ulong)*local_270;
            }
            _dprec = local_258;
          }
          goto LAB_06068670;
        case 0x58:
          buf._8_8_ = s_0123456789ABCDEF_0011de94;
        case 0x78:
          fpprec = 0x10;
          if (!bVar6) {
            if (bVar5) {
              iVar2 = argp->__gr_offs;
              if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
                local_2a0 = (ulong *)((long)argp->__gr_top + (long)iVar2);
              }
              else {
                local_2a0 = (ulong *)argp->__stack;
                argp->__stack = local_2a0 + 1;
              }
              local_2a8 = *local_2a0;
            }
            else {
              in_stack_fffffffffffffd4c = argp->__gr_offs;
              if ((in_stack_fffffffffffffd4c < 0) &&
                 (argp->__gr_offs = in_stack_fffffffffffffd4c + 8, in_stack_fffffffffffffd4c + 8 < 1
                 )) {
                in_stack_fffffffffffffd40 =
                     (int *)((long)argp->__gr_top + (long)in_stack_fffffffffffffd4c);
              }
              else {
                in_stack_fffffffffffffd40 = (int *)argp->__stack;
                argp->__stack = in_stack_fffffffffffffd40 + 2;
              }
              local_2a8 = (ulong)*in_stack_fffffffffffffd40;
            }
            _dprec = local_2a8;
            if ((bVar7) && (local_2a8 != 0)) {
              bVar8 = true;
            }
            goto LAB_06068670;
          }
          iVar2 = argp->__gr_offs;
          if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
            local_288 = (ulong *)((long)argp->__gr_top + (long)iVar2);
          }
          else {
            local_288 = (ulong *)argp->__stack;
            argp->__stack = local_288 + 1;
          }
          _flags = *local_288;
          if ((bVar7) && (_flags != 0)) {
            bVar8 = true;
          }
          goto LAB_06068860;
        case 99:
          iVar2 = argp->__gr_offs;
          if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
            local_138 = (undefined4 *)((long)argp->__gr_top + (long)iVar2);
          }
          else {
            local_138 = (undefined4 *)argp->__stack;
            argp->__stack = local_138 + 2;
          }
          _ulonglong = (ulonglong)local_c0;
          local_c0[0] = (undefined)*local_138;
          digs._0_4_ = 1;
          buf[0x10] = '\0';
          goto LAB_0606894c;
        case 0x68:
          pbStack_48 = pbVar1;
          goto LAB_06067ac0;
        case 0x6c:
          goto switchD_06067af8_caseD_6c;
        case 0x70:
          iVar2 = argp->__gr_offs;
          if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
            local_1f0 = (ulong *)((long)argp->__gr_top + (long)iVar2);
          }
          else {
            local_1f0 = (ulong *)argp->__stack;
            argp->__stack = local_1f0 + 1;
          }
          _dprec = *local_1f0;
          fpprec = 0x10;
          if (stack0xffffffffffffff64 == 0) {
            stack0xffffffffffffff64 = 0x12;
          }
          size = size | 0x60;
          bVar8 = true;
          goto LAB_06068670;
        case 0x73:
          iVar2 = argp->__gr_offs;
          if ((iVar2 < 0) && (argp->__gr_offs = iVar2 + 8, iVar2 + 8 < 1)) {
            local_208 = (ulonglong *)((long)argp->__gr_top + (long)iVar2);
          }
          else {
            local_208 = (ulonglong *)argp->__stack;
            argp->__stack = local_208 + 1;
          }
          _ulonglong = *local_208;
          if (_ulonglong == 0) {
            _ulonglong = (ulonglong)s__null__0011ea50;
          }
          sVar10 = strnlen_el3_sram((char *)CONCAT44(in_stack_fffffffffffffd4c,
                                                     in_stack_fffffffffffffd48),
                                    (size_t)in_stack_fffffffffffffd40);
          digs._0_4_ = (int)sVar10;
          buf[0x10] = '\0';
          goto LAB_0606894c;
        }
      }
      else {
        (*pf)(pfd,(int)bVar3);
        tt._0_4_ = (int)tt + 1;
      }
    }
    (*pf)(pfd,0x201);
    pfd_local._4_4_ = (int)tt;
  }
  return pfd_local._4_4_;
switchD_06067af8_caseD_6c:
  bVar5 = !bVar5;
  pbStack_48 = pbVar1;
  if (!bVar5) {
    bVar6 = true;
  }
  goto LAB_06067ac0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06068c38
 * symbol: putchar_el3_sram_hook
 * prototype: void putchar_el3_sram_hook(void * pfd, int ch)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void putchar_el3_sram_hook(void *pfd,int ch)

{
  int in_w1;
  
  if ((in_w1 != 0x200) && (in_w1 != 0x201)) {
    putchar_el3_sram(in_w1);
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06068c84
 * symbol: test_uart
 * prototype: void test_uart(void)
 * body addresses: 300
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: data64 */
/* WARNING: Variable defined which should be unmapped: data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention */

void test_uart(void)

{
  uint64_t *addr64;
  uint64_t data64;
  uint32_t data;
  uint32_t ui;
  
  printf_el3_sram("=======================================================\n");
  printf_el3_sram("Hello MP4/A53!!! - SRAM\n");
  printf_el3_sram("Check CPDDR: %p == 0x%08x\n",&DAT_d0000000,(ulong)_DAT_d0000000);
  printf_el3_sram("Check CPDDR: %p == 0x%016lx\n",&DAT_ec000000,_DAT_ec000000);
  _DAT_ec000000 = 0xfedcba9876543210;
  printf_el3_sram("Check CPDDR: %p == 0x%016lx\n",&DAT_ec000000,0xfedcba9876543210);
  printf_el3_sram("Check G6: %p == 0x%016lx\n",&DAT_88000000,_DAT_88000000);
  _DAT_88000000 = 0x89abcdef01234567;
  printf_el3_sram("Check G6: %p == 0x%016lx\n",&DAT_88000000,0x89abcdef01234567);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06068db0
 * symbol: syshub_init_all
 * prototype: int syshub_init_all(uint64_t * log)
 * body addresses: 692
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: sum */
/* WARNING: Variable defined which should be unmapped: log_local */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int syshub_init_all(uint64_t *log)

{
  uint64_t *puVar1;
  uint64_t data;
  uint64_t *addr64;
  uint32_t *addr32;
  uint64_t in_stack_ffffffffffffffc0;
  uint64_t *in_stack_ffffffffffffffc8;
  uint64_t v;
  uint64_t *log_00;
  uint local_1c;
  uint32_t sum;
  uint32_t ui;
  uint64_t *log_local;
  
  debug_status_step(in_stack_ffffffffffffffc8,in_stack_ffffffffffffffc0);
  log_00 = (uint64_t *)0x0;
  v = 0;
  for (local_1c = 0; local_1c < 0x8000000; local_1c = local_1c + 1) {
  }
  debug_status_step(in_stack_ffffffffffffffc8,in_stack_ffffffffffffffc0);
  debug_status_step(in_stack_ffffffffffffffc8,in_stack_ffffffffffffffc0);
  debug_status_step(in_stack_ffffffffffffffc8,in_stack_ffffffffffffffc0);
  syshub_init(0x22,0x60000000);
  syshub_init(0x27,0xc0000000);
  syshub_init(0x28,0xc0000000);
  syshub_init(0x29,0xc0000000);
  debug_status_set_x3(log_00,v);
  debug_status_set_x4(log_00,v);
  puVar1 = (uint64_t *)(ulong)_DAT_03230278;
  debug_status_set_x5(log_00,v);
  debug_status_step(puVar1,in_stack_ffffffffffffffc0);
  debug_status_step(puVar1,in_stack_ffffffffffffffc0);
  debug_status_step(puVar1,in_stack_ffffffffffffffc0);
  syshub_init(0x30,0x80000000);
  syshub_init(0x31,0xc0000000);
  syshub_init(0x34,0x880000000);
  debug_status_step(puVar1,in_stack_ffffffffffffffc0);
  debug_status_step(puVar1,in_stack_ffffffffffffffc0);
  puVar1 = _DAT_d0000000;
  debug_status_step(_DAT_d0000000,in_stack_ffffffffffffffc0);
  debug_status_set_x3(log_00,v);
  debug_status_step(puVar1,in_stack_ffffffffffffffc0);
  syshub_init(0x35,0x884000000);
  syshub_init(0x36,0x888000000);
  syshub_init(0x37,0x88c000000);
  syshub_init(0x38,0x890000000);
  syshub_init(0x39,0x894000000);
  syshub_init(0x3a,0x898000000);
  syshub_init(0x3b,0x89c000000);
  syshub_init_core(0xd,0xc4000000,0x4000000);
  syshub_init_core(0x20,0x7c000000,0x4000000);
  syshub_init_core(0x21,0x3c000000,0x4000000);
  _DAT_032303c0 = 0x3f;
  _DAT_032303c4 = 0x12;
  _DAT_032303c8 = 0;
  _DAT_032303cc = 0;
  _DAT_032304d0 = 0xffffffff;
  _DAT_032305c8 = 0xc0000003;
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06069064
 * symbol: debug_status_step
 * prototype: void debug_status_step(uint64_t * log, uint64_t v)
 * body addresses: 32
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void debug_status_step(uint64_t *log,uint64_t v)

{
  undefined8 *in_x0;
  undefined8 in_x1;
  
  *in_x0 = in_x1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06069084
 * symbol: syshub_init
 * prototype: void syshub_init(int tlb, uint64_t phy_addr)
 * body addresses: 48
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: tlb_local */

void syshub_init(int tlb,uint64_t phy_addr)

{
  int tlb_local;
  
  syshub_init_core(tlb,phy_addr,0x4000000);
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060690b4
 * symbol: debug_status_set_x3
 * prototype: void debug_status_set_x3(uint64_t * log, uint64_t v)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void debug_status_set_x3(uint64_t *log,uint64_t v)

{
  long in_x0;
  undefined8 in_x1;
  uint8_t *addr;
  
  *(undefined8 *)(in_x0 + 0x28) = in_x1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060690e0
 * symbol: debug_status_set_x4
 * prototype: void debug_status_set_x4(uint64_t * log, uint64_t v)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void debug_status_set_x4(uint64_t *log,uint64_t v)

{
  long in_x0;
  undefined8 in_x1;
  uint8_t *addr;
  
  *(undefined8 *)(in_x0 + 0x30) = in_x1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606910c
 * symbol: debug_status_set_x5
 * prototype: void debug_status_set_x5(uint64_t * log, uint64_t v)
 * body addresses: 44
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

void debug_status_set_x5(uint64_t *log,uint64_t v)

{
  long in_x0;
  undefined8 in_x1;
  uint8_t *addr;
  
  *(undefined8 *)(in_x0 + 0x38) = in_x1;
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06069138
 * symbol: syshub_init_core
 * prototype: void syshub_init_core(int tlb, uint64_t phy_addr, uint32_t seg_size)
 * body addresses: 760
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: phy_addr_local */
/* WARNING: Variable defined which should be unmapped: tlb_local */

void syshub_init_core(int tlb,uint64_t phy_addr,uint32_t seg_size)

{
  uint uVar1;
  uint32_t *puVar2;
  uint32_t *puVar3;
  uint32_t *puVar4;
  uint32_t *puVar5;
  uint32_t *puVar6;
  uint32_t *puVar7;
  uint uVar8;
  uint32_t *dst_attr1;
  uint32_t *dst_sub;
  uint32_t *dst_tlb3;
  uint32_t in_stack_ffffffffffffff6c;
  uint32_t *dst_tlb2;
  uint32_t *dst_tlb1;
  uint32_t *dst_tlb0;
  uint32_t offset;
  uint32_t base;
  uint32_t tlb1;
  int tlboff;
  uint32_t soc_addr;
  uint32_t seg_size_local;
  uint64_t phy_addr_local;
  int tlb_local;
  
  if (seg_size == 0x20000) {
    dst_tlb0._0_4_ = 0;
  }
  else if (seg_size == 0x40000) {
    dst_tlb0._0_4_ = 2;
  }
  else if (seg_size == 0x80000) {
    dst_tlb0._0_4_ = 4;
  }
  else if (seg_size == 0x100000) {
    dst_tlb0._0_4_ = 6;
  }
  else if (seg_size == 0x200000) {
    dst_tlb0._0_4_ = 8;
  }
  else if (seg_size == 0x400000) {
    dst_tlb0._0_4_ = 10;
  }
  else if (seg_size == 0x800000) {
    dst_tlb0._0_4_ = 0xc;
  }
  else if (seg_size == 0x1000000) {
    dst_tlb0._0_4_ = 0xe;
  }
  else if (seg_size == 0x2000000) {
    dst_tlb0._0_4_ = 0x10;
  }
  else {
    in_stack_ffffffffffffff6c = seg_size + 0xfc000000;
    if (in_stack_ffffffffffffff6c == 0) {
      dst_tlb0._0_4_ = 0x12;
    }
    else {
      printf_el3_sram("Unsupport seg_size 0x%08x\n",(ulong)seg_size);
      dst_tlb0._0_4_ = 0x12;
    }
  }
  uVar8 = (uint)phy_addr & 0xfc000000;
  uVar1 = (uint)phy_addr - uVar8;
  if (uVar1 != 0) {
    dst_tlb0._0_4_ = (uint)dst_tlb0 | (uVar1 >> 0x11) << 5;
    printf_el3_sram("tlb=%d, 0x%08x, offset=0x%08x, tlb1=0x%08x\n",(ulong)(uint)tlb,(ulong)uVar8,
                    (ulong)uVar1,(ulong)(uint)dst_tlb0);
  }
  puVar2 = addr32_to_puint32(in_stack_ffffffffffffff6c);
  puVar3 = addr32_to_puint32(in_stack_ffffffffffffff6c);
  puVar4 = addr32_to_puint32(in_stack_ffffffffffffff6c);
  puVar5 = addr32_to_puint32(in_stack_ffffffffffffff6c);
  puVar6 = addr32_to_puint32(in_stack_ffffffffffffff6c);
  puVar7 = addr32_to_puint32(in_stack_ffffffffffffff6c);
  *puVar2 = (uint32_t)(phy_addr >> 0x1a);
  *puVar3 = (uint)dst_tlb0;
  *puVar4 = 4;
  *puVar5 = 4;
  *puVar6 = 0xffffffff;
  if (tlb != 0x3e) {
    *puVar7 = 0xc1800003;
  }
  return;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06069430
 * symbol: el3_sram_boot
 * prototype: int el3_sram_boot(uint64_t * log)
 * body addresses: 448
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: pa32 */
/* WARNING: Variable defined which should be unmapped: log_local */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int el3_sram_boot(uint64_t *log)

{
  uint32_t *pa32;
  uint64_t *log_local;
  
  syshub_init_all(log);
  test_uart();
  printf_el3_sram("Install Image from SRAM to G6\n");
  printf_el3_sram("__g6_begin = %p [0x%08x]\n",0x100000,0x10000);
  printf_el3_sram("__g6_end   = %p\n",&__page_table_ext_core1_end);
  printf_el3_sram("mmMP4_C2PMSG_0:  %p = 0x%08x\n",&DAT_03010500,(ulong)_DAT_03010500);
  printf_el3_sram("mmDVM_MAILBOX_0: %p = 0x%08x\n",&DAT_030c0000,(ulong)_DAT_030c0000);
  printf_el3_sram("mmDVM_MAILBOX_1: %p = 0x%08x\n",&DAT_030c1000,(ulong)_DAT_030c1000);
  printf_el3_sram("mmDVM_MAILBOX_2: %p = 0x%08x\n",&DAT_030c2000,(ulong)_DAT_030c2000);
  _DAT_03200900 = 0xffffffff;
  _DAT_03200904 = 0xffffffff;
  _DAT_03010500 = 0x77777777;
  do {
  } while (_DAT_03010504 == 0);
  printf_el3_sram("mmMP4_C2PMSG_1:  %p = 0x%08x\n",&DAT_03010504,(ulong)_DAT_03010504);
  printf_el3_sram("<-0\n");
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060695f0
 * symbol: el3_sram_boot2
 * prototype: int el3_sram_boot2(int64_t * log)
 * body addresses: 76
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int el3_sram_boot2(int64_t *log)

{
  uint64_t *in_x0;
  uint32_t in_w2;
  
  printf_el3_sram("el3_sram_boot2 = %p\n",el3_sram_boot2);
  el3_boot(in_x0,(printf_func_t)in_x0,in_w2);
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x0606963c
 * symbol: el3_sram_serror
 * prototype: int el3_sram_serror(uint64_t * log)
 * body addresses: 804
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Variable defined which should be unmapped: data32 */
/* WARNING: Variable defined which should be unmapped: log_local */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int el3_sram_serror(uint64_t *log)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  uint64_t in_stack_ffffffffffffff80;
  undefined4 in_stack_ffffffffffffff88;
  undefined4 in_stack_ffffffffffffff8c;
  undefined4 in_stack_ffffffffffffff90;
  undefined4 in_stack_ffffffffffffff94;
  undefined4 in_stack_ffffffffffffff98;
  undefined4 in_stack_ffffffffffffff9c;
  mp4_debug_status_t *status;
  uint32_t data32;
  uint64_t *log_local;
  
  printf_el3_sram("-------------------------------------------------------\n");
  printf_el3_sram("Trap handler on SRAM\n");
  printf_el3_sram("STEP                    = 0x%016lx\n",*log);
  printf_el3_sram("VECTOR                  = 0x%016lx\n",log[1]);
  printf_el3_sram("X0                  \t = 0x%016lx\n",log[2]);
  printf_el3_sram("X1                      = 0x%016lx\n",log[3]);
  printf_el3_sram("X2                  \t = 0x%016lx\n",log[4]);
  printf_el3_sram("X3                      = 0x%016lx\n",log[5]);
  printf_el3_sram("X4                  \t = 0x%016lx\n",log[6]);
  printf_el3_sram("X5                      = 0x%016lx\n",log[7]);
  printf_el3_sram("SP                      = 0x%016lx\n",log[0x21]);
  printf_el3_sram("ESR_EL3                 = 0x%016lx\n",log[0x22]);
  printf_el3_sram("ELR_EL3                 = 0x%016lx\n",log[0x23]);
  printf_el3_sram("FAR_EL3                 = 0x%016lx\n",log[0x24]);
  debug_status_step((uint64_t *)CONCAT44(in_stack_ffffffffffffff8c,in_stack_ffffffffffffff88),
                    in_stack_ffffffffffffff80);
  uVar1 = _DAT_032305d0;
  debug_status_set_x3((uint64_t *)CONCAT44(in_stack_ffffffffffffff9c,in_stack_ffffffffffffff98),
                      CONCAT44(in_stack_ffffffffffffff94,in_stack_ffffffffffffff90));
  iVar4 = printf_el3_sram("mmMP4_SYSHUB_INT_STATUS = 0x%08x\n",(ulong)uVar1);
  uVar3 = _DAT_032305e0;
  uVar2 = _DAT_032305d4;
  if ((uVar1 & 1) == 0) {
    if ((uVar1 >> 1 & 1) == 0) {
      debug_status_set_x4((uint64_t *)CONCAT44(iVar4,in_stack_ffffffffffffff98),
                          CONCAT44(in_stack_ffffffffffffff94,in_stack_ffffffffffffff90));
      debug_status_step((uint64_t *)CONCAT44(in_stack_ffffffffffffff8c,in_stack_ffffffffffffff88),
                        in_stack_ffffffffffffff80);
    }
    else {
      debug_status_set_x4((uint64_t *)CONCAT44(iVar4,in_stack_ffffffffffffff98),
                          CONCAT44(in_stack_ffffffffffffff94,in_stack_ffffffffffffff90));
      iVar5 = printf_el3_sram("mmMP4_SYSHUB_WR_INT_ADDR  = 0x%08x\n",(ulong)uVar2);
      iVar6 = printf_el3_sram("mmMP4_SYSHUB_WR_INT_OTHER = 0x%08x\n",(ulong)_DAT_032305dc);
      debug_status_set_x5((uint64_t *)CONCAT44(iVar4,in_stack_ffffffffffffff98),
                          CONCAT44(in_stack_ffffffffffffff94,iVar5));
      debug_status_step((uint64_t *)CONCAT44(iVar6,in_stack_ffffffffffffff88),
                        in_stack_ffffffffffffff80);
    }
  }
  else {
    debug_status_set_x4((uint64_t *)CONCAT44(iVar4,in_stack_ffffffffffffff98),
                        CONCAT44(in_stack_ffffffffffffff94,in_stack_ffffffffffffff90));
    iVar5 = printf_el3_sram("mmMP4_SYSHUB_RD_INT_ADDR  = 0x%08x\n",(ulong)uVar3);
    uVar1 = _DAT_032305e4;
    debug_status_set_x5((uint64_t *)CONCAT44(iVar4,iVar5),
                        CONCAT44(in_stack_ffffffffffffff94,in_stack_ffffffffffffff90));
    printf_el3_sram("mmMP4_SYSHUB_RD_INT_OTHER = 0x%08x\n",(ulong)uVar1);
    debug_status_step((uint64_t *)CONCAT44(in_stack_ffffffffffffff8c,in_stack_ffffffffffffff88),
                      in_stack_ffffffffffffff80);
  }
  return 0;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x06069960
 * symbol: sram_sceMp4LookCtypeTable
 * prototype: int sram_sceMp4LookCtypeTable(uint c)
 * body addresses: 72
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

int sram_sceMp4LookCtypeTable(uint c)

{
  uint in_w0;
  uint local_4;
  
  if (in_w0 < 0x80) {
    local_4 = (uint)"         \b\b\b\b\b                  \x18\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x04\x04\x04\x04\x04\x04\x04\x04\x04\x04\x10\x10\x10\x10\x10\x10\x10AAAAAA\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x10\x10\x10\x10\x10\x10BBBBBB\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x02\x10\x10\x10\x10 "
                    [in_w0];
  }
  else {
    local_4 = 0;
  }
  return local_4;
}



/*
 * A53-RE recovery artifact -- generated by Ghidra.
 * entry: 0x060699a8
 * symbol: addr32_to_puint32
 * prototype: uint32_t * addr32_to_puint32(uint32_t addr)
 * body addresses: 20
 * This text is semantic pseudocode, not yet canonical compilable source.
 */


/* WARNING: Unknown calling convention */

uint32_t * addr32_to_puint32(uint32_t addr)

{
  uint in_w0;
  
  return (uint32_t *)(ulong)in_w0;
}


