// Exports one self-contained recovery artifact per function after Ghidra's analysis.
//@category A53

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Iterator;

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.decompiler.DecompiledFunction;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.mem.Memory;

public class ExportA53 extends GhidraScript {

    private static String json(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("\\", "\\\\").replace("\"", "\\\"")
                    .replace("\n", "\\n").replace("\r", "\\r");
    }

    private static String safeFileName(String value) {
        return value.replaceAll("[^A-Za-z0-9_.-]", "_");
    }

    private String firstBytes(Function function, int maxBytes) {
        try {
            Address entry = function.getEntryPoint();
            long available = function.getBody().getNumAddresses();
            int length = (int) Math.min((long) maxBytes, available);
            if (length <= 0) {
                return "";
            }
            Memory memory = currentProgram.getMemory();
            byte[] bytes = new byte[length];
            int read = memory.getBytes(entry, bytes);
            StringBuilder result = new StringBuilder(read * 2);
            for (int i = 0; i < read; ++i) {
                result.append(String.format("%02x", bytes[i] & 0xff));
            }
            return result.toString();
        }
        catch (Exception exception) {
            return "";
        }
    }

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length != 1) {
            throw new IllegalArgumentException("Usage: ExportA53.java <output-directory>");
        }

        Path root = new File(args[0]).toPath();
        Path functionsDirectory = root.resolve("functions");
        Files.createDirectories(functionsDirectory);

        DecompInterface decompiler = new DecompInterface();
        DecompileOptions options = new DecompileOptions();
        options.grabFromProgram(currentProgram);
        decompiler.setOptions(options);
        decompiler.toggleCCode(true);
        decompiler.toggleSyntaxTree(false);
        decompiler.setSimplificationStyle("decompile");
        if (!decompiler.openProgram(currentProgram)) {
            throw new IOException("Ghidra could not initialize the decompiler");
        }

        FunctionManager manager = currentProgram.getFunctionManager();
        Iterator<Function> functions = manager.getFunctions(true);
        int exported = 0;
        int failures = 0;

        try (BufferedWriter manifest = Files.newBufferedWriter(root.resolve("functions.jsonl"),
                StandardCharsets.UTF_8)) {
            while (functions.hasNext() && !monitor.isCancelled()) {
                Function function = functions.next();
                Address entry = function.getEntryPoint();
                String address = entry.toString();
                String name = function.getName();
                String filename = String.format("%08d_0x%s_%s.c", exported, address,
                        safeFileName(name));
                Path destination = functionsDirectory.resolve(filename);

                String c = null;
                String error = "";
                try {
                    DecompileResults result = decompiler.decompileFunction(function, 120, monitor);
                    DecompiledFunction decompiled = result.getDecompiledFunction();
                    if (result.decompileCompleted() && decompiled != null) {
                        c = decompiled.getC();
                    }
                    else {
                        error = result.getErrorMessage();
                    }
                }
                catch (Exception exception) {
                    error = exception.toString();
                }

                if (c == null) {
                    failures++;
                    c = "/* DECOMPILATION FAILED: " + error.replace("*/", "* /") + " */\n";
                }

                String header = "/*\n"
                    + " * A53-RE recovery artifact -- generated by Ghidra.\n"
                    + " * entry: 0x" + address + "\n"
                    + " * symbol: " + name + "\n"
                    + " * prototype: " + function.getPrototypeString(false, false) + "\n"
                    + " * body addresses: " + function.getBody().getNumAddresses() + "\n"
                    + " * This text is semantic pseudocode, not yet canonical compilable source.\n"
                    + " */\n\n";
                Files.write(destination, (header + c + "\n").getBytes(StandardCharsets.UTF_8));

                manifest.write("{\"entry\":\"0x" + json(address) + "\",\"name\":\""
                    + json(name) + "\",\"prototype\":\""
                    + json(function.getPrototypeString(false, false)) + "\",\"addresses\":"
                    + function.getBody().getNumAddresses() + ",\"bytes_prefix\":\""
                    + firstBytes(function, 32) + "\",\"file\":\"functions/"
                    + json(filename) + "\",\"decompiled\":" + (error.isEmpty() ? "true" : "false")
                    + ",\"error\":\"" + json(error) + "\"}\n");
                exported++;
                if (exported % 100 == 0) {
                    println("Exported " + exported + " functions");
                }
            }
        }
        finally {
            decompiler.dispose();
        }
        println("A53 export complete: " + exported + " functions, " + failures + " failures");
    }
}
